// Completion entries for crystal.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  { label: 'def', type: 'keyword', info: 'Define method' },
  { label: 'end', type: 'keyword', info: 'End block' },
  { label: 'class', type: 'keyword', info: 'Class' },
  { label: 'module', type: 'keyword', info: 'Module' },
  { label: 'struct', type: 'keyword', info: 'Struct (value type)' },
  { label: 'enum', type: 'keyword', info: 'Enum' },
  { label: 'abstract', type: 'keyword', info: 'Abstract class' },
  { label: 'private', type: 'keyword', info: 'Private visibility' },
  { label: 'protected', type: 'keyword', info: 'Protected' },
  { label: 'public', type: 'keyword', info: 'Public' },
  { label: 'include', type: 'keyword', info: 'Include module' },
  { label: 'extend', type: 'keyword', info: 'Extend module' },
  { label: 'require', type: 'keyword', info: 'Require file' },
  { label: 'macro', type: 'keyword', info: 'Macro' },
  { label: 'annotation', type: 'keyword', info: 'Annotation' },
  { label: 'lib', type: 'keyword', info: 'C library bind' },
  { label: 'fun', type: 'keyword', info: 'C function' },
  { label: 'if', type: 'keyword', info: 'If' },
  { label: 'elsif', type: 'keyword', info: 'Else if' },
  { label: 'else', type: 'keyword', info: 'Else' },
  { label: 'unless', type: 'keyword', info: 'Unless' },
  { label: 'case', type: 'keyword', info: 'Case' },
  { label: 'when', type: 'keyword', info: 'When' },
  { label: 'while', type: 'keyword', info: 'While' },
  { label: 'until', type: 'keyword', info: 'Until' },
  { label: 'for', type: 'keyword', info: 'For' },
  { label: 'in', type: 'keyword', info: 'In iteration' },
  { label: 'do', type: 'keyword', info: 'Do block' },
  { label: 'begin', type: 'keyword', info: 'Begin block' },
  { label: 'rescue', type: 'keyword', info: 'Rescue' },
  { label: 'ensure', type: 'keyword', info: 'Ensure' },
  { label: 'raise', type: 'keyword', info: 'Raise' },
  { label: 'yield', type: 'keyword', info: 'Yield' },
  { label: 'next', type: 'keyword', info: 'Next' },
  { label: 'break', type: 'keyword', info: 'Break' },
  { label: 'return', type: 'keyword', info: 'Return' },
  { label: 'true', type: 'keyword', info: 'True' },
  { label: 'false', type: 'keyword', info: 'False' },
  { label: 'nil', type: 'keyword', info: 'Nil' },
  { label: 'self', type: 'keyword', info: 'Self' },
  { label: 'super', type: 'keyword', info: 'Super' },
  { label: 'new', type: 'keyword', info: 'New instance' },
  { label: 'as', type: 'keyword', info: 'Type cast' },
  { label: 'is_a?', type: 'method', info: 'Type check' },
  { label: 'nil?', type: 'method', info: 'Is nil?' },
  { label: 'responds_to?', type: 'method', info: 'Responds to?' },
  { label: 'typeof', type: 'keyword', info: 'Type of expr' },
  { label: 'sizeof', type: 'keyword', info: 'Size of type' },
  { label: 'pointerof', type: 'keyword', info: 'Pointer of expr' },
  { label: 'instance_sizeof', type: 'keyword', info: 'Instance size' },
  // Types
  { label: 'Int', type: 'type', info: 'Integer base' },
  { label: 'Int32', type: 'type', info: '32-bit int' },
  { label: 'Int64', type: 'type', info: '64-bit int' },
  { label: 'UInt32', type: 'type', info: '32-bit uint' },
  { label: 'UInt64', type: 'type', info: '64-bit uint' },
  { label: 'Float32', type: 'type', info: '32-bit float' },
  { label: 'Float64', type: 'type', info: '64-bit float' },
  { label: 'Bool', type: 'type', info: 'Boolean' },
  { label: 'Char', type: 'type', info: 'Character' },
  { label: 'String', type: 'type', info: 'String' },
  { label: 'Symbol', type: 'type', info: 'Symbol' },
  { label: 'Array', type: 'type', info: 'Array' },
  { label: 'Hash', type: 'type', info: 'Hash' },
  { label: 'Set', type: 'type', info: 'Set' },
  { label: 'Range', type: 'type', info: 'Range' },
  { label: 'Tuple', type: 'type', info: 'Tuple' },
  { label: 'NamedTuple', type: 'type', info: 'Named tuple' },
  { label: 'Nil', type: 'type', info: 'Nil type' },
  { label: 'Object', type: 'type', info: 'Object base' },
  { label: 'Pointer', type: 'type', info: 'Pointer' },
  { label: 'Proc', type: 'type', info: 'Proc' },
  { label: 'Regex', type: 'type', info: 'Regex' },
  { label: 'Time', type: 'type', info: 'Time' },
  { label: 'URI', type: 'type', info: 'URI' },
  // Top-level
  { label: 'puts', type: 'function', info: 'Print line' },
  { label: 'print', type: 'function', info: 'Print' },
  { label: 'p', type: 'function', info: 'Inspect print' },
  { label: 'pp', type: 'function', info: 'Pretty print' },
  { label: 'gets', type: 'function', info: 'Read line' },
  { label: 'read_line', type: 'function', info: 'Read line' },
  { label: 'exit', type: 'function', info: 'Exit program' },
  { label: 'abort', type: 'function', info: 'Abort program' },
  { label: 'at_exit', type: 'function', info: 'Exit handler' },
  { label: 'spawn', type: 'function', info: 'Spawn fiber' },
  { label: 'sleep', type: 'function', info: 'Sleep seconds' },
  { label: 'rand', type: 'function', info: 'Random' },
  { label: 'ARGF', type: 'variable', info: 'Argument file' },
  { label: 'ARGV', type: 'variable', info: 'Argument vector' },
  { label: 'STDIN', type: 'variable', info: 'Standard input' },
  { label: 'STDOUT', type: 'variable', info: 'Standard output' },
  { label: 'STDERR', type: 'variable', info: 'Standard error' },
  { label: 'ENV', type: 'variable', info: 'Environment' },
  // Common methods (shared with Ruby)
  { label: 'each', type: 'method', info: 'Iterate' },
  { label: 'map', type: 'method', info: 'Map' },
  { label: 'select', type: 'method', info: 'Select/filter' },
  { label: 'reject', type: 'method', info: 'Reject/anti-filter' },
  { label: 'reduce', type: 'method', info: 'Reduce' },
  { label: 'find', type: 'method', info: 'Find first' },
  { label: 'sort', type: 'method', info: 'Sort' },
  { label: 'sort_by', type: 'method', info: 'Sort by block' },
  { label: 'group_by', type: 'method', info: 'Group by block' },
  { label: 'size', type: 'method', info: 'Size' },
  { label: 'empty?', type: 'method', info: 'Is empty?' },
  { label: 'includes?', type: 'method', info: 'Includes element' },
];
