// Completion entries for elixir.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  // Keywords
  { label: 'def', type: 'keyword', info: 'Define function' },
  { label: 'defp', type: 'keyword', info: 'Private function' },
  { label: 'defmodule', type: 'keyword', info: 'Define module' },
  { label: 'defmacro', type: 'keyword', info: 'Define macro' },
  { label: 'defmacrop', type: 'keyword', info: 'Private macro' },
  { label: 'defprotocol', type: 'keyword', info: 'Define protocol' },
  { label: 'defimpl', type: 'keyword', info: 'Implement protocol' },
  { label: 'defstruct', type: 'keyword', info: 'Define struct' },
  { label: 'defexception', type: 'keyword', info: 'Define exception' },
  { label: 'defdelegate', type: 'keyword', info: 'Delegate function' },
  { label: 'defguard', type: 'keyword', info: 'Define guard' },
  { label: 'defguardp', type: 'keyword', info: 'Private guard' },
  { label: 'do', type: 'keyword', info: 'Do block' },
  { label: 'end', type: 'keyword', info: 'End block' },
  { label: 'fn', type: 'keyword', info: 'Anonymous function' },
  { label: 'if', type: 'keyword', info: 'If expression' },
  { label: 'unless', type: 'keyword', info: 'Unless expression' },
  { label: 'case', type: 'keyword', info: 'Case expression' },
  { label: 'cond', type: 'keyword', info: 'Cond expression' },
  { label: 'with', type: 'keyword', info: 'With pipeline' },
  { label: 'for', type: 'keyword', info: 'Comprehension' },
  { label: 'try', type: 'keyword', info: 'Try block' },
  { label: 'rescue', type: 'keyword', info: 'Rescue exception' },
  { label: 'catch', type: 'keyword', info: 'Catch throw/exit' },
  { label: 'after', type: 'keyword', info: 'After clause' },
  { label: 'else', type: 'keyword', info: 'Else branch' },
  { label: 'raise', type: 'keyword', info: 'Raise exception' },
  { label: 'throw', type: 'keyword', info: 'Throw value' },
  { label: 'receive', type: 'keyword', info: 'Receive message' },
  { label: 'send', type: 'function', info: 'Send message' },
  { label: 'when', type: 'keyword', info: 'Guard clause' },
  { label: 'quote', type: 'keyword', info: 'Quote AST' },
  { label: 'unquote', type: 'keyword', info: 'Unquote AST' },
  { label: 'unquote_splicing', type: 'keyword', info: 'Unquote splicing' },
  { label: 'alias', type: 'keyword', info: 'Alias module' },
  { label: 'require', type: 'keyword', info: 'Require module' },
  { label: 'import', type: 'keyword', info: 'Import functions' },
  { label: 'use', type: 'keyword', info: 'Use behavior' },
  { label: 'true', type: 'constant', info: 'Boolean true' },
  { label: 'false', type: 'constant', info: 'Boolean false' },
  { label: 'nil', type: 'constant', info: 'Nil value' },
  { label: 'and', type: 'keyword', info: 'Logical AND' },
  { label: 'or', type: 'keyword', info: 'Logical OR' },
  { label: 'not', type: 'keyword', info: 'Logical NOT' },
  { label: '__MODULE__', type: 'constant', info: 'Current module' },
  { label: '__DIR__', type: 'constant', info: 'Current directory' },
  { label: '__ENV__', type: 'constant', info: 'Current env' },
  { label: '__CALLER__', type: 'constant', info: 'Caller env' },
  { label: '__STACKTRACE__', type: 'constant', info: 'Current stack' },
  // Standard modules
  { label: 'IO', type: 'module', info: 'I/O module' },
  { label: 'IO.puts', type: 'function', info: 'Print line' },
  { label: 'IO.inspect', type: 'function', info: 'Debug print' },
  { label: 'IO.write', type: 'function', info: 'Write string' },
  { label: 'IO.gets', type: 'function', info: 'Read line' },
  { label: 'IO.read', type: 'function', info: 'Read bytes' },
  { label: 'Kernel', type: 'module', info: 'Kernel module' },
  { label: 'Enum', type: 'module', info: 'Enumerable utils' },
  { label: 'Enum.map', type: 'function', info: 'Map enum' },
  { label: 'Enum.filter', type: 'function', info: 'Filter enum' },
  { label: 'Enum.reduce', type: 'function', info: 'Reduce enum' },
  { label: 'Enum.each', type: 'function', info: 'Iterate enum' },
  { label: 'Enum.find', type: 'function', info: 'Find first' },
  { label: 'Enum.count', type: 'function', info: 'Count enum' },
  { label: 'Enum.sum', type: 'function', info: 'Sum enum' },
  { label: 'Enum.sort', type: 'function', info: 'Sort enum' },
  { label: 'Enum.sort_by', type: 'function', info: 'Sort by fn' },
  { label: 'Enum.reverse', type: 'function', info: 'Reverse enum' },
  { label: 'Enum.take', type: 'function', info: 'Take first N' },
  { label: 'Enum.drop', type: 'function', info: 'Drop first N' },
  { label: 'Enum.chunk_every', type: 'function', info: 'Chunk of N' },
  { label: 'Enum.group_by', type: 'function', info: 'Group by key' },
  { label: 'Enum.flat_map', type: 'function', info: 'Flat map' },
  { label: 'Enum.uniq', type: 'function', info: 'Unique values' },
  { label: 'Enum.uniq_by', type: 'function', info: 'Unique by key' },
  { label: 'Enum.zip', type: 'function', info: 'Zip enums' },
  { label: 'Enum.unzip', type: 'function', info: 'Unzip pairs' },
  { label: 'Enum.all?', type: 'function', info: 'All match?' },
  { label: 'Enum.any?', type: 'function', info: 'Any match?' },
  { label: 'Enum.empty?', type: 'function', info: 'Is empty?' },
  { label: 'Enum.member?', type: 'function', info: 'Has member?' },
  { label: 'Enum.min', type: 'function', info: 'Minimum' },
  { label: 'Enum.max', type: 'function', info: 'Maximum' },
  { label: 'Enum.min_by', type: 'function', info: 'Min by key' },
  { label: 'Enum.max_by', type: 'function', info: 'Max by key' },
  { label: 'Enum.into', type: 'function', info: 'Collect into' },
  { label: 'Enum.to_list', type: 'function', info: 'Convert to list' },
  { label: 'Enum.at', type: 'function', info: 'Element at idx' },
  { label: 'Enum.random', type: 'function', info: 'Random element' },
  { label: 'Stream', type: 'module', info: 'Lazy enumerable' },
  { label: 'Stream.map', type: 'function', info: 'Lazy map' },
  { label: 'Stream.filter', type: 'function', info: 'Lazy filter' },
  { label: 'Stream.take', type: 'function', info: 'Lazy take' },
  { label: 'Stream.drop', type: 'function', info: 'Lazy drop' },
  { label: 'Stream.chunk_every', type: 'function', info: 'Lazy chunk' },
  { label: 'Stream.iterate', type: 'function', info: 'Iterate stream' },
  { label: 'Stream.cycle', type: 'function', info: 'Cycle stream' },
  { label: 'Stream.repeatedly', type: 'function', info: 'Repeat call' },
  // String / Atom / Map
  { label: 'String', type: 'module', info: 'String module' },
  { label: 'String.length', type: 'function', info: 'Length' },
  { label: 'String.split', type: 'function', info: 'Split string' },
  { label: 'String.replace', type: 'function', info: 'Replace' },
  { label: 'String.upcase', type: 'function', info: 'Uppercase' },
  { label: 'String.downcase', type: 'function', info: 'Lowercase' },
  { label: 'String.capitalize', type: 'function', info: 'Capitalize' },
  { label: 'String.trim', type: 'function', info: 'Trim whitespace' },
  { label: 'String.contains?', type: 'function', info: 'Contains?' },
  { label: 'String.starts_with?', type: 'function', info: 'Starts with?' },
  { label: 'String.ends_with?', type: 'function', info: 'Ends with?' },
  { label: 'String.to_atom', type: 'function', info: 'To atom' },
  { label: 'String.to_integer', type: 'function', info: 'To integer' },
  { label: 'String.to_float', type: 'function', info: 'To float' },
  { label: 'String.slice', type: 'function', info: 'Substring' },
  { label: 'Integer', type: 'module', info: 'Integer module' },
  { label: 'Integer.parse', type: 'function', info: 'Parse int' },
  { label: 'Integer.to_string', type: 'function', info: 'Int to string' },
  { label: 'Float', type: 'module', info: 'Float module' },
  { label: 'Atom', type: 'module', info: 'Atom module' },
  { label: 'Atom.to_string', type: 'function', info: 'Atom to string' },
  { label: 'Map', type: 'module', info: 'Map module' },
  { label: 'Map.new', type: 'function', info: 'New map' },
  { label: 'Map.get', type: 'function', info: 'Get value' },
  { label: 'Map.put', type: 'function', info: 'Put value' },
  { label: 'Map.delete', type: 'function', info: 'Delete key' },
  { label: 'Map.has_key?', type: 'function', info: 'Has key?' },
  { label: 'Map.keys', type: 'function', info: 'Map keys' },
  { label: 'Map.values', type: 'function', info: 'Map values' },
  { label: 'Map.merge', type: 'function', info: 'Merge maps' },
  { label: 'Map.update', type: 'function', info: 'Update value' },
  { label: 'Map.update!', type: 'function', info: 'Update (strict)' },
  { label: 'Map.from_struct', type: 'function', info: 'Struct to map' },
  { label: 'Keyword', type: 'module', info: 'Keyword list utils' },
  { label: 'List', type: 'module', info: 'List module' },
  { label: 'List.first', type: 'function', info: 'First element' },
  { label: 'List.last', type: 'function', info: 'Last element' },
  { label: 'List.flatten', type: 'function', info: 'Flatten list' },
  { label: 'List.foldl', type: 'function', info: 'Fold left' },
  { label: 'List.foldr', type: 'function', info: 'Fold right' },
  { label: 'Tuple', type: 'module', info: 'Tuple module' },
  { label: 'Tuple.to_list', type: 'function', info: 'Tuple to list' },
  { label: 'Tuple.append', type: 'function', info: 'Append tuple' },
  // Process / OTP
  { label: 'Process', type: 'module', info: 'Process module' },
  { label: 'Process.sleep', type: 'function', info: 'Sleep process' },
  { label: 'Process.exit', type: 'function', info: 'Exit process' },
  { label: 'Process.alive?', type: 'function', info: 'Is alive?' },
  { label: 'Process.register', type: 'function', info: 'Register pid' },
  { label: 'self', type: 'function', info: 'Current pid' },
  { label: 'spawn', type: 'function', info: 'Spawn process' },
  { label: 'spawn_link', type: 'function', info: 'Spawn linked' },
  { label: 'spawn_monitor', type: 'function', info: 'Spawn monitored' },
  { label: 'GenServer', type: 'module', info: 'Generic server' },
  { label: 'GenServer.start_link', type: 'function', info: 'Start linked' },
  { label: 'GenServer.call', type: 'function', info: 'Sync call' },
  { label: 'GenServer.cast', type: 'function', info: 'Async cast' },
  { label: 'Agent', type: 'module', info: 'State agent' },
  { label: 'Agent.start_link', type: 'function', info: 'Start agent' },
  { label: 'Agent.get', type: 'function', info: 'Get state' },
  { label: 'Agent.update', type: 'function', info: 'Update state' },
  { label: 'Task', type: 'module', info: 'Task module' },
  { label: 'Task.async', type: 'function', info: 'Async task' },
  { label: 'Task.await', type: 'function', info: 'Await task' },
  { label: 'Task.Supervisor', type: 'module', info: 'Task supervisor' },
  { label: 'Supervisor', type: 'module', info: 'Supervisor' },
  { label: 'Application', type: 'module', info: 'Application module' },
  { label: 'Registry', type: 'module', info: 'Registry' },
  // Phoenix (optional common)
  { label: 'Phoenix.Controller', type: 'module', info: 'Phoenix controller' },
  { label: 'Phoenix.LiveView', type: 'module', info: 'LiveView' },
  { label: 'Phoenix.Component', type: 'module', info: 'Phoenix component' },
  { label: 'Plug', type: 'module', info: 'Plug behavior' },
  { label: 'Ecto', type: 'module', info: 'Ecto' },
  { label: 'Ecto.Changeset', type: 'module', info: 'Ecto changeset' },
  { label: 'Ecto.Query', type: 'module', info: 'Ecto query' },
  { label: 'Repo', type: 'module', info: 'Ecto repo' },
  // Operators / pipes
  { label: '|>', type: 'keyword', info: 'Pipe operator' },
  { label: '=~', type: 'keyword', info: 'Regex match' },
  { label: '::', type: 'keyword', info: 'Binary type' },
  { label: '<-', type: 'keyword', info: 'Generator/match' },
  { label: '<<', type: 'keyword', info: 'Binary open' },
  { label: '>>', type: 'keyword', info: 'Binary close' },
  // Phoenix
  { label: 'Phoenix.Endpoint', type: 'module', info: 'Phoenix endpoint' },
  { label: 'Phoenix.Router', type: 'module', info: 'Phoenix router' },
  { label: 'Phoenix.Controller', type: 'module', info: 'Phoenix controller' },
  { label: 'Phoenix.View', type: 'module', info: 'Phoenix view' },
  { label: 'Phoenix.Template', type: 'module', info: 'Phoenix template' },
  { label: 'Phoenix.LiveView', type: 'module', info: 'LiveView' },
  { label: 'Phoenix.LiveComponent', type: 'module', info: 'Live component' },
  { label: 'Phoenix.Component', type: 'module', info: 'Phoenix component' },
  { label: 'Phoenix.Channel', type: 'module', info: 'Channel' },
  { label: 'Phoenix.Socket', type: 'module', info: 'Socket' },
  { label: 'Phoenix.Presence', type: 'module', info: 'Presence' },
  { label: 'Phoenix.PubSub', type: 'module', info: 'PubSub' },
  { label: 'Phoenix.HTML', type: 'module', info: 'Phoenix HTML' },
  { label: 'Phoenix.Token', type: 'module', info: 'Signed tokens' },
  { label: 'Phoenix.Param', type: 'module', info: 'URL param protocol' },
  { label: 'Phoenix.Naming', type: 'module', info: 'Naming helpers' },
  { label: 'Phoenix.VerifiedRoutes', type: 'module', info: 'Verified routes' },
  { label: 'sigil_p', type: 'function', info: 'Path sigil' },
  // Phoenix router macros
  { label: 'pipeline', type: 'macro', info: 'Router pipeline' },
  { label: 'scope', type: 'macro', info: 'Router scope' },
  { label: 'pipe_through', type: 'macro', info: 'Pipe through' },
  { label: 'get', type: 'macro', info: 'GET route' },
  { label: 'post', type: 'macro', info: 'POST route' },
  { label: 'put', type: 'macro', info: 'PUT route' },
  { label: 'patch', type: 'macro', info: 'PATCH route' },
  { label: 'delete', type: 'macro', info: 'DELETE route' },
  { label: 'options', type: 'macro', info: 'OPTIONS route' },
  { label: 'head', type: 'macro', info: 'HEAD route' },
  { label: 'match', type: 'macro', info: 'Match route' },
  { label: 'resources', type: 'macro', info: 'REST resources' },
  { label: 'forward', type: 'macro', info: 'Forward to plug' },
  { label: 'live', type: 'macro', info: 'Live route' },
  { label: 'live_session', type: 'macro', info: 'LV session' },
  // Conn / controller helpers
  { label: 'conn', type: 'variable', info: 'Plug.Conn' },
  { label: 'render', type: 'function', info: 'Render template' },
  { label: 'text', type: 'function', info: 'Send text' },
  { label: 'json', type: 'function', info: 'Send JSON' },
  { label: 'html', type: 'function', info: 'Send HTML' },
  { label: 'redirect', type: 'function', info: 'HTTP redirect' },
  { label: 'put_flash', type: 'function', info: 'Set flash' },
  { label: 'get_flash', type: 'function', info: 'Get flash' },
  { label: 'put_status', type: 'function', info: 'Set status' },
  { label: 'send_resp', type: 'function', info: 'Send response' },
  { label: 'halt', type: 'function', info: 'Halt pipeline' },
  { label: 'assign', type: 'function', info: 'Assign to conn' },
  { label: 'put_session', type: 'function', info: 'Put session' },
  { label: 'get_session', type: 'function', info: 'Get session' },
  { label: 'delete_session', type: 'function', info: 'Del session' },
  { label: 'configure_session', type: 'function', info: 'Config session' },
  { label: 'fetch_query_params', type: 'function', info: 'Fetch params' },
  { label: 'fetch_cookies', type: 'function', info: 'Fetch cookies' },
  { label: 'put_resp_header', type: 'function', info: 'Set resp header' },
  { label: 'get_req_header', type: 'function', info: 'Get req header' },
  { label: 'put_resp_content_type', type: 'function', info: 'Set ctype' },
  { label: 'put_resp_cookie', type: 'function', info: 'Set cookie' },
  { label: 'delete_resp_cookie', type: 'function', info: 'Del cookie' },
  { label: 'send_file', type: 'function', info: 'Send file' },
  { label: 'send_download', type: 'function', info: 'Send download' },
  { label: 'sent_resp', type: 'function', info: 'Get sent body' },
  { label: 'resp', type: 'function', info: 'Set resp' },
  { label: 'action_name', type: 'function', info: 'Action name' },
  { label: 'controller_module', type: 'function', info: 'Controller mod' },
  // Plug
  { label: 'Plug.Conn', type: 'module', info: 'Plug.Conn' },
  { label: 'Plug.Router', type: 'module', info: 'Plug router' },
  { label: 'Plug.Builder', type: 'module', info: 'Plug builder' },
  { label: 'Plug.Parsers', type: 'module', info: 'Plug parsers' },
  { label: 'Plug.Session', type: 'module', info: 'Plug session' },
  { label: 'Plug.Static', type: 'module', info: 'Static files' },
  { label: 'Plug.Logger', type: 'module', info: 'Request logger' },
  { label: 'Plug.RequestId', type: 'module', info: 'Request ID' },
  { label: 'Plug.MethodOverride', type: 'module', info: 'Override method' },
  { label: 'Plug.Head', type: 'module', info: 'HEAD -> GET' },
  { label: 'Plug.SSL', type: 'module', info: 'Force SSL' },
  { label: 'Plug.Debugger', type: 'module', info: 'Debug page' },
  { label: 'Plug.ErrorHandler', type: 'module', info: 'Error handler' },
  { label: 'Plug.Crypto', type: 'module', info: 'Plug crypto' },
  { label: 'Plug.HTML', type: 'module', info: 'HTML helpers' },
  { label: 'Plug.Upload', type: 'module', info: 'Uploaded file' },
  { label: 'plug', type: 'macro', info: 'Declare plug' },
  // LiveView
  { label: 'mount', type: 'function', info: 'LV mount' },
  { label: 'handle_params', type: 'function', info: 'Handle params' },
  { label: 'handle_event', type: 'function', info: 'LV handle event' },
  { label: 'handle_info', type: 'function', info: 'LV handle info' },
  { label: 'handle_call', type: 'function', info: 'LV handle call' },
  { label: 'handle_cast', type: 'function', info: 'LV handle cast' },
  { label: 'push_event', type: 'function', info: 'LV push event' },
  { label: 'push_navigate', type: 'function', info: 'LV push navigate' },
  { label: 'push_patch', type: 'function', info: 'LV push patch' },
  { label: 'push_redirect', type: 'function', info: 'LV push redirect' },
  { label: 'assign_async', type: 'function', info: 'LV assign async' },
  { label: 'stream', type: 'function', info: 'LV stream' },
  { label: 'stream_insert', type: 'function', info: 'LV stream insert' },
  { label: 'stream_delete', type: 'function', info: 'LV stream delete' },
  { label: 'allow_upload', type: 'function', info: 'Allow uploads' },
  { label: 'consume_uploaded_entries', type: 'function', info: 'Consume uploads' },
  { label: 'cancel_upload', type: 'function', info: 'Cancel upload' },
  { label: 'attach_hook', type: 'function', info: 'Attach hook' },
  { label: 'detach_hook', type: 'function', info: 'Detach hook' },
  { label: 'on_mount', type: 'macro', info: 'on_mount hook' },
  { label: 'attr', type: 'macro', info: 'Define attr' },
  { label: 'slot', type: 'macro', info: 'Define slot' },
  { label: 'render_slot', type: 'function', info: 'Render slot' },
  { label: 'put_flash', type: 'function', info: 'Flash message' },
  { label: 'clear_flash', type: 'function', info: 'Clear flash' },
  // Channel
  { label: 'join', type: 'function', info: 'Channel join' },
  { label: 'handle_in', type: 'function', info: 'Channel in' },
  { label: 'handle_out', type: 'function', info: 'Channel out' },
  { label: 'broadcast', type: 'function', info: 'Broadcast msg' },
  { label: 'broadcast_from', type: 'function', info: 'Broadcast from' },
  { label: 'push', type: 'function', info: 'Push to client' },
  { label: 'reply', type: 'function', info: 'Reply to client' },
  { label: 'intercept', type: 'macro', info: 'Intercept events' },
  // Ecto
  { label: 'Ecto.Schema', type: 'module', info: 'Ecto schema' },
  { label: 'Ecto.Changeset', type: 'module', info: 'Ecto changeset' },
  { label: 'Ecto.Query', type: 'module', info: 'Ecto query' },
  { label: 'Ecto.Repo', type: 'module', info: 'Ecto repo' },
  { label: 'Ecto.Multi', type: 'module', info: 'Ecto multi' },
  { label: 'Ecto.Migration', type: 'module', info: 'Migration' },
  { label: 'Ecto.Adapter', type: 'module', info: 'Ecto adapter' },
  { label: 'Ecto.Association', type: 'module', info: 'Association' },
  { label: 'Ecto.Enum', type: 'module', info: 'Ecto enum' },
  { label: 'Ecto.UUID', type: 'module', info: 'UUID type' },
  // Schema macros
  { label: 'schema', type: 'macro', info: 'Schema def' },
  { label: 'field', type: 'macro', info: 'Schema field' },
  { label: 'has_many', type: 'macro', info: 'has_many assoc' },
  { label: 'has_one', type: 'macro', info: 'has_one assoc' },
  { label: 'belongs_to', type: 'macro', info: 'belongs_to' },
  { label: 'many_to_many', type: 'macro', info: 'many_to_many' },
  { label: 'embeds_one', type: 'macro', info: 'Embed one' },
  { label: 'embeds_many', type: 'macro', info: 'Embed many' },
  { label: 'timestamps', type: 'macro', info: 'Timestamps' },
  { label: 'embedded_schema', type: 'macro', info: 'Embedded schema' },
  // Changeset
  { label: 'cast', type: 'function', info: 'Cast params' },
  { label: 'cast_embed', type: 'function', info: 'Cast embed' },
  { label: 'cast_assoc', type: 'function', info: 'Cast assoc' },
  { label: 'validate_required', type: 'function', info: 'Required fields' },
  { label: 'validate_format', type: 'function', info: 'Format regex' },
  { label: 'validate_length', type: 'function', info: 'Length check' },
  { label: 'validate_inclusion', type: 'function', info: 'In list' },
  { label: 'validate_exclusion', type: 'function', info: 'Not in list' },
  { label: 'validate_number', type: 'function', info: 'Num range' },
  { label: 'validate_change', type: 'function', info: 'Custom validate' },
  { label: 'validate_confirmation', type: 'function', info: 'Confirm field' },
  { label: 'validate_acceptance', type: 'function', info: 'Acceptance' },
  { label: 'validate_subset', type: 'function', info: 'Subset check' },
  { label: 'unique_constraint', type: 'function', info: 'Unique index' },
  { label: 'foreign_key_constraint', type: 'function', info: 'FK constraint' },
  { label: 'check_constraint', type: 'function', info: 'Check constraint' },
  { label: 'assoc_constraint', type: 'function', info: 'Assoc exists' },
  { label: 'no_assoc_constraint', type: 'function', info: 'No assoc' },
  { label: 'exclusion_constraint', type: 'function', info: 'Exclusion' },
  { label: 'put_change', type: 'function', info: 'Put change' },
  { label: 'put_assoc', type: 'function', info: 'Put assoc' },
  { label: 'put_embed', type: 'function', info: 'Put embed' },
  { label: 'get_change', type: 'function', info: 'Get change' },
  { label: 'get_field', type: 'function', info: 'Get field' },
  { label: 'fetch_change', type: 'function', info: 'Fetch change' },
  { label: 'fetch_field', type: 'function', info: 'Fetch field' },
  { label: 'delete_change', type: 'function', info: 'Delete change' },
  { label: 'apply_changes', type: 'function', info: 'Apply changes' },
  { label: 'apply_action', type: 'function', info: 'Apply action' },
  { label: 'apply_action!', type: 'function', info: 'Apply action!' },
  { label: 'traverse_errors', type: 'function', info: 'Traverse errors' },
  { label: 'add_error', type: 'function', info: 'Add error' },
  { label: 'update_change', type: 'function', info: 'Update change' },
  { label: 'force_change', type: 'function', info: 'Force change' },
  { label: 'change', type: 'function', info: 'Cast struct' },
  // Query
  { label: 'from', type: 'macro', info: 'Ecto from' },
  { label: 'where', type: 'macro', info: 'Query where' },
  { label: 'select', type: 'macro', info: 'Query select' },
  { label: 'order_by', type: 'macro', info: 'Query order' },
  { label: 'group_by', type: 'macro', info: 'Query group' },
  { label: 'having', type: 'macro', info: 'Query having' },
  { label: 'join', type: 'macro', info: 'Query join' },
  { label: 'limit', type: 'macro', info: 'Query limit' },
  { label: 'offset', type: 'macro', info: 'Query offset' },
  { label: 'distinct', type: 'macro', info: 'Query distinct' },
  { label: 'lock', type: 'macro', info: 'Query lock' },
  { label: 'preload', type: 'macro', info: 'Query preload' },
  { label: 'update', type: 'macro', info: 'Query update' },
  { label: 'subquery', type: 'function', info: 'Subquery' },
  { label: 'fragment', type: 'macro', info: 'SQL fragment' },
  { label: 'dynamic', type: 'macro', info: 'Dynamic query' },
  // Repo
  { label: 'Repo.get', type: 'function', info: 'Get by id' },
  { label: 'Repo.get!', type: 'function', info: 'Get by id (raise)' },
  { label: 'Repo.get_by', type: 'function', info: 'Get by fields' },
  { label: 'Repo.all', type: 'function', info: 'All rows' },
  { label: 'Repo.one', type: 'function', info: 'One row' },
  { label: 'Repo.one!', type: 'function', info: 'One! row' },
  { label: 'Repo.insert', type: 'function', info: 'Insert' },
  { label: 'Repo.insert!', type: 'function', info: 'Insert!' },
  { label: 'Repo.insert_all', type: 'function', info: 'Insert many' },
  { label: 'Repo.insert_or_update', type: 'function', info: 'Upsert' },
  { label: 'Repo.update', type: 'function', info: 'Update' },
  { label: 'Repo.update!', type: 'function', info: 'Update!' },
  { label: 'Repo.update_all', type: 'function', info: 'Update many' },
  { label: 'Repo.delete', type: 'function', info: 'Delete' },
  { label: 'Repo.delete!', type: 'function', info: 'Delete!' },
  { label: 'Repo.delete_all', type: 'function', info: 'Delete many' },
  { label: 'Repo.preload', type: 'function', info: 'Preload assoc' },
  { label: 'Repo.transaction', type: 'function', info: 'Transaction' },
  { label: 'Repo.rollback', type: 'function', info: 'Rollback' },
  { label: 'Repo.stream', type: 'function', info: 'Stream query' },
  { label: 'Repo.query', type: 'function', info: 'Raw query' },
  { label: 'Repo.query!', type: 'function', info: 'Raw query!' },
  { label: 'Repo.aggregate', type: 'function', info: 'Aggregate' },
  { label: 'Repo.exists?', type: 'function', info: 'Exists?' },
  // Multi
  { label: 'Multi.new', type: 'function', info: 'New Multi' },
  { label: 'Multi.insert', type: 'function', info: 'Multi insert' },
  { label: 'Multi.update', type: 'function', info: 'Multi update' },
  { label: 'Multi.delete', type: 'function', info: 'Multi delete' },
  { label: 'Multi.run', type: 'function', info: 'Multi run fn' },
  { label: 'Multi.append', type: 'function', info: 'Multi append' },
  { label: 'Multi.prepend', type: 'function', info: 'Multi prepend' },
  { label: 'Multi.merge', type: 'function', info: 'Multi merge' },
  // Migration
  { label: 'create', type: 'macro', info: 'Migration create' },
  { label: 'create_if_not_exists', type: 'macro', info: 'Create if not exists' },
  { label: 'alter', type: 'macro', info: 'Alter table' },
  { label: 'drop', type: 'macro', info: 'Drop table' },
  { label: 'drop_if_exists', type: 'macro', info: 'Drop if exists' },
  { label: 'rename', type: 'macro', info: 'Rename' },
  { label: 'table', type: 'macro', info: 'Table def' },
  { label: 'index', type: 'macro', info: 'Index def' },
  { label: 'unique_index', type: 'macro', info: 'Unique index' },
  { label: 'references', type: 'function', info: 'FK ref' },
  { label: 'add', type: 'macro', info: 'Add column' },
  { label: 'remove', type: 'macro', info: 'Remove column' },
  { label: 'modify', type: 'macro', info: 'Modify column' },
  { label: 'execute', type: 'macro', info: 'Raw SQL' },
  { label: 'constraint', type: 'function', info: 'Constraint def' },
  { label: 'flush', type: 'macro', info: 'Flush pending' },
  // GenServer
  { label: 'GenServer', type: 'module', info: 'OTP GenServer' },
  { label: 'start_link', type: 'function', info: 'Start linked' },
  { label: 'init', type: 'function', info: 'GenServer init' },
  { label: 'handle_call', type: 'function', info: 'Sync call handler' },
  { label: 'handle_cast', type: 'function', info: 'Async cast handler' },
  { label: 'handle_info', type: 'function', info: 'Msg handler' },
  { label: 'handle_continue', type: 'function', info: 'Continue handler' },
  { label: 'terminate', type: 'function', info: 'Terminate' },
  { label: 'code_change', type: 'function', info: 'Hot upgrade' },
  { label: 'format_status', type: 'function', info: 'Format status' },
  { label: 'call', type: 'function', info: 'Sync call' },
  { label: 'cast', type: 'function', info: 'Async cast' },
  { label: 'stop', type: 'function', info: 'Stop process' },
  { label: 'reply', type: 'function', info: 'Deferred reply' },
  { label: 'abcast', type: 'function', info: 'Broadcast cast' },
  { label: 'multi_call', type: 'function', info: 'Multi call' },
  // Supervisor
  { label: 'Supervisor', type: 'module', info: 'OTP Supervisor' },
  { label: 'DynamicSupervisor', type: 'module', info: 'Dynamic supervisor' },
  { label: 'start_child', type: 'function', info: 'Start child' },
  { label: 'terminate_child', type: 'function', info: 'Stop child' },
  { label: 'restart_child', type: 'function', info: 'Restart child' },
  { label: 'delete_child', type: 'function', info: 'Delete child' },
  { label: 'which_children', type: 'function', info: 'List children' },
  { label: 'count_children', type: 'function', info: 'Count children' },
  { label: 'child_spec', type: 'function', info: 'Child spec' },
  // Task
  { label: 'Task', type: 'module', info: 'Task module' },
  { label: 'Task.Supervisor', type: 'module', info: 'Task.Supervisor' },
  { label: 'Task.async', type: 'function', info: 'Async task' },
  { label: 'Task.await', type: 'function', info: 'Await task' },
  { label: 'Task.yield', type: 'function', info: 'Yield task' },
  { label: 'Task.shutdown', type: 'function', info: 'Shutdown task' },
  { label: 'Task.start', type: 'function', info: 'Start unlinked' },
  { label: 'Task.start_link', type: 'function', info: 'Start linked' },
  { label: 'Task.async_stream', type: 'function', info: 'Async stream' },
  { label: 'Task.completed', type: 'function', info: 'Completed task' },
  // Agent
  { label: 'Agent', type: 'module', info: 'OTP Agent' },
  { label: 'Agent.start_link', type: 'function', info: 'Start agent' },
  { label: 'Agent.get', type: 'function', info: 'Get state' },
  { label: 'Agent.update', type: 'function', info: 'Update state' },
  { label: 'Agent.get_and_update', type: 'function', info: 'Get+update' },
  { label: 'Agent.cast', type: 'function', info: 'Agent cast' },
  // Registry
  { label: 'Registry', type: 'module', info: 'Registry' },
  { label: 'Registry.register', type: 'function', info: 'Register' },
  { label: 'Registry.unregister', type: 'function', info: 'Unregister' },
  { label: 'Registry.lookup', type: 'function', info: 'Lookup' },
  { label: 'Registry.dispatch', type: 'function', info: 'Dispatch' },
  { label: 'Registry.keys', type: 'function', info: 'Keys' },
  { label: 'Registry.values', type: 'function', info: 'Values' },
  { label: 'Registry.count', type: 'function', info: 'Count' },
  // GenStage / Flow / Broadway
  { label: 'GenStage', type: 'module', info: 'GenStage' },
  { label: 'Flow', type: 'module', info: 'Flow module' },
  { label: 'Flow.from_enumerable', type: 'function', info: 'Flow from enum' },
  { label: 'Flow.partition', type: 'function', info: 'Flow partition' },
  { label: 'Flow.map', type: 'function', info: 'Flow map' },
  { label: 'Flow.reduce', type: 'function', info: 'Flow reduce' },
  { label: 'Flow.run', type: 'function', info: 'Flow run' },
  { label: 'Broadway', type: 'module', info: 'Broadway' },
  { label: 'handle_message', type: 'function', info: 'Broadway handle' },
  { label: 'handle_batch', type: 'function', info: 'Broadway batch' },
  // Enum
  { label: 'Enum.map', type: 'function', info: 'Enum.map' },
  { label: 'Enum.filter', type: 'function', info: 'Enum.filter' },
  { label: 'Enum.reduce', type: 'function', info: 'Enum.reduce' },
  { label: 'Enum.reduce_while', type: 'function', info: 'Reduce while' },
  { label: 'Enum.each', type: 'function', info: 'Enum.each' },
  { label: 'Enum.sort', type: 'function', info: 'Enum.sort' },
  { label: 'Enum.sort_by', type: 'function', info: 'Sort by' },
  { label: 'Enum.count', type: 'function', info: 'Enum.count' },
  { label: 'Enum.into', type: 'function', info: 'Enum.into' },
  { label: 'Enum.any?', type: 'function', info: 'Enum.any?' },
  { label: 'Enum.all?', type: 'function', info: 'Enum.all?' },
  { label: 'Enum.empty?', type: 'function', info: 'Enum.empty?' },
  { label: 'Enum.member?', type: 'function', info: 'Is member?' },
  { label: 'Enum.find', type: 'function', info: 'Enum.find' },
  { label: 'Enum.find_index', type: 'function', info: 'Find index' },
  { label: 'Enum.find_value', type: 'function', info: 'Find value' },
  { label: 'Enum.take', type: 'function', info: 'Enum.take' },
  { label: 'Enum.take_while', type: 'function', info: 'Take while' },
  { label: 'Enum.drop', type: 'function', info: 'Enum.drop' },
  { label: 'Enum.drop_while', type: 'function', info: 'Drop while' },
  { label: 'Enum.chunk_every', type: 'function', info: 'Chunk every' },
  { label: 'Enum.chunk_by', type: 'function', info: 'Chunk by' },
  { label: 'Enum.chunk_while', type: 'function', info: 'Chunk while' },
  { label: 'Enum.zip', type: 'function', info: 'Enum.zip' },
  { label: 'Enum.unzip', type: 'function', info: 'Enum.unzip' },
  { label: 'Enum.concat', type: 'function', info: 'Enum.concat' },
  { label: 'Enum.flat_map', type: 'function', info: 'Flat map' },
  { label: 'Enum.group_by', type: 'function', info: 'Group by' },
  { label: 'Enum.uniq', type: 'function', info: 'Enum.uniq' },
  { label: 'Enum.uniq_by', type: 'function', info: 'Uniq by' },
  { label: 'Enum.dedup', type: 'function', info: 'Dedup' },
  { label: 'Enum.dedup_by', type: 'function', info: 'Dedup by' },
  { label: 'Enum.reverse', type: 'function', info: 'Reverse' },
  { label: 'Enum.min', type: 'function', info: 'Min' },
  { label: 'Enum.max', type: 'function', info: 'Max' },
  { label: 'Enum.min_by', type: 'function', info: 'Min by' },
  { label: 'Enum.max_by', type: 'function', info: 'Max by' },
  { label: 'Enum.sum', type: 'function', info: 'Sum' },
  { label: 'Enum.product', type: 'function', info: 'Product' },
  { label: 'Enum.frequencies', type: 'function', info: 'Frequencies' },
  { label: 'Enum.at', type: 'function', info: 'Enum.at' },
  { label: 'Enum.first', type: 'function', info: 'First (Kernel)' },
  { label: 'Enum.slice', type: 'function', info: 'Enum.slice' },
  { label: 'Enum.split', type: 'function', info: 'Enum.split' },
  { label: 'Enum.split_while', type: 'function', info: 'Split while' },
  { label: 'Enum.split_with', type: 'function', info: 'Split with' },
  { label: 'Enum.partition', type: 'function', info: 'Partition' },
  { label: 'Enum.random', type: 'function', info: 'Enum.random' },
  { label: 'Enum.shuffle', type: 'function', info: 'Enum.shuffle' },
  { label: 'Enum.take_random', type: 'function', info: 'Take random' },
  { label: 'Enum.intersperse', type: 'function', info: 'Intersperse' },
  { label: 'Enum.join', type: 'function', info: 'Enum.join' },
  { label: 'Enum.to_list', type: 'function', info: 'Enum.to_list' },
  { label: 'Enum.scan', type: 'function', info: 'Enum.scan' },
  { label: 'Enum.with_index', type: 'function', info: 'With index' },
  { label: 'Enum.zip_with', type: 'function', info: 'Zip with fn' },
  { label: 'Enum.map_reduce', type: 'function', info: 'Map + reduce' },
  { label: 'Enum.map_join', type: 'function', info: 'Map + join' },
  { label: 'Enum.map_every', type: 'function', info: 'Map every n' },
  { label: 'Enum.reject', type: 'function', info: 'Enum.reject' },
  // Stream
  { label: 'Stream.map', type: 'function', info: 'Stream.map' },
  { label: 'Stream.filter', type: 'function', info: 'Stream.filter' },
  { label: 'Stream.reject', type: 'function', info: 'Stream.reject' },
  { label: 'Stream.take', type: 'function', info: 'Stream.take' },
  { label: 'Stream.take_while', type: 'function', info: 'Take while' },
  { label: 'Stream.drop', type: 'function', info: 'Stream.drop' },
  { label: 'Stream.drop_while', type: 'function', info: 'Drop while' },
  { label: 'Stream.chunk_every', type: 'function', info: 'Chunk every' },
  { label: 'Stream.chunk_by', type: 'function', info: 'Chunk by' },
  { label: 'Stream.chunk_while', type: 'function', info: 'Chunk while' },
  { label: 'Stream.zip', type: 'function', info: 'Stream.zip' },
  { label: 'Stream.zip_with', type: 'function', info: 'Zip with' },
  { label: 'Stream.concat', type: 'function', info: 'Concat streams' },
  { label: 'Stream.cycle', type: 'function', info: 'Stream.cycle' },
  { label: 'Stream.iterate', type: 'function', info: 'Stream.iterate' },
  { label: 'Stream.interval', type: 'function', info: 'Stream.interval' },
  { label: 'Stream.timer', type: 'function', info: 'Stream.timer' },
  { label: 'Stream.repeatedly', type: 'function', info: 'Repeatedly' },
  { label: 'Stream.resource', type: 'function', info: 'Stream resource' },
  { label: 'Stream.unfold', type: 'function', info: 'Stream.unfold' },
  { label: 'Stream.with_index', type: 'function', info: 'With index' },
  { label: 'Stream.flat_map', type: 'function', info: 'Flat map' },
  { label: 'Stream.dedup', type: 'function', info: 'Stream.dedup' },
  { label: 'Stream.transform', type: 'function', info: 'Transform' },
  { label: 'Stream.run', type: 'function', info: 'Stream.run' },
  { label: 'Stream.each', type: 'function', info: 'Stream.each' },
  { label: 'Stream.intersperse', type: 'function', info: 'Intersperse' },
  { label: 'Stream.scan', type: 'function', info: 'Stream.scan' },
  // List
  { label: 'List.first', type: 'function', info: 'List first' },
  { label: 'List.last', type: 'function', info: 'List last' },
  { label: 'List.delete', type: 'function', info: 'List.delete' },
  { label: 'List.delete_at', type: 'function', info: 'Delete at' },
  { label: 'List.insert_at', type: 'function', info: 'Insert at' },
  { label: 'List.keyfind', type: 'function', info: 'Keyfind' },
  { label: 'List.keyfind!', type: 'function', info: 'Keyfind!' },
  { label: 'List.keyreplace', type: 'function', info: 'Keyreplace' },
  { label: 'List.keystore', type: 'function', info: 'Keystore' },
  { label: 'List.keydelete', type: 'function', info: 'Keydelete' },
  { label: 'List.keysort', type: 'function', info: 'Keysort' },
  { label: 'List.keytake', type: 'function', info: 'Keytake' },
  { label: 'List.flatten', type: 'function', info: 'Flatten' },
  { label: 'List.foldl', type: 'function', info: 'Fold left' },
  { label: 'List.foldr', type: 'function', info: 'Fold right' },
  { label: 'List.myers_difference', type: 'function', info: 'Myers diff' },
  { label: 'List.replace_at', type: 'function', info: 'Replace at' },
  { label: 'List.update_at', type: 'function', info: 'Update at' },
  { label: 'List.starts_with?', type: 'function', info: 'Starts with?' },
  { label: 'List.to_atom', type: 'function', info: 'To atom' },
  { label: 'List.to_string', type: 'function', info: 'To string' },
  { label: 'List.to_tuple', type: 'function', info: 'To tuple' },
  { label: 'List.to_integer', type: 'function', info: 'To integer' },
  { label: 'List.zip', type: 'function', info: 'List.zip' },
  { label: 'List.wrap', type: 'function', info: 'List.wrap' },
  { label: 'List.improper?', type: 'function', info: 'Improper?' },
  // Map
  { label: 'Map.get', type: 'function', info: 'Map.get' },
  { label: 'Map.get_lazy', type: 'function', info: 'Map.get_lazy' },
  { label: 'Map.put', type: 'function', info: 'Map.put' },
  { label: 'Map.put_new', type: 'function', info: 'Put new' },
  { label: 'Map.put_new_lazy', type: 'function', info: 'Put new lazy' },
  { label: 'Map.merge', type: 'function', info: 'Map.merge' },
  { label: 'Map.update', type: 'function', info: 'Map.update' },
  { label: 'Map.update!', type: 'function', info: 'Map.update!' },
  { label: 'Map.delete', type: 'function', info: 'Map.delete' },
  { label: 'Map.drop', type: 'function', info: 'Map.drop' },
  { label: 'Map.take', type: 'function', info: 'Map.take' },
  { label: 'Map.split', type: 'function', info: 'Map.split' },
  { label: 'Map.keys', type: 'function', info: 'Map.keys' },
  { label: 'Map.values', type: 'function', info: 'Map.values' },
  { label: 'Map.to_list', type: 'function', info: 'To list' },
  { label: 'Map.from_keys', type: 'function', info: 'From keys' },
  { label: 'Map.replace', type: 'function', info: 'Replace' },
  { label: 'Map.replace!', type: 'function', info: 'Replace!' },
  { label: 'Map.has_key?', type: 'function', info: 'Has key?' },
  { label: 'Map.equal?', type: 'function', info: 'Equal?' },
  { label: 'Map.fetch', type: 'function', info: 'Map.fetch' },
  { label: 'Map.fetch!', type: 'function', info: 'Map.fetch!' },
  { label: 'Map.pop', type: 'function', info: 'Map.pop' },
  { label: 'Map.pop_lazy', type: 'function', info: 'Pop lazy' },
  { label: 'Map.pop!', type: 'function', info: 'Map.pop!' },
  { label: 'Map.get_and_update', type: 'function', info: 'Get+update' },
  { label: 'Map.new', type: 'function', info: 'Map.new' },
  { label: 'Map.filter', type: 'function', info: 'Map.filter' },
  { label: 'Map.reject', type: 'function', info: 'Map.reject' },
  { label: 'Map.split_with', type: 'function', info: 'Split with' },
  // Keyword
  { label: 'Keyword.get', type: 'function', info: 'KW get' },
  { label: 'Keyword.put', type: 'function', info: 'KW put' },
  { label: 'Keyword.merge', type: 'function', info: 'KW merge' },
  { label: 'Keyword.update', type: 'function', info: 'KW update' },
  { label: 'Keyword.delete', type: 'function', info: 'KW delete' },
  { label: 'Keyword.keys', type: 'function', info: 'KW keys' },
  { label: 'Keyword.values', type: 'function', info: 'KW values' },
  { label: 'Keyword.new', type: 'function', info: 'KW new' },
  { label: 'Keyword.fetch', type: 'function', info: 'KW fetch' },
  { label: 'Keyword.fetch!', type: 'function', info: 'KW fetch!' },
  { label: 'Keyword.has_key?', type: 'function', info: 'KW has key?' },
  { label: 'Keyword.to_list', type: 'function', info: 'KW to list' },
  { label: 'Keyword.keyword?', type: 'function', info: 'Is keyword?' },
  { label: 'Keyword.take', type: 'function', info: 'KW take' },
  { label: 'Keyword.drop', type: 'function', info: 'KW drop' },
  { label: 'Keyword.filter', type: 'function', info: 'KW filter' },
  { label: 'Keyword.reject', type: 'function', info: 'KW reject' },
  { label: 'Keyword.split', type: 'function', info: 'KW split' },
  { label: 'Keyword.validate!', type: 'function', info: 'Validate opts' },
  { label: 'Keyword.pop', type: 'function', info: 'KW pop' },
  // MapSet
  { label: 'MapSet.new', type: 'function', info: 'New MapSet' },
  { label: 'MapSet.put', type: 'function', info: 'MapSet put' },
  { label: 'MapSet.delete', type: 'function', info: 'MapSet delete' },
  { label: 'MapSet.union', type: 'function', info: 'Set union' },
  { label: 'MapSet.intersection', type: 'function', info: 'Set inter' },
  { label: 'MapSet.difference', type: 'function', info: 'Set diff' },
  { label: 'MapSet.disjoint?', type: 'function', info: 'Disjoint?' },
  { label: 'MapSet.subset?', type: 'function', info: 'Subset?' },
  { label: 'MapSet.equal?', type: 'function', info: 'Equal?' },
  { label: 'MapSet.member?', type: 'function', info: 'Member?' },
  { label: 'MapSet.size', type: 'function', info: 'Size' },
  { label: 'MapSet.to_list', type: 'function', info: 'To list' },
  { label: 'MapSet.filter', type: 'function', info: 'Filter' },
  { label: 'MapSet.reject', type: 'function', info: 'Reject' },
  // String
  { label: 'String.length', type: 'function', info: 'String length' },
  { label: 'String.upcase', type: 'function', info: 'Uppercase' },
  { label: 'String.downcase', type: 'function', info: 'Lowercase' },
  { label: 'String.capitalize', type: 'function', info: 'Capitalize' },
  { label: 'String.trim', type: 'function', info: 'Trim ws' },
  { label: 'String.trim_leading', type: 'function', info: 'Trim left' },
  { label: 'String.trim_trailing', type: 'function', info: 'Trim right' },
  { label: 'String.split', type: 'function', info: 'Split string' },
  { label: 'String.splitter', type: 'function', info: 'Stream split' },
  { label: 'String.split_at', type: 'function', info: 'Split at pos' },
  { label: 'String.replace', type: 'function', info: 'Replace pattern' },
  { label: 'String.replace_leading', type: 'function', info: 'Replace leading' },
  { label: 'String.replace_trailing', type: 'function', info: 'Replace trailing' },
  { label: 'String.replace_prefix', type: 'function', info: 'Replace prefix' },
  { label: 'String.replace_suffix', type: 'function', info: 'Replace suffix' },
  { label: 'String.contains?', type: 'function', info: 'Contains?' },
  { label: 'String.starts_with?', type: 'function', info: 'Starts with?' },
  { label: 'String.ends_with?', type: 'function', info: 'Ends with?' },
  { label: 'String.first', type: 'function', info: 'First char' },
  { label: 'String.last', type: 'function', info: 'Last char' },
  { label: 'String.at', type: 'function', info: 'Char at' },
  { label: 'String.slice', type: 'function', info: 'Slice' },
  { label: 'String.codepoints', type: 'function', info: 'Codepoints' },
  { label: 'String.graphemes', type: 'function', info: 'Graphemes' },
  { label: 'String.to_atom', type: 'function', info: 'To atom' },
  { label: 'String.to_existing_atom', type: 'function', info: 'Existing atom' },
  { label: 'String.to_integer', type: 'function', info: 'To int' },
  { label: 'String.to_float', type: 'function', info: 'To float' },
  { label: 'String.to_charlist', type: 'function', info: 'To charlist' },
  { label: 'String.pad_leading', type: 'function', info: 'Pad leading' },
  { label: 'String.pad_trailing', type: 'function', info: 'Pad trailing' },
  { label: 'String.duplicate', type: 'function', info: 'Duplicate' },
  { label: 'String.reverse', type: 'function', info: 'Reverse' },
  { label: 'String.valid?', type: 'function', info: 'Valid UTF-8?' },
  { label: 'String.printable?', type: 'function', info: 'Printable?' },
  { label: 'String.equivalent?', type: 'function', info: 'Equivalent?' },
  { label: 'String.normalize', type: 'function', info: 'Normalize' },
  { label: 'String.jaro_distance', type: 'function', info: 'Jaro distance' },
  { label: 'String.bag_distance', type: 'function', info: 'Bag distance' },
  { label: 'String.myers_difference', type: 'function', info: 'Myers diff' },
  { label: 'String.match?', type: 'function', info: 'Match regex?' },
  // IO / File / Path
  { label: 'IO.puts', type: 'function', info: 'IO.puts' },
  { label: 'IO.write', type: 'function', info: 'IO.write' },
  { label: 'IO.read', type: 'function', info: 'IO.read' },
  { label: 'IO.gets', type: 'function', info: 'IO.gets' },
  { label: 'IO.binread', type: 'function', info: 'Binary read' },
  { label: 'IO.binwrite', type: 'function', info: 'Binary write' },
  { label: 'IO.inspect', type: 'function', info: 'Inspect' },
  { label: 'IO.ANSI', type: 'module', info: 'ANSI codes' },
  { label: 'File.read', type: 'function', info: 'Read file' },
  { label: 'File.read!', type: 'function', info: 'Read file!' },
  { label: 'File.write', type: 'function', info: 'Write file' },
  { label: 'File.write!', type: 'function', info: 'Write file!' },
  { label: 'File.exists?', type: 'function', info: 'Exists?' },
  { label: 'File.mkdir', type: 'function', info: 'mkdir' },
  { label: 'File.mkdir_p', type: 'function', info: 'mkdir -p' },
  { label: 'File.rm', type: 'function', info: 'rm' },
  { label: 'File.rm_rf', type: 'function', info: 'rm -rf' },
  { label: 'File.stat', type: 'function', info: 'File stat' },
  { label: 'File.lstat', type: 'function', info: 'Link stat' },
  { label: 'File.ls', type: 'function', info: 'Dir contents' },
  { label: 'File.open', type: 'function', info: 'Open file' },
  { label: 'File.stream!', type: 'function', info: 'File stream' },
  { label: 'File.touch', type: 'function', info: 'Touch file' },
  { label: 'File.copy', type: 'function', info: 'Copy file' },
  { label: 'File.cp', type: 'function', info: 'cp' },
  { label: 'File.cp_r', type: 'function', info: 'cp -r' },
  { label: 'File.rename', type: 'function', info: 'Rename' },
  { label: 'File.chmod', type: 'function', info: 'chmod' },
  { label: 'File.chown', type: 'function', info: 'chown' },
  { label: 'File.cwd', type: 'function', info: 'cwd' },
  { label: 'File.cd', type: 'function', info: 'cd' },
  { label: 'File.cd!', type: 'function', info: 'cd!' },
  { label: 'Path.join', type: 'function', info: 'Path join' },
  { label: 'Path.dirname', type: 'function', info: 'Path dirname' },
  { label: 'Path.basename', type: 'function', info: 'Path basename' },
  { label: 'Path.extname', type: 'function', info: 'Extension' },
  { label: 'Path.rootname', type: 'function', info: 'Rootname' },
  { label: 'Path.expand', type: 'function', info: 'Expand path' },
  { label: 'Path.relative', type: 'function', info: 'Relative path' },
  { label: 'Path.absname', type: 'function', info: 'Absolute path' },
  { label: 'Path.wildcard', type: 'function', info: 'Glob paths' },
  // Process
  { label: 'Process.send', type: 'function', info: 'Send msg' },
  { label: 'Process.send_after', type: 'function', info: 'Send after' },
  { label: 'Process.exit', type: 'function', info: 'Exit' },
  { label: 'Process.flag', type: 'function', info: 'Process flag' },
  { label: 'Process.link', type: 'function', info: 'Link process' },
  { label: 'Process.unlink', type: 'function', info: 'Unlink' },
  { label: 'Process.monitor', type: 'function', info: 'Monitor' },
  { label: 'Process.demonitor', type: 'function', info: 'Demonitor' },
  { label: 'Process.register', type: 'function', info: 'Register name' },
  { label: 'Process.unregister', type: 'function', info: 'Unregister' },
  { label: 'Process.whereis', type: 'function', info: 'Whereis' },
  { label: 'Process.alive?', type: 'function', info: 'Is alive?' },
  { label: 'Process.info', type: 'function', info: 'Process info' },
  { label: 'Process.self', type: 'function', info: 'Self pid' },
  { label: 'Process.list', type: 'function', info: 'All pids' },
  { label: 'Process.sleep', type: 'function', info: 'Sleep' },
  { label: 'Process.spawn', type: 'function', info: 'Spawn' },
  { label: 'Process.get', type: 'function', info: 'Process get' },
  { label: 'Process.put', type: 'function', info: 'Process put' },
  // Code / Macro
  { label: 'Code.compile_file', type: 'function', info: 'Compile file' },
  { label: 'Code.compile_string', type: 'function', info: 'Compile string' },
  { label: 'Code.eval_file', type: 'function', info: 'Eval file' },
  { label: 'Code.eval_string', type: 'function', info: 'Eval string' },
  { label: 'Code.require_file', type: 'function', info: 'Require file' },
  { label: 'Code.ensure_loaded', type: 'function', info: 'Ensure loaded' },
  { label: 'Code.ensure_loaded?', type: 'function', info: 'Is loaded?' },
  { label: 'Code.format_string!', type: 'function', info: 'Format code' },
  { label: 'Macro.expand', type: 'function', info: 'Expand macro' },
  { label: 'Macro.expand_once', type: 'function', info: 'Expand once' },
  { label: 'Macro.escape', type: 'function', info: 'Escape AST' },
  { label: 'Macro.var', type: 'function', info: 'Make var AST' },
  { label: 'Macro.to_string', type: 'function', info: 'AST to str' },
  { label: 'Macro.prewalk', type: 'function', info: 'Prewalk AST' },
  { label: 'Macro.postwalk', type: 'function', info: 'Postwalk AST' },
  { label: 'Macro.traverse', type: 'function', info: 'Traverse AST' },
  // Kernel.SpecialForms
  { label: 'quote', type: 'keyword', info: 'Quote AST' },
  { label: 'unquote', type: 'keyword', info: 'Unquote AST' },
  { label: 'unquote_splicing', type: 'keyword', info: 'Unquote splice' },
  { label: 'for', type: 'keyword', info: 'Comprehension' },
  { label: 'case', type: 'keyword', info: 'Case expr' },
  { label: 'cond', type: 'keyword', info: 'Cond expr' },
  { label: 'with', type: 'keyword', info: 'With expr' },
  { label: 'if', type: 'keyword', info: 'If expr' },
  { label: 'unless', type: 'keyword', info: 'Unless expr' },
  { label: 'receive', type: 'keyword', info: 'Receive block' },
  { label: 'try', type: 'keyword', info: 'Try block' },
  { label: 'raise', type: 'keyword', info: 'Raise exception' },
  { label: 'reraise', type: 'keyword', info: 'Reraise' },
  { label: 'throw', type: 'keyword', info: 'Throw value' },
  { label: 'catch', type: 'keyword', info: 'Catch block' },
  { label: 'rescue', type: 'keyword', info: 'Rescue block' },
  { label: 'after', type: 'keyword', info: 'After block' },
  { label: 'else', type: 'keyword', info: 'Else clause' },
  { label: 'end', type: 'keyword', info: 'End block' },
  { label: 'defmodule', type: 'keyword', info: 'Define module' },
  { label: 'def', type: 'keyword', info: 'Define function' },
  { label: 'defp', type: 'keyword', info: 'Private function' },
  { label: 'defmacro', type: 'keyword', info: 'Define macro' },
  { label: 'defmacrop', type: 'keyword', info: 'Private macro' },
  { label: 'defstruct', type: 'keyword', info: 'Define struct' },
  { label: 'defguard', type: 'keyword', info: 'Define guard' },
  { label: 'defguardp', type: 'keyword', info: 'Private guard' },
  { label: 'defexception', type: 'keyword', info: 'Define exception' },
  { label: 'defprotocol', type: 'keyword', info: 'Define protocol' },
  { label: 'defimpl', type: 'keyword', info: 'Define impl' },
  { label: 'defoverridable', type: 'keyword', info: 'Override hook' },
  { label: 'defdelegate', type: 'keyword', info: 'Delegate fn' },
  { label: 'use', type: 'keyword', info: 'Use macro' },
  { label: 'import', type: 'keyword', info: 'Import module' },
  { label: 'alias', type: 'keyword', info: 'Alias module' },
  { label: 'require', type: 'keyword', info: 'Require module' },
  { label: 'fn', type: 'keyword', info: 'Anonymous fn' },
  { label: 'when', type: 'keyword', info: 'Guard clause' },
  { label: 'do', type: 'keyword', info: 'Do block' },
  // ExUnit
  { label: 'ExUnit.Case', type: 'module', info: 'Test case' },
  { label: 'ExUnit.start', type: 'function', info: 'Start ExUnit' },
  { label: 'test', type: 'macro', info: 'Test macro' },
  { label: 'describe', type: 'macro', info: 'Describe block' },
  { label: 'setup', type: 'macro', info: 'Setup callback' },
  { label: 'setup_all', type: 'macro', info: 'Setup all' },
  { label: 'on_exit', type: 'function', info: 'On-exit hook' },
  { label: 'assert', type: 'macro', info: 'Assert' },
  { label: 'refute', type: 'macro', info: 'Refute' },
  { label: 'assert_raise', type: 'macro', info: 'Assert raises' },
  { label: 'assert_received', type: 'macro', info: 'Assert msg recv' },
  { label: 'assert_receive', type: 'macro', info: 'Async assert recv' },
  { label: 'refute_receive', type: 'macro', info: 'Refute recv' },
  { label: 'doctest', type: 'macro', info: 'Doctest' },
  { label: 'capture_io', type: 'function', info: 'Capture IO' },
  { label: 'capture_log', type: 'function', info: 'Capture log' },
  // Mix
  { label: 'Mix.Task', type: 'module', info: 'Mix task' },
  { label: 'Mix.Project', type: 'module', info: 'Mix project' },
  { label: 'Mix.env', type: 'function', info: 'Mix env' },
  { label: 'Mix.target', type: 'function', info: 'Mix target' },
  { label: 'Mix.shell', type: 'function', info: 'Mix shell' },
  { label: 'Mix.Task.run', type: 'function', info: 'Run task' },
  { label: 'Mix.deps', type: 'function', info: 'Mix deps' },
  // Logger
  { label: 'Logger', type: 'module', info: 'Logger' },
  { label: 'Logger.debug', type: 'function', info: 'Debug log' },
  { label: 'Logger.info', type: 'function', info: 'Info log' },
  { label: 'Logger.warning', type: 'function', info: 'Warning log' },
  { label: 'Logger.error', type: 'function', info: 'Error log' },
  { label: 'Logger.critical', type: 'function', info: 'Critical log' },
  { label: 'Logger.notice', type: 'function', info: 'Notice log' },
  { label: 'Logger.emergency', type: 'function', info: 'Emergency log' },
  { label: 'Logger.alert', type: 'function', info: 'Alert log' },
  { label: 'Logger.metadata', type: 'function', info: 'Log metadata' },
  // Kernel
  { label: 'is_atom', type: 'guard', info: 'is_atom guard' },
  { label: 'is_binary', type: 'guard', info: 'is_binary' },
  { label: 'is_bitstring', type: 'guard', info: 'is_bitstring' },
  { label: 'is_boolean', type: 'guard', info: 'is_boolean' },
  { label: 'is_float', type: 'guard', info: 'is_float' },
  { label: 'is_function', type: 'guard', info: 'is_function' },
  { label: 'is_integer', type: 'guard', info: 'is_integer' },
  { label: 'is_list', type: 'guard', info: 'is_list' },
  { label: 'is_map', type: 'guard', info: 'is_map' },
  { label: 'is_nil', type: 'guard', info: 'is_nil' },
  { label: 'is_number', type: 'guard', info: 'is_number' },
  { label: 'is_pid', type: 'guard', info: 'is_pid' },
  { label: 'is_port', type: 'guard', info: 'is_port' },
  { label: 'is_reference', type: 'guard', info: 'is_reference' },
  { label: 'is_tuple', type: 'guard', info: 'is_tuple' },
  { label: 'is_exception', type: 'guard', info: 'is_exception' },
  { label: 'is_struct', type: 'guard', info: 'is_struct' },
  { label: 'not', type: 'operator', info: 'Boolean not' },
  { label: 'and', type: 'operator', info: 'Boolean and' },
  { label: 'or', type: 'operator', info: 'Boolean or' },
  { label: '==', type: 'operator', info: 'Equality' },
  { label: '!=', type: 'operator', info: 'Inequality' },
  { label: '===', type: 'operator', info: 'Strict equality' },
  { label: '!==', type: 'operator', info: 'Strict inequality' },
  // Snippets
  { label: 'gen-server', type: 'snippet', apply: 'defmodule ${Name} do\n  use GenServer\n  def start_link(opts), do: GenServer.start_link(__MODULE__, opts, name: __MODULE__)\n  def init(state), do: {:ok, state}\n  def handle_call(_msg, _from, state), do: {:reply, :ok, state}\n  def handle_cast(_msg, state), do: {:noreply, state}\nend', info: 'GenServer skeleton' },
  { label: 'with', type: 'snippet', apply: 'with {:ok, ${x}} <- ${expr} do\n  ${body}\nelse\n  {:error, reason} -> ${err}\nend', info: 'With block' },
  { label: 'case', type: 'snippet', apply: 'case ${expr} do\n  ${pat} -> ${body}\n  _ -> ${default}\nend', info: 'Case expression' },
  { label: 'pipeline', type: 'snippet', apply: '${expr}\n|> ${step1}\n|> ${step2}\n|> ${step3}', info: 'Pipe pipeline' },
  // Phoenix component
  { label: 'defcomponent', type: 'snippet', apply: 'attr :${name}, :string, required: true\n\ndef ${comp}(assigns) do\n  ~H"""\n  <div>\n    <%= @${name} %>\n  </div>\n  """\nend', info: 'Phx component' },
  // Integer / Float
  { label: 'Integer.parse', type: 'function', info: 'Parse int' },
  { label: 'Integer.to_string', type: 'function', info: 'Int to str' },
  { label: 'Integer.to_charlist', type: 'function', info: 'Int to charlist' },
  { label: 'Integer.digits', type: 'function', info: 'Digits' },
  { label: 'Integer.undigits', type: 'function', info: 'From digits' },
  { label: 'Integer.gcd', type: 'function', info: 'GCD' },
  { label: 'Integer.mod', type: 'function', info: 'Modulo' },
  { label: 'Integer.floor_div', type: 'function', info: 'Floor div' },
  { label: 'Integer.pow', type: 'function', info: 'Int power' },
  { label: 'Integer.is_odd', type: 'guard', info: 'Is odd?' },
  { label: 'Integer.is_even', type: 'guard', info: 'Is even?' },
  { label: 'Float.parse', type: 'function', info: 'Parse float' },
  { label: 'Float.ceil', type: 'function', info: 'Float ceil' },
  { label: 'Float.floor', type: 'function', info: 'Float floor' },
  { label: 'Float.round', type: 'function', info: 'Float round' },
  { label: 'Float.to_string', type: 'function', info: 'Float to str' },
  { label: 'Float.ratio', type: 'function', info: 'Float ratio' },
  // Atom
  { label: 'Atom.to_string', type: 'function', info: 'Atom to str' },
  { label: 'Atom.to_charlist', type: 'function', info: 'Atom to chars' },
  // Tuple
  { label: 'Tuple.to_list', type: 'function', info: 'Tuple to list' },
  { label: 'Tuple.append', type: 'function', info: 'Append elem' },
  { label: 'Tuple.insert_at', type: 'function', info: 'Insert at' },
  { label: 'Tuple.delete_at', type: 'function', info: 'Delete at' },
  { label: 'Tuple.duplicate', type: 'function', info: 'Duplicate tuple' },
  { label: 'Tuple.sum', type: 'function', info: 'Tuple sum' },
  { label: 'Tuple.product', type: 'function', info: 'Tuple product' },
  // Kernel functions
  { label: 'elem', type: 'function', info: 'Tuple elem at' },
  { label: 'put_elem', type: 'function', info: 'Put tuple elem' },
  { label: 'tuple_size', type: 'function', info: 'Tuple size' },
  { label: 'map_size', type: 'function', info: 'Map size' },
  { label: 'length', type: 'function', info: 'List length' },
  { label: 'hd', type: 'function', info: 'List head' },
  { label: 'tl', type: 'function', info: 'List tail' },
  { label: 'round', type: 'function', info: 'Round number' },
  { label: 'trunc', type: 'function', info: 'Truncate' },
  { label: 'div', type: 'function', info: 'Integer div' },
  { label: 'rem', type: 'function', info: 'Integer mod' },
  { label: 'abs', type: 'function', info: 'Absolute' },
  { label: 'min', type: 'function', info: 'Min' },
  { label: 'max', type: 'function', info: 'Max' },
  { label: 'spawn', type: 'function', info: 'Spawn process' },
  { label: 'spawn_link', type: 'function', info: 'Spawn linked' },
  { label: 'spawn_monitor', type: 'function', info: 'Spawn monitor' },
  { label: 'send', type: 'function', info: 'Send msg' },
  { label: 'self', type: 'function', info: 'Self pid' },
  { label: 'node', type: 'function', info: 'Node name' },
  { label: 'exit', type: 'function', info: 'Exit process' },
  { label: 'inspect', type: 'function', info: 'Inspect value' },
  { label: 'to_string', type: 'function', info: 'Coerce to string' },
  { label: 'to_charlist', type: 'function', info: 'Coerce to chars' },
  { label: 'binary_part', type: 'function', info: 'Binary part' },
  { label: 'byte_size', type: 'function', info: 'Byte size' },
  { label: 'bit_size', type: 'function', info: 'Bit size' },
  { label: 'make_ref', type: 'function', info: 'Make reference' },
  { label: 'function_exported?', type: 'function', info: 'Exported?' },
  { label: 'macro_exported?', type: 'function', info: 'Macro exported?' },
  { label: 'struct', type: 'function', info: 'Make struct' },
  { label: 'struct!', type: 'function', info: 'Make struct!' },
  { label: 'put_in', type: 'function', info: 'Put nested' },
  { label: 'update_in', type: 'function', info: 'Update nested' },
  { label: 'get_in', type: 'function', info: 'Get nested' },
  { label: 'pop_in', type: 'function', info: 'Pop nested' },
  { label: 'get_and_update_in', type: 'function', info: 'Get+update nested' },
  { label: 'sigil_w', type: 'function', info: 'Word list sigil' },
  { label: 'sigil_W', type: 'function', info: 'Raw word list' },
  { label: 'sigil_r', type: 'function', info: 'Regex sigil' },
  { label: 'sigil_R', type: 'function', info: 'Raw regex' },
  { label: 'sigil_s', type: 'function', info: 'String sigil' },
  { label: 'sigil_S', type: 'function', info: 'Raw string' },
  { label: 'sigil_c', type: 'function', info: 'Charlist sigil' },
  { label: 'sigil_C', type: 'function', info: 'Raw charlist' },
  { label: 'sigil_D', type: 'function', info: 'Date sigil' },
  { label: 'sigil_T', type: 'function', info: 'Time sigil' },
  { label: 'sigil_U', type: 'function', info: 'UTC datetime' },
  { label: 'sigil_N', type: 'function', info: 'Naive datetime' },
  { label: 'sigil_H', type: 'function', info: 'HEEx sigil' },
  // Regex
  { label: 'Regex.match?', type: 'function', info: 'Regex match?' },
  { label: 'Regex.run', type: 'function', info: 'Regex run' },
  { label: 'Regex.scan', type: 'function', info: 'Regex scan' },
  { label: 'Regex.named_captures', type: 'function', info: 'Named caps' },
  { label: 'Regex.replace', type: 'function', info: 'Regex replace' },
  { label: 'Regex.split', type: 'function', info: 'Regex split' },
  { label: 'Regex.compile', type: 'function', info: 'Compile regex' },
  { label: 'Regex.source', type: 'function', info: 'Regex source' },
  { label: 'Regex.escape', type: 'function', info: 'Regex escape' },
  // DateTime / Date / Time
  { label: 'DateTime.utc_now', type: 'function', info: 'UTC now' },
  { label: 'DateTime.now', type: 'function', info: 'DateTime now' },
  { label: 'DateTime.from_iso8601', type: 'function', info: 'From ISO8601' },
  { label: 'DateTime.to_iso8601', type: 'function', info: 'To ISO8601' },
  { label: 'DateTime.from_unix', type: 'function', info: 'From unix' },
  { label: 'DateTime.to_unix', type: 'function', info: 'To unix' },
  { label: 'DateTime.add', type: 'function', info: 'Add duration' },
  { label: 'DateTime.diff', type: 'function', info: 'Diff datetimes' },
  { label: 'DateTime.compare', type: 'function', info: 'Compare' },
  { label: 'DateTime.shift_zone', type: 'function', info: 'Shift zone' },
  { label: 'Date.utc_today', type: 'function', info: 'UTC today' },
  { label: 'Date.from_iso8601', type: 'function', info: 'From ISO' },
  { label: 'Date.to_iso8601', type: 'function', info: 'To ISO' },
  { label: 'Date.diff', type: 'function', info: 'Diff days' },
  { label: 'Date.add', type: 'function', info: 'Add days' },
  { label: 'Date.range', type: 'function', info: 'Date range' },
  { label: 'Date.beginning_of_week', type: 'function', info: 'Week start' },
  { label: 'Date.end_of_week', type: 'function', info: 'Week end' },
  { label: 'Date.beginning_of_month', type: 'function', info: 'Month start' },
  { label: 'Date.end_of_month', type: 'function', info: 'Month end' },
  { label: 'Date.leap_year?', type: 'function', info: 'Leap year?' },
  { label: 'Date.day_of_week', type: 'function', info: 'Day of week' },
  { label: 'Date.day_of_year', type: 'function', info: 'Day of year' },
  { label: 'Time.utc_now', type: 'function', info: 'UTC time now' },
  { label: 'Time.from_iso8601', type: 'function', info: 'Parse time' },
  { label: 'Time.to_iso8601', type: 'function', info: 'Format time' },
  { label: 'Time.diff', type: 'function', info: 'Time diff' },
  { label: 'Time.add', type: 'function', info: 'Time add' },
  { label: 'NaiveDateTime.utc_now', type: 'function', info: 'Naive now' },
  { label: 'NaiveDateTime.from_iso8601', type: 'function', info: 'Parse naive' },
  { label: 'NaiveDateTime.to_iso8601', type: 'function', info: 'Fmt naive' },
  { label: 'NaiveDateTime.diff', type: 'function', info: 'Naive diff' },
  { label: 'NaiveDateTime.add', type: 'function', info: 'Naive add' },
  // Calendar
  { label: 'Calendar.ISO', type: 'module', info: 'ISO calendar' },
  { label: 'Calendar.DateTime', type: 'module', info: 'Calendar datetime' },
  // ETS
  { label: ':ets.new', type: 'function', info: 'Create ETS' },
  { label: ':ets.insert', type: 'function', info: 'ETS insert' },
  { label: ':ets.lookup', type: 'function', info: 'ETS lookup' },
  { label: ':ets.delete', type: 'function', info: 'ETS delete' },
  { label: ':ets.tab2list', type: 'function', info: 'ETS to list' },
  { label: ':ets.select', type: 'function', info: 'ETS select' },
  { label: ':ets.match', type: 'function', info: 'ETS match' },
  { label: ':ets.update_counter', type: 'function', info: 'Counter' },
  { label: ':ets.foldl', type: 'function', info: 'ETS foldl' },
  { label: ':ets.info', type: 'function', info: 'ETS info' },
  // Base / binary ops
  { label: 'Base.encode64', type: 'function', info: 'Base64 encode' },
  { label: 'Base.decode64', type: 'function', info: 'Base64 decode' },
  { label: 'Base.encode16', type: 'function', info: 'Hex encode' },
  { label: 'Base.decode16', type: 'function', info: 'Hex decode' },
  { label: 'Base.url_encode64', type: 'function', info: 'URL base64' },
  { label: 'Base.url_decode64', type: 'function', info: 'URL base64 dec' },
  { label: 'Base.encode32', type: 'function', info: 'Base32 encode' },
  { label: 'Base.decode32', type: 'function', info: 'Base32 decode' },
  // URI
  { label: 'URI.parse', type: 'function', info: 'Parse URI' },
  { label: 'URI.to_string', type: 'function', info: 'URI to str' },
  { label: 'URI.encode', type: 'function', info: 'URI encode' },
  { label: 'URI.encode_www_form', type: 'function', info: 'URL form encode' },
  { label: 'URI.decode', type: 'function', info: 'URI decode' },
  { label: 'URI.decode_www_form', type: 'function', info: 'Form decode' },
  { label: 'URI.encode_query', type: 'function', info: 'Encode query' },
  { label: 'URI.decode_query', type: 'function', info: 'Decode query' },
  { label: 'URI.merge', type: 'function', info: 'URI merge' },
  // Access
  { label: 'Access.get', type: 'function', info: 'Access get' },
  { label: 'Access.key', type: 'function', info: 'Access key' },
  { label: 'Access.key!', type: 'function', info: 'Access key!' },
  { label: 'Access.at', type: 'function', info: 'Access at' },
  { label: 'Access.all', type: 'function', info: 'Access all' },
  { label: 'Access.filter', type: 'function', info: 'Access filter' },
  { label: 'Access.elem', type: 'function', info: 'Access elem' },
  { label: 'Access.pop', type: 'function', info: 'Access pop' },
  { label: 'Access.fetch', type: 'function', info: 'Access fetch' },
  // Application / OTP
  { label: 'Application.start', type: 'function', info: 'App start' },
  { label: 'Application.stop', type: 'function', info: 'App stop' },
  { label: 'Application.ensure_started', type: 'function', info: 'Ensure started' },
  { label: 'Application.ensure_all_started', type: 'function', info: 'Ensure all' },
  { label: 'Application.get_env', type: 'function', info: 'Get config' },
  { label: 'Application.put_env', type: 'function', info: 'Put config' },
  { label: 'Application.fetch_env', type: 'function', info: 'Fetch config' },
  { label: 'Application.fetch_env!', type: 'function', info: 'Fetch config!' },
  { label: 'Application.spec', type: 'function', info: 'App spec' },
  { label: 'Application.started_applications', type: 'function', info: 'Started apps' },
  // Config
  { label: 'Config', type: 'module', info: 'Config module' },
  { label: 'config', type: 'macro', info: 'Config macro' },
  { label: 'config_env', type: 'function', info: 'Config env' },
  { label: 'config_target', type: 'function', info: 'Config target' },
  { label: 'import_config', type: 'macro', info: 'Import config' },
  // System
  { label: 'System.get_env', type: 'function', info: 'Env var' },
  { label: 'System.put_env', type: 'function', info: 'Set env var' },
  { label: 'System.delete_env', type: 'function', info: 'Del env var' },
  { label: 'System.argv', type: 'function', info: 'CLI args' },
  { label: 'System.halt', type: 'function', info: 'System halt' },
  { label: 'System.stop', type: 'function', info: 'System stop' },
  { label: 'System.cmd', type: 'function', info: 'Run command' },
  { label: 'System.os_time', type: 'function', info: 'OS time' },
  { label: 'System.system_time', type: 'function', info: 'System time' },
  { label: 'System.monotonic_time', type: 'function', info: 'Monotonic' },
  { label: 'System.convert_time_unit', type: 'function', info: 'Convert units' },
  { label: 'System.pid', type: 'function', info: 'Process PID' },
  { label: 'System.version', type: 'function', info: 'Elixir version' },
  { label: 'System.otp_release', type: 'function', info: 'OTP release' },
  { label: 'System.user_home', type: 'function', info: 'User home' },
  { label: 'System.tmp_dir', type: 'function', info: 'Temp dir' },
  // :crypto / :rand / :base64 (erlang)
  { label: ':crypto.hash', type: 'function', info: 'Erlang crypto hash' },
  { label: ':crypto.strong_rand_bytes', type: 'function', info: 'Random bytes' },
  { label: ':crypto.hmac', type: 'function', info: 'HMAC' },
  { label: ':rand.uniform', type: 'function', info: 'Random uniform' },
  { label: ':rand.normal', type: 'function', info: 'Random normal' },
  { label: ':rand.seed', type: 'function', info: 'Seed RNG' },
  // GenEvent / Port / Node
  { label: 'Port.open', type: 'function', info: 'Open port' },
  { label: 'Port.command', type: 'function', info: 'Port command' },
  { label: 'Port.close', type: 'function', info: 'Close port' },
  { label: 'Node.connect', type: 'function', info: 'Connect node' },
  { label: 'Node.disconnect', type: 'function', info: 'Disconnect' },
  { label: 'Node.list', type: 'function', info: 'Connected nodes' },
  { label: 'Node.ping', type: 'function', info: 'Ping node' },
  { label: 'Node.spawn', type: 'function', info: 'Spawn on node' },
  { label: 'Node.spawn_link', type: 'function', info: 'Spawn link' },
  { label: 'Node.monitor', type: 'function', info: 'Monitor node' },
  { label: 'Node.alive?', type: 'function', info: 'Node alive?' },
  { label: 'Node.self', type: 'function', info: 'Self node' },
  // HTTPoison / Req
  { label: 'HTTPoison.get', type: 'function', info: 'HTTPoison GET' },
  { label: 'HTTPoison.post', type: 'function', info: 'HTTPoison POST' },
  { label: 'HTTPoison.put', type: 'function', info: 'HTTPoison PUT' },
  { label: 'HTTPoison.delete', type: 'function', info: 'HTTPoison DELETE' },
  { label: 'Req.get', type: 'function', info: 'Req GET' },
  { label: 'Req.post', type: 'function', info: 'Req POST' },
  { label: 'Req.put', type: 'function', info: 'Req PUT' },
  { label: 'Req.delete', type: 'function', info: 'Req DELETE' },
  { label: 'Req.request', type: 'function', info: 'Req request' },
  { label: 'Req.new', type: 'function', info: 'New Req' },
  // Jason
  { label: 'Jason.encode', type: 'function', info: 'JSON encode' },
  { label: 'Jason.encode!', type: 'function', info: 'JSON encode!' },
  { label: 'Jason.decode', type: 'function', info: 'JSON decode' },
  { label: 'Jason.decode!', type: 'function', info: 'JSON decode!' },
  // Additional Phoenix macros
  { label: 'render_inline', type: 'function', info: 'Render inline (test)' },
  { label: 'render_click', type: 'function', info: 'LV test click' },
  { label: 'render_submit', type: 'function', info: 'LV test submit' },
  { label: 'render_change', type: 'function', info: 'LV test change' },
  { label: 'render_hook', type: 'function', info: 'LV test hook' },
  { label: 'render_patch', type: 'function', info: 'LV test patch' },
  { label: 'live', type: 'function', info: 'LV test helper' },
  { label: 'live_isolated', type: 'function', info: 'LV isolated test' },
  // Phoenix Verified routes
  { label: '~p"/path"', type: 'snippet', apply: '~p"${path}"', info: 'Verified path' },
  // Additional Ecto
  { label: 'validate_subset', type: 'function', info: 'Subset' },
  { label: 'optimistic_lock', type: 'function', info: 'Optimistic lock' },
  { label: 'prepare_changes', type: 'function', info: 'Prepare changes' },
  // Extras (Elixir 1.15+)
  { label: 'dbg', type: 'function', info: 'Debug pipe' },
  { label: 'binding', type: 'function', info: 'Local bindings' },
  { label: 'function', type: 'function', info: 'fun ref' },
  // Struct helpers
  { label: '__MODULE__', type: 'variable', info: 'Current module' },
  { label: '__DIR__', type: 'variable', info: 'File dir' },
  { label: '__ENV__', type: 'variable', info: 'Env info' },
  { label: '__CALLER__', type: 'variable', info: 'Caller info' },
  { label: '__STACKTRACE__', type: 'variable', info: 'Stacktrace' },
  // Bitstring
  { label: 'bitstring', type: 'keyword', info: 'Bitstring type' },
  // Common Enum chunks
  { label: 'Enum.reduce/3', type: 'function', info: 'Reduce with init' },
  // Phoenix.Presence API
  { label: 'Presence.track', type: 'function', info: 'Presence track' },
  { label: 'Presence.untrack', type: 'function', info: 'Presence untrack' },
  { label: 'Presence.list', type: 'function', info: 'Presence list' },
  { label: 'Presence.update', type: 'function', info: 'Presence update' },
  // HEEx / Slots
  { label: 'render_slot', type: 'function', info: 'Render slot' },
  // Phoenix Socket
  { label: 'channel', type: 'macro', info: 'Socket channel' },
  // Absinthe (GraphQL)
  { label: 'Absinthe.Schema', type: 'module', info: 'Absinthe schema' },
  { label: 'Absinthe.Resolution', type: 'module', info: 'Absinthe res' },
  { label: 'object', type: 'macro', info: 'GraphQL object' },
  { label: 'field', type: 'macro', info: 'GraphQL field' },
  { label: 'arg', type: 'macro', info: 'GraphQL arg' },
  { label: 'resolve', type: 'macro', info: 'GraphQL resolve' },
  { label: 'query', type: 'macro', info: 'GraphQL query' },
  { label: 'mutation', type: 'macro', info: 'GraphQL mutation' },
  { label: 'subscription', type: 'macro', info: 'GraphQL subscription' },
  // Oban background jobs
  { label: 'Oban', type: 'module', info: 'Oban job queue' },
  { label: 'Oban.Worker', type: 'module', info: 'Oban worker' },
  { label: 'Oban.Job', type: 'module', info: 'Oban job struct' },
  { label: 'Oban.insert', type: 'function', info: 'Enqueue job' },
  { label: 'Oban.insert_all', type: 'function', info: 'Enqueue many' },
  { label: 'Oban.cancel_job', type: 'function', info: 'Cancel job' },
  { label: 'Oban.retry_job', type: 'function', info: 'Retry job' },
  { label: 'perform', type: 'function', info: 'Worker perform' },
  // Common Ecto types
  { label: ':string', type: 'type', info: 'Ecto string' },
  { label: ':integer', type: 'type', info: 'Ecto integer' },
  { label: ':id', type: 'type', info: 'Ecto id' },
  { label: ':binary_id', type: 'type', info: 'Ecto UUID' },
  { label: ':binary', type: 'type', info: 'Ecto binary' },
  { label: ':boolean', type: 'type', info: 'Ecto boolean' },
  { label: ':map', type: 'type', info: 'Ecto map' },
  { label: ':decimal', type: 'type', info: 'Ecto decimal' },
  { label: ':float', type: 'type', info: 'Ecto float' },
  { label: ':date', type: 'type', info: 'Ecto date' },
  { label: ':time', type: 'type', info: 'Ecto time' },
  { label: ':naive_datetime', type: 'type', info: 'Ecto naive_dt' },
  { label: ':utc_datetime', type: 'type', info: 'Ecto utc_dt' },
  { label: ':utc_datetime_usec', type: 'type', info: 'utc_dt usec' },
  { label: '{:array, :string}', type: 'type', info: 'Array of strings' },
  // Telemetry
  { label: ':telemetry.attach', type: 'function', info: 'Telemetry attach' },
  { label: ':telemetry.detach', type: 'function', info: 'Telemetry detach' },
  { label: ':telemetry.execute', type: 'function', info: 'Exec event' },
  { label: ':telemetry.span', type: 'function', info: 'Span event' },
  // Tesla
  { label: 'Tesla.get', type: 'function', info: 'Tesla GET' },
  { label: 'Tesla.post', type: 'function', info: 'Tesla POST' },
  // Erlang modules used often
  { label: ':lists.sort', type: 'function', info: 'Erlang sort' },
  { label: ':lists.reverse', type: 'function', info: 'Erlang reverse' },
  { label: ':lists.map', type: 'function', info: 'Erlang map' },
  { label: ':lists.foreach', type: 'function', info: 'Erlang foreach' },
  { label: ':lists.filter', type: 'function', info: 'Erlang filter' },
  { label: ':lists.foldl', type: 'function', info: 'Erlang foldl' },
  { label: ':lists.foldr', type: 'function', info: 'Erlang foldr' },
  { label: ':math.sqrt', type: 'function', info: 'Erlang sqrt' },
  { label: ':math.log', type: 'function', info: 'Erlang log' },
  { label: ':math.pow', type: 'function', info: 'Erlang pow' },
  { label: ':io.format', type: 'function', info: 'Erlang io fmt' },
  { label: ':file.read_file', type: 'function', info: 'Erlang read file' },
  { label: ':binary.split', type: 'function', info: 'Binary split' },
  { label: ':binary.decode_unsigned', type: 'function', info: 'Decode uint' },
  { label: ':os.type', type: 'function', info: 'OS type' },
  { label: ':os.cmd', type: 'function', info: 'OS cmd' },
  { label: ':timer.sleep', type: 'function', info: 'Timer sleep' },
  { label: ':timer.send_after', type: 'function', info: 'Send after' },
  { label: ':timer.apply_after', type: 'function', info: 'Apply after' },
  { label: ':inet.gethostname', type: 'function', info: 'Hostname' },
  // Bitstring comprehensions / syntax
  { label: 'bitstring-int', type: 'snippet', apply: '<<${n}::integer>>', info: 'Integer bin' },
  { label: 'bitstring-utf8', type: 'snippet', apply: '<<${s}::utf8>>', info: 'UTF-8 bin' },
  { label: 'bitstring-binary', type: 'snippet', apply: '<<${b}::binary>>', info: 'Binary part' },
  // Phoenix Socket / Channel boilerplate
  { label: 'socket', type: 'macro', info: 'Socket macro' },
  { label: 'transport', type: 'macro', info: 'Transport macro' },
  // Phoenix helpers
  { label: 'live_title_tag', type: 'function', info: 'Live title' },
  { label: 'live_flash', type: 'function', info: 'Flash helper' },
  { label: 'live_render', type: 'function', info: 'Live render' },
  { label: 'live_patch', type: 'function', info: 'Live patch' },
  { label: 'live_redirect', type: 'function', info: 'Live redirect' },
  // Phoenix.Plug pipelines
  { label: 'accepts', type: 'plug', info: 'Accepts plug' },
  { label: 'fetch_session', type: 'plug', info: 'Fetch session plug' },
  { label: 'protect_from_forgery', type: 'plug', info: 'CSRF plug' },
  { label: 'put_secure_browser_headers', type: 'plug', info: 'Sec headers' },
  // HEEx helpers
  { label: 'slot', type: 'macro', info: 'Define slot' },
  { label: 'attr', type: 'macro', info: 'Define attr' },
  // Common GenServer returns
  { label: '{:reply, resp, state}', type: 'snippet', info: 'Reply tuple' },
  { label: '{:noreply, state}', type: 'snippet', info: 'Noreply tuple' },
  { label: '{:stop, reason, state}', type: 'snippet', info: 'Stop tuple' },
  { label: '{:ok, state}', type: 'snippet', info: 'Ok tuple' },
  { label: '{:error, reason}', type: 'snippet', info: 'Error tuple' },
  // Pattern matching sigil
  { label: 'map-pat', type: 'snippet', apply: '%{${key} => ${val}}', info: 'Map pattern' },
  { label: 'struct-pat', type: 'snippet', apply: '%${Struct}{${field}: ${val}}', info: 'Struct pattern' },
  // Common test helpers
  { label: 'assert_match', type: 'macro', info: 'Assert pattern match' },
  // Testing extras
  { label: 'Mox', type: 'module', info: 'Mox library' },
  { label: 'expect', type: 'function', info: 'Mox expect' },
  { label: 'stub', type: 'function', info: 'Mox stub' },
  { label: 'verify_on_exit!', type: 'macro', info: 'Mox verify' },
];
