// Completion entries for haskell.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  // Keywords
  { label: 'module', type: 'keyword', info: 'Module header' },
  { label: 'where', type: 'keyword', info: 'Where clause' },
  { label: 'import', type: 'keyword', info: 'Import module' },
  { label: 'qualified', type: 'keyword', info: 'Qualified import' },
  { label: 'as', type: 'keyword', info: 'Import alias' },
  { label: 'hiding', type: 'keyword', info: 'Import hiding' },
  { label: 'data', type: 'keyword', info: 'Data type' },
  { label: 'type', type: 'keyword', info: 'Type alias' },
  { label: 'newtype', type: 'keyword', info: 'Newtype' },
  { label: 'class', type: 'keyword', info: 'Type class' },
  { label: 'instance', type: 'keyword', info: 'Class instance' },
  { label: 'deriving', type: 'keyword', info: 'Derive instances' },
  { label: 'default', type: 'keyword', info: 'Default decl' },
  { label: 'let', type: 'keyword', info: 'Let binding' },
  { label: 'in', type: 'keyword', info: 'Let in' },
  { label: 'do', type: 'keyword', info: 'Do block' },
  { label: 'case', type: 'keyword', info: 'Case expression' },
  { label: 'of', type: 'keyword', info: 'Case of' },
  { label: 'if', type: 'keyword', info: 'If expression' },
  { label: 'then', type: 'keyword', info: 'Then branch' },
  { label: 'else', type: 'keyword', info: 'Else branch' },
  { label: 'forall', type: 'keyword', info: 'Universal quantifier' },
  { label: 'infix', type: 'keyword', info: 'Infix decl' },
  { label: 'infixl', type: 'keyword', info: 'Left infix' },
  { label: 'infixr', type: 'keyword', info: 'Right infix' },
  { label: 'foreign', type: 'keyword', info: 'Foreign import' },
  // Prelude types
  { label: 'Int', type: 'type', info: 'Fixed int' },
  { label: 'Integer', type: 'type', info: 'Arbitrary int' },
  { label: 'Float', type: 'type', info: 'Float' },
  { label: 'Double', type: 'type', info: 'Double' },
  { label: 'Char', type: 'type', info: 'Character' },
  { label: 'String', type: 'type', info: 'String (=[Char])' },
  { label: 'Bool', type: 'type', info: 'Boolean' },
  { label: 'Maybe', type: 'type', info: 'Maybe a' },
  { label: 'Just', type: 'class', info: 'Just x' },
  { label: 'Nothing', type: 'class', info: 'Nothing' },
  { label: 'Either', type: 'type', info: 'Either a b' },
  { label: 'Left', type: 'class', info: 'Left x' },
  { label: 'Right', type: 'class', info: 'Right x' },
  { label: 'IO', type: 'type', info: 'IO monad' },
  { label: '[a]', type: 'type', info: 'List type' },
  { label: '(,)', type: 'type', info: 'Tuple type' },
  { label: 'Ord', type: 'class', info: 'Ord class' },
  { label: 'Eq', type: 'class', info: 'Eq class' },
  { label: 'Show', type: 'class', info: 'Show class' },
  { label: 'Read', type: 'class', info: 'Read class' },
  { label: 'Num', type: 'class', info: 'Num class' },
  { label: 'Fractional', type: 'class', info: 'Fractional class' },
  { label: 'Functor', type: 'class', info: 'Functor class' },
  { label: 'Applicative', type: 'class', info: 'Applicative class' },
  { label: 'Monad', type: 'class', info: 'Monad class' },
  { label: 'Monoid', type: 'class', info: 'Monoid class' },
  { label: 'Semigroup', type: 'class', info: 'Semigroup class' },
  { label: 'Foldable', type: 'class', info: 'Foldable class' },
  { label: 'Traversable', type: 'class', info: 'Traversable class' },
  // Prelude functions
  { label: 'print', type: 'function', info: 'Print Showable' },
  { label: 'putStrLn', type: 'function', info: 'Print line' },
  { label: 'putStr', type: 'function', info: 'Print string' },
  { label: 'getLine', type: 'function', info: 'Read line' },
  { label: 'getContents', type: 'function', info: 'Read all stdin' },
  { label: 'readFile', type: 'function', info: 'Read file' },
  { label: 'writeFile', type: 'function', info: 'Write file' },
  { label: 'appendFile', type: 'function', info: 'Append file' },
  { label: 'return', type: 'function', info: 'Monadic return' },
  { label: 'pure', type: 'function', info: 'Applicative pure' },
  { label: 'map', type: 'function', info: 'Map list' },
  { label: 'fmap', type: 'function', info: 'Functor map' },
  { label: 'filter', type: 'function', info: 'Filter list' },
  { label: 'foldr', type: 'function', info: 'Fold right' },
  { label: 'foldl', type: 'function', info: 'Fold left' },
  { label: 'foldl\'', type: 'function', info: 'Strict foldl' },
  { label: 'zip', type: 'function', info: 'Zip lists' },
  { label: 'zipWith', type: 'function', info: 'Zip with func' },
  { label: 'unzip', type: 'function', info: 'Unzip pairs' },
  { label: 'head', type: 'function', info: 'First element' },
  { label: 'tail', type: 'function', info: 'All but first' },
  { label: 'init', type: 'function', info: 'All but last' },
  { label: 'last', type: 'function', info: 'Last element' },
  { label: 'null', type: 'function', info: 'Is empty?' },
  { label: 'length', type: 'function', info: 'List length' },
  { label: 'reverse', type: 'function', info: 'Reverse list' },
  { label: 'take', type: 'function', info: 'Take N' },
  { label: 'drop', type: 'function', info: 'Drop N' },
  { label: 'takeWhile', type: 'function', info: 'Take while' },
  { label: 'dropWhile', type: 'function', info: 'Drop while' },
  { label: 'span', type: 'function', info: 'Span predicate' },
  { label: 'break', type: 'function', info: 'Break on pred' },
  { label: 'splitAt', type: 'function', info: 'Split at index' },
  { label: 'concat', type: 'function', info: 'Concat lists' },
  { label: 'concatMap', type: 'function', info: 'Concat map' },
  { label: 'replicate', type: 'function', info: 'Replicate value' },
  { label: 'repeat', type: 'function', info: 'Infinite repeat' },
  { label: 'cycle', type: 'function', info: 'Cycle list' },
  { label: 'iterate', type: 'function', info: 'Iterate function' },
  { label: 'elem', type: 'function', info: 'Is element of' },
  { label: 'notElem', type: 'function', info: 'Not element of' },
  { label: 'lookup', type: 'function', info: 'Lookup in pairs' },
  { label: 'sum', type: 'function', info: 'Sum list' },
  { label: 'product', type: 'function', info: 'Product list' },
  { label: 'maximum', type: 'function', info: 'Maximum' },
  { label: 'minimum', type: 'function', info: 'Minimum' },
  { label: 'and', type: 'function', info: 'All True?' },
  { label: 'or', type: 'function', info: 'Any True?' },
  { label: 'any', type: 'function', info: 'Any predicate' },
  { label: 'all', type: 'function', info: 'All predicate' },
  { label: 'show', type: 'function', info: 'Show value' },
  { label: 'read', type: 'function', info: 'Read value' },
  { label: 'id', type: 'function', info: 'Identity' },
  { label: 'const', type: 'function', info: 'Const function' },
  { label: 'flip', type: 'function', info: 'Flip args' },
  { label: 'curry', type: 'function', info: 'Curry function' },
  { label: 'uncurry', type: 'function', info: 'Uncurry function' },
  { label: 'not', type: 'function', info: 'Logical not' },
  { label: 'otherwise', type: 'constant', info: 'Guard otherwise' },
  { label: 'error', type: 'function', info: 'Raise error' },
  { label: 'undefined', type: 'constant', info: 'Undefined' },
  // Monadic / Do
  { label: 'mapM', type: 'function', info: 'Monad map' },
  { label: 'mapM_', type: 'function', info: 'Monad map ignore' },
  { label: 'forM', type: 'function', info: 'Flipped mapM' },
  { label: 'forM_', type: 'function', info: 'Flipped mapM_' },
  { label: 'sequence', type: 'function', info: 'Sequence monads' },
  { label: 'sequence_', type: 'function', info: 'Sequence ignore' },
  { label: 'when', type: 'function', info: 'Conditional do' },
  { label: 'unless', type: 'function', info: 'Inverted when' },
  { label: 'replicateM', type: 'function', info: 'Replicate monad' },
  { label: 'forever', type: 'function', info: 'Infinite monad' },
  // Common modules
  { label: 'Data.List', type: 'module', info: 'Data.List' },
  { label: 'Data.Map', type: 'module', info: 'Data.Map' },
  { label: 'Data.Set', type: 'module', info: 'Data.Set' },
  { label: 'Data.Maybe', type: 'module', info: 'Data.Maybe' },
  { label: 'Data.Text', type: 'module', info: 'Data.Text' },
  { label: 'Data.ByteString', type: 'module', info: 'Data.ByteString' },
  { label: 'Data.Char', type: 'module', info: 'Data.Char' },
  { label: 'Control.Monad', type: 'module', info: 'Control.Monad' },
  { label: 'Control.Applicative', type: 'module', info: 'Control.Applicative' },
  { label: 'System.IO', type: 'module', info: 'System.IO' },
  { label: 'System.Environment', type: 'module', info: 'System.Env' },
  // Operators
  { label: '>>=', type: 'keyword', info: 'Bind' },
  { label: '=<<', type: 'keyword', info: 'Reverse bind' },
  { label: '>>', type: 'keyword', info: 'Sequence' },
  { label: '$', type: 'keyword', info: 'Function apply' },
  { label: '.', type: 'keyword', info: 'Function compose' },
  { label: '<$>', type: 'keyword', info: 'Functor fmap' },
  { label: '<*>', type: 'keyword', info: 'Applicative apply' },
  { label: '<|>', type: 'keyword', info: 'Alternative' },
  { label: '<>', type: 'keyword', info: 'Monoid append' },
  { label: '++', type: 'keyword', info: 'List append' },
  { label: '::', type: 'keyword', info: 'Type annotation' },
  { label: '->', type: 'keyword', info: 'Function arrow' },
  { label: '=>', type: 'keyword', info: 'Class constraint' },
  { label: '|', type: 'keyword', info: 'Guards / alts' },
];
