// Completion entries for json.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  // package.json common keys
  { label: 'name', type: 'property', info: 'Package name' },
  { label: 'version', type: 'property', info: 'SemVer version' },
  { label: 'description', type: 'property', info: 'Short description' },
  { label: 'keywords', type: 'property', info: 'Search keywords' },
  { label: 'homepage', type: 'property', info: 'Project URL' },
  { label: 'bugs', type: 'property', info: 'Issue tracker URL' },
  { label: 'license', type: 'property', info: 'SPDX license ID' },
  { label: 'author', type: 'property', info: 'Package author' },
  { label: 'contributors', type: 'property', info: 'Contributors list' },
  { label: 'funding', type: 'property', info: 'Funding URL' },
  { label: 'files', type: 'property', info: 'Published files' },
  { label: 'main', type: 'property', info: 'Main entry point' },
  { label: 'module', type: 'property', info: 'ESM entry' },
  { label: 'browser', type: 'property', info: 'Browser entry' },
  { label: 'bin', type: 'property', info: 'Executable' },
  { label: 'man', type: 'property', info: 'Man page path' },
  { label: 'directories', type: 'property', info: 'Directory hints' },
  { label: 'repository', type: 'property', info: 'Source repo' },
  { label: 'scripts', type: 'property', info: 'npm scripts' },
  { label: 'config', type: 'property', info: 'Package config' },
  { label: 'dependencies', type: 'property', info: 'Runtime deps' },
  { label: 'devDependencies', type: 'property', info: 'Dev deps' },
  { label: 'peerDependencies', type: 'property', info: 'Peer deps' },
  { label: 'peerDependenciesMeta', type: 'property', info: 'Peer deps meta' },
  { label: 'optionalDependencies', type: 'property', info: 'Optional deps' },
  { label: 'bundledDependencies', type: 'property', info: 'Bundled deps' },
  { label: 'engines', type: 'property', info: 'Engine versions' },
  { label: 'os', type: 'property', info: 'OS compat' },
  { label: 'cpu', type: 'property', info: 'CPU compat' },
  { label: 'private', type: 'property', info: 'Private package' },
  { label: 'publishConfig', type: 'property', info: 'Publish settings' },
  { label: 'workspaces', type: 'property', info: 'Monorepo workspaces' },
  { label: 'type', type: 'property', info: 'module / commonjs' },
  { label: 'exports', type: 'property', info: 'Subpath exports' },
  { label: 'imports', type: 'property', info: 'Subpath imports' },
  { label: 'sideEffects', type: 'property', info: 'Side effects hint' },
  { label: 'types', type: 'property', info: 'TS types entry' },
  { label: 'typings', type: 'property', info: 'TS typings entry' },
  { label: 'typesVersions', type: 'property', info: 'TS types versions' },
  // tsconfig compilerOptions
  { label: 'compilerOptions', type: 'property', info: 'TS compiler options' },
  { label: 'target', type: 'property', info: 'Output ES version' },
  { label: 'module', type: 'property', info: 'Module format' },
  { label: 'moduleResolution', type: 'property', info: 'Resolution mode' },
  { label: 'strict', type: 'property', info: 'Strict mode' },
  { label: 'strictNullChecks', type: 'property', info: 'Strict null checks' },
  { label: 'strictFunctionTypes', type: 'property', info: 'Strict fn types' },
  { label: 'strictBindCallApply', type: 'property', info: 'Strict bind' },
  { label: 'strictPropertyInitialization', type: 'property', info: 'Strict init' },
  { label: 'noImplicitAny', type: 'property', info: 'No implicit any' },
  { label: 'noImplicitThis', type: 'property', info: 'No implicit this' },
  { label: 'alwaysStrict', type: 'property', info: 'Always strict' },
  { label: 'noUnusedLocals', type: 'property', info: 'No unused locals' },
  { label: 'noUnusedParameters', type: 'property', info: 'No unused params' },
  { label: 'noImplicitReturns', type: 'property', info: 'No implicit returns' },
  { label: 'noFallthroughCasesInSwitch', type: 'property', info: 'Switch check' },
  { label: 'noUncheckedIndexedAccess', type: 'property', info: 'Index access check' },
  { label: 'noPropertyAccessFromIndexSignature', type: 'property', info: 'Prop access' },
  { label: 'exactOptionalPropertyTypes', type: 'property', info: 'Exact optional' },
  { label: 'esModuleInterop', type: 'property', info: 'ESM interop' },
  { label: 'allowSyntheticDefaultImports', type: 'property', info: 'Synthetic defaults' },
  { label: 'skipLibCheck', type: 'property', info: 'Skip lib check' },
  { label: 'forceConsistentCasingInFileNames', type: 'property', info: 'Case-consistent paths' },
  { label: 'resolveJsonModule', type: 'property', info: 'Allow JSON imports' },
  { label: 'allowJs', type: 'property', info: 'Allow JS files' },
  { label: 'checkJs', type: 'property', info: 'Type-check JS' },
  { label: 'jsx', type: 'property', info: 'JSX factory' },
  { label: 'jsxFactory', type: 'property', info: 'JSX factory name' },
  { label: 'jsxFragmentFactory', type: 'property', info: 'JSX fragment fn' },
  { label: 'jsxImportSource', type: 'property', info: 'JSX import src' },
  { label: 'outDir', type: 'property', info: 'Output directory' },
  { label: 'rootDir', type: 'property', info: 'Source root' },
  { label: 'rootDirs', type: 'property', info: 'Virtual source roots' },
  { label: 'paths', type: 'property', info: 'Path aliases' },
  { label: 'baseUrl', type: 'property', info: 'Base URL for paths' },
  { label: 'typeRoots', type: 'property', info: 'Type root dirs' },
  { label: 'types', type: 'property', info: 'Included types' },
  { label: 'lib', type: 'property', info: 'Library files' },
  { label: 'declaration', type: 'property', info: 'Emit .d.ts' },
  { label: 'declarationMap', type: 'property', info: 'Emit .d.ts.map' },
  { label: 'declarationDir', type: 'property', info: 'Declaration dir' },
  { label: 'sourceMap', type: 'property', info: 'Emit source map' },
  { label: 'inlineSourceMap', type: 'property', info: 'Inline source map' },
  { label: 'inlineSources', type: 'property', info: 'Inline sources' },
  { label: 'noEmit', type: 'property', info: 'No emit output' },
  { label: 'noEmitOnError', type: 'property', info: 'No emit on error' },
  { label: 'emitDeclarationOnly', type: 'property', info: 'Only declarations' },
  { label: 'preserveConstEnums', type: 'property', info: 'Preserve const enum' },
  { label: 'isolatedModules', type: 'property', info: 'Isolated module' },
  { label: 'experimentalDecorators', type: 'property', info: 'Exp decorators' },
  { label: 'emitDecoratorMetadata', type: 'property', info: 'Decorator metadata' },
  { label: 'useDefineForClassFields', type: 'property', info: 'Class field define' },
  { label: 'verbatimModuleSyntax', type: 'property', info: 'Verbatim imports' },
  { label: 'include', type: 'property', info: 'Included files' },
  { label: 'exclude', type: 'property', info: 'Excluded files' },
  { label: 'files', type: 'property', info: 'File list' },
  { label: 'extends', type: 'property', info: 'Extend config' },
  { label: 'references', type: 'property', info: 'Project refs' },
  // ESLint
  { label: 'rules', type: 'property', info: 'ESLint rules' },
  { label: 'parser', type: 'property', info: 'ESLint parser' },
  { label: 'parserOptions', type: 'property', info: 'Parser options' },
  { label: 'plugins', type: 'property', info: 'ESLint plugins' },
  { label: 'env', type: 'property', info: 'Environment' },
  { label: 'globals', type: 'property', info: 'Global vars' },
  { label: 'overrides', type: 'property', info: 'Config overrides' },
  { label: 'ignorePatterns', type: 'property', info: 'Ignore patterns' },
  { label: 'root', type: 'property', info: 'Root config' },
  // VSCode settings
  { label: 'editor.fontSize', type: 'property', info: 'Editor font size' },
  { label: 'editor.tabSize', type: 'property', info: 'Tab size' },
  { label: 'editor.wordWrap', type: 'property', info: 'Word wrap mode' },
  { label: 'editor.formatOnSave', type: 'property', info: 'Format on save' },
  { label: 'files.autoSave', type: 'property', info: 'Auto save' },
  { label: 'files.exclude', type: 'property', info: 'Hide files' },
  { label: 'search.exclude', type: 'property', info: 'Search exclude' },
  { label: 'workbench.colorTheme', type: 'property', info: 'Color theme' },
  { label: 'terminal.integrated.fontSize', type: 'property', info: 'Term font size' },
  // Values
  { label: 'true', type: 'keyword', info: 'Boolean true' },
  { label: 'false', type: 'keyword', info: 'Boolean false' },
  { label: 'null', type: 'keyword', info: 'Null value' },
  // package.json - complete set
  { label: 'main', type: 'property', info: 'CJS entry' },
  { label: 'module', type: 'property', info: 'ESM entry' },
  { label: 'type', type: 'property', info: 'module|commonjs' },
  { label: 'exports', type: 'property', info: 'Conditional exports' },
  { label: 'imports', type: 'property', info: 'Import subpaths' },
  { label: 'browser', type: 'property', info: 'Browser entry' },
  { label: 'bin', type: 'property', info: 'Binary commands' },
  { label: 'files', type: 'property', info: 'Published files' },
  { label: 'directories', type: 'property', info: 'Dir hints' },
  { label: 'contributors', type: 'property', info: 'Contributor list' },
  { label: 'peerDependenciesMeta', type: 'property', info: 'Peer deps meta' },
  { label: 'optionalDependencies', type: 'property', info: 'Optional deps' },
  { label: 'bundledDependencies', type: 'property', info: 'Bundled deps' },
  { label: 'bundleDependencies', type: 'property', info: 'Bundled deps alias' },
  { label: 'overrides', type: 'property', info: 'npm overrides' },
  { label: 'resolutions', type: 'property', info: 'Yarn resolutions' },
  { label: 'engineStrict', type: 'property', info: 'Strict engines' },
  { label: 'os', type: 'property', info: 'Supported OS' },
  { label: 'cpu', type: 'property', info: 'Supported CPU' },
  { label: 'publishConfig', type: 'property', info: 'Publish config' },
  { label: 'packageManager', type: 'property', info: 'Corepack pkg mgr' },
  { label: 'sideEffects', type: 'property', info: 'Side-effect hint' },
  { label: 'typings', type: 'property', info: 'TS typings entry' },
  { label: 'typesVersions', type: 'property', info: 'TS typesVersions' },
  { label: 'funding', type: 'property', info: 'Funding URL' },
  { label: 'browserslist', type: 'property', info: 'Browserslist' },
  { label: 'eslintConfig', type: 'property', info: 'ESLint config' },
  { label: 'prettier', type: 'property', info: 'Prettier config' },
  { label: 'husky', type: 'property', info: 'Husky config' },
  { label: 'lint-staged', type: 'property', info: 'lint-staged config' },
  { label: 'nodemonConfig', type: 'property', info: 'nodemon config' },
  { label: 'stylelint', type: 'property', info: 'Stylelint config' },
  { label: 'babel', type: 'property', info: 'Babel config' },
  { label: 'jest', type: 'property', info: 'Jest config' },
  { label: 'mocha', type: 'property', info: 'Mocha config' },
  { label: 'ava', type: 'property', info: 'AVA config' },
  // tsconfig compilerOptions full
  { label: 'allowJs', type: 'property', info: 'Allow .js files' },
  { label: 'checkJs', type: 'property', info: 'Type-check .js' },
  { label: 'jsxImportSource', type: 'property', info: 'JSX source' },
  { label: 'declaration', type: 'property', info: 'Emit .d.ts' },
  { label: 'declarationMap', type: 'property', info: 'Emit .d.ts.map' },
  { label: 'declarationDir', type: 'property', info: 'Declarations dir' },
  { label: 'sourceMap', type: 'property', info: 'Emit .js.map' },
  { label: 'inlineSourceMap', type: 'property', info: 'Inline sourcemap' },
  { label: 'inlineSources', type: 'property', info: 'Inline sources' },
  { label: 'outFile', type: 'property', info: 'Bundle output' },
  { label: 'rootDir', type: 'property', info: 'Common root' },
  { label: 'rootDirs', type: 'property', info: 'Virtual roots' },
  { label: 'composite', type: 'property', info: 'Enable project refs' },
  { label: 'tsBuildInfoFile', type: 'property', info: 'Incremental cache' },
  { label: 'incremental', type: 'property', info: 'Incremental compile' },
  { label: 'isolatedModules', type: 'property', info: 'Transpile-safe' },
  { label: 'isolatedDeclarations', type: 'property', info: 'Isolated d.ts' },
  { label: 'verbatimModuleSyntax', type: 'property', info: 'Literal imports' },
  { label: 'esModuleInterop', type: 'property', info: 'ESM interop' },
  { label: 'allowSyntheticDefaultImports', type: 'property', info: 'Synthetic imports' },
  { label: 'forceConsistentCasingInFileNames', type: 'property', info: 'Case-strict fs' },
  { label: 'strict', type: 'property', info: 'All strict checks' },
  { label: 'noImplicitAny', type: 'property', info: 'No implicit any' },
  { label: 'strictNullChecks', type: 'property', info: 'Null-safe' },
  { label: 'strictFunctionTypes', type: 'property', info: 'Bivariance fix' },
  { label: 'strictBindCallApply', type: 'property', info: 'Bind/call/apply' },
  { label: 'strictPropertyInitialization', type: 'property', info: 'Ctor init' },
  { label: 'noImplicitThis', type: 'property', info: 'No implicit this' },
  { label: 'useUnknownInCatchVariables', type: 'property', info: 'catch => unknown' },
  { label: 'alwaysStrict', type: 'property', info: 'emit use strict' },
  { label: 'noUnusedLocals', type: 'property', info: 'Unused local err' },
  { label: 'noUnusedParameters', type: 'property', info: 'Unused param err' },
  { label: 'noImplicitReturns', type: 'property', info: 'Return in all paths' },
  { label: 'noFallthroughCasesInSwitch', type: 'property', info: 'No fallthrough' },
  { label: 'noUncheckedIndexedAccess', type: 'property', info: 'Index => T | undef' },
  { label: 'noImplicitOverride', type: 'property', info: 'Require override' },
  { label: 'noPropertyAccessFromIndexSignature', type: 'property', info: 'Index only' },
  { label: 'allowUnusedLabels', type: 'property', info: 'Allow unused labels' },
  { label: 'allowUnreachableCode', type: 'property', info: 'Allow unreachable' },
  { label: 'moduleResolution', type: 'property', info: 'Resolution algo' },
  { label: 'baseUrl', type: 'property', info: 'Non-relative base' },
  { label: 'paths', type: 'property', info: 'Path mapping' },
  { label: 'typeRoots', type: 'property', info: 'Type roots' },
  { label: 'types', type: 'property', info: 'Type packages' },
  { label: 'allowUmdGlobalAccess', type: 'property', info: 'UMD globals' },
  { label: 'moduleSuffixes', type: 'property', info: 'Module suffixes' },
  { label: 'resolvePackageJsonExports', type: 'property', info: 'Use exports' },
  { label: 'resolvePackageJsonImports', type: 'property', info: 'Use imports' },
  { label: 'customConditions', type: 'property', info: 'Custom conditions' },
  { label: 'resolveJsonModule', type: 'property', info: 'Import JSON' },
  { label: 'allowArbitraryExtensions', type: 'property', info: 'Allow any ext' },
  { label: 'noResolve', type: 'property', info: 'Skip resolution' },
  { label: 'allowImportingTsExtensions', type: 'property', info: 'Import .ts' },
  { label: 'disableSizeLimit', type: 'property', info: 'Disable size cap' },
  { label: 'disableSourceOfProjectReferenceRedirect', type: 'property', info: 'Proj ref redirect' },
  { label: 'disableSolutionSearching', type: 'property', info: 'Solution search off' },
  { label: 'disableReferencedProjectLoad', type: 'property', info: 'Ref proj load off' },
  { label: 'emitDeclarationOnly', type: 'property', info: 'Only .d.ts' },
  { label: 'importHelpers', type: 'property', info: 'Use tslib' },
  { label: 'downlevelIteration', type: 'property', info: 'Down-level iter' },
  { label: 'newLine', type: 'property', info: 'Newline style' },
  { label: 'stripInternal', type: 'property', info: 'Strip @internal' },
  { label: 'noEmit', type: 'property', info: 'Do not emit' },
  { label: 'noEmitHelpers', type: 'property', info: 'No tslib emit' },
  { label: 'noEmitOnError', type: 'property', info: 'Skip emit on err' },
  { label: 'preserveConstEnums', type: 'property', info: 'Const enums' },
  { label: 'removeComments', type: 'property', info: 'Strip comments' },
  { label: 'importsNotUsedAsValues', type: 'property', info: 'Import style' },
  { label: 'jsxFactory', type: 'property', info: 'JSX factory' },
  { label: 'jsxFragmentFactory', type: 'property', info: 'JSX fragment' },
  { label: 'reactNamespace', type: 'property', info: 'React namespace' },
  { label: 'skipLibCheck', type: 'property', info: 'Skip .d.ts check' },
  { label: 'skipDefaultLibCheck', type: 'property', info: 'Skip default lib' },
  { label: 'preserveSymlinks', type: 'property', info: 'Preserve symlinks' },
  { label: 'preserveWatchOutput', type: 'property', info: 'Preserve output' },
  { label: 'preserveValueImports', type: 'property', info: 'Preserve imports' },
  { label: 'maxNodeModuleJsDepth', type: 'property', info: 'JS depth' },
  { label: 'noLib', type: 'property', info: 'No default lib' },
  { label: 'charset', type: 'property', info: 'Source charset' },
  { label: 'mapRoot', type: 'property', info: 'Map root' },
  { label: 'sourceRoot', type: 'property', info: 'Source root' },
  { label: 'experimentalDecorators', type: 'property', info: 'Exp decorators' },
  { label: 'emitDecoratorMetadata', type: 'property', info: 'Emit meta' },
  { label: 'useDefineForClassFields', type: 'property', info: 'ES define fields' },
  { label: 'include', type: 'property', info: 'Files include' },
  { label: 'exclude', type: 'property', info: 'Files exclude' },
  { label: 'references', type: 'property', info: 'Project refs' },
  { label: 'extends', type: 'property', info: 'Base tsconfig' },
  { label: 'watchOptions', type: 'property', info: 'TS watch opts' },
  // TS compiler values
  { label: '"ES3"', type: 'value', info: 'ES3 target' },
  { label: '"ES5"', type: 'value', info: 'ES5 target' },
  { label: '"ES2015"', type: 'value', info: 'ES2015' },
  { label: '"ES2016"', type: 'value', info: 'ES2016' },
  { label: '"ES2017"', type: 'value', info: 'ES2017' },
  { label: '"ES2018"', type: 'value', info: 'ES2018' },
  { label: '"ES2019"', type: 'value', info: 'ES2019' },
  { label: '"ES2020"', type: 'value', info: 'ES2020' },
  { label: '"ES2021"', type: 'value', info: 'ES2021' },
  { label: '"ES2022"', type: 'value', info: 'ES2022' },
  { label: '"ES2023"', type: 'value', info: 'ES2023' },
  { label: '"ESNext"', type: 'value', info: 'Latest ES' },
  { label: '"CommonJS"', type: 'value', info: 'CJS modules' },
  { label: '"Node"', type: 'value', info: 'Node resolution' },
  { label: '"Node10"', type: 'value', info: 'Node10 resolution' },
  { label: '"Node16"', type: 'value', info: 'Node16 resolution' },
  { label: '"NodeNext"', type: 'value', info: 'NodeNext resolution' },
  { label: '"Bundler"', type: 'value', info: 'Bundler resolution' },
  { label: '"Classic"', type: 'value', info: 'Classic resolution' },
  { label: '"react"', type: 'value', info: 'JSX react' },
  { label: '"react-jsx"', type: 'value', info: 'JSX react-jsx' },
  { label: '"react-jsxdev"', type: 'value', info: 'JSX react-jsxdev' },
  { label: '"react-native"', type: 'value', info: 'JSX react-native' },
  { label: '"preserve"', type: 'value', info: 'JSX preserve' },
  // ESLint flat config
  { label: 'languageOptions', type: 'property', info: 'ESLint lang opts' },
  { label: 'globals', type: 'property', info: 'ESLint globals' },
  { label: 'parser', type: 'property', info: 'ESLint parser' },
  { label: 'parserOptions', type: 'property', info: 'ESLint parser opts' },
  { label: 'rules', type: 'property', info: 'ESLint rules' },
  { label: 'plugins', type: 'property', info: 'ESLint plugins' },
  { label: 'ignores', type: 'property', info: 'Ignore patterns' },
  { label: 'processor', type: 'property', info: 'File processor' },
  { label: 'linterOptions', type: 'property', info: 'Linter options' },
  { label: 'settings', type: 'property', info: 'Shared settings' },
  { label: 'ecmaVersion', type: 'property', info: 'ECMA version' },
  { label: 'sourceType', type: 'property', info: 'module|script' },
  { label: 'ecmaFeatures', type: 'property', info: 'Extra features' },
  { label: 'project', type: 'property', info: 'TS project' },
  { label: 'tsconfigRootDir', type: 'property', info: 'tsconfig root' },
  { label: 'extraFileExtensions', type: 'property', info: 'Extra extensions' },
  // Prettier
  { label: 'semi', type: 'property', info: 'Use semicolons' },
  { label: 'singleQuote', type: 'property', info: 'Single quotes' },
  { label: 'quoteProps', type: 'property', info: 'Quote obj props' },
  { label: 'jsxSingleQuote', type: 'property', info: 'JSX single quotes' },
  { label: 'trailingComma', type: 'property', info: 'Trailing commas' },
  { label: 'bracketSpacing', type: 'property', info: 'Obj bracket space' },
  { label: 'bracketSameLine', type: 'property', info: 'Bracket same line' },
  { label: 'arrowParens', type: 'property', info: 'Arrow parens' },
  { label: 'rangeStart', type: 'property', info: 'Range start' },
  { label: 'rangeEnd', type: 'property', info: 'Range end' },
  { label: 'filepath', type: 'property', info: 'File path parser' },
  { label: 'requirePragma', type: 'property', info: 'Require pragma' },
  { label: 'insertPragma', type: 'property', info: 'Insert pragma' },
  { label: 'proseWrap', type: 'property', info: 'Prose wrap' },
  { label: 'htmlWhitespaceSensitivity', type: 'property', info: 'HTML whitespace' },
  { label: 'vueIndentScriptAndStyle', type: 'property', info: 'Vue indent' },
  { label: 'endOfLine', type: 'property', info: 'EOL style' },
  { label: 'embeddedLanguageFormatting', type: 'property', info: 'Embed fmt' },
  { label: 'singleAttributePerLine', type: 'property', info: 'Attr per line' },
  { label: 'printWidth', type: 'property', info: 'Print width' },
  { label: 'tabWidth', type: 'property', info: 'Tab width' },
  { label: 'useTabs', type: 'property', info: 'Use tabs' },
  { label: 'overrides', type: 'property', info: 'Per-file overrides' },
  // Deno config
  { label: 'tasks', type: 'property', info: 'Deno tasks' },
  { label: 'importMap', type: 'property', info: 'Import map path' },
  { label: 'lint', type: 'property', info: 'Deno lint config' },
  { label: 'fmt', type: 'property', info: 'Deno fmt config' },
  { label: 'lock', type: 'property', info: 'Lock file' },
  { label: 'nodeModulesDir', type: 'property', info: 'node_modules dir' },
  { label: 'unstable', type: 'property', info: 'Unstable flags' },
  // VS Code settings
  { label: 'editor.tabSize', type: 'property', info: 'Editor tab size' },
  { label: 'editor.insertSpaces', type: 'property', info: 'Insert spaces' },
  { label: 'editor.formatOnSave', type: 'property', info: 'Format on save' },
  { label: 'editor.formatOnPaste', type: 'property', info: 'Format on paste' },
  { label: 'editor.formatOnType', type: 'property', info: 'Format on type' },
  { label: 'editor.codeActionsOnSave', type: 'property', info: 'Code actions' },
  { label: 'editor.defaultFormatter', type: 'property', info: 'Default formatter' },
  { label: 'editor.fontFamily', type: 'property', info: 'Font family' },
  { label: 'editor.fontLigatures', type: 'property', info: 'Font ligatures' },
  { label: 'editor.lineHeight', type: 'property', info: 'Line height' },
  { label: 'editor.rulers', type: 'property', info: 'Column rulers' },
  { label: 'editor.wordWrap', type: 'property', info: 'Word wrap' },
  { label: 'editor.minimap.enabled', type: 'property', info: 'Minimap on/off' },
  { label: 'editor.renderWhitespace', type: 'property', info: 'Show whitespace' },
  { label: 'editor.cursorBlinking', type: 'property', info: 'Cursor blink' },
  { label: 'editor.cursorStyle', type: 'property', info: 'Cursor style' },
  { label: 'editor.cursorSmoothCaretAnimation', type: 'property', info: 'Smooth caret' },
  { label: 'editor.smoothScrolling', type: 'property', info: 'Smooth scroll' },
  { label: 'editor.quickSuggestions', type: 'property', info: 'Quick suggest' },
  { label: 'editor.suggestOnTriggerCharacters', type: 'property', info: 'Suggest trigger' },
  { label: 'editor.snippetSuggestions', type: 'property', info: 'Snippet suggest' },
  { label: 'editor.parameterHints.enabled', type: 'property', info: 'Param hints' },
  { label: 'editor.inlineSuggest.enabled', type: 'property', info: 'Inline suggest' },
  { label: 'editor.bracketPairColorization.enabled', type: 'property', info: 'Bracket pairs' },
  { label: 'files.encoding', type: 'property', info: 'File encoding' },
  { label: 'files.eol', type: 'property', info: 'Default EOL' },
  { label: 'files.trimTrailingWhitespace', type: 'property', info: 'Trim trailing' },
  { label: 'files.insertFinalNewline', type: 'property', info: 'Final newline' },
  { label: 'files.trimFinalNewlines', type: 'property', info: 'Trim finals' },
  { label: 'files.exclude', type: 'property', info: 'Files exclude' },
  { label: 'files.watcherExclude', type: 'property', info: 'Watcher exclude' },
  { label: 'files.associations', type: 'property', info: 'File assoc' },
  { label: 'files.autoSave', type: 'property', info: 'Auto save' },
  { label: 'files.autoSaveDelay', type: 'property', info: 'Auto save delay' },
  { label: 'files.defaultLanguage', type: 'property', info: 'Default lang' },
  { label: 'terminal.integrated.shell.linux', type: 'property', info: 'Linux shell' },
  { label: 'terminal.integrated.shell.osx', type: 'property', info: 'macOS shell' },
  { label: 'terminal.integrated.shell.windows', type: 'property', info: 'Windows shell' },
  { label: 'terminal.integrated.defaultProfile.linux', type: 'property', info: 'Linux profile' },
  { label: 'terminal.integrated.defaultProfile.osx', type: 'property', info: 'macOS profile' },
  { label: 'terminal.integrated.defaultProfile.windows', type: 'property', info: 'Win profile' },
  { label: 'terminal.integrated.fontFamily', type: 'property', info: 'Term font' },
  { label: 'terminal.integrated.scrollback', type: 'property', info: 'Scrollback' },
  { label: 'terminal.integrated.cursorBlinking', type: 'property', info: 'Term blink' },
  { label: 'workbench.iconTheme', type: 'property', info: 'Icon theme' },
  { label: 'workbench.editor.showTabs', type: 'property', info: 'Show tabs' },
  { label: 'workbench.editor.tabCloseButton', type: 'property', info: 'Tab close btn' },
  { label: 'workbench.startupEditor', type: 'property', info: 'Startup editor' },
  { label: 'workbench.list.smoothScrolling', type: 'property', info: 'Smooth list' },
  { label: 'workbench.tree.indent', type: 'property', info: 'Tree indent' },
  { label: 'workbench.sideBar.location', type: 'property', info: 'Side bar loc' },
  { label: 'search.useIgnoreFiles', type: 'property', info: 'Use ignore' },
  { label: 'search.useGlobalIgnoreFiles', type: 'property', info: 'Global ignore' },
  { label: 'search.smartCase', type: 'property', info: 'Smart case' },
  { label: 'git.autofetch', type: 'property', info: 'Git autofetch' },
  { label: 'git.confirmSync', type: 'property', info: 'Confirm sync' },
  { label: 'git.enableSmartCommit', type: 'property', info: 'Smart commit' },
  { label: 'git.enableStatusBarSync', type: 'property', info: 'Status bar sync' },
  { label: 'git.fetchOnPull', type: 'property', info: 'Fetch on pull' },
  { label: 'git.postCommitCommand', type: 'property', info: 'Post-commit' },
  { label: 'git.pruneOnFetch', type: 'property', info: 'Prune on fetch' },
  { label: 'git.rebaseWhenSync', type: 'property', info: 'Rebase on sync' },
  { label: 'git.inputValidation', type: 'property', info: 'Input validation' },
  { label: 'git.untrackedChanges', type: 'property', info: 'Untracked changes' },
  // JSON Schema keywords
  { label: '$schema', type: 'property', info: 'Schema URI' },
  { label: '$id', type: 'property', info: 'Schema ID' },
  { label: '$ref', type: 'property', info: 'Schema ref' },
  { label: '$defs', type: 'property', info: 'Schema defs' },
  { label: '$anchor', type: 'property', info: 'Schema anchor' },
  { label: '$dynamicRef', type: 'property', info: 'Dynamic ref' },
  { label: '$dynamicAnchor', type: 'property', info: 'Dynamic anchor' },
  { label: '$vocabulary', type: 'property', info: 'Vocabulary' },
  { label: '$comment', type: 'property', info: 'Schema comment' },
  { label: 'definitions', type: 'property', info: 'Legacy defs' },
  { label: 'title', type: 'property', info: 'Schema title' },
  { label: 'description', type: 'property', info: 'Schema desc' },
  { label: 'default', type: 'property', info: 'Default value' },
  { label: 'examples', type: 'property', info: 'Examples list' },
  { label: 'readOnly', type: 'property', info: 'Read-only flag' },
  { label: 'writeOnly', type: 'property', info: 'Write-only flag' },
  { label: 'deprecated', type: 'property', info: 'Deprecated flag' },
  { label: 'enum', type: 'property', info: 'Enum values' },
  { label: 'const', type: 'property', info: 'Const value' },
  { label: 'format', type: 'property', info: 'Format hint' },
  { label: 'properties', type: 'property', info: 'Object props' },
  { label: 'patternProperties', type: 'property', info: 'Pattern props' },
  { label: 'additionalProperties', type: 'property', info: 'Extra props' },
  { label: 'unevaluatedProperties', type: 'property', info: 'Unevaluated' },
  { label: 'required', type: 'property', info: 'Required list' },
  { label: 'dependentRequired', type: 'property', info: 'Dependent req' },
  { label: 'dependentSchemas', type: 'property', info: 'Dependent schemas' },
  { label: 'propertyNames', type: 'property', info: 'Property names' },
  { label: 'minProperties', type: 'property', info: 'Min props' },
  { label: 'maxProperties', type: 'property', info: 'Max props' },
  { label: 'items', type: 'property', info: 'Array items' },
  { label: 'prefixItems', type: 'property', info: 'Prefix items' },
  { label: 'contains', type: 'property', info: 'Must contain' },
  { label: 'minContains', type: 'property', info: 'Min contains' },
  { label: 'maxContains', type: 'property', info: 'Max contains' },
  { label: 'minItems', type: 'property', info: 'Min items' },
  { label: 'maxItems', type: 'property', info: 'Max items' },
  { label: 'uniqueItems', type: 'property', info: 'Unique items' },
  { label: 'unevaluatedItems', type: 'property', info: 'Unevaluated items' },
  { label: 'minLength', type: 'property', info: 'Min length' },
  { label: 'maxLength', type: 'property', info: 'Max length' },
  { label: 'pattern', type: 'property', info: 'Regex pattern' },
  { label: 'contentEncoding', type: 'property', info: 'Content encoding' },
  { label: 'contentMediaType', type: 'property', info: 'Content type' },
  { label: 'contentSchema', type: 'property', info: 'Content schema' },
  { label: 'minimum', type: 'property', info: 'Min value' },
  { label: 'maximum', type: 'property', info: 'Max value' },
  { label: 'exclusiveMinimum', type: 'property', info: 'Excl min' },
  { label: 'exclusiveMaximum', type: 'property', info: 'Excl max' },
  { label: 'multipleOf', type: 'property', info: 'Multiple of' },
  { label: 'allOf', type: 'property', info: 'All schemas' },
  { label: 'anyOf', type: 'property', info: 'Any schema' },
  { label: 'oneOf', type: 'property', info: 'One schema' },
  { label: 'not', type: 'property', info: 'Not schema' },
  { label: 'if', type: 'property', info: 'Conditional if' },
  { label: 'then', type: 'property', info: 'Conditional then' },
  { label: 'else', type: 'property', info: 'Conditional else' },
  // JSON Schema values
  { label: '"string"', type: 'value', info: 'Type string' },
  { label: '"number"', type: 'value', info: 'Type number' },
  { label: '"integer"', type: 'value', info: 'Type integer' },
  { label: '"boolean"', type: 'value', info: 'Type boolean' },
  { label: '"object"', type: 'value', info: 'Type object' },
  { label: '"array"', type: 'value', info: 'Type array' },
  { label: '"null"', type: 'value', info: 'Type null' },
  { label: '"date-time"', type: 'value', info: 'Format date-time' },
  { label: '"date"', type: 'value', info: 'Format date' },
  { label: '"time"', type: 'value', info: 'Format time' },
  { label: '"duration"', type: 'value', info: 'Format duration' },
  { label: '"email"', type: 'value', info: 'Format email' },
  { label: '"hostname"', type: 'value', info: 'Format hostname' },
  { label: '"ipv4"', type: 'value', info: 'Format IPv4' },
  { label: '"ipv6"', type: 'value', info: 'Format IPv6' },
  { label: '"uri"', type: 'value', info: 'Format URI' },
  { label: '"uri-reference"', type: 'value', info: 'Format URI-ref' },
  { label: '"uuid"', type: 'value', info: 'Format UUID' },
  { label: '"regex"', type: 'value', info: 'Format regex' },
  { label: '"json-pointer"', type: 'value', info: 'JSON pointer' },
  { label: '"relative-json-pointer"', type: 'value', info: 'Rel JSON pointer' },
  // Renovate
  { label: 'extends', type: 'property', info: 'Renovate presets' },
  { label: 'timezone', type: 'property', info: 'Renovate timezone' },
  { label: 'schedule', type: 'property', info: 'Renovate schedule' },
  { label: 'packageRules', type: 'property', info: 'Renovate rules' },
  { label: 'major', type: 'property', info: 'Major policy' },
  { label: 'minor', type: 'property', info: 'Minor policy' },
  { label: 'patch', type: 'property', info: 'Patch policy' },
  { label: 'rangeStrategy', type: 'property', info: 'Range strategy' },
  { label: 'prCreation', type: 'property', info: 'PR creation' },
  { label: 'automerge', type: 'property', info: 'Auto merge' },
  { label: 'automergeType', type: 'property', info: 'Auto merge type' },
  { label: 'automergeStrategy', type: 'property', info: 'Auto merge strategy' },
  { label: 'labels', type: 'property', info: 'PR labels' },
  { label: 'reviewers', type: 'property', info: 'PR reviewers' },
  { label: 'assignees', type: 'property', info: 'PR assignees' },
  { label: 'dependencyDashboard', type: 'property', info: 'Dep dashboard' },
  { label: 'prConcurrentLimit', type: 'property', info: 'PR concurrency' },
  { label: 'prHourlyLimit', type: 'property', info: 'PR hourly limit' },
  // Dependabot
  { label: 'updates', type: 'property', info: 'Dependabot updates' },
  { label: 'package-ecosystem', type: 'property', info: 'Ecosystem' },
  { label: 'directory', type: 'property', info: 'Lockfile dir' },
  { label: 'interval', type: 'property', info: 'Schedule interval' },
  { label: 'day', type: 'property', info: 'Schedule day' },
  { label: 'target-branch', type: 'property', info: 'Target branch' },
  { label: 'open-pull-requests-limit', type: 'property', info: 'Open PR limit' },
  { label: 'commit-message', type: 'property', info: 'Commit message' },
  { label: 'pull-request-branch-name', type: 'property', info: 'Branch naming' },
  { label: 'rebase-strategy', type: 'property', info: 'Rebase strategy' },
  // launch.json
  { label: 'request', type: 'property', info: 'Request kind' },
  { label: 'program', type: 'property', info: 'Program path' },
  { label: 'args', type: 'property', info: 'Launch args' },
  { label: 'cwd', type: 'property', info: 'Working dir' },
  { label: 'env', type: 'property', info: 'Env vars' },
  { label: 'console', type: 'property', info: 'Console kind' },
  { label: 'stopOnEntry', type: 'property', info: 'Stop on entry' },
  { label: 'preLaunchTask', type: 'property', info: 'Pre-launch task' },
  { label: 'postDebugTask', type: 'property', info: 'Post debug task' },
  { label: 'internalConsoleOptions', type: 'property', info: 'Internal console' },
  { label: 'outFiles', type: 'property', info: 'outFiles' },
  { label: 'sourceMaps', type: 'property', info: 'Source maps' },
  { label: 'runtimeExecutable', type: 'property', info: 'Runtime exe' },
  { label: 'runtimeArgs', type: 'property', info: 'Runtime args' },
  { label: 'processId', type: 'property', info: 'Attach PID' },
  { label: 'port', type: 'property', info: 'Debug port' },
  { label: 'remoteRoot', type: 'property', info: 'Remote root' },
  { label: 'localRoot', type: 'property', info: 'Local root' },
  // tasks.json
  { label: 'label', type: 'property', info: 'Task label' },
  { label: 'command', type: 'property', info: 'Task command' },
  { label: 'group', type: 'property', info: 'Task group' },
  { label: 'presentation', type: 'property', info: 'Presentation' },
  { label: 'problemMatcher', type: 'property', info: 'Problem matcher' },
  { label: 'isBackground', type: 'property', info: 'Background task' },
  { label: 'runOptions', type: 'property', info: 'Run options' },
  { label: 'dependsOn', type: 'property', info: 'Depends on' },
  { label: 'dependsOrder', type: 'property', info: 'Depends order' },
  // exports conditions
  { label: '"./*"', type: 'value', info: 'Export all subpath' },
  { label: '"./package.json"', type: 'value', info: 'Export manifest' },
  { label: '"."', type: 'value', info: 'Main export key' },
  { label: '"import"', type: 'value', info: 'ESM condition' },
  { label: '"require"', type: 'value', info: 'CJS condition' },
  { label: '"default"', type: 'value', info: 'Fallback cond' },
  { label: '"types"', type: 'value', info: 'Types cond' },
  { label: '"node"', type: 'value', info: 'Node cond' },
  { label: '"browser"', type: 'value', info: 'Browser cond' },
  { label: '"deno"', type: 'value', info: 'Deno cond' },
  { label: '"workerd"', type: 'value', info: 'workerd cond' },
  { label: '"bun"', type: 'value', info: 'Bun cond' },
  { label: '"react-native"', type: 'value', info: 'RN cond' },
  // Browserslist values
  { label: '"> 1%"', type: 'value', info: 'Global >1%' },
  { label: '"last 2 versions"', type: 'value', info: 'Last 2 versions' },
  { label: '"not dead"', type: 'value', info: 'Not dead' },
  { label: '"not ie <= 11"', type: 'value', info: 'No IE' },
  { label: '"since 2020"', type: 'value', info: 'Since year' },
  // Firebase firebase.json
  { label: 'hosting', type: 'property', info: 'Firebase hosting' },
  { label: 'functions', type: 'property', info: 'Firebase functions' },
  { label: 'firestore', type: 'property', info: 'Firebase Firestore' },
  { label: 'storage', type: 'property', info: 'Firebase storage' },
  { label: 'database', type: 'property', info: 'RTDB config' },
  { label: 'emulators', type: 'property', info: 'Emulator config' },
  { label: 'extensions', type: 'property', info: 'Firebase exts' },
  { label: 'remoteconfig', type: 'property', info: 'Remote config' },
  // Serverless as JSON
  { label: 'provider', type: 'property', info: 'SLS provider' },
  { label: 'handler', type: 'property', info: 'Fn handler' },
  { label: 'events', type: 'property', info: 'Fn events' },
  { label: 'timeout', type: 'property', info: 'Fn timeout' },
  { label: 'memorySize', type: 'property', info: 'Fn memory' },
  { label: 'runtime', type: 'property', info: 'Fn runtime' },
  { label: 'region', type: 'property', info: 'Fn region' },
  { label: 'stage', type: 'property', info: 'SLS stage' },
  // CloudFormation
  { label: 'AWSTemplateFormatVersion', type: 'property', info: 'CFN version' },
  { label: 'Resources', type: 'property', info: 'CFN resources' },
  { label: 'Parameters', type: 'property', info: 'CFN parameters' },
  { label: 'Outputs', type: 'property', info: 'CFN outputs' },
  { label: 'Mappings', type: 'property', info: 'CFN mappings' },
  { label: 'Conditions', type: 'property', info: 'CFN conditions' },
  { label: 'Transform', type: 'property', info: 'CFN transform' },
  { label: 'Metadata', type: 'property', info: 'CFN metadata' },
  { label: 'Type', type: 'property', info: 'Resource type' },
  { label: 'Properties', type: 'property', info: 'Resource props' },
  { label: 'DependsOn', type: 'property', info: 'Resource deps' },
  // EditorConfig fields
  { label: 'indent_style', type: 'property', info: 'Indent style' },
  { label: 'indent_size', type: 'property', info: 'Indent size' },
  { label: 'tab_width', type: 'property', info: 'Tab width' },
  { label: 'end_of_line', type: 'property', info: 'End of line' },
  { label: 'trim_trailing_whitespace', type: 'property', info: 'Trim trailing ws' },
  { label: 'insert_final_newline', type: 'property', info: 'Final newline' },
  { label: 'max_line_length', type: 'property', info: 'Max line length' },
  // Common snippets
  { label: 'scripts-dev', type: 'snippet', apply: '"dev": "vite"', info: 'Vite dev' },
  { label: 'scripts-build', type: 'snippet', apply: '"build": "vite build"', info: 'Vite build' },
  { label: 'scripts-test', type: 'snippet', apply: '"test": "vitest"', info: 'Vitest' },
  { label: 'scripts-lint', type: 'snippet', apply: '"lint": "eslint ."', info: 'ESLint' },
  { label: 'scripts-format', type: 'snippet', apply: '"format": "prettier --write ."', info: 'Prettier' },
  // Common SemVer operators
  { label: '"^1.0.0"', type: 'value', info: 'Caret range' },
  { label: '"~1.0.0"', type: 'value', info: 'Tilde range' },
  { label: '">=1.0.0"', type: 'value', info: 'Min version' },
  { label: '"*"', type: 'value', info: 'Any version' },
  { label: '"latest"', type: 'value', info: 'Latest dist-tag' },
  { label: '"next"', type: 'value', info: 'Next dist-tag' },
  // VS Code language-specific
  { label: '[javascript]', type: 'property', info: 'Per-lang JS' },
  { label: '[typescript]', type: 'property', info: 'Per-lang TS' },
  { label: '[javascriptreact]', type: 'property', info: 'Per-lang JSX' },
  { label: '[typescriptreact]', type: 'property', info: 'Per-lang TSX' },
  { label: '[json]', type: 'property', info: 'Per-lang JSON' },
  { label: '[jsonc]', type: 'property', info: 'Per-lang JSONC' },
  { label: '[html]', type: 'property', info: 'Per-lang HTML' },
  { label: '[css]', type: 'property', info: 'Per-lang CSS' },
  { label: '[scss]', type: 'property', info: 'Per-lang SCSS' },
  { label: '[less]', type: 'property', info: 'Per-lang LESS' },
  { label: '[markdown]', type: 'property', info: 'Per-lang MD' },
  { label: '[yaml]', type: 'property', info: 'Per-lang YAML' },
  { label: '[python]', type: 'property', info: 'Per-lang Python' },
  { label: '[rust]', type: 'property', info: 'Per-lang Rust' },
  { label: '[go]', type: 'property', info: 'Per-lang Go' },
  { label: '[java]', type: 'property', info: 'Per-lang Java' },
  // AppCompat and platforms
  { label: '"darwin"', type: 'value', info: 'macOS' },
  { label: '"linux"', type: 'value', info: 'Linux' },
  { label: '"win32"', type: 'value', info: 'Windows' },
  { label: '"freebsd"', type: 'value', info: 'FreeBSD' },
  { label: '"openbsd"', type: 'value', info: 'OpenBSD' },
  { label: '"sunos"', type: 'value', info: 'SunOS' },
  { label: '"aix"', type: 'value', info: 'AIX' },
  { label: '"x64"', type: 'value', info: 'x86_64' },
  { label: '"arm"', type: 'value', info: 'ARM' },
  { label: '"arm64"', type: 'value', info: 'ARM64' },
  { label: '"ia32"', type: 'value', info: 'x86' },
  { label: '"mips"', type: 'value', info: 'MIPS' },
  { label: '"ppc"', type: 'value', info: 'PPC' },
  { label: '"ppc64"', type: 'value', info: 'PPC64' },
  { label: '"s390"', type: 'value', info: 's390' },
  { label: '"s390x"', type: 'value', info: 's390x' },
  // Rollup / webpack common keys
  { label: 'entry', type: 'property', info: 'Build entry' },
  { label: 'output', type: 'property', info: 'Build output' },
  { label: 'plugins', type: 'property', info: 'Build plugins' },
  { label: 'external', type: 'property', info: 'External mods' },
  { label: 'cacheDir', type: 'property', info: 'Cache dir' },
  { label: 'alias', type: 'property', info: 'Import alias' },
  { label: 'resolve', type: 'property', info: 'Resolve config' },
  { label: 'loader', type: 'property', info: 'Webpack loader' },
  { label: 'devServer', type: 'property', info: 'Dev server' },
  { label: 'proxy', type: 'property', info: 'Dev server proxy' },
  // Vite keys
  { label: 'root', type: 'property', info: 'Project root' },
  { label: 'base', type: 'property', info: 'Public base' },
  { label: 'publicDir', type: 'property', info: 'Static assets dir' },
  { label: 'assetsInclude', type: 'property', info: 'Asset patterns' },
  { label: 'build', type: 'property', info: 'Build config' },
  { label: 'server', type: 'property', info: 'Dev server config' },
  { label: 'preview', type: 'property', info: 'Preview config' },
  { label: 'optimizeDeps', type: 'property', info: 'Optimize deps' },
  { label: 'ssr', type: 'property', info: 'SSR config' },
  { label: 'worker', type: 'property', info: 'Worker config' },
  { label: 'define', type: 'property', info: 'Global defines' },
  // webpack output
  { label: 'path', type: 'property', info: 'Output path' },
  { label: 'filename', type: 'property', info: 'Output filename' },
  { label: 'chunkFilename', type: 'property', info: 'Chunk filename' },
  { label: 'publicPath', type: 'property', info: 'Public URL' },
  { label: 'library', type: 'property', info: 'Library name' },
  { label: 'libraryTarget', type: 'property', info: 'Library target' },
  { label: 'globalObject', type: 'property', info: 'Global object' },
  { label: 'clean', type: 'property', info: 'Clean output' },
  // babel keys
  { label: 'presets', type: 'property', info: 'Babel presets' },
  { label: 'plugins', type: 'property', info: 'Babel plugins' },
  { label: 'sourceType', type: 'property', info: 'Module source' },
  { label: 'targets', type: 'property', info: 'Target envs' },
  { label: 'assumptions', type: 'property', info: 'Babel assumptions' },
  { label: 'env', type: 'property', info: 'Env-specific config' },
  // devcontainer.json
  { label: 'name', type: 'property', info: 'Devcontainer name' },
  { label: 'image', type: 'property', info: 'Container image' },
  { label: 'build', type: 'property', info: 'Build config' },
  { label: 'dockerFile', type: 'property', info: 'Dockerfile path' },
  { label: 'context', type: 'property', info: 'Build context' },
  { label: 'runArgs', type: 'property', info: 'Run args' },
  { label: 'mounts', type: 'property', info: 'Bind mounts' },
  { label: 'workspaceFolder', type: 'property', info: 'Workspace folder' },
  { label: 'workspaceMount', type: 'property', info: 'Workspace mount' },
  { label: 'remoteUser', type: 'property', info: 'Remote user' },
  { label: 'containerUser', type: 'property', info: 'Container user' },
  { label: 'updateRemoteUserUID', type: 'property', info: 'Update UID' },
  { label: 'forwardPorts', type: 'property', info: 'Forward ports' },
  { label: 'postCreateCommand', type: 'property', info: 'Post-create cmd' },
  { label: 'postStartCommand', type: 'property', info: 'Post-start cmd' },
  { label: 'postAttachCommand', type: 'property', info: 'Post-attach cmd' },
  { label: 'onCreateCommand', type: 'property', info: 'On-create cmd' },
  { label: 'updateContentCommand', type: 'property', info: 'Update content' },
  { label: 'features', type: 'property', info: 'Devcontainer features' },
  { label: 'customizations', type: 'property', info: 'Customizations' },
  { label: 'shutdownAction', type: 'property', info: 'Shutdown action' },
  { label: 'overrideCommand', type: 'property', info: 'Override cmd' },
  // ESLint common rule IDs
  { label: '"no-unused-vars"', type: 'rule', info: 'ESLint rule' },
  { label: '"no-console"', type: 'rule', info: 'ESLint rule' },
  { label: '"no-debugger"', type: 'rule', info: 'ESLint rule' },
  { label: '"eqeqeq"', type: 'rule', info: 'Require ===' },
  { label: '"no-var"', type: 'rule', info: 'No var' },
  { label: '"prefer-const"', type: 'rule', info: 'Prefer const' },
  { label: '"no-undef"', type: 'rule', info: 'No undefined refs' },
  { label: '"curly"', type: 'rule', info: 'Require curly' },
  { label: '"semi"', type: 'rule', info: 'Require/disallow ;' },
  { label: '"quotes"', type: 'rule', info: 'Quote style' },
  { label: '"indent"', type: 'rule', info: 'Indent rule' },
  { label: '"comma-dangle"', type: 'rule', info: 'Trailing commas' },
  { label: '"no-multi-spaces"', type: 'rule', info: 'No multi spaces' },
  { label: '"arrow-parens"', type: 'rule', info: 'Arrow parens' },
  { label: '"no-trailing-spaces"', type: 'rule', info: 'No trailing ws' },
  { label: '"@typescript-eslint/no-unused-vars"', type: 'rule', info: 'TS unused vars' },
  { label: '"@typescript-eslint/no-explicit-any"', type: 'rule', info: 'No any' },
  { label: '"@typescript-eslint/explicit-module-boundary-types"', type: 'rule', info: 'Explicit types' },
  { label: '"@typescript-eslint/consistent-type-imports"', type: 'rule', info: 'Type imports' },
  { label: '"@typescript-eslint/no-non-null-assertion"', type: 'rule', info: 'No !' },
  { label: '"react/react-in-jsx-scope"', type: 'rule', info: 'React JSX scope' },
  { label: '"react/jsx-uses-react"', type: 'rule', info: 'JSX uses React' },
  { label: '"react/prop-types"', type: 'rule', info: 'Proptypes check' },
  { label: '"react/jsx-key"', type: 'rule', info: 'JSX key' },
  { label: '"react-hooks/rules-of-hooks"', type: 'rule', info: 'Rules of hooks' },
  { label: '"react-hooks/exhaustive-deps"', type: 'rule', info: 'Exhaustive deps' },
  { label: '"import/order"', type: 'rule', info: 'Import order' },
  { label: '"import/no-unresolved"', type: 'rule', info: 'No unresolved' },
  { label: '"import/no-default-export"', type: 'rule', info: 'No default export' },
  { label: '"jsx-a11y/alt-text"', type: 'rule', info: 'A11y alt' },
  // Rule severity
  { label: '"off"', type: 'value', info: 'Rule off' },
  { label: '"warn"', type: 'value', info: 'Rule warn' },
  { label: '"error"', type: 'value', info: 'Rule error' },
  { label: '0', type: 'value', info: 'Rule off (numeric)' },
  { label: '1', type: 'value', info: 'Rule warn (numeric)' },
  { label: '2', type: 'value', info: 'Rule error (numeric)' },
  // Jest config keys
  { label: 'testMatch', type: 'property', info: 'Test match' },
  { label: 'testRegex', type: 'property', info: 'Test regex' },
  { label: 'testPathIgnorePatterns', type: 'property', info: 'Ignore paths' },
  { label: 'testEnvironment', type: 'property', info: 'Test env' },
  { label: 'testEnvironmentOptions', type: 'property', info: 'Env opts' },
  { label: 'transform', type: 'property', info: 'Transform' },
  { label: 'transformIgnorePatterns', type: 'property', info: 'Transform ignore' },
  { label: 'moduleFileExtensions', type: 'property', info: 'Module exts' },
  { label: 'moduleNameMapper', type: 'property', info: 'Module name map' },
  { label: 'modulePaths', type: 'property', info: 'Module paths' },
  { label: 'moduleDirectories', type: 'property', info: 'Module dirs' },
  { label: 'setupFiles', type: 'property', info: 'Setup files' },
  { label: 'setupFilesAfterEach', type: 'property', info: 'Setup after each' },
  { label: 'globalSetup', type: 'property', info: 'Global setup' },
  { label: 'globalTeardown', type: 'property', info: 'Global teardown' },
  { label: 'collectCoverage', type: 'property', info: 'Collect cov' },
  { label: 'collectCoverageFrom', type: 'property', info: 'Cov from' },
  { label: 'coverageDirectory', type: 'property', info: 'Cov dir' },
  { label: 'coverageReporters', type: 'property', info: 'Cov reporters' },
  { label: 'coverageThreshold', type: 'property', info: 'Cov threshold' },
  { label: 'coveragePathIgnorePatterns', type: 'property', info: 'Cov ignore' },
  { label: 'verbose', type: 'property', info: 'Verbose output' },
  { label: 'bail', type: 'property', info: 'Bail on fail' },
  { label: 'watchPathIgnorePatterns', type: 'property', info: 'Watch ignore' },
  { label: 'snapshotSerializers', type: 'property', info: 'Snap serializers' },
  { label: 'snapshotResolver', type: 'property', info: 'Snap resolver' },
  { label: 'reporters', type: 'property', info: 'Reporters' },
  { label: 'maxWorkers', type: 'property', info: 'Max workers' },
  { label: 'maxConcurrency', type: 'property', info: 'Max concurrency' },
  { label: 'clearMocks', type: 'property', info: 'Clear mocks' },
  { label: 'resetMocks', type: 'property', info: 'Reset mocks' },
  { label: 'restoreMocks', type: 'property', info: 'Restore mocks' },
  { label: 'injectGlobals', type: 'property', info: 'Inject globals' },
  // Mocharc
  { label: 'require', type: 'property', info: 'Mocha require' },
  { label: 'recursive', type: 'property', info: 'Recursive tests' },
  { label: 'ui', type: 'property', info: 'Mocha UI' },
  { label: 'reporter', type: 'property', info: 'Mocha reporter' },
  { label: 'slow', type: 'property', info: 'Slow threshold' },
  { label: 'timeout', type: 'property', info: 'Test timeout' },
  { label: 'forbidOnly', type: 'property', info: 'Forbid .only' },
  { label: 'forbidPending', type: 'property', info: 'Forbid pending' },
  { label: 'retries', type: 'property', info: 'Retry count' },
  // nodemon
  { label: 'watch', type: 'property', info: 'Watch dirs' },
  { label: 'ext', type: 'property', info: 'Watched exts' },
  { label: 'ignore', type: 'property', info: 'Ignore paths' },
  { label: 'delay', type: 'property', info: 'Restart delay' },
  { label: 'execMap', type: 'property', info: 'Exec map' },
  { label: 'restartable', type: 'property', info: 'Restart key' },
  // husky / commitlint
  { label: 'hooks', type: 'property', info: 'Hook scripts' },
  // stylelint
  { label: 'customSyntax', type: 'property', info: 'Custom syntax' },
  { label: 'fix', type: 'property', info: 'Auto-fix' },
  { label: 'reportNeedlessDisables', type: 'property', info: 'Needless disables' },
  { label: 'reportInvalidScopeDisables', type: 'property', info: 'Invalid scopes' },
  // git attributes / git gitignore (rare as JSON, but schemastore)
  { label: 'gitignore', type: 'property', info: 'Gitignore patterns' },
  // Runtime engine fields
  { label: 'node', type: 'property', info: 'Node version range' },
  { label: 'npm', type: 'property', info: 'npm version range' },
  { label: 'yarn', type: 'property', info: 'yarn version range' },
  { label: 'pnpm', type: 'property', info: 'pnpm version range' },
  // Spread: tauri.conf.json basics
  { label: 'tauri', type: 'property', info: 'Tauri config' },
  { label: 'build', type: 'property', info: 'Build cfg' },
  { label: 'package', type: 'property', info: 'Package info' },
  { label: 'productName', type: 'property', info: 'Product name' },
  { label: 'bundle', type: 'property', info: 'Bundle opts' },
  { label: 'windows', type: 'property', info: 'Windows cfg' },
  { label: 'allowlist', type: 'property', info: 'Allowlist' },
  { label: 'security', type: 'property', info: 'Security cfg' },
  { label: 'updater', type: 'property', info: 'Updater cfg' },
  // Cap'n Proto / misc not needed. More SchemaStore
  { label: 'matchRegex', type: 'property', info: 'Match regex' },
  { label: 'url', type: 'property', info: 'Schema URL' },
  { label: 'fileMatch', type: 'property', info: 'File match glob' },
  // npm-shrinkwrap/lock
  { label: 'lockfileVersion', type: 'property', info: 'Lockfile version' },
  { label: 'requires', type: 'property', info: 'Legacy requires' },
  { label: 'integrity', type: 'property', info: 'SRI hash' },
  { label: 'resolved', type: 'property', info: 'Resolved URL' },
  { label: 'dev', type: 'property', info: 'Is dev dep' },
  { label: 'optional', type: 'property', info: 'Is optional' },
  { label: 'peer', type: 'property', info: 'Is peer' },
  { label: 'funding', type: 'property', info: 'Funding info' },
  // nestjs-cli nest-cli.json
  { label: 'collection', type: 'property', info: 'Nest collection' },
  { label: 'compilerOptions', type: 'property', info: 'Nest compiler' },
  { label: 'monorepo', type: 'property', info: 'Nest monorepo' },
  // NuGet
  { label: 'packageTypes', type: 'property', info: 'NuGet types' },
  // launch.json attrs (more)
  { label: 'skipFiles', type: 'property', info: 'Skip files' },
  { label: 'autoAttachChildProcesses', type: 'property', info: 'Auto attach' },
  { label: 'restart', type: 'property', info: 'Restart on exit' },
  { label: 'killBehavior', type: 'property', info: 'Kill behavior' },
  { label: 'envFile', type: 'property', info: 'Env file path' },
  // semantic-release
  { label: 'branches', type: 'property', info: 'SemRel branches' },
  { label: 'prerelease', type: 'property', info: 'Prerelease id' },
  { label: 'assets', type: 'property', info: 'Release assets' },
  { label: 'analyzeCommits', type: 'property', info: 'Analyze commits' },
  { label: 'generateNotes', type: 'property', info: 'Generate notes' },
  // Common import map schema
  { label: 'scopes', type: 'property', info: 'Import map scopes' },
  { label: 'integrity', type: 'property', info: 'SRI map' },
  // Babel assumptions
  { label: 'constantReexports', type: 'property', info: 'Babel assume' },
  { label: 'constantSuper', type: 'property', info: 'Babel assume' },
  { label: 'iterableIsArray', type: 'property', info: 'Babel assume' },
  { label: 'mutableTemplateObject', type: 'property', info: 'Babel assume' },
  { label: 'pureGetters', type: 'property', info: 'Babel assume' },
  { label: 'setClassMethods', type: 'property', info: 'Babel assume' },
  { label: 'setPublicClassFields', type: 'property', info: 'Babel assume' },
  { label: 'setSpreadProperties', type: 'property', info: 'Babel assume' },
  // tsconfig watchOptions
  { label: 'watchFile', type: 'property', info: 'Watch file strategy' },
  { label: 'watchDirectory', type: 'property', info: 'Watch dir strategy' },
  { label: 'fallbackPolling', type: 'property', info: 'Fallback polling' },
  { label: 'synchronousWatchDirectory', type: 'property', info: 'Sync watch' },
  { label: 'excludeDirectories', type: 'property', info: 'Exclude dirs' },
  { label: 'excludeFiles', type: 'property', info: 'Exclude files' },
  // ts project references
  { label: 'path', type: 'property', info: 'Ref path' },
  // More VS Code settings
  { label: 'explorer.confirmDelete', type: 'property', info: 'Confirm delete' },
  { label: 'explorer.confirmDragAndDrop', type: 'property', info: 'Confirm DnD' },
  { label: 'explorer.openEditors.visible', type: 'property', info: 'Open editors' },
  { label: 'diffEditor.ignoreTrimWhitespace', type: 'property', info: 'Diff ignore ws' },
  { label: 'diffEditor.renderSideBySide', type: 'property', info: 'Diff side by side' },
  { label: 'zenMode.hideTabs', type: 'property', info: 'Zen hide tabs' },
  { label: 'zenMode.hideStatusBar', type: 'property', info: 'Zen hide status' },
  { label: 'window.zoomLevel', type: 'property', info: 'Window zoom' },
  { label: 'window.titleBarStyle', type: 'property', info: 'Title bar style' },
  { label: 'window.menuBarVisibility', type: 'property', info: 'Menu bar visibility' },
  { label: 'window.newWindowDimensions', type: 'property', info: 'New window dims' },
  { label: 'window.restoreWindows', type: 'property', info: 'Restore windows' },
  { label: 'update.mode', type: 'property', info: 'Update mode' },
  { label: 'update.showReleaseNotes', type: 'property', info: 'Show release notes' },
  { label: 'telemetry.telemetryLevel', type: 'property', info: 'Telemetry level' },
  { label: 'scm.defaultViewMode', type: 'property', info: 'SCM view mode' },
  { label: 'debug.console.fontSize', type: 'property', info: 'Debug console font' },
  { label: 'debug.console.fontFamily', type: 'property', info: 'Debug console font fam' },
  { label: 'debug.openDebug', type: 'property', info: 'Open debug' },
  { label: 'debug.inlineValues', type: 'property', info: 'Debug inline values' },
  { label: 'extensions.autoUpdate', type: 'property', info: 'Auto update ext' },
  { label: 'extensions.ignoreRecommendations', type: 'property', info: 'Ignore recs' },
];
