// Completion entries for lua.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  // Keywords
  { label: 'and', type: 'keyword', info: 'Logical AND' },
  { label: 'break', type: 'keyword', info: 'Break loop' },
  { label: 'do', type: 'keyword', info: 'Do block' },
  { label: 'else', type: 'keyword', info: 'Else branch' },
  { label: 'elseif', type: 'keyword', info: 'Else if' },
  { label: 'end', type: 'keyword', info: 'End block' },
  { label: 'false', type: 'keyword', info: 'False' },
  { label: 'for', type: 'keyword', info: 'For loop' },
  { label: 'function', type: 'keyword', info: 'Function' },
  { label: 'goto', type: 'keyword', info: 'Goto label' },
  { label: 'if', type: 'keyword', info: 'If statement' },
  { label: 'in', type: 'keyword', info: 'Generic for' },
  { label: 'local', type: 'keyword', info: 'Local variable' },
  { label: 'nil', type: 'keyword', info: 'Nil value' },
  { label: 'not', type: 'keyword', info: 'Logical NOT' },
  { label: 'or', type: 'keyword', info: 'Logical OR' },
  { label: 'repeat', type: 'keyword', info: 'Repeat loop' },
  { label: 'return', type: 'keyword', info: 'Return value' },
  { label: 'then', type: 'keyword', info: 'Then' },
  { label: 'true', type: 'keyword', info: 'True' },
  { label: 'until', type: 'keyword', info: 'Until clause' },
  { label: 'while', type: 'keyword', info: 'While loop' },
  // Stdlib base
  { label: 'print', type: 'function', info: 'Print to stdout' },
  { label: 'tostring', type: 'function', info: 'Convert to string' },
  { label: 'tonumber', type: 'function', info: 'Convert to number' },
  { label: 'type', type: 'function', info: 'Type of value' },
  { label: 'ipairs', type: 'function', info: 'Iterate sequence' },
  { label: 'pairs', type: 'function', info: 'Iterate table' },
  { label: 'next', type: 'function', info: 'Next table entry' },
  { label: 'select', type: 'function', info: 'Select args' },
  { label: 'unpack', type: 'function', info: 'Unpack table (5.1)' },
  { label: 'error', type: 'function', info: 'Raise error' },
  { label: 'pcall', type: 'function', info: 'Protected call' },
  { label: 'xpcall', type: 'function', info: 'Extended pcall' },
  { label: 'assert', type: 'function', info: 'Assertion' },
  { label: 'require', type: 'function', info: 'Require module' },
  { label: 'dofile', type: 'function', info: 'Do file' },
  { label: 'loadstring', type: 'function', info: 'Load string (5.1)' },
  { label: 'load', type: 'function', info: 'Load chunk' },
  { label: 'loadfile', type: 'function', info: 'Load file' },
  { label: 'setmetatable', type: 'function', info: 'Set metatable' },
  { label: 'getmetatable', type: 'function', info: 'Get metatable' },
  { label: 'rawget', type: 'function', info: 'Raw get' },
  { label: 'rawset', type: 'function', info: 'Raw set' },
  { label: 'rawequal', type: 'function', info: 'Raw equality' },
  { label: 'rawlen', type: 'function', info: 'Raw length' },
  { label: 'collectgarbage', type: 'function', info: 'GC control' },
  { label: 'getfenv', type: 'function', info: 'Get env (5.1)' },
  { label: 'setfenv', type: 'function', info: 'Set env (5.1)' },
  // string
  { label: 'string.format', type: 'function', info: 'Format string' },
  { label: 'string.len', type: 'function', info: 'String length' },
  { label: 'string.upper', type: 'function', info: 'Uppercase' },
  { label: 'string.lower', type: 'function', info: 'Lowercase' },
  { label: 'string.sub', type: 'function', info: 'Substring' },
  { label: 'string.find', type: 'function', info: 'Find pattern' },
  { label: 'string.match', type: 'function', info: 'Match pattern' },
  { label: 'string.gmatch', type: 'function', info: 'Iter matches' },
  { label: 'string.gsub', type: 'function', info: 'Global substitute' },
  { label: 'string.rep', type: 'function', info: 'Repeat string' },
  { label: 'string.reverse', type: 'function', info: 'Reverse string' },
  { label: 'string.byte', type: 'function', info: 'Char to byte' },
  { label: 'string.char', type: 'function', info: 'Byte to char' },
  { label: 'string.dump', type: 'function', info: 'Dump function' },
  { label: 'string.pack', type: 'function', info: 'Pack values' },
  { label: 'string.unpack', type: 'function', info: 'Unpack values' },
  { label: 'string.packsize', type: 'function', info: 'Pack size' },
  // table
  { label: 'table.insert', type: 'function', info: 'Insert at pos' },
  { label: 'table.remove', type: 'function', info: 'Remove at pos' },
  { label: 'table.concat', type: 'function', info: 'Concat table' },
  { label: 'table.sort', type: 'function', info: 'Sort table' },
  { label: 'table.unpack', type: 'function', info: 'Unpack table' },
  { label: 'table.pack', type: 'function', info: 'Pack into table' },
  { label: 'table.move', type: 'function', info: 'Move elements' },
  // math
  { label: 'math.abs', type: 'function', info: 'Absolute value' },
  { label: 'math.ceil', type: 'function', info: 'Ceiling' },
  { label: 'math.floor', type: 'function', info: 'Floor' },
  { label: 'math.max', type: 'function', info: 'Max value' },
  { label: 'math.min', type: 'function', info: 'Min value' },
  { label: 'math.random', type: 'function', info: 'Random number' },
  { label: 'math.randomseed', type: 'function', info: 'Random seed' },
  { label: 'math.pi', type: 'constant', info: 'Pi constant' },
  { label: 'math.huge', type: 'constant', info: 'Infinity' },
  { label: 'math.maxinteger', type: 'constant', info: 'Max int' },
  { label: 'math.mininteger', type: 'constant', info: 'Min int' },
  { label: 'math.sqrt', type: 'function', info: 'Square root' },
  { label: 'math.pow', type: 'function', info: 'Power (5.1)' },
  { label: 'math.exp', type: 'function', info: 'Exponential' },
  { label: 'math.log', type: 'function', info: 'Logarithm' },
  { label: 'math.sin', type: 'function', info: 'Sine' },
  { label: 'math.cos', type: 'function', info: 'Cosine' },
  { label: 'math.tan', type: 'function', info: 'Tangent' },
  { label: 'math.asin', type: 'function', info: 'Arc sine' },
  { label: 'math.acos', type: 'function', info: 'Arc cosine' },
  { label: 'math.atan', type: 'function', info: 'Arc tangent' },
  { label: 'math.deg', type: 'function', info: 'To degrees' },
  { label: 'math.rad', type: 'function', info: 'To radians' },
  { label: 'math.fmod', type: 'function', info: 'Modulo' },
  { label: 'math.modf', type: 'function', info: 'Split int/frac' },
  { label: 'math.tointeger', type: 'function', info: 'To integer' },
  { label: 'math.type', type: 'function', info: 'Number type' },
  { label: 'math.ult', type: 'function', info: 'Unsigned less' },
  // io
  { label: 'io.open', type: 'function', info: 'Open file' },
  { label: 'io.read', type: 'function', info: 'Read from stdin' },
  { label: 'io.write', type: 'function', info: 'Write to stdout' },
  { label: 'io.close', type: 'function', info: 'Close file' },
  { label: 'io.lines', type: 'function', info: 'Iterate lines' },
  { label: 'io.input', type: 'function', info: 'Get/set default in' },
  { label: 'io.output', type: 'function', info: 'Get/set default out' },
  { label: 'io.stdin', type: 'variable', info: 'Standard input' },
  { label: 'io.stdout', type: 'variable', info: 'Standard output' },
  { label: 'io.stderr', type: 'variable', info: 'Standard error' },
  { label: 'io.popen', type: 'function', info: 'Open process' },
  { label: 'io.tmpfile', type: 'function', info: 'Temp file' },
  { label: 'io.type', type: 'function', info: 'Handle type' },
  { label: 'io.flush', type: 'function', info: 'Flush output' },
  // os
  { label: 'os.time', type: 'function', info: 'Current time' },
  { label: 'os.date', type: 'function', info: 'Format date' },
  { label: 'os.clock', type: 'function', info: 'CPU time' },
  { label: 'os.difftime', type: 'function', info: 'Time diff' },
  { label: 'os.exit', type: 'function', info: 'Exit program' },
  { label: 'os.getenv', type: 'function', info: 'Get env var' },
  { label: 'os.setenv', type: 'function', info: 'Set env var' },
  { label: 'os.execute', type: 'function', info: 'Run shell cmd' },
  { label: 'os.remove', type: 'function', info: 'Delete file' },
  { label: 'os.rename', type: 'function', info: 'Rename file' },
  { label: 'os.tmpname', type: 'function', info: 'Temp file name' },
  { label: 'os.getlocale', type: 'function', info: 'Get locale' },
  { label: 'os.setlocale', type: 'function', info: 'Set locale' },
  // coroutine
  { label: 'coroutine.create', type: 'function', info: 'Create coroutine' },
  { label: 'coroutine.resume', type: 'function', info: 'Resume coroutine' },
  { label: 'coroutine.yield', type: 'function', info: 'Yield coroutine' },
  { label: 'coroutine.status', type: 'function', info: 'Coroutine status' },
  { label: 'coroutine.wrap', type: 'function', info: 'Wrap function' },
  { label: 'coroutine.isyieldable', type: 'function', info: 'Is yieldable' },
  { label: 'coroutine.running', type: 'function', info: 'Running coroutine' },
  { label: 'coroutine.close', type: 'function', info: 'Close coroutine' },
  // debug
  { label: 'debug.traceback', type: 'function', info: 'Stack trace' },
  { label: 'debug.getinfo', type: 'function', info: 'Info for function' },
  { label: 'debug.sethook', type: 'function', info: 'Set debug hook' },
  { label: 'debug.getlocal', type: 'function', info: 'Get local var' },
  { label: 'debug.setlocal', type: 'function', info: 'Set local var' },
  { label: 'debug.getupvalue', type: 'function', info: 'Get upvalue' },
  { label: 'debug.setupvalue', type: 'function', info: 'Set upvalue' },
  // Self/vars
  { label: 'self', type: 'variable', info: 'Method self' },
  { label: '_G', type: 'variable', info: 'Global env' },
  { label: '_ENV', type: 'variable', info: 'Lexical env (5.2+)' },
  { label: '_VERSION', type: 'constant', info: 'Lua version' },
  { label: '...', type: 'variable', info: 'Varargs' },
  { label: 'arg', type: 'variable', info: 'Script args' },
  // Lua 5.4 built-ins
  { label: 'print', type: 'function', info: 'Print to stdout' },
  { label: 'tostring', type: 'function', info: 'To string' },
  { label: 'tonumber', type: 'function', info: 'To number' },
  { label: 'type', type: 'function', info: 'Type name' },
  { label: 'ipairs', type: 'function', info: 'Array iter' },
  { label: 'pairs', type: 'function', info: 'Key iter' },
  { label: 'next', type: 'function', info: 'Next key' },
  { label: 'select', type: 'function', info: 'Select from vararg' },
  { label: 'unpack', type: 'function', info: 'Unpack table (5.1)' },
  { label: 'error', type: 'function', info: 'Raise error' },
  { label: 'pcall', type: 'function', info: 'Protected call' },
  { label: 'xpcall', type: 'function', info: 'pcall + handler' },
  { label: 'assert', type: 'function', info: 'Assert condition' },
  { label: 'require', type: 'function', info: 'Load module' },
  { label: 'dofile', type: 'function', info: 'Run script' },
  { label: 'loadstring', type: 'function', info: 'Load string (5.1)' },
  { label: 'load', type: 'function', info: 'Load chunk' },
  { label: 'loadfile', type: 'function', info: 'Load file' },
  { label: 'setmetatable', type: 'function', info: 'Set metatable' },
  { label: 'getmetatable', type: 'function', info: 'Get metatable' },
  { label: 'rawget', type: 'function', info: 'Raw get (no mt)' },
  { label: 'rawset', type: 'function', info: 'Raw set (no mt)' },
  { label: 'rawequal', type: 'function', info: 'Raw equality' },
  { label: 'rawlen', type: 'function', info: 'Raw length' },
  { label: 'collectgarbage', type: 'function', info: 'GC control' },
  { label: 'gcinfo', type: 'function', info: 'GC info (5.1)' },
  // string library
  { label: 'string.format', type: 'function', info: 'printf-style format' },
  { label: 'string.len', type: 'function', info: 'String length' },
  { label: 'string.upper', type: 'function', info: 'Uppercase' },
  { label: 'string.lower', type: 'function', info: 'Lowercase' },
  { label: 'string.sub', type: 'function', info: 'Substring' },
  { label: 'string.find', type: 'function', info: 'Find pattern' },
  { label: 'string.match', type: 'function', info: 'Match pattern' },
  { label: 'string.gmatch', type: 'function', info: 'Iter matches' },
  { label: 'string.gsub', type: 'function', info: 'Global substitute' },
  { label: 'string.rep', type: 'function', info: 'Repeat string' },
  { label: 'string.reverse', type: 'function', info: 'Reverse string' },
  { label: 'string.byte', type: 'function', info: 'Byte at pos' },
  { label: 'string.char', type: 'function', info: 'Char from code' },
  { label: 'string.pack', type: 'function', info: 'Pack binary' },
  { label: 'string.unpack', type: 'function', info: 'Unpack binary' },
  { label: 'string.packsize', type: 'function', info: 'Pack size' },
  { label: 'string.dump', type: 'function', info: 'Dump function' },
  // String patterns
  { label: '%a', type: 'pattern', info: 'Letters' },
  { label: '%A', type: 'pattern', info: 'Non-letters' },
  { label: '%c', type: 'pattern', info: 'Control chars' },
  { label: '%C', type: 'pattern', info: 'Non-control' },
  { label: '%d', type: 'pattern', info: 'Digits' },
  { label: '%D', type: 'pattern', info: 'Non-digits' },
  { label: '%g', type: 'pattern', info: 'Printable ex-space' },
  { label: '%G', type: 'pattern', info: 'Non-printable' },
  { label: '%l', type: 'pattern', info: 'Lower letters' },
  { label: '%L', type: 'pattern', info: 'Non-lower' },
  { label: '%p', type: 'pattern', info: 'Punctuation' },
  { label: '%P', type: 'pattern', info: 'Non-punct' },
  { label: '%s', type: 'pattern', info: 'Whitespace' },
  { label: '%S', type: 'pattern', info: 'Non-whitespace' },
  { label: '%u', type: 'pattern', info: 'Upper letters' },
  { label: '%U', type: 'pattern', info: 'Non-upper' },
  { label: '%w', type: 'pattern', info: 'Alphanumeric' },
  { label: '%W', type: 'pattern', info: 'Non-alnum' },
  { label: '%x', type: 'pattern', info: 'Hex digits' },
  { label: '%X', type: 'pattern', info: 'Non-hex' },
  // table library
  { label: 'table.insert', type: 'function', info: 'Insert into table' },
  { label: 'table.remove', type: 'function', info: 'Remove from table' },
  { label: 'table.concat', type: 'function', info: 'Concat array' },
  { label: 'table.sort', type: 'function', info: 'Sort array' },
  { label: 'table.unpack', type: 'function', info: 'Unpack table' },
  { label: 'table.pack', type: 'function', info: 'Pack to table' },
  { label: 'table.move', type: 'function', info: 'Move range' },
  { label: 'table.foreach', type: 'function', info: 'Iter (5.1 old)' },
  // math library
  { label: 'math.abs', type: 'function', info: 'Absolute value' },
  { label: 'math.ceil', type: 'function', info: 'Ceiling' },
  { label: 'math.floor', type: 'function', info: 'Floor' },
  { label: 'math.max', type: 'function', info: 'Maximum' },
  { label: 'math.min', type: 'function', info: 'Minimum' },
  { label: 'math.random', type: 'function', info: 'Random number' },
  { label: 'math.randomseed', type: 'function', info: 'Seed RNG' },
  { label: 'math.pi', type: 'constant', info: 'Pi constant' },
  { label: 'math.huge', type: 'constant', info: 'Infinity' },
  { label: 'math.maxinteger', type: 'constant', info: 'Max integer' },
  { label: 'math.mininteger', type: 'constant', info: 'Min integer' },
  { label: 'math.sqrt', type: 'function', info: 'Square root' },
  { label: 'math.pow', type: 'function', info: 'Power (5.1)' },
  { label: 'math.exp', type: 'function', info: 'e^x' },
  { label: 'math.log', type: 'function', info: 'Logarithm' },
  { label: 'math.sin', type: 'function', info: 'Sine' },
  { label: 'math.cos', type: 'function', info: 'Cosine' },
  { label: 'math.tan', type: 'function', info: 'Tangent' },
  { label: 'math.asin', type: 'function', info: 'Arc sine' },
  { label: 'math.acos', type: 'function', info: 'Arc cosine' },
  { label: 'math.atan', type: 'function', info: 'Arc tangent' },
  { label: 'math.sinh', type: 'function', info: 'Sinh (5.2)' },
  { label: 'math.cosh', type: 'function', info: 'Cosh (5.2)' },
  { label: 'math.tanh', type: 'function', info: 'Tanh (5.2)' },
  { label: 'math.deg', type: 'function', info: 'Rad to deg' },
  { label: 'math.rad', type: 'function', info: 'Deg to rad' },
  { label: 'math.fmod', type: 'function', info: 'Float mod' },
  { label: 'math.modf', type: 'function', info: 'Int/frac split' },
  { label: 'math.atan2', type: 'function', info: 'atan2 (5.1)' },
  { label: 'math.frexp', type: 'function', info: 'Split fp (5.1)' },
  { label: 'math.ldexp', type: 'function', info: 'Combine fp (5.1)' },
  { label: 'math.type', type: 'function', info: 'integer/float' },
  { label: 'math.tointeger', type: 'function', info: 'Try to int' },
  { label: 'math.ult', type: 'function', info: 'Unsigned less than' },
  // io library
  { label: 'io.open', type: 'function', info: 'Open file' },
  { label: 'io.read', type: 'function', info: 'Read from stdin' },
  { label: 'io.write', type: 'function', info: 'Write to stdout' },
  { label: 'io.close', type: 'function', info: 'Close file' },
  { label: 'io.lines', type: 'function', info: 'Iter file lines' },
  { label: 'io.input', type: 'function', info: 'Default input' },
  { label: 'io.output', type: 'function', info: 'Default output' },
  { label: 'io.stderr', type: 'variable', info: 'stderr file' },
  { label: 'io.stdin', type: 'variable', info: 'stdin file' },
  { label: 'io.stdout', type: 'variable', info: 'stdout file' },
  { label: 'io.tmpfile', type: 'function', info: 'Temp file' },
  { label: 'io.popen', type: 'function', info: 'Pipe to process' },
  { label: 'file:read', type: 'method', info: 'File read' },
  { label: 'file:write', type: 'method', info: 'File write' },
  { label: 'file:close', type: 'method', info: 'File close' },
  { label: 'file:lines', type: 'method', info: 'Iter lines' },
  { label: 'file:seek', type: 'method', info: 'File seek' },
  { label: 'file:flush', type: 'method', info: 'File flush' },
  { label: 'file:setvbuf', type: 'method', info: 'Set buffer' },
  // os library
  { label: 'os.time', type: 'function', info: 'Current time' },
  { label: 'os.date', type: 'function', info: 'Format date' },
  { label: 'os.clock', type: 'function', info: 'CPU time' },
  { label: 'os.exit', type: 'function', info: 'Exit program' },
  { label: 'os.getenv', type: 'function', info: 'Env var' },
  { label: 'os.setenv', type: 'function', info: 'Set env (nonstd)' },
  { label: 'os.execute', type: 'function', info: 'Run shell cmd' },
  { label: 'os.remove', type: 'function', info: 'Delete file' },
  { label: 'os.rename', type: 'function', info: 'Rename file' },
  { label: 'os.tmpname', type: 'function', info: 'Temp filename' },
  { label: 'os.difftime', type: 'function', info: 'Time diff' },
  { label: 'os.setlocale', type: 'function', info: 'Set locale' },
  // Coroutines
  { label: 'coroutine.create', type: 'function', info: 'Make coroutine' },
  { label: 'coroutine.resume', type: 'function', info: 'Resume co' },
  { label: 'coroutine.yield', type: 'function', info: 'Yield value' },
  { label: 'coroutine.wrap', type: 'function', info: 'Wrap as fn' },
  { label: 'coroutine.status', type: 'function', info: 'Co status' },
  { label: 'coroutine.running', type: 'function', info: 'Current co' },
  { label: 'coroutine.isyieldable', type: 'function', info: 'Yieldable?' },
  { label: 'coroutine.close', type: 'function', info: 'Close co (5.4)' },
  // Debug library
  { label: 'debug.traceback', type: 'function', info: 'Stack traceback' },
  { label: 'debug.getinfo', type: 'function', info: 'Frame info' },
  { label: 'debug.sethook', type: 'function', info: 'Install hook' },
  { label: 'debug.gethook', type: 'function', info: 'Current hook' },
  { label: 'debug.getlocal', type: 'function', info: 'Get local' },
  { label: 'debug.setlocal', type: 'function', info: 'Set local' },
  { label: 'debug.upvaluejoin', type: 'function', info: 'Join upvalues' },
  { label: 'debug.upvalueid', type: 'function', info: 'Upvalue id' },
  { label: 'debug.setmetatable', type: 'function', info: 'Set mt (raw)' },
  { label: 'debug.getmetatable', type: 'function', info: 'Get mt (raw)' },
  { label: 'debug.getregistry', type: 'function', info: 'Lua registry' },
  { label: 'debug.setcstacklimit', type: 'function', info: 'C stack limit (5.4)' },
  // Metamethods
  { label: '__index', type: 'metamethod', info: 'Index lookup' },
  { label: '__newindex', type: 'metamethod', info: 'New index set' },
  { label: '__call', type: 'metamethod', info: 'Call table as fn' },
  { label: '__add', type: 'metamethod', info: 'Add op' },
  { label: '__sub', type: 'metamethod', info: 'Sub op' },
  { label: '__mul', type: 'metamethod', info: 'Mul op' },
  { label: '__div', type: 'metamethod', info: 'Div op' },
  { label: '__mod', type: 'metamethod', info: 'Mod op' },
  { label: '__pow', type: 'metamethod', info: 'Power op' },
  { label: '__unm', type: 'metamethod', info: 'Unary minus' },
  { label: '__idiv', type: 'metamethod', info: 'Floor div' },
  { label: '__band', type: 'metamethod', info: 'Bitwise AND' },
  { label: '__bor', type: 'metamethod', info: 'Bitwise OR' },
  { label: '__bxor', type: 'metamethod', info: 'Bitwise XOR' },
  { label: '__bnot', type: 'metamethod', info: 'Bitwise NOT' },
  { label: '__shl', type: 'metamethod', info: 'Shift left' },
  { label: '__shr', type: 'metamethod', info: 'Shift right' },
  { label: '__concat', type: 'metamethod', info: 'Concat op' },
  { label: '__len', type: 'metamethod', info: 'Length op' },
  { label: '__eq', type: 'metamethod', info: 'Equality' },
  { label: '__lt', type: 'metamethod', info: 'Less than' },
  { label: '__le', type: 'metamethod', info: 'Less or eq' },
  { label: '__tostring', type: 'metamethod', info: 'to-string conv' },
  { label: '__name', type: 'metamethod', info: 'Type name' },
  { label: '__metatable', type: 'metamethod', info: 'MT protect' },
  { label: '__gc', type: 'metamethod', info: 'Finalizer' },
  { label: '__close', type: 'metamethod', info: 'Close (5.4)' },
  { label: '__mode', type: 'metamethod', info: 'Weak table mode' },
  { label: '__pairs', type: 'metamethod', info: 'Custom pairs' },
  // LOVE (love2D)
  { label: 'love.load', type: 'function', info: 'LÖVE load' },
  { label: 'love.update', type: 'function', info: 'LÖVE update' },
  { label: 'love.draw', type: 'function', info: 'LÖVE draw' },
  { label: 'love.keypressed', type: 'function', info: 'Key press' },
  { label: 'love.keyreleased', type: 'function', info: 'Key release' },
  { label: 'love.mousepressed', type: 'function', info: 'Mouse press' },
  { label: 'love.mousereleased', type: 'function', info: 'Mouse release' },
  { label: 'love.mousemoved', type: 'function', info: 'Mouse move' },
  { label: 'love.wheelmoved', type: 'function', info: 'Wheel move' },
  { label: 'love.resize', type: 'function', info: 'Window resize' },
  { label: 'love.focus', type: 'function', info: 'Window focus' },
  { label: 'love.quit', type: 'function', info: 'On quit' },
  { label: 'love.textinput', type: 'function', info: 'Text input' },
  { label: 'love.graphics.draw', type: 'function', info: 'Draw drawable' },
  { label: 'love.graphics.rectangle', type: 'function', info: 'Draw rect' },
  { label: 'love.graphics.circle', type: 'function', info: 'Draw circle' },
  { label: 'love.graphics.line', type: 'function', info: 'Draw line' },
  { label: 'love.graphics.polygon', type: 'function', info: 'Draw polygon' },
  { label: 'love.graphics.print', type: 'function', info: 'Draw text' },
  { label: 'love.graphics.printf', type: 'function', info: 'Formatted text' },
  { label: 'love.graphics.setColor', type: 'function', info: 'Set color' },
  { label: 'love.graphics.getColor', type: 'function', info: 'Get color' },
  { label: 'love.graphics.setFont', type: 'function', info: 'Set font' },
  { label: 'love.graphics.newFont', type: 'function', info: 'New font' },
  { label: 'love.graphics.newImage', type: 'function', info: 'Load image' },
  { label: 'love.graphics.newQuad', type: 'function', info: 'New quad' },
  { label: 'love.graphics.newCanvas', type: 'function', info: 'New canvas' },
  { label: 'love.graphics.newSpriteBatch', type: 'function', info: 'Sprite batch' },
  { label: 'love.graphics.setCanvas', type: 'function', info: 'Set canvas' },
  { label: 'love.graphics.push', type: 'function', info: 'Push xform' },
  { label: 'love.graphics.pop', type: 'function', info: 'Pop xform' },
  { label: 'love.graphics.translate', type: 'function', info: 'Translate' },
  { label: 'love.graphics.rotate', type: 'function', info: 'Rotate' },
  { label: 'love.graphics.scale', type: 'function', info: 'Scale' },
  { label: 'love.graphics.shear', type: 'function', info: 'Shear' },
  { label: 'love.graphics.origin', type: 'function', info: 'Reset xform' },
  { label: 'love.graphics.getWidth', type: 'function', info: 'Window width' },
  { label: 'love.graphics.getHeight', type: 'function', info: 'Window height' },
  { label: 'love.graphics.getDimensions', type: 'function', info: 'Window WxH' },
  { label: 'love.graphics.setBackgroundColor', type: 'function', info: 'BG color' },
  { label: 'love.graphics.clear', type: 'function', info: 'Clear screen' },
  { label: 'love.graphics.present', type: 'function', info: 'Present' },
  { label: 'love.graphics.setBlendMode', type: 'function', info: 'Blend mode' },
  { label: 'love.graphics.setLineWidth', type: 'function', info: 'Line width' },
  { label: 'love.audio.play', type: 'function', info: 'Play source' },
  { label: 'love.audio.stop', type: 'function', info: 'Stop audio' },
  { label: 'love.audio.pause', type: 'function', info: 'Pause audio' },
  { label: 'love.audio.newSource', type: 'function', info: 'New source' },
  { label: 'love.audio.setVolume', type: 'function', info: 'Set volume' },
  { label: 'love.keyboard.isDown', type: 'function', info: 'Key down?' },
  { label: 'love.keyboard.isScancodeDown', type: 'function', info: 'Scancode down?' },
  { label: 'love.mouse.getPosition', type: 'function', info: 'Mouse pos' },
  { label: 'love.mouse.isDown', type: 'function', info: 'Button down?' },
  { label: 'love.mouse.setVisible', type: 'function', info: 'Show/hide cursor' },
  { label: 'love.mouse.setCursor', type: 'function', info: 'Set cursor' },
  { label: 'love.timer.getDelta', type: 'function', info: 'Frame dt' },
  { label: 'love.timer.getFPS', type: 'function', info: 'FPS counter' },
  { label: 'love.timer.getTime', type: 'function', info: 'Time since launch' },
  { label: 'love.timer.sleep', type: 'function', info: 'Sleep seconds' },
  { label: 'love.filesystem.read', type: 'function', info: 'Read file' },
  { label: 'love.filesystem.write', type: 'function', info: 'Write file' },
  { label: 'love.filesystem.exists', type: 'function', info: 'File exists?' },
  { label: 'love.filesystem.getInfo', type: 'function', info: 'File info' },
  { label: 'love.filesystem.load', type: 'function', info: 'Load lua file' },
  { label: 'love.filesystem.getDirectoryItems', type: 'function', info: 'Dir items' },
  { label: 'love.event.quit', type: 'function', info: 'Quit program' },
  { label: 'love.event.push', type: 'function', info: 'Push event' },
  { label: 'love.window.setTitle', type: 'function', info: 'Window title' },
  { label: 'love.window.getTitle', type: 'function', info: 'Get title' },
  { label: 'love.window.setMode', type: 'function', info: 'Window mode' },
  { label: 'love.window.setFullscreen', type: 'function', info: 'Fullscreen' },
  { label: 'love.physics.newWorld', type: 'function', info: 'Physics world' },
  { label: 'love.physics.newBody', type: 'function', info: 'Physics body' },
  { label: 'love.physics.newRectangleShape', type: 'function', info: 'Box shape' },
  { label: 'love.physics.newCircleShape', type: 'function', info: 'Circle shape' },
  { label: 'love.physics.newPolygonShape', type: 'function', info: 'Poly shape' },
  { label: 'love.physics.newFixture', type: 'function', info: 'Fixture' },
  { label: 'love.math.random', type: 'function', info: 'LÖVE random' },
  { label: 'love.math.noise', type: 'function', info: 'Perlin noise' },
  { label: 'love.math.triangulate', type: 'function', info: 'Triangulate' },
  // OpenResty Nginx Lua
  { label: 'ngx.say', type: 'function', info: 'Write + newline' },
  { label: 'ngx.print', type: 'function', info: 'Write to client' },
  { label: 'ngx.log', type: 'function', info: 'Log message' },
  { label: 'ngx.exit', type: 'function', info: 'Exit status' },
  { label: 'ngx.redirect', type: 'function', info: 'HTTP redirect' },
  { label: 'ngx.escape_uri', type: 'function', info: 'URL encode' },
  { label: 'ngx.unescape_uri', type: 'function', info: 'URL decode' },
  { label: 'ngx.encode_base64', type: 'function', info: 'B64 encode' },
  { label: 'ngx.decode_base64', type: 'function', info: 'B64 decode' },
  { label: 'ngx.hmac_sha1', type: 'function', info: 'HMAC-SHA1' },
  { label: 'ngx.md5', type: 'function', info: 'MD5 hash' },
  { label: 'ngx.sha1_bin', type: 'function', info: 'SHA1 binary' },
  { label: 'ngx.crc32_long', type: 'function', info: 'CRC32 long' },
  { label: 'ngx.crc32_short', type: 'function', info: 'CRC32 short' },
  { label: 'ngx.time', type: 'function', info: 'Cached time' },
  { label: 'ngx.now', type: 'function', info: 'Current float time' },
  { label: 'ngx.update_time', type: 'function', info: 'Refresh time' },
  { label: 'ngx.today', type: 'function', info: 'Today string' },
  { label: 'ngx.localtime', type: 'function', info: 'Local time' },
  { label: 'ngx.utctime', type: 'function', info: 'UTC time' },
  { label: 'ngx.cookie_time', type: 'function', info: 'Format cookie time' },
  { label: 'ngx.http_time', type: 'function', info: 'Format HTTP time' },
  { label: 'ngx.parse_http_time', type: 'function', info: 'Parse HTTP time' },
  { label: 'ngx.sleep', type: 'function', info: 'Async sleep' },
  { label: 'ngx.var', type: 'variable', info: 'Nginx variables' },
  { label: 'ngx.req.get_headers', type: 'function', info: 'Req headers' },
  { label: 'ngx.req.get_uri_args', type: 'function', info: 'URI args' },
  { label: 'ngx.req.get_post_args', type: 'function', info: 'POST args' },
  { label: 'ngx.req.read_body', type: 'function', info: 'Read body' },
  { label: 'ngx.req.get_body_data', type: 'function', info: 'Body data' },
  { label: 'ngx.req.get_body_file', type: 'function', info: 'Body file' },
  { label: 'ngx.req.set_header', type: 'function', info: 'Set req header' },
  { label: 'ngx.req.clear_header', type: 'function', info: 'Clear req header' },
  { label: 'ngx.req.get_method', type: 'function', info: 'HTTP method' },
  { label: 'ngx.req.set_method', type: 'function', info: 'Set method' },
  { label: 'ngx.req.raw_header', type: 'function', info: 'Raw request' },
  { label: 'ngx.req.start_time', type: 'function', info: 'Request start' },
  { label: 'ngx.req.http_version', type: 'function', info: 'HTTP version' },
  { label: 'ngx.header', type: 'variable', info: 'Resp headers' },
  { label: 'ngx.resp.get_headers', type: 'function', info: 'Resp headers' },
  { label: 'ngx.status', type: 'variable', info: 'Resp status' },
  { label: 'ngx.shared', type: 'variable', info: 'Shared dict' },
  { label: 'ngx.shared.DICT:get', type: 'method', info: 'Shared get' },
  { label: 'ngx.shared.DICT:set', type: 'method', info: 'Shared set' },
  { label: 'ngx.shared.DICT:add', type: 'method', info: 'Shared add' },
  { label: 'ngx.shared.DICT:delete', type: 'method', info: 'Shared delete' },
  { label: 'ngx.shared.DICT:incr', type: 'method', info: 'Shared incr' },
  { label: 'ngx.shared.DICT:flush_all', type: 'method', info: 'Flush all' },
  { label: 'ngx.timer.at', type: 'function', info: 'Schedule timer' },
  { label: 'ngx.timer.every', type: 'function', info: 'Recurring timer' },
  { label: 'ngx.socket.tcp', type: 'function', info: 'TCP socket' },
  { label: 'ngx.socket.udp', type: 'function', info: 'UDP socket' },
  { label: 'ngx.socket.connect', type: 'function', info: 'Connect' },
  { label: 'ngx.worker.pid', type: 'function', info: 'Worker PID' },
  { label: 'ngx.worker.id', type: 'function', info: 'Worker ID' },
  { label: 'ngx.worker.count', type: 'function', info: 'Worker count' },
  { label: 'ngx.thread.spawn', type: 'function', info: 'Spawn light thread' },
  { label: 'ngx.thread.wait', type: 'function', info: 'Wait threads' },
  { label: 'ngx.thread.kill', type: 'function', info: 'Kill thread' },
  { label: 'ngx.location.capture', type: 'function', info: 'Subrequest' },
  { label: 'ngx.location.capture_multi', type: 'function', info: 'Parallel subreqs' },
  { label: 'ngx.HTTP_OK', type: 'constant', info: '200 OK' },
  { label: 'ngx.HTTP_NOT_FOUND', type: 'constant', info: '404' },
  { label: 'ngx.HTTP_INTERNAL_SERVER_ERROR', type: 'constant', info: '500' },
  { label: 'ngx.HTTP_FORBIDDEN', type: 'constant', info: '403' },
  { label: 'ngx.HTTP_UNAUTHORIZED', type: 'constant', info: '401' },
  { label: 'ngx.HTTP_MOVED_TEMPORARILY', type: 'constant', info: '302' },
  { label: 'ngx.HTTP_MOVED_PERMANENTLY', type: 'constant', info: '301' },
  { label: 'ngx.HTTP_BAD_REQUEST', type: 'constant', info: '400' },
  { label: 'ngx.ERR', type: 'constant', info: 'Log ERR' },
  { label: 'ngx.WARN', type: 'constant', info: 'Log WARN' },
  { label: 'ngx.NOTICE', type: 'constant', info: 'Log NOTICE' },
  { label: 'ngx.INFO', type: 'constant', info: 'Log INFO' },
  { label: 'ngx.DEBUG', type: 'constant', info: 'Log DEBUG' },
  { label: 'ngx.OK', type: 'constant', info: 'OK constant' },
  { label: 'ngx.DONE', type: 'constant', info: 'DONE constant' },
  { label: 'ngx.AGAIN', type: 'constant', info: 'AGAIN constant' },
  { label: 'ngx.ERROR', type: 'constant', info: 'ERROR constant' },
  // Neovim Lua API
  { label: 'vim.api.nvim_buf_set_lines', type: 'function', info: 'Set buffer lines' },
  { label: 'vim.api.nvim_buf_get_lines', type: 'function', info: 'Get buffer lines' },
  { label: 'vim.api.nvim_buf_set_text', type: 'function', info: 'Set buffer text' },
  { label: 'vim.api.nvim_buf_get_text', type: 'function', info: 'Get buffer text' },
  { label: 'vim.api.nvim_buf_set_option', type: 'function', info: 'Set buf option' },
  { label: 'vim.api.nvim_buf_get_option', type: 'function', info: 'Get buf option' },
  { label: 'vim.api.nvim_buf_set_name', type: 'function', info: 'Rename buffer' },
  { label: 'vim.api.nvim_buf_delete', type: 'function', info: 'Delete buffer' },
  { label: 'vim.api.nvim_create_buf', type: 'function', info: 'Create buffer' },
  { label: 'vim.api.nvim_list_bufs', type: 'function', info: 'List buffers' },
  { label: 'vim.api.nvim_get_current_buf', type: 'function', info: 'Current buffer' },
  { label: 'vim.api.nvim_set_current_buf', type: 'function', info: 'Set current buf' },
  { label: 'vim.api.nvim_create_autocmd', type: 'function', info: 'Create autocmd' },
  { label: 'vim.api.nvim_create_user_command', type: 'function', info: 'User command' },
  { label: 'vim.api.nvim_set_keymap', type: 'function', info: 'Set keymap' },
  { label: 'vim.api.nvim_buf_set_keymap', type: 'function', info: 'Buf keymap' },
  { label: 'vim.api.nvim_del_keymap', type: 'function', info: 'Delete keymap' },
  { label: 'vim.api.nvim_open_win', type: 'function', info: 'Open float win' },
  { label: 'vim.api.nvim_win_close', type: 'function', info: 'Close window' },
  { label: 'vim.api.nvim_win_set_buf', type: 'function', info: 'Win set buf' },
  { label: 'vim.api.nvim_win_set_cursor', type: 'function', info: 'Win cursor pos' },
  { label: 'vim.api.nvim_win_get_cursor', type: 'function', info: 'Get cursor' },
  { label: 'vim.api.nvim_echo', type: 'function', info: 'Echo message' },
  { label: 'vim.api.nvim_err_writeln', type: 'function', info: 'Error message' },
  { label: 'vim.api.nvim_command', type: 'function', info: 'Run ex command' },
  { label: 'vim.api.nvim_exec2', type: 'function', info: 'Run vimscript' },
  { label: 'vim.api.nvim_eval', type: 'function', info: 'Eval vimscript' },
  { label: 'vim.api.nvim_get_option', type: 'function', info: 'Get option' },
  { label: 'vim.api.nvim_set_option', type: 'function', info: 'Set option' },
  { label: 'vim.keymap.set', type: 'function', info: 'Set keymap (new)' },
  { label: 'vim.keymap.del', type: 'function', info: 'Delete keymap (new)' },
  { label: 'vim.fn', type: 'table', info: 'Vim functions' },
  { label: 'vim.cmd', type: 'function', info: 'Ex command' },
  { label: 'vim.g', type: 'table', info: 'Globals' },
  { label: 'vim.b', type: 'table', info: 'Buffer-local' },
  { label: 'vim.w', type: 'table', info: 'Window-local' },
  { label: 'vim.t', type: 'table', info: 'Tab-local' },
  { label: 'vim.v', type: 'table', info: 'Vim-predefined' },
  { label: 'vim.env', type: 'table', info: 'Environment' },
  { label: 'vim.opt', type: 'table', info: 'Options' },
  { label: 'vim.opt_local', type: 'table', info: 'Buffer-local opts' },
  { label: 'vim.opt_global', type: 'table', info: 'Global opts' },
  { label: 'vim.o', type: 'table', info: 'Options (flat)' },
  { label: 'vim.bo', type: 'table', info: 'Buf options' },
  { label: 'vim.wo', type: 'table', info: 'Win options' },
  { label: 'vim.lsp.start', type: 'function', info: 'Start LSP' },
  { label: 'vim.lsp.stop_client', type: 'function', info: 'Stop LSP' },
  { label: 'vim.lsp.buf.format', type: 'function', info: 'LSP format' },
  { label: 'vim.lsp.buf.hover', type: 'function', info: 'LSP hover' },
  { label: 'vim.lsp.buf.definition', type: 'function', info: 'LSP def' },
  { label: 'vim.lsp.buf.references', type: 'function', info: 'LSP refs' },
  { label: 'vim.lsp.buf.rename', type: 'function', info: 'LSP rename' },
  { label: 'vim.lsp.buf.code_action', type: 'function', info: 'LSP code action' },
  { label: 'vim.lsp.buf.completion', type: 'function', info: 'LSP completion' },
  { label: 'vim.diagnostic.get', type: 'function', info: 'Get diags' },
  { label: 'vim.diagnostic.set', type: 'function', info: 'Set diags' },
  { label: 'vim.diagnostic.open_float', type: 'function', info: 'Diag float' },
  { label: 'vim.diagnostic.goto_next', type: 'function', info: 'Next diag' },
  { label: 'vim.diagnostic.goto_prev', type: 'function', info: 'Prev diag' },
  { label: 'vim.notify', type: 'function', info: 'Notify message' },
  { label: 'vim.schedule', type: 'function', info: 'Schedule callback' },
  { label: 'vim.schedule_wrap', type: 'function', info: 'Schedule wrap' },
  { label: 'vim.defer_fn', type: 'function', info: 'Defer fn' },
  { label: 'vim.loop', type: 'table', info: 'libuv (legacy)' },
  { label: 'vim.uv', type: 'table', info: 'libuv (new)' },
  { label: 'vim.json.encode', type: 'function', info: 'JSON encode' },
  { label: 'vim.json.decode', type: 'function', info: 'JSON decode' },
  { label: 'vim.tbl_deep_extend', type: 'function', info: 'Deep table merge' },
  { label: 'vim.tbl_extend', type: 'function', info: 'Shallow merge' },
  { label: 'vim.tbl_keys', type: 'function', info: 'Table keys' },
  { label: 'vim.tbl_values', type: 'function', info: 'Table values' },
  { label: 'vim.tbl_contains', type: 'function', info: 'Contains elem' },
  { label: 'vim.tbl_isempty', type: 'function', info: 'Is empty' },
  { label: 'vim.tbl_count', type: 'function', info: 'Count entries' },
  { label: 'vim.tbl_filter', type: 'function', info: 'Filter table' },
  { label: 'vim.tbl_map', type: 'function', info: 'Map table' },
  { label: 'vim.tbl_flatten', type: 'function', info: 'Flatten table' },
  { label: 'vim.split', type: 'function', info: 'Split string' },
  { label: 'vim.trim', type: 'function', info: 'Trim string' },
  { label: 'vim.startswith', type: 'function', info: 'Starts with' },
  { label: 'vim.endswith', type: 'function', info: 'Ends with' },
  { label: 'vim.validate', type: 'function', info: 'Validate args' },
  { label: 'vim.inspect', type: 'function', info: 'Pretty print' },
  { label: 'vim.deep_equal', type: 'function', info: 'Deep equal' },
  { label: 'vim.fs.find', type: 'function', info: 'Find files' },
  { label: 'vim.fs.dirname', type: 'function', info: 'Dirname' },
  { label: 'vim.fs.basename', type: 'function', info: 'Basename' },
  { label: 'vim.fs.joinpath', type: 'function', info: 'Join path' },
  { label: 'vim.ui.input', type: 'function', info: 'UI input' },
  { label: 'vim.ui.select', type: 'function', info: 'UI select' },
  { label: 'vim.treesitter.get_parser', type: 'function', info: 'TS parser' },
  // Keywords + control
  { label: 'and', type: 'keyword', info: 'Logical AND' },
  { label: 'or', type: 'keyword', info: 'Logical OR' },
  { label: 'not', type: 'keyword', info: 'Logical NOT' },
  { label: 'if', type: 'keyword', info: 'If statement' },
  { label: 'then', type: 'keyword', info: 'Then' },
  { label: 'else', type: 'keyword', info: 'Else' },
  { label: 'elseif', type: 'keyword', info: 'Elseif' },
  { label: 'end', type: 'keyword', info: 'Block end' },
  { label: 'for', type: 'keyword', info: 'For loop' },
  { label: 'while', type: 'keyword', info: 'While loop' },
  { label: 'do', type: 'keyword', info: 'Do block' },
  { label: 'repeat', type: 'keyword', info: 'Repeat loop' },
  { label: 'until', type: 'keyword', info: 'Until cond' },
  { label: 'break', type: 'keyword', info: 'Break loop' },
  { label: 'goto', type: 'keyword', info: 'Goto label' },
  { label: 'function', type: 'keyword', info: 'Function keyword' },
  { label: 'return', type: 'keyword', info: 'Return' },
  { label: 'local', type: 'keyword', info: 'Local scope' },
  { label: 'true', type: 'keyword', info: 'Boolean true' },
  { label: 'false', type: 'keyword', info: 'Boolean false' },
  { label: 'nil', type: 'keyword', info: 'Nil value' },
  { label: 'in', type: 'keyword', info: 'for ... in' },
  // Snippets
  { label: 'for-i', type: 'snippet', apply: 'for ${i}=${1},${n} do\n\t${body}\nend', info: 'Numeric for' },
  { label: 'for-in', type: 'snippet', apply: 'for ${k},${v} in pairs(${t}) do\n\t${body}\nend', info: 'Generic for' },
  { label: 'while', type: 'snippet', apply: 'while ${cond} do\n\t${body}\nend', info: 'While loop' },
  { label: 'if-then', type: 'snippet', apply: 'if ${cond} then\n\t${body}\nend', info: 'If block' },
  { label: 'local-fn', type: 'snippet', apply: 'local function ${name}(${args})\n\t${body}\nend', info: 'Local function' },
  { label: 'class', type: 'snippet', apply: 'local ${Name} = {}\n${Name}.__index = ${Name}\n\nfunction ${Name}.new(${args})\n\tlocal self = setmetatable({}, ${Name})\n\t${init}\n\treturn self\nend\n', info: 'OOP class' },
  { label: 'module', type: 'snippet', apply: 'local M = {}\n\nfunction M.${name}(${args})\n\t${body}\nend\n\nreturn M\n', info: 'Lua module' },
  // Neovim options
  { label: 'vim.opt.number', type: 'option', info: 'Line numbers' },
  { label: 'vim.opt.relativenumber', type: 'option', info: 'Rel numbers' },
  { label: 'vim.opt.cursorline', type: 'option', info: 'Cursor line' },
  { label: 'vim.opt.expandtab', type: 'option', info: 'Expand tabs' },
  { label: 'vim.opt.shiftwidth', type: 'option', info: 'Shift width' },
  { label: 'vim.opt.tabstop', type: 'option', info: 'Tab stop' },
  { label: 'vim.opt.softtabstop', type: 'option', info: 'Soft tabstop' },
  { label: 'vim.opt.smartindent', type: 'option', info: 'Smart indent' },
  { label: 'vim.opt.wrap', type: 'option', info: 'Line wrap' },
  { label: 'vim.opt.hlsearch', type: 'option', info: 'HL search' },
  { label: 'vim.opt.incsearch', type: 'option', info: 'Inc search' },
  { label: 'vim.opt.ignorecase', type: 'option', info: 'Ignore case' },
  { label: 'vim.opt.smartcase', type: 'option', info: 'Smart case' },
  { label: 'vim.opt.termguicolors', type: 'option', info: 'True color' },
  { label: 'vim.opt.signcolumn', type: 'option', info: 'Sign column' },
  { label: 'vim.opt.clipboard', type: 'option', info: 'Clipboard' },
  { label: 'vim.opt.splitright', type: 'option', info: 'Split right' },
  { label: 'vim.opt.splitbelow', type: 'option', info: 'Split below' },
  { label: 'vim.opt.mouse', type: 'option', info: 'Mouse mode' },
  { label: 'vim.opt.scrolloff', type: 'option', info: 'Scroll offset' },
  { label: 'vim.opt.undofile', type: 'option', info: 'Persistent undo' },
  { label: 'vim.opt.backup', type: 'option', info: 'Backup files' },
  { label: 'vim.opt.writebackup', type: 'option', info: 'Write backup' },
  { label: 'vim.opt.swapfile', type: 'option', info: 'Swap file' },
  { label: 'vim.opt.updatetime', type: 'option', info: 'Update time' },
  { label: 'vim.opt.timeoutlen', type: 'option', info: 'Timeout ms' },
  { label: 'vim.opt.completeopt', type: 'option', info: 'Completion' },
  { label: 'vim.opt.pumheight', type: 'option', info: 'Popup height' },
  { label: 'vim.opt.showmode', type: 'option', info: 'Show mode' },
  { label: 'vim.opt.showtabline', type: 'option', info: 'Show tabline' },
  { label: 'vim.opt.laststatus', type: 'option', info: 'Status line' },
  { label: 'vim.opt.cmdheight', type: 'option', info: 'Cmdheight' },
  { label: 'vim.opt.fillchars', type: 'option', info: 'Fill chars' },
  { label: 'vim.opt.listchars', type: 'option', info: 'List chars' },
  { label: 'vim.opt.list', type: 'option', info: 'Show listchars' },
  { label: 'vim.opt.colorcolumn', type: 'option', info: 'Color column' },
  { label: 'vim.opt.textwidth', type: 'option', info: 'Text width' },
  { label: 'vim.opt.foldmethod', type: 'option', info: 'Fold method' },
  { label: 'vim.opt.foldlevel', type: 'option', info: 'Fold level' },
  { label: 'vim.opt.foldenable', type: 'option', info: 'Enable fold' },
  { label: 'vim.opt.hidden', type: 'option', info: 'Hidden buffers' },
  { label: 'vim.opt.lazyredraw', type: 'option', info: 'Lazy redraw' },
  { label: 'vim.opt.autoindent', type: 'option', info: 'Auto indent' },
  { label: 'vim.opt.cindent', type: 'option', info: 'C indent' },
  { label: 'vim.opt.autoread', type: 'option', info: 'Auto read' },
  { label: 'vim.opt.autowrite', type: 'option', info: 'Auto write' },
  { label: 'vim.opt.encoding', type: 'option', info: 'Encoding' },
  { label: 'vim.opt.fileencoding', type: 'option', info: 'File encoding' },
  { label: 'vim.opt.fileformat', type: 'option', info: 'File format' },
  { label: 'vim.opt.ttyfast', type: 'option', info: 'Fast terminal' },
  { label: 'vim.opt.backspace', type: 'option', info: 'Backspace behavior' },
  { label: 'vim.opt.whichwrap', type: 'option', info: 'Wrap keys' },
  { label: 'vim.opt.showmatch', type: 'option', info: 'Show matching' },
  { label: 'vim.opt.matchtime', type: 'option', info: 'Match time' },
  { label: 'vim.opt.shortmess', type: 'option', info: 'Short messages' },
  // Additional LÖVE
  { label: 'love.graphics.printf', type: 'function', info: 'Wrapped text' },
  { label: 'love.graphics.arc', type: 'function', info: 'Draw arc' },
  { label: 'love.graphics.ellipse', type: 'function', info: 'Draw ellipse' },
  { label: 'love.graphics.points', type: 'function', info: 'Draw points' },
  { label: 'love.graphics.stencil', type: 'function', info: 'Stencil buffer' },
  { label: 'love.graphics.setStencilTest', type: 'function', info: 'Stencil test' },
  { label: 'love.graphics.setScissor', type: 'function', info: 'Set scissor' },
  { label: 'love.graphics.getScissor', type: 'function', info: 'Get scissor' },
  { label: 'love.graphics.setShader', type: 'function', info: 'Set shader' },
  { label: 'love.graphics.newShader', type: 'function', info: 'New shader' },
  { label: 'love.graphics.setDefaultFilter', type: 'function', info: 'Default filter' },
  { label: 'love.graphics.setWireframe', type: 'function', info: 'Wireframe' },
  { label: 'love.graphics.setPointSize', type: 'function', info: 'Point size' },
  { label: 'love.graphics.setLineStyle', type: 'function', info: 'Line style' },
  { label: 'love.graphics.setLineJoin', type: 'function', info: 'Line join' },
  { label: 'love.graphics.newMesh', type: 'function', info: 'New mesh' },
  { label: 'love.graphics.drawInstanced', type: 'function', info: 'Instanced draw' },
  { label: 'love.graphics.captureScreenshot', type: 'function', info: 'Screenshot' },
  { label: 'love.graphics.newParticleSystem', type: 'function', info: 'Particles' },
  { label: 'love.graphics.newText', type: 'function', info: 'Text obj' },
  { label: 'love.graphics.newImageFont', type: 'function', info: 'Image font' },
  { label: 'love.graphics.setNewFont', type: 'function', info: 'Set new font' },
  { label: 'love.graphics.getFont', type: 'function', info: 'Get font' },
  { label: 'love.graphics.getCanvas', type: 'function', info: 'Get canvas' },
  { label: 'love.graphics.reset', type: 'function', info: 'Reset state' },
  { label: 'love.sound.newSoundData', type: 'function', info: 'Sound data' },
  { label: 'love.sound.newDecoder', type: 'function', info: 'Decoder' },
  { label: 'love.image.newImageData', type: 'function', info: 'Image data' },
  { label: 'love.data.encode', type: 'function', info: 'Encode data' },
  { label: 'love.data.decode', type: 'function', info: 'Decode data' },
  { label: 'love.data.hash', type: 'function', info: 'Hash data' },
  { label: 'love.data.compress', type: 'function', info: 'Compress data' },
  { label: 'love.data.decompress', type: 'function', info: 'Decompress data' },
  { label: 'love.system.getClipboardText', type: 'function', info: 'Get clipboard' },
  { label: 'love.system.setClipboardText', type: 'function', info: 'Set clipboard' },
  { label: 'love.system.getOS', type: 'function', info: 'OS name' },
  { label: 'love.system.getProcessorCount', type: 'function', info: 'CPU count' },
  { label: 'love.system.openURL', type: 'function', info: 'Open URL' },
  { label: 'love.system.vibrate', type: 'function', info: 'Vibrate' },
  { label: 'love.thread.newThread', type: 'function', info: 'New thread' },
  { label: 'love.thread.getChannel', type: 'function', info: 'Get channel' },
  { label: 'love.thread.newChannel', type: 'function', info: 'New channel' },
  // More Nvim API
  { label: 'vim.api.nvim_list_wins', type: 'function', info: 'List windows' },
  { label: 'vim.api.nvim_get_current_win', type: 'function', info: 'Current window' },
  { label: 'vim.api.nvim_set_current_win', type: 'function', info: 'Set current win' },
  { label: 'vim.api.nvim_win_get_buf', type: 'function', info: 'Win get buf' },
  { label: 'vim.api.nvim_win_get_position', type: 'function', info: 'Win position' },
  { label: 'vim.api.nvim_win_set_config', type: 'function', info: 'Set win config' },
  { label: 'vim.api.nvim_win_get_config', type: 'function', info: 'Get win config' },
  { label: 'vim.api.nvim_win_get_width', type: 'function', info: 'Win width' },
  { label: 'vim.api.nvim_win_set_width', type: 'function', info: 'Set win width' },
  { label: 'vim.api.nvim_win_get_height', type: 'function', info: 'Win height' },
  { label: 'vim.api.nvim_win_set_height', type: 'function', info: 'Set win height' },
  { label: 'vim.api.nvim_tabpage_list_wins', type: 'function', info: 'Tab wins' },
  { label: 'vim.api.nvim_list_tabpages', type: 'function', info: 'List tabs' },
  { label: 'vim.api.nvim_get_current_tabpage', type: 'function', info: 'Current tab' },
  { label: 'vim.api.nvim_set_current_tabpage', type: 'function', info: 'Set current tab' },
  { label: 'vim.api.nvim_buf_call', type: 'function', info: 'Call in buf' },
  { label: 'vim.api.nvim_buf_attach', type: 'function', info: 'Attach buf' },
  { label: 'vim.api.nvim_buf_clear_namespace', type: 'function', info: 'Clear ns' },
  { label: 'vim.api.nvim_buf_add_highlight', type: 'function', info: 'Add HL' },
  { label: 'vim.api.nvim_buf_set_extmark', type: 'function', info: 'Set extmark' },
  { label: 'vim.api.nvim_buf_get_extmarks', type: 'function', info: 'Get extmarks' },
  { label: 'vim.api.nvim_buf_del_extmark', type: 'function', info: 'Del extmark' },
  { label: 'vim.api.nvim_create_namespace', type: 'function', info: 'Create ns' },
  { label: 'vim.api.nvim_get_namespaces', type: 'function', info: 'List ns' },
  { label: 'vim.api.nvim_get_hl', type: 'function', info: 'Get highlight' },
  { label: 'vim.api.nvim_set_hl', type: 'function', info: 'Set highlight' },
  { label: 'vim.api.nvim_create_augroup', type: 'function', info: 'Create augroup' },
  { label: 'vim.api.nvim_del_augroup_by_name', type: 'function', info: 'Del augroup' },
  { label: 'vim.api.nvim_del_autocmd', type: 'function', info: 'Del autocmd' },
  { label: 'vim.api.nvim_exec_autocmds', type: 'function', info: 'Exec autocmds' },
  { label: 'vim.api.nvim_get_autocmds', type: 'function', info: 'Get autocmds' },
  { label: 'vim.api.nvim_feedkeys', type: 'function', info: 'Feed keys' },
  { label: 'vim.api.nvim_input', type: 'function', info: 'Input keys' },
  { label: 'vim.api.nvim_replace_termcodes', type: 'function', info: 'Replace terms' },
  { label: 'vim.api.nvim_get_mode', type: 'function', info: 'Current mode' },
  { label: 'vim.api.nvim_get_vvar', type: 'function', info: 'v: variable' },
  { label: 'vim.api.nvim_set_vvar', type: 'function', info: 'Set v: var' },
  { label: 'vim.api.nvim_get_var', type: 'function', info: 'g: variable' },
  { label: 'vim.api.nvim_set_var', type: 'function', info: 'Set g: var' },
  { label: 'vim.api.nvim_del_var', type: 'function', info: 'Del g: var' },
  { label: 'vim.api.nvim_get_proc_children', type: 'function', info: 'Proc children' },
  { label: 'vim.api.nvim_get_proc', type: 'function', info: 'Proc info' },
  { label: 'vim.api.nvim_list_runtime_paths', type: 'function', info: 'Runtime paths' },
  { label: 'vim.api.nvim_get_runtime_file', type: 'function', info: 'Get rt file' },
  { label: 'vim.api.nvim_paste', type: 'function', info: 'Paste text' },
  { label: 'vim.api.nvim_put', type: 'function', info: 'Put text' },
  { label: 'vim.api.nvim_get_color_by_name', type: 'function', info: 'Color code' },
  { label: 'vim.api.nvim_get_color_map', type: 'function', info: 'Color map' },
  { label: 'vim.api.nvim_select_popupmenu_item', type: 'function', info: 'Select pumitem' },
  // More vim utility
  { label: 'vim.pesc', type: 'function', info: 'Pattern escape' },
  { label: 'vim.stricmp', type: 'function', info: 'Case-insens cmp' },
  { label: 'vim.str_byteindex', type: 'function', info: 'Byte index' },
  { label: 'vim.str_utfindex', type: 'function', info: 'UTF index' },
  { label: 'vim.gsplit', type: 'function', info: 'Iter split' },
  { label: 'vim.tbl_islist', type: 'function', info: 'Is list' },
  { label: 'vim.tbl_add_reverse_lookup', type: 'function', info: 'Reverse lookup' },
  { label: 'vim.tbl_get', type: 'function', info: 'Nested get' },
  { label: 'vim.list_extend', type: 'function', info: 'Extend list' },
  { label: 'vim.list_slice', type: 'function', info: 'Slice list' },
  { label: 'vim.regex', type: 'function', info: 'Compile regex' },
  { label: 'vim.region', type: 'function', info: 'Get region' },
  { label: 'vim.str_byteindex', type: 'function', info: 'Byte idx' },
  // More string patterns
  { label: '%b()', type: 'pattern', info: 'Balanced parens' },
  { label: '%b[]', type: 'pattern', info: 'Balanced brackets' },
  { label: '%b{}', type: 'pattern', info: 'Balanced braces' },
  { label: '%f[set]', type: 'pattern', info: 'Frontier pattern' },
  { label: '%1', type: 'pattern', info: 'Captured group 1' },
  // Bit32 library (5.2)
  { label: 'bit32.arshift', type: 'function', info: 'Arith shift right' },
  { label: 'bit32.band', type: 'function', info: 'Bitwise AND' },
  { label: 'bit32.bnot', type: 'function', info: 'Bitwise NOT' },
  { label: 'bit32.bor', type: 'function', info: 'Bitwise OR' },
  { label: 'bit32.btest', type: 'function', info: 'Bit test' },
  { label: 'bit32.bxor', type: 'function', info: 'Bitwise XOR' },
  { label: 'bit32.extract', type: 'function', info: 'Extract bits' },
  { label: 'bit32.lrotate', type: 'function', info: 'Left rotate' },
  { label: 'bit32.lshift', type: 'function', info: 'Left shift' },
  { label: 'bit32.replace', type: 'function', info: 'Replace bits' },
  { label: 'bit32.rrotate', type: 'function', info: 'Right rotate' },
  { label: 'bit32.rshift', type: 'function', info: 'Right shift' },
  // utf8 library
  { label: 'utf8.char', type: 'function', info: 'UTF char' },
  { label: 'utf8.charpattern', type: 'constant', info: 'UTF pattern' },
  { label: 'utf8.codepoint', type: 'function', info: 'Codepoint' },
  { label: 'utf8.codes', type: 'function', info: 'Iter codepoints' },
  { label: 'utf8.len', type: 'function', info: 'UTF length' },
  { label: 'utf8.offset', type: 'function', info: 'UTF offset' },
  // Package library
  { label: 'package.loaded', type: 'variable', info: 'Loaded modules' },
  { label: 'package.path', type: 'variable', info: 'Lua search path' },
  { label: 'package.cpath', type: 'variable', info: 'C search path' },
  { label: 'package.loaders', type: 'variable', info: 'Loaders (5.1)' },
  { label: 'package.searchers', type: 'variable', info: 'Searchers (5.2+)' },
  { label: 'package.preload', type: 'variable', info: 'Preloaded' },
  { label: 'package.config', type: 'variable', info: 'Path config' },
  { label: 'package.searchpath', type: 'function', info: 'Search path' },
  { label: 'package.loadlib', type: 'function', info: 'Load C lib' },
  // Roblox common (widely used)
  { label: 'game', type: 'variable', info: 'DataModel' },
  { label: 'workspace', type: 'variable', info: 'Workspace' },
  { label: 'script', type: 'variable', info: 'Current script' },
  { label: 'Instance.new', type: 'function', info: 'New instance' },
  { label: 'Vector3.new', type: 'function', info: 'Vector3' },
  { label: 'Vector2.new', type: 'function', info: 'Vector2' },
  { label: 'CFrame.new', type: 'function', info: 'CFrame' },
  { label: 'Color3.new', type: 'function', info: 'Color3' },
  { label: 'Color3.fromRGB', type: 'function', info: 'Color3 RGB' },
  { label: 'UDim.new', type: 'function', info: 'UDim' },
  { label: 'UDim2.new', type: 'function', info: 'UDim2' },
  { label: 'Ray.new', type: 'function', info: 'Ray' },
  { label: 'Region3.new', type: 'function', info: 'Region3' },
  { label: 'game:GetService', type: 'function', info: 'Get service' },
  { label: 'game:BindToClose', type: 'function', info: 'Bind close' },
  { label: 'task.wait', type: 'function', info: 'Task wait' },
  { label: 'task.spawn', type: 'function', info: 'Task spawn' },
  { label: 'task.delay', type: 'function', info: 'Task delay' },
  { label: 'task.defer', type: 'function', info: 'Task defer' },
  { label: 'task.synchronize', type: 'function', info: 'Task sync' },
  { label: 'task.desynchronize', type: 'function', info: 'Task desync' },
  { label: 'warn', type: 'function', info: 'Log warning' },
  { label: 'wait', type: 'function', info: 'Wait (legacy)' },
  { label: 'delay', type: 'function', info: 'Delay (legacy)' },
  { label: 'spawn', type: 'function', info: 'Spawn (legacy)' },
  { label: 'tick', type: 'function', info: 'Current tick' },
  // Additional snippets
  { label: 'function-def', type: 'snippet', apply: 'function ${name}(${args})\n\t${body}\nend', info: 'Function def' },
  { label: 'nvim-autocmd', type: 'snippet', apply: "vim.api.nvim_create_autocmd('${event}', {\n\tpattern = '${pat}',\n\tcallback = function(${args})\n\t\t${body}\n\tend,\n})", info: 'Autocmd lua' },
  { label: 'nvim-keymap', type: 'snippet', apply: "vim.keymap.set('${mode}', '${lhs}', function() ${body} end, { desc = '${desc}' })", info: 'Keymap lua' },
  { label: 'lazy-plugin', type: 'snippet', apply: "{\n\t'${repo}',\n\tconfig = function()\n\t\trequire('${name}').setup({})\n\tend,\n}", info: 'lazy.nvim plugin' },
  // More OpenResty cosocket
  { label: 'sock:connect', type: 'method', info: 'Sock connect' },
  { label: 'sock:send', type: 'method', info: 'Sock send' },
  { label: 'sock:receive', type: 'method', info: 'Sock receive' },
  { label: 'sock:close', type: 'method', info: 'Sock close' },
  { label: 'sock:settimeout', type: 'method', info: 'Set timeout' },
  { label: 'sock:setoption', type: 'method', info: 'Set option' },
  { label: 'sock:setkeepalive', type: 'method', info: 'Keepalive' },
  { label: 'sock:getreusedtimes', type: 'method', info: 'Reuse count' },
  { label: 'sock:sslhandshake', type: 'method', info: 'SSL handshake' },
  // Busted test framework
  { label: 'describe', type: 'function', info: 'Busted describe' },
  { label: 'it', type: 'function', info: 'Busted test' },
  { label: 'before_each', type: 'function', info: 'Before hook' },
  { label: 'after_each', type: 'function', info: 'After hook' },
  { label: 'setup', type: 'function', info: 'Setup hook' },
  { label: 'teardown', type: 'function', info: 'Teardown hook' },
  { label: 'finally', type: 'function', info: 'Finally block' },
  { label: 'assert.is_true', type: 'function', info: 'Assert true' },
  { label: 'assert.is_false', type: 'function', info: 'Assert false' },
  { label: 'assert.is_nil', type: 'function', info: 'Assert nil' },
  { label: 'assert.is_not_nil', type: 'function', info: 'Assert not nil' },
  { label: 'assert.equals', type: 'function', info: 'Assert equal' },
  { label: 'assert.same', type: 'function', info: 'Deep equal' },
  { label: 'assert.are_equal', type: 'function', info: 'Are equal' },
  { label: 'assert.are_not_equal', type: 'function', info: 'Are not equal' },
  { label: 'assert.has_error', type: 'function', info: 'Has error' },
  { label: 'assert.truthy', type: 'function', info: 'Truthy' },
  { label: 'assert.falsy', type: 'function', info: 'Falsy' },
  { label: 'assert.matches', type: 'function', info: 'String matches' },
  // LuaRocks helpers
  { label: 'luarocks.install', type: 'function', info: 'LuaRocks install' },
  { label: 'luarocks.require', type: 'function', info: 'LuaRocks require' },
  // lfs (luafilesystem)
  { label: 'lfs.attributes', type: 'function', info: 'File attrs' },
  { label: 'lfs.chdir', type: 'function', info: 'Change dir' },
  { label: 'lfs.currentdir', type: 'function', info: 'Current dir' },
  { label: 'lfs.dir', type: 'function', info: 'Iter dir' },
  { label: 'lfs.lock', type: 'function', info: 'Lock file' },
  { label: 'lfs.mkdir', type: 'function', info: 'Make dir' },
  { label: 'lfs.rmdir', type: 'function', info: 'Remove dir' },
  { label: 'lfs.touch', type: 'function', info: 'Touch file' },
  { label: 'lfs.symlinkattributes', type: 'function', info: 'Symlink attrs' },
  { label: 'lfs.link', type: 'function', info: 'Hard link' },
  // cjson
  { label: 'cjson.encode', type: 'function', info: 'JSON encode' },
  { label: 'cjson.decode', type: 'function', info: 'JSON decode' },
  { label: 'cjson.null', type: 'constant', info: 'JSON null' },
  { label: 'cjson.empty_array', type: 'constant', info: 'Empty array' },
  { label: 'cjson.encode_empty_table_as_object', type: 'function', info: 'Obj vs array' },
  // Lua LPeg
  { label: 'lpeg.P', type: 'function', info: 'Pattern literal' },
  { label: 'lpeg.S', type: 'function', info: 'Char set' },
  { label: 'lpeg.R', type: 'function', info: 'Char range' },
  { label: 'lpeg.B', type: 'function', info: 'Behind pattern' },
  { label: 'lpeg.C', type: 'function', info: 'Capture' },
  { label: 'lpeg.Cc', type: 'function', info: 'Const capture' },
  { label: 'lpeg.Cf', type: 'function', info: 'Fold capture' },
  { label: 'lpeg.Cg', type: 'function', info: 'Group capture' },
  { label: 'lpeg.Ct', type: 'function', info: 'Table capture' },
  { label: 'lpeg.match', type: 'function', info: 'Pattern match' },
  { label: 'lpeg.V', type: 'function', info: 'Grammar var' },
  { label: 'lpeg.Cp', type: 'function', info: 'Position capture' },
  // Busy lua patterns
  { label: 'tostring-number', type: 'snippet', apply: 'tostring(${n})', info: 'Num to str' },
  { label: 'tonumber-str', type: 'snippet', apply: 'tonumber(${s})', info: 'Str to num' },
  // Neovim treesitter
  { label: 'vim.treesitter.query.parse', type: 'function', info: 'Parse query' },
  { label: 'vim.treesitter.get_node', type: 'function', info: 'Get node' },
  { label: 'vim.treesitter.get_node_text', type: 'function', info: 'Node text' },
  { label: 'vim.treesitter.get_captures_at_cursor', type: 'function', info: 'Captures at cursor' },
  { label: 'vim.treesitter.highlighter', type: 'variable', info: 'TS highlighter' },
  { label: 'vim.treesitter.start', type: 'function', info: 'Start TS' },
  { label: 'vim.treesitter.stop', type: 'function', info: 'Stop TS' },
  // Nvim UI more
  { label: 'vim.ui.open', type: 'function', info: 'Open URL' },
  // Nvim utility more
  { label: 'vim.deepcopy', type: 'function', info: 'Deep copy' },
  { label: 'vim.pretty_print', type: 'function', info: 'Pretty print' },
  { label: 'vim.print', type: 'function', info: 'Print' },
  { label: 'vim.F', type: 'table', info: 'Functional utils' },
  { label: 'vim.F.if_nil', type: 'function', info: 'If nil default' },
  // Health / checkhealth
  { label: 'vim.health.ok', type: 'function', info: 'Health OK' },
  { label: 'vim.health.warn', type: 'function', info: 'Health WARN' },
  { label: 'vim.health.error', type: 'function', info: 'Health ERR' },
  { label: 'vim.health.info', type: 'function', info: 'Health info' },
  { label: 'vim.health.start', type: 'function', info: 'Health start' },
  // LSP client functions
  { label: 'vim.lsp.get_active_clients', type: 'function', info: 'Active clients' },
  { label: 'vim.lsp.get_clients', type: 'function', info: 'Get clients' },
  { label: 'vim.lsp.buf_request', type: 'function', info: 'Buf request' },
  { label: 'vim.lsp.buf_request_all', type: 'function', info: 'Buf req all' },
  { label: 'vim.lsp.buf_request_sync', type: 'function', info: 'Buf req sync' },
  { label: 'vim.lsp.with', type: 'function', info: 'LSP handler wrap' },
  { label: 'vim.lsp.handlers', type: 'table', info: 'LSP handlers' },
  { label: 'vim.lsp.protocol.SymbolKind', type: 'table', info: 'Symbol kinds' },
  { label: 'vim.lsp.protocol.CompletionItemKind', type: 'table', info: 'Completion kinds' },
  { label: 'vim.lsp.util.make_position_params', type: 'function', info: 'Pos params' },
  { label: 'vim.lsp.util.make_range_params', type: 'function', info: 'Range params' },
  { label: 'vim.lsp.util.apply_text_edits', type: 'function', info: 'Apply text edits' },
  { label: 'vim.lsp.util.jump_to_location', type: 'function', info: 'Jump to loc' },
  { label: 'vim.lsp.util.locations_to_items', type: 'function', info: 'Locs to items' },
  { label: 'vim.lsp.util.open_floating_preview', type: 'function', info: 'Float preview' },
  // Lualine / statusline helpers (common)
  { label: 'require("lualine").setup', type: 'function', info: 'Lualine setup' },
  { label: 'require("telescope").setup', type: 'function', info: 'Telescope setup' },
  { label: 'require("nvim-tree").setup', type: 'function', info: 'NvimTree setup' },
  { label: 'require("bufferline").setup', type: 'function', info: 'Bufferline setup' },
  { label: 'require("treesitter").setup', type: 'function', info: 'Treesitter setup' },
  // Common LOVE callbacks extras
  { label: 'love.filedropped', type: 'function', info: 'File dropped' },
  { label: 'love.directorydropped', type: 'function', info: 'Dir dropped' },
  { label: 'love.joystickadded', type: 'function', info: 'Joystick added' },
  { label: 'love.joystickremoved', type: 'function', info: 'Joystick removed' },
  { label: 'love.joystickaxis', type: 'function', info: 'Axis event' },
  { label: 'love.joystickhat', type: 'function', info: 'Hat event' },
  { label: 'love.joystickpressed', type: 'function', info: 'Joystick press' },
  { label: 'love.joystickreleased', type: 'function', info: 'Joystick release' },
  { label: 'love.gamepadaxis', type: 'function', info: 'Gamepad axis' },
  { label: 'love.gamepadpressed', type: 'function', info: 'Gamepad press' },
  { label: 'love.gamepadreleased', type: 'function', info: 'Gamepad release' },
  { label: 'love.visible', type: 'function', info: 'Visibility' },
  { label: 'love.lowmemory', type: 'function', info: 'Low memory' },
  { label: 'love.errhand', type: 'function', info: 'Error handler' },
  { label: 'love.threaderror', type: 'function', info: 'Thread error' },
  // More ngx.req
  { label: 'ngx.req.set_body_data', type: 'function', info: 'Set body data' },
  { label: 'ngx.req.set_body_file', type: 'function', info: 'Set body file' },
  { label: 'ngx.req.set_uri', type: 'function', info: 'Set URI' },
  { label: 'ngx.req.set_uri_args', type: 'function', info: 'Set URI args' },
  { label: 'ngx.req.discard_body', type: 'function', info: 'Discard body' },
  { label: 'ngx.req.init_body', type: 'function', info: 'Init body' },
  { label: 'ngx.req.append_body', type: 'function', info: 'Append body' },
  { label: 'ngx.req.finish_body', type: 'function', info: 'Finish body' },
  { label: 'ngx.req.socket', type: 'function', info: 'Request socket' },
  // Additional Lua snippets
  { label: 'table-insert', type: 'snippet', apply: 'table.insert(${t}, ${v})', info: 'Insert' },
  { label: 'table-remove', type: 'snippet', apply: 'table.remove(${t}, ${i})', info: 'Remove' },
  { label: 'table-concat', type: 'snippet', apply: 'table.concat(${t}, ${sep})', info: 'Concat' },
  { label: 'iter-ipairs', type: 'snippet', apply: 'for i, v in ipairs(${t}) do\n\t${body}\nend', info: 'Array iter' },
  { label: 'iter-pairs', type: 'snippet', apply: 'for k, v in pairs(${t}) do\n\t${body}\nend', info: 'Key iter' },
  { label: 'switch-ish', type: 'snippet', apply: 'local cases = {\n\t[${k}] = function() ${body} end,\n}\nlocal f = cases[${x}] or function() ${default} end\nf()\n', info: 'Table switch' },
  { label: 'mt-index', type: 'snippet', apply: 'setmetatable(${t}, { __index = ${base} })', info: 'Inherit via mt' },
  // Convenience printing
  { label: 'print-fmt', type: 'snippet', apply: 'print(string.format("${fmt}", ${args}))', info: 'Formatted print' },
  // Roblox UI
  { label: 'Enum', type: 'variable', info: 'Roblox enum' },
  { label: 'BrickColor.new', type: 'function', info: 'Brick color' },
  { label: 'TweenInfo.new', type: 'function', info: 'TweenInfo' },
  // Control flow
  { label: 'goto-label', type: 'snippet', apply: '::${label}::\n${body}', info: 'Goto target' },
  { label: 'break-when', type: 'snippet', apply: 'if ${cond} then break end', info: 'Conditional break' },
  // Misc
  { label: 'nil-check', type: 'snippet', apply: 'if ${v} == nil then ${body} end', info: 'Nil check' },
  { label: 'default-val', type: 'snippet', apply: 'local ${x} = ${v} or ${default}', info: 'Default value' },
  { label: 'ternary', type: 'snippet', apply: '(${cond} and ${a}) or ${b}', info: 'Ternary' },
  // Bit library (LuaJIT)
  { label: 'bit.band', type: 'function', info: 'Bit AND' },
  { label: 'bit.bor', type: 'function', info: 'Bit OR' },
  { label: 'bit.bxor', type: 'function', info: 'Bit XOR' },
  { label: 'bit.bnot', type: 'function', info: 'Bit NOT' },
  { label: 'bit.lshift', type: 'function', info: 'Left shift' },
  { label: 'bit.rshift', type: 'function', info: 'Right shift' },
  { label: 'bit.arshift', type: 'function', info: 'Arith right shift' },
  { label: 'bit.rol', type: 'function', info: 'Rotate left' },
  { label: 'bit.ror', type: 'function', info: 'Rotate right' },
  { label: 'bit.bswap', type: 'function', info: 'Byte swap' },
  { label: 'bit.tobit', type: 'function', info: 'To 32-bit int' },
  { label: 'bit.tohex', type: 'function', info: 'To hex string' },
  // FFI (LuaJIT)
  { label: 'ffi.cdef', type: 'function', info: 'FFI cdef' },
  { label: 'ffi.C', type: 'variable', info: 'FFI C namespace' },
  { label: 'ffi.new', type: 'function', info: 'New cdata' },
  { label: 'ffi.cast', type: 'function', info: 'Cast cdata' },
  { label: 'ffi.typeof', type: 'function', info: 'C typeof' },
  { label: 'ffi.sizeof', type: 'function', info: 'C sizeof' },
  { label: 'ffi.alignof', type: 'function', info: 'C alignof' },
  { label: 'ffi.offsetof', type: 'function', info: 'C offsetof' },
  { label: 'ffi.istype', type: 'function', info: 'Type check' },
  { label: 'ffi.load', type: 'function', info: 'Load shared lib' },
  { label: 'ffi.string', type: 'function', info: 'C string to Lua' },
  { label: 'ffi.copy', type: 'function', info: 'Copy bytes' },
  { label: 'ffi.fill', type: 'function', info: 'Fill bytes' },
  { label: 'ffi.gc', type: 'function', info: 'Finalizer' },
  { label: 'ffi.metatype', type: 'function', info: 'Attach metatable' },
  { label: 'ffi.errno', type: 'function', info: 'Errno' },
  { label: 'ffi.os', type: 'variable', info: 'OS name' },
  { label: 'ffi.arch', type: 'variable', info: 'Arch name' },
  { label: 'ffi.abi', type: 'function', info: 'ABI check' },
];
