// Completion entries for markdown.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  { label: '#', type: 'snippet', apply: '# ${heading}', info: 'Heading 1' },
  { label: '##', type: 'snippet', apply: '## ${heading}', info: 'Heading 2' },
  { label: '###', type: 'snippet', apply: '### ${heading}', info: 'Heading 3' },
  { label: '####', type: 'snippet', apply: '#### ${heading}', info: 'Heading 4' },
  { label: '#####', type: 'snippet', apply: '##### ${heading}', info: 'Heading 5' },
  { label: '######', type: 'snippet', apply: '###### ${heading}', info: 'Heading 6' },
  { label: 'bold', type: 'snippet', apply: '**${text}**', info: 'Bold text' },
  { label: 'italic', type: 'snippet', apply: '*${text}*', info: 'Italic text' },
  { label: 'bold-italic', type: 'snippet', apply: '***${text}***', info: 'Bold italic' },
  { label: 'strikethrough', type: 'snippet', apply: '~~${text}~~', info: 'Strikethrough' },
  { label: 'highlight', type: 'snippet', apply: '==${text}==', info: 'Highlight' },
  { label: 'inline-code', type: 'snippet', apply: '`${code}`', info: 'Inline code' },
  { label: 'code-block', type: 'snippet', apply: '```${lang}\n${code}\n```', info: 'Fenced code block' },
  { label: 'link', type: 'snippet', apply: '[${text}](${url})', info: 'Hyperlink' },
  { label: 'link-with-title', type: 'snippet', apply: '[${text}](${url} "${title}")', info: 'Link w/ title' },
  { label: 'image', type: 'snippet', apply: '![${alt}](${url})', info: 'Image' },
  { label: 'image-with-title', type: 'snippet', apply: '![${alt}](${url} "${title}")', info: 'Image w/ title' },
  { label: 'reference-link', type: 'snippet', apply: '[${text}][${ref}]', info: 'Reference link' },
  { label: 'autolink', type: 'snippet', apply: '<${url}>', info: 'Automatic link' },
  { label: 'blockquote', type: 'snippet', apply: '> ${text}', info: 'Block quote' },
  { label: 'nested-blockquote', type: 'snippet', apply: '> ${text}\n> > ${nested}', info: 'Nested quote' },
  { label: 'ordered-list', type: 'snippet', apply: '1. ${item}\n2. ${item}\n3. ${item}', info: 'Numbered list' },
  { label: 'unordered-list', type: 'snippet', apply: '- ${item}\n- ${item}\n- ${item}', info: 'Bullet list' },
  { label: 'nested-list', type: 'snippet', apply: '- ${item}\n  - ${nested}', info: 'Nested list' },
  { label: 'task-list', type: 'snippet', apply: '- [ ] ${task}', info: 'Task list item' },
  { label: 'task-unchecked', type: 'snippet', apply: '- [ ] ${task}', info: 'Unchecked task' },
  { label: 'task-checked', type: 'snippet', apply: '- [x] ${task}', info: 'Checked task' },
  { label: 'horizontal-rule', type: 'snippet', apply: '---', info: 'Horizontal rule' },
  { label: 'line-break', type: 'snippet', apply: '  \n', info: 'Hard line break' },
  { label: 'table', type: 'snippet', apply: '| ${Col1} | ${Col2} |\n| --- | --- |\n| ${a} | ${b} |', info: 'Basic table' },
  { label: 'table-aligned', type: 'snippet', apply: '| ${Col1} | ${Col2} |\n| :--- | ---: |\n| ${a} | ${b} |', info: 'Aligned table' },
  { label: 'footnote', type: 'snippet', apply: '${text}[^${id}]\n\n[^${id}]: ${note}', info: 'Footnote' },
  { label: 'definition', type: 'snippet', apply: '${term}\n: ${definition}', info: 'Definition list' },
  { label: 'details', type: 'snippet', apply: '<details>\n<summary>${summary}</summary>\n\n${body}\n\n</details>', info: 'Collapsible section' },
  { label: 'frontmatter', type: 'snippet', apply: '---\ntitle: ${title}\ndate: ${date}\ntags: [${tag}]\n---', info: 'YAML frontmatter' },
  { label: 'mermaid', type: 'snippet', apply: '```mermaid\n${diagram}\n```', info: 'Mermaid diagram' },
  { label: 'math-inline', type: 'snippet', apply: '$${math}$', info: 'Inline math' },
  { label: 'math-block', type: 'snippet', apply: '$$\n${math}\n$$', info: 'Block math' },
  { label: 'html-comment', type: 'snippet', apply: '<!-- ${comment} -->', info: 'HTML comment' },
  { label: 'keyboard', type: 'snippet', apply: '<kbd>${key}</kbd>', info: 'Keyboard key' },
  { label: 'abbreviation', type: 'snippet', apply: '*[${abbr}]: ${full}', info: 'Abbreviation def' },
  // Common code fences
  { label: 'python', type: 'snippet', apply: '```python\n${code}\n```', info: 'Python fence' },
  { label: 'javascript', type: 'snippet', apply: '```javascript\n${code}\n```', info: 'JS fence' },
  { label: 'typescript', type: 'snippet', apply: '```typescript\n${code}\n```', info: 'TS fence' },
  { label: 'bash', type: 'snippet', apply: '```bash\n${code}\n```', info: 'Bash fence' },
  { label: 'shell', type: 'snippet', apply: '```sh\n${code}\n```', info: 'Shell fence' },
  { label: 'json', type: 'snippet', apply: '```json\n${code}\n```', info: 'JSON fence' },
  { label: 'yaml', type: 'snippet', apply: '```yaml\n${code}\n```', info: 'YAML fence' },
  { label: 'rust', type: 'snippet', apply: '```rust\n${code}\n```', info: 'Rust fence' },
  { label: 'go', type: 'snippet', apply: '```go\n${code}\n```', info: 'Go fence' },
  { label: 'java', type: 'snippet', apply: '```java\n${code}\n```', info: 'Java fence' },
  { label: 'cpp', type: 'snippet', apply: '```cpp\n${code}\n```', info: 'C++ fence' },
  { label: 'c', type: 'snippet', apply: '```c\n${code}\n```', info: 'C fence' },
  { label: 'csharp', type: 'snippet', apply: '```csharp\n${code}\n```', info: 'C# fence' },
  { label: 'php', type: 'snippet', apply: '```php\n${code}\n```', info: 'PHP fence' },
  { label: 'ruby', type: 'snippet', apply: '```ruby\n${code}\n```', info: 'Ruby fence' },
  { label: 'kotlin', type: 'snippet', apply: '```kotlin\n${code}\n```', info: 'Kotlin fence' },
  { label: 'swift', type: 'snippet', apply: '```swift\n${code}\n```', info: 'Swift fence' },
  { label: 'sql', type: 'snippet', apply: '```sql\n${code}\n```', info: 'SQL fence' },
  { label: 'html', type: 'snippet', apply: '```html\n${code}\n```', info: 'HTML fence' },
  { label: 'css', type: 'snippet', apply: '```css\n${code}\n```', info: 'CSS fence' },
  { label: 'diff', type: 'snippet', apply: '```diff\n${code}\n```', info: 'Diff fence' },
  // CommonMark basics
  { label: 'h1', type: 'snippet', apply: '# ${title}', info: 'H1 heading' },
  { label: 'h2', type: 'snippet', apply: '## ${title}', info: 'H2 heading' },
  { label: 'h3', type: 'snippet', apply: '### ${title}', info: 'H3 heading' },
  { label: 'h4', type: 'snippet', apply: '#### ${title}', info: 'H4 heading' },
  { label: 'h5', type: 'snippet', apply: '##### ${title}', info: 'H5 heading' },
  { label: 'h6', type: 'snippet', apply: '###### ${title}', info: 'H6 heading' },
  { label: 'bold', type: 'snippet', apply: '**${text}**', info: 'Bold' },
  { label: 'italic', type: 'snippet', apply: '*${text}*', info: 'Italic' },
  { label: 'bold-italic', type: 'snippet', apply: '***${text}***', info: 'Bold italic' },
  { label: 'strike', type: 'snippet', apply: '~~${text}~~', info: 'Strikethrough' },
  { label: 'code', type: 'snippet', apply: '`${code}`', info: 'Inline code' },
  { label: 'link', type: 'snippet', apply: '[${text}](${url})', info: 'Link' },
  { label: 'link-title', type: 'snippet', apply: '[${text}](${url} "${title}")', info: 'Link w/ title' },
  { label: 'image', type: 'snippet', apply: '![${alt}](${url})', info: 'Image' },
  { label: 'image-title', type: 'snippet', apply: '![${alt}](${url} "${title}")', info: 'Image w/ title' },
  { label: 'ref-link', type: 'snippet', apply: '[${text}][${id}]', info: 'Reference link' },
  { label: 'ref-def', type: 'snippet', apply: '[${id}]: ${url} "${title}"', info: 'Link definition' },
  { label: 'auto-link', type: 'snippet', apply: '<${url}>', info: 'Auto link' },
  { label: 'hr', type: 'snippet', apply: '---', info: 'Horizontal rule' },
  { label: 'blockquote', type: 'snippet', apply: '> ${text}', info: 'Blockquote' },
  { label: 'ul', type: 'snippet', apply: '- ${item}', info: 'Bullet list' },
  { label: 'ol', type: 'snippet', apply: '1. ${item}', info: 'Ordered list' },
  { label: 'nested-ul', type: 'snippet', apply: '- item\n  - subitem', info: 'Nested bullets' },
  { label: 'line-break', type: 'snippet', apply: '  \n', info: 'Hard line break' },
  // More code fences
  { label: 'fenced', type: 'snippet', apply: '```${lang}\n${code}\n```', info: 'Fenced code' },
  { label: 'py', type: 'snippet', apply: '```python\n${code}\n```', info: 'Python fence' },
  { label: 'rs', type: 'snippet', apply: '```rust\n${code}\n```', info: 'Rust fence' },
  { label: 'go', type: 'snippet', apply: '```go\n${code}\n```', info: 'Go fence' },
  { label: 'sh', type: 'snippet', apply: '```sh\n${code}\n```', info: 'Shell fence' },
  { label: 'zsh', type: 'snippet', apply: '```zsh\n${code}\n```', info: 'Zsh fence' },
  { label: 'fish', type: 'snippet', apply: '```fish\n${code}\n```', info: 'Fish fence' },
  { label: 'powershell', type: 'snippet', apply: '```powershell\n${code}\n```', info: 'PS fence' },
  { label: 'json', type: 'snippet', apply: '```json\n${code}\n```', info: 'JSON fence' },
  { label: 'yaml', type: 'snippet', apply: '```yaml\n${code}\n```', info: 'YAML fence' },
  { label: 'toml', type: 'snippet', apply: '```toml\n${code}\n```', info: 'TOML fence' },
  { label: 'xml', type: 'snippet', apply: '```xml\n${code}\n```', info: 'XML fence' },
  { label: 'ts', type: 'snippet', apply: '```typescript\n${code}\n```', info: 'TS fence' },
  { label: 'js', type: 'snippet', apply: '```javascript\n${code}\n```', info: 'JS fence' },
  { label: 'cpp', type: 'snippet', apply: '```cpp\n${code}\n```', info: 'C++ fence' },
  { label: 'c-code', type: 'snippet', apply: '```c\n${code}\n```', info: 'C fence' },
  { label: 'csharp', type: 'snippet', apply: '```csharp\n${code}\n```', info: 'C# fence' },
  { label: 'dart', type: 'snippet', apply: '```dart\n${code}\n```', info: 'Dart fence' },
  { label: 'php', type: 'snippet', apply: '```php\n${code}\n```', info: 'PHP fence' },
  { label: 'elixir', type: 'snippet', apply: '```elixir\n${code}\n```', info: 'Elixir fence' },
  { label: 'haskell', type: 'snippet', apply: '```haskell\n${code}\n```', info: 'Haskell fence' },
  { label: 'ocaml', type: 'snippet', apply: '```ocaml\n${code}\n```', info: 'OCaml fence' },
  { label: 'scala', type: 'snippet', apply: '```scala\n${code}\n```', info: 'Scala fence' },
  { label: 'clojure', type: 'snippet', apply: '```clojure\n${code}\n```', info: 'Clojure fence' },
  { label: 'r-code', type: 'snippet', apply: '```r\n${code}\n```', info: 'R fence' },
  { label: 'lua', type: 'snippet', apply: '```lua\n${code}\n```', info: 'Lua fence' },
  { label: 'nim', type: 'snippet', apply: '```nim\n${code}\n```', info: 'Nim fence' },
  { label: 'crystal', type: 'snippet', apply: '```crystal\n${code}\n```', info: 'Crystal fence' },
  { label: 'zig', type: 'snippet', apply: '```zig\n${code}\n```', info: 'Zig fence' },
  { label: 'dockerfile', type: 'snippet', apply: '```dockerfile\n${code}\n```', info: 'Dockerfile fence' },
  { label: 'nginx', type: 'snippet', apply: '```nginx\n${code}\n```', info: 'nginx fence' },
  { label: 'make', type: 'snippet', apply: '```make\n${code}\n```', info: 'Makefile fence' },
  { label: 'cmake', type: 'snippet', apply: '```cmake\n${code}\n```', info: 'CMake fence' },
  { label: 'ini', type: 'snippet', apply: '```ini\n${code}\n```', info: 'INI fence' },
  { label: 'properties', type: 'snippet', apply: '```properties\n${code}\n```', info: 'Properties fence' },
  { label: 'markdown', type: 'snippet', apply: '```markdown\n${code}\n```', info: 'Markdown fence' },
  { label: 'text', type: 'snippet', apply: '```text\n${code}\n```', info: 'Text fence' },
  // GFM features
  { label: 'task-list', type: 'snippet', apply: '- [ ] ${task}', info: 'Task list item' },
  { label: 'task-done', type: 'snippet', apply: '- [x] ${task}', info: 'Done task' },
  { label: 'table', type: 'snippet', apply: '| Col1 | Col2 |\n| --- | --- |\n| A | B |', info: 'GFM table' },
  { label: 'table-aligned', type: 'snippet', apply: '| Left | Center | Right |\n| :--- | :---: | ---: |\n| a | b | c |', info: 'Aligned table' },
  { label: 'alert-note', type: 'snippet', apply: '> [!NOTE]\n> ${text}', info: 'GFM note' },
  { label: 'alert-tip', type: 'snippet', apply: '> [!TIP]\n> ${text}', info: 'GFM tip' },
  { label: 'alert-important', type: 'snippet', apply: '> [!IMPORTANT]\n> ${text}', info: 'GFM important' },
  { label: 'alert-warning', type: 'snippet', apply: '> [!WARNING]\n> ${text}', info: 'GFM warning' },
  { label: 'alert-caution', type: 'snippet', apply: '> [!CAUTION]\n> ${text}', info: 'GFM caution' },
  // MDX
  { label: 'mdx-import', type: 'snippet', apply: "import ${name} from '${path}';", info: 'MDX import' },
  { label: 'mdx-export', type: 'snippet', apply: 'export const ${name} = ${value};', info: 'MDX export' },
  { label: 'jsx-comp', type: 'snippet', apply: '<${Component} />', info: 'JSX self-closing' },
  { label: 'jsx-expr', type: 'snippet', apply: '{${expression}}', info: 'MDX expression' },
  { label: 'frontmatter', type: 'snippet', apply: '---\ntitle: ${title}\ndate: ${date}\n---\n', info: 'YAML frontmatter' },
  { label: 'toml-fm', type: 'snippet', apply: '+++\ntitle = "${title}"\ndate = "${date}"\n+++\n', info: 'TOML frontmatter' },
  // Docusaurus directives
  { label: ':::note', type: 'snippet', apply: ':::note\n${text}\n:::', info: 'Note admonition' },
  { label: ':::warning', type: 'snippet', apply: ':::warning\n${text}\n:::', info: 'Warning admonition' },
  { label: ':::tip', type: 'snippet', apply: ':::tip\n${text}\n:::', info: 'Tip admonition' },
  { label: ':::caution', type: 'snippet', apply: ':::caution\n${text}\n:::', info: 'Caution admonition' },
  { label: ':::danger', type: 'snippet', apply: ':::danger\n${text}\n:::', info: 'Danger admonition' },
  { label: ':::info', type: 'snippet', apply: ':::info\n${text}\n:::', info: 'Info admonition' },
  // Footnotes
  { label: 'footnote-ref', type: 'snippet', apply: '[^${id}]', info: 'Footnote ref' },
  { label: 'footnote-def', type: 'snippet', apply: '[^${id}]: ${text}', info: 'Footnote def' },
  // Math
  { label: 'math-inline', type: 'snippet', apply: '$${expr}$', info: 'Inline math' },
  { label: 'math-block', type: 'snippet', apply: '$$\n${expr}\n$$', info: 'Display math' },
  { label: 'frac', type: 'snippet', apply: '\\frac{${a}}{${b}}', info: 'Fraction' },
  { label: 'sqrt', type: 'snippet', apply: '\\sqrt{${x}}', info: 'Square root' },
  { label: 'sum', type: 'snippet', apply: '\\sum_{${i}=${a}}^{${b}} ${e}', info: 'Sum' },
  { label: 'prod', type: 'snippet', apply: '\\prod_{${i}=${a}}^{${b}} ${e}', info: 'Product' },
  { label: 'int', type: 'snippet', apply: '\\int_{${a}}^{${b}} ${e}', info: 'Integral' },
  { label: 'lim', type: 'snippet', apply: '\\lim_{${x} \\to ${a}} ${f}', info: 'Limit' },
  { label: 'alpha', type: 'snippet', apply: '\\alpha', info: 'Greek alpha' },
  { label: 'beta', type: 'snippet', apply: '\\beta', info: 'Greek beta' },
  { label: 'gamma', type: 'snippet', apply: '\\gamma', info: 'Greek gamma' },
  { label: 'delta', type: 'snippet', apply: '\\delta', info: 'Greek delta' },
  { label: 'epsilon', type: 'snippet', apply: '\\epsilon', info: 'Greek epsilon' },
  { label: 'theta', type: 'snippet', apply: '\\theta', info: 'Greek theta' },
  { label: 'lambda', type: 'snippet', apply: '\\lambda', info: 'Greek lambda' },
  { label: 'mu', type: 'snippet', apply: '\\mu', info: 'Greek mu' },
  { label: 'pi', type: 'snippet', apply: '\\pi', info: 'Greek pi' },
  { label: 'sigma', type: 'snippet', apply: '\\sigma', info: 'Greek sigma' },
  { label: 'phi', type: 'snippet', apply: '\\phi', info: 'Greek phi' },
  { label: 'omega', type: 'snippet', apply: '\\omega', info: 'Greek omega' },
  { label: 'infty', type: 'snippet', apply: '\\infty', info: 'Infinity' },
  { label: 'partial', type: 'snippet', apply: '\\partial', info: 'Partial' },
  { label: 'nabla', type: 'snippet', apply: '\\nabla', info: 'Nabla' },
  { label: 'forall', type: 'snippet', apply: '\\forall', info: 'For all' },
  { label: 'exists', type: 'snippet', apply: '\\exists', info: 'There exists' },
  { label: 'in', type: 'snippet', apply: '\\in', info: 'Set member' },
  { label: 'notin', type: 'snippet', apply: '\\notin', info: 'Not in set' },
  { label: 'subset', type: 'snippet', apply: '\\subset', info: 'Subset' },
  { label: 'supset', type: 'snippet', apply: '\\supset', info: 'Superset' },
  { label: 'cup', type: 'snippet', apply: '\\cup', info: 'Union' },
  { label: 'cap', type: 'snippet', apply: '\\cap', info: 'Intersect' },
  { label: 'leq', type: 'snippet', apply: '\\leq', info: 'Less eq' },
  { label: 'geq', type: 'snippet', apply: '\\geq', info: 'Greater eq' },
  { label: 'neq', type: 'snippet', apply: '\\neq', info: 'Not equal' },
  { label: 'approx', type: 'snippet', apply: '\\approx', info: 'Approx' },
  { label: 'rightarrow', type: 'snippet', apply: '\\rightarrow', info: 'Right arrow' },
  { label: 'leftarrow', type: 'snippet', apply: '\\leftarrow', info: 'Left arrow' },
  { label: 'leftrightarrow', type: 'snippet', apply: '\\leftrightarrow', info: 'Bi arrow' },
  { label: 'Rightarrow', type: 'snippet', apply: '\\Rightarrow', info: 'Implies' },
  { label: 'Leftrightarrow', type: 'snippet', apply: '\\Leftrightarrow', info: 'Iff' },
  // Mermaid
  { label: 'mermaid', type: 'snippet', apply: '```mermaid\n${code}\n```', info: 'Mermaid fence' },
  { label: 'mermaid-flow', type: 'snippet', apply: '```mermaid\nflowchart LR\n  A --> B\n```', info: 'Flowchart' },
  { label: 'mermaid-flow-td', type: 'snippet', apply: '```mermaid\nflowchart TD\n  A --> B\n```', info: 'Top-down flowchart' },
  { label: 'mermaid-sequence', type: 'snippet', apply: '```mermaid\nsequenceDiagram\n  A->>B: Hello\n  B-->>A: Hi\n```', info: 'Sequence diagram' },
  { label: 'mermaid-class', type: 'snippet', apply: '```mermaid\nclassDiagram\n  class A\n  A <|-- B\n```', info: 'Class diagram' },
  { label: 'mermaid-state', type: 'snippet', apply: '```mermaid\nstateDiagram-v2\n  [*] --> S1\n  S1 --> [*]\n```', info: 'State diagram' },
  { label: 'mermaid-er', type: 'snippet', apply: '```mermaid\nerDiagram\n  A ||--o{ B : has\n```', info: 'ER diagram' },
  { label: 'mermaid-gantt', type: 'snippet', apply: '```mermaid\ngantt\n  title Project\n  section X\n  Task :a1, 2024-01-01, 30d\n```', info: 'Gantt chart' },
  { label: 'mermaid-pie', type: 'snippet', apply: '```mermaid\npie\n  "A" : 40\n  "B" : 60\n```', info: 'Pie chart' },
  { label: 'mermaid-journey', type: 'snippet', apply: '```mermaid\njourney\n  title My journey\n  section X\n  Do: 5: Me\n```', info: 'User journey' },
  { label: 'mermaid-gitGraph', type: 'snippet', apply: '```mermaid\ngitGraph\n  commit\n  branch dev\n  checkout dev\n  commit\n```', info: 'Git graph' },
  // Common doc snippets
  { label: 'details', type: 'snippet', apply: '<details>\n<summary>${summary}</summary>\n\n${content}\n\n</details>', info: 'Collapsible block' },
  { label: 'kbd', type: 'snippet', apply: '<kbd>${key}</kbd>', info: 'Keyboard key' },
  { label: 'mark', type: 'snippet', apply: '<mark>${text}</mark>', info: 'Highlighted text' },
  { label: 'sup', type: 'snippet', apply: '<sup>${text}</sup>', info: 'Superscript' },
  { label: 'sub', type: 'snippet', apply: '<sub>${text}</sub>', info: 'Subscript' },
  { label: 'abbr', type: 'snippet', apply: '<abbr title="${title}">${text}</abbr>', info: 'Abbreviation' },
  { label: 'br', type: 'snippet', apply: '<br>', info: 'Line break' },
  { label: 'img-resize', type: 'snippet', apply: '<img src="${url}" width="${w}" alt="${alt}" />', info: 'Sized image' },
  { label: 'center', type: 'snippet', apply: '<p align="center">${text}</p>', info: 'Centered text' },
  { label: 'figure', type: 'snippet', apply: '<figure>\n<img src="${url}" alt="${alt}" />\n<figcaption>${caption}</figcaption>\n</figure>', info: 'Figure w/ caption' },
  // GitHub badges
  { label: 'badge-shields', type: 'snippet', apply: '![${alt}](https://img.shields.io/badge/${label}-${msg}-${color})', info: 'Shields.io badge' },
  { label: 'badge-npm', type: 'snippet', apply: '[![npm](https://img.shields.io/npm/v/${pkg}.svg)](https://www.npmjs.com/package/${pkg})', info: 'npm badge' },
  { label: 'badge-build', type: 'snippet', apply: '![Build](https://github.com/${owner}/${repo}/actions/workflows/${wf}.yml/badge.svg)', info: 'GH Actions badge' },
  { label: 'badge-license', type: 'snippet', apply: '[![License](https://img.shields.io/badge/license-${lic}-blue.svg)](LICENSE)', info: 'License badge' },
  { label: 'badge-coverage', type: 'snippet', apply: '[![Coverage](https://codecov.io/gh/${owner}/${repo}/branch/main/graph/badge.svg)](https://codecov.io/gh/${owner}/${repo})', info: 'Codecov badge' },
  // Commit message conventions
  { label: 'feat:', type: 'snippet', apply: 'feat(${scope}): ${msg}', info: 'Conventional feat' },
  { label: 'fix:', type: 'snippet', apply: 'fix(${scope}): ${msg}', info: 'Conventional fix' },
  { label: 'docs:', type: 'snippet', apply: 'docs(${scope}): ${msg}', info: 'Conventional docs' },
  { label: 'style:', type: 'snippet', apply: 'style(${scope}): ${msg}', info: 'Conventional style' },
  { label: 'refactor:', type: 'snippet', apply: 'refactor(${scope}): ${msg}', info: 'Conventional refactor' },
  { label: 'perf:', type: 'snippet', apply: 'perf(${scope}): ${msg}', info: 'Conventional perf' },
  { label: 'test:', type: 'snippet', apply: 'test(${scope}): ${msg}', info: 'Conventional test' },
  { label: 'build:', type: 'snippet', apply: 'build(${scope}): ${msg}', info: 'Conventional build' },
  { label: 'ci:', type: 'snippet', apply: 'ci(${scope}): ${msg}', info: 'Conventional ci' },
  { label: 'chore:', type: 'snippet', apply: 'chore(${scope}): ${msg}', info: 'Conventional chore' },
  // Common doc structures
  { label: 'readme', type: 'snippet', apply: '# ${project}\n\n${description}\n\n## Installation\n\n```bash\n${install}\n```\n\n## Usage\n\n```${lang}\n${usage}\n```\n\n## License\n\n${license}', info: 'Mini README' },
  { label: 'changelog', type: 'snippet', apply: '## [${version}] - ${date}\n\n### Added\n- ${feature}\n\n### Changed\n- ${change}\n\n### Fixed\n- ${fix}\n', info: 'Changelog entry' },
  { label: 'api-header', type: 'snippet', apply: '### `${name}(${params})`\n\n> ${description}\n\n**Returns:** `${type}`\n', info: 'API fn header' },
  // KaTeX symbols more
  { label: 'mathbb', type: 'snippet', apply: '\\mathbb{${N}}', info: 'Blackboard bold' },
  { label: 'mathcal', type: 'snippet', apply: '\\mathcal{${A}}', info: 'Calligraphic' },
  { label: 'mathfrak', type: 'snippet', apply: '\\mathfrak{${g}}', info: 'Fraktur' },
  { label: 'boxed', type: 'snippet', apply: '\\boxed{${e}}', info: 'Boxed formula' },
  { label: 'begin-align', type: 'snippet', apply: '\\begin{align*}\n${eqs}\n\\end{align*}', info: 'Align env' },
  { label: 'begin-cases', type: 'snippet', apply: '\\begin{cases}\n${a} & \\text{if ${c}}\\\\\n${b} & \\text{otherwise}\n\\end{cases}', info: 'Cases env' },
  { label: 'matrix-pmatrix', type: 'snippet', apply: '\\begin{pmatrix}\n${a} & ${b}\\\\\n${c} & ${d}\n\\end{pmatrix}', info: 'Matrix' },
  { label: 'vec', type: 'snippet', apply: '\\vec{${v}}', info: 'Vector' },
  { label: 'hat', type: 'snippet', apply: '\\hat{${v}}', info: 'Hat' },
  { label: 'bar', type: 'snippet', apply: '\\bar{${v}}', info: 'Bar' },
  { label: 'tilde', type: 'snippet', apply: '\\tilde{${v}}', info: 'Tilde' },
  { label: 'dot', type: 'snippet', apply: '\\dot{${v}}', info: 'Dot' },
  { label: 'ddot', type: 'snippet', apply: '\\ddot{${v}}', info: 'DoubleDot' },
  // Pandoc style
  { label: 'pandoc-title', type: 'snippet', apply: '% ${title}\n% ${author}\n% ${date}\n', info: 'Pandoc title' },
  // Common labels
  { label: 'emoji', type: 'snippet', apply: ':${name}:', info: 'Shortcode emoji' },
  // Markdown links for images/figures
  { label: 'link-ref', type: 'snippet', apply: '[![${alt}][img]][link]\n\n[img]: ${imgUrl}\n[link]: ${linkUrl}', info: 'Image ref link' },
  { label: 'anchor', type: 'snippet', apply: '<a id="${id}"></a>', info: 'HTML anchor' },
  { label: 'toc', type: 'snippet', apply: '## Table of Contents\n\n- [${section}](#${anchor})', info: 'TOC stub' },
  // More Mermaid
  { label: 'mermaid-c4', type: 'snippet', apply: '```mermaid\nC4Context\n  title ${title}\n  Person(user, "User")\n  System(sys, "System")\n  Rel(user, sys, "uses")\n```', info: 'C4 diagram' },
  { label: 'mermaid-mindmap', type: 'snippet', apply: '```mermaid\nmindmap\n  root((root))\n    child1\n    child2\n```', info: 'Mindmap' },
  { label: 'mermaid-timeline', type: 'snippet', apply: '```mermaid\ntimeline\n  title ${title}\n  2020 : event\n  2021 : event\n```', info: 'Timeline' },
  // Heading anchors (GitHub style)
  { label: 'heading-anchor', type: 'snippet', apply: '## ${title} {#${id}}', info: 'Heading w/ anchor' },
  // Common markdown structures
  { label: 'screenshot', type: 'snippet', apply: '![${alt}](./docs/images/${name}.png)', info: 'Docs image' },
  { label: 'quote-source', type: 'snippet', apply: '> ${text}\n> \n> — ${source}', info: 'Attributed quote' },
  // Extra MDX components
  { label: 'mdx-layout', type: 'snippet', apply: 'export { default as Layout } from \'${path}\';', info: 'MDX layout' },
  // HTML in markdown
  { label: 'html-block', type: 'snippet', apply: '<div class="${cls}">\n${content}\n</div>', info: 'HTML block' },
  { label: 'comment', type: 'snippet', apply: '<!-- ${comment} -->', info: 'HTML comment' },
  // GitHub emojis common
  { label: ':heart:', type: 'emoji', info: 'Heart emoji' },
  { label: ':rocket:', type: 'emoji', info: 'Rocket emoji' },
  { label: ':fire:', type: 'emoji', info: 'Fire emoji' },
  { label: ':tada:', type: 'emoji', info: 'Tada emoji' },
  { label: ':+1:', type: 'emoji', info: 'Thumbs up' },
  { label: ':-1:', type: 'emoji', info: 'Thumbs down' },
  { label: ':white_check_mark:', type: 'emoji', info: 'Check emoji' },
  { label: ':x:', type: 'emoji', info: 'Cross emoji' },
  { label: ':warning:', type: 'emoji', info: 'Warning emoji' },
  { label: ':bug:', type: 'emoji', info: 'Bug emoji' },
  { label: ':book:', type: 'emoji', info: 'Book emoji' },
  { label: ':bulb:', type: 'emoji', info: 'Idea bulb' },
  { label: ':sparkles:', type: 'emoji', info: 'Sparkles' },
  { label: ':zap:', type: 'emoji', info: 'Zap' },
  { label: ':wrench:', type: 'emoji', info: 'Wrench' },
  { label: ':package:', type: 'emoji', info: 'Package' },
  { label: ':construction:', type: 'emoji', info: 'Construction' },
  { label: ':lock:', type: 'emoji', info: 'Lock' },
  { label: ':unlock:', type: 'emoji', info: 'Unlock' },
  { label: ':shield:', type: 'emoji', info: 'Shield' },
  { label: ':chart_with_upwards_trend:', type: 'emoji', info: 'Chart up' },
  { label: ':hourglass:', type: 'emoji', info: 'Hourglass' },
  { label: ':art:', type: 'emoji', info: 'Art palette' },
  { label: ':recycle:', type: 'emoji', info: 'Recycle' },
  { label: ':hammer:', type: 'emoji', info: 'Hammer' },
  { label: ':pencil:', type: 'emoji', info: 'Pencil' },
  // More fences
  { label: 'graphql', type: 'snippet', apply: '```graphql\n${code}\n```', info: 'GraphQL fence' },
  { label: 'protobuf', type: 'snippet', apply: '```protobuf\n${code}\n```', info: 'Protobuf fence' },
  { label: 'tsx', type: 'snippet', apply: '```tsx\n${code}\n```', info: 'TSX fence' },
  { label: 'jsx', type: 'snippet', apply: '```jsx\n${code}\n```', info: 'JSX fence' },
  { label: 'vue', type: 'snippet', apply: '```vue\n${code}\n```', info: 'Vue fence' },
  { label: 'svelte', type: 'snippet', apply: '```svelte\n${code}\n```', info: 'Svelte fence' },
  { label: 'astro', type: 'snippet', apply: '```astro\n${code}\n```', info: 'Astro fence' },
  { label: 'jupyter', type: 'snippet', apply: '```jupyter\n${code}\n```', info: 'Jupyter fence' },
  { label: 'julia', type: 'snippet', apply: '```julia\n${code}\n```', info: 'Julia fence' },
  { label: 'f#', type: 'snippet', apply: '```fsharp\n${code}\n```', info: 'F# fence' },
  { label: 'erlang', type: 'snippet', apply: '```erlang\n${code}\n```', info: 'Erlang fence' },
  { label: 'groovy', type: 'snippet', apply: '```groovy\n${code}\n```', info: 'Groovy fence' },
  { label: 'scheme', type: 'snippet', apply: '```scheme\n${code}\n```', info: 'Scheme fence' },
  { label: 'racket', type: 'snippet', apply: '```racket\n```', info: 'Racket fence' },
  { label: 'perl-code', type: 'snippet', apply: '```perl\n${code}\n```', info: 'Perl fence' },
  { label: 'asm', type: 'snippet', apply: '```asm\n${code}\n```', info: 'Assembly fence' },
  { label: 'verilog', type: 'snippet', apply: '```verilog\n${code}\n```', info: 'Verilog fence' },
  { label: 'vhdl', type: 'snippet', apply: '```vhdl\n${code}\n```', info: 'VHDL fence' },
  { label: 'tcl', type: 'snippet', apply: '```tcl\n${code}\n```', info: 'Tcl fence' },
  { label: 'latex', type: 'snippet', apply: '```latex\n${code}\n```', info: 'LaTeX fence' },
  { label: 'bibtex', type: 'snippet', apply: '```bibtex\n${code}\n```', info: 'BibTeX fence' },
  { label: 'solidity', type: 'snippet', apply: '```solidity\n${code}\n```', info: 'Solidity fence' },
  { label: 'matlab', type: 'snippet', apply: '```matlab\n${code}\n```', info: 'MATLAB fence' },
  { label: 'octave', type: 'snippet', apply: '```octave\n${code}\n```', info: 'Octave fence' },
  { label: 'fortran', type: 'snippet', apply: '```fortran\n${code}\n```', info: 'Fortran fence' },
  { label: 'pascal', type: 'snippet', apply: '```pascal\n${code}\n```', info: 'Pascal fence' },
  { label: 'coffeescript', type: 'snippet', apply: '```coffeescript\n${code}\n```', info: 'CoffeeScript fence' },
  { label: 'livescript', type: 'snippet', apply: '```livescript\n${code}\n```', info: 'LiveScript fence' },
  { label: 'elm', type: 'snippet', apply: '```elm\n${code}\n```', info: 'Elm fence' },
  { label: 'purescript', type: 'snippet', apply: '```purescript\n${code}\n```', info: 'PureScript fence' },
  // Markdown settings blocks
  { label: 'admonition', type: 'snippet', apply: ':::{.${class}}\n${text}\n:::', info: 'Pandoc admonition' },
  { label: 'fenced-div', type: 'snippet', apply: '::: {.${class}}\n${content}\n:::', info: 'Pandoc fenced div' },
  // LaTeX extras
  { label: 'itemize', type: 'snippet', apply: '\\begin{itemize}\n  \\item ${a}\n  \\item ${b}\n\\end{itemize}', info: 'LaTeX bullets' },
  { label: 'enumerate', type: 'snippet', apply: '\\begin{enumerate}\n  \\item ${a}\n  \\item ${b}\n\\end{enumerate}', info: 'LaTeX enumerate' },
  // GFM inline
  { label: 'gfm-autolink', type: 'snippet', apply: 'https://${url}', info: 'GFM autolink' },
  // Common sections
  { label: 'overview', type: 'snippet', apply: '## Overview\n\n${text}', info: 'Overview section' },
  { label: 'features', type: 'snippet', apply: '## Features\n\n- ${a}\n- ${b}\n- ${c}', info: 'Features section' },
  { label: 'install', type: 'snippet', apply: '## Installation\n\n```bash\n${cmd}\n```', info: 'Install section' },
  { label: 'usage', type: 'snippet', apply: '## Usage\n\n```${lang}\n${code}\n```', info: 'Usage section' },
  { label: 'license-section', type: 'snippet', apply: '## License\n\nDistributed under the ${lic} License.', info: 'License section' },
  { label: 'contributing', type: 'snippet', apply: '## Contributing\n\nPRs welcome. See [CONTRIBUTING](CONTRIBUTING.md).', info: 'Contributing section' },
  { label: 'faq', type: 'snippet', apply: '## FAQ\n\n### ${question}\n\n${answer}', info: 'FAQ section' },
  { label: 'roadmap', type: 'snippet', apply: '## Roadmap\n\n- [ ] ${item}', info: 'Roadmap section' },
  { label: 'acknowledgements', type: 'snippet', apply: '## Acknowledgements\n\n- [${name}](${url})', info: 'Credits' },
  // API doc snippets
  { label: 'method-doc', type: 'snippet', apply: '### `${object}.${method}(${params})`\n\n${desc}\n\n**Parameters:**\n\n- `${p1}` — ${p1desc}\n\n**Returns:** `${ret}`', info: 'Method doc' },
  // Bibliography / citations
  { label: 'citation', type: 'snippet', apply: '[@${key}]', info: 'Pandoc citation' },
  // Docs theme boilerplate
  { label: 'callout', type: 'snippet', apply: '> **${label}**\n>\n> ${text}', info: 'Generic callout' },
  // Additional fences (mobile/desktop)
  { label: 'kotlin-code', type: 'snippet', apply: '```kotlin\n${code}\n```', info: 'Kotlin fence' },
  { label: 'swift-code', type: 'snippet', apply: '```swift\n${code}\n```', info: 'Swift fence' },
  { label: 'rb-code', type: 'snippet', apply: '```ruby\n${code}\n```', info: 'Ruby fence' },
  { label: 'java-code', type: 'snippet', apply: '```java\n${code}\n```', info: 'Java fence' },
  // Styled blockquotes
  { label: 'quote-callout', type: 'snippet', apply: '> [!NOTE]\n> ${text}', info: 'GFM note callout' },
  // Code groups (Docusaurus)
  { label: 'code-group', type: 'snippet', apply: '<Tabs>\n  <TabItem value="js" label="JS">\n\n```js\n${code}\n```\n\n  </TabItem>\n</Tabs>', info: 'Docusaurus tabs' },
  // Admonition variants (older)
  { label: 'admo-warning', type: 'snippet', apply: '!!! warning\n    ${text}', info: 'MkDocs warning' },
  { label: 'admo-note', type: 'snippet', apply: '!!! note\n    ${text}', info: 'MkDocs note' },
  { label: 'admo-tip', type: 'snippet', apply: '!!! tip\n    ${text}', info: 'MkDocs tip' },
  { label: 'admo-danger', type: 'snippet', apply: '!!! danger\n    ${text}', info: 'MkDocs danger' },
  { label: 'admo-info', type: 'snippet', apply: '!!! info\n    ${text}', info: 'MkDocs info' },
  // Jekyll / Hugo shortcodes
  { label: 'hugo-figure', type: 'snippet', apply: '{{< figure src="${src}" caption="${cap}" >}}', info: 'Hugo figure' },
  { label: 'hugo-youtube', type: 'snippet', apply: '{{< youtube ${id} >}}', info: 'Hugo youtube' },
  { label: 'jekyll-include', type: 'snippet', apply: '{% include ${file} %}', info: 'Jekyll include' },
  { label: 'jekyll-highlight', type: 'snippet', apply: '{% highlight ${lang} %}\n${code}\n{% endhighlight %}', info: 'Jekyll highlight' },
  // Numbered ordered lists variants
  { label: 'list-all-1', type: 'snippet', apply: '1. ${a}\n1. ${b}\n1. ${c}', info: 'Auto-numbered' },
  // Github-flavored PR task list template
  { label: 'pr-checklist', type: 'snippet', apply: '## Checklist\n\n- [ ] Tests pass\n- [ ] Docs updated\n- [ ] Changelog updated', info: 'PR checklist' },
  { label: 'issue-template', type: 'snippet', apply: '## Description\n\n${desc}\n\n## Steps to reproduce\n\n1. ${step}\n\n## Expected\n\n${expected}\n\n## Actual\n\n${actual}', info: 'Issue body' },
  // Common section separators
  { label: 'hr-underscore', type: 'snippet', apply: '___', info: 'HR underscore' },
  { label: 'hr-asterisk', type: 'snippet', apply: '***', info: 'HR asterisk' },
  // Directive attributes
  { label: ':::details', type: 'snippet', apply: ':::details ${summary}\n${text}\n:::', info: 'Details directive' },
  // Attribute block (mdx / pandoc-attr)
  { label: 'attr-block', type: 'snippet', apply: '{.${class} #${id}}', info: 'Attribute block' },
  // Common HTML-in-md
  { label: 'iframe', type: 'snippet', apply: '<iframe src="${url}" width="${w}" height="${h}" frameborder="0"></iframe>', info: 'Iframe embed' },
  { label: 'video', type: 'snippet', apply: '<video controls src="${url}" width="${w}"></video>', info: 'Video tag' },
  { label: 'audio', type: 'snippet', apply: '<audio controls src="${url}"></audio>', info: 'Audio tag' },
  // Github Mermaid theme
  { label: 'mermaid-theme', type: 'snippet', apply: '%%{init: { "theme": "default" } }%%', info: 'Mermaid theme' },
  // Admonition (RST-like)
  { label: '.. note::', type: 'snippet', apply: '.. note::\n   ${text}', info: 'RST note' },
  { label: '.. warning::', type: 'snippet', apply: '.. warning::\n   ${text}', info: 'RST warning' },
  // Markdown lint disables
  { label: 'markdownlint-disable', type: 'snippet', apply: '<!-- markdownlint-disable -->', info: 'Disable mdlint' },
  { label: 'markdownlint-enable', type: 'snippet', apply: '<!-- markdownlint-enable -->', info: 'Enable mdlint' },
  // License banners
  { label: 'license-mit-banner', type: 'snippet', apply: '> Released under the MIT License.', info: 'MIT banner' },
  { label: 'license-apache-banner', type: 'snippet', apply: '> Licensed under the Apache License 2.0.', info: 'Apache banner' },
  // Docs intro boilerplate
  { label: 'getting-started', type: 'snippet', apply: '## Getting started\n\n1. Install: `${install}`\n2. Configure: `${config}`\n3. Run: `${run}`', info: 'Quickstart' },
  // Extra mermaid
  { label: 'mermaid-req', type: 'snippet', apply: '```mermaid\nrequirementDiagram\n  requirement ${name} {\n    id: 1\n    text: ${text}\n  }\n```', info: 'Requirements diagram' },
  // Front-matter TOML alt
  { label: 'jekyll-fm', type: 'snippet', apply: '---\nlayout: ${layout}\ntitle: ${title}\npermalink: ${perma}\n---', info: 'Jekyll frontmatter' },
  // Extra emoji
  { label: ':eyes:', type: 'emoji', info: 'Eyes emoji' },
  { label: ':clap:', type: 'emoji', info: 'Clap emoji' },
  { label: ':pray:', type: 'emoji', info: 'Pray emoji' },
  { label: ':star:', type: 'emoji', info: 'Star emoji' },
  { label: ':boom:', type: 'emoji', info: 'Boom emoji' },
  { label: ':100:', type: 'emoji', info: '100 emoji' },
  { label: ':question:', type: 'emoji', info: 'Question emoji' },
  { label: ':exclamation:', type: 'emoji', info: 'Exclamation' },
  { label: ':hammer_and_wrench:', type: 'emoji', info: 'Tools' },
  { label: ':arrow_up:', type: 'emoji', info: 'Up arrow' },
  { label: ':arrow_down:', type: 'emoji', info: 'Down arrow' },
  { label: ':arrow_right:', type: 'emoji', info: 'Right arrow' },
  { label: ':arrow_left:', type: 'emoji', info: 'Left arrow' },
  { label: ':loudspeaker:', type: 'emoji', info: 'Loudspeaker' },
  { label: ':mega:', type: 'emoji', info: 'Megaphone' },
  { label: ':bell:', type: 'emoji', info: 'Bell' },
  { label: ':no_bell:', type: 'emoji', info: 'No bell' },
  { label: ':mag:', type: 'emoji', info: 'Magnifying glass' },
  { label: ':key:', type: 'emoji', info: 'Key' },
  { label: ':tickets:', type: 'emoji', info: 'Tickets' },
  { label: ':memo:', type: 'emoji', info: 'Memo' },
  { label: ':clipboard:', type: 'emoji', info: 'Clipboard' },
  { label: ':scroll:', type: 'emoji', info: 'Scroll' },
  { label: ':gift:', type: 'emoji', info: 'Gift' },
  { label: ':mortar_board:', type: 'emoji', info: 'Graduation' },
  // Additional structures
  { label: 'code-block-lang-name', type: 'snippet', apply: '```${lang} title="${title}"\n${code}\n```', info: 'Titled code' },
  { label: 'code-block-highlight', type: 'snippet', apply: '```${lang} {${lines}}\n${code}\n```', info: 'Highlighted lines' },
  { label: 'table-row', type: 'snippet', apply: '| ${a} | ${b} |', info: 'Table row' },
  // Additional Mermaid
  { label: 'mermaid-subgraph', type: 'snippet', apply: 'subgraph ${name}\n  ${content}\nend', info: 'Subgraph' },
  { label: 'mermaid-class-method', type: 'snippet', apply: '${Class} : +${method}()', info: 'Class method' },
  { label: 'mermaid-seq-activate', type: 'snippet', apply: 'activate ${target}', info: 'Seq activate' },
  { label: 'mermaid-seq-deactivate', type: 'snippet', apply: 'deactivate ${target}', info: 'Seq deactivate' },
  { label: 'mermaid-seq-note', type: 'snippet', apply: 'Note over ${target}: ${text}', info: 'Sequence note' },
  // Additional LaTeX
  { label: 'text-math', type: 'snippet', apply: '\\text{${text}}', info: 'Text in math' },
  { label: 'overset', type: 'snippet', apply: '\\overset{${a}}{${b}}', info: 'Overset' },
  { label: 'underset', type: 'snippet', apply: '\\underset{${a}}{${b}}', info: 'Underset' },
  { label: 'binom', type: 'snippet', apply: '\\binom{${n}}{${k}}', info: 'Binomial' },
  // Math sets
  { label: 'mathbb-R', type: 'snippet', apply: '\\mathbb{R}', info: 'Reals' },
  { label: 'mathbb-N', type: 'snippet', apply: '\\mathbb{N}', info: 'Naturals' },
  { label: 'mathbb-Z', type: 'snippet', apply: '\\mathbb{Z}', info: 'Integers' },
  { label: 'mathbb-Q', type: 'snippet', apply: '\\mathbb{Q}', info: 'Rationals' },
  { label: 'mathbb-C', type: 'snippet', apply: '\\mathbb{C}', info: 'Complex' },
];
