// Completion entries for nim.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  { label: 'proc', type: 'keyword', info: 'Procedure' },
  { label: 'func', type: 'keyword', info: 'Function (pure)' },
  { label: 'method', type: 'keyword', info: 'Method (dynamic)' },
  { label: 'iterator', type: 'keyword', info: 'Iterator' },
  { label: 'converter', type: 'keyword', info: 'Type converter' },
  { label: 'template', type: 'keyword', info: 'Template' },
  { label: 'macro', type: 'keyword', info: 'Macro' },
  { label: 'let', type: 'keyword', info: 'Immutable binding' },
  { label: 'var', type: 'keyword', info: 'Mutable binding' },
  { label: 'const', type: 'keyword', info: 'Constant' },
  { label: 'type', type: 'keyword', info: 'Type decl' },
  { label: 'object', type: 'keyword', info: 'Object type' },
  { label: 'tuple', type: 'keyword', info: 'Tuple type' },
  { label: 'ref', type: 'keyword', info: 'Reference type' },
  { label: 'ptr', type: 'keyword', info: 'Unsafe pointer' },
  { label: 'enum', type: 'keyword', info: 'Enum type' },
  { label: 'distinct', type: 'keyword', info: 'Distinct type' },
  { label: 'if', type: 'keyword', info: 'If statement' },
  { label: 'elif', type: 'keyword', info: 'Else if' },
  { label: 'else', type: 'keyword', info: 'Else branch' },
  { label: 'case', type: 'keyword', info: 'Case of' },
  { label: 'of', type: 'keyword', info: 'Case pattern' },
  { label: 'when', type: 'keyword', info: 'Compile-time if' },
  { label: 'while', type: 'keyword', info: 'While loop' },
  { label: 'for', type: 'keyword', info: 'For loop' },
  { label: 'in', type: 'keyword', info: 'In iterable' },
  { label: 'notin', type: 'keyword', info: 'Not in' },
  { label: 'break', type: 'keyword', info: 'Break loop' },
  { label: 'continue', type: 'keyword', info: 'Continue loop' },
  { label: 'return', type: 'keyword', info: 'Return value' },
  { label: 'yield', type: 'keyword', info: 'Yield from iter' },
  { label: 'raise', type: 'keyword', info: 'Raise exception' },
  { label: 'try', type: 'keyword', info: 'Try block' },
  { label: 'except', type: 'keyword', info: 'Except clause' },
  { label: 'finally', type: 'keyword', info: 'Finally block' },
  { label: 'defer', type: 'keyword', info: 'Defer cleanup' },
  { label: 'import', type: 'keyword', info: 'Import module' },
  { label: 'export', type: 'keyword', info: 'Export symbol' },
  { label: 'include', type: 'keyword', info: 'Include file' },
  { label: 'from', type: 'keyword', info: 'From module' },
  { label: 'discard', type: 'keyword', info: 'Discard result' },
  { label: 'nil', type: 'keyword', info: 'Nil' },
  { label: 'true', type: 'keyword', info: 'True' },
  { label: 'false', type: 'keyword', info: 'False' },
  { label: 'not', type: 'keyword', info: 'Logical NOT' },
  { label: 'and', type: 'keyword', info: 'Logical AND' },
  { label: 'or', type: 'keyword', info: 'Logical OR' },
  { label: 'xor', type: 'keyword', info: 'Logical XOR' },
  { label: 'is', type: 'keyword', info: 'Type test' },
  { label: 'isnot', type: 'keyword', info: 'Type negation' },
  { label: 'as', type: 'keyword', info: 'Type cast' },
  { label: 'cast', type: 'keyword', info: 'Bitcast' },
  { label: 'shr', type: 'keyword', info: 'Shift right' },
  { label: 'shl', type: 'keyword', info: 'Shift left' },
  { label: 'div', type: 'keyword', info: 'Integer div' },
  { label: 'mod', type: 'keyword', info: 'Modulo' },
  { label: 'block', type: 'keyword', info: 'Block' },
  { label: 'static', type: 'keyword', info: 'Static compile' },
  { label: 'ptr', type: 'keyword', info: 'Pointer' },
  // Types
  { label: 'int', type: 'type', info: 'Integer' },
  { label: 'int8', type: 'type', info: '8-bit int' },
  { label: 'int16', type: 'type', info: '16-bit int' },
  { label: 'int32', type: 'type', info: '32-bit int' },
  { label: 'int64', type: 'type', info: '64-bit int' },
  { label: 'uint', type: 'type', info: 'Unsigned int' },
  { label: 'uint8', type: 'type', info: '8-bit uint' },
  { label: 'uint32', type: 'type', info: '32-bit uint' },
  { label: 'uint64', type: 'type', info: '64-bit uint' },
  { label: 'float', type: 'type', info: 'Float' },
  { label: 'float32', type: 'type', info: '32-bit float' },
  { label: 'float64', type: 'type', info: '64-bit float' },
  { label: 'bool', type: 'type', info: 'Boolean' },
  { label: 'char', type: 'type', info: 'Character' },
  { label: 'string', type: 'type', info: 'String' },
  { label: 'cstring', type: 'type', info: 'C string' },
  { label: 'seq', type: 'type', info: 'Sequence' },
  { label: 'array', type: 'type', info: 'Fixed array' },
  { label: 'openArray', type: 'type', info: 'Open array' },
  { label: 'set', type: 'type', info: 'Set (bit set)' },
  { label: 'Option', type: 'type', info: 'Option type' },
  { label: 'Table', type: 'type', info: 'Hash table' },
  { label: 'CountTable', type: 'type', info: 'Count table' },
  // Procs
  { label: 'echo', type: 'function', info: 'Print line' },
  { label: 'write', type: 'function', info: 'Write output' },
  { label: 'readLine', type: 'function', info: 'Read line' },
  { label: 'readFile', type: 'function', info: 'Read file' },
  { label: 'writeFile', type: 'function', info: 'Write file' },
  { label: 'len', type: 'function', info: 'Length' },
  { label: 'high', type: 'function', info: 'Upper bound' },
  { label: 'low', type: 'function', info: 'Lower bound' },
  { label: 'add', type: 'function', info: 'Append' },
  { label: 'delete', type: 'function', info: 'Delete element' },
  { label: 'contains', type: 'function', info: 'Contains check' },
  { label: 'find', type: 'function', info: 'Find index' },
  { label: 'setLen', type: 'function', info: 'Set length' },
  { label: 'newSeq', type: 'function', info: 'New sequence' },
  { label: 'newSeqOfCap', type: 'function', info: 'Seq w/ capacity' },
  { label: '@', type: 'function', info: 'Sequence literal' },
  { label: 'toSeq', type: 'function', info: 'To sequence' },
  { label: 'parseInt', type: 'function', info: 'Parse int' },
  { label: 'parseFloat', type: 'function', info: 'Parse float' },
  { label: '$', type: 'function', info: 'To string' },
  { label: 'repr', type: 'function', info: 'Value repr' },
  { label: 'quit', type: 'function', info: 'Exit program' },
  { label: 'assert', type: 'function', info: 'Assertion' },
  { label: 'doAssert', type: 'function', info: 'Always assert' },
  // Modules
  { label: 'strutils', type: 'module', info: 'String utilities' },
  { label: 'sequtils', type: 'module', info: 'Sequence utilities' },
  { label: 'tables', type: 'module', info: 'Hash tables' },
  { label: 'sets', type: 'module', info: 'Hash sets' },
  { label: 'strformat', type: 'module', info: 'String formatting' },
  { label: 'json', type: 'module', info: 'JSON' },
  { label: 'os', type: 'module', info: 'OS utilities' },
  { label: 'times', type: 'module', info: 'Time utilities' },
  { label: 'math', type: 'module', info: 'Math functions' },
  { label: 'options', type: 'module', info: 'Option type' },
  { label: 'strtabs', type: 'module', info: 'String tables' },
  { label: 'httpclient', type: 'module', info: 'HTTP client' },
  { label: 'asyncdispatch', type: 'module', info: 'Async dispatch' },
];
