// Completion entries for ocaml.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  { label: 'let', type: 'keyword', info: 'Let binding' },
  { label: 'let rec', type: 'keyword', info: 'Recursive let' },
  { label: 'and', type: 'keyword', info: 'Simultaneous def' },
  { label: 'in', type: 'keyword', info: 'Let in' },
  { label: 'fun', type: 'keyword', info: 'Lambda' },
  { label: 'function', type: 'keyword', info: 'Pattern lambda' },
  { label: 'match', type: 'keyword', info: 'Match expression' },
  { label: 'with', type: 'keyword', info: 'Match with' },
  { label: 'when', type: 'keyword', info: 'Guard' },
  { label: 'if', type: 'keyword', info: 'If expression' },
  { label: 'then', type: 'keyword', info: 'Then' },
  { label: 'else', type: 'keyword', info: 'Else' },
  { label: 'begin', type: 'keyword', info: 'Begin block' },
  { label: 'end', type: 'keyword', info: 'End block' },
  { label: 'module', type: 'keyword', info: 'Module decl' },
  { label: 'struct', type: 'keyword', info: 'Module struct' },
  { label: 'sig', type: 'keyword', info: 'Module signature' },
  { label: 'functor', type: 'keyword', info: 'Functor decl' },
  { label: 'include', type: 'keyword', info: 'Include module' },
  { label: 'open', type: 'keyword', info: 'Open module' },
  { label: 'type', type: 'keyword', info: 'Type def' },
  { label: 'of', type: 'keyword', info: 'Constructor of' },
  { label: 'mutable', type: 'keyword', info: 'Mutable field' },
  { label: 'exception', type: 'keyword', info: 'Exception decl' },
  { label: 'raise', type: 'keyword', info: 'Raise exception' },
  { label: 'try', type: 'keyword', info: 'Try block' },
  { label: 'assert', type: 'keyword', info: 'Assertion' },
  { label: 'class', type: 'keyword', info: 'OO class' },
  { label: 'object', type: 'keyword', info: 'Object' },
  { label: 'method', type: 'keyword', info: 'Method' },
  { label: 'inherit', type: 'keyword', info: 'Inherit class' },
  { label: 'virtual', type: 'keyword', info: 'Virtual method' },
  { label: 'private', type: 'keyword', info: 'Private visibility' },
  { label: 'val', type: 'keyword', info: 'Value member' },
  { label: 'new', type: 'keyword', info: 'New instance' },
  { label: 'do', type: 'keyword', info: 'Do block' },
  { label: 'done', type: 'keyword', info: 'End for/while' },
  { label: 'for', type: 'keyword', info: 'For loop' },
  { label: 'to', type: 'keyword', info: 'For to' },
  { label: 'downto', type: 'keyword', info: 'For downto' },
  { label: 'while', type: 'keyword', info: 'While loop' },
  { label: 'true', type: 'constant', info: 'True' },
  { label: 'false', type: 'constant', info: 'False' },
  { label: 'lazy', type: 'keyword', info: 'Lazy value' },
  { label: 'as', type: 'keyword', info: 'Pattern alias' },
  { label: 'ref', type: 'keyword', info: 'Mutable ref' },
  // Types
  { label: 'int', type: 'type', info: 'Integer' },
  { label: 'float', type: 'type', info: 'Float' },
  { label: 'bool', type: 'type', info: 'Boolean' },
  { label: 'char', type: 'type', info: 'Character' },
  { label: 'string', type: 'type', info: 'String' },
  { label: 'unit', type: 'type', info: 'Unit type' },
  { label: 'list', type: 'type', info: 'List' },
  { label: 'array', type: 'type', info: 'Array' },
  { label: 'option', type: 'type', info: 'Option type' },
  { label: 'Some', type: 'class', info: 'Some x' },
  { label: 'None', type: 'class', info: 'None' },
  { label: 'result', type: 'type', info: 'Result type' },
  { label: 'Ok', type: 'class', info: 'Ok x' },
  { label: 'Error', type: 'class', info: 'Error x' },
  // Stdlib
  { label: 'print_endline', type: 'function', info: 'Print line' },
  { label: 'print_string', type: 'function', info: 'Print string' },
  { label: 'print_int', type: 'function', info: 'Print int' },
  { label: 'print_float', type: 'function', info: 'Print float' },
  { label: 'print_char', type: 'function', info: 'Print char' },
  { label: 'read_line', type: 'function', info: 'Read line' },
  { label: 'read_int', type: 'function', info: 'Read int' },
  { label: 'read_float', type: 'function', info: 'Read float' },
  { label: 'List.map', type: 'function', info: 'Map list' },
  { label: 'List.filter', type: 'function', info: 'Filter list' },
  { label: 'List.iter', type: 'function', info: 'Iterate list' },
  { label: 'List.fold_left', type: 'function', info: 'Fold left' },
  { label: 'List.fold_right', type: 'function', info: 'Fold right' },
  { label: 'List.length', type: 'function', info: 'List length' },
  { label: 'List.rev', type: 'function', info: 'Reverse list' },
  { label: 'List.sort', type: 'function', info: 'Sort list' },
  { label: 'List.append', type: 'function', info: 'Append lists' },
  { label: 'List.concat', type: 'function', info: 'Concat lists' },
  { label: 'List.hd', type: 'function', info: 'Head of list' },
  { label: 'List.tl', type: 'function', info: 'Tail of list' },
  { label: 'List.nth', type: 'function', info: 'Nth element' },
  { label: 'List.mem', type: 'function', info: 'Is member' },
  { label: 'List.find', type: 'function', info: 'Find first' },
  { label: 'List.exists', type: 'function', info: 'Any match' },
  { label: 'List.for_all', type: 'function', info: 'All match' },
  { label: 'Array.make', type: 'function', info: 'Make array' },
  { label: 'Array.length', type: 'function', info: 'Array length' },
  { label: 'Array.get', type: 'function', info: 'Array get' },
  { label: 'Array.set', type: 'function', info: 'Array set' },
  { label: 'Array.iter', type: 'function', info: 'Iterate array' },
  { label: 'Array.map', type: 'function', info: 'Map array' },
  { label: 'Array.fold_left', type: 'function', info: 'Fold left' },
  { label: 'String.length', type: 'function', info: 'String length' },
  { label: 'String.sub', type: 'function', info: 'Substring' },
  { label: 'String.concat', type: 'function', info: 'Concat strings' },
  { label: 'String.split_on_char', type: 'function', info: 'Split' },
  { label: 'String.uppercase_ascii', type: 'function', info: 'Uppercase' },
  { label: 'String.lowercase_ascii', type: 'function', info: 'Lowercase' },
  { label: 'int_of_string', type: 'function', info: 'Parse int' },
  { label: 'float_of_string', type: 'function', info: 'Parse float' },
  { label: 'string_of_int', type: 'function', info: 'Int to string' },
  { label: 'string_of_float', type: 'function', info: 'Float to string' },
  { label: 'Printf.printf', type: 'function', info: 'Formatted print' },
  { label: 'Printf.sprintf', type: 'function', info: 'Format to string' },
  { label: 'Hashtbl', type: 'module', info: 'Hashtable module' },
  { label: 'Hashtbl.create', type: 'function', info: 'Create hashtbl' },
  { label: 'Hashtbl.add', type: 'function', info: 'Add entry' },
  { label: 'Hashtbl.find', type: 'function', info: 'Find entry' },
  { label: 'Hashtbl.remove', type: 'function', info: 'Remove entry' },
  { label: 'Map', type: 'module', info: 'Functor Map' },
  { label: 'Set', type: 'module', info: 'Functor Set' },
  { label: 'Option.map', type: 'function', info: 'Map option' },
  { label: 'Option.value', type: 'function', info: 'Option get/default' },
  { label: 'Result.map', type: 'function', info: 'Map result' },
  { label: 'Result.bind', type: 'function', info: 'Bind result' },
  // Operators
  { label: '|>', type: 'keyword', info: 'Pipe' },
  { label: '@@', type: 'keyword', info: 'Reverse pipe' },
  { label: '::', type: 'keyword', info: 'List cons' },
  { label: '@', type: 'keyword', info: 'List append' },
];
