// Completion entries for r.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  // Keywords
  { label: 'if', type: 'keyword', info: 'If statement' },
  { label: 'else', type: 'keyword', info: 'Else branch' },
  { label: 'for', type: 'keyword', info: 'For loop' },
  { label: 'while', type: 'keyword', info: 'While loop' },
  { label: 'repeat', type: 'keyword', info: 'Repeat loop' },
  { label: 'function', type: 'keyword', info: 'Define function' },
  { label: 'return', type: 'keyword', info: 'Return value' },
  { label: 'break', type: 'keyword', info: 'Break loop' },
  { label: 'next', type: 'keyword', info: 'Next iteration' },
  { label: 'TRUE', type: 'constant', info: 'Logical true' },
  { label: 'FALSE', type: 'constant', info: 'Logical false' },
  { label: 'NULL', type: 'constant', info: 'Null value' },
  { label: 'NA', type: 'constant', info: 'Missing value' },
  { label: 'NaN', type: 'constant', info: 'Not a number' },
  { label: 'Inf', type: 'constant', info: 'Infinity' },
  { label: 'T', type: 'constant', info: 'Shorthand TRUE' },
  { label: 'F', type: 'constant', info: 'Shorthand FALSE' },
  { label: 'NA_integer_', type: 'constant', info: 'Integer NA' },
  { label: 'NA_real_', type: 'constant', info: 'Real NA' },
  { label: 'NA_character_', type: 'constant', info: 'Character NA' },
  { label: 'NA_complex_', type: 'constant', info: 'Complex NA' },
  // Base R: creation
  { label: 'c', type: 'function', info: 'Combine values' },
  { label: 'list', type: 'function', info: 'Create list' },
  { label: 'vector', type: 'function', info: 'Create vector' },
  { label: 'array', type: 'function', info: 'Create array' },
  { label: 'matrix', type: 'function', info: 'Create matrix' },
  { label: 'data.frame', type: 'function', info: 'Create data frame' },
  { label: 'factor', type: 'function', info: 'Categorical variable' },
  { label: 'as.numeric', type: 'function', info: 'To numeric' },
  { label: 'as.integer', type: 'function', info: 'To integer' },
  { label: 'as.character', type: 'function', info: 'To character' },
  { label: 'as.logical', type: 'function', info: 'To logical' },
  { label: 'as.factor', type: 'function', info: 'To factor' },
  { label: 'as.Date', type: 'function', info: 'To Date' },
  { label: 'as.POSIXct', type: 'function', info: 'To POSIXct' },
  { label: 'as.vector', type: 'function', info: 'To vector' },
  { label: 'as.matrix', type: 'function', info: 'To matrix' },
  { label: 'as.list', type: 'function', info: 'To list' },
  { label: 'as.data.frame', type: 'function', info: 'To data frame' },
  // Base R: inspection
  { label: 'print', type: 'function', info: 'Print object' },
  { label: 'cat', type: 'function', info: 'Concatenate print' },
  { label: 'paste', type: 'function', info: 'Paste strings' },
  { label: 'paste0', type: 'function', info: 'Paste no sep' },
  { label: 'sprintf', type: 'function', info: 'Format string' },
  { label: 'format', type: 'function', info: 'Format numbers' },
  { label: 'formatC', type: 'function', info: 'C-style format' },
  { label: 'length', type: 'function', info: 'Vector length' },
  { label: 'nrow', type: 'function', info: 'Row count' },
  { label: 'ncol', type: 'function', info: 'Column count' },
  { label: 'NROW', type: 'function', info: 'Vector-safe nrow' },
  { label: 'NCOL', type: 'function', info: 'Vector-safe ncol' },
  { label: 'dim', type: 'function', info: 'Object dimensions' },
  { label: 'names', type: 'function', info: 'Names attribute' },
  { label: 'rownames', type: 'function', info: 'Row names' },
  { label: 'colnames', type: 'function', info: 'Column names' },
  { label: 'head', type: 'function', info: 'First elements' },
  { label: 'tail', type: 'function', info: 'Last elements' },
  { label: 'summary', type: 'function', info: 'Summary stats' },
  { label: 'str', type: 'function', info: 'Structure' },
  { label: 'class', type: 'function', info: 'Object class' },
  { label: 'typeof', type: 'function', info: 'Object type' },
  { label: 'attributes', type: 'function', info: 'Get attributes' },
  { label: 'attr', type: 'function', info: 'Get/set attribute' },
  // String functions
  { label: 'strsplit', type: 'function', info: 'Split strings' },
  { label: 'gsub', type: 'function', info: 'Global substitute' },
  { label: 'sub', type: 'function', info: 'Substitute first' },
  { label: 'grep', type: 'function', info: 'Pattern indices' },
  { label: 'grepl', type: 'function', info: 'Pattern logical' },
  { label: 'regmatches', type: 'function', info: 'Regex matches' },
  { label: 'regexpr', type: 'function', info: 'Regex search' },
  { label: 'gregexpr', type: 'function', info: 'Global regex' },
  { label: 'substring', type: 'function', info: 'Substring' },
  { label: 'substr', type: 'function', info: 'Substring' },
  { label: 'nchar', type: 'function', info: 'Character count' },
  { label: 'tolower', type: 'function', info: 'Lowercase' },
  { label: 'toupper', type: 'function', info: 'Uppercase' },
  { label: 'trimws', type: 'function', info: 'Trim whitespace' },
  { label: 'startsWith', type: 'function', info: 'Starts with' },
  { label: 'endsWith', type: 'function', info: 'Ends with' },
  // Sequences
  { label: 'seq', type: 'function', info: 'Sequence' },
  { label: 'seq_len', type: 'function', info: 'Length sequence' },
  { label: 'seq_along', type: 'function', info: 'Along sequence' },
  { label: 'rep', type: 'function', info: 'Repeat values' },
  { label: 'rev', type: 'function', info: 'Reverse' },
  { label: 'sort', type: 'function', info: 'Sort vector' },
  { label: 'order', type: 'function', info: 'Ordering' },
  { label: 'rank', type: 'function', info: 'Ranks' },
  { label: 'unique', type: 'function', info: 'Unique values' },
  { label: 'duplicated', type: 'function', info: 'Is duplicate' },
  { label: 'which', type: 'function', info: 'Which indices' },
  { label: 'match', type: 'function', info: 'Value position' },
  { label: 'table', type: 'function', info: 'Frequency table' },
  { label: 'tabulate', type: 'function', info: 'Integer counts' },
  // Logical
  { label: 'any', type: 'function', info: 'Any TRUE' },
  { label: 'all', type: 'function', info: 'All TRUE' },
  { label: 'xor', type: 'function', info: 'Exclusive OR' },
  { label: 'isTRUE', type: 'function', info: 'Is single TRUE' },
  { label: 'isFALSE', type: 'function', info: 'Is single FALSE' },
  { label: 'is.na', type: 'function', info: 'Is NA' },
  { label: 'is.null', type: 'function', info: 'Is NULL' },
  { label: 'is.numeric', type: 'function', info: 'Is numeric' },
  { label: 'is.character', type: 'function', info: 'Is character' },
  { label: 'is.logical', type: 'function', info: 'Is logical' },
  { label: 'is.factor', type: 'function', info: 'Is factor' },
  { label: 'is.data.frame', type: 'function', info: 'Is data frame' },
  { label: 'is.list', type: 'function', info: 'Is list' },
  { label: 'is.vector', type: 'function', info: 'Is vector' },
  { label: 'is.function', type: 'function', info: 'Is function' },
  { label: 'is.finite', type: 'function', info: 'Is finite' },
  { label: 'is.infinite', type: 'function', info: 'Is infinite' },
  { label: 'is.nan', type: 'function', info: 'Is NaN' },
  // Summary stats
  { label: 'sum', type: 'function', info: 'Sum values' },
  { label: 'mean', type: 'function', info: 'Arithmetic mean' },
  { label: 'median', type: 'function', info: 'Median' },
  { label: 'min', type: 'function', info: 'Minimum' },
  { label: 'max', type: 'function', info: 'Maximum' },
  { label: 'range', type: 'function', info: 'Min and max' },
  { label: 'var', type: 'function', info: 'Variance' },
  { label: 'sd', type: 'function', info: 'Standard dev' },
  { label: 'quantile', type: 'function', info: 'Quantiles' },
  { label: 'cor', type: 'function', info: 'Correlation' },
  { label: 'cov', type: 'function', info: 'Covariance' },
  { label: 'prod', type: 'function', info: 'Product' },
  { label: 'cumsum', type: 'function', info: 'Cumulative sum' },
  { label: 'cumprod', type: 'function', info: 'Cumulative prod' },
  { label: 'cummax', type: 'function', info: 'Cumulative max' },
  { label: 'cummin', type: 'function', info: 'Cumulative min' },
  { label: 'diff', type: 'function', info: 'Differences' },
  // Apply family
  { label: 'apply', type: 'function', info: 'Apply over array' },
  { label: 'sapply', type: 'function', info: 'Simplify apply' },
  { label: 'lapply', type: 'function', info: 'List apply' },
  { label: 'vapply', type: 'function', info: 'Typed apply' },
  { label: 'mapply', type: 'function', info: 'Multi-arg apply' },
  { label: 'tapply', type: 'function', info: 'Table apply' },
  { label: 'Reduce', type: 'function', info: 'Reduce' },
  { label: 'Filter', type: 'function', info: 'Filter list' },
  { label: 'Map', type: 'function', info: 'Map function' },
  { label: 'Find', type: 'function', info: 'Find first match' },
  { label: 'Position', type: 'function', info: 'Position of match' },
  { label: 'do.call', type: 'function', info: 'Call with args' },
  // Control
  { label: 'tryCatch', type: 'function', info: 'Try-catch' },
  { label: 'try', type: 'function', info: 'Try expression' },
  { label: 'stop', type: 'function', info: 'Raise error' },
  { label: 'warning', type: 'function', info: 'Raise warning' },
  { label: 'message', type: 'function', info: 'Emit message' },
  { label: 'stopifnot', type: 'function', info: 'Assert stop' },
  { label: 'withCallingHandlers', type: 'function', info: 'Calling handlers' },
  { label: 'simpleError', type: 'function', info: 'Create simple error' },
  { label: 'simpleWarning', type: 'function', info: 'Simple warning' },
  { label: 'simpleMessage', type: 'function', info: 'Simple message' },
  { label: 'simpleCondition', type: 'function', info: 'Simple condition' },
  // Reading files
  { label: 'read.csv', type: 'function', info: 'Read CSV' },
  { label: 'read.csv2', type: 'function', info: 'Read CSV (;)' },
  { label: 'read.table', type: 'function', info: 'Read table' },
  { label: 'read.delim', type: 'function', info: 'Read delimited' },
  { label: 'readLines', type: 'function', info: 'Read lines' },
  { label: 'readRDS', type: 'function', info: 'Read RDS' },
  { label: 'saveRDS', type: 'function', info: 'Save RDS' },
  { label: 'write.csv', type: 'function', info: 'Write CSV' },
  { label: 'write.table', type: 'function', info: 'Write table' },
  { label: 'writeLines', type: 'function', info: 'Write lines' },
  { label: 'file.exists', type: 'function', info: 'File exists' },
  { label: 'dir.exists', type: 'function', info: 'Dir exists' },
  { label: 'list.files', type: 'function', info: 'List files' },
  { label: 'list.dirs', type: 'function', info: 'List dirs' },
  { label: 'file.path', type: 'function', info: 'Path join' },
  { label: 'getwd', type: 'function', info: 'Current dir' },
  { label: 'setwd', type: 'function', info: 'Set dir' },
  // dplyr
  { label: 'mutate', type: 'function', info: 'Add/change columns' },
  { label: 'select', type: 'function', info: 'Select columns' },
  { label: 'filter', type: 'function', info: 'Filter rows' },
  { label: 'arrange', type: 'function', info: 'Sort rows' },
  { label: 'summarize', type: 'function', info: 'Summarize' },
  { label: 'summarise', type: 'function', info: 'Summarise' },
  { label: 'group_by', type: 'function', info: 'Group by' },
  { label: 'ungroup', type: 'function', info: 'Remove grouping' },
  { label: 'left_join', type: 'function', info: 'Left join' },
  { label: 'right_join', type: 'function', info: 'Right join' },
  { label: 'inner_join', type: 'function', info: 'Inner join' },
  { label: 'full_join', type: 'function', info: 'Full join' },
  { label: 'semi_join', type: 'function', info: 'Semi join' },
  { label: 'anti_join', type: 'function', info: 'Anti join' },
  { label: 'bind_rows', type: 'function', info: 'Bind rows' },
  { label: 'bind_cols', type: 'function', info: 'Bind cols' },
  { label: 'count', type: 'function', info: 'Count rows' },
  { label: 'distinct', type: 'function', info: 'Unique rows' },
  { label: 'pull', type: 'function', info: 'Pull column' },
  { label: 'slice', type: 'function', info: 'Slice rows' },
  { label: 'slice_head', type: 'function', info: 'First rows' },
  { label: 'slice_tail', type: 'function', info: 'Last rows' },
  { label: 'slice_max', type: 'function', info: 'Top by value' },
  { label: 'slice_min', type: 'function', info: 'Bottom by value' },
  { label: 'rename', type: 'function', info: 'Rename columns' },
  { label: 'relocate', type: 'function', info: 'Reorder columns' },
  { label: 'across', type: 'function', info: 'Apply across cols' },
  { label: 'starts_with', type: 'function', info: 'Select by prefix' },
  { label: 'ends_with', type: 'function', info: 'Select by suffix' },
  { label: 'contains', type: 'function', info: 'Select by substring' },
  { label: 'matches', type: 'function', info: 'Select by regex' },
  { label: 'everything', type: 'function', info: 'Select all' },
  { label: '%>%', type: 'keyword', info: 'Pipe (magrittr)' },
  { label: '|>', type: 'keyword', info: 'Native pipe' },
  // ggplot2
  { label: 'ggplot', type: 'function', info: 'Create ggplot' },
  { label: 'aes', type: 'function', info: 'Aesthetic mapping' },
  { label: 'geom_point', type: 'function', info: 'Scatter layer' },
  { label: 'geom_line', type: 'function', info: 'Line layer' },
  { label: 'geom_bar', type: 'function', info: 'Bar (count) layer' },
  { label: 'geom_col', type: 'function', info: 'Bar (value) layer' },
  { label: 'geom_histogram', type: 'function', info: 'Histogram' },
  { label: 'geom_boxplot', type: 'function', info: 'Boxplot' },
  { label: 'geom_density', type: 'function', info: 'Density layer' },
  { label: 'geom_smooth', type: 'function', info: 'Smooth layer' },
  { label: 'geom_text', type: 'function', info: 'Text layer' },
  { label: 'geom_label', type: 'function', info: 'Label layer' },
  { label: 'geom_tile', type: 'function', info: 'Tile layer' },
  { label: 'geom_raster', type: 'function', info: 'Raster layer' },
  { label: 'geom_area', type: 'function', info: 'Area layer' },
  { label: 'geom_ribbon', type: 'function', info: 'Ribbon layer' },
  { label: 'geom_violin', type: 'function', info: 'Violin plot' },
  { label: 'geom_jitter', type: 'function', info: 'Jittered points' },
  { label: 'geom_errorbar', type: 'function', info: 'Error bars' },
  { label: 'theme', type: 'function', info: 'Custom theme' },
  { label: 'theme_minimal', type: 'function', info: 'Minimal theme' },
  { label: 'theme_bw', type: 'function', info: 'B&W theme' },
  { label: 'theme_classic', type: 'function', info: 'Classic theme' },
  { label: 'theme_void', type: 'function', info: 'Void theme' },
  { label: 'theme_light', type: 'function', info: 'Light theme' },
  { label: 'theme_dark', type: 'function', info: 'Dark theme' },
  { label: 'labs', type: 'function', info: 'Axis/legend labels' },
  { label: 'xlab', type: 'function', info: 'X axis label' },
  { label: 'ylab', type: 'function', info: 'Y axis label' },
  { label: 'ggtitle', type: 'function', info: 'Plot title' },
  { label: 'scale_color_manual', type: 'function', info: 'Manual colors' },
  { label: 'scale_fill_manual', type: 'function', info: 'Manual fills' },
  { label: 'scale_x_continuous', type: 'function', info: 'X continuous' },
  { label: 'scale_y_continuous', type: 'function', info: 'Y continuous' },
  { label: 'scale_x_log10', type: 'function', info: 'X log10' },
  { label: 'scale_y_log10', type: 'function', info: 'Y log10' },
  { label: 'facet_wrap', type: 'function', info: 'Wrap facets' },
  { label: 'facet_grid', type: 'function', info: 'Grid facets' },
  { label: 'coord_flip', type: 'function', info: 'Flip axes' },
  { label: 'coord_polar', type: 'function', info: 'Polar coords' },
  { label: 'coord_fixed', type: 'function', info: 'Fixed ratio' },
  // tidyr / readr
  { label: 'pivot_longer', type: 'function', info: 'Wide to long' },
  { label: 'pivot_wider', type: 'function', info: 'Long to wide' },
  { label: 'separate', type: 'function', info: 'Split column' },
  { label: 'unite', type: 'function', info: 'Combine columns' },
  { label: 'drop_na', type: 'function', info: 'Drop NA rows' },
  { label: 'fill', type: 'function', info: 'Fill NA' },
  { label: 'complete', type: 'function', info: 'Complete combos' },
  { label: 'nest', type: 'function', info: 'Nest columns' },
  { label: 'unnest', type: 'function', info: 'Unnest columns' },
  { label: 'read_csv', type: 'function', info: 'Read CSV (readr)' },
  { label: 'read_tsv', type: 'function', info: 'Read TSV' },
  { label: 'read_delim', type: 'function', info: 'Read delim' },
  { label: 'write_csv', type: 'function', info: 'Write CSV' },
  { label: 'write_tsv', type: 'function', info: 'Write TSV' },
  // Package management
  { label: 'library', type: 'function', info: 'Load package' },
  { label: 'require', type: 'function', info: 'Require package' },
  { label: 'install.packages', type: 'function', info: 'Install pkg' },
  { label: 'update.packages', type: 'function', info: 'Update pkgs' },
  { label: 'remove.packages', type: 'function', info: 'Remove pkgs' },
  { label: 'installed.packages', type: 'function', info: 'List pkgs' },
  { label: 'loadNamespace', type: 'function', info: 'Load namespace' },
  { label: 'requireNamespace', type: 'function', info: 'Require namespace' },
  // dplyr
  { label: 'filter', type: 'function', info: 'dplyr filter rows' },
  { label: 'select', type: 'function', info: 'dplyr select cols' },
  { label: 'mutate', type: 'function', info: 'dplyr mutate' },
  { label: 'transmute', type: 'function', info: 'dplyr transmute' },
  { label: 'arrange', type: 'function', info: 'dplyr arrange' },
  { label: 'summarise', type: 'function', info: 'dplyr summarise' },
  { label: 'summarize', type: 'function', info: 'dplyr summarize' },
  { label: 'group_by', type: 'function', info: 'dplyr group_by' },
  { label: 'ungroup', type: 'function', info: 'dplyr ungroup' },
  { label: 'distinct', type: 'function', info: 'dplyr distinct' },
  { label: 'count', type: 'function', info: 'dplyr count' },
  { label: 'tally', type: 'function', info: 'dplyr tally' },
  { label: 'slice', type: 'function', info: 'dplyr slice' },
  { label: 'slice_head', type: 'function', info: 'dplyr slice head' },
  { label: 'slice_tail', type: 'function', info: 'dplyr slice tail' },
  { label: 'slice_min', type: 'function', info: 'dplyr slice min' },
  { label: 'slice_max', type: 'function', info: 'dplyr slice max' },
  { label: 'slice_sample', type: 'function', info: 'Random slice' },
  { label: 'rename', type: 'function', info: 'dplyr rename' },
  { label: 'rename_with', type: 'function', info: 'rename w/ func' },
  { label: 'relocate', type: 'function', info: 'dplyr relocate' },
  { label: 'pull', type: 'function', info: 'dplyr pull col' },
  { label: 'bind_rows', type: 'function', info: 'Row-bind tibbles' },
  { label: 'bind_cols', type: 'function', info: 'Col-bind tibbles' },
  { label: 'inner_join', type: 'function', info: 'Inner join' },
  { label: 'left_join', type: 'function', info: 'Left join' },
  { label: 'right_join', type: 'function', info: 'Right join' },
  { label: 'full_join', type: 'function', info: 'Full join' },
  { label: 'semi_join', type: 'function', info: 'Semi join' },
  { label: 'anti_join', type: 'function', info: 'Anti join' },
  { label: 'cross_join', type: 'function', info: 'Cross join' },
  { label: 'nest_join', type: 'function', info: 'Nest join' },
  { label: 'if_else', type: 'function', info: 'Vector if-else' },
  { label: 'case_when', type: 'function', info: 'Vectorised cases' },
  { label: 'case_match', type: 'function', info: 'Case match' },
  { label: 'coalesce', type: 'function', info: 'dplyr coalesce' },
  { label: 'lag', type: 'function', info: 'dplyr lag' },
  { label: 'lead', type: 'function', info: 'dplyr lead' },
  { label: 'n', type: 'function', info: 'Row count' },
  { label: 'n_distinct', type: 'function', info: 'Distinct count' },
  { label: 'across', type: 'function', info: 'Apply across cols' },
  { label: 'c_across', type: 'function', info: 'Row-wise across' },
  { label: 'rowwise', type: 'function', info: 'Row-wise ops' },
  { label: 'cur_group', type: 'function', info: 'Current group' },
  { label: 'cur_group_id', type: 'function', info: 'Cur group id' },
  { label: 'cur_data', type: 'function', info: 'Current data' },
  { label: 'cur_column', type: 'function', info: 'Current col' },
  { label: 'desc', type: 'function', info: 'Descending sort' },
  { label: 'between', type: 'function', info: 'Value between' },
  { label: 'near', type: 'function', info: 'Approx equal' },
  { label: 'row_number', type: 'function', info: 'Rank row' },
  { label: 'min_rank', type: 'function', info: 'Min rank' },
  { label: 'dense_rank', type: 'function', info: 'Dense rank' },
  { label: 'percent_rank', type: 'function', info: 'Percent rank' },
  { label: 'cume_dist', type: 'function', info: 'Cumulative dist' },
  { label: 'ntile', type: 'function', info: 'N-tile' },
  { label: 'where', type: 'function', info: 'Helper: where' },
  { label: 'starts_with', type: 'function', info: 'Col starts_with' },
  { label: 'ends_with', type: 'function', info: 'Col ends_with' },
  { label: 'contains', type: 'function', info: 'Col contains' },
  { label: 'matches', type: 'function', info: 'Col regex match' },
  { label: 'num_range', type: 'function', info: 'Col num range' },
  { label: 'all_of', type: 'function', info: 'All of vars' },
  { label: 'any_of', type: 'function', info: 'Any of vars' },
  { label: 'everything', type: 'function', info: 'All cols' },
  { label: 'last_col', type: 'function', info: 'Last col' },
  // tidyr
  { label: 'pivot_longer', type: 'function', info: 'tidyr longer' },
  { label: 'pivot_wider', type: 'function', info: 'tidyr wider' },
  { label: 'gather', type: 'function', info: 'tidyr gather' },
  { label: 'spread', type: 'function', info: 'tidyr spread' },
  { label: 'separate', type: 'function', info: 'tidyr separate' },
  { label: 'separate_wider_delim', type: 'function', info: 'Split by delim' },
  { label: 'separate_wider_position', type: 'function', info: 'Split by pos' },
  { label: 'separate_wider_regex', type: 'function', info: 'Split by regex' },
  { label: 'separate_rows', type: 'function', info: 'Separate rows' },
  { label: 'unite', type: 'function', info: 'tidyr unite' },
  { label: 'drop_na', type: 'function', info: 'Drop NA rows' },
  { label: 'fill', type: 'function', info: 'Fill NA' },
  { label: 'replace_na', type: 'function', info: 'Replace NA' },
  { label: 'nest', type: 'function', info: 'tidyr nest' },
  { label: 'unnest', type: 'function', info: 'tidyr unnest' },
  { label: 'unnest_longer', type: 'function', info: 'Unnest long' },
  { label: 'unnest_wider', type: 'function', info: 'Unnest wide' },
  { label: 'hoist', type: 'function', info: 'Hoist fields' },
  { label: 'chop', type: 'function', info: 'Chop columns' },
  { label: 'unchop', type: 'function', info: 'Unchop columns' },
  { label: 'pack', type: 'function', info: 'Pack columns' },
  { label: 'unpack', type: 'function', info: 'Unpack columns' },
  { label: 'complete', type: 'function', info: 'Fill combos' },
  { label: 'crossing', type: 'function', info: 'All combos' },
  { label: 'expand', type: 'function', info: 'Expand' },
  { label: 'expand_grid', type: 'function', info: 'Expand grid' },
  // readr
  { label: 'read_csv', type: 'function', info: 'readr read_csv' },
  { label: 'read_csv2', type: 'function', info: 'read_csv2 (;)' },
  { label: 'read_tsv', type: 'function', info: 'read_tsv' },
  { label: 'read_delim', type: 'function', info: 'Read delim' },
  { label: 'read_fwf', type: 'function', info: 'Fixed width' },
  { label: 'read_log', type: 'function', info: 'Read log' },
  { label: 'read_lines', type: 'function', info: 'Read lines' },
  { label: 'read_file', type: 'function', info: 'Read file' },
  { label: 'write_csv', type: 'function', info: 'Write CSV' },
  { label: 'write_csv2', type: 'function', info: 'Write CSV2' },
  { label: 'write_tsv', type: 'function', info: 'Write TSV' },
  { label: 'write_delim', type: 'function', info: 'Write delim' },
  { label: 'write_rds', type: 'function', info: 'Write RDS' },
  { label: 'read_rds', type: 'function', info: 'Read RDS' },
  { label: 'parse_number', type: 'function', info: 'Parse number' },
  { label: 'parse_double', type: 'function', info: 'Parse double' },
  { label: 'parse_integer', type: 'function', info: 'Parse integer' },
  { label: 'parse_character', type: 'function', info: 'Parse string' },
  { label: 'parse_logical', type: 'function', info: 'Parse logical' },
  { label: 'parse_date', type: 'function', info: 'Parse date' },
  { label: 'parse_datetime', type: 'function', info: 'Parse datetime' },
  { label: 'parse_time', type: 'function', info: 'Parse time' },
  { label: 'parse_factor', type: 'function', info: 'Parse factor' },
  { label: 'parse_guess', type: 'function', info: 'Guess type' },
  { label: 'col_double', type: 'function', info: 'Col double' },
  { label: 'col_integer', type: 'function', info: 'Col integer' },
  { label: 'col_character', type: 'function', info: 'Col character' },
  { label: 'col_logical', type: 'function', info: 'Col logical' },
  { label: 'col_date', type: 'function', info: 'Col date' },
  { label: 'col_datetime', type: 'function', info: 'Col datetime' },
  { label: 'col_factor', type: 'function', info: 'Col factor' },
  { label: 'col_skip', type: 'function', info: 'Col skip' },
  { label: 'col_guess', type: 'function', info: 'Col guess' },
  // tibble
  { label: 'tibble', type: 'function', info: 'Make tibble' },
  { label: 'as_tibble', type: 'function', info: 'Coerce tibble' },
  { label: 'tribble', type: 'function', info: 'Row-wise tibble' },
  { label: 'enframe', type: 'function', info: 'Vec -> tibble' },
  { label: 'deframe', type: 'function', info: 'Tibble -> vec' },
  { label: 'add_row', type: 'function', info: 'Add row' },
  { label: 'add_column', type: 'function', info: 'Add column' },
  { label: 'rownames_to_column', type: 'function', info: 'Rownames col' },
  { label: 'column_to_rownames', type: 'function', info: 'Col rownames' },
  { label: 'has_rownames', type: 'function', info: 'Has rownames' },
  { label: 'rowid_to_column', type: 'function', info: 'Rowid to col' },
  { label: 'glimpse', type: 'function', info: 'Tibble glimpse' },
  // stringr
  { label: 'str_detect', type: 'function', info: 'stringr detect' },
  { label: 'str_starts', type: 'function', info: 'Starts with' },
  { label: 'str_ends', type: 'function', info: 'Ends with' },
  { label: 'str_which', type: 'function', info: 'Which match' },
  { label: 'str_count', type: 'function', info: 'Count matches' },
  { label: 'str_subset', type: 'function', info: 'Subset vec' },
  { label: 'str_locate', type: 'function', info: 'Locate pos' },
  { label: 'str_locate_all', type: 'function', info: 'Locate all' },
  { label: 'str_extract', type: 'function', info: 'Extract match' },
  { label: 'str_extract_all', type: 'function', info: 'Extract all' },
  { label: 'str_match', type: 'function', info: 'Match groups' },
  { label: 'str_match_all', type: 'function', info: 'Match all groups' },
  { label: 'str_replace', type: 'function', info: 'Replace first' },
  { label: 'str_replace_all', type: 'function', info: 'Replace all' },
  { label: 'str_remove', type: 'function', info: 'Remove match' },
  { label: 'str_remove_all', type: 'function', info: 'Remove all' },
  { label: 'str_split', type: 'function', info: 'Split string' },
  { label: 'str_split_fixed', type: 'function', info: 'Split fixed' },
  { label: 'str_split_1', type: 'function', info: 'Split length 1' },
  { label: 'str_c', type: 'function', info: 'Concatenate strings' },
  { label: 'str_length', type: 'function', info: 'String length' },
  { label: 'str_sub', type: 'function', info: 'Substring' },
  { label: 'str_to_upper', type: 'function', info: 'Uppercase' },
  { label: 'str_to_lower', type: 'function', info: 'Lowercase' },
  { label: 'str_to_title', type: 'function', info: 'Title case' },
  { label: 'str_to_sentence', type: 'function', info: 'Sentence case' },
  { label: 'str_trim', type: 'function', info: 'Trim whitespace' },
  { label: 'str_squish', type: 'function', info: 'Squish whitespace' },
  { label: 'str_pad', type: 'function', info: 'Pad string' },
  { label: 'str_trunc', type: 'function', info: 'Truncate string' },
  { label: 'str_wrap', type: 'function', info: 'Wrap string' },
  { label: 'str_order', type: 'function', info: 'Order strings' },
  { label: 'str_sort', type: 'function', info: 'Sort strings' },
  { label: 'str_rank', type: 'function', info: 'Rank strings' },
  { label: 'str_dup', type: 'function', info: 'Repeat string' },
  { label: 'str_glue', type: 'function', info: 'Glue template' },
  { label: 'str_interp', type: 'function', info: 'Interp template' },
  { label: 'regex', type: 'function', info: 'stringr regex' },
  { label: 'fixed', type: 'function', info: 'Fixed pattern' },
  { label: 'coll', type: 'function', info: 'Collation pattern' },
  { label: 'boundary', type: 'function', info: 'Boundary pattern' },
  // forcats
  { label: 'fct_rev', type: 'function', info: 'Reverse factor' },
  { label: 'fct_relevel', type: 'function', info: 'Relevel factor' },
  { label: 'fct_infreq', type: 'function', info: 'Reorder by freq' },
  { label: 'fct_inorder', type: 'function', info: 'Reorder in order' },
  { label: 'fct_reorder', type: 'function', info: 'Reorder by stat' },
  { label: 'fct_reorder2', type: 'function', info: 'Reorder 2-var' },
  { label: 'fct_recode', type: 'function', info: 'Recode levels' },
  { label: 'fct_collapse', type: 'function', info: 'Collapse levels' },
  { label: 'fct_lump', type: 'function', info: 'Lump rare' },
  { label: 'fct_lump_n', type: 'function', info: 'Keep top n' },
  { label: 'fct_lump_min', type: 'function', info: 'Lump under min' },
  { label: 'fct_other', type: 'function', info: 'Other level' },
  { label: 'fct_drop', type: 'function', info: 'Drop unused' },
  { label: 'fct_na_value_to_level', type: 'function', info: 'NA to level' },
  { label: 'fct_count', type: 'function', info: 'Count levels' },
  { label: 'fct_unique', type: 'function', info: 'Unique levels' },
  { label: 'as_factor', type: 'function', info: 'To factor' },
  { label: 'fct_c', type: 'function', info: 'Concat factors' },
  // lubridate
  { label: 'ymd', type: 'function', info: 'Parse Y-M-D' },
  { label: 'mdy', type: 'function', info: 'Parse M-D-Y' },
  { label: 'dmy', type: 'function', info: 'Parse D-M-Y' },
  { label: 'ymd_hms', type: 'function', info: 'Y-M-D H:M:S' },
  { label: 'ymd_hm', type: 'function', info: 'Y-M-D H:M' },
  { label: 'ymd_h', type: 'function', info: 'Y-M-D H' },
  { label: 'ydm', type: 'function', info: 'Y-D-M' },
  { label: 'year', type: 'function', info: 'Get year' },
  { label: 'month', type: 'function', info: 'Get month' },
  { label: 'day', type: 'function', info: 'Get day' },
  { label: 'hour', type: 'function', info: 'Get hour' },
  { label: 'minute', type: 'function', info: 'Get minute' },
  { label: 'second', type: 'function', info: 'Get second' },
  { label: 'wday', type: 'function', info: 'Day of week' },
  { label: 'yday', type: 'function', info: 'Day of year' },
  { label: 'mday', type: 'function', info: 'Day of month' },
  { label: 'qday', type: 'function', info: 'Day of quarter' },
  { label: 'isoweek', type: 'function', info: 'ISO week' },
  { label: 'isoyear', type: 'function', info: 'ISO year' },
  { label: 'week', type: 'function', info: 'Week of year' },
  { label: 'quarter', type: 'function', info: 'Quarter' },
  { label: 'semester', type: 'function', info: 'Semester' },
  { label: 'now', type: 'function', info: 'Current time' },
  { label: 'today', type: 'function', info: 'Current date' },
  { label: 'days', type: 'function', info: 'Days period' },
  { label: 'hours', type: 'function', info: 'Hours period' },
  { label: 'minutes', type: 'function', info: 'Minutes period' },
  { label: 'seconds', type: 'function', info: 'Seconds period' },
  { label: 'weeks', type: 'function', info: 'Weeks period' },
  { label: 'months', type: 'function', info: 'Months period' },
  { label: 'years', type: 'function', info: 'Years period' },
  { label: 'ddays', type: 'function', info: 'Duration days' },
  { label: 'dminutes', type: 'function', info: 'Duration minutes' },
  { label: 'dhours', type: 'function', info: 'Duration hours' },
  { label: 'interval', type: 'function', info: 'Interval' },
  { label: 'int_length', type: 'function', info: 'Interval length' },
  { label: 'int_overlaps', type: 'function', info: 'Intervals overlap' },
  { label: 'duration', type: 'function', info: 'Make duration' },
  { label: 'period', type: 'function', info: 'Make period' },
  { label: 'floor_date', type: 'function', info: 'Floor date' },
  { label: 'ceiling_date', type: 'function', info: 'Ceil date' },
  { label: 'round_date', type: 'function', info: 'Round date' },
  { label: 'with_tz', type: 'function', info: 'Change tz' },
  { label: 'force_tz', type: 'function', info: 'Force tz' },
  // purrr
  { label: 'map', type: 'function', info: 'purrr map' },
  { label: 'map_lgl', type: 'function', info: 'map logical' },
  { label: 'map_int', type: 'function', info: 'map integer' },
  { label: 'map_dbl', type: 'function', info: 'map double' },
  { label: 'map_chr', type: 'function', info: 'map char' },
  { label: 'map_vec', type: 'function', info: 'map vec' },
  { label: 'map_df', type: 'function', info: 'map -> df' },
  { label: 'map_dfr', type: 'function', info: 'map -> rows' },
  { label: 'map_dfc', type: 'function', info: 'map -> cols' },
  { label: 'map2', type: 'function', info: 'Map 2 lists' },
  { label: 'map2_lgl', type: 'function', info: 'map2 logical' },
  { label: 'map2_int', type: 'function', info: 'map2 integer' },
  { label: 'map2_dbl', type: 'function', info: 'map2 double' },
  { label: 'map2_chr', type: 'function', info: 'map2 char' },
  { label: 'pmap', type: 'function', info: 'Parallel map' },
  { label: 'pmap_lgl', type: 'function', info: 'pmap logical' },
  { label: 'pmap_dbl', type: 'function', info: 'pmap double' },
  { label: 'pmap_chr', type: 'function', info: 'pmap char' },
  { label: 'imap', type: 'function', info: 'Indexed map' },
  { label: 'walk', type: 'function', info: 'Walk side effects' },
  { label: 'walk2', type: 'function', info: 'walk 2' },
  { label: 'pwalk', type: 'function', info: 'parallel walk' },
  { label: 'iwalk', type: 'function', info: 'indexed walk' },
  { label: 'reduce', type: 'function', info: 'purrr reduce' },
  { label: 'reduce2', type: 'function', info: 'reduce 2' },
  { label: 'reduce_right', type: 'function', info: 'reduce right' },
  { label: 'accumulate', type: 'function', info: 'Running reduce' },
  { label: 'accumulate2', type: 'function', info: 'Running 2' },
  { label: 'keep', type: 'function', info: 'Keep by pred' },
  { label: 'discard', type: 'function', info: 'Discard by pred' },
  { label: 'every', type: 'function', info: 'All match' },
  { label: 'some', type: 'function', info: 'Any match' },
  { label: 'none', type: 'function', info: 'None match' },
  { label: 'detect', type: 'function', info: 'Find first' },
  { label: 'detect_index', type: 'function', info: 'Find idx' },
  { label: 'compact', type: 'function', info: 'Drop NULLs' },
  { label: 'flatten', type: 'function', info: 'Flatten list' },
  { label: 'flatten_lgl', type: 'function', info: 'Flatten logical' },
  { label: 'flatten_int', type: 'function', info: 'Flatten integer' },
  { label: 'flatten_dbl', type: 'function', info: 'Flatten double' },
  { label: 'flatten_chr', type: 'function', info: 'Flatten char' },
  { label: 'flatten_df', type: 'function', info: 'Flatten df' },
  { label: 'pluck', type: 'function', info: 'Pluck element' },
  { label: 'chuck', type: 'function', info: 'Chuck element' },
  { label: 'safely', type: 'function', info: 'Safe wrapper' },
  { label: 'possibly', type: 'function', info: 'Possibly wrapper' },
  { label: 'quietly', type: 'function', info: 'Quiet wrapper' },
  { label: 'insistently', type: 'function', info: 'Retry wrapper' },
  { label: 'partial', type: 'function', info: 'Partial application' },
  { label: 'lift', type: 'function', info: 'Lift func' },
  { label: 'compose', type: 'function', info: 'Compose functions' },
  { label: 'negate', type: 'function', info: 'Negate pred' },
  { label: 'as_mapper', type: 'function', info: 'Coerce mapper' },
  { label: 'transpose', type: 'function', info: 'Transpose list' },
  { label: 'list_modify', type: 'function', info: 'Modify list' },
  { label: 'list_flatten', type: 'function', info: 'Flatten list (v1)' },
  { label: 'list_rbind', type: 'function', info: 'Rbind list' },
  { label: 'list_cbind', type: 'function', info: 'Cbind list' },
  { label: 'list_transpose', type: 'function', info: 'Transpose' },
  { label: 'list_assign', type: 'function', info: 'Assign list' },
  // ggplot2
  { label: 'ggplot', type: 'function', info: 'ggplot init' },
  { label: 'aes', type: 'function', info: 'Aesthetic mapping' },
  { label: 'labs', type: 'function', info: 'Axis/title labels' },
  { label: 'xlab', type: 'function', info: 'X label' },
  { label: 'ylab', type: 'function', info: 'Y label' },
  { label: 'ggtitle', type: 'function', info: 'Plot title' },
  { label: 'xlim', type: 'function', info: 'X limits' },
  { label: 'ylim', type: 'function', info: 'Y limits' },
  { label: 'lims', type: 'function', info: 'Axis limits' },
  { label: 'guides', type: 'function', info: 'Guide config' },
  { label: 'guide_legend', type: 'function', info: 'Legend guide' },
  { label: 'guide_colorbar', type: 'function', info: 'Colorbar guide' },
  { label: 'guide_colourbar', type: 'function', info: 'Colorbar guide (UK)' },
  { label: 'guide_axis', type: 'function', info: 'Axis guide' },
  { label: 'guide_none', type: 'function', info: 'No guide' },
  // geoms
  { label: 'geom_point', type: 'function', info: 'Scatter points' },
  { label: 'geom_line', type: 'function', info: 'Line plot' },
  { label: 'geom_path', type: 'function', info: 'Path plot' },
  { label: 'geom_bar', type: 'function', info: 'Bar chart' },
  { label: 'geom_col', type: 'function', info: 'Col chart' },
  { label: 'geom_histogram', type: 'function', info: 'Histogram' },
  { label: 'geom_density', type: 'function', info: 'Density' },
  { label: 'geom_boxplot', type: 'function', info: 'Boxplot' },
  { label: 'geom_violin', type: 'function', info: 'Violin plot' },
  { label: 'geom_jitter', type: 'function', info: 'Jittered points' },
  { label: 'geom_smooth', type: 'function', info: 'Smoother' },
  { label: 'geom_abline', type: 'function', info: 'a+bx line' },
  { label: 'geom_hline', type: 'function', info: 'Horizontal line' },
  { label: 'geom_vline', type: 'function', info: 'Vertical line' },
  { label: 'geom_text', type: 'function', info: 'Text annotation' },
  { label: 'geom_label', type: 'function', info: 'Label annotation' },
  { label: 'geom_area', type: 'function', info: 'Area chart' },
  { label: 'geom_ribbon', type: 'function', info: 'Ribbon' },
  { label: 'geom_errorbar', type: 'function', info: 'Error bars' },
  { label: 'geom_errorbarh', type: 'function', info: 'Horiz errorbars' },
  { label: 'geom_linerange', type: 'function', info: 'Line range' },
  { label: 'geom_pointrange', type: 'function', info: 'Point range' },
  { label: 'geom_crossbar', type: 'function', info: 'Crossbar' },
  { label: 'geom_step', type: 'function', info: 'Step function' },
  { label: 'geom_polygon', type: 'function', info: 'Polygon' },
  { label: 'geom_rect', type: 'function', info: 'Rectangle' },
  { label: 'geom_tile', type: 'function', info: 'Heatmap tile' },
  { label: 'geom_raster', type: 'function', info: 'Raster heatmap' },
  { label: 'geom_bin2d', type: 'function', info: '2D bin' },
  { label: 'geom_hex', type: 'function', info: 'Hex bin' },
  { label: 'geom_contour', type: 'function', info: 'Contours' },
  { label: 'geom_contour_filled', type: 'function', info: 'Filled contours' },
  { label: 'geom_density_2d', type: 'function', info: '2D density' },
  { label: 'geom_density_2d_filled', type: 'function', info: 'Filled 2D density' },
  { label: 'geom_freqpoly', type: 'function', info: 'Frequency poly' },
  { label: 'geom_dotplot', type: 'function', info: 'Dot plot' },
  { label: 'geom_map', type: 'function', info: 'Polygon map' },
  { label: 'geom_sf', type: 'function', info: 'Simple features' },
  { label: 'geom_segment', type: 'function', info: 'Line segments' },
  { label: 'geom_curve', type: 'function', info: 'Curved segments' },
  { label: 'geom_qq', type: 'function', info: 'QQ plot' },
  { label: 'geom_qq_line', type: 'function', info: 'QQ line' },
  { label: 'geom_function', type: 'function', info: 'Function line' },
  { label: 'geom_blank', type: 'function', info: 'Blank geom' },
  { label: 'geom_spoke', type: 'function', info: 'Polar spoke' },
  { label: 'geom_rug', type: 'function', info: 'Rug marks' },
  { label: 'geom_count', type: 'function', info: 'Count points' },
  { label: 'geom_quantile', type: 'function', info: 'Quantile lines' },
  // stats
  { label: 'stat_smooth', type: 'function', info: 'Smooth stat' },
  { label: 'stat_summary', type: 'function', info: 'Summary stat' },
  { label: 'stat_density', type: 'function', info: 'Density stat' },
  { label: 'stat_bin', type: 'function', info: 'Bin stat' },
  { label: 'stat_boxplot', type: 'function', info: 'Boxplot stat' },
  { label: 'stat_count', type: 'function', info: 'Count stat' },
  { label: 'stat_ecdf', type: 'function', info: 'ECDF stat' },
  { label: 'stat_function', type: 'function', info: 'Function stat' },
  { label: 'stat_identity', type: 'function', info: 'Identity stat' },
  { label: 'stat_qq', type: 'function', info: 'QQ stat' },
  { label: 'stat_quantile', type: 'function', info: 'Quantile stat' },
  // scales
  { label: 'scale_x_continuous', type: 'function', info: 'X continuous' },
  { label: 'scale_y_continuous', type: 'function', info: 'Y continuous' },
  { label: 'scale_x_discrete', type: 'function', info: 'X discrete' },
  { label: 'scale_y_discrete', type: 'function', info: 'Y discrete' },
  { label: 'scale_x_log10', type: 'function', info: 'X log10' },
  { label: 'scale_y_log10', type: 'function', info: 'Y log10' },
  { label: 'scale_x_sqrt', type: 'function', info: 'X sqrt' },
  { label: 'scale_y_sqrt', type: 'function', info: 'Y sqrt' },
  { label: 'scale_x_reverse', type: 'function', info: 'X reverse' },
  { label: 'scale_y_reverse', type: 'function', info: 'Y reverse' },
  { label: 'scale_x_date', type: 'function', info: 'X date' },
  { label: 'scale_y_date', type: 'function', info: 'Y date' },
  { label: 'scale_x_datetime', type: 'function', info: 'X datetime' },
  { label: 'scale_y_datetime', type: 'function', info: 'Y datetime' },
  { label: 'scale_x_time', type: 'function', info: 'X time' },
  { label: 'scale_y_time', type: 'function', info: 'Y time' },
  { label: 'scale_color_manual', type: 'function', info: 'Manual colors' },
  { label: 'scale_colour_manual', type: 'function', info: 'Manual colors (UK)' },
  { label: 'scale_fill_manual', type: 'function', info: 'Manual fill' },
  { label: 'scale_color_brewer', type: 'function', info: 'Brewer palette' },
  { label: 'scale_colour_brewer', type: 'function', info: 'Brewer (UK)' },
  { label: 'scale_fill_brewer', type: 'function', info: 'Brewer fill' },
  { label: 'scale_color_gradient', type: 'function', info: 'Color gradient' },
  { label: 'scale_fill_gradient', type: 'function', info: 'Fill gradient' },
  { label: 'scale_color_gradient2', type: 'function', info: 'Diverging grad' },
  { label: 'scale_fill_gradient2', type: 'function', info: 'Diverging fill' },
  { label: 'scale_color_gradientn', type: 'function', info: 'N-color grad' },
  { label: 'scale_fill_gradientn', type: 'function', info: 'N-color fill' },
  { label: 'scale_color_viridis_c', type: 'function', info: 'Viridis cont' },
  { label: 'scale_color_viridis_d', type: 'function', info: 'Viridis discrete' },
  { label: 'scale_fill_viridis_c', type: 'function', info: 'Viridis fill' },
  { label: 'scale_fill_viridis_d', type: 'function', info: 'Viridis fill disc' },
  { label: 'scale_size_continuous', type: 'function', info: 'Size continuous' },
  { label: 'scale_size_manual', type: 'function', info: 'Manual sizes' },
  { label: 'scale_size_area', type: 'function', info: 'Area-based size' },
  { label: 'scale_alpha_continuous', type: 'function', info: 'Alpha cont' },
  { label: 'scale_alpha_manual', type: 'function', info: 'Alpha manual' },
  { label: 'scale_shape_manual', type: 'function', info: 'Shape manual' },
  { label: 'scale_linetype_manual', type: 'function', info: 'Linetype manual' },
  { label: 'scale_linewidth_manual', type: 'function', info: 'Linewidth manual' },
  // coord
  { label: 'coord_cartesian', type: 'function', info: 'Cartesian coord' },
  { label: 'coord_fixed', type: 'function', info: 'Fixed aspect' },
  { label: 'coord_flip', type: 'function', info: 'Flip axes' },
  { label: 'coord_polar', type: 'function', info: 'Polar coord' },
  { label: 'coord_map', type: 'function', info: 'Map proj' },
  { label: 'coord_sf', type: 'function', info: 'sf coord' },
  { label: 'coord_trans', type: 'function', info: 'Axis transform' },
  { label: 'coord_quickmap', type: 'function', info: 'Quick map' },
  // facet
  { label: 'facet_wrap', type: 'function', info: 'Wrap facets' },
  { label: 'facet_grid', type: 'function', info: 'Grid facets' },
  { label: 'facet_null', type: 'function', info: 'No facets' },
  { label: 'vars', type: 'function', info: 'Facet vars' },
  // themes
  { label: 'theme', type: 'function', info: 'Custom theme' },
  { label: 'theme_gray', type: 'function', info: 'Gray theme' },
  { label: 'theme_bw', type: 'function', info: 'BW theme' },
  { label: 'theme_classic', type: 'function', info: 'Classic theme' },
  { label: 'theme_minimal', type: 'function', info: 'Minimal theme' },
  { label: 'theme_dark', type: 'function', info: 'Dark theme' },
  { label: 'theme_light', type: 'function', info: 'Light theme' },
  { label: 'theme_linedraw', type: 'function', info: 'Linedraw theme' },
  { label: 'theme_void', type: 'function', info: 'Void theme' },
  { label: 'theme_set', type: 'function', info: 'Set default theme' },
  { label: 'element_blank', type: 'function', info: 'Blank element' },
  { label: 'element_text', type: 'function', info: 'Text element' },
  { label: 'element_line', type: 'function', info: 'Line element' },
  { label: 'element_rect', type: 'function', info: 'Rect element' },
  { label: 'margin', type: 'function', info: 'Margin spec' },
  { label: 'unit', type: 'function', info: 'Grid unit' },
  // positions
  { label: 'position_dodge', type: 'function', info: 'Dodge position' },
  { label: 'position_stack', type: 'function', info: 'Stack position' },
  { label: 'position_jitter', type: 'function', info: 'Jitter position' },
  { label: 'position_jitterdodge', type: 'function', info: 'Jitter+dodge' },
  { label: 'position_identity', type: 'function', info: 'Identity pos' },
  { label: 'position_fill', type: 'function', info: 'Fill position' },
  { label: 'position_nudge', type: 'function', info: 'Nudge position' },
  // caret
  { label: 'train', type: 'function', info: 'caret train' },
  { label: 'trainControl', type: 'function', info: 'Train control' },
  { label: 'resample', type: 'function', info: 'Resample' },
  { label: 'predict', type: 'function', info: 'Predict' },
  { label: 'varImp', type: 'function', info: 'Var importance' },
  { label: 'confusionMatrix', type: 'function', info: 'Confusion matrix' },
  { label: 'createDataPartition', type: 'function', info: 'Data partition' },
  { label: 'createFolds', type: 'function', info: 'CV folds' },
  { label: 'createResamples', type: 'function', info: 'Resamples' },
  { label: 'createTimeSlices', type: 'function', info: 'Time slices' },
  // tidymodels - recipes
  { label: 'recipe', type: 'function', info: 'recipes recipe' },
  { label: 'step_center', type: 'function', info: 'Center vars' },
  { label: 'step_scale', type: 'function', info: 'Scale vars' },
  { label: 'step_normalize', type: 'function', info: 'Normalize' },
  { label: 'step_range', type: 'function', info: 'Range scale' },
  { label: 'step_dummy', type: 'function', info: 'Dummy vars' },
  { label: 'step_impute_mean', type: 'function', info: 'Mean impute' },
  { label: 'step_impute_median', type: 'function', info: 'Median impute' },
  { label: 'step_impute_knn', type: 'function', info: 'kNN impute' },
  { label: 'step_pca', type: 'function', info: 'PCA' },
  { label: 'step_ica', type: 'function', info: 'ICA' },
  { label: 'step_date', type: 'function', info: 'Date features' },
  { label: 'step_holiday', type: 'function', info: 'Holiday features' },
  { label: 'step_log', type: 'function', info: 'Log transform' },
  { label: 'step_BoxCox', type: 'function', info: 'BoxCox transform' },
  { label: 'step_YeoJohnson', type: 'function', info: 'YJ transform' },
  { label: 'step_naomit', type: 'function', info: 'Omit NAs' },
  { label: 'step_zv', type: 'function', info: 'Zero variance' },
  { label: 'step_nzv', type: 'function', info: 'Near-zero var' },
  { label: 'step_corr', type: 'function', info: 'Correlation filter' },
  { label: 'step_lincomb', type: 'function', info: 'Linear comb filter' },
  { label: 'step_interact', type: 'function', info: 'Interactions' },
  { label: 'prep', type: 'function', info: 'Prep recipe' },
  { label: 'bake', type: 'function', info: 'Bake recipe' },
  { label: 'juice', type: 'function', info: 'Juice recipe' },
  // parsnip
  { label: 'linear_reg', type: 'function', info: 'Linear reg' },
  { label: 'logistic_reg', type: 'function', info: 'Logistic reg' },
  { label: 'decision_tree', type: 'function', info: 'Decision tree' },
  { label: 'rand_forest', type: 'function', info: 'Random forest' },
  { label: 'boost_tree', type: 'function', info: 'Boosted tree' },
  { label: 'nearest_neighbor', type: 'function', info: 'kNN' },
  { label: 'svm_linear', type: 'function', info: 'Linear SVM' },
  { label: 'svm_rbf', type: 'function', info: 'RBF SVM' },
  { label: 'svm_poly', type: 'function', info: 'Poly SVM' },
  { label: 'mlp', type: 'function', info: 'MLP model' },
  { label: 'naive_Bayes', type: 'function', info: 'Naive Bayes' },
  { label: 'multinom_reg', type: 'function', info: 'Multinom reg' },
  { label: 'set_engine', type: 'function', info: 'Set engine' },
  { label: 'set_mode', type: 'function', info: 'Set mode' },
  { label: 'set_args', type: 'function', info: 'Set args' },
  { label: 'fit', type: 'function', info: 'Fit model' },
  { label: 'fit_xy', type: 'function', info: 'Fit x, y' },
  // yardstick
  { label: 'metrics', type: 'function', info: 'Standard metrics' },
  { label: 'metric_set', type: 'function', info: 'Metric set' },
  { label: 'rmse', type: 'function', info: 'RMSE' },
  { label: 'mae', type: 'function', info: 'MAE' },
  { label: 'mape', type: 'function', info: 'MAPE' },
  { label: 'rsq', type: 'function', info: 'R^2' },
  { label: 'accuracy', type: 'function', info: 'Accuracy' },
  { label: 'kap', type: 'function', info: 'Kappa' },
  { label: 'sens', type: 'function', info: 'Sensitivity' },
  { label: 'spec', type: 'function', info: 'Specificity' },
  { label: 'ppv', type: 'function', info: 'PPV' },
  { label: 'npv', type: 'function', info: 'NPV' },
  { label: 'f_meas', type: 'function', info: 'F-measure' },
  { label: 'precision', type: 'function', info: 'Precision' },
  { label: 'recall', type: 'function', info: 'Recall' },
  { label: 'mcc', type: 'function', info: 'Matthews corr' },
  { label: 'roc_auc', type: 'function', info: 'ROC AUC' },
  { label: 'pr_auc', type: 'function', info: 'PR AUC' },
  { label: 'gain_capture', type: 'function', info: 'Gain capture' },
  { label: 'mn_log_loss', type: 'function', info: 'Log loss' },
  // workflows
  { label: 'workflow', type: 'function', info: 'New workflow' },
  { label: 'add_model', type: 'function', info: 'Add model' },
  { label: 'add_recipe', type: 'function', info: 'Add recipe' },
  { label: 'add_formula', type: 'function', info: 'Add formula' },
  { label: 'last_fit', type: 'function', info: 'Last fit' },
  { label: 'fit_resamples', type: 'function', info: 'Fit resamples' },
  // tune
  { label: 'tune', type: 'function', info: 'Placeholder param' },
  { label: 'tune_grid', type: 'function', info: 'Grid search' },
  { label: 'tune_bayes', type: 'function', info: 'Bayes search' },
  { label: 'select_best', type: 'function', info: 'Best param' },
  { label: 'select_by_one_std_err', type: 'function', info: '1-SE rule' },
  { label: 'finalize_workflow', type: 'function', info: 'Finalize workflow' },
  { label: 'finalize_model', type: 'function', info: 'Finalize model' },
  { label: 'finalize_recipe', type: 'function', info: 'Finalize recipe' },
  { label: 'collect_metrics', type: 'function', info: 'Collect metrics' },
  { label: 'collect_predictions', type: 'function', info: 'Collect preds' },
  { label: 'grid_regular', type: 'function', info: 'Regular grid' },
  { label: 'grid_random', type: 'function', info: 'Random grid' },
  { label: 'grid_latin_hypercube', type: 'function', info: 'LHS grid' },
  // data.table
  { label: 'data.table', type: 'function', info: 'data.table ctor' },
  { label: 'fread', type: 'function', info: 'Fast read' },
  { label: 'fwrite', type: 'function', info: 'Fast write' },
  { label: 'setkey', type: 'function', info: 'Set key' },
  { label: 'setkeyv', type: 'function', info: 'Set key (vec)' },
  { label: 'setorder', type: 'function', info: 'Set order' },
  { label: 'setorderv', type: 'function', info: 'Set order (vec)' },
  { label: 'setnames', type: 'function', info: 'Set col names' },
  { label: 'setcolorder', type: 'function', info: 'Set col order' },
  { label: 'setDT', type: 'function', info: 'Set as DT' },
  { label: 'set', type: 'function', info: 'Fast set' },
  { label: 'foverlaps', type: 'function', info: 'Overlap join' },
  { label: 'rleid', type: 'function', info: 'RLE id' },
  { label: 'rleidv', type: 'function', info: 'RLE id (vec)' },
  { label: 'shift', type: 'function', info: 'Lag/lead' },
  { label: 'frollmean', type: 'function', info: 'Rolling mean' },
  { label: 'frollsum', type: 'function', info: 'Rolling sum' },
  { label: 'frollapply', type: 'function', info: 'Rolling apply' },
  { label: 'uniqueN', type: 'function', info: 'Unique count' },
  { label: '.N', type: 'variable', info: 'DT row count' },
  { label: '.SD', type: 'variable', info: 'Subset data' },
  { label: '.SDcols', type: 'variable', info: 'SD columns' },
  { label: '.GRP', type: 'variable', info: 'Group id' },
  { label: '.BY', type: 'variable', info: 'By vals' },
  { label: '.I', type: 'variable', info: 'Row idx' },
  // plumber
  { label: 'plumb', type: 'function', info: 'Plumb router' },
  { label: 'pr', type: 'function', info: 'New router' },
  { label: 'pr_get', type: 'function', info: 'GET handler' },
  { label: 'pr_post', type: 'function', info: 'POST handler' },
  { label: 'pr_put', type: 'function', info: 'PUT handler' },
  { label: 'pr_delete', type: 'function', info: 'DELETE handler' },
  { label: 'pr_run', type: 'function', info: 'Run router' },
  { label: 'pr_filter', type: 'function', info: 'Filter handler' },
  { label: 'pr_set_api_spec', type: 'function', info: 'Set API spec' },
  { label: 'pr_set_docs', type: 'function', info: 'Set docs' },
  // shiny
  { label: 'shinyApp', type: 'function', info: 'Shiny app' },
  { label: 'fluidPage', type: 'function', info: 'Fluid page' },
  { label: 'fixedPage', type: 'function', info: 'Fixed page' },
  { label: 'navbarPage', type: 'function', info: 'Navbar page' },
  { label: 'sidebarLayout', type: 'function', info: 'Sidebar layout' },
  { label: 'sidebarPanel', type: 'function', info: 'Sidebar panel' },
  { label: 'mainPanel', type: 'function', info: 'Main panel' },
  { label: 'fluidRow', type: 'function', info: 'Fluid row' },
  { label: 'column', type: 'function', info: 'Column' },
  { label: 'tabsetPanel', type: 'function', info: 'Tabset panel' },
  { label: 'tabPanel', type: 'function', info: 'Tab panel' },
  { label: 'wellPanel', type: 'function', info: 'Well panel' },
  { label: 'navbarMenu', type: 'function', info: 'Navbar menu' },
  { label: 'actionButton', type: 'function', info: 'Button input' },
  { label: 'submitButton', type: 'function', info: 'Submit button' },
  { label: 'textInput', type: 'function', info: 'Text input' },
  { label: 'textAreaInput', type: 'function', info: 'Text area' },
  { label: 'numericInput', type: 'function', info: 'Numeric input' },
  { label: 'selectInput', type: 'function', info: 'Select input' },
  { label: 'selectizeInput', type: 'function', info: 'Selectize input' },
  { label: 'checkboxInput', type: 'function', info: 'Checkbox' },
  { label: 'checkboxGroupInput', type: 'function', info: 'Checkbox group' },
  { label: 'radioButtons', type: 'function', info: 'Radio buttons' },
  { label: 'dateInput', type: 'function', info: 'Date input' },
  { label: 'dateRangeInput', type: 'function', info: 'Date range' },
  { label: 'fileInput', type: 'function', info: 'File input' },
  { label: 'sliderInput', type: 'function', info: 'Slider input' },
  { label: 'passwordInput', type: 'function', info: 'Password input' },
  { label: 'tagList', type: 'function', info: 'Tag list' },
  { label: 'renderPlot', type: 'function', info: 'Render plot' },
  { label: 'renderPlotly', type: 'function', info: 'Render plotly' },
  { label: 'renderTable', type: 'function', info: 'Render table' },
  { label: 'renderDataTable', type: 'function', info: 'DT render' },
  { label: 'renderPrint', type: 'function', info: 'Render print' },
  { label: 'renderText', type: 'function', info: 'Render text' },
  { label: 'renderUI', type: 'function', info: 'Render UI' },
  { label: 'renderImage', type: 'function', info: 'Render image' },
  { label: 'plotOutput', type: 'function', info: 'Plot output' },
  { label: 'tableOutput', type: 'function', info: 'Table output' },
  { label: 'dataTableOutput', type: 'function', info: 'DT output' },
  { label: 'verbatimTextOutput', type: 'function', info: 'Verbatim out' },
  { label: 'textOutput', type: 'function', info: 'Text output' },
  { label: 'uiOutput', type: 'function', info: 'UI output' },
  { label: 'imageOutput', type: 'function', info: 'Image output' },
  { label: 'reactive', type: 'function', info: 'Reactive value' },
  { label: 'reactiveVal', type: 'function', info: 'Reactive atom' },
  { label: 'reactiveValues', type: 'function', info: 'Reactive values' },
  { label: 'observe', type: 'function', info: 'Observe block' },
  { label: 'observeEvent', type: 'function', info: 'Observe event' },
  { label: 'eventReactive', type: 'function', info: 'Event reactive' },
  { label: 'isolate', type: 'function', info: 'Isolate reactivity' },
  { label: 'updateTextInput', type: 'function', info: 'Update text input' },
  { label: 'updateNumericInput', type: 'function', info: 'Update numeric' },
  { label: 'updateSelectInput', type: 'function', info: 'Update select' },
  { label: 'updateSliderInput', type: 'function', info: 'Update slider' },
  { label: 'showModal', type: 'function', info: 'Show modal' },
  { label: 'modalDialog', type: 'function', info: 'Modal dialog' },
  { label: 'removeModal', type: 'function', info: 'Remove modal' },
  { label: 'validate', type: 'function', info: 'Shiny validate' },
  { label: 'need', type: 'function', info: 'Shiny need' },
  { label: 'req', type: 'function', info: 'Shiny req' },
  { label: 'withProgress', type: 'function', info: 'Progress bar' },
  { label: 'incProgress', type: 'function', info: 'Inc progress' },
  { label: 'setProgress', type: 'function', info: 'Set progress' },
  { label: 'showNotification', type: 'function', info: 'Show notification' },
  { label: 'removeNotification', type: 'function', info: 'Remove notif' },
  { label: 'session', type: 'variable', info: 'Shiny session' },
  // stats / distributions
  { label: 'dnorm', type: 'function', info: 'Normal PDF' },
  { label: 'pnorm', type: 'function', info: 'Normal CDF' },
  { label: 'qnorm', type: 'function', info: 'Normal quantile' },
  { label: 'rnorm', type: 'function', info: 'Normal random' },
  { label: 'dbinom', type: 'function', info: 'Binomial PDF' },
  { label: 'pbinom', type: 'function', info: 'Binomial CDF' },
  { label: 'qbinom', type: 'function', info: 'Binomial quantile' },
  { label: 'rbinom', type: 'function', info: 'Binomial random' },
  { label: 'dpois', type: 'function', info: 'Poisson PDF' },
  { label: 'ppois', type: 'function', info: 'Poisson CDF' },
  { label: 'qpois', type: 'function', info: 'Poisson quantile' },
  { label: 'rpois', type: 'function', info: 'Poisson random' },
  { label: 'dunif', type: 'function', info: 'Uniform PDF' },
  { label: 'punif', type: 'function', info: 'Uniform CDF' },
  { label: 'qunif', type: 'function', info: 'Uniform quantile' },
  { label: 'runif', type: 'function', info: 'Uniform random' },
  { label: 'dexp', type: 'function', info: 'Exponential PDF' },
  { label: 'pexp', type: 'function', info: 'Exponential CDF' },
  { label: 'qexp', type: 'function', info: 'Exp quantile' },
  { label: 'rexp', type: 'function', info: 'Exp random' },
  { label: 'dgamma', type: 'function', info: 'Gamma PDF' },
  { label: 'pgamma', type: 'function', info: 'Gamma CDF' },
  { label: 'qgamma', type: 'function', info: 'Gamma quantile' },
  { label: 'rgamma', type: 'function', info: 'Gamma random' },
  { label: 'dbeta', type: 'function', info: 'Beta PDF' },
  { label: 'pbeta', type: 'function', info: 'Beta CDF' },
  { label: 'qbeta', type: 'function', info: 'Beta quantile' },
  { label: 'rbeta', type: 'function', info: 'Beta random' },
  { label: 'dchisq', type: 'function', info: 'Chi-square PDF' },
  { label: 'pchisq', type: 'function', info: 'Chi-square CDF' },
  { label: 'qchisq', type: 'function', info: 'Chi-square quantile' },
  { label: 'rchisq', type: 'function', info: 'Chi-square random' },
  { label: 'dt', type: 'function', info: 'Student t PDF' },
  { label: 'pt', type: 'function', info: 'Student t CDF' },
  { label: 'qt', type: 'function', info: 'Student t quantile' },
  { label: 'rt', type: 'function', info: 'Student t random' },
  { label: 'df', type: 'function', info: 'F-dist PDF' },
  { label: 'pf', type: 'function', info: 'F-dist CDF' },
  { label: 'qf', type: 'function', info: 'F-dist quantile' },
  { label: 'rf', type: 'function', info: 'F-dist random' },
  { label: 'dmvnorm', type: 'function', info: 'MVN PDF' },
  { label: 'rmvnorm', type: 'function', info: 'MVN random' },
  { label: 'lm', type: 'function', info: 'Linear model' },
  { label: 'glm', type: 'function', info: 'Generalized LM' },
  { label: 'aov', type: 'function', info: 'ANOVA' },
  { label: 'anova', type: 'function', info: 'ANOVA table' },
  { label: 'summary.lm', type: 'function', info: 'LM summary' },
  { label: 'cor.test', type: 'function', info: 'Correlation test' },
  { label: 't.test', type: 'function', info: 'Student t-test' },
  { label: 'chisq.test', type: 'function', info: 'Chi-square test' },
  { label: 'wilcox.test', type: 'function', info: 'Wilcoxon test' },
  { label: 'kruskal.test', type: 'function', info: 'Kruskal-Wallis' },
  { label: 'shapiro.test', type: 'function', info: 'Shapiro-Wilk' },
  { label: 'ks.test', type: 'function', info: 'KS test' },
  { label: 'binom.test', type: 'function', info: 'Binomial test' },
  { label: 'prop.test', type: 'function', info: 'Proportion test' },
  { label: 'fisher.test', type: 'function', info: 'Fisher exact' },
  { label: 'cor', type: 'function', info: 'Correlation' },
  { label: 'cov', type: 'function', info: 'Covariance' },
  { label: 'var', type: 'function', info: 'Variance' },
  { label: 'sd', type: 'function', info: 'Std deviation' },
  { label: 'median', type: 'function', info: 'Median' },
  { label: 'mean', type: 'function', info: 'Mean' },
  { label: 'sum', type: 'function', info: 'Sum' },
  { label: 'prod', type: 'function', info: 'Product' },
  { label: 'range', type: 'function', info: 'Min-max range' },
  { label: 'min', type: 'function', info: 'Minimum' },
  { label: 'max', type: 'function', info: 'Maximum' },
  { label: 'quantile', type: 'function', info: 'Quantiles' },
  { label: 'summary', type: 'function', info: 'Summary stats' },
  // utils & formulas
  { label: 'formula', type: 'function', info: 'Formula obj' },
  { label: 'update', type: 'function', info: 'Update model' },
  { label: 'step', type: 'function', info: 'Stepwise selection' },
  { label: 'predict.lm', type: 'function', info: 'LM predict' },
  { label: 'residuals', type: 'function', info: 'Residuals' },
  { label: 'fitted', type: 'function', info: 'Fitted vals' },
  { label: 'coef', type: 'function', info: 'Coefficients' },
  { label: 'confint', type: 'function', info: 'Conf intervals' },
  { label: 'vcov', type: 'function', info: 'Var-cov matrix' },
  // file IO
  { label: 'saveRDS', type: 'function', info: 'Save RDS' },
  { label: 'readRDS', type: 'function', info: 'Read RDS' },
  { label: 'save', type: 'function', info: 'Save objects' },
  { label: 'load', type: 'function', info: 'Load workspace' },
  { label: 'write.csv', type: 'function', info: 'Write CSV' },
  { label: 'read.csv', type: 'function', info: 'Read CSV' },
  { label: 'write.table', type: 'function', info: 'Write table' },
  { label: 'read.table', type: 'function', info: 'Read table' },
  { label: 'file.exists', type: 'function', info: 'File exists?' },
  { label: 'file.path', type: 'function', info: 'Build path' },
  { label: 'file.create', type: 'function', info: 'Create file' },
  { label: 'file.remove', type: 'function', info: 'Remove file' },
  { label: 'file.rename', type: 'function', info: 'Rename file' },
  { label: 'file.copy', type: 'function', info: 'Copy file' },
  { label: 'dir.create', type: 'function', info: 'Create dir' },
  { label: 'list.files', type: 'function', info: 'List files' },
  { label: 'list.dirs', type: 'function', info: 'List dirs' },
  // base R
  { label: 'ifelse', type: 'function', info: 'Base ifelse' },
  { label: 'switch', type: 'function', info: 'Switch' },
  { label: 'do.call', type: 'function', info: 'Call with args' },
  { label: 'Reduce', type: 'function', info: 'Base reduce' },
  { label: 'Map', type: 'function', info: 'Base map' },
  { label: 'Filter', type: 'function', info: 'Base filter' },
  { label: 'Find', type: 'function', info: 'Base find' },
  { label: 'Position', type: 'function', info: 'Find position' },
  { label: 'Negate', type: 'function', info: 'Negate pred' },
  { label: 'sapply', type: 'function', info: 'Simplify apply' },
  { label: 'lapply', type: 'function', info: 'List apply' },
  { label: 'vapply', type: 'function', info: 'Typed apply' },
  { label: 'mapply', type: 'function', info: 'Multi apply' },
  { label: 'tapply', type: 'function', info: 'Group apply' },
  { label: 'apply', type: 'function', info: 'Matrix apply' },
  { label: 'rapply', type: 'function', info: 'Recursive apply' },
  { label: 'eapply', type: 'function', info: 'Env apply' },
  // Pipes
  { label: '|>', type: 'operator', info: 'Native pipe' },
  { label: '%>%', type: 'operator', info: 'magrittr pipe' },
  { label: '%<>%', type: 'operator', info: 'Compound pipe' },
  { label: '%T>%', type: 'operator', info: 'Tee pipe' },
  { label: '%$%', type: 'operator', info: 'Exposition pipe' },
  { label: '%in%', type: 'operator', info: 'Set membership' },
  // Operators
  { label: '<-', type: 'operator', info: 'Assignment' },
  { label: '->', type: 'operator', info: 'Right assign' },
  { label: '<<-', type: 'operator', info: 'Global assign' },
  { label: ':=', type: 'operator', info: 'DT assignment' },
  // RMarkdown
  { label: 'knit', type: 'function', info: 'Knit Rmd' },
  { label: 'render', type: 'function', info: 'rmarkdown render' },
  { label: 'knit_child', type: 'function', info: 'Knit child' },
  { label: 'knit_print', type: 'function', info: 'Knit print' },
  { label: 'opts_chunk', type: 'function', info: 'Chunk opts' },
  { label: 'fig.width', type: 'option', info: 'Figure width' },
  { label: 'fig.height', type: 'option', info: 'Figure height' },
  { label: 'echo', type: 'option', info: 'Show code' },
  { label: 'eval', type: 'option', info: 'Evaluate code' },
  { label: 'include', type: 'option', info: 'Include output' },
  { label: 'message', type: 'option', info: 'Show messages' },
  { label: 'warning', type: 'option', info: 'Show warnings' },
  { label: 'error', type: 'option', info: 'Show errors' },
  { label: 'results', type: 'option', info: 'Results type' },
  // Misc
  { label: 'is.na', type: 'function', info: 'Is NA?' },
  { label: 'na.omit', type: 'function', info: 'Omit NAs' },
  { label: 'complete.cases', type: 'function', info: 'Complete rows' },
  { label: 'duplicated', type: 'function', info: 'Duplicates' },
  { label: 'unique', type: 'function', info: 'Unique vals' },
  { label: 'rev', type: 'function', info: 'Reverse' },
  { label: 'sort', type: 'function', info: 'Sort' },
  { label: 'order', type: 'function', info: 'Sort order' },
  { label: 'rank', type: 'function', info: 'Rank' },
  { label: 'seq', type: 'function', info: 'Sequence' },
  { label: 'seq_len', type: 'function', info: 'seq 1..n' },
  { label: 'seq_along', type: 'function', info: 'seq along vec' },
  { label: 'rep', type: 'function', info: 'Repeat' },
  { label: 'paste', type: 'function', info: 'Paste strings' },
  { label: 'paste0', type: 'function', info: 'Paste without sep' },
  { label: 'sprintf', type: 'function', info: 'printf style' },
  { label: 'format', type: 'function', info: 'Format object' },
  { label: 'formatC', type: 'function', info: 'C-style format' },
  // Additional
  { label: 'glue', type: 'function', info: 'glue template' },
  { label: 'glue_data', type: 'function', info: 'glue w/ env' },
  // More base R
  { label: 'abs', type: 'function', info: 'Absolute value' },
  { label: 'sqrt', type: 'function', info: 'Square root' },
  { label: 'exp', type: 'function', info: 'Exponential' },
  { label: 'log', type: 'function', info: 'Logarithm' },
  { label: 'log2', type: 'function', info: 'Log base 2' },
  { label: 'log10', type: 'function', info: 'Log base 10' },
  { label: 'log1p', type: 'function', info: 'Log(1+x)' },
  { label: 'expm1', type: 'function', info: 'exp(x)-1' },
  { label: 'sin', type: 'function', info: 'Sine' },
  { label: 'cos', type: 'function', info: 'Cosine' },
  { label: 'tan', type: 'function', info: 'Tangent' },
  { label: 'asin', type: 'function', info: 'Arcsine' },
  { label: 'acos', type: 'function', info: 'Arccosine' },
  { label: 'atan', type: 'function', info: 'Arctangent' },
  { label: 'atan2', type: 'function', info: 'atan2' },
  { label: 'sinh', type: 'function', info: 'Hyperbolic sine' },
  { label: 'cosh', type: 'function', info: 'Hyperbolic cos' },
  { label: 'tanh', type: 'function', info: 'Hyperbolic tan' },
  { label: 'ceiling', type: 'function', info: 'Ceiling' },
  { label: 'floor', type: 'function', info: 'Floor' },
  { label: 'round', type: 'function', info: 'Round' },
  { label: 'signif', type: 'function', info: 'Significant digits' },
  { label: 'trunc', type: 'function', info: 'Truncate' },
  { label: 'sign', type: 'function', info: 'Sign function' },
  { label: 'cumsum', type: 'function', info: 'Cumulative sum' },
  { label: 'cumprod', type: 'function', info: 'Cumulative prod' },
  { label: 'cummax', type: 'function', info: 'Cumulative max' },
  { label: 'cummin', type: 'function', info: 'Cumulative min' },
  { label: 'pmax', type: 'function', info: 'Parallel max' },
  { label: 'pmin', type: 'function', info: 'Parallel min' },
  { label: 'which', type: 'function', info: 'Indices where' },
  { label: 'which.max', type: 'function', info: 'Index of max' },
  { label: 'which.min', type: 'function', info: 'Index of min' },
  { label: 'any', type: 'function', info: 'Any true?' },
  { label: 'all', type: 'function', info: 'All true?' },
  { label: 'xor', type: 'function', info: 'XOR' },
  { label: 'isTRUE', type: 'function', info: 'Is TRUE?' },
  { label: 'isFALSE', type: 'function', info: 'Is FALSE?' },
  { label: 'identical', type: 'function', info: 'Exact equal' },
  { label: 'all.equal', type: 'function', info: 'Near equal' },
  { label: 'is.null', type: 'function', info: 'Is NULL?' },
  { label: 'is.numeric', type: 'function', info: 'Is numeric?' },
  { label: 'is.character', type: 'function', info: 'Is character?' },
  { label: 'is.logical', type: 'function', info: 'Is logical?' },
  { label: 'is.integer', type: 'function', info: 'Is integer?' },
  { label: 'is.double', type: 'function', info: 'Is double?' },
  { label: 'is.list', type: 'function', info: 'Is list?' },
  { label: 'is.vector', type: 'function', info: 'Is vector?' },
  { label: 'is.matrix', type: 'function', info: 'Is matrix?' },
  { label: 'is.array', type: 'function', info: 'Is array?' },
  { label: 'is.data.frame', type: 'function', info: 'Is df?' },
  { label: 'is.factor', type: 'function', info: 'Is factor?' },
  { label: 'is.function', type: 'function', info: 'Is function?' },
  { label: 'is.environment', type: 'function', info: 'Is env?' },
  { label: 'as.numeric', type: 'function', info: 'To numeric' },
  { label: 'as.integer', type: 'function', info: 'To integer' },
  { label: 'as.double', type: 'function', info: 'To double' },
  { label: 'as.character', type: 'function', info: 'To character' },
  { label: 'as.logical', type: 'function', info: 'To logical' },
  { label: 'as.factor', type: 'function', info: 'To factor' },
  { label: 'as.matrix', type: 'function', info: 'To matrix' },
  { label: 'as.data.frame', type: 'function', info: 'To df' },
  { label: 'as.list', type: 'function', info: 'To list' },
  { label: 'as.vector', type: 'function', info: 'To vector' },
  { label: 'as.Date', type: 'function', info: 'To Date' },
  { label: 'as.POSIXct', type: 'function', info: 'To POSIXct' },
  { label: 'as.POSIXlt', type: 'function', info: 'To POSIXlt' },
  { label: 'class', type: 'function', info: 'Class of' },
  { label: 'typeof', type: 'function', info: 'Type of' },
  { label: 'mode', type: 'function', info: 'Mode of' },
  { label: 'storage.mode', type: 'function', info: 'Storage mode' },
  { label: 'attributes', type: 'function', info: 'Object attrs' },
  { label: 'attr', type: 'function', info: 'Get attr' },
  { label: 'attr<-', type: 'function', info: 'Set attr' },
  { label: 'structure', type: 'function', info: 'Add attrs' },
  { label: 'length', type: 'function', info: 'Vec length' },
  { label: 'nrow', type: 'function', info: 'Num rows' },
  { label: 'ncol', type: 'function', info: 'Num cols' },
  { label: 'NROW', type: 'function', info: 'NROW' },
  { label: 'NCOL', type: 'function', info: 'NCOL' },
  { label: 'dim', type: 'function', info: 'Dimensions' },
  { label: 'names', type: 'function', info: 'Object names' },
  { label: 'rownames', type: 'function', info: 'Row names' },
  { label: 'colnames', type: 'function', info: 'Column names' },
  { label: 'dimnames', type: 'function', info: 'Dim names' },
  { label: 'setNames', type: 'function', info: 'Set names' },
  { label: 'head', type: 'function', info: 'First rows' },
  { label: 'tail', type: 'function', info: 'Last rows' },
  { label: 'str', type: 'function', info: 'Structure' },
  { label: 'print', type: 'function', info: 'Print' },
  { label: 'cat', type: 'function', info: 'Concatenate print' },
  { label: 'message', type: 'function', info: 'Print message' },
  { label: 'warning', type: 'function', info: 'Raise warning' },
  { label: 'stop', type: 'function', info: 'Raise error' },
  { label: 'stopifnot', type: 'function', info: 'Assert' },
  { label: 'tryCatch', type: 'function', info: 'Try/catch' },
  { label: 'try', type: 'function', info: 'Simple try' },
  { label: 'withCallingHandlers', type: 'function', info: 'Calling handlers' },
  { label: 'on.exit', type: 'function', info: 'Exit hook' },
  { label: 'invisible', type: 'function', info: 'Return invisible' },
  { label: 'Recall', type: 'function', info: 'Recursive call' },
  { label: 'match.arg', type: 'function', info: 'Match arg' },
  { label: 'match.call', type: 'function', info: 'Match call' },
  { label: 'sys.call', type: 'function', info: 'Sys call' },
  { label: 'parent.frame', type: 'function', info: 'Caller env' },
  { label: 'parent.env', type: 'function', info: 'Parent env' },
  { label: 'globalenv', type: 'function', info: 'Global env' },
  { label: 'baseenv', type: 'function', info: 'Base env' },
  { label: 'emptyenv', type: 'function', info: 'Empty env' },
  { label: 'new.env', type: 'function', info: 'New env' },
  { label: 'environment', type: 'function', info: 'Fn env' },
  { label: 'environmentName', type: 'function', info: 'Env name' },
  { label: 'env2list', type: 'function', info: 'Env to list' },
  { label: 'as.list', type: 'function', info: 'To list' },
  { label: 'list2env', type: 'function', info: 'List to env' },
  { label: 'ls', type: 'function', info: 'List objects' },
  { label: 'exists', type: 'function', info: 'Object exists?' },
  { label: 'get', type: 'function', info: 'Get by name' },
  { label: 'get0', type: 'function', info: 'Safer get' },
  { label: 'mget', type: 'function', info: 'Multi get' },
  { label: 'assign', type: 'function', info: 'Assign by name' },
  { label: 'rm', type: 'function', info: 'Remove object' },
  { label: 'remove', type: 'function', info: 'Remove object' },
  // Matrices / linear algebra
  { label: 'matrix', type: 'function', info: 'Build matrix' },
  { label: 'array', type: 'function', info: 'Build array' },
  { label: 'diag', type: 'function', info: 'Diagonal' },
  { label: 't', type: 'function', info: 'Transpose' },
  { label: 'solve', type: 'function', info: 'Solve linear' },
  { label: 'crossprod', type: 'function', info: 't(x) %*% y' },
  { label: 'tcrossprod', type: 'function', info: 'x %*% t(y)' },
  { label: 'det', type: 'function', info: 'Determinant' },
  { label: 'rowSums', type: 'function', info: 'Row sums' },
  { label: 'colSums', type: 'function', info: 'Col sums' },
  { label: 'rowMeans', type: 'function', info: 'Row means' },
  { label: 'colMeans', type: 'function', info: 'Col means' },
  { label: 'rbind', type: 'function', info: 'Bind rows' },
  { label: 'cbind', type: 'function', info: 'Bind cols' },
  { label: 'eigen', type: 'function', info: 'Eigendecomposition' },
  { label: 'svd', type: 'function', info: 'SVD' },
  { label: 'qr', type: 'function', info: 'QR decomp' },
  { label: 'chol', type: 'function', info: 'Cholesky' },
  { label: 'norm', type: 'function', info: 'Matrix norm' },
  { label: 'outer', type: 'function', info: 'Outer product' },
  { label: 'kronecker', type: 'function', info: 'Kronecker prod' },
  // Regex base
  { label: 'grep', type: 'function', info: 'Regex match' },
  { label: 'grepl', type: 'function', info: 'Regex match logical' },
  { label: 'regmatches', type: 'function', info: 'Extract matches' },
  { label: 'regexpr', type: 'function', info: 'Regex positions' },
  { label: 'gregexpr', type: 'function', info: 'Global regex pos' },
  { label: 'sub', type: 'function', info: 'Regex sub first' },
  { label: 'gsub', type: 'function', info: 'Regex sub all' },
  { label: 'strsplit', type: 'function', info: 'Split string' },
  { label: 'nchar', type: 'function', info: 'String length' },
  { label: 'substr', type: 'function', info: 'Substring' },
  { label: 'substring', type: 'function', info: 'Substring alt' },
  { label: 'toupper', type: 'function', info: 'Uppercase' },
  { label: 'tolower', type: 'function', info: 'Lowercase' },
  { label: 'chartr', type: 'function', info: 'Char translate' },
  { label: 'startsWith', type: 'function', info: 'Starts with' },
  { label: 'endsWith', type: 'function', info: 'Ends with' },
  { label: 'trimws', type: 'function', info: 'Trim whitespace' },
  // List utils
  { label: 'list', type: 'function', info: 'Make list' },
  { label: 'unlist', type: 'function', info: 'Unlist to vec' },
  { label: 'c', type: 'function', info: 'Concat values' },
  { label: 'append', type: 'function', info: 'Append to vec' },
  { label: 'Recall', type: 'function', info: 'Call self' },
  // DB / DBI
  { label: 'dbConnect', type: 'function', info: 'DBI connect' },
  { label: 'dbDisconnect', type: 'function', info: 'DBI disconnect' },
  { label: 'dbGetQuery', type: 'function', info: 'Run SELECT' },
  { label: 'dbSendQuery', type: 'function', info: 'Send SQL' },
  { label: 'dbFetch', type: 'function', info: 'Fetch rows' },
  { label: 'dbExecute', type: 'function', info: 'Exec SQL' },
  { label: 'dbWriteTable', type: 'function', info: 'Write table' },
  { label: 'dbReadTable', type: 'function', info: 'Read table' },
  { label: 'dbListTables', type: 'function', info: 'List tables' },
  { label: 'dbListFields', type: 'function', info: 'List fields' },
  { label: 'dbExistsTable', type: 'function', info: 'Table exists?' },
  { label: 'dbRemoveTable', type: 'function', info: 'Remove table' },
  { label: 'dbAppendTable', type: 'function', info: 'Append table' },
  { label: 'dbCreateTable', type: 'function', info: 'Create table' },
  { label: 'dbBegin', type: 'function', info: 'Begin tx' },
  { label: 'dbCommit', type: 'function', info: 'Commit tx' },
  { label: 'dbRollback', type: 'function', info: 'Rollback tx' },
  // RStudio API
  { label: 'rstudioapi.getActiveDocumentContext', type: 'function', info: 'Active doc' },
  { label: 'rstudioapi.insertText', type: 'function', info: 'Insert text' },
  { label: 'rstudioapi.showQuestion', type: 'function', info: 'Dialog' },
  { label: 'rstudioapi.getSourceEditorContext', type: 'function', info: 'Source editor' },
  // devtools
  { label: 'devtools::install_github', type: 'function', info: 'GitHub install' },
  { label: 'devtools::load_all', type: 'function', info: 'Load package' },
  { label: 'devtools::check', type: 'function', info: 'R CMD check' },
  { label: 'devtools::test', type: 'function', info: 'Run tests' },
  { label: 'devtools::document', type: 'function', info: 'Gen roxygen' },
  { label: 'devtools::build', type: 'function', info: 'Build package' },
  { label: 'devtools::install', type: 'function', info: 'Install local' },
  { label: 'devtools::create', type: 'function', info: 'Create pkg' },
  { label: 'devtools::use_package', type: 'function', info: 'Add dep' },
  { label: 'devtools::release', type: 'function', info: 'Release pkg' },
  // usethis
  { label: 'usethis::use_mit_license', type: 'function', info: 'Use MIT' },
  { label: 'usethis::use_testthat', type: 'function', info: 'Use testthat' },
  { label: 'usethis::use_git', type: 'function', info: 'Init git' },
  { label: 'usethis::use_github', type: 'function', info: 'Push to GitHub' },
  { label: 'usethis::use_readme_rmd', type: 'function', info: 'README.Rmd' },
  { label: 'usethis::use_news_md', type: 'function', info: 'NEWS.md' },
  { label: 'usethis::use_pkgdown', type: 'function', info: 'pkgdown site' },
  { label: 'usethis::use_github_actions', type: 'function', info: 'GHA workflow' },
  { label: 'usethis::use_r', type: 'function', info: 'Create R file' },
  { label: 'usethis::use_test', type: 'function', info: 'Create test file' },
  { label: 'usethis::use_data', type: 'function', info: 'Add data' },
  { label: 'usethis::use_vignette', type: 'function', info: 'New vignette' },
  { label: 'usethis::use_package', type: 'function', info: 'Add pkg dep' },
  // testthat
  { label: 'test_that', type: 'function', info: 'Describe test' },
  { label: 'expect_equal', type: 'function', info: 'Expect equal' },
  { label: 'expect_identical', type: 'function', info: 'Expect identical' },
  { label: 'expect_true', type: 'function', info: 'Expect TRUE' },
  { label: 'expect_false', type: 'function', info: 'Expect FALSE' },
  { label: 'expect_null', type: 'function', info: 'Expect NULL' },
  { label: 'expect_type', type: 'function', info: 'Expect type' },
  { label: 'expect_s3_class', type: 'function', info: 'Expect S3' },
  { label: 'expect_s4_class', type: 'function', info: 'Expect S4' },
  { label: 'expect_error', type: 'function', info: 'Expect error' },
  { label: 'expect_warning', type: 'function', info: 'Expect warning' },
  { label: 'expect_message', type: 'function', info: 'Expect message' },
  { label: 'expect_silent', type: 'function', info: 'Expect silent' },
  { label: 'expect_output', type: 'function', info: 'Expect output' },
  { label: 'expect_match', type: 'function', info: 'Expect match' },
  { label: 'expect_snapshot', type: 'function', info: 'Expect snapshot' },
  { label: 'expect_gt', type: 'function', info: 'Expect greater' },
  { label: 'expect_lt', type: 'function', info: 'Expect less' },
  { label: 'expect_length', type: 'function', info: 'Expect length' },
  { label: 'expect_named', type: 'function', info: 'Expect named' },
  { label: 'expect_no_error', type: 'function', info: 'Expect no error' },
  { label: 'expect_no_warning', type: 'function', info: 'Expect no warning' },
  { label: 'expect_no_message', type: 'function', info: 'Expect no msg' },
  { label: 'skip', type: 'function', info: 'Skip test' },
  { label: 'skip_if_not', type: 'function', info: 'Conditional skip' },
  { label: 'skip_on_cran', type: 'function', info: 'Skip on CRAN' },
  { label: 'skip_on_ci', type: 'function', info: 'Skip on CI' },
  { label: 'skip_on_os', type: 'function', info: 'Skip on OS' },
  // httr / httr2 / jsonlite / xml2
  { label: 'GET', type: 'function', info: 'httr GET' },
  { label: 'POST', type: 'function', info: 'httr POST' },
  { label: 'PUT', type: 'function', info: 'httr PUT' },
  { label: 'DELETE', type: 'function', info: 'httr DELETE' },
  { label: 'PATCH', type: 'function', info: 'httr PATCH' },
  { label: 'HEAD', type: 'function', info: 'httr HEAD' },
  { label: 'content', type: 'function', info: 'Extract content' },
  { label: 'status_code', type: 'function', info: 'HTTP status' },
  { label: 'add_headers', type: 'function', info: 'Add headers' },
  { label: 'authenticate', type: 'function', info: 'HTTP auth' },
  { label: 'config', type: 'function', info: 'httr config' },
  { label: 'set_cookies', type: 'function', info: 'Set cookies' },
  { label: 'upload_file', type: 'function', info: 'Upload file' },
  { label: 'request', type: 'function', info: 'httr2 request' },
  { label: 'req_perform', type: 'function', info: 'httr2 perform' },
  { label: 'req_url_path', type: 'function', info: 'httr2 URL path' },
  { label: 'req_url_query', type: 'function', info: 'httr2 query' },
  { label: 'req_method', type: 'function', info: 'httr2 method' },
  { label: 'req_headers', type: 'function', info: 'httr2 headers' },
  { label: 'req_body_json', type: 'function', info: 'httr2 JSON body' },
  { label: 'req_body_form', type: 'function', info: 'httr2 form body' },
  { label: 'req_auth_basic', type: 'function', info: 'httr2 basic auth' },
  { label: 'req_auth_bearer_token', type: 'function', info: 'httr2 bearer' },
  { label: 'resp_body_json', type: 'function', info: 'Resp JSON' },
  { label: 'resp_body_string', type: 'function', info: 'Resp string' },
  { label: 'resp_body_raw', type: 'function', info: 'Resp raw' },
  { label: 'resp_status', type: 'function', info: 'Resp status' },
  { label: 'resp_headers', type: 'function', info: 'Resp headers' },
  { label: 'toJSON', type: 'function', info: 'jsonlite toJSON' },
  { label: 'fromJSON', type: 'function', info: 'jsonlite fromJSON' },
  { label: 'read_json', type: 'function', info: 'Read JSON file' },
  { label: 'write_json', type: 'function', info: 'Write JSON file' },
  { label: 'read_xml', type: 'function', info: 'xml2 read' },
  { label: 'xml_text', type: 'function', info: 'xml2 text' },
  { label: 'xml_find_all', type: 'function', info: 'xml2 find all' },
  { label: 'xml_find_first', type: 'function', info: 'xml2 find first' },
  { label: 'xml_attrs', type: 'function', info: 'xml2 attrs' },
  { label: 'xml_attr', type: 'function', info: 'xml2 attr' },
  { label: 'xml_name', type: 'function', info: 'xml2 name' },
  { label: 'xml_children', type: 'function', info: 'xml2 children' },
  // survival / time series
  { label: 'Surv', type: 'function', info: 'Survival object' },
  { label: 'survfit', type: 'function', info: 'Survival fit' },
  { label: 'coxph', type: 'function', info: 'Cox regression' },
  { label: 'survdiff', type: 'function', info: 'Log-rank' },
  { label: 'ts', type: 'function', info: 'Time series' },
  { label: 'arima', type: 'function', info: 'ARIMA model' },
  { label: 'auto.arima', type: 'function', info: 'Auto ARIMA' },
  { label: 'forecast', type: 'function', info: 'Forecast' },
  { label: 'ets', type: 'function', info: 'ETS model' },
  { label: 'HoltWinters', type: 'function', info: 'Holt-Winters' },
  { label: 'decompose', type: 'function', info: 'TS decompose' },
  { label: 'stl', type: 'function', info: 'STL decompose' },
  { label: 'acf', type: 'function', info: 'ACF' },
  { label: 'pacf', type: 'function', info: 'PACF' },
  // Spatial / sf
  { label: 'st_read', type: 'function', info: 'sf read' },
  { label: 'st_write', type: 'function', info: 'sf write' },
  { label: 'st_as_sf', type: 'function', info: 'To sf' },
  { label: 'st_transform', type: 'function', info: 'Transform CRS' },
  { label: 'st_crs', type: 'function', info: 'CRS object' },
  { label: 'st_geometry', type: 'function', info: 'Geometry' },
  { label: 'st_buffer', type: 'function', info: 'Buffer geom' },
  { label: 'st_intersection', type: 'function', info: 'Intersection' },
  { label: 'st_union', type: 'function', info: 'Union' },
  { label: 'st_difference', type: 'function', info: 'Difference' },
  { label: 'st_sym_difference', type: 'function', info: 'Sym diff' },
  { label: 'st_contains', type: 'function', info: 'Contains?' },
  { label: 'st_within', type: 'function', info: 'Within?' },
  { label: 'st_touches', type: 'function', info: 'Touches?' },
  { label: 'st_intersects', type: 'function', info: 'Intersects?' },
  { label: 'st_distance', type: 'function', info: 'Distance' },
  { label: 'st_area', type: 'function', info: 'Area' },
  { label: 'st_length', type: 'function', info: 'Length' },
  { label: 'st_centroid', type: 'function', info: 'Centroid' },
  { label: 'st_bbox', type: 'function', info: 'Bounding box' },
  // rsample
  { label: 'initial_split', type: 'function', info: 'Train/test split' },
  { label: 'training', type: 'function', info: 'Training set' },
  { label: 'testing', type: 'function', info: 'Testing set' },
  { label: 'vfold_cv', type: 'function', info: 'V-fold CV' },
  { label: 'bootstraps', type: 'function', info: 'Bootstrap CV' },
  { label: 'mc_cv', type: 'function', info: 'Monte Carlo CV' },
  { label: 'loo_cv', type: 'function', info: 'LOO CV' },
  { label: 'group_vfold_cv', type: 'function', info: 'Group V-fold' },
  { label: 'nested_cv', type: 'function', info: 'Nested CV' },
  { label: 'rolling_origin', type: 'function', info: 'Time-rolling CV' },
  // broom
  { label: 'tidy', type: 'function', info: 'Tidy model' },
  { label: 'glance', type: 'function', info: 'Glance stats' },
  { label: 'augment', type: 'function', info: 'Augment data' },
  // recipes additional
  { label: 'step_downsample', type: 'function', info: 'Downsample' },
  { label: 'step_upsample', type: 'function', info: 'Upsample' },
  { label: 'step_smote', type: 'function', info: 'SMOTE' },
  { label: 'step_ns', type: 'function', info: 'Natural spline' },
  { label: 'step_bs', type: 'function', info: 'B-spline' },
  { label: 'step_poly', type: 'function', info: 'Polynomial' },
  { label: 'step_spline_b', type: 'function', info: 'B-spline' },
  { label: 'step_other', type: 'function', info: 'Collapse levels' },
  { label: 'step_novel', type: 'function', info: 'Handle novel' },
  { label: 'step_unknown', type: 'function', info: 'Unknown -> NA' },
  { label: 'step_mutate', type: 'function', info: 'Mutate step' },
  { label: 'step_rm', type: 'function', info: 'Remove vars' },
  { label: 'step_select', type: 'function', info: 'Select vars' },
  { label: 'step_filter', type: 'function', info: 'Filter rows' },
  { label: 'step_arrange', type: 'function', info: 'Arrange rows' },
  // parallel
  { label: 'makeCluster', type: 'function', info: 'Make cluster' },
  { label: 'stopCluster', type: 'function', info: 'Stop cluster' },
  { label: 'parLapply', type: 'function', info: 'Parallel lapply' },
  { label: 'parSapply', type: 'function', info: 'Parallel sapply' },
  { label: 'clusterExport', type: 'function', info: 'Export to cluster' },
  { label: 'clusterEvalQ', type: 'function', info: 'Eval on cluster' },
  { label: 'detectCores', type: 'function', info: 'CPU count' },
  { label: 'mclapply', type: 'function', info: 'Multicore lapply' },
  { label: 'mcparallel', type: 'function', info: 'Multicore fork' },
  { label: 'mcollect', type: 'function', info: 'Collect results' },
  // future / furrr
  { label: 'plan', type: 'function', info: 'future plan' },
  { label: 'future', type: 'function', info: 'future value' },
  { label: 'value', type: 'function', info: 'future value extractor' },
  { label: 'future_map', type: 'function', info: 'furrr map' },
  { label: 'future_map_dbl', type: 'function', info: 'furrr map_dbl' },
  { label: 'future_lapply', type: 'function', info: 'future_lapply' },
  { label: 'sequential', type: 'function', info: 'future sequential' },
  { label: 'multisession', type: 'function', info: 'future multisession' },
  { label: 'multicore', type: 'function', info: 'future multicore' },
  { label: 'cluster', type: 'function', info: 'future cluster' },
  // dplyr grouped helpers (more)
  { label: 'group_split', type: 'function', info: 'Split groups' },
  { label: 'group_keys', type: 'function', info: 'Group keys' },
  { label: 'group_data', type: 'function', info: 'Group data' },
  { label: 'group_vars', type: 'function', info: 'Group vars' },
  { label: 'group_trim', type: 'function', info: 'Trim groups' },
  { label: 'summarise_all', type: 'function', info: 'Summarise all' },
  { label: 'summarise_if', type: 'function', info: 'Summarise if' },
  { label: 'summarise_at', type: 'function', info: 'Summarise at' },
  { label: 'mutate_all', type: 'function', info: 'Mutate all' },
  { label: 'mutate_if', type: 'function', info: 'Mutate if' },
  { label: 'mutate_at', type: 'function', info: 'Mutate at' },
  { label: 'transmute_all', type: 'function', info: 'Transmute all' },
  { label: 'filter_all', type: 'function', info: 'Filter all' },
  { label: 'filter_if', type: 'function', info: 'Filter if' },
  { label: 'filter_at', type: 'function', info: 'Filter at' },
  { label: 'rename_all', type: 'function', info: 'Rename all' },
  { label: 'rename_if', type: 'function', info: 'Rename if' },
  { label: 'rename_at', type: 'function', info: 'Rename at' },
  { label: 'select_all', type: 'function', info: 'Select all' },
  { label: 'select_if', type: 'function', info: 'Select if' },
  { label: 'select_at', type: 'function', info: 'Select at' },
  // More ggplot
  { label: 'after_stat', type: 'function', info: 'ggplot after_stat' },
  { label: 'after_scale', type: 'function', info: 'ggplot after_scale' },
  { label: 'stage', type: 'function', info: 'ggplot stage' },
  { label: 'expansion', type: 'function', info: 'Scale expansion' },
  { label: 'expand_scale', type: 'function', info: 'Expand scale' },
  { label: 'label_wrap_gen', type: 'function', info: 'Wrap labels' },
  { label: 'label_both', type: 'function', info: 'Label both' },
  { label: 'label_bquote', type: 'function', info: 'Label expr' },
  { label: 'label_context', type: 'function', info: 'Context label' },
  { label: 'label_parsed', type: 'function', info: 'Parsed label' },
  { label: 'label_value', type: 'function', info: 'Value label' },
  { label: 'ggsave', type: 'function', info: 'Save ggplot' },
  { label: 'last_plot', type: 'function', info: 'Last ggplot' },
  { label: 'qplot', type: 'function', info: 'Quick plot' },
  { label: 'quickplot', type: 'function', info: 'Quick plot alt' },
  // arrange helpers
  { label: 'arrange_if', type: 'function', info: 'Arrange if' },
  { label: 'arrange_at', type: 'function', info: 'Arrange at' },
  // R6 OOP
  { label: 'R6::R6Class', type: 'function', info: 'R6 class' },
  { label: 'self', type: 'variable', info: 'R6 self' },
  { label: 'private', type: 'variable', info: 'R6 private' },
  // S4
  { label: 'setClass', type: 'function', info: 'S4 class' },
  { label: 'setGeneric', type: 'function', info: 'S4 generic' },
  { label: 'setMethod', type: 'function', info: 'S4 method' },
  { label: 'setValidity', type: 'function', info: 'S4 validity' },
  { label: 'new', type: 'function', info: 'S4 new' },
  { label: 'isVirtualClass', type: 'function', info: 'S4 virtual?' },
  { label: 'slot', type: 'function', info: 'S4 slot' },
  { label: 'slotNames', type: 'function', info: 'S4 slot names' },
  // Environment
  { label: 'Sys.getenv', type: 'function', info: 'Get env var' },
  { label: 'Sys.setenv', type: 'function', info: 'Set env var' },
  { label: 'Sys.unsetenv', type: 'function', info: 'Unset env var' },
  { label: 'Sys.time', type: 'function', info: 'Current time' },
  { label: 'Sys.Date', type: 'function', info: 'Current date' },
  { label: 'Sys.timezone', type: 'function', info: 'System tz' },
  { label: 'Sys.sleep', type: 'function', info: 'Sleep seconds' },
  { label: 'Sys.info', type: 'function', info: 'System info' },
  { label: 'Sys.which', type: 'function', info: 'Locate command' },
  { label: 'Sys.getlocale', type: 'function', info: 'Get locale' },
  { label: 'Sys.setlocale', type: 'function', info: 'Set locale' },
  // Misc
  { label: 'Sys.glob', type: 'function', info: 'File glob' },
  { label: 'Sys.chmod', type: 'function', info: 'chmod' },
  { label: 'Sys.umask', type: 'function', info: 'umask' },
  { label: 'normalizePath', type: 'function', info: 'Normalize path' },
  { label: 'path.expand', type: 'function', info: 'Expand ~' },
  { label: 'tools::file_ext', type: 'function', info: 'File ext' },
  { label: 'tools::file_path_sans_ext', type: 'function', info: 'Strip ext' },
  { label: 'tempfile', type: 'function', info: 'Temp file' },
  { label: 'tempdir', type: 'function', info: 'Temp dir' },
  { label: 'basename', type: 'function', info: 'File basename' },
  { label: 'dirname', type: 'function', info: 'Dir name' },
  { label: 'file.info', type: 'function', info: 'File info' },
  { label: 'file.size', type: 'function', info: 'File size' },
  { label: 'file.mtime', type: 'function', info: 'Modified time' },
  { label: 'file.ctime', type: 'function', info: 'Change time' },
  { label: 'file.access', type: 'function', info: 'Access check' },
  // More base
  { label: 'Reduce', type: 'function', info: 'Reduce fn' },
  { label: 'Find', type: 'function', info: 'Find first' },
  { label: 'Position', type: 'function', info: 'Position' },
  // Pipe defaults
  { label: 'identity', type: 'function', info: 'Identity fn' },
];
