// Completion entries for scala.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  // Keywords
  { label: 'val', type: 'keyword', info: 'Immutable value' },
  { label: 'var', type: 'keyword', info: 'Mutable variable' },
  { label: 'def', type: 'keyword', info: 'Define method' },
  { label: 'lazy', type: 'keyword', info: 'Lazy val' },
  { label: 'class', type: 'keyword', info: 'Class definition' },
  { label: 'object', type: 'keyword', info: 'Singleton object' },
  { label: 'trait', type: 'keyword', info: 'Trait' },
  { label: 'case class', type: 'keyword', info: 'Case class' },
  { label: 'case object', type: 'keyword', info: 'Case object' },
  { label: 'enum', type: 'keyword', info: 'Enum (Scala 3)' },
  { label: 'sealed', type: 'keyword', info: 'Sealed hierarchy' },
  { label: 'abstract', type: 'keyword', info: 'Abstract' },
  { label: 'final', type: 'keyword', info: 'Final modifier' },
  { label: 'override', type: 'keyword', info: 'Override member' },
  { label: 'extends', type: 'keyword', info: 'Extends class' },
  { label: 'with', type: 'keyword', info: 'Mix in trait' },
  { label: 'implicit', type: 'keyword', info: 'Implicit (S2)' },
  { label: 'given', type: 'keyword', info: 'Given (S3)' },
  { label: 'using', type: 'keyword', info: 'Using (S3)' },
  { label: 'inline', type: 'keyword', info: 'Inline (S3)' },
  { label: 'opaque', type: 'keyword', info: 'Opaque type (S3)' },
  { label: 'transparent', type: 'keyword', info: 'Transparent inline' },
  { label: 'new', type: 'keyword', info: 'Create instance' },
  { label: 'this', type: 'keyword', info: 'Self reference' },
  { label: 'super', type: 'keyword', info: 'Super reference' },
  { label: 'null', type: 'keyword', info: 'Null value' },
  { label: 'true', type: 'keyword', info: 'True' },
  { label: 'false', type: 'keyword', info: 'False' },
  { label: 'if', type: 'keyword', info: 'If expression' },
  { label: 'else', type: 'keyword', info: 'Else branch' },
  { label: 'match', type: 'keyword', info: 'Match expression' },
  { label: 'case', type: 'keyword', info: 'Case pattern' },
  { label: 'for', type: 'keyword', info: 'For comprehension' },
  { label: 'yield', type: 'keyword', info: 'Yield value' },
  { label: 'while', type: 'keyword', info: 'While loop' },
  { label: 'do', type: 'keyword', info: 'Do-while' },
  { label: 'try', type: 'keyword', info: 'Try block' },
  { label: 'catch', type: 'keyword', info: 'Catch exception' },
  { label: 'finally', type: 'keyword', info: 'Finally block' },
  { label: 'throw', type: 'keyword', info: 'Throw exception' },
  { label: 'return', type: 'keyword', info: 'Return value' },
  { label: 'import', type: 'keyword', info: 'Import' },
  { label: 'export', type: 'keyword', info: 'Export (S3)' },
  { label: 'package', type: 'keyword', info: 'Package decl' },
  { label: 'private', type: 'keyword', info: 'Private visibility' },
  { label: 'protected', type: 'keyword', info: 'Protected visibility' },
  { label: 'type', type: 'keyword', info: 'Type alias' },
  // Types
  { label: 'Int', type: 'type', info: 'Integer' },
  { label: 'Long', type: 'type', info: 'Long int' },
  { label: 'Double', type: 'type', info: 'Double' },
  { label: 'Float', type: 'type', info: 'Float' },
  { label: 'Boolean', type: 'type', info: 'Boolean' },
  { label: 'Char', type: 'type', info: 'Character' },
  { label: 'Byte', type: 'type', info: 'Byte' },
  { label: 'Short', type: 'type', info: 'Short int' },
  { label: 'Unit', type: 'type', info: 'Unit (void)' },
  { label: 'Any', type: 'type', info: 'Root type' },
  { label: 'AnyVal', type: 'type', info: 'Value type root' },
  { label: 'AnyRef', type: 'type', info: 'Reference root' },
  { label: 'Nothing', type: 'type', info: 'Bottom type' },
  { label: 'Null', type: 'type', info: 'Null type' },
  { label: 'String', type: 'type', info: 'String' },
  { label: 'Array[T]', type: 'type', info: 'Array' },
  { label: 'List[T]', type: 'type', info: 'Immutable list' },
  { label: 'Vector[T]', type: 'type', info: 'Immutable vector' },
  { label: 'Seq[T]', type: 'type', info: 'Sequence' },
  { label: 'Set[T]', type: 'type', info: 'Set' },
  { label: 'Map[K,V]', type: 'type', info: 'Map' },
  { label: 'Option[T]', type: 'type', info: 'Option value' },
  { label: 'Some', type: 'class', info: 'Some(x)' },
  { label: 'None', type: 'class', info: 'None' },
  { label: 'Either[L,R]', type: 'type', info: 'Either type' },
  { label: 'Left', type: 'class', info: 'Left(x)' },
  { label: 'Right', type: 'class', info: 'Right(x)' },
  { label: 'Try[T]', type: 'type', info: 'Try result' },
  { label: 'Success', type: 'class', info: 'Success(x)' },
  { label: 'Failure', type: 'class', info: 'Failure(e)' },
  { label: 'Future[T]', type: 'type', info: 'Future result' },
  { label: 'Tuple2[A,B]', type: 'type', info: 'Pair tuple' },
  // Common operations
  { label: 'map', type: 'method', info: 'Map collection' },
  { label: 'filter', type: 'method', info: 'Filter collection' },
  { label: 'flatMap', type: 'method', info: 'Flat map' },
  { label: 'fold', type: 'method', info: 'Fold' },
  { label: 'foldLeft', type: 'method', info: 'Fold left' },
  { label: 'foldRight', type: 'method', info: 'Fold right' },
  { label: 'reduce', type: 'method', info: 'Reduce' },
  { label: 'reduceLeft', type: 'method', info: 'Reduce left' },
  { label: 'reduceRight', type: 'method', info: 'Reduce right' },
  { label: 'collect', type: 'method', info: 'Collect matching' },
  { label: 'foreach', type: 'method', info: 'Iterate' },
  { label: 'groupBy', type: 'method', info: 'Group by key' },
  { label: 'zip', type: 'method', info: 'Zip collections' },
  { label: 'unzip', type: 'method', info: 'Unzip pairs' },
  { label: 'sortBy', type: 'method', info: 'Sort by key' },
  { label: 'sorted', type: 'method', info: 'Sort ascending' },
  { label: 'distinct', type: 'method', info: 'Unique elements' },
  { label: 'head', type: 'method', info: 'First element' },
  { label: 'headOption', type: 'method', info: 'First as Option' },
  { label: 'tail', type: 'method', info: 'Tail of list' },
  { label: 'last', type: 'method', info: 'Last element' },
  { label: 'isEmpty', type: 'method', info: 'Is empty?' },
  { label: 'nonEmpty', type: 'method', info: 'Is non-empty?' },
  { label: 'size', type: 'method', info: 'Size' },
  { label: 'length', type: 'method', info: 'Length' },
  { label: 'contains', type: 'method', info: 'Contains element' },
  { label: 'exists', type: 'method', info: 'Any match' },
  { label: 'forall', type: 'method', info: 'All match' },
  { label: 'getOrElse', type: 'method', info: 'Option default' },
  { label: 'orElse', type: 'method', info: 'Option fallback' },
  { label: 'toList', type: 'method', info: 'To List' },
  { label: 'toSeq', type: 'method', info: 'To Seq' },
  { label: 'toSet', type: 'method', info: 'To Set' },
  { label: 'toMap', type: 'method', info: 'To Map' },
  { label: 'toArray', type: 'method', info: 'To Array' },
  { label: 'mkString', type: 'method', info: 'Join to string' },
  // Common objects
  { label: 'println', type: 'function', info: 'Print line' },
  { label: 'print', type: 'function', info: 'Print' },
  { label: 'readLine', type: 'function', info: 'Read line' },
  { label: 'Console', type: 'module', info: 'Console' },
  { label: 'Math', type: 'module', info: 'Math' },
  { label: 'Predef', type: 'module', info: 'Predef' },
  { label: 'scala.util.Random', type: 'class', info: 'Random' },
  { label: 'Future.successful', type: 'function', info: 'Successful future' },
  { label: 'Future.failed', type: 'function', info: 'Failed future' },
  { label: 'Await.result', type: 'function', info: 'Await result' },
  { label: 'Await.ready', type: 'function', info: 'Await ready' },
  // Cats core typeclasses
  { label: 'Functor', type: 'type', info: 'Cats Functor' },
  { label: 'Applicative', type: 'type', info: 'Applicative' },
  { label: 'Monad', type: 'type', info: 'Cats Monad' },
  { label: 'Traverse', type: 'type', info: 'Traverse' },
  { label: 'Foldable', type: 'type', info: 'Foldable' },
  { label: 'Semigroup', type: 'type', info: 'Semigroup' },
  { label: 'Monoid', type: 'type', info: 'Monoid' },
  { label: 'Eq', type: 'type', info: 'Eq typeclass' },
  { label: 'Order', type: 'type', info: 'Order typeclass' },
  { label: 'Show', type: 'type', info: 'Show typeclass' },
  { label: 'Hash', type: 'type', info: 'Hash typeclass' },
  { label: 'Contravariant', type: 'type', info: 'Contravariant' },
  { label: 'Invariant', type: 'type', info: 'Invariant' },
  { label: 'NonEmptyList', type: 'type', info: 'NEL' },
  { label: 'NonEmptyVector', type: 'type', info: 'NEV' },
  { label: 'Validated', type: 'type', info: 'Validated' },
  { label: 'ValidatedNel', type: 'type', info: 'ValidatedNel' },
  { label: 'Ior', type: 'type', info: 'Ior either' },
  { label: 'Kleisli', type: 'type', info: 'Kleisli' },
  { label: 'Reader', type: 'type', info: 'Reader monad' },
  { label: 'Writer', type: 'type', info: 'Writer monad' },
  { label: 'State', type: 'type', info: 'State monad' },
  { label: 'EitherT', type: 'type', info: 'EitherT transformer' },
  { label: 'OptionT', type: 'type', info: 'OptionT transformer' },
  { label: 'StateT', type: 'type', info: 'StateT transformer' },
  { label: 'ReaderT', type: 'type', info: 'ReaderT transformer' },
  { label: 'WriterT', type: 'type', info: 'WriterT transformer' },
  { label: 'Free', type: 'type', info: 'Free monad' },
  { label: 'Cofree', type: 'type', info: 'Cofree comonad' },
  { label: 'FreeApplicative', type: 'type', info: 'Free applicative' },
  // cats-effect
  { label: 'IO', type: 'type', info: 'Cats IO' },
  { label: 'IOApp', type: 'type', info: 'IOApp main' },
  { label: 'IOApp.Simple', type: 'type', info: 'Simple IOApp' },
  { label: 'Resource', type: 'type', info: 'Resource' },
  { label: 'Ref', type: 'type', info: 'Ref atomic' },
  { label: 'Deferred', type: 'type', info: 'Deferred (promise)' },
  { label: 'Semaphore', type: 'type', info: 'Semaphore' },
  { label: 'MVar', type: 'type', info: 'MVar sync box' },
  { label: 'Fiber', type: 'type', info: 'Fiber' },
  { label: 'Outcome', type: 'type', info: 'Fiber outcome' },
  { label: 'Async', type: 'type', info: 'Async typeclass' },
  { label: 'Sync', type: 'type', info: 'Sync typeclass' },
  { label: 'Concurrent', type: 'type', info: 'Concurrent typeclass' },
  { label: 'Clock', type: 'type', info: 'Clock' },
  { label: 'Temporal', type: 'type', info: 'Temporal typeclass' },
  { label: 'Spawn', type: 'type', info: 'Spawn typeclass' },
  { label: 'MonadCancel', type: 'type', info: 'MonadCancel' },
  { label: 'Dispatcher', type: 'type', info: 'Dispatcher' },
  { label: 'Supervisor', type: 'type', info: 'Supervisor' },
  { label: 'Queue', type: 'type', info: 'IO Queue' },
  { label: 'Random', type: 'type', info: 'Random IO' },
  { label: 'Console', type: 'type', info: 'IO Console' },
  // fs2
  { label: 'Stream', type: 'type', info: 'fs2 Stream' },
  { label: 'Pipe', type: 'type', info: 'fs2 Pipe' },
  { label: 'Sink', type: 'type', info: 'fs2 Sink' },
  { label: 'Chunk', type: 'type', info: 'fs2 Chunk' },
  { label: 'Pull', type: 'type', info: 'fs2 Pull' },
  { label: 'Stream.emit', type: 'function', info: 'Stream emit one' },
  { label: 'Stream.emits', type: 'function', info: 'Stream emit many' },
  { label: 'Stream.eval', type: 'function', info: 'Stream eval IO' },
  { label: 'Stream.awakeEvery', type: 'function', info: 'Tick stream' },
  { label: 'Stream.resource', type: 'function', info: 'Stream from resource' },
  { label: 'Stream.repeat', type: 'function', info: 'Stream repeat' },
  { label: 'Stream.constant', type: 'function', info: 'Stream constant' },
  { label: 'Stream.iterate', type: 'function', info: 'Stream iterate' },
  { label: 'Stream.fromIterator', type: 'function', info: 'From iterator' },
  { label: 'Stream.fromQueueUnterminated', type: 'function', info: 'From queue' },
  // ZIO
  { label: 'ZIO', type: 'type', info: 'ZIO effect' },
  { label: 'UIO', type: 'type', info: 'Unfailable ZIO' },
  { label: 'URIO', type: 'type', info: 'ZIO with env' },
  { label: 'RIO', type: 'type', info: 'ZIO R, Throwable' },
  { label: 'Task', type: 'type', info: 'ZIO Task' },
  { label: 'ZLayer', type: 'type', info: 'ZIO layer' },
  { label: 'Has', type: 'type', info: 'ZIO Has (old)' },
  { label: 'ZEnvironment', type: 'type', info: 'ZIO environment' },
  { label: 'ZManaged', type: 'type', info: 'Managed resource' },
  { label: 'ZScope', type: 'type', info: 'ZIO scope' },
  { label: 'ZFiber', type: 'type', info: 'ZIO fiber' },
  { label: 'ZIO.succeed', type: 'function', info: 'ZIO succeed' },
  { label: 'ZIO.fail', type: 'function', info: 'ZIO fail' },
  { label: 'ZIO.attempt', type: 'function', info: 'ZIO attempt' },
  { label: 'ZIO.effect', type: 'function', info: 'ZIO effect' },
  { label: 'ZIO.die', type: 'function', info: 'ZIO die' },
  { label: 'ZIO.interrupt', type: 'function', info: 'ZIO interrupt' },
  { label: 'ZIO.sleep', type: 'function', info: 'ZIO sleep' },
  { label: 'ZIO.foreach', type: 'function', info: 'ZIO foreach' },
  { label: 'ZIO.foreachPar', type: 'function', info: 'ZIO foreachPar' },
  { label: 'ZIO.collectAll', type: 'function', info: 'ZIO collectAll' },
  { label: 'ZIO.collectAllPar', type: 'function', info: 'ZIO collectAllPar' },
  { label: 'ZIO.race', type: 'function', info: 'ZIO race' },
  { label: 'ZIO.raceAll', type: 'function', info: 'ZIO raceAll' },
  // Akka
  { label: 'ActorSystem', type: 'type', info: 'Akka actor system' },
  { label: 'Behaviors', type: 'type', info: 'Typed actor behaviors' },
  { label: 'ActorRef', type: 'type', info: 'Akka ActorRef' },
  { label: 'Props', type: 'type', info: 'Akka Props' },
  { label: 'Supervision', type: 'type', info: 'Supervision strategies' },
  { label: 'Routing', type: 'type', info: 'Router' },
  { label: 'Source', type: 'type', info: 'Akka source' },
  { label: 'Sink', type: 'type', info: 'Akka sink' },
  { label: 'Flow', type: 'type', info: 'Akka flow' },
  { label: 'GraphDSL', type: 'type', info: 'Akka graph DSL' },
  { label: 'RunnableGraph', type: 'type', info: 'Runnable graph' },
  { label: 'Cluster', type: 'type', info: 'Akka cluster' },
  { label: 'ClusterSingleton', type: 'type', info: 'Cluster singleton' },
  { label: 'ClusterSharding', type: 'type', info: 'Cluster sharding' },
  { label: 'PersistentActor', type: 'type', info: 'Persistent actor' },
  { label: 'EventSourcedBehavior', type: 'type', info: 'ES behavior' },
  { label: 'HttpApp', type: 'type', info: 'Akka HTTP app' },
  { label: 'Http', type: 'type', info: 'Akka HTTP' },
  { label: 'Route', type: 'type', info: 'Akka HTTP route' },
  { label: 'Directives', type: 'type', info: 'HTTP directives' },
  { label: 'Unmarshaller', type: 'type', info: 'Unmarshaller' },
  { label: 'Marshaller', type: 'type', info: 'Marshaller' },
  // Slick
  { label: 'TableQuery', type: 'type', info: 'Slick table query' },
  { label: 'Column', type: 'type', info: 'Slick column' },
  { label: 'ForeignKey', type: 'type', info: 'Slick FK' },
  { label: 'PrimaryKey', type: 'type', info: 'Slick PK' },
  { label: 'Database', type: 'type', info: 'Slick Database' },
  { label: 'DBIO', type: 'type', info: 'Slick DBIO' },
  { label: 'DBIOAction', type: 'type', info: 'Slick DBIOAction' },
  { label: 'Action', type: 'type', info: 'Slick Action' },
  { label: 'SqlStreamingAction', type: 'type', info: 'Streaming action' },
  { label: 'pinSession', type: 'function', info: 'Slick pinSession' },
  { label: 'transactionally', type: 'function', info: 'Slick tx' },
  // sbt keys
  { label: 'name', type: 'key', info: 'sbt project name' },
  { label: 'scalaVersion', type: 'key', info: 'Scala version' },
  { label: 'crossScalaVersions', type: 'key', info: 'Cross Scala' },
  { label: 'organization', type: 'key', info: 'Organization' },
  { label: 'libraryDependencies', type: 'key', info: 'Dependencies' },
  { label: 'resolvers', type: 'key', info: 'Resolvers' },
  { label: 'addCompilerPlugin', type: 'function', info: 'Compiler plugin' },
  { label: 'scalacOptions', type: 'key', info: 'scalac options' },
  { label: 'javacOptions', type: 'key', info: 'javac options' },
  { label: 'javaOptions', type: 'key', info: 'JVM options' },
  { label: 'fork', type: 'key', info: 'Fork JVM' },
  { label: 'mainClass', type: 'key', info: 'Main class' },
  { label: 'assembly', type: 'key', info: 'Assembly task' },
  { label: 'assemblyJarName', type: 'key', info: 'Assembly jar name' },
  { label: 'assemblyMergeStrategy', type: 'key', info: 'Assembly merge' },
  { label: 'Compile', type: 'scope', info: 'Compile scope' },
  { label: 'Test', type: 'scope', info: 'Test scope' },
  { label: 'Runtime', type: 'scope', info: 'Runtime scope' },
  { label: 'IntegrationTest', type: 'scope', info: 'IT scope' },
  { label: 'Global', type: 'scope', info: 'Global scope' },
  { label: 'ThisBuild', type: 'scope', info: 'ThisBuild scope' },
  { label: 'inThisBuild', type: 'function', info: 'In this build' },
  { label: 'enablePlugins', type: 'function', info: 'Enable plugins' },
  { label: 'project', type: 'function', info: 'Define project' },
  { label: 'aggregate', type: 'function', info: 'Aggregate' },
  { label: 'dependsOn', type: 'function', info: 'Depends on' },
  { label: 'settings', type: 'function', info: 'Project settings' },
  // Scala 3 features
  { label: 'given', type: 'keyword', info: 'Given instance' },
  { label: 'using', type: 'keyword', info: 'Context param' },
  { label: 'summon', type: 'function', info: 'Summon given' },
  { label: 'extension', type: 'keyword', info: 'Extension method' },
  { label: 'enum', type: 'keyword', info: 'Scala 3 enum' },
  { label: 'opaque', type: 'keyword', info: 'Opaque type' },
  { label: 'export', type: 'keyword', info: 'Export members' },
  { label: 'infix', type: 'keyword', info: 'Infix method' },
  { label: 'inline', type: 'keyword', info: 'Inline method' },
  { label: 'transparent', type: 'keyword', info: 'Transparent inline' },
  { label: 'derives', type: 'keyword', info: 'Derive typeclasses' },
  { label: 'Mirror', type: 'type', info: 'Mirror typeclass' },
  { label: 'Mirror.Of', type: 'type', info: 'Mirror.Of[T]' },
  { label: 'Mirror.ProductOf', type: 'type', info: 'Mirror product' },
  { label: 'Mirror.SumOf', type: 'type', info: 'Mirror sum' },
  { label: 'EmptyTuple', type: 'type', info: 'Empty tuple' },
  // Core
  { label: 'Option', type: 'type', info: 'Option' },
  { label: 'Some', type: 'type', info: 'Some' },
  { label: 'None', type: 'type', info: 'None' },
  { label: 'Either', type: 'type', info: 'Either' },
  { label: 'Left', type: 'type', info: 'Either Left' },
  { label: 'Right', type: 'type', info: 'Either Right' },
  { label: 'Try', type: 'type', info: 'Try' },
  { label: 'Success', type: 'type', info: 'Try Success' },
  { label: 'Failure', type: 'type', info: 'Try Failure' },
  { label: 'Nil', type: 'value', info: 'Empty list' },
  { label: 'Vector', type: 'type', info: 'Vector' },
  { label: 'Seq', type: 'type', info: 'Seq' },
  { label: 'Set', type: 'type', info: 'Set' },
  { label: 'Map', type: 'type', info: 'Map' },
  { label: 'Array', type: 'type', info: 'Array' },
  { label: 'IndexedSeq', type: 'type', info: 'IndexedSeq' },
  { label: 'Iterable', type: 'type', info: 'Iterable' },
  { label: 'Iterator', type: 'type', info: 'Iterator' },
  { label: 'LazyList', type: 'type', info: 'Lazy list' },
  { label: 'Range', type: 'type', info: 'Range' },
  { label: 'ArrayBuffer', type: 'type', info: 'ArrayBuffer' },
  { label: 'ListBuffer', type: 'type', info: 'ListBuffer' },
  { label: 'HashMap', type: 'type', info: 'HashMap' },
  { label: 'HashSet', type: 'type', info: 'HashSet' },
  { label: 'TreeMap', type: 'type', info: 'TreeMap' },
  { label: 'TreeSet', type: 'type', info: 'TreeSet' },
  { label: 'ListMap', type: 'type', info: 'ListMap' },
  { label: 'Queue', type: 'type', info: 'immutable.Queue' },
  { label: 'Stack', type: 'type', info: 'Stack' },
  { label: 'BitSet', type: 'type', info: 'BitSet' },
  // Collection methods
  { label: 'flatMap', type: 'method', info: 'Collection flatMap' },
  { label: 'filterNot', type: 'method', info: 'Filter not' },
  { label: 'collect', type: 'method', info: 'Collect pf' },
  { label: 'collectFirst', type: 'method', info: 'Collect first' },
  { label: 'exists', type: 'method', info: 'Any match' },
  { label: 'forall', type: 'method', info: 'All match' },
  { label: 'find', type: 'method', info: 'Find first' },
  { label: 'fold', type: 'method', info: 'Fold' },
  { label: 'foldLeft', type: 'method', info: 'Fold left' },
  { label: 'foldRight', type: 'method', info: 'Fold right' },
  { label: 'reduce', type: 'method', info: 'Reduce' },
  { label: 'reduceLeft', type: 'method', info: 'Reduce left' },
  { label: 'reduceRight', type: 'method', info: 'Reduce right' },
  { label: 'reduceOption', type: 'method', info: 'Reduce opt' },
  { label: 'scanLeft', type: 'method', info: 'Scan left' },
  { label: 'scanRight', type: 'method', info: 'Scan right' },
  { label: 'groupBy', type: 'method', info: 'Group by' },
  { label: 'groupMap', type: 'method', info: 'Group + map' },
  { label: 'groupMapReduce', type: 'method', info: 'Group+map+red' },
  { label: 'partition', type: 'method', info: 'Partition' },
  { label: 'span', type: 'method', info: 'Span by pred' },
  { label: 'splitAt', type: 'method', info: 'Split at idx' },
  { label: 'take', type: 'method', info: 'Take n' },
  { label: 'takeWhile', type: 'method', info: 'Take while' },
  { label: 'drop', type: 'method', info: 'Drop n' },
  { label: 'dropWhile', type: 'method', info: 'Drop while' },
  { label: 'slice', type: 'method', info: 'Slice' },
  { label: 'head', type: 'method', info: 'Head' },
  { label: 'headOption', type: 'method', info: 'Head option' },
  { label: 'tail', type: 'method', info: 'Tail' },
  { label: 'last', type: 'method', info: 'Last' },
  { label: 'lastOption', type: 'method', info: 'Last option' },
  { label: 'init', type: 'method', info: 'All but last' },
  { label: 'isEmpty', type: 'method', info: 'Is empty' },
  { label: 'nonEmpty', type: 'method', info: 'Non empty' },
  { label: 'size', type: 'method', info: 'Collection size' },
  { label: 'length', type: 'method', info: 'Collection length' },
  { label: 'count', type: 'method', info: 'Count matches' },
  { label: 'sum', type: 'method', info: 'Sum' },
  { label: 'product', type: 'method', info: 'Product' },
  { label: 'min', type: 'method', info: 'Min' },
  { label: 'minBy', type: 'method', info: 'Min by fn' },
  { label: 'minOption', type: 'method', info: 'Min option' },
  { label: 'max', type: 'method', info: 'Max' },
  { label: 'maxBy', type: 'method', info: 'Max by fn' },
  { label: 'maxOption', type: 'method', info: 'Max option' },
  { label: 'sorted', type: 'method', info: 'Sorted' },
  { label: 'sortBy', type: 'method', info: 'Sort by' },
  { label: 'sortWith', type: 'method', info: 'Sort with' },
  { label: 'reverse', type: 'method', info: 'Reverse' },
  { label: 'zip', type: 'method', info: 'Zip' },
  { label: 'zipAll', type: 'method', info: 'ZipAll' },
  { label: 'zipWithIndex', type: 'method', info: 'Zip w/ index' },
  { label: 'unzip', type: 'method', info: 'Unzip' },
  { label: 'unzip3', type: 'method', info: 'Unzip3' },
  { label: 'grouped', type: 'method', info: 'Grouped' },
  { label: 'sliding', type: 'method', info: 'Sliding window' },
  { label: 'mkString', type: 'method', info: 'Make string' },
  { label: 'toList', type: 'method', info: 'To list' },
  { label: 'toVector', type: 'method', info: 'To vector' },
  { label: 'toSeq', type: 'method', info: 'To seq' },
  { label: 'toSet', type: 'method', info: 'To set' },
  { label: 'toMap', type: 'method', info: 'To map' },
  { label: 'toArray', type: 'method', info: 'To array' },
  { label: 'toIterable', type: 'method', info: 'To iterable' },
  { label: 'distinct', type: 'method', info: 'Distinct elements' },
  { label: 'distinctBy', type: 'method', info: 'Distinct by' },
  { label: 'flatten', type: 'method', info: 'Flatten nested' },
  { label: 'transpose', type: 'method', info: 'Transpose' },
  { label: 'apply', type: 'method', info: 'Apply index' },
  { label: 'indices', type: 'method', info: 'Indices' },
  { label: 'indexOf', type: 'method', info: 'Index of' },
  { label: 'lastIndexOf', type: 'method', info: 'Last index of' },
  { label: 'contains', type: 'method', info: 'Contains' },
  { label: 'containsSlice', type: 'method', info: 'Contains slice' },
  { label: 'startsWith', type: 'method', info: 'Starts with' },
  { label: 'endsWith', type: 'method', info: 'Ends with' },
  { label: '++', type: 'operator', info: 'Concat' },
  { label: '::', type: 'operator', info: 'Cons' },
  { label: ':::', type: 'operator', info: 'List prepend' },
  { label: '+:', type: 'operator', info: 'Prepend seq' },
  { label: ':+', type: 'operator', info: 'Append seq' },
  // Pattern matching / keywords
  { label: 'match', type: 'keyword', info: 'Pattern match' },
  { label: 'case', type: 'keyword', info: 'Case clause' },
  { label: '_', type: 'pattern', info: 'Wildcard' },
  { label: 'yield', type: 'keyword', info: 'Yield' },
  { label: 'while', type: 'keyword', info: 'While' },
  { label: 'do', type: 'keyword', info: 'Do block' },
  { label: 'try', type: 'keyword', info: 'Try block' },
  { label: 'catch', type: 'keyword', info: 'Catch' },
  { label: 'finally', type: 'keyword', info: 'Finally' },
  { label: 'throw', type: 'keyword', info: 'Throw' },
  { label: 'return', type: 'keyword', info: 'Return' },
  { label: 'new', type: 'keyword', info: 'New instance' },
  { label: 'this', type: 'keyword', info: 'This reference' },
  { label: 'super', type: 'keyword', info: 'Super reference' },
  { label: 'object', type: 'keyword', info: 'Object decl' },
  { label: 'class', type: 'keyword', info: 'Class decl' },
  { label: 'abstract', type: 'keyword', info: 'Abstract' },
  { label: 'trait', type: 'keyword', info: 'Trait decl' },
  { label: 'sealed', type: 'keyword', info: 'Sealed' },
  { label: 'final', type: 'keyword', info: 'Final' },
  { label: 'override', type: 'keyword', info: 'Override' },
  { label: 'implicit', type: 'keyword', info: 'Implicit (Scala 2)' },
  { label: 'lazy', type: 'keyword', info: 'Lazy val' },
  { label: 'private', type: 'keyword', info: 'Private' },
  { label: 'protected', type: 'keyword', info: 'Protected' },
  { label: 'package', type: 'keyword', info: 'Package decl' },
  { label: 'with', type: 'keyword', info: 'With (traits)' },
  { label: 'extends', type: 'keyword', info: 'Extends' },
  // Base types
  { label: 'Int', type: 'type', info: 'Int type' },
  { label: 'Long', type: 'type', info: 'Long type' },
  { label: 'Short', type: 'type', info: 'Short type' },
  { label: 'Byte', type: 'type', info: 'Byte type' },
  { label: 'Float', type: 'type', info: 'Float type' },
  { label: 'Double', type: 'type', info: 'Double type' },
  { label: 'Boolean', type: 'type', info: 'Boolean type' },
  { label: 'Char', type: 'type', info: 'Char type' },
  { label: 'String', type: 'type', info: 'String type' },
  { label: 'Unit', type: 'type', info: 'Unit type' },
  { label: 'Nothing', type: 'type', info: 'Nothing type' },
  { label: 'Null', type: 'type', info: 'Null type' },
  { label: 'Any', type: 'type', info: 'Any type' },
  { label: 'AnyVal', type: 'type', info: 'AnyVal' },
  { label: 'AnyRef', type: 'type', info: 'AnyRef' },
  { label: 'BigInt', type: 'type', info: 'BigInt' },
  { label: 'BigDecimal', type: 'type', info: 'BigDecimal' },
  { label: 'Numeric', type: 'type', info: 'Numeric typeclass' },
  { label: 'Integral', type: 'type', info: 'Integral' },
  { label: 'Fractional', type: 'type', info: 'Fractional' },
  { label: 'Ordering', type: 'type', info: 'Ordering' },
  { label: 'Ordered', type: 'type', info: 'Ordered trait' },
  { label: 'Equiv', type: 'type', info: 'Equiv' },
  { label: 'Product', type: 'type', info: 'Product' },
  { label: 'Product1', type: 'type', info: 'Product1' },
  { label: 'Tuple2', type: 'type', info: 'Tuple2' },
  { label: 'Tuple3', type: 'type', info: 'Tuple3' },
  // Play Framework
  { label: 'Action', type: 'type', info: 'Play Action' },
  { label: 'Action.async', type: 'function', info: 'Async action' },
  { label: 'Results', type: 'type', info: 'Play Results' },
  { label: 'Ok', type: 'function', info: '200 Result' },
  { label: 'BadRequest', type: 'function', info: '400 Result' },
  { label: 'NotFound', type: 'function', info: '404 Result' },
  { label: 'InternalServerError', type: 'function', info: '500 Result' },
  { label: 'Redirect', type: 'function', info: '302 Result' },
  { label: 'Forbidden', type: 'function', info: '403 Result' },
  { label: 'Unauthorized', type: 'function', info: '401 Result' },
  { label: 'Controller', type: 'type', info: 'Play Controller' },
  { label: 'BaseController', type: 'type', info: 'Base controller' },
  { label: 'InjectedController', type: 'type', info: 'DI controller' },
  { label: 'AbstractController', type: 'type', info: 'Abstract controller' },
  { label: 'Request', type: 'type', info: 'Play Request' },
  { label: 'RequestHeader', type: 'type', info: 'Request header' },
  { label: 'Form', type: 'type', info: 'Play Form' },
  { label: 'mapping', type: 'function', info: 'Form mapping' },
  { label: 'text', type: 'function', info: 'Form text' },
  { label: 'number', type: 'function', info: 'Form number' },
  { label: 'email', type: 'function', info: 'Form email' },
  { label: 'boolean', type: 'function', info: 'Form boolean' },
  // http4s / tapir
  { label: 'HttpRoutes', type: 'type', info: 'http4s routes' },
  { label: 'Uri', type: 'type', info: 'http4s URI' },
  { label: 'Response', type: 'type', info: 'http4s response' },
  { label: 'Status', type: 'type', info: 'http4s status' },
  { label: 'Method', type: 'type', info: 'http4s method' },
  { label: 'EntityEncoder', type: 'type', info: 'Encoder' },
  { label: 'EntityDecoder', type: 'type', info: 'Decoder' },
  { label: 'endpoint', type: 'value', info: 'tapir endpoint' },
  { label: 'infallibleEndpoint', type: 'value', info: 'tapir inf ep' },
  { label: 'stringBody', type: 'function', info: 'tapir string body' },
  { label: 'jsonBody', type: 'function', info: 'tapir JSON body' },
  { label: 'path', type: 'function', info: 'tapir path' },
  { label: 'query', type: 'function', info: 'tapir query' },
  { label: 'header', type: 'function', info: 'tapir header' },
  { label: 'statusCode', type: 'function', info: 'tapir status' },
  // ScalaTest
  { label: 'AnyFunSuite', type: 'type', info: 'AnyFunSuite' },
  { label: 'AnyFlatSpec', type: 'type', info: 'AnyFlatSpec' },
  { label: 'AnyFreeSpec', type: 'type', info: 'AnyFreeSpec' },
  { label: 'AnyFunSpec', type: 'type', info: 'AnyFunSpec' },
  { label: 'AnyWordSpec', type: 'type', info: 'AnyWordSpec' },
  { label: 'AnyPropSpec', type: 'type', info: 'AnyPropSpec' },
  { label: 'Matchers', type: 'type', info: 'Should matchers' },
  { label: 'BeforeAndAfter', type: 'type', info: 'Before/after hooks' },
  { label: 'BeforeAndAfterAll', type: 'type', info: 'BeforeAndAfterAll' },
  { label: 'OptionValues', type: 'type', info: 'OptionValues' },
  { label: 'EitherValues', type: 'type', info: 'EitherValues' },
  { label: 'TryValues', type: 'type', info: 'TryValues' },
  { label: 'Inside', type: 'type', info: 'Inside matcher' },
  { label: 'Inspectors', type: 'type', info: 'Inspectors' },
  { label: 'test', type: 'function', info: 'ScalaTest test' },
  { label: 'should', type: 'function', info: 'Should matcher' },
  { label: 'must', type: 'function', info: 'Must matcher' },
  { label: 'shouldBe', type: 'function', info: 'Should be' },
  { label: 'shouldEqual', type: 'function', info: 'Should equal' },
  { label: 'shouldNot', type: 'function', info: 'Should not' },
  { label: 'assert', type: 'function', info: 'Assert' },
  { label: 'assertResult', type: 'function', info: 'Assert result' },
  { label: 'assertThrows', type: 'function', info: 'Assert throws' },
  { label: 'intercept', type: 'function', info: 'Intercept' },
  { label: 'forAll', type: 'function', info: 'Property forAll' },
  { label: 'forEvery', type: 'function', info: 'ForEvery' },
  { label: 'exactly', type: 'function', info: 'Exactly matcher' },
  { label: 'atLeast', type: 'function', info: 'At least matcher' },
  { label: 'atMost', type: 'function', info: 'At most matcher' },
  // munit
  { label: 'assertEquals', type: 'function', info: 'Assert equals' },
  { label: 'assertNotEquals', type: 'function', info: 'Assert not eq' },
  { label: 'fail', type: 'function', info: 'Fail test' },
  // circe / play-json
  { label: 'Json.parse', type: 'function', info: 'Parse JSON' },
  { label: 'Json.stringify', type: 'function', info: 'Stringify JSON' },
  { label: 'Json.toJson', type: 'function', info: 'To JSON' },
  { label: 'decode', type: 'function', info: 'circe decode' },
  { label: 'parser.parse', type: 'function', info: 'circe parse' },
  { label: 'Encoder', type: 'type', info: 'circe encoder' },
  { label: 'Decoder', type: 'type', info: 'circe decoder' },
  { label: 'Json', type: 'type', info: 'circe Json' },
  { label: 'HCursor', type: 'type', info: 'circe cursor' },
  { label: 'ACursor', type: 'type', info: 'circe acursor' },
  // Doobie
  { label: 'Transactor', type: 'type', info: 'Doobie transactor' },
  { label: 'ConnectionIO', type: 'type', info: 'Doobie connIO' },
  { label: 'Query', type: 'type', info: 'Doobie query' },
  { label: 'Update', type: 'type', info: 'Doobie update' },
  { label: 'Fragment', type: 'type', info: 'Doobie fragment' },
  { label: 'fr', type: 'function', info: 'Doobie fragment literal' },
  { label: 'sql', type: 'function', info: 'Doobie sql literal' },
  // Snippets
  { label: 'case-class', type: 'snippet', apply: 'case class ${Name}(${fields})', info: 'Case class' },
  { label: 'sealed-trait', type: 'snippet', apply: 'sealed trait ${Name}\n', info: 'Sealed trait' },
  { label: 'object-main', type: 'snippet', apply: 'object ${Name}:\n  def main(args: Array[String]): Unit =\n    ${body}\n', info: 'Main object' },
  { label: 'for-yield', type: 'snippet', apply: 'for\n  ${x} <- ${xs}\nyield ${expr}', info: 'For comprehension' },
  { label: 'match-case', type: 'snippet', apply: '${expr} match\n  case ${pat} => ${body}\n  case _ => ${default}', info: 'Match block' },
  // Common imports
  { label: 'import-cats', type: 'snippet', apply: 'import cats._\nimport cats.syntax.all._\nimport cats.implicits._', info: 'Cats imports' },
  { label: 'import-effect', type: 'snippet', apply: 'import cats.effect._\nimport cats.effect.syntax.all._', info: 'Cats-effect imports' },
  { label: 'import-zio', type: 'snippet', apply: 'import zio._', info: 'ZIO imports' },
  { label: 'import-fs2', type: 'snippet', apply: 'import fs2._\nimport fs2.concurrent._', info: 'fs2 imports' },
  // cats syntax
  { label: '.some', type: 'method', info: 'Some wrap' },
  { label: '.asRight', type: 'method', info: 'asRight' },
  { label: '.asLeft', type: 'method', info: 'asLeft' },
  { label: '.pure[F]', type: 'method', info: 'Pure wrap' },
  { label: '.liftTo', type: 'method', info: 'Lift to F' },
  { label: '.mapN', type: 'method', info: 'mapN over tuple' },
  { label: '.tupled', type: 'method', info: 'Tupled' },
  { label: '.sequence', type: 'method', info: 'Sequence' },
  { label: '.traverse', type: 'method', info: 'Traverse' },
  { label: '.sequenceU', type: 'method', info: 'Sequence unapply' },
  { label: '.parSequence', type: 'method', info: 'Parallel sequence' },
  { label: '.parTraverse', type: 'method', info: 'Parallel traverse' },
  { label: '.orEmpty', type: 'method', info: 'orEmpty' },
  { label: '.widen', type: 'method', info: 'Widen type' },
  { label: '|+|', type: 'operator', info: 'Combine' },
  { label: '===', type: 'operator', info: 'Cats eq' },
  { label: '=!=', type: 'operator', info: 'Cats neq' },
  { label: '>>', type: 'operator', info: 'Sequence w/ discard' },
  { label: '*>', type: 'operator', info: 'Applicative discard right' },
  { label: '<*', type: 'operator', info: 'Applicative discard left' },
  { label: '<*>', type: 'operator', info: 'Applicative apply' },
  { label: '<|>', type: 'operator', info: 'Alternative' },
  // IO ops
  { label: 'IO.pure', type: 'function', info: 'IO pure' },
  { label: 'IO.delay', type: 'function', info: 'IO delay' },
  { label: 'IO.raiseError', type: 'function', info: 'IO error' },
  { label: 'IO.async', type: 'function', info: 'IO async' },
  { label: 'IO.async_', type: 'function', info: 'IO async underscore' },
  { label: 'IO.blocking', type: 'function', info: 'IO blocking' },
  { label: 'IO.interruptible', type: 'function', info: 'IO interruptible' },
  { label: 'IO.sleep', type: 'function', info: 'IO sleep' },
  { label: 'IO.never', type: 'function', info: 'IO never' },
  { label: 'IO.unit', type: 'function', info: 'IO unit' },
  { label: 'IO.fromFuture', type: 'function', info: 'From Future' },
  { label: 'IO.fromOption', type: 'function', info: 'From Option' },
  { label: 'IO.fromEither', type: 'function', info: 'From Either' },
  { label: 'IO.fromTry', type: 'function', info: 'From Try' },
  { label: 'IO.realTime', type: 'function', info: 'Real time' },
  { label: 'IO.monotonic', type: 'function', info: 'Monotonic time' },
  { label: 'IO.canceled', type: 'function', info: 'Self cancel' },
  { label: 'IO.cede', type: 'function', info: 'IO cede' },
  { label: 'IO.uncancelable', type: 'function', info: 'Uncancelable' },
  { label: 'IO.race', type: 'function', info: 'Race IOs' },
  { label: 'IO.racePair', type: 'function', info: 'Race pair' },
  { label: 'IO.both', type: 'function', info: 'Both IO' },
  { label: 'IO.parMap2', type: 'function', info: 'parMap2' },
  { label: 'IO.parMap3', type: 'function', info: 'parMap3' },
  { label: 'IO.parSequenceN', type: 'function', info: 'Bounded par' },
  { label: 'IO.parTraverseN', type: 'function', info: 'Bounded parTraverse' },
  { label: 'IO.ref', type: 'function', info: 'IO ref' },
  { label: 'IO.deferred', type: 'function', info: 'IO deferred' },
  { label: 'IO.print', type: 'function', info: 'IO print' },
  { label: 'IO.println', type: 'function', info: 'IO println' },
  { label: 'IO.readLine', type: 'function', info: 'IO readLine' },
  // Resource
  { label: 'Resource.make', type: 'function', info: 'Make resource' },
  { label: 'Resource.pure', type: 'function', info: 'Pure resource' },
  { label: 'Resource.eval', type: 'function', info: 'Eval IO as res' },
  { label: 'Resource.liftK', type: 'function', info: 'Lift K' },
  { label: 'Resource.fromAutoCloseable', type: 'function', info: 'Auto closable' },
  { label: 'Resource.unit', type: 'function', info: 'Resource unit' },
  { label: 'Resource.canceled', type: 'function', info: 'Cancel resource' },
  { label: 'Resource.raiseError', type: 'function', info: 'Error resource' },
  // Ref
  { label: 'Ref.of', type: 'function', info: 'Create Ref' },
  { label: 'Ref.unsafe', type: 'function', info: 'Unsafe Ref' },
  { label: 'ref.get', type: 'method', info: 'Ref get' },
  { label: 'ref.set', type: 'method', info: 'Ref set' },
  { label: 'ref.update', type: 'method', info: 'Ref update' },
  { label: 'ref.modify', type: 'method', info: 'Ref modify' },
  { label: 'ref.getAndSet', type: 'method', info: 'Get and set' },
  { label: 'ref.getAndUpdate', type: 'method', info: 'Get and update' },
  // Stream ops
  { label: '.compile.drain', type: 'method', info: 'Stream drain' },
  { label: '.compile.toList', type: 'method', info: 'Stream to list' },
  { label: '.compile.toVector', type: 'method', info: 'Stream to vector' },
  { label: '.compile.last', type: 'method', info: 'Stream last' },
  { label: '.compile.count', type: 'method', info: 'Stream count' },
  { label: '.compile.foldMonoid', type: 'method', info: 'Fold monoid' },
  { label: '.compile.string', type: 'method', info: 'To string' },
  { label: '.through', type: 'method', info: 'Stream through pipe' },
  { label: '.pipe', type: 'method', info: 'Pipe stream' },
  { label: '.evalMap', type: 'method', info: 'Eval map' },
  { label: '.parEvalMap', type: 'method', info: 'Parallel evalMap' },
  { label: '.parJoin', type: 'method', info: 'parJoin streams' },
  { label: '.parJoinUnbounded', type: 'method', info: 'parJoin unbounded' },
  { label: '.mapChunks', type: 'method', info: 'Map chunks' },
  { label: '.chunkLimit', type: 'method', info: 'Chunk limit' },
  { label: '.chunkN', type: 'method', info: 'Chunks of N' },
  { label: '.evalTap', type: 'method', info: 'Eval tap' },
  { label: '.evalFilter', type: 'method', info: 'Eval filter' },
  // ZIO ops more
  { label: 'ZIO.ifZIO', type: 'function', info: 'If ZIO' },
  { label: 'ZIO.when', type: 'function', info: 'When' },
  { label: 'ZIO.unless', type: 'function', info: 'Unless' },
  { label: 'ZIO.loop', type: 'function', info: 'ZIO loop' },
  { label: 'ZIO.iterate', type: 'function', info: 'ZIO iterate' },
  { label: 'ZIO.bracket', type: 'function', info: 'ZIO bracket' },
  { label: 'ZIO.scoped', type: 'function', info: 'ZIO scoped' },
  { label: 'ZIO.acquireRelease', type: 'function', info: 'Acquire/release' },
  { label: 'ZIO.environment', type: 'function', info: 'ZIO env' },
  { label: 'ZIO.serviceWith', type: 'function', info: 'ZIO serviceWith' },
  { label: 'ZIO.serviceWithZIO', type: 'function', info: 'serviceWithZIO' },
  { label: 'ZIO.service', type: 'function', info: 'ZIO service' },
  { label: 'ZIO.debug', type: 'function', info: 'ZIO debug' },
  { label: 'ZIO.log', type: 'function', info: 'ZIO log' },
  { label: 'ZIO.logInfo', type: 'function', info: 'ZIO logInfo' },
  { label: 'ZIO.logDebug', type: 'function', info: 'ZIO logDebug' },
  { label: 'ZIO.logWarning', type: 'function', info: 'ZIO logWarn' },
  { label: 'ZIO.logError', type: 'function', info: 'ZIO logError' },
  { label: 'ZIO.acquireReleaseWith', type: 'function', info: 'AcquireReleaseWith' },
  { label: 'ZIO.mapBoth', type: 'function', info: 'Map both' },
  // Akka stream combinators
  { label: 'Source.single', type: 'function', info: 'Source single' },
  { label: 'Source.fromIterator', type: 'function', info: 'From iterator' },
  { label: 'Source.fromFuture', type: 'function', info: 'From future' },
  { label: 'Source.repeat', type: 'function', info: 'Repeat source' },
  { label: 'Source.cycle', type: 'function', info: 'Cycle source' },
  { label: 'Source.tick', type: 'function', info: 'Tick source' },
  { label: 'Source.queue', type: 'function', info: 'Queue source' },
  { label: 'Source.actorRef', type: 'function', info: 'Actor ref' },
  { label: 'Sink.foreach', type: 'function', info: 'Sink foreach' },
  { label: 'Sink.fold', type: 'function', info: 'Sink fold' },
  { label: 'Sink.ignore', type: 'function', info: 'Sink ignore' },
  { label: 'Sink.head', type: 'function', info: 'Sink head' },
  { label: 'Sink.seq', type: 'function', info: 'Sink seq' },
  { label: 'Flow.map', type: 'function', info: 'Flow map' },
  { label: 'Flow.mapAsync', type: 'function', info: 'Flow mapAsync' },
  { label: 'Flow.filter', type: 'function', info: 'Flow filter' },
  { label: 'Flow.grouped', type: 'function', info: 'Flow grouped' },
  { label: 'Flow.batch', type: 'function', info: 'Flow batch' },
  { label: 'Flow.throttle', type: 'function', info: 'Flow throttle' },
  { label: 'Flow.buffer', type: 'function', info: 'Flow buffer' },
  // Ammonite / REPL misc
  { label: 'println', type: 'function', info: 'Println' },
  { label: 'print', type: 'function', info: 'Print' },
  { label: 'readLine', type: 'function', info: 'Read line' },
  { label: 'readInt', type: 'function', info: 'Read int' },
  { label: 'readDouble', type: 'function', info: 'Read double' },
  // Actor typed behaviors
  { label: 'Behaviors.receive', type: 'function', info: 'Behaviors.receive' },
  { label: 'Behaviors.receiveMessage', type: 'function', info: 'Recv msg' },
  { label: 'Behaviors.setup', type: 'function', info: 'Behaviors.setup' },
  { label: 'Behaviors.stopped', type: 'function', info: 'Behaviors.stopped' },
  { label: 'Behaviors.same', type: 'function', info: 'Behaviors.same' },
  { label: 'Behaviors.empty', type: 'function', info: 'Behaviors.empty' },
  { label: 'Behaviors.ignore', type: 'function', info: 'Behaviors.ignore' },
  { label: 'Behaviors.supervise', type: 'function', info: 'Behaviors.supervise' },
  { label: 'Behaviors.withTimers', type: 'function', info: 'With timers' },
  { label: 'Behaviors.withStash', type: 'function', info: 'With stash' },
  // Scala 3 misc
  { label: 'quoted', type: 'keyword', info: 'Quoted (S3)' },
  { label: 'Expr', type: 'type', info: 'Scala 3 Expr' },
  { label: 'Type', type: 'type', info: 'Scala 3 Type' },
  { label: 'Quotes', type: 'type', info: 'Scala 3 Quotes' },
  // Slick Action helpers
  { label: 'DBIO.successful', type: 'function', info: 'Successful DBIO' },
  { label: 'DBIO.failed', type: 'function', info: 'Failed DBIO' },
  { label: 'DBIO.sequence', type: 'function', info: 'DBIO sequence' },
  { label: 'DBIO.from', type: 'function', info: 'DBIO from Future' },
  { label: 'DBIO.fold', type: 'function', info: 'DBIO fold' },
  { label: 'DBIO.successful', type: 'function', info: 'DBIO successful' },
  // SparkSQL / Scala Spark commons
  { label: 'SparkSession', type: 'type', info: 'Spark session' },
  { label: 'SparkContext', type: 'type', info: 'Spark context' },
  { label: 'SQLContext', type: 'type', info: 'SQL context' },
  { label: 'Dataset', type: 'type', info: 'Spark Dataset' },
  { label: 'DataFrame', type: 'type', info: 'Spark DataFrame' },
  { label: 'RDD', type: 'type', info: 'Spark RDD' },
  { label: 'Row', type: 'type', info: 'Spark Row' },
  { label: 'Column', type: 'type', info: 'Spark Column' },
  { label: 'col', type: 'function', info: 'Spark col()' },
  { label: 'lit', type: 'function', info: 'Spark lit()' },
  { label: 'expr', type: 'function', info: 'Spark expr()' },
  { label: 'array', type: 'function', info: 'Spark array()' },
  { label: 'struct', type: 'function', info: 'Spark struct()' },
  { label: 'udf', type: 'function', info: 'Spark udf()' },
  { label: 'when', type: 'function', info: 'Spark when()' },
  { label: 'otherwise', type: 'function', info: 'Spark otherwise()' },
  { label: 'explode', type: 'function', info: 'Spark explode()' },
  { label: 'desc', type: 'function', info: 'Spark desc()' },
  { label: 'asc', type: 'function', info: 'Spark asc()' },
  { label: 'window', type: 'function', info: 'Spark window()' },
  { label: 'row_number', type: 'function', info: 'Spark row_number()' },
  { label: 'rank', type: 'function', info: 'Spark rank()' },
  { label: 'dense_rank', type: 'function', info: 'Spark dense_rank()' },
  { label: 'collect_list', type: 'function', info: 'collect_list' },
  { label: 'collect_set', type: 'function', info: 'collect_set' },
  { label: 'concat', type: 'function', info: 'concat()' },
  { label: 'concat_ws', type: 'function', info: 'concat_ws()' },
  { label: 'split', type: 'function', info: 'Spark split()' },
  { label: 'trim', type: 'function', info: 'Spark trim()' },
  { label: 'upper', type: 'function', info: 'Spark upper()' },
  { label: 'lower', type: 'function', info: 'Spark lower()' },
  { label: 'date_format', type: 'function', info: 'Spark date_format' },
  { label: 'to_date', type: 'function', info: 'Spark to_date' },
  { label: 'to_timestamp', type: 'function', info: 'Spark to_timestamp' },
  { label: 'year', type: 'function', info: 'Spark year' },
  { label: 'month', type: 'function', info: 'Spark month' },
  { label: 'dayofmonth', type: 'function', info: 'Spark dayofmonth' },
  { label: 'sum', type: 'function', info: 'Spark sum' },
  { label: 'avg', type: 'function', info: 'Spark avg' },
  { label: 'count', type: 'function', info: 'Spark count' },
  { label: 'countDistinct', type: 'function', info: 'countDistinct' },
  { label: 'min', type: 'function', info: 'Spark min' },
  { label: 'max', type: 'function', info: 'Spark max' },
  // Scalameta / bloop
  { label: 'scalafmt', type: 'tool', info: 'scalafmt' },
  { label: 'scalafix', type: 'tool', info: 'scalafix' },
  { label: 'bloop', type: 'tool', info: 'bloop build tool' },
  // Common Scala idioms
  { label: 'require', type: 'function', info: 'Precondition' },
  { label: 'assume', type: 'function', info: 'Assume precondition' },
  { label: 'ensure', type: 'function', info: 'Postcondition' },
  { label: 'ensuring', type: 'function', info: 'ensuring postcond' },
  { label: 'classOf', type: 'keyword', info: 'Class of T' },
  { label: 'isInstanceOf', type: 'method', info: 'Type check' },
  { label: 'asInstanceOf', type: 'method', info: 'Type cast' },
  { label: 'getClass', type: 'method', info: 'Runtime class' },
  { label: 'hashCode', type: 'method', info: 'Hash code' },
  { label: 'equals', type: 'method', info: 'Equals' },
  { label: 'toString', type: 'method', info: 'To string' },
  { label: 'notify', type: 'method', info: 'notify()' },
  { label: 'notifyAll', type: 'method', info: 'notifyAll()' },
  { label: 'wait', type: 'method', info: 'wait()' },
  { label: 'synchronized', type: 'keyword', info: 'synchronized' },
  // Akka messaging
  { label: '!', type: 'operator', info: 'Fire and forget tell' },
  { label: '?', type: 'operator', info: 'Ask pattern' },
  { label: 'ask', type: 'function', info: 'Ask pattern' },
  { label: 'pipeTo', type: 'function', info: 'Pipe future' },
  // Additional typeclasses / utils
  { label: 'Endo', type: 'type', info: 'Endomorphism' },
  { label: 'Const', type: 'type', info: 'Const functor' },
  { label: 'Id', type: 'type', info: 'Identity monad' },
  { label: 'Nested', type: 'type', info: 'Nested functor' },
  { label: 'Coproduct', type: 'type', info: 'Coproduct' },
  { label: 'Yoneda', type: 'type', info: 'Yoneda embedding' },
  { label: 'Coyoneda', type: 'type', info: 'Coyoneda' },
  { label: 'Eval', type: 'type', info: 'Eval Lazy' },
  { label: 'Eval.always', type: 'function', info: 'Eval.always' },
  { label: 'Eval.later', type: 'function', info: 'Eval.later' },
  { label: 'Eval.now', type: 'function', info: 'Eval.now' },
  { label: 'Eval.defer', type: 'function', info: 'Eval.defer' },
  // Additional Akka typed
  { label: 'Receptionist', type: 'type', info: 'Receptionist' },
  { label: 'ServiceKey', type: 'type', info: 'ServiceKey' },
  { label: 'Routers', type: 'type', info: 'Routers' },
  { label: 'ActorContext', type: 'type', info: 'ActorContext' },
  { label: 'TimerScheduler', type: 'type', info: 'TimerScheduler' },
  { label: 'StashBuffer', type: 'type', info: 'StashBuffer' },
  // Additional core
  { label: 'Regex', type: 'type', info: 'Regex type' },
  { label: 'r', type: 'method', info: 'String.r regex' },
  { label: 'StringOps', type: 'type', info: 'StringOps' },
  { label: 'StringBuilder', type: 'type', info: 'StringBuilder' },
  // Error handling
  { label: 'recover', type: 'method', info: 'Recover err' },
  { label: 'recoverWith', type: 'method', info: 'Recover monadic' },
  { label: 'transform', type: 'method', info: 'Transform' },
  { label: 'transformWith', type: 'method', info: 'Transform with' },
  { label: 'handleError', type: 'method', info: 'Handle error' },
  { label: 'handleErrorWith', type: 'method', info: 'Handle err monadic' },
  { label: 'attempt', type: 'method', info: 'Attempt (to Either)' },
  { label: 'attemptT', type: 'method', info: 'EitherT result' },
  { label: 'redeem', type: 'method', info: 'Redeem' },
  { label: 'redeemWith', type: 'method', info: 'Redeem monadic' },
  // Future ops
  { label: '.map', type: 'method', info: 'Future map' },
  { label: '.flatMap', type: 'method', info: 'Future flatMap' },
  { label: '.foreach', type: 'method', info: 'Future foreach' },
  { label: '.onComplete', type: 'method', info: 'Future onComplete' },
  { label: '.andThen', type: 'method', info: 'Future andThen' },
  { label: '.fallbackTo', type: 'method', info: 'Fallback to' },
  { label: 'Future.sequence', type: 'function', info: 'Future.sequence' },
  { label: 'Future.traverse', type: 'function', info: 'Future.traverse' },
  { label: 'Future.firstCompletedOf', type: 'function', info: 'First completed' },
  { label: 'Future.fold', type: 'function', info: 'Future.fold' },
  { label: 'Future.reduce', type: 'function', info: 'Future.reduce' },
  // Implicit / context
  { label: 'implicitly', type: 'function', info: 'Get implicit' },
  { label: 'classTag', type: 'function', info: 'ClassTag lookup' },
  { label: 'typeTag', type: 'function', info: 'TypeTag lookup' },
  // Common encoders
  { label: 'deriveEncoder', type: 'function', info: 'circe derive' },
  { label: 'deriveDecoder', type: 'function', info: 'circe derive' },
  { label: 'deriveCodec', type: 'function', info: 'circe derive codec' },
  // munit more
  { label: 'munit.FunSuite', type: 'type', info: 'munit FunSuite' },
  { label: 'munit.CatsEffectSuite', type: 'type', info: 'CatsEffectSuite' },
  // Scala JS / Native interop (common)
  { label: 'js.Dynamic', type: 'type', info: 'JS dynamic' },
  { label: 'js.Array', type: 'type', info: 'JS array' },
  { label: 'js.Object', type: 'type', info: 'JS object' },
  { label: 'js.Promise', type: 'type', info: 'JS promise' },
  { label: 'js.Thenable', type: 'type', info: 'JS thenable' },
  // Additional test imports
  { label: 'EitherValues', type: 'type', info: 'EitherValues' },
  { label: 'OptionValues', type: 'type', info: 'OptionValues' },
  // Scala / JDK utilities
  { label: 'System.currentTimeMillis', type: 'function', info: 'Current millis' },
  { label: 'System.nanoTime', type: 'function', info: 'Current nanos' },
  { label: 'System.lineSeparator', type: 'function', info: 'Line separator' },
  { label: 'System.exit', type: 'function', info: 'System.exit' },
  { label: 'System.getenv', type: 'function', info: 'Get env var' },
  { label: 'System.getProperty', type: 'function', info: 'Get property' },
  { label: 'Thread.sleep', type: 'function', info: 'Thread sleep' },
  { label: 'Thread.currentThread', type: 'function', info: 'Current thread' },
  { label: 'Runtime.getRuntime', type: 'function', info: 'JVM runtime' },
  { label: 'util.Random', type: 'type', info: 'Random' },
  { label: 'util.control.NonFatal', type: 'type', info: 'NonFatal matcher' },
  { label: 'util.Using', type: 'type', info: 'AutoCloseable helper' },
  { label: 'util.Using.resource', type: 'function', info: 'Using.resource' },
  { label: 'util.chaining', type: 'type', info: 'chaining ops' },
  { label: 'Pipe', type: 'method', info: 'pipe() method' },
  { label: 'Tap', type: 'method', info: 'tap() method' },
  // Collection views
  { label: '.view', type: 'method', info: 'Lazy view' },
  { label: '.par', type: 'method', info: 'Parallel view' },
  { label: '.iterator', type: 'method', info: 'Iterator' },
  // Tuples
  { label: '_1', type: 'method', info: 'Tuple _1' },
  { label: '_2', type: 'method', info: 'Tuple _2' },
  { label: '_3', type: 'method', info: 'Tuple _3' },
  { label: '_4', type: 'method', info: 'Tuple _4' },
  { label: '_5', type: 'method', info: 'Tuple _5' },
  // Regex utils
  { label: 'r.findFirstIn', type: 'method', info: 'Regex findFirstIn' },
  { label: 'r.findAllIn', type: 'method', info: 'Regex findAllIn' },
  { label: 'r.findAllMatchIn', type: 'method', info: 'Match iterator' },
  { label: 'r.replaceAllIn', type: 'method', info: 'Replace all' },
  { label: 'r.replaceFirstIn', type: 'method', info: 'Replace first' },
  { label: 'r.matches', type: 'method', info: 'Regex matches' },
  // String ops
  { label: '.length', type: 'method', info: 'String length' },
  { label: '.toInt', type: 'method', info: 'To int' },
  { label: '.toLong', type: 'method', info: 'To long' },
  { label: '.toDouble', type: 'method', info: 'To double' },
  { label: '.toFloat', type: 'method', info: 'To float' },
  { label: '.toBoolean', type: 'method', info: 'To boolean' },
  { label: '.toIntOption', type: 'method', info: 'To Int opt' },
  { label: '.trim', type: 'method', info: 'Trim' },
  { label: '.stripMargin', type: 'method', info: 'Strip margin' },
  { label: '.stripPrefix', type: 'method', info: 'Strip prefix' },
  { label: '.stripSuffix', type: 'method', info: 'Strip suffix' },
  { label: '.toLowerCase', type: 'method', info: 'Lowercase' },
  { label: '.toUpperCase', type: 'method', info: 'Uppercase' },
  { label: '.capitalize', type: 'method', info: 'Capitalize' },
  { label: '.split', type: 'method', info: 'Split string' },
  { label: '.substring', type: 'method', info: 'Substring' },
  { label: '.replace', type: 'method', info: 'Replace' },
  { label: '.replaceAll', type: 'method', info: 'Replace all regex' },
  { label: '.replaceFirst', type: 'method', info: 'Replace first regex' },
  { label: '.matches', type: 'method', info: 'Regex matches' },
  { label: '.startsWith', type: 'method', info: 'Starts with' },
  { label: '.endsWith', type: 'method', info: 'Ends with' },
  { label: '.contains', type: 'method', info: 'Contains' },
  { label: '.indexOf', type: 'method', info: 'Index of' },
  { label: '.lastIndexOf', type: 'method', info: 'Last index' },
  { label: '.reverse', type: 'method', info: 'Reverse' },
  { label: '.chars', type: 'method', info: 'Chars stream' },
  // Map ops
  { label: '.keys', type: 'method', info: 'Map keys' },
  { label: '.values', type: 'method', info: 'Map values' },
  { label: '.keySet', type: 'method', info: 'Key set' },
  { label: '.valuesIterator', type: 'method', info: 'Values iterator' },
  { label: '.keysIterator', type: 'method', info: 'Keys iterator' },
  { label: '.get', type: 'method', info: 'Option get' },
  { label: '.getOrElse', type: 'method', info: 'Get or else' },
  { label: '.contains', type: 'method', info: 'Map contains' },
  { label: '.isDefinedAt', type: 'method', info: 'Is defined at' },
  { label: '.updated', type: 'method', info: 'Map updated' },
  { label: '.+', type: 'method', info: 'Map add entry' },
  { label: '.-', type: 'method', info: 'Map remove key' },
  // Option ops
  { label: '.isDefined', type: 'method', info: 'Option defined' },
  { label: '.isEmpty', type: 'method', info: 'Option empty' },
  { label: '.nonEmpty', type: 'method', info: 'Option non-empty' },
  { label: '.get', type: 'method', info: 'Unsafe get' },
  { label: '.getOrElse', type: 'method', info: 'Get or else' },
  { label: '.orElse', type: 'method', info: 'Or else' },
  { label: '.orNull', type: 'method', info: 'Or null' },
  { label: '.fold', type: 'method', info: 'Option fold' },
  { label: '.toRight', type: 'method', info: 'Option toRight' },
  { label: '.toLeft', type: 'method', info: 'Option toLeft' },
  { label: '.toList', type: 'method', info: 'Option toList' },
  { label: '.toSeq', type: 'method', info: 'Option toSeq' },
  // Either ops
  { label: '.isLeft', type: 'method', info: 'Either isLeft' },
  { label: '.isRight', type: 'method', info: 'Either isRight' },
  { label: '.left', type: 'method', info: 'Either left' },
  { label: '.right', type: 'method', info: 'Either right' },
  { label: '.swap', type: 'method', info: 'Either swap' },
  { label: '.merge', type: 'method', info: 'Either merge' },
  { label: '.toOption', type: 'method', info: 'To Option' },
  { label: '.bimap', type: 'method', info: 'Bimap' },
  // Numeric ops
  { label: '.abs', type: 'method', info: 'abs' },
  { label: '.signum', type: 'method', info: 'signum' },
  { label: '.pow', type: 'method', info: 'pow' },
  { label: '.min', type: 'method', info: 'min' },
  { label: '.max', type: 'method', info: 'max' },
  { label: '.round', type: 'method', info: 'round' },
  { label: '.ceil', type: 'method', info: 'ceil' },
  { label: '.floor', type: 'method', info: 'floor' },
  // Futures env
  { label: 'ExecutionContext.global', type: 'value', info: 'Global EC' },
  { label: 'ExecutionContext.Implicits.global', type: 'value', info: 'Implicit global EC' },
  { label: 'ExecutionContext.fromExecutor', type: 'function', info: 'EC from executor' },
  { label: 'ExecutionContext.fromExecutorService', type: 'function', info: 'EC from exec svc' },
  // Spire
  { label: 'spire.math.Rational', type: 'type', info: 'Rational' },
  { label: 'spire.math.Complex', type: 'type', info: 'Complex' },
  { label: 'spire.math.UByte', type: 'type', info: 'UByte' },
  { label: 'spire.math.UInt', type: 'type', info: 'UInt' },
  { label: 'spire.math.ULong', type: 'type', info: 'ULong' },
  // Additional Cats ops
  { label: '.as', type: 'method', info: 'Replace value' },
  { label: '.void', type: 'method', info: 'Discard value' },
  { label: '.foreverM', type: 'method', info: 'Repeat forever' },
  { label: '.whileM', type: 'method', info: 'While monadic' },
  { label: '.replicateA', type: 'method', info: 'Replicate applicative' },
  { label: '.replicateA_', type: 'method', info: 'Replicate discard' },
  { label: '.iterateUntil', type: 'method', info: 'Iterate until' },
  { label: '.iterateWhile', type: 'method', info: 'Iterate while' },
  // Queue ops (cats-effect)
  { label: 'Queue.bounded', type: 'function', info: 'Bounded queue' },
  { label: 'Queue.unbounded', type: 'function', info: 'Unbounded queue' },
  { label: 'Queue.circularBuffer', type: 'function', info: 'Circular buffer' },
  { label: 'Queue.dropping', type: 'function', info: 'Dropping queue' },
  { label: 'Queue.synchronous', type: 'function', info: 'Synchronous queue' },
  // Dispatcher
  { label: 'Dispatcher.sequential', type: 'function', info: 'Sequential dispatcher' },
  { label: 'Dispatcher.parallel', type: 'function', info: 'Parallel dispatcher' },
  // Logging
  { label: 'Logger', type: 'type', info: 'Logger' },
  { label: 'LoggerFactory', type: 'type', info: 'LoggerFactory' },
  { label: 'Slf4jLogger', type: 'type', info: 'Slf4j logger' },
  { label: 'LazyLogging', type: 'type', info: 'LazyLogging trait' },
  { label: 'StrictLogging', type: 'type', info: 'StrictLogging trait' },
  { label: 'logger.info', type: 'method', info: 'Log info' },
  { label: 'logger.debug', type: 'method', info: 'Log debug' },
  { label: 'logger.warn', type: 'method', info: 'Log warn' },
  { label: 'logger.error', type: 'method', info: 'Log error' },
  { label: 'logger.trace', type: 'method', info: 'Log trace' },
  // Additional test matchers
  { label: 'include', type: 'function', info: 'String include matcher' },
  { label: 'have', type: 'function', info: 'Have matcher' },
  { label: 'contain', type: 'function', info: 'Contain matcher' },
  { label: 'only', type: 'function', info: 'Only matcher' },
  { label: 'all', type: 'function', info: 'All matcher' },
  { label: 'every', type: 'function', info: 'Every matcher' },
  { label: 'some', type: 'function', info: 'Some matcher' },
  { label: 'thrownBy', type: 'function', info: 'Thrown by matcher' },
  { label: 'in', type: 'function', info: 'In test body' },
  { label: 'they', type: 'function', info: 'They test body' },
  // Additional Scala 3 misc
  { label: 'compiletime.summonInline', type: 'function', info: 'Summon inline' },
  { label: 'compiletime.error', type: 'function', info: 'Compile-time error' },
  { label: 'compiletime.constValue', type: 'function', info: 'Const value' },
  { label: 'compiletime.erasedValue', type: 'function', info: 'Erased value' },
  // Additional Futures ops
  { label: 'Future.delegate', type: 'function', info: 'Future delegate' },
  { label: 'Future.unit', type: 'function', info: 'Future.unit' },
  { label: 'Future.apply', type: 'function', info: 'Future.apply' },
  // Additional error types
  { label: 'Throwable', type: 'type', info: 'Throwable' },
  { label: 'Exception', type: 'type', info: 'Exception' },
  { label: 'RuntimeException', type: 'type', info: 'Runtime exception' },
  { label: 'IllegalArgumentException', type: 'type', info: 'IAE' },
  { label: 'IllegalStateException', type: 'type', info: 'ISE' },
  { label: 'UnsupportedOperationException', type: 'type', info: 'UOE' },
  { label: 'NoSuchElementException', type: 'type', info: 'NSEE' },
  { label: 'NullPointerException', type: 'type', info: 'NPE' },
  { label: 'ArrayIndexOutOfBoundsException', type: 'type', info: 'AIOOB' },
  { label: 'ClassCastException', type: 'type', info: 'CCE' },
  { label: 'NumberFormatException', type: 'type', info: 'NFE' },
  // Java interop common
  { label: 'java.util.UUID', type: 'type', info: 'UUID' },
  { label: 'java.time.Instant', type: 'type', info: 'Instant' },
  { label: 'java.time.LocalDate', type: 'type', info: 'LocalDate' },
  { label: 'java.time.LocalDateTime', type: 'type', info: 'LocalDateTime' },
  { label: 'java.time.ZonedDateTime', type: 'type', info: 'ZonedDateTime' },
  { label: 'java.time.Duration', type: 'type', info: 'Java Duration' },
  { label: 'java.nio.file.Paths', type: 'type', info: 'Paths' },
  { label: 'java.nio.file.Files', type: 'type', info: 'Files' },
  { label: 'java.net.URI', type: 'type', info: 'URI' },
  { label: 'java.net.URL', type: 'type', info: 'URL' },
  { label: 'java.util.concurrent.ConcurrentHashMap', type: 'type', info: 'CHM' },
  { label: 'java.util.concurrent.Executors', type: 'type', info: 'Executors' },
];
