// Completion entries for toml.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  // Keywords
  { label: '[table]', type: 'keyword', info: 'Table header' },
  { label: '[[array]]', type: 'keyword', info: 'Array of tables' },
  { label: '# comment', type: 'keyword', info: 'Comment' },
  { label: 'true', type: 'keyword', info: 'Boolean true' },
  { label: 'false', type: 'keyword', info: 'Boolean false' },
  // Syntax
  { label: 'key = value', type: 'snippet', apply: '${key} = ${value}', info: 'Key-value pair' },
  { label: 'key = "value"', type: 'snippet', apply: '${key} = "${value}"', info: 'String value' },
  { label: 'key = [array]', type: 'snippet', apply: '${key} = [${values}]', info: 'Array value' },
  { label: 'key = { inline }', type: 'snippet', apply: '${key} = { ${nested} }', info: 'Inline table' },
  // Common TOML structures
  {
    label: 'table',
    type: 'snippet',
    apply: '[${table_name}]\n${key} = ${value}',
    info: 'Table definition'
  },
  {
    label: 'nested table',
    type: 'snippet',
    apply: '[${parent}.${child}]\n${key} = ${value}',
    info: 'Nested table'
  },
  {
    label: 'array of tables',
    type: 'snippet',
    apply: '[[${array_name}]]\n${key} = ${value}',
    info: 'Array of tables'
  },
  // Common TOML keys (generic)
  { label: 'title', type: 'property', info: 'Title property' },
  { label: 'version', type: 'property', info: 'Version property' },
  { label: 'description', type: 'property', info: 'Description property' },
  { label: 'authors', type: 'property', info: 'Authors list' },
  { label: 'dependencies', type: 'property', info: 'Dependencies table' },
  { label: 'dev-dependencies', type: 'property', info: 'Dev dependencies' },
  { label: 'path', type: 'property', info: 'Path property' },
  { label: 'git', type: 'property', info: 'Git repository' },
  { label: 'branch', type: 'property', info: 'Git branch' },
  { label: 'optional', type: 'property', info: 'Optional dependency' },
  // Cargo.toml
  { label: 'package', type: 'property', info: 'Package section' },
  { label: 'name', type: 'property', info: 'Package name' },
  { label: 'edition', type: 'property', info: 'Rust edition' },
  { label: 'license', type: 'property', info: 'License string' },
  { label: 'license-file', type: 'property', info: 'License file' },
  { label: 'repository', type: 'property', info: 'Source repo URL' },
  { label: 'homepage', type: 'property', info: 'Homepage URL' },
  { label: 'documentation', type: 'property', info: 'Docs URL' },
  { label: 'readme', type: 'property', info: 'README file' },
  { label: 'keywords', type: 'property', info: 'Search keywords' },
  { label: 'categories', type: 'property', info: 'Categories' },
  { label: 'workspace', type: 'property', info: 'Workspace table' },
  { label: 'members', type: 'property', info: 'Workspace members' },
  { label: 'exclude', type: 'property', info: 'Exclude paths' },
  { label: 'include', type: 'property', info: 'Include paths' },
  { label: 'features', type: 'property', info: 'Feature flags' },
  { label: 'default', type: 'property', info: 'Default features' },
  { label: 'build-dependencies', type: 'property', info: 'Build deps' },
  { label: 'target', type: 'property', info: 'Target config' },
  { label: 'bin', type: 'property', info: 'Binary target' },
  { label: 'lib', type: 'property', info: 'Library target' },
  { label: 'test', type: 'property', info: 'Test target' },
  { label: 'bench', type: 'property', info: 'Benchmark target' },
  { label: 'example', type: 'property', info: 'Example target' },
  { label: 'crate-type', type: 'property', info: 'Crate types' },
  { label: 'rust-version', type: 'property', info: 'Min Rust version' },
  { label: 'resolver', type: 'property', info: 'Feature resolver' },
  { label: 'default-features', type: 'property', info: 'Default features' },
  { label: 'registry', type: 'property', info: 'Crate registry' },
  { label: 'rev', type: 'property', info: 'Git revision' },
  { label: 'tag', type: 'property', info: 'Git tag' },
  { label: 'package', type: 'property', info: 'Pkg rename/pin' },
  // pyproject.toml
  { label: 'project', type: 'property', info: 'PEP 621 project' },
  { label: 'build-system', type: 'property', info: 'PEP 518 build' },
  { label: 'requires', type: 'property', info: 'Build requires' },
  { label: 'build-backend', type: 'property', info: 'Build backend' },
  { label: 'tool', type: 'property', info: 'Tool table' },
  { label: 'dynamic', type: 'property', info: 'Dynamic fields' },
  { label: 'requires-python', type: 'property', info: 'Python version' },
  { label: 'classifiers', type: 'property', info: 'PyPI classifiers' },
  { label: 'urls', type: 'property', info: 'Project URLs' },
  { label: 'scripts', type: 'property', info: 'Entry point scripts' },
  { label: 'entry-points', type: 'property', info: 'Entry points' },
  { label: 'gui-scripts', type: 'property', info: 'GUI scripts' },
  { label: 'optional-dependencies', type: 'property', info: 'Optional deps' },
  { label: 'maintainers', type: 'property', info: 'Maintainers list' },
  // Netlify / Vercel
  { label: 'publish', type: 'property', info: 'Publish dir' },
  { label: 'functions', type: 'property', info: 'Functions dir' },
  { label: 'redirects', type: 'property', info: 'Redirects' },
  { label: 'headers', type: 'property', info: 'Headers config' },
  // Cargo.toml package
  { label: 'edition', type: 'property', info: 'Rust edition' },
  { label: 'rust-version', type: 'property', info: 'Min rustc' },
  { label: 'authors', type: 'property', info: 'Crate authors' },
  { label: 'categories', type: 'property', info: 'crates.io categories' },
  { label: 'keywords', type: 'property', info: 'crates.io keywords' },
  { label: 'homepage', type: 'property', info: 'Homepage URL' },
  { label: 'repository', type: 'property', info: 'VCS URL' },
  { label: 'documentation', type: 'property', info: 'Docs URL' },
  { label: 'readme', type: 'property', info: 'README path' },
  { label: 'license', type: 'property', info: 'SPDX license' },
  { label: 'license-file', type: 'property', info: 'License file' },
  { label: 'workspace', type: 'property', info: 'Workspace root' },
  { label: 'build', type: 'property', info: 'build.rs path' },
  { label: 'links', type: 'property', info: 'Links native lib' },
  { label: 'include', type: 'property', info: 'Package include' },
  { label: 'exclude', type: 'property', info: 'Package exclude' },
  { label: 'publish', type: 'property', info: 'Publish allowed' },
  { label: 'metadata', type: 'property', info: 'Tool metadata' },
  { label: 'default-run', type: 'property', info: 'Default bin' },
  { label: 'autobins', type: 'property', info: 'Auto-discover bins' },
  { label: 'autoexamples', type: 'property', info: 'Auto-discover examples' },
  { label: 'autotests', type: 'property', info: 'Auto-discover tests' },
  { label: 'autobenches', type: 'property', info: 'Auto-discover benches' },
  { label: 'resolver', type: 'property', info: 'Dep resolver version' },
  // [dependencies]
  { label: '[dependencies]', type: 'section', info: 'Dependencies' },
  { label: '[dev-dependencies]', type: 'section', info: 'Dev dependencies' },
  { label: '[build-dependencies]', type: 'section', info: 'Build deps' },
  { label: '[dependencies.*]', type: 'section', info: 'Dep detail table' },
  { label: "[target.'cfg(...)'.dependencies]", type: 'section', info: 'cfg deps' },
  { label: "[target.'cfg(unix)'.dependencies]", type: 'section', info: 'Unix deps' },
  { label: "[target.'cfg(windows)'.dependencies]", type: 'section', info: 'Windows deps' },
  { label: 'path', type: 'property', info: 'Local path' },
  { label: 'git', type: 'property', info: 'Git URL' },
  { label: 'branch', type: 'property', info: 'Git branch' },
  { label: 'tag', type: 'property', info: 'Git tag' },
  { label: 'rev', type: 'property', info: 'Git rev' },
  { label: 'features', type: 'property', info: 'Enabled features' },
  { label: 'default-features', type: 'property', info: 'Use default feats' },
  { label: 'optional', type: 'property', info: 'Optional dep' },
  { label: 'registry', type: 'property', info: 'Custom registry' },
  { label: 'package', type: 'property', info: 'Actual pkg name' },
  { label: 'public', type: 'property', info: 'Public re-export' },
  // [features]
  { label: '[features]', type: 'section', info: 'Cargo features' },
  { label: 'default', type: 'property', info: 'Default features' },
  // [lib]
  { label: '[lib]', type: 'section', info: 'Library target' },
  { label: 'name', type: 'property', info: 'Target name' },
  { label: 'crate-type', type: 'property', info: 'Crate type' },
  { label: 'test', type: 'property', info: 'Enable test' },
  { label: 'doctest', type: 'property', info: 'Enable doctests' },
  { label: 'bench', type: 'property', info: 'Enable bench' },
  { label: 'doc', type: 'property', info: 'Docs generation' },
  { label: 'harness', type: 'property', info: 'Use test harness' },
  { label: 'plugin', type: 'property', info: 'Plugin target' },
  { label: 'proc-macro', type: 'property', info: 'Proc macro crate' },
  { label: 'required-features', type: 'property', info: 'Required features' },
  // [[bin]] / [[example]] / [[test]] / [[bench]]
  { label: '[[bin]]', type: 'section', info: 'Binary target' },
  { label: '[[example]]', type: 'section', info: 'Example target' },
  { label: '[[test]]', type: 'section', info: 'Integration test' },
  { label: '[[bench]]', type: 'section', info: 'Benchmark target' },
  // [profile.*]
  { label: '[profile.dev]', type: 'section', info: 'Dev profile' },
  { label: '[profile.release]', type: 'section', info: 'Release profile' },
  { label: '[profile.test]', type: 'section', info: 'Test profile' },
  { label: '[profile.bench]', type: 'section', info: 'Bench profile' },
  { label: 'opt-level', type: 'property', info: 'Optimization level' },
  { label: 'debug', type: 'property', info: 'Debug info' },
  { label: 'split-debuginfo', type: 'property', info: 'Split debug info' },
  { label: 'strip', type: 'property', info: 'Strip symbols' },
  { label: 'debug-assertions', type: 'property', info: 'Debug asserts' },
  { label: 'overflow-checks', type: 'property', info: 'Overflow checks' },
  { label: 'lto', type: 'property', info: 'Link-time optim' },
  { label: 'panic', type: 'property', info: 'Panic strategy' },
  { label: 'incremental', type: 'property', info: 'Incremental compile' },
  { label: 'codegen-units', type: 'property', info: 'Codegen units' },
  { label: 'rpath', type: 'property', info: 'rpath flag' },
  // [workspace]
  { label: '[workspace]', type: 'section', info: 'Cargo workspace' },
  { label: 'members', type: 'property', info: 'Workspace members' },
  { label: 'default-members', type: 'property', info: 'Default members' },
  { label: '[workspace.package]', type: 'section', info: 'Shared package meta' },
  { label: '[workspace.dependencies]', type: 'section', info: 'Shared deps' },
  { label: '[workspace.lints]', type: 'section', info: 'Shared lints' },
  { label: '[patch]', type: 'section', info: 'Patch deps' },
  { label: '[patch.crates-io]', type: 'section', info: 'Patch crates.io' },
  { label: '[replace]', type: 'section', info: 'Replace deps (deprecated)' },
  { label: '[badges]', type: 'section', info: 'crates.io badges' },
  // pyproject.toml
  { label: '[project]', type: 'section', info: 'PEP 621 project' },
  { label: 'dependencies', type: 'property', info: 'Project deps' },
  { label: 'optional-dependencies', type: 'property', info: 'Extras' },
  { label: 'requires-python', type: 'property', info: 'Python version req' },
  { label: 'dynamic', type: 'property', info: 'Dynamic fields' },
  { label: 'classifiers', type: 'property', info: 'Trove classifiers' },
  { label: 'urls', type: 'property', info: 'URL map' },
  { label: 'entry-points', type: 'property', info: 'Entry points' },
  { label: 'gui-scripts', type: 'property', info: 'GUI scripts' },
  { label: 'scripts', type: 'property', info: 'CLI scripts' },
  { label: '[project.urls]', type: 'section', info: 'Project URLs' },
  { label: '[project.scripts]', type: 'section', info: 'Console scripts' },
  { label: '[project.gui-scripts]', type: 'section', info: 'GUI scripts' },
  { label: '[project.entry-points]', type: 'section', info: 'Entry points' },
  { label: '[project.optional-dependencies]', type: 'section', info: 'Extras' },
  { label: '[build-system]', type: 'section', info: 'PEP 517 build system' },
  { label: 'requires', type: 'property', info: 'Build reqs' },
  { label: 'build-backend', type: 'property', info: 'Build backend' },
  { label: 'backend-path', type: 'property', info: 'Backend path' },
  // Tool configs
  { label: '[tool.black]', type: 'section', info: 'Black formatter' },
  { label: '[tool.ruff]', type: 'section', info: 'Ruff linter' },
  { label: '[tool.ruff.lint]', type: 'section', info: 'Ruff lint rules' },
  { label: '[tool.ruff.format]', type: 'section', info: 'Ruff format' },
  { label: '[tool.mypy]', type: 'section', info: 'mypy config' },
  { label: '[tool.pytest.ini_options]', type: 'section', info: 'pytest config' },
  { label: '[tool.coverage.run]', type: 'section', info: 'coverage run' },
  { label: '[tool.coverage.report]', type: 'section', info: 'coverage report' },
  { label: '[tool.coverage.html]', type: 'section', info: 'coverage HTML' },
  { label: '[tool.poetry]', type: 'section', info: 'Poetry metadata' },
  { label: '[tool.poetry.dependencies]', type: 'section', info: 'Poetry deps' },
  { label: '[tool.poetry.dev-dependencies]', type: 'section', info: 'Poetry dev deps' },
  { label: '[tool.poetry.group.dev.dependencies]', type: 'section', info: 'Poetry dev group' },
  { label: '[tool.poetry.scripts]', type: 'section', info: 'Poetry scripts' },
  { label: '[tool.poetry.extras]', type: 'section', info: 'Poetry extras' },
  { label: '[tool.hatch]', type: 'section', info: 'Hatch config' },
  { label: '[tool.hatch.build]', type: 'section', info: 'Hatch build' },
  { label: '[tool.hatch.envs.default]', type: 'section', info: 'Hatch env' },
  { label: '[tool.hatch.version]', type: 'section', info: 'Hatch version' },
  { label: '[tool.setuptools]', type: 'section', info: 'setuptools' },
  { label: '[tool.setuptools.packages.find]', type: 'section', info: 'Pkg discovery' },
  { label: '[tool.setuptools.package-data]', type: 'section', info: 'Pkg data' },
  { label: '[tool.setuptools.dynamic]', type: 'section', info: 'Dynamic vals' },
  { label: '[tool.uv]', type: 'section', info: 'uv config' },
  { label: '[tool.uv.sources]', type: 'section', info: 'uv sources' },
  { label: '[tool.uv.workspace]', type: 'section', info: 'uv workspace' },
  { label: '[tool.pdm]', type: 'section', info: 'PDM config' },
  { label: '[tool.pdm.dev-dependencies]', type: 'section', info: 'PDM dev deps' },
  { label: '[tool.pdm.scripts]', type: 'section', info: 'PDM scripts' },
  { label: '[tool.isort]', type: 'section', info: 'isort config' },
  { label: '[tool.flake8]', type: 'section', info: 'flake8 config' },
  { label: '[tool.pylint]', type: 'section', info: 'pylint config' },
  { label: '[tool.pyright]', type: 'section', info: 'pyright config' },
  { label: '[tool.bandit]', type: 'section', info: 'bandit config' },
  { label: '[tool.cibuildwheel]', type: 'section', info: 'cibuildwheel' },
  // Common TOML scalars
  { label: 'line-length', type: 'property', info: 'Max line length' },
  { label: 'target-version', type: 'property', info: 'Target Python' },
  { label: 'skip-string-normalization', type: 'property', info: 'Black opt' },
  { label: 'preview', type: 'property', info: 'Preview feature' },
  { label: 'select', type: 'property', info: 'Rules select' },
  { label: 'ignore', type: 'property', info: 'Rules ignore' },
  { label: 'extend-select', type: 'property', info: 'Extend select' },
  { label: 'extend-ignore', type: 'property', info: 'Extend ignore' },
  { label: 'fix', type: 'property', info: 'Auto-fix flag' },
  { label: 'unfixable', type: 'property', info: 'Unfixable rules' },
  { label: 'exclude', type: 'property', info: 'Exclude paths' },
  { label: 'extend-exclude', type: 'property', info: 'Extend exclude' },
  { label: 'force-exclude', type: 'property', info: 'Force exclude' },
  { label: 'respect-gitignore', type: 'property', info: 'Respect gitignore' },
  { label: 'src', type: 'property', info: 'Source dirs' },
  { label: 'namespace-packages', type: 'property', info: 'Namespace pkgs' },
  { label: 'per-file-ignores', type: 'property', info: 'Per-file ignores' },
  { label: 'allowed-confusables', type: 'property', info: 'Allowed confs' },
  { label: 'dummy-variable-rgx', type: 'property', info: 'Dummy var regex' },
  { label: 'quote-style', type: 'property', info: 'Quote style' },
  { label: 'indent-style', type: 'property', info: 'Indent style' },
  { label: 'skip-magic-trailing-comma', type: 'property', info: 'Skip trail comma' },
  { label: 'docstring-code-format', type: 'property', info: 'Format doctests' },
  { label: 'strict', type: 'property', info: 'Strict mode' },
  { label: 'warn_unused_ignores', type: 'property', info: 'Warn unused' },
  { label: 'warn_redundant_casts', type: 'property', info: 'Warn redundant' },
  { label: 'warn_return_any', type: 'property', info: 'Warn any' },
  { label: 'disallow_untyped_defs', type: 'property', info: 'No untyped defs' },
  { label: 'disallow_incomplete_defs', type: 'property', info: 'No incomplete defs' },
  { label: 'no_implicit_optional', type: 'property', info: 'No implicit optional' },
  { label: 'check_untyped_defs', type: 'property', info: 'Check untyped' },
  { label: 'ignore_missing_imports', type: 'property', info: 'Ignore missing imports' },
  { label: 'pretty', type: 'property', info: 'Pretty output' },
  { label: 'show_error_codes', type: 'property', info: 'Show err codes' },
  { label: 'python_version', type: 'property', info: 'Python version' },
  { label: 'mypy_path', type: 'property', info: 'mypy PYTHONPATH' },
  { label: 'plugins', type: 'property', info: 'mypy plugins' },
  // pytest
  { label: 'testpaths', type: 'property', info: 'Test dirs' },
  { label: 'python_files', type: 'property', info: 'Test file glob' },
  { label: 'python_classes', type: 'property', info: 'Test class glob' },
  { label: 'python_functions', type: 'property', info: 'Test fn glob' },
  { label: 'markers', type: 'property', info: 'Test markers' },
  { label: 'addopts', type: 'property', info: 'Extra args' },
  { label: 'minversion', type: 'property', info: 'Min pytest version' },
  { label: 'xfail_strict', type: 'property', info: 'xfail strict' },
  { label: 'filterwarnings', type: 'property', info: 'Filter warnings' },
  // coverage
  { label: 'branch', type: 'property', info: 'Branch coverage' },
  { label: 'source', type: 'property', info: 'Source packages' },
  { label: 'omit', type: 'property', info: 'Omit files' },
  { label: 'include', type: 'property', info: 'Include paths' },
  { label: 'show_missing', type: 'property', info: 'Show missing' },
  { label: 'fail_under', type: 'property', info: 'Coverage threshold' },
  { label: 'skip_covered', type: 'property', info: 'Skip covered' },
  { label: 'skip_empty', type: 'property', info: 'Skip empty' },
  { label: 'sort', type: 'property', info: 'Sort order' },
  { label: 'precision', type: 'property', info: 'Report precision' },
  { label: 'exclude_lines', type: 'property', info: 'Exclude lines' },
  { label: 'directory', type: 'property', info: 'HTML dir' },
  { label: 'title', type: 'property', info: 'Report title' },
  // fly.toml
  { label: 'app', type: 'property', info: 'Fly app name' },
  { label: 'primary_region', type: 'property', info: 'Primary region' },
  { label: 'kill_signal', type: 'property', info: 'Kill signal' },
  { label: 'kill_timeout', type: 'property', info: 'Kill timeout' },
  { label: '[build]', type: 'section', info: 'Build section' },
  { label: '[env]', type: 'section', info: 'Env section' },
  { label: '[experimental]', type: 'section', info: 'Experimental' },
  { label: '[deploy]', type: 'section', info: 'Deploy config' },
  { label: '[[services]]', type: 'section', info: 'Services array' },
  { label: '[[services.ports]]', type: 'section', info: 'Service ports' },
  { label: '[[services.tcp_checks]]', type: 'section', info: 'TCP check' },
  { label: '[[services.http_checks]]', type: 'section', info: 'HTTP check' },
  { label: '[services.concurrency]', type: 'section', info: 'Concurrency' },
  { label: 'internal_port', type: 'property', info: 'Internal port' },
  { label: 'processes', type: 'property', info: 'Processes' },
  { label: 'auto_stop_machines', type: 'property', info: 'Auto stop' },
  { label: 'auto_start_machines', type: 'property', info: 'Auto start' },
  { label: 'min_machines_running', type: 'property', info: 'Min machines' },
  { label: '[[vm]]', type: 'section', info: 'VM config' },
  { label: 'size', type: 'property', info: 'VM size' },
  { label: 'memory', type: 'property', info: 'VM memory' },
  // starship.toml
  { label: 'format', type: 'property', info: 'Prompt format' },
  { label: 'right_format', type: 'property', info: 'Right prompt' },
  { label: 'continuation_prompt', type: 'property', info: 'Cont prompt' },
  { label: 'add_newline', type: 'property', info: 'Newline prepended' },
  { label: 'palette', type: 'property', info: 'Palette name' },
  { label: 'palettes', type: 'property', info: 'Palette map' },
  { label: '[character]', type: 'section', info: 'Prompt char' },
  { label: '[directory]', type: 'section', info: 'Directory mod' },
  { label: '[git_branch]', type: 'section', info: 'Git branch mod' },
  { label: '[git_commit]', type: 'section', info: 'Git commit mod' },
  { label: '[git_state]', type: 'section', info: 'Git state mod' },
  { label: '[git_status]', type: 'section', info: 'Git status mod' },
  { label: '[cmd_duration]', type: 'section', info: 'Cmd duration mod' },
  { label: '[battery]', type: 'section', info: 'Battery mod' },
  { label: '[time]', type: 'section', info: 'Time mod' },
  { label: '[hostname]', type: 'section', info: 'Hostname mod' },
  { label: '[username]', type: 'section', info: 'Username mod' },
  { label: '[kubernetes]', type: 'section', info: 'Kubernetes mod' },
  { label: '[aws]', type: 'section', info: 'AWS mod' },
  { label: '[gcloud]', type: 'section', info: 'GCP mod' },
  { label: '[azure]', type: 'section', info: 'Azure mod' },
  { label: '[nodejs]', type: 'section', info: 'Node.js mod' },
  { label: '[python]', type: 'section', info: 'Python mod' },
  { label: '[rust]', type: 'section', info: 'Rust mod' },
  { label: '[golang]', type: 'section', info: 'Go mod' },
  { label: '[java]', type: 'section', info: 'Java mod' },
  { label: '[docker_context]', type: 'section', info: 'Docker ctx mod' },
  // netlify.toml more
  { label: '[context.production]', type: 'section', info: 'Prod context' },
  { label: '[context.deploy-preview]', type: 'section', info: 'Preview context' },
  { label: '[context.branch-deploy]', type: 'section', info: 'Branch context' },
  { label: '[[redirects]]', type: 'section', info: 'Redirect rules' },
  { label: '[[headers]]', type: 'section', info: 'Header rules' },
  { label: '[[plugins]]', type: 'section', info: 'Plugin' },
  { label: 'from', type: 'property', info: 'From path/URL' },
  { label: 'to', type: 'property', info: 'To path/URL' },
  { label: 'status', type: 'property', info: 'HTTP status' },
  { label: 'force', type: 'property', info: 'Force redirect' },
  { label: 'conditions', type: 'property', info: 'Conditions map' },
  { label: 'values', type: 'property', info: 'Header values' },
  { label: 'for', type: 'property', info: 'Path match' },
  // .cargo/config.toml
  { label: '[build]', type: 'section', info: 'Cargo build cfg' },
  { label: 'target', type: 'property', info: 'Build target' },
  { label: 'jobs', type: 'property', info: 'Parallel jobs' },
  { label: 'rustflags', type: 'property', info: 'Rust flags' },
  { label: 'rustdocflags', type: 'property', info: 'rustdoc flags' },
  { label: 'rustc-wrapper', type: 'property', info: 'rustc wrapper' },
  { label: 'pipelining', type: 'property', info: 'Pipelining flag' },
  { label: 'incremental', type: 'property', info: 'Incremental flag' },
  { label: '[registries]', type: 'section', info: 'Custom registries' },
  { label: '[registry]', type: 'section', info: 'Default registry' },
  { label: '[net]', type: 'section', info: 'Net config' },
  { label: 'retry', type: 'property', info: 'Net retries' },
  { label: 'git-fetch-with-cli', type: 'property', info: 'Use git CLI' },
  { label: 'offline', type: 'property', info: 'Offline mode' },
  { label: '[term]', type: 'section', info: 'Term config' },
  { label: 'color', type: 'property', info: 'Color output' },
  { label: 'progress', type: 'property', info: 'Progress output' },
  { label: 'verbose', type: 'property', info: 'Verbose output' },
  { label: '[alias]', type: 'section', info: 'Cargo aliases' },
  { label: '[env]', type: 'section', info: 'Env vars' },
  { label: '[source]', type: 'section', info: 'Source replace' },
  { label: '[source.crates-io]', type: 'section', info: 'crates.io src' },
  { label: 'replace-with', type: 'property', info: 'Replace source' },
  { label: '[http]', type: 'section', info: 'HTTP config' },
  { label: 'cainfo', type: 'property', info: 'CA info file' },
  { label: 'proxy', type: 'property', info: 'HTTP proxy' },
  { label: 'timeout', type: 'property', info: 'HTTP timeout' },
  { label: 'low-speed-limit', type: 'property', info: 'Low-speed limit' },
  { label: 'multiplexing', type: 'property', info: 'HTTP multiplex' },
  // SPDX license ids
  { label: 'MIT', type: 'value', info: 'MIT license' },
  { label: 'Apache-2.0', type: 'value', info: 'Apache 2.0' },
  { label: 'MIT OR Apache-2.0', type: 'value', info: 'Rust-style dual' },
  { label: 'GPL-3.0-or-later', type: 'value', info: 'GPL-3.0+' },
  { label: 'GPL-2.0-only', type: 'value', info: 'GPL-2.0' },
  { label: 'BSD-2-Clause', type: 'value', info: 'BSD-2-Clause' },
  { label: 'BSD-3-Clause', type: 'value', info: 'BSD-3-Clause' },
  { label: 'LGPL-3.0-or-later', type: 'value', info: 'LGPL-3.0+' },
  { label: 'MPL-2.0', type: 'value', info: 'MPL 2.0' },
  { label: 'AGPL-3.0-or-later', type: 'value', info: 'AGPL-3.0+' },
  { label: 'Unlicense', type: 'value', info: 'Unlicense' },
  { label: 'ISC', type: 'value', info: 'ISC license' },
  // Crate types
  { label: 'lib', type: 'value', info: 'crate-type lib' },
  { label: 'rlib', type: 'value', info: 'crate-type rlib' },
  { label: 'dylib', type: 'value', info: 'crate-type dylib' },
  { label: 'cdylib', type: 'value', info: 'crate-type cdylib' },
  { label: 'staticlib', type: 'value', info: 'crate-type staticlib' },
  { label: 'proc-macro', type: 'value', info: 'crate-type proc-macro' },
  { label: 'bin', type: 'value', info: 'crate-type bin' },
  // Opt levels
  { label: '"z"', type: 'value', info: 'Opt z size' },
  { label: '"s"', type: 'value', info: 'Opt s size' },
  { label: '"fat"', type: 'value', info: 'LTO fat' },
  { label: '"thin"', type: 'value', info: 'LTO thin' },
  { label: 'abort', type: 'value', info: 'panic abort' },
  { label: 'unwind', type: 'value', info: 'panic unwind' },
  // Additional pyproject tool sections
  { label: '[tool.poe.tasks]', type: 'section', info: 'Poe tasks' },
  { label: '[tool.nox]', type: 'section', info: 'Nox config' },
  { label: '[tool.tox]', type: 'section', info: 'Tox config' },
  { label: '[tool.pylint.master]', type: 'section', info: 'pylint master' },
  { label: '[tool.pylint.messages_control]', type: 'section', info: 'pylint msgs' },
  { label: '[tool.pylint.format]', type: 'section', info: 'pylint format' },
  { label: '[tool.pylint.basic]', type: 'section', info: 'pylint basic' },
  { label: '[tool.pylint.design]', type: 'section', info: 'pylint design' },
  { label: '[tool.pyright.overrides]', type: 'section', info: 'pyright overrides' },
  { label: '[tool.commitizen]', type: 'section', info: 'commitizen' },
  { label: '[tool.semantic_release]', type: 'section', info: 'sem release' },
  { label: '[tool.codespell]', type: 'section', info: 'codespell' },
  // Rust cargo badges / metadata
  { label: 'maintenance', type: 'property', info: 'Maintenance badge' },
  { label: 'is-it-maintained-issue-resolution', type: 'property', info: 'Badge' },
  { label: 'is-it-maintained-open-issues', type: 'property', info: 'Badge' },
  { label: 'travis-ci', type: 'property', info: 'Travis badge' },
  { label: 'codecov', type: 'property', info: 'codecov badge' },
  { label: 'coveralls', type: 'property', info: 'coveralls badge' },
  { label: 'circle-ci', type: 'property', info: 'CircleCI badge' },
  { label: 'gitlab', type: 'property', info: 'GitLab badge' },
  { label: 'appveyor', type: 'property', info: 'appveyor badge' },
  // Python classifier samples
  { label: '"Development Status :: 5 - Production/Stable"', type: 'value', info: 'Prod status' },
  { label: '"Programming Language :: Python :: 3"', type: 'value', info: 'Python 3' },
  { label: '"License :: OSI Approved :: MIT License"', type: 'value', info: 'MIT clf' },
  { label: '"Operating System :: OS Independent"', type: 'value', info: 'OS indep' },
  { label: '"Topic :: Software Development :: Libraries"', type: 'value', info: 'Topic libs' },
  { label: '"Intended Audience :: Developers"', type: 'value', info: 'Audience dev' },
  { label: '"Framework :: Django"', type: 'value', info: 'Framework Django' },
  { label: '"Framework :: Flask"', type: 'value', info: 'Framework Flask' },
  { label: '"Framework :: FastAPI"', type: 'value', info: 'Framework FastAPI' },
  // Poetry source
  { label: '[[tool.poetry.source]]', type: 'section', info: 'Poetry source' },
  { label: 'priority', type: 'property', info: 'Source priority' },
  // Rye / uv
  { label: '[tool.rye]', type: 'section', info: 'Rye config' },
  { label: '[tool.rye.scripts]', type: 'section', info: 'Rye scripts' },
  { label: 'managed', type: 'property', info: 'Managed flag' },
  { label: 'dev-dependencies', type: 'property', info: 'Rye dev deps' },
  { label: '[tool.uv.pip]', type: 'section', info: 'uv pip cfg' },
  { label: '[tool.uv.index]', type: 'section', info: 'uv index' },
  // Cargo build new keys
  { label: 'dep-info-basedir', type: 'property', info: 'dep-info basedir' },
  { label: 'jobs', type: 'property', info: 'Parallel jobs' },
  { label: 'crate-name', type: 'property', info: 'Crate rename' },
  // More starship module flags
  { label: 'disabled', type: 'property', info: 'Disable module' },
  { label: 'symbol', type: 'property', info: 'Module symbol' },
  { label: 'success_symbol', type: 'property', info: 'Success symbol' },
  { label: 'error_symbol', type: 'property', info: 'Error symbol' },
  { label: 'vicmd_symbol', type: 'property', info: 'vi-cmd symbol' },
  { label: 'read_only', type: 'property', info: 'RO marker' },
  { label: 'style', type: 'property', info: 'Style string' },
  { label: 'truncation_length', type: 'property', info: 'Trunc length' },
  { label: 'truncation_symbol', type: 'property', info: 'Trunc symbol' },
  { label: 'truncate_to_repo', type: 'property', info: 'Truncate to repo' },
  { label: 'fish_style_pwd_dir_length', type: 'property', info: 'Fish-style dir' },
  { label: 'show_always', type: 'property', info: 'Show always' },
  { label: 'min_time', type: 'property', info: 'Min duration' },
  // vercel.json-ish fields for TOML adapters
  { label: 'buildCommand', type: 'property', info: 'Build command' },
  { label: 'devCommand', type: 'property', info: 'Dev command' },
  { label: 'outputDirectory', type: 'property', info: 'Output dir' },
  { label: 'installCommand', type: 'property', info: 'Install command' },
  { label: 'framework', type: 'property', info: 'Framework preset' },
  { label: 'regions', type: 'property', info: 'Edge regions' },
  { label: 'rewrites', type: 'property', info: 'URL rewrites' },
  { label: 'cleanUrls', type: 'property', info: 'Clean URLs' },
  { label: 'trailingSlash', type: 'property', info: 'Trailing slash' },
  // TOML datatypes
  { label: 'true', type: 'value', info: 'Bool true' },
  { label: 'false', type: 'value', info: 'Bool false' },
  { label: 'inf', type: 'value', info: 'Infinity' },
  { label: '-inf', type: 'value', info: 'Neg infinity' },
  { label: 'nan', type: 'value', info: 'NaN' },
  { label: '0x', type: 'value', info: 'Hex int' },
  { label: '0o', type: 'value', info: 'Octal int' },
  { label: '0b', type: 'value', info: 'Binary int' },
  // Snippets
  { label: 'dep-version', type: 'snippet', apply: '${name} = "${version}"', info: 'Simple dep' },
  { label: 'dep-detailed', type: 'snippet', apply: '${name} = { version = "${version}", features = [${feats}] }', info: 'Detailed dep' },
  { label: 'dep-git', type: 'snippet', apply: '${name} = { git = "${url}", branch = "${branch}" }', info: 'Git dep' },
  { label: 'dep-path', type: 'snippet', apply: '${name} = { path = "${path}" }', info: 'Local path dep' },
  { label: 'table-dep', type: 'snippet', apply: '[dependencies.${name}]\nversion = "${version}"\nfeatures = [${feats}]', info: 'Table dep' },
  { label: 'profile-release', type: 'snippet', apply: '[profile.release]\nopt-level = 3\nlto = true\ncodegen-units = 1\nstrip = true', info: 'Tight release' },
  // Additional keys
  { label: 'workspace-inherit', type: 'snippet', apply: '${name} = { workspace = true }', info: 'Inherit from ws' },
  { label: 'MSRV', type: 'value', info: 'Min supported Rust' },
  // Build target triples
  { label: 'x86_64-unknown-linux-gnu', type: 'value', info: 'Linux GNU' },
  { label: 'x86_64-unknown-linux-musl', type: 'value', info: 'Linux musl' },
  { label: 'aarch64-unknown-linux-gnu', type: 'value', info: 'ARM64 Linux' },
  { label: 'aarch64-unknown-linux-musl', type: 'value', info: 'ARM64 musl' },
  { label: 'x86_64-apple-darwin', type: 'value', info: 'Intel Mac' },
  { label: 'aarch64-apple-darwin', type: 'value', info: 'Apple Silicon' },
  { label: 'x86_64-pc-windows-msvc', type: 'value', info: 'Windows MSVC' },
  { label: 'x86_64-pc-windows-gnu', type: 'value', info: 'Windows GNU' },
  { label: 'wasm32-unknown-unknown', type: 'value', info: 'WASM no runtime' },
  { label: 'wasm32-wasi', type: 'value', info: 'WASM WASI' },
  { label: 'thumbv7em-none-eabihf', type: 'value', info: 'ARM Cortex M4/7F' },
  // ruff rule selectors
  { label: '"E"', type: 'value', info: 'pycodestyle errors' },
  { label: '"F"', type: 'value', info: 'Pyflakes' },
  { label: '"W"', type: 'value', info: 'pycodestyle warnings' },
  { label: '"I"', type: 'value', info: 'isort' },
  { label: '"N"', type: 'value', info: 'pep8-naming' },
  { label: '"D"', type: 'value', info: 'pydocstyle' },
  { label: '"UP"', type: 'value', info: 'pyupgrade' },
  { label: '"S"', type: 'value', info: 'bandit' },
  { label: '"B"', type: 'value', info: 'bugbear' },
  { label: '"C4"', type: 'value', info: 'comprehensions' },
  { label: '"SIM"', type: 'value', info: 'simplify' },
  { label: '"PL"', type: 'value', info: 'pylint' },
  { label: '"RUF"', type: 'value', info: 'Ruff-specific' },
  { label: '"ALL"', type: 'value', info: 'All rules' },
  // Commonly used profile keys
  { label: '[profile.dev.package."*"]', type: 'section', info: 'Per-pkg dev' },
  { label: '[profile.release.package."*"]', type: 'section', info: 'Per-pkg rel' },
  { label: '[profile.release-with-debug]', type: 'section', info: 'Custom profile' },
  { label: 'inherits', type: 'property', info: 'Profile inherits' },
  // Wrangler / misc
  { label: 'compatibility_date', type: 'property', info: 'Workers compat' },
  { label: 'main', type: 'property', info: 'Entry file' },
  { label: 'route', type: 'property', info: 'Worker route' },
  { label: 'workers_dev', type: 'property', info: 'Workers dev' },
  { label: 'account_id', type: 'property', info: 'Workers account' },
  { label: 'zone_id', type: 'property', info: 'Workers zone' },
  { label: 'usage_model', type: 'property', info: 'Workers usage' },
  { label: '[vars]', type: 'section', info: 'Worker vars' },
  { label: '[durable_objects]', type: 'section', info: 'Durable objects' },
  { label: '[[kv_namespaces]]', type: 'section', info: 'KV ns list' },
  { label: '[[r2_buckets]]', type: 'section', info: 'R2 buckets' },
  { label: '[[d1_databases]]', type: 'section', info: 'D1 dbs' },
];
