// Completion entries for xml.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  { label: '<?xml?>', type: 'snippet', apply: '<?xml version="1.0" encoding="UTF-8"?>', info: 'XML declaration' },
  { label: '<!DOCTYPE>', type: 'snippet', apply: '<!DOCTYPE ${root} SYSTEM "${dtd}">', info: 'DOCTYPE' },
  { label: 'CDATA', type: 'snippet', apply: '<![CDATA[${text}]]>', info: 'CDATA section' },
  { label: 'comment', type: 'snippet', apply: '<!-- ${comment} -->', info: 'XML comment' },
  { label: 'xmlns', type: 'attribute', info: 'XML namespace' },
  { label: 'xmlns:xsi', type: 'attribute', info: 'XSI namespace' },
  { label: 'xsi:schemaLocation', type: 'attribute', info: 'XSD schema location' },
  { label: 'xsi:noNamespaceSchemaLocation', type: 'attribute', info: 'No-ns XSD loc' },
  { label: 'xsi:type', type: 'attribute', info: 'XSI type' },
  // Common XML
  { label: 'xml:lang', type: 'attribute', info: 'XML language' },
  { label: 'xml:space', type: 'attribute', info: 'XML space' },
  { label: 'xml:base', type: 'attribute', info: 'XML base URI' },
  { label: 'xml:id', type: 'attribute', info: 'XML ID' },
  // POM (Maven)
  { label: 'project', type: 'tag', info: 'POM root' },
  { label: 'modelVersion', type: 'tag', info: 'POM model version' },
  { label: 'groupId', type: 'tag', info: 'Maven groupId' },
  { label: 'artifactId', type: 'tag', info: 'Maven artifactId' },
  { label: 'version', type: 'tag', info: 'Artifact version' },
  { label: 'packaging', type: 'tag', info: 'Packaging type' },
  { label: 'parent', type: 'tag', info: 'Parent POM' },
  { label: 'properties', type: 'tag', info: 'Properties' },
  { label: 'dependencies', type: 'tag', info: 'Dependencies list' },
  { label: 'dependency', type: 'tag', info: 'Dependency entry' },
  { label: 'dependencyManagement', type: 'tag', info: 'Dep management' },
  { label: 'build', type: 'tag', info: 'Build settings' },
  { label: 'plugins', type: 'tag', info: 'Plugins list' },
  { label: 'plugin', type: 'tag', info: 'Plugin entry' },
  { label: 'pluginManagement', type: 'tag', info: 'Plugin management' },
  { label: 'repositories', type: 'tag', info: 'Repositories' },
  { label: 'repository', type: 'tag', info: 'Repository entry' },
  { label: 'pluginRepositories', type: 'tag', info: 'Plugin repositories' },
  { label: 'profiles', type: 'tag', info: 'Build profiles' },
  { label: 'profile', type: 'tag', info: 'Build profile' },
  { label: 'modules', type: 'tag', info: 'Submodules' },
  { label: 'scope', type: 'tag', info: 'Dep scope' },
  { label: 'optional', type: 'tag', info: 'Optional dep' },
  { label: 'exclusions', type: 'tag', info: 'Dep exclusions' },
  { label: 'exclusion', type: 'tag', info: 'Exclusion entry' },
  // Android manifest
  { label: 'manifest', type: 'tag', info: 'Android manifest' },
  { label: 'application', type: 'tag', info: 'Android application' },
  { label: 'activity', type: 'tag', info: 'Android activity' },
  { label: 'service', type: 'tag', info: 'Android service' },
  { label: 'receiver', type: 'tag', info: 'Broadcast receiver' },
  { label: 'provider', type: 'tag', info: 'Content provider' },
  { label: 'intent-filter', type: 'tag', info: 'Intent filter' },
  { label: 'action', type: 'tag', info: 'Intent action' },
  { label: 'category', type: 'tag', info: 'Intent category' },
  { label: 'data', type: 'tag', info: 'Intent data' },
  { label: 'uses-permission', type: 'tag', info: 'Permission usage' },
  { label: 'permission', type: 'tag', info: 'Permission decl' },
  { label: 'uses-feature', type: 'tag', info: 'Feature req' },
  { label: 'uses-sdk', type: 'tag', info: 'SDK version' },
  { label: 'meta-data', type: 'tag', info: 'Manifest metadata' },
  // RSS/Atom
  { label: 'rss', type: 'tag', info: 'RSS root' },
  { label: 'channel', type: 'tag', info: 'RSS channel' },
  { label: 'item', type: 'tag', info: 'RSS item' },
  { label: 'title', type: 'tag', info: 'Title' },
  { label: 'link', type: 'tag', info: 'Link' },
  { label: 'description', type: 'tag', info: 'Description' },
  { label: 'pubDate', type: 'tag', info: 'Publication date' },
  { label: 'guid', type: 'tag', info: 'Unique identifier' },
  { label: 'author', type: 'tag', info: 'Author email' },
  { label: 'category', type: 'tag', info: 'Category' },
  { label: 'enclosure', type: 'tag', info: 'Media enclosure' },
  { label: 'feed', type: 'tag', info: 'Atom feed root' },
  { label: 'entry', type: 'tag', info: 'Atom entry' },
  { label: 'id', type: 'tag', info: 'Atom entry ID' },
  { label: 'updated', type: 'tag', info: 'Updated time' },
  { label: 'published', type: 'tag', info: 'Published time' },
  { label: 'summary', type: 'tag', info: 'Summary' },
  { label: 'content', type: 'tag', info: 'Content' },
  // SVG
  { label: 'svg', type: 'tag', info: 'SVG root' },
  { label: 'path', type: 'tag', info: 'SVG path' },
  { label: 'rect', type: 'tag', info: 'SVG rectangle' },
  { label: 'circle', type: 'tag', info: 'SVG circle' },
  { label: 'ellipse', type: 'tag', info: 'SVG ellipse' },
  { label: 'line', type: 'tag', info: 'SVG line' },
  { label: 'polyline', type: 'tag', info: 'SVG polyline' },
  { label: 'polygon', type: 'tag', info: 'SVG polygon' },
  { label: 'g', type: 'tag', info: 'SVG group' },
  { label: 'text', type: 'tag', info: 'SVG text' },
  { label: 'tspan', type: 'tag', info: 'SVG text span' },
  { label: 'defs', type: 'tag', info: 'SVG defs' },
  { label: 'use', type: 'tag', info: 'SVG use' },
  { label: 'symbol', type: 'tag', info: 'SVG symbol' },
  { label: 'linearGradient', type: 'tag', info: 'Linear gradient' },
  { label: 'radialGradient', type: 'tag', info: 'Radial gradient' },
  { label: 'stop', type: 'tag', info: 'Gradient stop' },
  { label: 'clipPath', type: 'tag', info: 'SVG clipPath' },
  { label: 'mask', type: 'tag', info: 'SVG mask' },
  { label: 'pattern', type: 'tag', info: 'SVG pattern' },
  { label: 'marker', type: 'tag', info: 'SVG marker' },
  { label: 'animate', type: 'tag', info: 'SVG animate' },
  { label: 'animateTransform', type: 'tag', info: 'SVG animateTransform' },
  { label: 'filter', type: 'tag', info: 'SVG filter' },
  // Android AndroidManifest.xml
  { label: 'manifest', type: 'tag', info: 'Android root' },
  { label: 'application', type: 'tag', info: 'App tag' },
  { label: 'activity', type: 'tag', info: 'Activity tag' },
  { label: 'activity-alias', type: 'tag', info: 'Activity alias' },
  { label: 'service', type: 'tag', info: 'Service tag' },
  { label: 'receiver', type: 'tag', info: 'Broadcast receiver' },
  { label: 'provider', type: 'tag', info: 'Content provider' },
  { label: 'uses-permission', type: 'tag', info: 'Permission required' },
  { label: 'uses-permission-sdk-23', type: 'tag', info: 'Perm SDK 23+' },
  { label: 'permission', type: 'tag', info: 'Define permission' },
  { label: 'permission-group', type: 'tag', info: 'Permission group' },
  { label: 'permission-tree', type: 'tag', info: 'Permission tree' },
  { label: 'uses-feature', type: 'tag', info: 'Feature required' },
  { label: 'uses-sdk', type: 'tag', info: 'Min/target SDK' },
  { label: 'uses-library', type: 'tag', info: 'Shared library' },
  { label: 'uses-configuration', type: 'tag', info: 'Input config' },
  { label: 'intent-filter', type: 'tag', info: 'Intent filter' },
  { label: 'action', type: 'tag', info: 'Intent action' },
  { label: 'category', type: 'tag', info: 'Intent category' },
  { label: 'data', type: 'tag', info: 'Intent data' },
  { label: 'meta-data', type: 'tag', info: 'Metadata entry' },
  { label: 'grant-uri-permission', type: 'tag', info: 'Grant URI perm' },
  { label: 'path-permission', type: 'tag', info: 'Path permission' },
  { label: 'supports-screens', type: 'tag', info: 'Supported screens' },
  { label: 'compatible-screens', type: 'tag', info: 'Compatible screens' },
  { label: 'supports-gl-texture', type: 'tag', info: 'GL texture' },
  { label: 'queries', type: 'tag', info: 'Pkg queries' },
  { label: 'profileable', type: 'tag', info: 'Profileable' },
  // Android common attributes
  { label: 'android:name', type: 'attr', info: 'Component name' },
  { label: 'android:label', type: 'attr', info: 'Display label' },
  { label: 'android:icon', type: 'attr', info: 'Icon resource' },
  { label: 'android:roundIcon', type: 'attr', info: 'Round icon' },
  { label: 'android:banner', type: 'attr', info: 'TV banner' },
  { label: 'android:theme', type: 'attr', info: 'App/activity theme' },
  { label: 'android:allowBackup', type: 'attr', info: 'Allow backup' },
  { label: 'android:fullBackupContent', type: 'attr', info: 'Full backup cfg' },
  { label: 'android:networkSecurityConfig', type: 'attr', info: 'Net security cfg' },
  { label: 'android:usesCleartextTraffic', type: 'attr', info: 'Clear HTTP' },
  { label: 'android:requestLegacyExternalStorage', type: 'attr', info: 'Legacy storage' },
  { label: 'android:hasFragileUserData', type: 'attr', info: 'Fragile data' },
  { label: 'android:hardwareAccelerated', type: 'attr', info: 'HW accel' },
  { label: 'android:debuggable', type: 'attr', info: 'Debuggable flag' },
  { label: 'android:installLocation', type: 'attr', info: 'Install location' },
  { label: 'android:targetSdkVersion', type: 'attr', info: 'Target SDK' },
  { label: 'android:minSdkVersion', type: 'attr', info: 'Min SDK' },
  { label: 'android:maxSdkVersion', type: 'attr', info: 'Max SDK' },
  { label: 'android:versionCode', type: 'attr', info: 'Version code' },
  { label: 'android:versionName', type: 'attr', info: 'Version name' },
  { label: 'android:exported', type: 'attr', info: 'Component exported' },
  { label: 'android:enabled', type: 'attr', info: 'Component enabled' },
  { label: 'android:process', type: 'attr', info: 'Process name' },
  { label: 'android:taskAffinity', type: 'attr', info: 'Task affinity' },
  { label: 'android:launchMode', type: 'attr', info: 'Launch mode' },
  { label: 'android:screenOrientation', type: 'attr', info: 'Screen orientation' },
  { label: 'android:configChanges', type: 'attr', info: 'Config changes' },
  { label: 'android:windowSoftInputMode', type: 'attr', info: 'IME mode' },
  { label: 'android:parentActivityName', type: 'attr', info: 'Parent activity' },
  { label: 'android:documentLaunchMode', type: 'attr', info: 'Doc launch' },
  { label: 'android:maxRecents', type: 'attr', info: 'Max recents' },
  { label: 'android:resizeableActivity', type: 'attr', info: 'Resizeable' },
  { label: 'android:supportsPictureInPicture', type: 'attr', info: 'PiP support' },
  { label: 'android:noHistory', type: 'attr', info: 'No history' },
  { label: 'android:finishOnTaskLaunch', type: 'attr', info: 'Finish on launch' },
  { label: 'android:clearTaskOnLaunch', type: 'attr', info: 'Clear task' },
  { label: 'android:alwaysRetainTaskState', type: 'attr', info: 'Retain task' },
  { label: 'android:stateNotNeeded', type: 'attr', info: 'State not needed' },
  { label: 'android:excludeFromRecents', type: 'attr', info: 'Exclude recents' },
  { label: 'android:multiprocess', type: 'attr', info: 'Multiprocess' },
  { label: 'android:permission', type: 'attr', info: 'Required perm' },
  { label: 'android:readPermission', type: 'attr', info: 'Read permission' },
  { label: 'android:writePermission', type: 'attr', info: 'Write permission' },
  { label: 'android:grantUriPermissions', type: 'attr', info: 'Grant URI perms' },
  { label: 'android:authorities', type: 'attr', info: 'Provider authorities' },
  { label: 'android:scheme', type: 'attr', info: 'URI scheme' },
  { label: 'android:host', type: 'attr', info: 'URI host' },
  { label: 'android:port', type: 'attr', info: 'URI port' },
  { label: 'android:path', type: 'attr', info: 'URI path' },
  { label: 'android:pathPattern', type: 'attr', info: 'URI path pattern' },
  { label: 'android:pathPrefix', type: 'attr', info: 'URI path prefix' },
  { label: 'android:mimeType', type: 'attr', info: 'MIME type' },
  { label: 'android:required', type: 'attr', info: 'Feature required' },
  { label: 'android:glEsVersion', type: 'attr', info: 'OpenGL ES ver' },
  { label: 'android:smallScreens', type: 'attr', info: 'Small screens' },
  { label: 'android:normalScreens', type: 'attr', info: 'Normal screens' },
  { label: 'android:largeScreens', type: 'attr', info: 'Large screens' },
  { label: 'android:xlargeScreens', type: 'attr', info: 'X-large screens' },
  { label: 'android:anyDensity', type: 'attr', info: 'Any density' },
  { label: 'android:resizeable', type: 'attr', info: 'Resizeable screen' },
  { label: 'android:requiresSmallestWidthDp', type: 'attr', info: 'Smallest width' },
  { label: 'android:compileSdkVersion', type: 'attr', info: 'Compile SDK' },
  { label: 'xmlns:android', type: 'attr', info: 'Android ns' },
  { label: 'xmlns:tools', type: 'attr', info: 'Tools ns' },
  // Maven pom.xml
  { label: 'project', type: 'tag', info: 'Maven root' },
  { label: 'modelVersion', type: 'tag', info: 'POM model ver' },
  { label: 'groupId', type: 'tag', info: 'Group ID' },
  { label: 'artifactId', type: 'tag', info: 'Artifact ID' },
  { label: 'packaging', type: 'tag', info: 'Packaging type' },
  { label: 'parent', type: 'tag', info: 'Parent POM' },
  { label: 'relativePath', type: 'tag', info: 'Parent rel path' },
  { label: 'properties', type: 'tag', info: 'POM properties' },
  { label: 'dependencies', type: 'tag', info: 'Dependency list' },
  { label: 'dependency', type: 'tag', info: 'Dependency entry' },
  { label: 'dependencyManagement', type: 'tag', info: 'Dep management' },
  { label: 'scope', type: 'tag', info: 'Dependency scope' },
  { label: 'classifier', type: 'tag', info: 'Dep classifier' },
  { label: 'exclusions', type: 'tag', info: 'Dep exclusions' },
  { label: 'exclusion', type: 'tag', info: 'Exclude dep' },
  { label: 'optional', type: 'tag', info: 'Optional dep' },
  { label: 'systemPath', type: 'tag', info: 'System path' },
  { label: 'build', type: 'tag', info: 'Build config' },
  { label: 'plugins', type: 'tag', info: 'Plugin list' },
  { label: 'plugin', type: 'tag', info: 'Plugin entry' },
  { label: 'pluginManagement', type: 'tag', info: 'Plugin mgmt' },
  { label: 'executions', type: 'tag', info: 'Plugin executions' },
  { label: 'execution', type: 'tag', info: 'Execution entry' },
  { label: 'goals', type: 'tag', info: 'Plugin goals' },
  { label: 'goal', type: 'tag', info: 'Goal entry' },
  { label: 'phase', type: 'tag', info: 'Build phase' },
  { label: 'configuration', type: 'tag', info: 'Plugin cfg' },
  { label: 'finalName', type: 'tag', info: 'Build final name' },
  { label: 'directory', type: 'tag', info: 'Output dir' },
  { label: 'outputDirectory', type: 'tag', info: 'Classes dir' },
  { label: 'testOutputDirectory', type: 'tag', info: 'Test classes dir' },
  { label: 'sourceDirectory', type: 'tag', info: 'Source dir' },
  { label: 'scriptSourceDirectory', type: 'tag', info: 'Script src dir' },
  { label: 'testSourceDirectory', type: 'tag', info: 'Test src dir' },
  { label: 'resources', type: 'tag', info: 'Resources' },
  { label: 'resource', type: 'tag', info: 'Resource entry' },
  { label: 'testResources', type: 'tag', info: 'Test resources' },
  { label: 'includes', type: 'tag', info: 'Include patterns' },
  { label: 'excludes', type: 'tag', info: 'Exclude patterns' },
  { label: 'filters', type: 'tag', info: 'Filter props' },
  { label: 'filtering', type: 'tag', info: 'Enable filtering' },
  { label: 'profiles', type: 'tag', info: 'Build profiles' },
  { label: 'profile', type: 'tag', info: 'Profile entry' },
  { label: 'activation', type: 'tag', info: 'Profile activation' },
  { label: 'activeByDefault', type: 'tag', info: 'Active default' },
  { label: 'modules', type: 'tag', info: 'Reactor modules' },
  { label: 'module', type: 'tag', info: 'Module entry' },
  { label: 'scm', type: 'tag', info: 'SCM info' },
  { label: 'connection', type: 'tag', info: 'SCM connection' },
  { label: 'developerConnection', type: 'tag', info: 'Dev SCM' },
  { label: 'distributionManagement', type: 'tag', info: 'Deploy target' },
  { label: 'repositories', type: 'tag', info: 'Repositories' },
  { label: 'repository', type: 'tag', info: 'Repository entry' },
  { label: 'pluginRepositories', type: 'tag', info: 'Plugin repos' },
  { label: 'pluginRepository', type: 'tag', info: 'Plugin repo' },
  { label: 'releases', type: 'tag', info: 'Release policy' },
  { label: 'snapshots', type: 'tag', info: 'Snapshot policy' },
  { label: 'updatePolicy', type: 'tag', info: 'Update policy' },
  { label: 'checksumPolicy', type: 'tag', info: 'Checksum policy' },
  { label: 'developers', type: 'tag', info: 'Developers' },
  { label: 'developer', type: 'tag', info: 'Developer entry' },
  { label: 'contributors', type: 'tag', info: 'Contributors' },
  { label: 'contributor', type: 'tag', info: 'Contributor entry' },
  { label: 'licenses', type: 'tag', info: 'Licenses' },
  { label: 'mailingLists', type: 'tag', info: 'Mailing lists' },
  { label: 'mailingList', type: 'tag', info: 'Mailing list' },
  { label: 'issueManagement', type: 'tag', info: 'Issue tracker' },
  { label: 'ciManagement', type: 'tag', info: 'CI system' },
  { label: 'inceptionYear', type: 'tag', info: 'Inception year' },
  { label: 'organization', type: 'tag', info: 'Organization' },
  { label: 'reporting', type: 'tag', info: 'Site reporting' },
  { label: 'reports', type: 'tag', info: 'Reports' },
  // XSLT 3.0
  { label: 'xsl:stylesheet', type: 'tag', info: 'XSLT root' },
  { label: 'xsl:transform', type: 'tag', info: 'XSLT root alt' },
  { label: 'xsl:template', type: 'tag', info: 'XSLT template' },
  { label: 'xsl:apply-templates', type: 'tag', info: 'Apply templates' },
  { label: 'xsl:call-template', type: 'tag', info: 'Call template' },
  { label: 'xsl:apply-imports', type: 'tag', info: 'Apply imports' },
  { label: 'xsl:param', type: 'tag', info: 'Template param' },
  { label: 'xsl:with-param', type: 'tag', info: 'Pass param' },
  { label: 'xsl:variable', type: 'tag', info: 'Variable decl' },
  { label: 'xsl:value-of', type: 'tag', info: 'Output value' },
  { label: 'xsl:for-each', type: 'tag', info: 'Iterate nodes' },
  { label: 'xsl:for-each-group', type: 'tag', info: 'Group iterate' },
  { label: 'xsl:if', type: 'tag', info: 'Conditional' },
  { label: 'xsl:choose', type: 'tag', info: 'Choose block' },
  { label: 'xsl:when', type: 'tag', info: 'Choose when' },
  { label: 'xsl:otherwise', type: 'tag', info: 'Choose else' },
  { label: 'xsl:sort', type: 'tag', info: 'Sort items' },
  { label: 'xsl:copy', type: 'tag', info: 'Copy node' },
  { label: 'xsl:copy-of', type: 'tag', info: 'Copy subtree' },
  { label: 'xsl:element', type: 'tag', info: 'Create element' },
  { label: 'xsl:attribute', type: 'tag', info: 'Create attr' },
  { label: 'xsl:attribute-set', type: 'tag', info: 'Attribute set' },
  { label: 'xsl:text', type: 'tag', info: 'Literal text' },
  { label: 'xsl:number', type: 'tag', info: 'Format number' },
  { label: 'xsl:function', type: 'tag', info: 'Function decl' },
  { label: 'xsl:accumulator', type: 'tag', info: 'Accumulator' },
  { label: 'xsl:accumulator-rule', type: 'tag', info: 'Acc rule' },
  { label: 'xsl:try', type: 'tag', info: 'Try block' },
  { label: 'xsl:catch', type: 'tag', info: 'Catch block' },
  { label: 'xsl:iterate', type: 'tag', info: 'Iterate w/ state' },
  { label: 'xsl:next-iteration', type: 'tag', info: 'Next iter' },
  { label: 'xsl:break', type: 'tag', info: 'Break iter' },
  { label: 'xsl:import', type: 'tag', info: 'Import stylesheet' },
  { label: 'xsl:include', type: 'tag', info: 'Include stylesheet' },
  { label: 'xsl:output', type: 'tag', info: 'Output config' },
  { label: 'xsl:strip-space', type: 'tag', info: 'Strip whitespace' },
  { label: 'xsl:preserve-space', type: 'tag', info: 'Preserve whitespace' },
  { label: 'xsl:namespace', type: 'tag', info: 'Namespace node' },
  { label: 'xsl:namespace-alias', type: 'tag', info: 'Alias ns' },
  { label: 'xsl:processing-instruction', type: 'tag', info: 'PI node' },
  { label: 'xsl:comment', type: 'tag', info: 'Comment node' },
  { label: 'xsl:document', type: 'tag', info: 'Document node' },
  { label: 'xsl:result-document', type: 'tag', info: 'Result doc' },
  { label: 'xsl:analyze-string', type: 'tag', info: 'Regex analyze' },
  { label: 'xsl:matching-substring', type: 'tag', info: 'Match subs' },
  { label: 'xsl:non-matching-substring', type: 'tag', info: 'Non-match subs' },
  { label: 'xsl:key', type: 'tag', info: 'Define key' },
  { label: 'xsl:decimal-format', type: 'tag', info: 'Decimal format' },
  { label: 'xsl:sequence', type: 'tag', info: 'Return sequence' },
  { label: 'xsl:map', type: 'tag', info: 'Build map' },
  { label: 'xsl:map-entry', type: 'tag', info: 'Map entry' },
  { label: 'xsl:array', type: 'tag', info: 'Build array' },
  { label: 'xsl:array-member', type: 'tag', info: 'Array member' },
  { label: 'xsl:fallback', type: 'tag', info: 'XSLT fallback' },
  { label: 'xsl:message', type: 'tag', info: 'Print message' },
  { label: 'xsl:assert', type: 'tag', info: 'Assert cond' },
  { label: 'xsl:evaluate', type: 'tag', info: 'Eval XPath' },
  { label: 'xsl:expression', type: 'tag', info: 'Expression' },
  { label: 'xsl:on-completion', type: 'tag', info: 'Iter completion' },
  { label: 'xsl:global-context-item', type: 'tag', info: 'Global context' },
  { label: 'xsl:mode', type: 'tag', info: 'XSLT mode' },
  // XSLT attrs
  { label: 'match', type: 'attr', info: 'Template match' },
  { label: 'select', type: 'attr', info: 'XPath select' },
  { label: 'test', type: 'attr', info: 'XPath test' },
  { label: 'as', type: 'attr', info: 'Type decl' },
  { label: 'use', type: 'attr', info: 'Key use' },
  { label: 'priority', type: 'attr', info: 'Template prio' },
  { label: 'mode', type: 'attr', info: 'Template mode' },
  // XSD Schema
  { label: 'xs:schema', type: 'tag', info: 'XSD root' },
  { label: 'xs:element', type: 'tag', info: 'Element decl' },
  { label: 'xs:attribute', type: 'tag', info: 'Attribute decl' },
  { label: 'xs:attributeGroup', type: 'tag', info: 'Attribute group' },
  { label: 'xs:group', type: 'tag', info: 'Element group' },
  { label: 'xs:complexType', type: 'tag', info: 'Complex type' },
  { label: 'xs:simpleType', type: 'tag', info: 'Simple type' },
  { label: 'xs:complexContent', type: 'tag', info: 'Complex content' },
  { label: 'xs:simpleContent', type: 'tag', info: 'Simple content' },
  { label: 'xs:sequence', type: 'tag', info: 'Sequence' },
  { label: 'xs:choice', type: 'tag', info: 'Choice' },
  { label: 'xs:all', type: 'tag', info: 'All group' },
  { label: 'xs:any', type: 'tag', info: 'Any element' },
  { label: 'xs:anyAttribute', type: 'tag', info: 'Any attribute' },
  { label: 'xs:restriction', type: 'tag', info: 'Restriction' },
  { label: 'xs:extension', type: 'tag', info: 'Extension' },
  { label: 'xs:list', type: 'tag', info: 'List type' },
  { label: 'xs:union', type: 'tag', info: 'Union type' },
  { label: 'xs:enumeration', type: 'tag', info: 'Enum facet' },
  { label: 'xs:pattern', type: 'tag', info: 'Pattern facet' },
  { label: 'xs:minInclusive', type: 'tag', info: 'Min inclusive' },
  { label: 'xs:maxInclusive', type: 'tag', info: 'Max inclusive' },
  { label: 'xs:minExclusive', type: 'tag', info: 'Min exclusive' },
  { label: 'xs:maxExclusive', type: 'tag', info: 'Max exclusive' },
  { label: 'xs:length', type: 'tag', info: 'Length facet' },
  { label: 'xs:minLength', type: 'tag', info: 'Min length' },
  { label: 'xs:maxLength', type: 'tag', info: 'Max length' },
  { label: 'xs:totalDigits', type: 'tag', info: 'Total digits' },
  { label: 'xs:fractionDigits', type: 'tag', info: 'Fraction digits' },
  { label: 'xs:whiteSpace', type: 'tag', info: 'Whitespace facet' },
  { label: 'xs:annotation', type: 'tag', info: 'Annotation' },
  { label: 'xs:appinfo', type: 'tag', info: 'App info' },
  { label: 'xs:documentation', type: 'tag', info: 'Documentation' },
  { label: 'xs:include', type: 'tag', info: 'Include schema' },
  { label: 'xs:import', type: 'tag', info: 'Import schema' },
  { label: 'xs:redefine', type: 'tag', info: 'Redefine schema' },
  { label: 'xs:override', type: 'tag', info: 'Override schema' },
  { label: 'xs:notation', type: 'tag', info: 'Notation decl' },
  { label: 'xs:field', type: 'tag', info: 'Field selector' },
  { label: 'xs:selector', type: 'tag', info: 'Key selector' },
  { label: 'xs:key', type: 'tag', info: 'Key constraint' },
  { label: 'xs:keyref', type: 'tag', info: 'Keyref' },
  { label: 'xs:unique', type: 'tag', info: 'Unique constraint' },
  // XSD attrs
  { label: 'minOccurs', type: 'attr', info: 'Min occurs' },
  { label: 'maxOccurs', type: 'attr', info: 'Max occurs' },
  { label: 'nillable', type: 'attr', info: 'Nillable' },
  { label: 'base', type: 'attr', info: 'Base type' },
  { label: 'targetNamespace', type: 'attr', info: 'Target ns' },
  { label: 'elementFormDefault', type: 'attr', info: 'Element form' },
  { label: 'attributeFormDefault', type: 'attr', info: 'Attribute form' },
  { label: 'xmlns:xs', type: 'attr', info: 'XSD ns' },
  // SVG presentation attributes
  { label: 'fill', type: 'attr', info: 'SVG fill' },
  { label: 'stroke', type: 'attr', info: 'SVG stroke' },
  { label: 'stroke-width', type: 'attr', info: 'Stroke width' },
  { label: 'stroke-linecap', type: 'attr', info: 'Stroke linecap' },
  { label: 'stroke-linejoin', type: 'attr', info: 'Stroke linejoin' },
  { label: 'stroke-miterlimit', type: 'attr', info: 'Miter limit' },
  { label: 'stroke-dasharray', type: 'attr', info: 'Dash array' },
  { label: 'stroke-dashoffset', type: 'attr', info: 'Dash offset' },
  { label: 'stroke-opacity', type: 'attr', info: 'Stroke opacity' },
  { label: 'fill-opacity', type: 'attr', info: 'Fill opacity' },
  { label: 'fill-rule', type: 'attr', info: 'Fill rule' },
  { label: 'opacity', type: 'attr', info: 'Opacity' },
  { label: 'transform', type: 'attr', info: 'Transform' },
  { label: 'cx', type: 'attr', info: 'Center X' },
  { label: 'cy', type: 'attr', info: 'Center Y' },
  { label: 'r', type: 'attr', info: 'Radius' },
  { label: 'rx', type: 'attr', info: 'Radius X' },
  { label: 'ry', type: 'attr', info: 'Radius Y' },
  { label: 'x1', type: 'attr', info: 'X1' },
  { label: 'y1', type: 'attr', info: 'Y1' },
  { label: 'x2', type: 'attr', info: 'X2' },
  { label: 'y2', type: 'attr', info: 'Y2' },
  { label: 'points', type: 'attr', info: 'Polyline points' },
  { label: 'd', type: 'attr', info: 'Path data' },
  { label: 'viewBox', type: 'attr', info: 'SVG viewBox' },
  { label: 'preserveAspectRatio', type: 'attr', info: 'Aspect ratio' },
  { label: 'xlink:href', type: 'attr', info: 'xlink href' },
  { label: 'font-family', type: 'attr', info: 'Font family' },
  { label: 'font-size', type: 'attr', info: 'Font size' },
  { label: 'font-weight', type: 'attr', info: 'Font weight' },
  { label: 'text-anchor', type: 'attr', info: 'Text anchor' },
  { label: 'dominant-baseline', type: 'attr', info: 'Baseline' },
  { label: 'color', type: 'attr', info: 'Color attr' },
  { label: 'cursor', type: 'attr', info: 'Cursor' },
  { label: 'display', type: 'attr', info: 'Display' },
  { label: 'visibility', type: 'attr', info: 'Visibility' },
  { label: 'clip-path', type: 'attr', info: 'Clip path' },
  { label: 'clip-rule', type: 'attr', info: 'Clip rule' },
  { label: 'mask', type: 'attr', info: 'Mask' },
  { label: 'pointer-events', type: 'attr', info: 'Pointer events' },
  { label: 'marker-start', type: 'attr', info: 'Marker start' },
  { label: 'marker-mid', type: 'attr', info: 'Marker mid' },
  { label: 'marker-end', type: 'attr', info: 'Marker end' },
  { label: 'vector-effect', type: 'attr', info: 'Vector effect' },
  { label: 'stop-color', type: 'attr', info: 'Gradient stop' },
  { label: 'stop-opacity', type: 'attr', info: 'Stop opacity' },
  { label: 'offset', type: 'attr', info: 'Stop offset' },
  { label: 'gradientUnits', type: 'attr', info: 'Gradient units' },
  { label: 'gradientTransform', type: 'attr', info: 'Gradient xform' },
  { label: 'spreadMethod', type: 'attr', info: 'Spread method' },
  { label: 'patternUnits', type: 'attr', info: 'Pattern units' },
  { label: 'patternContentUnits', type: 'attr', info: 'Pattern content units' },
  { label: 'patternTransform', type: 'attr', info: 'Pattern xform' },
  { label: 'filterUnits', type: 'attr', info: 'Filter units' },
  { label: 'primitiveUnits', type: 'attr', info: 'Primitive units' },
  // SVG filter primitives
  { label: 'feBlend', type: 'tag', info: 'SVG feBlend' },
  { label: 'feColorMatrix', type: 'tag', info: 'SVG feColorMatrix' },
  { label: 'feComponentTransfer', type: 'tag', info: 'SVG feCompXfer' },
  { label: 'feComposite', type: 'tag', info: 'SVG feComposite' },
  { label: 'feConvolveMatrix', type: 'tag', info: 'SVG feConvolve' },
  { label: 'feDiffuseLighting', type: 'tag', info: 'SVG feDiffuse' },
  { label: 'feDisplacementMap', type: 'tag', info: 'SVG feDisplace' },
  { label: 'feDistantLight', type: 'tag', info: 'SVG feDistantLight' },
  { label: 'feDropShadow', type: 'tag', info: 'SVG feDropShadow' },
  { label: 'feFlood', type: 'tag', info: 'SVG feFlood' },
  { label: 'feFuncA', type: 'tag', info: 'SVG feFuncA' },
  { label: 'feFuncR', type: 'tag', info: 'SVG feFuncR' },
  { label: 'feFuncG', type: 'tag', info: 'SVG feFuncG' },
  { label: 'feFuncB', type: 'tag', info: 'SVG feFuncB' },
  { label: 'feGaussianBlur', type: 'tag', info: 'SVG blur' },
  { label: 'feImage', type: 'tag', info: 'SVG feImage' },
  { label: 'feMerge', type: 'tag', info: 'SVG feMerge' },
  { label: 'feMergeNode', type: 'tag', info: 'SVG feMergeNode' },
  { label: 'feMorphology', type: 'tag', info: 'SVG morphology' },
  { label: 'feOffset', type: 'tag', info: 'SVG feOffset' },
  { label: 'fePointLight', type: 'tag', info: 'SVG fePointLight' },
  { label: 'feSpecularLighting', type: 'tag', info: 'SVG specular' },
  { label: 'feSpotLight', type: 'tag', info: 'SVG feSpotLight' },
  { label: 'feTile', type: 'tag', info: 'SVG feTile' },
  { label: 'feTurbulence', type: 'tag', info: 'SVG turbulence' },
  // SOAP
  { label: 'soap:Envelope', type: 'tag', info: 'SOAP envelope' },
  { label: 'soap:Header', type: 'tag', info: 'SOAP header' },
  { label: 'soap:Body', type: 'tag', info: 'SOAP body' },
  { label: 'soap:Fault', type: 'tag', info: 'SOAP fault' },
  { label: 'faultcode', type: 'tag', info: 'SOAP fault code' },
  { label: 'faultstring', type: 'tag', info: 'SOAP fault str' },
  { label: 'faultactor', type: 'tag', info: 'SOAP fault actor' },
  { label: 'detail', type: 'tag', info: 'SOAP detail' },
  { label: 'soap:encodingStyle', type: 'attr', info: 'Encoding style' },
  { label: 'xmlns:soap', type: 'attr', info: 'SOAP ns' },
  // WSDL
  { label: 'definitions', type: 'tag', info: 'WSDL root' },
  { label: 'types', type: 'tag', info: 'WSDL types' },
  { label: 'message', type: 'tag', info: 'WSDL message' },
  { label: 'portType', type: 'tag', info: 'WSDL portType' },
  { label: 'binding', type: 'tag', info: 'WSDL binding' },
  { label: 'port', type: 'tag', info: 'WSDL port' },
  { label: 'operation', type: 'tag', info: 'WSDL operation' },
  { label: 'input', type: 'tag', info: 'WSDL input' },
  { label: 'output', type: 'tag', info: 'WSDL output' },
  { label: 'fault', type: 'tag', info: 'WSDL fault' },
  // RSS 2.0
  { label: 'rss', type: 'tag', info: 'RSS root' },
  { label: 'channel', type: 'tag', info: 'RSS channel' },
  { label: 'item', type: 'tag', info: 'RSS item' },
  { label: 'pubDate', type: 'tag', info: 'Publish date' },
  { label: 'lastBuildDate', type: 'tag', info: 'Last build' },
  { label: 'guid', type: 'tag', info: 'RSS GUID' },
  { label: 'enclosure', type: 'tag', info: 'RSS enclosure' },
  { label: 'ttl', type: 'tag', info: 'TTL minutes' },
  { label: 'generator', type: 'tag', info: 'Generator string' },
  { label: 'docs', type: 'tag', info: 'Docs URL' },
  { label: 'cloud', type: 'tag', info: 'Cloud notify' },
  { label: 'rating', type: 'tag', info: 'PICS rating' },
  { label: 'textInput', type: 'tag', info: 'RSS textInput' },
  { label: 'skipHours', type: 'tag', info: 'Skip hours' },
  { label: 'skipDays', type: 'tag', info: 'Skip days' },
  // Atom
  { label: 'feed', type: 'tag', info: 'Atom feed root' },
  { label: 'entry', type: 'tag', info: 'Atom entry' },
  { label: 'author', type: 'tag', info: 'Author' },
  { label: 'contributor', type: 'tag', info: 'Contributor' },
  { label: 'content', type: 'tag', info: 'Content' },
  { label: 'summary', type: 'tag', info: 'Summary' },
  { label: 'published', type: 'tag', info: 'Publish date' },
  { label: 'updated', type: 'tag', info: 'Updated date' },
  { label: 'rights', type: 'tag', info: 'Rights' },
  { label: 'subtitle', type: 'tag', info: 'Subtitle' },
  { label: 'logo', type: 'tag', info: 'Logo' },
  // XHTML common
  { label: 'html', type: 'tag', info: 'HTML root' },
  { label: 'head', type: 'tag', info: 'Head' },
  { label: 'body', type: 'tag', info: 'Body' },
  { label: 'title', type: 'tag', info: 'Page title' },
  { label: 'meta', type: 'tag', info: 'Meta tag' },
  { label: 'div', type: 'tag', info: 'Div container' },
  { label: 'span', type: 'tag', info: 'Span' },
  { label: 'p', type: 'tag', info: 'Paragraph' },
  { label: 'a', type: 'tag', info: 'Anchor' },
  { label: 'img', type: 'tag', info: 'Image' },
  { label: 'ul', type: 'tag', info: 'UL list' },
  { label: 'ol', type: 'tag', info: 'OL list' },
  { label: 'li', type: 'tag', info: 'List item' },
  { label: 'table', type: 'tag', info: 'Table' },
  { label: 'thead', type: 'tag', info: 'Table head' },
  { label: 'tbody', type: 'tag', info: 'Table body' },
  { label: 'tfoot', type: 'tag', info: 'Table foot' },
  { label: 'tr', type: 'tag', info: 'Table row' },
  { label: 'th', type: 'tag', info: 'Table header' },
  { label: 'td', type: 'tag', info: 'Table cell' },
  { label: 'form', type: 'tag', info: 'Form' },
  { label: 'input', type: 'tag', info: 'Input' },
  { label: 'button', type: 'tag', info: 'Button' },
  { label: 'label', type: 'tag', info: 'Label' },
  { label: 'script', type: 'tag', info: 'Script' },
  { label: 'style', type: 'tag', info: 'Style' },
  // DocBook basics
  { label: 'article', type: 'tag', info: 'DocBook article' },
  { label: 'book', type: 'tag', info: 'DocBook book' },
  { label: 'chapter', type: 'tag', info: 'DocBook chapter' },
  { label: 'section', type: 'tag', info: 'DocBook section' },
  { label: 'para', type: 'tag', info: 'DocBook paragraph' },
  { label: 'itemizedlist', type: 'tag', info: 'DocBook list' },
  { label: 'orderedlist', type: 'tag', info: 'Ordered list' },
  { label: 'listitem', type: 'tag', info: 'List item' },
  // Processing instructions
  { label: '<?xml', type: 'pi', info: 'XML declaration' },
  { label: '<?xml-stylesheet', type: 'pi', info: 'Stylesheet PI' },
  { label: '<![CDATA[', type: 'marker', info: 'CDATA section' },
  { label: ']]>', type: 'marker', info: 'CDATA end' },
  { label: '<!--', type: 'marker', info: 'Comment start' },
  { label: '-->', type: 'marker', info: 'Comment end' },
  { label: '<!DOCTYPE', type: 'marker', info: 'DOCTYPE decl' },
  { label: '&lt;', type: 'entity', info: 'Entity <' },
  { label: '&gt;', type: 'entity', info: 'Entity >' },
  { label: '&amp;', type: 'entity', info: 'Entity &' },
  { label: '&quot;', type: 'entity', info: 'Entity "' },
  { label: '&apos;', type: 'entity', info: "Entity '" },
  { label: '&nbsp;', type: 'entity', info: 'Non-breaking space' },
  // Gradle / Ant
  { label: 'target', type: 'tag', info: 'Ant target' },
  { label: 'property', type: 'tag', info: 'Ant property' },
  { label: 'condition', type: 'tag', info: 'Ant condition' },
  { label: 'available', type: 'tag', info: 'Ant available' },
  { label: 'echo', type: 'tag', info: 'Ant echo' },
  { label: 'fail', type: 'tag', info: 'Ant fail' },
  { label: 'javac', type: 'tag', info: 'Ant javac' },
  { label: 'jar', type: 'tag', info: 'Ant jar' },
  { label: 'war', type: 'tag', info: 'Ant war' },
  { label: 'copy', type: 'tag', info: 'Ant copy' },
  { label: 'delete', type: 'tag', info: 'Ant delete' },
  { label: 'mkdir', type: 'tag', info: 'Ant mkdir' },
  { label: 'move', type: 'tag', info: 'Ant move' },
  { label: 'exec', type: 'tag', info: 'Ant exec' },
  // NuGet .nuspec
  { label: 'package', type: 'tag', info: 'NuGet pkg root' },
  { label: 'frameworkAssemblies', type: 'tag', info: 'NuGet fx asm' },
  { label: 'frameworkAssembly', type: 'tag', info: 'FX assembly' },
  { label: 'files', type: 'tag', info: 'NuGet files' },
  { label: 'file', type: 'tag', info: 'NuGet file' },
  { label: 'contentFiles', type: 'tag', info: 'Content files' },
  { label: 'references', type: 'tag', info: 'NuGet refs' },
  { label: 'reference', type: 'tag', info: 'NuGet ref' },
  // XML signatures
  { label: 'Signature', type: 'tag', info: 'XML Dsig' },
  { label: 'SignedInfo', type: 'tag', info: 'Signed info' },
  { label: 'SignatureValue', type: 'tag', info: 'Sig value' },
  { label: 'KeyInfo', type: 'tag', info: 'Key info' },
  { label: 'Reference', type: 'tag', info: 'Signed ref' },
  { label: 'Transforms', type: 'tag', info: 'Xform chain' },
  { label: 'Transform', type: 'tag', info: 'Transform step' },
  { label: 'DigestMethod', type: 'tag', info: 'Digest method' },
  { label: 'DigestValue', type: 'tag', info: 'Digest value' },
  { label: 'CanonicalizationMethod', type: 'tag', info: 'C14N method' },
  { label: 'SignatureMethod', type: 'tag', info: 'Sig method' },
  // SAML
  { label: 'saml:Assertion', type: 'tag', info: 'SAML assertion' },
  { label: 'saml:Issuer', type: 'tag', info: 'SAML issuer' },
  { label: 'saml:Subject', type: 'tag', info: 'SAML subject' },
  { label: 'saml:Conditions', type: 'tag', info: 'SAML conds' },
  { label: 'saml:AuthnStatement', type: 'tag', info: 'SAML authn' },
  { label: 'saml:AttributeStatement', type: 'tag', info: 'SAML attrs' },
  { label: 'saml:Attribute', type: 'tag', info: 'SAML attr' },
  { label: 'samlp:Response', type: 'tag', info: 'SAML response' },
  { label: 'samlp:AuthnRequest', type: 'tag', info: 'SAML auth req' },
  { label: 'samlp:Status', type: 'tag', info: 'SAML status' },
  { label: 'samlp:StatusCode', type: 'tag', info: 'SAML status code' },
  // WS-Security
  { label: 'wsse:Security', type: 'tag', info: 'WS-Security' },
  { label: 'wsse:UsernameToken', type: 'tag', info: 'Username token' },
  { label: 'wsse:Username', type: 'tag', info: 'Username' },
  { label: 'wsse:Password', type: 'tag', info: 'Password' },
  { label: 'wsse:BinarySecurityToken', type: 'tag', info: 'Binary sec token' },
  { label: 'wsse:SecurityTokenReference', type: 'tag', info: 'Token ref' },
  // Additional tags
  { label: 'xsi:schemaLocation', type: 'attr', info: 'Schema location' },
  { label: 'xsi:noNamespaceSchemaLocation', type: 'attr', info: 'No-ns schema loc' },
  { label: 'xsi:type', type: 'attr', info: 'xsi type' },
  { label: 'xsi:nil', type: 'attr', info: 'xsi nil' },
  { label: 'xml:lang', type: 'attr', info: 'Lang' },
  { label: 'xml:space', type: 'attr', info: 'Whitespace handling' },
  { label: 'xml:base', type: 'attr', info: 'xml:base' },
  { label: 'xml:id', type: 'attr', info: 'xml:id' },
];
