// Completion entries for yaml.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  // Keywords
  { label: '---', type: 'keyword', info: 'Document start' },
  { label: '...', type: 'keyword', info: 'Document end' },
  { label: 'true', type: 'keyword', info: 'Boolean true' },
  { label: 'false', type: 'keyword', info: 'Boolean false' },
  { label: 'null', type: 'keyword', info: 'Null value' },
  // Syntax
  { label: '- ', type: 'snippet', apply: '- ${item}', info: 'List item' },
  { label: 'key: value', type: 'snippet', apply: '${key}: ${value}', info: 'Key-value pair' },
  { label: '|', type: 'snippet', apply: '${key}: |\n\t${multiline}', info: 'Literal block scalar' },
  { label: '>', type: 'snippet', apply: '${key}: >\n\t${folded}', info: 'Folded block scalar' },
  { label: '&', type: 'keyword', info: 'Anchor' },
  { label: '*', type: 'keyword', info: 'Alias' },
  { label: '!!', type: 'keyword', info: 'Tag' },
  // Common YAML structures
  {
    label: 'list',
    type: 'snippet',
    apply: '- ${item1}\n- ${item2}',
    info: 'Simple list'
  },
  {
    label: 'map',
    type: 'snippet',
    apply: '${key1}: ${value1}\n${key2}: ${value2}',
    info: 'Simple map'
  },
  {
    label: 'nested map',
    type: 'snippet',
    apply: '${parent}:\n\t${child}: ${value}',
    info: 'Nested map'
  },
  {
    label: 'list of maps',
    type: 'snippet',
    apply: '- ${key1}: ${value1}\n\t${key2}: ${value2}',
    info: 'List of maps'
  },
  // Common YAML keys (generic)
  { label: 'name', type: 'property', info: 'Name property' },
  { label: 'version', type: 'property', info: 'Version property' },
  { label: 'description', type: 'property', info: 'Description property' },
  { label: 'type', type: 'property', info: 'Type property' },
  { label: 'url', type: 'property', info: 'URL property' },
  { label: 'path', type: 'property', info: 'Path property' },
  { label: 'env', type: 'property', info: 'Environment variables' },
  { label: 'args', type: 'property', info: 'Arguments list' },
  { label: 'ports', type: 'property', info: 'Ports mapping' },
  { label: 'volumes', type: 'property', info: 'Volumes mapping' },
  // Docker Compose
  { label: 'services', type: 'property', info: 'Compose services' },
  { label: 'networks', type: 'property', info: 'Compose networks' },
  { label: 'configs', type: 'property', info: 'Compose configs' },
  { label: 'secrets', type: 'property', info: 'Compose secrets' },
  { label: 'image', type: 'property', info: 'Docker image' },
  { label: 'build', type: 'property', info: 'Build context' },
  { label: 'dockerfile', type: 'property', info: 'Dockerfile path' },
  { label: 'context', type: 'property', info: 'Build context dir' },
  { label: 'container_name', type: 'property', info: 'Container name' },
  { label: 'hostname', type: 'property', info: 'Container hostname' },
  { label: 'command', type: 'property', info: 'Override CMD' },
  { label: 'entrypoint', type: 'property', info: 'Override entrypoint' },
  { label: 'environment', type: 'property', info: 'Env vars (YAML)' },
  { label: 'env_file', type: 'property', info: 'Env file list' },
  { label: 'depends_on', type: 'property', info: 'Deps on services' },
  { label: 'restart', type: 'property', info: 'Restart policy' },
  { label: 'healthcheck', type: 'property', info: 'Health check' },
  { label: 'labels', type: 'property', info: 'Container labels' },
  { label: 'networks', type: 'property', info: 'Attached networks' },
  { label: 'expose', type: 'property', info: 'Internal ports' },
  { label: 'working_dir', type: 'property', info: 'Working dir' },
  { label: 'user', type: 'property', info: 'Run user' },
  { label: 'privileged', type: 'property', info: 'Privileged mode' },
  { label: 'cap_add', type: 'property', info: 'Add capabilities' },
  { label: 'cap_drop', type: 'property', info: 'Drop capabilities' },
  { label: 'tmpfs', type: 'property', info: 'tmpfs mounts' },
  { label: 'extra_hosts', type: 'property', info: 'Extra hosts file' },
  { label: 'dns', type: 'property', info: 'DNS servers' },
  { label: 'dns_search', type: 'property', info: 'DNS search list' },
  { label: 'stop_grace_period', type: 'property', info: 'Shutdown grace' },
  { label: 'init', type: 'property', info: 'Run init' },
  { label: 'mem_limit', type: 'property', info: 'Memory limit' },
  { label: 'cpus', type: 'property', info: 'CPU quota' },
  { label: 'replicas', type: 'property', info: 'Swarm replicas' },
  { label: 'resources', type: 'property', info: 'Resource limits' },
  { label: 'deploy', type: 'property', info: 'Deploy config' },
  { label: 'profiles', type: 'property', info: 'Compose profiles' },
  { label: 'target', type: 'property', info: 'Dockerfile target' },
  { label: 'pull_policy', type: 'property', info: 'Pull policy' },
  // GitHub Actions
  { label: 'on', type: 'property', info: 'Workflow triggers' },
  { label: 'jobs', type: 'property', info: 'Workflow jobs' },
  { label: 'steps', type: 'property', info: 'Job steps' },
  { label: 'uses', type: 'property', info: 'Use action' },
  { label: 'runs-on', type: 'property', info: 'Runner type' },
  { label: 'strategy', type: 'property', info: 'Matrix strategy' },
  { label: 'matrix', type: 'property', info: 'Job matrix' },
  { label: 'needs', type: 'property', info: 'Job dependencies' },
  { label: 'if', type: 'property', info: 'Conditional step' },
  { label: 'with', type: 'property', info: 'Action inputs' },
  { label: 'run', type: 'property', info: 'Shell command' },
  { label: 'working-directory', type: 'property', info: 'Work dir (GH)' },
  { label: 'shell', type: 'property', info: 'Shell type' },
  { label: 'timeout-minutes', type: 'property', info: 'Timeout minutes' },
  { label: 'continue-on-error', type: 'property', info: 'Continue on err' },
  { label: 'permissions', type: 'property', info: 'GITHUB_TOKEN perms' },
  { label: 'concurrency', type: 'property', info: 'Concurrency group' },
  { label: 'cancel-in-progress', type: 'property', info: 'Cancel in progress' },
  { label: 'schedule', type: 'property', info: 'Schedule trigger' },
  { label: 'cron', type: 'property', info: 'Cron expression' },
  { label: 'push', type: 'property', info: 'Push trigger' },
  { label: 'pull_request', type: 'property', info: 'PR trigger' },
  { label: 'workflow_dispatch', type: 'property', info: 'Manual trigger' },
  { label: 'workflow_call', type: 'property', info: 'Reusable workflow' },
  { label: 'repository_dispatch', type: 'property', info: 'Repo dispatch' },
  { label: 'paths', type: 'property', info: 'Path filters' },
  { label: 'paths-ignore', type: 'property', info: 'Path ignore' },
  { label: 'branches', type: 'property', info: 'Branch filters' },
  { label: 'branches-ignore', type: 'property', info: 'Branch ignore' },
  { label: 'tags', type: 'property', info: 'Tag filters' },
  { label: 'outputs', type: 'property', info: 'Job outputs' },
  { label: 'inputs', type: 'property', info: 'Workflow inputs' },
  { label: 'secrets', type: 'property', info: 'Workflow secrets' },
  { label: 'services', type: 'property', info: 'Job services' },
  { label: 'container', type: 'property', info: 'Job container' },
  { label: 'artifact', type: 'property', info: 'Artifact ref' },
  { label: 'cache', type: 'property', info: 'Cache config' },
  // Kubernetes
  { label: 'apiVersion', type: 'property', info: 'API version' },
  { label: 'kind', type: 'property', info: 'Resource kind' },
  { label: 'metadata', type: 'property', info: 'Resource metadata' },
  { label: 'spec', type: 'property', info: 'Resource spec' },
  { label: 'namespace', type: 'property', info: 'Namespace' },
  { label: 'selector', type: 'property', info: 'Label selector' },
  { label: 'matchLabels', type: 'property', info: 'Match labels' },
  { label: 'template', type: 'property', info: 'Pod template' },
  { label: 'containers', type: 'property', info: 'Pod containers' },
  { label: 'initContainers', type: 'property', info: 'Init containers' },
  { label: 'volumes', type: 'property', info: 'Pod volumes' },
  { label: 'volumeMounts', type: 'property', info: 'Volume mounts' },
  { label: 'resources', type: 'property', info: 'Resource requests' },
  { label: 'limits', type: 'property', info: 'Resource limits' },
  { label: 'requests', type: 'property', info: 'Resource requests' },
  { label: 'livenessProbe', type: 'property', info: 'Liveness probe' },
  { label: 'readinessProbe', type: 'property', info: 'Readiness probe' },
  { label: 'startupProbe', type: 'property', info: 'Startup probe' },
  { label: 'imagePullPolicy', type: 'property', info: 'Pull policy' },
  { label: 'imagePullSecrets', type: 'property', info: 'Pull secrets' },
  { label: 'securityContext', type: 'property', info: 'Security context' },
  { label: 'serviceAccountName', type: 'property', info: 'Service account' },
  { label: 'nodeSelector', type: 'property', info: 'Node selector' },
  { label: 'affinity', type: 'property', info: 'Affinity' },
  { label: 'tolerations', type: 'property', info: 'Tolerations' },
  { label: 'replicas', type: 'property', info: 'Replica count' },
  { label: 'strategy', type: 'property', info: 'Update strategy' },
  { label: 'rollingUpdate', type: 'property', info: 'Rolling update' },
  { label: 'maxSurge', type: 'property', info: 'Max surge' },
  { label: 'maxUnavailable', type: 'property', info: 'Max unavailable' },
  { label: 'annotations', type: 'property', info: 'Annotations map' },
  { label: 'labels', type: 'property', info: 'Labels map' },
  { label: 'configMapRef', type: 'property', info: 'ConfigMap ref' },
  { label: 'secretRef', type: 'property', info: 'Secret ref' },
  { label: 'envFrom', type: 'property', info: 'Env from' },
  { label: 'clusterIP', type: 'property', info: 'Cluster IP' },
  { label: 'externalIPs', type: 'property', info: 'External IPs' },
  { label: 'loadBalancer', type: 'property', info: 'LoadBalancer' },
  { label: 'targetPort', type: 'property', info: 'Target port' },
  { label: 'protocol', type: 'property', info: 'Port protocol' },
  { label: 'rules', type: 'property', info: 'Ingress rules' },
  { label: 'host', type: 'property', info: 'Ingress host' },
  { label: 'paths', type: 'property', info: 'Ingress paths' },
  { label: 'backend', type: 'property', info: 'Ingress backend' },
  { label: 'tls', type: 'property', info: 'TLS config' },
  { label: 'secretName', type: 'property', info: 'Secret name' },
  // CI/CD Generic
  { label: 'stages', type: 'property', info: 'Pipeline stages' },
  { label: 'stage', type: 'property', info: 'Stage ref' },
  { label: 'script', type: 'property', info: 'Script lines' },
  { label: 'before_script', type: 'property', info: 'Before script' },
  { label: 'after_script', type: 'property', info: 'After script' },
  { label: 'only', type: 'property', info: 'Only branches' },
  { label: 'except', type: 'property', info: 'Except branches' },
  { label: 'tags', type: 'property', info: 'Runner tags' },
  { label: 'artifacts', type: 'property', info: 'Artifacts config' },
  { label: 'cache', type: 'property', info: 'Cache config' },
  { label: 'include', type: 'property', info: 'Include template' },
  { label: 'extends', type: 'property', info: 'Extend job' },
  { label: 'allow_failure', type: 'property', info: 'Allow failure' },
  { label: 'retry', type: 'property', info: 'Retry config' },
  { label: 'parallel', type: 'property', info: 'Parallel jobs' },
  { label: 'trigger', type: 'property', info: 'Trigger downstream' },
  // Kubernetes top-level kinds
  { label: 'Pod', type: 'kind', info: 'K8s Pod kind' },
  { label: 'Service', type: 'kind', info: 'K8s Service kind' },
  { label: 'ConfigMap', type: 'kind', info: 'K8s ConfigMap' },
  { label: 'Secret', type: 'kind', info: 'K8s Secret' },
  { label: 'Namespace', type: 'kind', info: 'K8s Namespace' },
  { label: 'ServiceAccount', type: 'kind', info: 'K8s SA' },
  { label: 'Endpoints', type: 'kind', info: 'K8s Endpoints' },
  { label: 'EndpointSlice', type: 'kind', info: 'K8s EndpointSlice' },
  { label: 'Node', type: 'kind', info: 'K8s Node' },
  { label: 'PersistentVolume', type: 'kind', info: 'K8s PV' },
  { label: 'PersistentVolumeClaim', type: 'kind', info: 'K8s PVC' },
  { label: 'ResourceQuota', type: 'kind', info: 'K8s ResourceQuota' },
  { label: 'LimitRange', type: 'kind', info: 'K8s LimitRange' },
  { label: 'Event', type: 'kind', info: 'K8s Event' },
  { label: 'ReplicationController', type: 'kind', info: 'K8s RC' },
  { label: 'PodTemplate', type: 'kind', info: 'K8s PodTemplate' },
  { label: 'Deployment', type: 'kind', info: 'apps/v1 Deployment' },
  { label: 'StatefulSet', type: 'kind', info: 'apps/v1 StatefulSet' },
  { label: 'DaemonSet', type: 'kind', info: 'apps/v1 DaemonSet' },
  { label: 'ReplicaSet', type: 'kind', info: 'apps/v1 ReplicaSet' },
  { label: 'ControllerRevision', type: 'kind', info: 'apps/v1 Ctrl rev' },
  { label: 'Job', type: 'kind', info: 'batch/v1 Job' },
  { label: 'CronJob', type: 'kind', info: 'batch/v1 CronJob' },
  { label: 'Ingress', type: 'kind', info: 'networking Ingress' },
  { label: 'IngressClass', type: 'kind', info: 'networking IngressClass' },
  { label: 'NetworkPolicy', type: 'kind', info: 'networking NetPolicy' },
  { label: 'Role', type: 'kind', info: 'rbac Role' },
  { label: 'RoleBinding', type: 'kind', info: 'rbac RoleBinding' },
  { label: 'ClusterRole', type: 'kind', info: 'rbac ClusterRole' },
  { label: 'ClusterRoleBinding', type: 'kind', info: 'rbac ClusterRoleBinding' },
  { label: 'HorizontalPodAutoscaler', type: 'kind', info: 'autoscaling HPA' },
  { label: 'VerticalPodAutoscaler', type: 'kind', info: 'autoscaling VPA' },
  { label: 'PodDisruptionBudget', type: 'kind', info: 'policy PDB' },
  { label: 'PodSecurityPolicy', type: 'kind', info: 'policy PSP (deprecated)' },
  { label: 'StorageClass', type: 'kind', info: 'storage StorageClass' },
  { label: 'VolumeAttachment', type: 'kind', info: 'storage VA' },
  { label: 'CSIDriver', type: 'kind', info: 'storage CSIDriver' },
  { label: 'CSINode', type: 'kind', info: 'storage CSINode' },
  { label: 'CSIStorageCapacity', type: 'kind', info: 'storage CSICapacity' },
  { label: 'CertificateSigningRequest', type: 'kind', info: 'certs CSR' },
  { label: 'Lease', type: 'kind', info: 'coordination Lease' },
  { label: 'PriorityClass', type: 'kind', info: 'scheduling PC' },
  { label: 'RuntimeClass', type: 'kind', info: 'node RuntimeClass' },
  { label: 'CustomResourceDefinition', type: 'kind', info: 'apiextensions CRD' },
  { label: 'APIService', type: 'kind', info: 'apiregistration svc' },
  { label: 'MutatingWebhookConfiguration', type: 'kind', info: 'admission mutating' },
  { label: 'ValidatingWebhookConfiguration', type: 'kind', info: 'admission valid' },
  { label: 'FlowSchema', type: 'kind', info: 'API priority' },
  { label: 'PriorityLevelConfiguration', type: 'kind', info: 'API priority level' },
  // Core metadata
  { label: 'apiVersion', type: 'property', info: 'Resource apiVersion' },
  { label: 'kind', type: 'property', info: 'Resource kind' },
  { label: 'metadata', type: 'property', info: 'Resource metadata' },
  { label: 'spec', type: 'property', info: 'Resource spec' },
  { label: 'status', type: 'property', info: 'Resource status' },
  { label: 'ownerReferences', type: 'property', info: 'Owner refs' },
  { label: 'resourceVersion', type: 'property', info: 'Optimistic lock' },
  { label: 'generation', type: 'property', info: 'Metadata generation' },
  { label: 'uid', type: 'property', info: 'Unique ID' },
  { label: 'generateName', type: 'property', info: 'Name prefix' },
  { label: 'creationTimestamp', type: 'property', info: 'Creation time' },
  { label: 'deletionTimestamp', type: 'property', info: 'Deletion time' },
  { label: 'deletionGracePeriodSeconds', type: 'property', info: 'Delete grace' },
  { label: 'managedFields', type: 'property', info: 'Managed fields' },
  // PodSpec
  { label: 'containers', type: 'property', info: 'Pod containers' },
  { label: 'initContainers', type: 'property', info: 'Init containers' },
  { label: 'ephemeralContainers', type: 'property', info: 'Ephemeral ctrs' },
  { label: 'restartPolicy', type: 'property', info: 'Pod restart policy' },
  { label: 'terminationGracePeriodSeconds', type: 'property', info: 'Term grace' },
  { label: 'activeDeadlineSeconds', type: 'property', info: 'Active deadline' },
  { label: 'dnsPolicy', type: 'property', info: 'DNS policy' },
  { label: 'dnsConfig', type: 'property', info: 'DNS config' },
  { label: 'nodeName', type: 'property', info: 'Pin to node' },
  { label: 'serviceAccountName', type: 'property', info: 'SA name' },
  { label: 'serviceAccount', type: 'property', info: 'SA (deprecated)' },
  { label: 'automountServiceAccountToken', type: 'property', info: 'Mount SA token' },
  { label: 'hostNetwork', type: 'property', info: 'Use host net' },
  { label: 'hostPID', type: 'property', info: 'Use host PID ns' },
  { label: 'hostIPC', type: 'property', info: 'Use host IPC ns' },
  { label: 'shareProcessNamespace', type: 'property', info: 'Share PID ns' },
  { label: 'securityContext', type: 'property', info: 'Security ctx' },
  { label: 'imagePullSecrets', type: 'property', info: 'Pull secrets' },
  { label: 'affinity', type: 'property', info: 'Affinity rules' },
  { label: 'tolerations', type: 'property', info: 'Tolerations' },
  { label: 'nodeSelector', type: 'property', info: 'Node selector' },
  { label: 'topologySpreadConstraints', type: 'property', info: 'Spread' },
  { label: 'readinessGates', type: 'property', info: 'Readiness gates' },
  { label: 'schedulerName', type: 'property', info: 'Scheduler name' },
  { label: 'priority', type: 'property', info: 'Pod priority' },
  { label: 'priorityClassName', type: 'property', info: 'Priority class' },
  { label: 'preemptionPolicy', type: 'property', info: 'Preemption' },
  { label: 'runtimeClassName', type: 'property', info: 'Runtime class' },
  { label: 'overhead', type: 'property', info: 'Pod overhead' },
  { label: 'resourceClaims', type: 'property', info: 'Resource claims' },
  { label: 'os', type: 'property', info: 'Pod OS' },
  { label: 'hostAliases', type: 'property', info: 'Host aliases' },
  { label: 'subdomain', type: 'property', info: 'Pod subdomain' },
  { label: 'hostname', type: 'property', info: 'Pod hostname' },
  { label: 'setHostnameAsFQDN', type: 'property', info: 'FQDN hostname' },
  { label: 'enableServiceLinks', type: 'property', info: 'Service env links' },
  // Container
  { label: 'imagePullPolicy', type: 'property', info: 'Pull policy' },
  { label: 'workingDir', type: 'property', info: 'Working dir' },
  { label: 'envFrom', type: 'property', info: 'Env from CM/Secret' },
  { label: 'volumeMounts', type: 'property', info: 'Volume mounts' },
  { label: 'volumeDevices', type: 'property', info: 'Raw block devices' },
  { label: 'livenessProbe', type: 'property', info: 'Liveness probe' },
  { label: 'readinessProbe', type: 'property', info: 'Readiness probe' },
  { label: 'startupProbe', type: 'property', info: 'Startup probe' },
  { label: 'lifecycle', type: 'property', info: 'Lifecycle hooks' },
  { label: 'terminationMessagePath', type: 'property', info: 'Term msg path' },
  { label: 'terminationMessagePolicy', type: 'property', info: 'Term msg policy' },
  { label: 'stdin', type: 'property', info: 'Allocate stdin' },
  { label: 'stdinOnce', type: 'property', info: 'stdin one client' },
  { label: 'tty', type: 'property', info: 'Allocate TTY' },
  // Probe
  { label: 'httpGet', type: 'property', info: 'HTTP probe' },
  { label: 'tcpSocket', type: 'property', info: 'TCP probe' },
  { label: 'grpc', type: 'property', info: 'gRPC probe' },
  { label: 'exec', type: 'property', info: 'Exec probe' },
  { label: 'initialDelaySeconds', type: 'property', info: 'Initial delay' },
  { label: 'periodSeconds', type: 'property', info: 'Probe period' },
  { label: 'timeoutSeconds', type: 'property', info: 'Probe timeout' },
  { label: 'successThreshold', type: 'property', info: 'Success thresh' },
  { label: 'failureThreshold', type: 'property', info: 'Failure thresh' },
  { label: 'scheme', type: 'property', info: 'HTTP/HTTPS' },
  { label: 'httpHeaders', type: 'property', info: 'Probe headers' },
  // Resource requests
  { label: 'requests', type: 'property', info: 'Resource requests' },
  { label: 'limits', type: 'property', info: 'Resource limits' },
  { label: 'cpu', type: 'property', info: 'CPU qty' },
  { label: 'memory', type: 'property', info: 'Memory qty' },
  { label: 'ephemeral-storage', type: 'property', info: 'Ephem storage' },
  // ConfigMap / Secret
  { label: 'binaryData', type: 'property', info: 'Binary data' },
  { label: 'stringData', type: 'property', info: 'Secret strData' },
  { label: 'immutable', type: 'property', info: 'CM/Secret immutable' },
  // Service
  { label: 'clusterIP', type: 'property', info: 'Service clusterIP' },
  { label: 'clusterIPs', type: 'property', info: 'ClusterIPs list' },
  { label: 'externalIPs', type: 'property', info: 'External IPs' },
  { label: 'externalName', type: 'property', info: 'External name' },
  { label: 'externalTrafficPolicy', type: 'property', info: 'Ext traffic pol' },
  { label: 'internalTrafficPolicy', type: 'property', info: 'Int traffic pol' },
  { label: 'sessionAffinity', type: 'property', info: 'Session affinity' },
  { label: 'sessionAffinityConfig', type: 'property', info: 'Affinity config' },
  { label: 'loadBalancerIP', type: 'property', info: 'LB IP' },
  { label: 'loadBalancerSourceRanges', type: 'property', info: 'LB sources' },
  { label: 'loadBalancerClass', type: 'property', info: 'LB class' },
  { label: 'ipFamilies', type: 'property', info: 'IP families' },
  { label: 'ipFamilyPolicy', type: 'property', info: 'IP family policy' },
  { label: 'publishNotReadyAddresses', type: 'property', info: 'Pub notReady' },
  { label: 'topologyKeys', type: 'property', info: 'Topology keys' },
  { label: 'allocateLoadBalancerNodePorts', type: 'property', info: 'Alloc NP for LB' },
  { label: 'healthCheckNodePort', type: 'property', info: 'Health NP' },
  // Deployment / ReplicaSet
  { label: 'rollingUpdate', type: 'property', info: 'Rolling update' },
  { label: 'maxSurge', type: 'property', info: 'Max surge' },
  { label: 'maxUnavailable', type: 'property', info: 'Max unavailable' },
  { label: 'minReadySeconds', type: 'property', info: 'Min ready secs' },
  { label: 'progressDeadlineSeconds', type: 'property', info: 'Progress deadline' },
  { label: 'revisionHistoryLimit', type: 'property', info: 'Rev history limit' },
  { label: 'matchLabels', type: 'property', info: 'Label selector' },
  { label: 'matchExpressions', type: 'property', info: 'Selector exprs' },
  { label: 'paused', type: 'property', info: 'Paused rollout' },
  // StatefulSet
  { label: 'serviceName', type: 'property', info: 'Headless svc' },
  { label: 'volumeClaimTemplates', type: 'property', info: 'PVC template' },
  { label: 'podManagementPolicy', type: 'property', info: 'Pod mgmt policy' },
  { label: 'updateStrategy', type: 'property', info: 'Update strategy' },
  // Job / CronJob
  { label: 'completions', type: 'property', info: 'Job completions' },
  { label: 'parallelism', type: 'property', info: 'Job parallelism' },
  { label: 'backoffLimit', type: 'property', info: 'Backoff limit' },
  { label: 'ttlSecondsAfterFinished', type: 'property', info: 'TTL after done' },
  { label: 'podFailurePolicy', type: 'property', info: 'Pod fail policy' },
  { label: 'completionMode', type: 'property', info: 'Completion mode' },
  { label: 'suspend', type: 'property', info: 'Suspend job' },
  { label: 'timeZone', type: 'property', info: 'Cron timezone' },
  { label: 'concurrencyPolicy', type: 'property', info: 'Concurrency' },
  { label: 'startingDeadlineSeconds', type: 'property', info: 'Start deadline' },
  { label: 'jobTemplate', type: 'property', info: 'Job template' },
  { label: 'successfulJobsHistoryLimit', type: 'property', info: 'Success hist' },
  { label: 'failedJobsHistoryLimit', type: 'property', info: 'Failed hist' },
  // Ingress
  { label: 'ingressClassName', type: 'property', info: 'IngressClass name' },
  { label: 'backend', type: 'property', info: 'Default backend' },
  { label: 'http', type: 'property', info: 'HTTP ingress' },
  { label: 'paths', type: 'property', info: 'Ingress paths' },
  { label: 'pathType', type: 'property', info: 'Path type' },
  // NetworkPolicy
  { label: 'podSelector', type: 'property', info: 'Pod selector' },
  { label: 'policyTypes', type: 'property', info: 'Policy types' },
  { label: 'egress', type: 'property', info: 'Egress rules' },
  // Volume types
  { label: 'volumeMode', type: 'property', info: 'Volume mode' },
  { label: 'emptyDir', type: 'property', info: 'EmptyDir volume' },
  { label: 'hostPath', type: 'property', info: 'HostPath volume' },
  { label: 'configMap', type: 'property', info: 'CM volume' },
  { label: 'persistentVolumeClaim', type: 'property', info: 'PVC volume' },
  { label: 'downwardAPI', type: 'property', info: 'Downward API' },
  { label: 'projected', type: 'property', info: 'Projected vol' },
  { label: 'nfs', type: 'property', info: 'NFS volume' },
  { label: 'iscsi', type: 'property', info: 'iSCSI volume' },
  { label: 'cephfs', type: 'property', info: 'CephFS volume' },
  { label: 'rbd', type: 'property', info: 'RBD volume' },
  { label: 'glusterfs', type: 'property', info: 'GlusterFS volume' },
  { label: 'awsElasticBlockStore', type: 'property', info: 'AWS EBS' },
  { label: 'gcePersistentDisk', type: 'property', info: 'GCE PD' },
  { label: 'azureDisk', type: 'property', info: 'Azure disk' },
  { label: 'azureFile', type: 'property', info: 'Azure file' },
  { label: 'csi', type: 'property', info: 'CSI volume' },
  { label: 'ephemeral', type: 'property', info: 'Ephemeral vol' },
  { label: 'fsGroup', type: 'property', info: 'FS group' },
  { label: 'fsGroupChangePolicy', type: 'property', info: 'FS group pol' },
  { label: 'runAsUser', type: 'property', info: 'Run as UID' },
  { label: 'runAsGroup', type: 'property', info: 'Run as GID' },
  { label: 'runAsNonRoot', type: 'property', info: 'Non-root' },
  { label: 'allowPrivilegeEscalation', type: 'property', info: 'Allow privesc' },
  { label: 'privileged', type: 'property', info: 'Privileged ctr' },
  { label: 'readOnlyRootFilesystem', type: 'property', info: 'RO root FS' },
  { label: 'capabilities', type: 'property', info: 'Capabilities' },
  { label: 'seccompProfile', type: 'property', info: 'Seccomp' },
  { label: 'seLinuxOptions', type: 'property', info: 'SELinux' },
  { label: 'windowsOptions', type: 'property', info: 'Windows opts' },
  { label: 'supplementalGroups', type: 'property', info: 'Extra groups' },
  { label: 'sysctls', type: 'property', info: 'Kernel sysctls' },
  { label: 'procMount', type: 'property', info: 'proc mount type' },
  // Affinity
  { label: 'nodeAffinity', type: 'property', info: 'Node affinity' },
  { label: 'podAffinity', type: 'property', info: 'Pod affinity' },
  { label: 'podAntiAffinity', type: 'property', info: 'Pod anti-affinity' },
  { label: 'requiredDuringSchedulingIgnoredDuringExecution', type: 'property', info: 'Required sched' },
  { label: 'preferredDuringSchedulingIgnoredDuringExecution', type: 'property', info: 'Preferred sched' },
  { label: 'nodeSelectorTerms', type: 'property', info: 'Node sel terms' },
  { label: 'topologyKey', type: 'property', info: 'Topology key' },
  { label: 'weight', type: 'property', info: 'Preference weight' },
  { label: 'preference', type: 'property', info: 'Preference term' },
  // Toleration
  { label: 'tolerationSeconds', type: 'property', info: 'Tolerate secs' },
  { label: 'operator', type: 'property', info: 'Match operator' },
  // Ingress/Rules details
  { label: 'containerPort', type: 'property', info: 'Container port' },
  { label: 'hostPort', type: 'property', info: 'Host port' },
  { label: 'hostIP', type: 'property', info: 'Host IP' },
  { label: 'protocol', type: 'property', info: 'Protocol' },
  { label: 'targetPort', type: 'property', info: 'Target port' },
  { label: 'nodePort', type: 'property', info: 'Node port' },
  // HPA
  { label: 'minReplicas', type: 'property', info: 'Min replicas' },
  { label: 'maxReplicas', type: 'property', info: 'Max replicas' },
  { label: 'scaleTargetRef', type: 'property', info: 'HPA target' },
  { label: 'metrics', type: 'property', info: 'HPA metrics' },
  { label: 'behavior', type: 'property', info: 'HPA behavior' },
  { label: 'scaleUp', type: 'property', info: 'Scale-up policy' },
  { label: 'scaleDown', type: 'property', info: 'Scale-down policy' },
  // RBAC
  { label: 'apiGroups', type: 'property', info: 'API groups' },
  { label: 'resourceNames', type: 'property', info: 'Resource names' },
  { label: 'verbs', type: 'property', info: 'Verb list' },
  { label: 'roleRef', type: 'property', info: 'Role reference' },
  { label: 'subjects', type: 'property', info: 'Binding subjects' },
  // Helm template
  { label: '{{ .Values }}', type: 'helm', info: 'Helm Values' },
  { label: '{{ .Values. }}', type: 'helm', info: 'Helm Values access' },
  { label: '{{ .Release.Name }}', type: 'helm', info: 'Release name' },
  { label: '{{ .Release.Namespace }}', type: 'helm', info: 'Release namespace' },
  { label: '{{ .Release.IsInstall }}', type: 'helm', info: 'Is install' },
  { label: '{{ .Release.IsUpgrade }}', type: 'helm', info: 'Is upgrade' },
  { label: '{{ .Release.Revision }}', type: 'helm', info: 'Release revision' },
  { label: '{{ .Release.Service }}', type: 'helm', info: 'Release service' },
  { label: '{{ .Chart.Name }}', type: 'helm', info: 'Chart name' },
  { label: '{{ .Chart.Version }}', type: 'helm', info: 'Chart version' },
  { label: '{{ .Chart.AppVersion }}', type: 'helm', info: 'Chart appVersion' },
  { label: '{{ .Chart.Description }}', type: 'helm', info: 'Chart desc' },
  { label: '{{ .Chart.Home }}', type: 'helm', info: 'Chart home' },
  { label: '{{ .Chart.Sources }}', type: 'helm', info: 'Chart sources' },
  { label: '{{ .Chart.Maintainers }}', type: 'helm', info: 'Chart maintainers' },
  { label: '{{ .Chart.Keywords }}', type: 'helm', info: 'Chart keywords' },
  { label: '{{ .Files.Get }}', type: 'helm', info: 'Read file' },
  { label: '{{ .Files.GetBytes }}', type: 'helm', info: 'Read file bytes' },
  { label: '{{ .Files.Glob }}', type: 'helm', info: 'Glob files' },
  { label: '{{ .Files.Lines }}', type: 'helm', info: 'File lines' },
  { label: '{{ .Files.AsSecrets }}', type: 'helm', info: 'Files as secrets' },
  { label: '{{ .Files.AsConfig }}', type: 'helm', info: 'Files as CM' },
  { label: '{{ .Capabilities.KubeVersion }}', type: 'helm', info: 'Kube version' },
  { label: '{{ .Capabilities.APIVersions }}', type: 'helm', info: 'API versions' },
  { label: '{{ .Template.Name }}', type: 'helm', info: 'Template name' },
  { label: '{{ .Template.BasePath }}', type: 'helm', info: 'Template base path' },
  { label: '{{ include }}', type: 'helm', apply: '{{ include "${name}" . }}', info: 'Include tpl' },
  { label: '{{ tpl }}', type: 'helm', apply: '{{ tpl "${str}" . }}', info: 'Render tpl' },
  { label: '{{ required }}', type: 'helm', apply: '{{ required "${msg}" .Values.${v} }}', info: 'Required value' },
  { label: '{{ fail }}', type: 'helm', apply: '{{ fail "${msg}" }}', info: 'Fail' },
  { label: '{{ lookup }}', type: 'helm', apply: '{{ lookup "v1" "ConfigMap" "${ns}" "${name}" }}', info: 'Lookup resource' },
  // Sprig
  { label: 'default', type: 'function', info: 'Sprig default' },
  { label: 'empty', type: 'function', info: 'Sprig empty' },
  { label: 'coalesce', type: 'function', info: 'Sprig coalesce' },
  { label: 'ternary', type: 'function', info: 'Sprig ternary' },
  { label: 'upper', type: 'function', info: 'Sprig upper' },
  { label: 'lower', type: 'function', info: 'Sprig lower' },
  { label: 'title', type: 'function', info: 'Sprig title' },
  { label: 'untitle', type: 'function', info: 'Sprig untitle' },
  { label: 'substr', type: 'function', info: 'Sprig substr' },
  { label: 'trunc', type: 'function', info: 'Sprig trunc' },
  { label: 'trim', type: 'function', info: 'Sprig trim' },
  { label: 'trimAll', type: 'function', info: 'Sprig trimAll' },
  { label: 'trimPrefix', type: 'function', info: 'Sprig trimPrefix' },
  { label: 'trimSuffix', type: 'function', info: 'Sprig trimSuffix' },
  { label: 'contains', type: 'function', info: 'Sprig contains' },
  { label: 'hasPrefix', type: 'function', info: 'Sprig hasPrefix' },
  { label: 'hasSuffix', type: 'function', info: 'Sprig hasSuffix' },
  { label: 'quote', type: 'function', info: 'Sprig quote' },
  { label: 'squote', type: 'function', info: 'Sprig squote' },
  { label: 'indent', type: 'function', info: 'Sprig indent' },
  { label: 'nindent', type: 'function', info: 'Sprig nindent' },
  { label: 'repeat', type: 'function', info: 'Sprig repeat' },
  { label: 'replace', type: 'function', info: 'Sprig replace' },
  { label: 'regexMatch', type: 'function', info: 'Sprig regexMatch' },
  { label: 'regexFind', type: 'function', info: 'Sprig regexFind' },
  { label: 'regexFindAll', type: 'function', info: 'Sprig regexFindAll' },
  { label: 'regexReplaceAll', type: 'function', info: 'Sprig replace all' },
  { label: 'regexSplit', type: 'function', info: 'Sprig split' },
  { label: 'add', type: 'function', info: 'Sprig add' },
  { label: 'sub', type: 'function', info: 'Sprig sub' },
  { label: 'mul', type: 'function', info: 'Sprig mul' },
  { label: 'div', type: 'function', info: 'Sprig div' },
  { label: 'mod', type: 'function', info: 'Sprig mod' },
  { label: 'max', type: 'function', info: 'Sprig max' },
  { label: 'min', type: 'function', info: 'Sprig min' },
  { label: 'round', type: 'function', info: 'Sprig round' },
  { label: 'ceil', type: 'function', info: 'Sprig ceil' },
  { label: 'floor', type: 'function', info: 'Sprig floor' },
  { label: 'abs', type: 'function', info: 'Sprig abs' },
  { label: 'toInt', type: 'function', info: 'Sprig toInt' },
  { label: 'toString', type: 'function', info: 'Sprig toString' },
  { label: 'toJson', type: 'function', info: 'Sprig toJson' },
  { label: 'toYaml', type: 'function', info: 'Sprig toYaml' },
  { label: 'toToml', type: 'function', info: 'Sprig toToml' },
  { label: 'fromJson', type: 'function', info: 'Sprig fromJson' },
  { label: 'fromYaml', type: 'function', info: 'Sprig fromYaml' },
  { label: 'b64enc', type: 'function', info: 'Base64 encode' },
  { label: 'b64dec', type: 'function', info: 'Base64 decode' },
  { label: 'sha256sum', type: 'function', info: 'SHA-256' },
  { label: 'sha1sum', type: 'function', info: 'SHA-1' },
  { label: 'adler32sum', type: 'function', info: 'Adler32' },
  { label: 'genCA', type: 'function', info: 'Generate CA' },
  { label: 'genSelfSignedCert', type: 'function', info: 'Self-signed cert' },
  { label: 'genSignedCert', type: 'function', info: 'Signed cert' },
  { label: 'randAlphaNum', type: 'function', info: 'Random alnum' },
  { label: 'randAlpha', type: 'function', info: 'Random alpha' },
  { label: 'randNumeric', type: 'function', info: 'Random digits' },
  { label: 'randAscii', type: 'function', info: 'Random ASCII' },
  { label: 'uuidv4', type: 'function', info: 'UUID v4' },
  { label: 'date', type: 'function', info: 'Sprig date' },
  { label: 'dateModify', type: 'function', info: 'Date modify' },
  { label: 'now', type: 'function', info: 'Current time' },
  { label: 'ago', type: 'function', info: 'Duration ago' },
  { label: 'htmlDate', type: 'function', info: 'HTML date' },
  { label: 'toDate', type: 'function', info: 'Parse date' },
  { label: 'unixEpoch', type: 'function', info: 'Unix epoch' },
  { label: 'htmlDateInZone', type: 'function', info: 'Zoned HTML date' },
  { label: 'duration', type: 'function', info: 'Duration' },
  { label: 'join', type: 'function', info: 'Sprig join' },
  { label: 'splitn', type: 'function', info: 'Sprig splitn' },
  { label: 'sortAlpha', type: 'function', info: 'Sprig sortAlpha' },
  { label: 'reverse', type: 'function', info: 'Sprig reverse' },
  { label: 'first', type: 'function', info: 'Sprig first' },
  { label: 'rest', type: 'function', info: 'Sprig rest' },
  { label: 'last', type: 'function', info: 'Sprig last' },
  { label: 'initial', type: 'function', info: 'Sprig initial' },
  { label: 'append', type: 'function', info: 'Sprig append' },
  { label: 'prepend', type: 'function', info: 'Sprig prepend' },
  { label: 'concat', type: 'function', info: 'Sprig concat' },
  { label: 'uniq', type: 'function', info: 'Sprig uniq' },
  { label: 'without', type: 'function', info: 'Sprig without' },
  { label: 'has', type: 'function', info: 'Sprig has' },
  { label: 'push', type: 'function', info: 'Sprig push' },
  { label: 'pop', type: 'function', info: 'Sprig pop' },
  { label: 'slice', type: 'function', info: 'Sprig slice' },
  { label: 'dict', type: 'function', info: 'Sprig dict' },
  { label: 'get', type: 'function', info: 'Sprig get' },
  { label: 'unset', type: 'function', info: 'Sprig unset' },
  { label: 'hasKey', type: 'function', info: 'Sprig hasKey' },
  { label: 'pluck', type: 'function', info: 'Sprig pluck' },
  { label: 'keys', type: 'function', info: 'Sprig keys' },
  { label: 'values', type: 'function', info: 'Sprig values' },
  { label: 'merge', type: 'function', info: 'Sprig merge' },
  { label: 'mergeOverwrite', type: 'function', info: 'Sprig mergeOver' },
  { label: 'deepCopy', type: 'function', info: 'Sprig deepCopy' },
  { label: 'pick', type: 'function', info: 'Sprig pick' },
  { label: 'omit', type: 'function', info: 'Sprig omit' },
  { label: 'list', type: 'function', info: 'Sprig list' },
  { label: 'tuple', type: 'function', info: 'Sprig tuple' },
  { label: 'range', type: 'function', info: 'Sprig range' },
  { label: 'untilStep', type: 'function', info: 'Sprig untilStep' },
  // Docker Compose v3 keys
  { label: 'configs', type: 'compose', info: 'Configs map' },
  { label: 'profiles', type: 'compose', info: 'Service profile list' },
  { label: 'context', type: 'compose', info: 'Build context' },
  { label: 'dockerfile', type: 'compose', info: 'Dockerfile path' },
  { label: 'cache_from', type: 'compose', info: 'Build cache_from' },
  { label: 'cache_to', type: 'compose', info: 'Build cache_to' },
  { label: 'extra_hosts', type: 'compose', info: 'hosts file extras' },
  { label: 'platforms', type: 'compose', info: 'Build platforms' },
  { label: 'hostname', type: 'compose', info: 'Ctr hostname' },
  { label: 'entrypoint', type: 'compose', info: 'Override EP' },
  { label: 'env_file', type: 'compose', info: 'Env file list' },
  { label: 'depends_on', type: 'compose', info: 'Depends on' },
  { label: 'expose', type: 'compose', info: 'Exposed ports' },
  { label: 'restart', type: 'compose', info: 'Restart policy' },
  { label: 'healthcheck', type: 'compose', info: 'Healthcheck' },
  { label: 'interval', type: 'compose', info: 'HC interval' },
  { label: 'timeout', type: 'compose', info: 'HC timeout' },
  { label: 'retries', type: 'compose', info: 'HC retries' },
  { label: 'start_period', type: 'compose', info: 'HC start period' },
  { label: 'logging', type: 'compose', info: 'Logging config' },
  { label: 'mode', type: 'compose', info: 'Deploy mode' },
  { label: 'placement', type: 'compose', info: 'Placement rules' },
  { label: 'update_config', type: 'compose', info: 'Update config' },
  { label: 'rollback_config', type: 'compose', info: 'Rollback config' },
  { label: 'restart_policy', type: 'compose', info: 'Restart policy' },
  { label: 'working_dir', type: 'compose', info: 'Work dir' },
  { label: 'stdin_open', type: 'compose', info: 'Stdin open' },
  { label: 'read_only', type: 'compose', info: 'Read-only FS' },
  { label: 'tmpfs', type: 'compose', info: 'Tmpfs mounts' },
  { label: 'ulimits', type: 'compose', info: 'Ulimits' },
  { label: 'cap_add', type: 'compose', info: 'Capabilities add' },
  { label: 'cap_drop', type: 'compose', info: 'Capabilities drop' },
  { label: 'security_opt', type: 'compose', info: 'Security opts' },
  { label: 'devices', type: 'compose', info: 'Device list' },
  { label: 'isolation', type: 'compose', info: 'Isolation mode' },
  { label: 'dns', type: 'compose', info: 'DNS servers' },
  { label: 'dns_search', type: 'compose', info: 'DNS search' },
  { label: 'dns_opt', type: 'compose', info: 'DNS opts' },
  { label: 'domainname', type: 'compose', info: 'Domain name' },
  { label: 'mac_address', type: 'compose', info: 'MAC address' },
  { label: 'pid', type: 'compose', info: 'PID namespace' },
  { label: 'ipc', type: 'compose', info: 'IPC namespace' },
  { label: 'userns_mode', type: 'compose', info: 'User ns mode' },
  { label: 'stop_grace_period', type: 'compose', info: 'Stop grace' },
  { label: 'stop_signal', type: 'compose', info: 'Stop signal' },
  { label: 'external', type: 'compose', info: 'External resource' },
  // GitHub Actions
  { label: 'on', type: 'gha', info: 'Workflow trigger' },
  { label: 'runs-on', type: 'gha', info: 'Runner OS' },
  { label: 'defaults', type: 'gha', info: 'Default opts' },
  { label: 'concurrency', type: 'gha', info: 'Concurrency group' },
  { label: 'permissions', type: 'gha', info: 'GITHUB_TOKEN perms' },
  { label: 'strategy', type: 'gha', info: 'Matrix strategy' },
  { label: 'matrix', type: 'gha', info: 'Matrix' },
  { label: 'needs', type: 'gha', info: 'Job deps' },
  { label: 'outputs', type: 'gha', info: 'Job outputs' },
  { label: 'if', type: 'gha', info: 'Conditional' },
  { label: 'timeout-minutes', type: 'gha', info: 'Job timeout' },
  { label: 'continue-on-error', type: 'gha', info: 'Continue on err' },
  { label: 'container', type: 'gha', info: 'Container' },
  { label: 'environment', type: 'gha', info: 'Environment target' },
  { label: 'steps', type: 'gha', info: 'Job steps' },
  { label: 'uses', type: 'gha', info: 'Step action' },
  { label: 'with', type: 'gha', info: 'Action inputs' },
  { label: 'run', type: 'gha', info: 'Step run' },
  { label: 'shell', type: 'gha', info: 'Shell' },
  { label: 'working-directory', type: 'gha', info: 'Work dir' },
  { label: 'fail-fast', type: 'gha', info: 'Matrix fail-fast' },
  { label: 'max-parallel', type: 'gha', info: 'Max parallel jobs' },
  { label: 'group', type: 'gha', info: 'Concurrency group' },
  { label: 'cancel-in-progress', type: 'gha', info: 'Cancel running' },
  { label: 'pull_request', type: 'gha', info: 'Trigger: PR' },
  { label: 'workflow_dispatch', type: 'gha', info: 'Trigger: manual' },
  { label: 'workflow_call', type: 'gha', info: 'Reusable workflow' },
  { label: 'workflow_run', type: 'gha', info: 'Trigger: wflow run' },
  { label: 'release', type: 'gha', info: 'Trigger: release' },
  { label: 'repository_dispatch', type: 'gha', info: 'Trigger: dispatch' },
  { label: 'actions/checkout@v4', type: 'action', info: 'Checkout action' },
  { label: 'actions/setup-node@v4', type: 'action', info: 'Setup Node' },
  { label: 'actions/setup-python@v5', type: 'action', info: 'Setup Python' },
  { label: 'actions/setup-go@v5', type: 'action', info: 'Setup Go' },
  { label: 'actions/setup-java@v4', type: 'action', info: 'Setup Java' },
  { label: 'actions/setup-dotnet@v4', type: 'action', info: 'Setup .NET' },
  { label: 'actions/cache@v4', type: 'action', info: 'Cache action' },
  { label: 'actions/upload-artifact@v4', type: 'action', info: 'Upload artifact' },
  { label: 'actions/download-artifact@v4', type: 'action', info: 'Download artifact' },
  { label: 'actions/github-script@v7', type: 'action', info: 'gh-script' },
  { label: 'docker/setup-buildx-action@v3', type: 'action', info: 'buildx setup' },
  { label: 'docker/setup-qemu-action@v3', type: 'action', info: 'QEMU setup' },
  { label: 'docker/login-action@v3', type: 'action', info: 'Docker login' },
  { label: 'docker/build-push-action@v6', type: 'action', info: 'Build & push' },
  { label: 'docker/metadata-action@v5', type: 'action', info: 'Metadata tags' },
  // Ansible common modules
  { label: 'ansible.builtin.copy', type: 'module', info: 'Copy files' },
  { label: 'ansible.builtin.file', type: 'module', info: 'Manage file' },
  { label: 'ansible.builtin.template', type: 'module', info: 'Jinja template' },
  { label: 'ansible.builtin.command', type: 'module', info: 'Run command' },
  { label: 'ansible.builtin.shell', type: 'module', info: 'Run shell' },
  { label: 'ansible.builtin.service', type: 'module', info: 'Service mgmt' },
  { label: 'ansible.builtin.systemd', type: 'module', info: 'systemd mgmt' },
  { label: 'ansible.builtin.apt', type: 'module', info: 'apt mgmt' },
  { label: 'ansible.builtin.yum', type: 'module', info: 'yum mgmt' },
  { label: 'ansible.builtin.dnf', type: 'module', info: 'dnf mgmt' },
  { label: 'ansible.builtin.user', type: 'module', info: 'User mgmt' },
  { label: 'ansible.builtin.group', type: 'module', info: 'Group mgmt' },
  { label: 'ansible.builtin.git', type: 'module', info: 'Git clone' },
  { label: 'ansible.builtin.lineinfile', type: 'module', info: 'Line in file' },
  { label: 'ansible.builtin.blockinfile', type: 'module', info: 'Block in file' },
  { label: 'ansible.builtin.replace', type: 'module', info: 'Regex replace' },
  { label: 'ansible.builtin.debug', type: 'module', info: 'Print debug' },
  { label: 'ansible.builtin.setup', type: 'module', info: 'Gather facts' },
  { label: 'ansible.builtin.get_url', type: 'module', info: 'HTTP download' },
  { label: 'ansible.builtin.uri', type: 'module', info: 'Any HTTP' },
  { label: 'ansible.builtin.fail', type: 'module', info: 'Fail' },
  { label: 'ansible.builtin.assert', type: 'module', info: 'Assert cond' },
  { label: 'ansible.builtin.set_fact', type: 'module', info: 'Set fact' },
  { label: 'ansible.builtin.include_vars', type: 'module', info: 'Include vars' },
  { label: 'ansible.builtin.include_tasks', type: 'module', info: 'Include tasks' },
  { label: 'ansible.builtin.import_tasks', type: 'module', info: 'Import tasks' },
  { label: 'ansible.builtin.include_role', type: 'module', info: 'Include role' },
  { label: 'ansible.builtin.import_role', type: 'module', info: 'Import role' },
  { label: 'ansible.builtin.wait_for', type: 'module', info: 'Wait for port' },
  { label: 'ansible.builtin.stat', type: 'module', info: 'Stat file' },
  { label: 'ansible.builtin.unarchive', type: 'module', info: 'Unpack archive' },
  { label: 'ansible.builtin.fetch', type: 'module', info: 'Fetch file' },
  { label: 'ansible.builtin.pause', type: 'module', info: 'Pause' },
  { label: 'community.general.pip', type: 'module', info: 'pip install' },
  { label: 'become', type: 'ansible', info: 'Privilege escalation' },
  { label: 'become_user', type: 'ansible', info: 'Become user' },
  { label: 'become_method', type: 'ansible', info: 'Become method' },
  { label: 'hosts', type: 'ansible', info: 'Target hosts' },
  { label: 'gather_facts', type: 'ansible', info: 'Gather facts' },
  { label: 'handlers', type: 'ansible', info: 'Play handlers' },
  { label: 'vars_files', type: 'ansible', info: 'Vars files' },
  { label: 'vars_prompt', type: 'ansible', info: 'Prompt vars' },
  { label: 'roles', type: 'ansible', info: 'Play roles' },
  { label: 'pre_tasks', type: 'ansible', info: 'Pre tasks' },
  { label: 'post_tasks', type: 'ansible', info: 'Post tasks' },
  { label: 'when', type: 'ansible', info: 'Task when cond' },
  { label: 'loop_control', type: 'ansible', info: 'Loop control' },
  { label: 'register', type: 'ansible', info: 'Register var' },
  { label: 'notify', type: 'ansible', info: 'Notify handler' },
  { label: 'listen', type: 'ansible', info: 'Handler listen' },
  { label: 'any_errors_fatal', type: 'ansible', info: 'Errors fatal' },
  { label: 'ignore_errors', type: 'ansible', info: 'Ignore errors' },
  { label: 'delegate_to', type: 'ansible', info: 'Delegate task' },
  { label: 'run_once', type: 'ansible', info: 'Run only once' },
  { label: 'no_log', type: 'ansible', info: 'Do not log' },
  { label: 'changed_when', type: 'ansible', info: 'Changed when' },
  { label: 'failed_when', type: 'ansible', info: 'Failed when' },
  { label: 'serial', type: 'ansible', info: 'Play serial' },
  { label: 'max_fail_percentage', type: 'ansible', info: 'Fail pct' },
  { label: 'remote_user', type: 'ansible', info: 'SSH user' },
  { label: 'connection', type: 'ansible', info: 'Connection type' },
  // Tags & markers
  { label: '!include', type: 'tag', info: 'Include file tag' },
  { label: '!!str', type: 'tag', info: 'String tag' },
  { label: '!!int', type: 'tag', info: 'Int tag' },
  { label: '!!float', type: 'tag', info: 'Float tag' },
  { label: '!!bool', type: 'tag', info: 'Bool tag' },
  { label: '!!null', type: 'tag', info: 'Null tag' },
  { label: '!!binary', type: 'tag', info: 'Binary tag' },
  { label: '!!seq', type: 'tag', info: 'Sequence tag' },
  { label: '!!map', type: 'tag', info: 'Map tag' },
  { label: '!!set', type: 'tag', info: 'Set tag' },
  { label: '!!omap', type: 'tag', info: 'Ordered map' },
  { label: '!!timestamp', type: 'tag', info: 'Timestamp tag' },
  { label: '---', type: 'marker', info: 'Document start' },
  { label: '...', type: 'marker', info: 'Document end' },
  // Extended K8s - apiVersions
  { label: 'v1', type: 'apiver', info: 'Core v1' },
  { label: 'apps/v1', type: 'apiver', info: 'Apps v1' },
  { label: 'batch/v1', type: 'apiver', info: 'Batch v1' },
  { label: 'networking.k8s.io/v1', type: 'apiver', info: 'Networking v1' },
  { label: 'rbac.authorization.k8s.io/v1', type: 'apiver', info: 'RBAC v1' },
  { label: 'autoscaling/v1', type: 'apiver', info: 'Autoscaling v1' },
  { label: 'autoscaling/v2', type: 'apiver', info: 'Autoscaling v2' },
  { label: 'policy/v1', type: 'apiver', info: 'Policy v1' },
  { label: 'storage.k8s.io/v1', type: 'apiver', info: 'Storage v1' },
  { label: 'certificates.k8s.io/v1', type: 'apiver', info: 'Certs v1' },
  { label: 'coordination.k8s.io/v1', type: 'apiver', info: 'Coord v1' },
  { label: 'scheduling.k8s.io/v1', type: 'apiver', info: 'Scheduling v1' },
  { label: 'node.k8s.io/v1', type: 'apiver', info: 'Node v1' },
  { label: 'apiextensions.k8s.io/v1', type: 'apiver', info: 'ApiExts v1' },
  { label: 'admissionregistration.k8s.io/v1', type: 'apiver', info: 'Admission v1' },
  { label: 'flowcontrol.apiserver.k8s.io/v1', type: 'apiver', info: 'Flow control' },
  // Image pull / policies
  { label: 'Always', type: 'value', info: 'Always pull/restart' },
  { label: 'Never', type: 'value', info: 'Never pull/restart' },
  { label: 'IfNotPresent', type: 'value', info: 'Pull if missing' },
  { label: 'OnFailure', type: 'value', info: 'Restart on failure' },
  { label: 'ClusterFirst', type: 'value', info: 'DNS cluster first' },
  { label: 'Default', type: 'value', info: 'DNS default' },
  { label: 'None', type: 'value', info: 'None' },
  { label: 'ClusterFirstWithHostNet', type: 'value', info: 'DNS w/ host net' },
  { label: 'RollingUpdate', type: 'value', info: 'Rolling update type' },
  { label: 'Recreate', type: 'value', info: 'Recreate deploy type' },
  { label: 'OrderedReady', type: 'value', info: 'STS podMgmt' },
  { label: 'Parallel', type: 'value', info: 'Parallel podMgmt' },
  { label: 'PreemptLowerPriority', type: 'value', info: 'Preempt lower prio' },
  { label: 'PreemptNever', type: 'value', info: 'Never preempt' },
  { label: 'Indexed', type: 'value', info: 'Job completion mode' },
  { label: 'NonIndexed', type: 'value', info: 'Job completion mode' },
  { label: 'Allow', type: 'value', info: 'Concurrency policy' },
  { label: 'Forbid', type: 'value', info: 'Concurrency policy' },
  { label: 'Replace', type: 'value', info: 'Concurrency policy' },
  { label: 'ReadWriteOnce', type: 'value', info: 'Access mode RWO' },
  { label: 'ReadOnlyMany', type: 'value', info: 'Access mode ROX' },
  { label: 'ReadWriteMany', type: 'value', info: 'Access mode RWX' },
  { label: 'ReadWriteOncePod', type: 'value', info: 'RWO to one pod' },
  { label: 'Delete', type: 'value', info: 'PV reclaim delete' },
  { label: 'Retain', type: 'value', info: 'PV reclaim retain' },
  { label: 'Filesystem', type: 'value', info: 'Volume filesystem' },
  { label: 'Block', type: 'value', info: 'Raw block' },
  { label: 'ClusterIP', type: 'value', info: 'Service type CIP' },
  { label: 'NodePort', type: 'value', info: 'Service type NP' },
  { label: 'LoadBalancer', type: 'value', info: 'Service type LB' },
  { label: 'ExternalName', type: 'value', info: 'Service ExtName' },
  { label: 'Local', type: 'value', info: 'Traffic policy Local' },
  { label: 'Cluster', type: 'value', info: 'Traffic policy Cluster' },
  { label: 'Exists', type: 'value', info: 'Selector Exists' },
  { label: 'DoesNotExist', type: 'value', info: 'Selector DoesNotExist' },
  { label: 'In', type: 'value', info: 'Selector In' },
  { label: 'NotIn', type: 'value', info: 'Selector NotIn' },
  { label: 'NoSchedule', type: 'value', info: 'Taint effect' },
  { label: 'PreferNoSchedule', type: 'value', info: 'Taint effect' },
  { label: 'NoExecute', type: 'value', info: 'Taint effect' },
  { label: 'Equal', type: 'value', info: 'Toleration op' },
  { label: 'TCP', type: 'value', info: 'Protocol TCP' },
  { label: 'UDP', type: 'value', info: 'Protocol UDP' },
  { label: 'SCTP', type: 'value', info: 'Protocol SCTP' },
  { label: 'HTTP', type: 'value', info: 'Scheme HTTP' },
  { label: 'HTTPS', type: 'value', info: 'Scheme HTTPS' },
  { label: 'Pending', type: 'value', info: 'Phase Pending' },
  { label: 'Running', type: 'value', info: 'Phase Running' },
  { label: 'Succeeded', type: 'value', info: 'Phase Succeeded' },
  { label: 'Failed', type: 'value', info: 'Phase Failed' },
  { label: 'Unknown', type: 'value', info: 'Phase Unknown' },
  { label: 'Prefix', type: 'value', info: 'Ingress pathType' },
  { label: 'ImplementationSpecific', type: 'value', info: 'pathType impl' },
  { label: 'Immediate', type: 'value', info: 'VolumeBindingMode' },
  { label: 'WaitForFirstConsumer', type: 'value', info: 'VolumeBindingMode' },
  { label: 'Utilization', type: 'value', info: 'HPA metric type' },
  { label: 'AverageValue', type: 'value', info: 'HPA metric type' },
  { label: 'Value', type: 'value', info: 'HPA metric type' },
  { label: 'Resource', type: 'value', info: 'HPA metric kind' },
  { label: 'Pods', type: 'value', info: 'HPA metric kind' },
  { label: 'Object', type: 'value', info: 'HPA metric kind' },
  { label: 'External', type: 'value', info: 'HPA metric kind' },
  { label: 'ContainerResource', type: 'value', info: 'HPA metric kind' },
  // More helm values
  { label: '{{ .Release.IsInstall }}', type: 'helm', info: 'Install check' },
  { label: '{{ toYaml }}', type: 'helm', info: 'To YAML filter' },
  { label: '{{ printf }}', type: 'helm', info: 'printf function' },
  { label: '{{ default }}', type: 'helm', info: 'default func' },
  { label: '{{ if eq }}', type: 'helm', info: 'if eq' },
  { label: '{{ if ne }}', type: 'helm', info: 'if ne' },
  { label: '{{ if and }}', type: 'helm', info: 'if and' },
  { label: '{{ if or }}', type: 'helm', info: 'if or' },
  { label: '{{ if not }}', type: 'helm', info: 'if not' },
  { label: '{{ with }}', type: 'helm', info: 'with block' },
  { label: '{{ range }}', type: 'helm', info: 'range loop' },
  { label: '{{ end }}', type: 'helm', info: 'End block' },
  { label: '{{- }}', type: 'helm', info: 'Trim whitespace' },
  { label: '{{/* comment */}}', type: 'helm', info: 'Template comment' },
  { label: '{{ define }}', type: 'helm', info: 'Define tpl' },
  { label: '{{ template }}', type: 'helm', info: 'Template call' },
  { label: '{{ block }}', type: 'helm', info: 'Block tpl' },
  // GitHub Actions env/contexts
  { label: '${{ github.ref }}', type: 'gha-ctx', info: 'Ref context' },
  { label: '${{ github.sha }}', type: 'gha-ctx', info: 'Commit SHA' },
  { label: '${{ github.actor }}', type: 'gha-ctx', info: 'Actor login' },
  { label: '${{ github.event_name }}', type: 'gha-ctx', info: 'Event name' },
  { label: '${{ github.repository }}', type: 'gha-ctx', info: 'owner/repo' },
  { label: '${{ github.repository_owner }}', type: 'gha-ctx', info: 'Repo owner' },
  { label: '${{ github.workspace }}', type: 'gha-ctx', info: 'Workspace dir' },
  { label: '${{ github.workflow }}', type: 'gha-ctx', info: 'Workflow name' },
  { label: '${{ github.job }}', type: 'gha-ctx', info: 'Job id' },
  { label: '${{ github.run_id }}', type: 'gha-ctx', info: 'Run ID' },
  { label: '${{ github.run_number }}', type: 'gha-ctx', info: 'Run number' },
  { label: '${{ github.run_attempt }}', type: 'gha-ctx', info: 'Run attempt' },
  { label: '${{ github.token }}', type: 'gha-ctx', info: 'GH token' },
  { label: '${{ github.api_url }}', type: 'gha-ctx', info: 'API URL' },
  { label: '${{ github.server_url }}', type: 'gha-ctx', info: 'Server URL' },
  { label: '${{ github.graphql_url }}', type: 'gha-ctx', info: 'GraphQL URL' },
  { label: '${{ github.head_ref }}', type: 'gha-ctx', info: 'PR head ref' },
  { label: '${{ github.base_ref }}', type: 'gha-ctx', info: 'PR base ref' },
  { label: '${{ github.ref_name }}', type: 'gha-ctx', info: 'Ref name' },
  { label: '${{ github.ref_type }}', type: 'gha-ctx', info: 'Ref type' },
  { label: '${{ secrets. }}', type: 'gha-ctx', info: 'Secret ref' },
  { label: '${{ secrets.GITHUB_TOKEN }}', type: 'gha-ctx', info: 'GH token' },
  { label: '${{ env. }}', type: 'gha-ctx', info: 'Env context' },
  { label: '${{ inputs. }}', type: 'gha-ctx', info: 'Inputs context' },
  { label: '${{ steps. }}', type: 'gha-ctx', info: 'Steps context' },
  { label: '${{ needs. }}', type: 'gha-ctx', info: 'Needs context' },
  { label: '${{ matrix. }}', type: 'gha-ctx', info: 'Matrix context' },
  { label: '${{ strategy. }}', type: 'gha-ctx', info: 'Strategy context' },
  { label: '${{ runner.os }}', type: 'gha-ctx', info: 'Runner OS' },
  { label: '${{ runner.arch }}', type: 'gha-ctx', info: 'Runner arch' },
  { label: '${{ runner.temp }}', type: 'gha-ctx', info: 'Runner temp' },
  { label: '${{ runner.tool_cache }}', type: 'gha-ctx', info: 'Tool cache' },
  { label: '${{ job.status }}', type: 'gha-ctx', info: 'Job status' },
  { label: '${{ contains() }}', type: 'gha-func', info: 'Contains func' },
  { label: '${{ startsWith() }}', type: 'gha-func', info: 'startsWith' },
  { label: '${{ endsWith() }}', type: 'gha-func', info: 'endsWith' },
  { label: '${{ format() }}', type: 'gha-func', info: 'format()' },
  { label: '${{ join() }}', type: 'gha-func', info: 'join()' },
  { label: '${{ toJSON() }}', type: 'gha-func', info: 'toJSON' },
  { label: '${{ fromJSON() }}', type: 'gha-func', info: 'fromJSON' },
  { label: '${{ hashFiles() }}', type: 'gha-func', info: 'hashFiles' },
  { label: '${{ success() }}', type: 'gha-func', info: 'success()' },
  { label: '${{ always() }}', type: 'gha-func', info: 'always()' },
  { label: '${{ cancelled() }}', type: 'gha-func', info: 'cancelled()' },
  { label: '${{ failure() }}', type: 'gha-func', info: 'failure()' },
  // runner labels
  { label: 'ubuntu-latest', type: 'runner', info: 'Ubuntu runner' },
  { label: 'ubuntu-24.04', type: 'runner', info: 'Ubuntu 24.04' },
  { label: 'ubuntu-22.04', type: 'runner', info: 'Ubuntu 22.04' },
  { label: 'ubuntu-20.04', type: 'runner', info: 'Ubuntu 20.04' },
  { label: 'windows-latest', type: 'runner', info: 'Windows runner' },
  { label: 'windows-2022', type: 'runner', info: 'Windows 2022' },
  { label: 'macos-latest', type: 'runner', info: 'macOS runner' },
  { label: 'macos-14', type: 'runner', info: 'macOS 14 (Sonoma)' },
  { label: 'macos-13', type: 'runner', info: 'macOS 13 (Ventura)' },
  { label: 'self-hosted', type: 'runner', info: 'Self-hosted runner' },
  // More Ansible modules
  { label: 'ansible.builtin.docker_container', type: 'module', info: 'Docker ctr' },
  { label: 'ansible.posix.sysctl', type: 'module', info: 'sysctl' },
  { label: 'ansible.posix.mount', type: 'module', info: 'mount' },
  { label: 'ansible.posix.firewalld', type: 'module', info: 'firewalld' },
  { label: 'community.crypto.openssl_certificate', type: 'module', info: 'OpenSSL cert' },
  { label: 'community.crypto.openssl_privatekey', type: 'module', info: 'Private key' },
  { label: 'kubernetes.core.k8s', type: 'module', info: 'K8s apply' },
  { label: 'kubernetes.core.helm', type: 'module', info: 'Helm ops' },
  { label: 'amazon.aws.ec2_instance', type: 'module', info: 'AWS EC2' },
  { label: 'amazon.aws.s3_bucket', type: 'module', info: 'AWS S3' },
  { label: 'google.cloud.gcp_compute_instance', type: 'module', info: 'GCP VM' },
  { label: 'azure.azcollection.azure_rm_virtualmachine', type: 'module', info: 'Azure VM' },
  // Prometheus / CI common
  { label: 'groups', type: 'property', info: 'Prom rule groups' },
  { label: 'rules', type: 'property', info: 'Rules list' },
  { label: 'alert', type: 'property', info: 'Alert name' },
  { label: 'expr', type: 'property', info: 'PromQL expr' },
  { label: 'for', type: 'property', info: 'Alert for' },
  { label: 'scrape_configs', type: 'property', info: 'Prom scrape' },
  { label: 'job_name', type: 'property', info: 'Prom job name' },
  { label: 'static_configs', type: 'property', info: 'Static targets' },
  { label: 'targets', type: 'property', info: 'Target list' },
  { label: 'relabel_configs', type: 'property', info: 'Relabel rules' },
  { label: 'metric_relabel_configs', type: 'property', info: 'Metric relabel' },
  { label: 'file_sd_configs', type: 'property', info: 'File SD' },
  { label: 'kubernetes_sd_configs', type: 'property', info: 'K8s SD' },
  { label: 'consul_sd_configs', type: 'property', info: 'Consul SD' },
  { label: 'dns_sd_configs', type: 'property', info: 'DNS SD' },
  { label: 'ec2_sd_configs', type: 'property', info: 'EC2 SD' },
  // OpenAPI / Swagger
  { label: 'openapi', type: 'property', info: 'OpenAPI version' },
  { label: 'swagger', type: 'property', info: 'Swagger version' },
  { label: 'info', type: 'property', info: 'Info block' },
  { label: 'servers', type: 'property', info: 'Server list' },
  { label: 'paths', type: 'property', info: 'Paths object' },
  { label: 'components', type: 'property', info: 'Components object' },
  { label: 'schemas', type: 'property', info: 'Schemas' },
  { label: 'parameters', type: 'property', info: 'Parameters' },
  { label: 'responses', type: 'property', info: 'Responses' },
  { label: 'requestBodies', type: 'property', info: 'Request bodies' },
  { label: 'headers', type: 'property', info: 'Headers' },
  { label: 'securitySchemes', type: 'property', info: 'Sec schemes' },
  { label: 'security', type: 'property', info: 'Security req' },
  { label: 'tags', type: 'property', info: 'OpenAPI tags' },
  { label: 'externalDocs', type: 'property', info: 'External docs' },
  // More OpenAPI fields
  { label: 'title', type: 'property', info: 'Doc title' },
  { label: 'description', type: 'property', info: 'Description' },
  { label: 'version', type: 'property', info: 'API version' },
  { label: 'termsOfService', type: 'property', info: 'TOS URL' },
  { label: 'contact', type: 'property', info: 'Contact info' },
  { label: 'license', type: 'property', info: 'License info' },
  { label: 'url', type: 'property', info: 'URL' },
  { label: 'variables', type: 'property', info: 'Server vars' },
  { label: 'summary', type: 'property', info: 'Short summary' },
  { label: 'operationId', type: 'property', info: 'Operation ID' },
  { label: 'deprecated', type: 'property', info: 'Deprecated flag' },
  { label: 'requestBody', type: 'property', info: 'Request body' },
  { label: 'content', type: 'property', info: 'Content map' },
  { label: 'required', type: 'property', info: 'Required fields' },
  { label: 'schema', type: 'property', info: 'Schema ref' },
  { label: '$ref', type: 'property', info: 'Ref pointer' },
  { label: 'type', type: 'property', info: 'Schema type' },
  { label: 'format', type: 'property', info: 'Schema format' },
  { label: 'enum', type: 'property', info: 'Enum values' },
  { label: 'pattern', type: 'property', info: 'Regex pattern' },
  { label: 'minimum', type: 'property', info: 'Min value' },
  { label: 'maximum', type: 'property', info: 'Max value' },
  { label: 'exclusiveMinimum', type: 'property', info: 'Excl min' },
  { label: 'exclusiveMaximum', type: 'property', info: 'Excl max' },
  { label: 'minLength', type: 'property', info: 'Min length' },
  { label: 'maxLength', type: 'property', info: 'Max length' },
  { label: 'minItems', type: 'property', info: 'Min items' },
  { label: 'maxItems', type: 'property', info: 'Max items' },
  { label: 'uniqueItems', type: 'property', info: 'Unique items' },
  { label: 'items', type: 'property', info: 'Array items' },
  { label: 'properties', type: 'property', info: 'Object props' },
  { label: 'additionalProperties', type: 'property', info: 'Extra props' },
  { label: 'allOf', type: 'property', info: 'AllOf schemas' },
  { label: 'anyOf', type: 'property', info: 'AnyOf schemas' },
  { label: 'oneOf', type: 'property', info: 'OneOf schemas' },
  { label: 'not', type: 'property', info: 'Not schema' },
  { label: 'discriminator', type: 'property', info: 'Discriminator' },
  { label: 'readOnly', type: 'property', info: 'Read-only field' },
  { label: 'writeOnly', type: 'property', info: 'Write-only field' },
  { label: 'example', type: 'property', info: 'Example value' },
  { label: 'examples', type: 'property', info: 'Examples map' },
  { label: 'nullable', type: 'property', info: 'Nullable flag' },
  { label: 'default', type: 'property', info: 'Default value' },
  { label: 'in', type: 'property', info: 'Parameter in' },
  { label: 'query', type: 'property', info: 'Query param' },
  { label: 'header', type: 'property', info: 'Header param' },
  { label: 'path', type: 'property', info: 'Path param' },
  { label: 'cookie', type: 'property', info: 'Cookie param' },
  { label: 'style', type: 'property', info: 'Param style' },
  { label: 'explode', type: 'property', info: 'Param explode' },
  { label: 'allowReserved', type: 'property', info: 'Allow reserved' },
  { label: 'encoding', type: 'property', info: 'Encoding map' },
  { label: 'bearerFormat', type: 'property', info: 'Bearer format' },
  { label: 'flows', type: 'property', info: 'OAuth flows' },
  { label: 'openIdConnectUrl', type: 'property', info: 'OIDC URL' },
  // gRPC / protobuf config
  { label: 'grpc_service', type: 'property', info: 'gRPC service' },
  { label: 'grpc_method', type: 'property', info: 'gRPC method' },
  { label: 'service', type: 'property', info: 'Service name' },
  // Istio
  { label: 'VirtualService', type: 'kind', info: 'Istio VS' },
  { label: 'DestinationRule', type: 'kind', info: 'Istio DR' },
  { label: 'Gateway', type: 'kind', info: 'Istio Gateway' },
  { label: 'ServiceEntry', type: 'kind', info: 'Istio SE' },
  { label: 'Sidecar', type: 'kind', info: 'Istio Sidecar' },
  { label: 'EnvoyFilter', type: 'kind', info: 'Envoy filter' },
  { label: 'PeerAuthentication', type: 'kind', info: 'mTLS policy' },
  { label: 'AuthorizationPolicy', type: 'kind', info: 'Authz policy' },
  { label: 'RequestAuthentication', type: 'kind', info: 'Req auth' },
  { label: 'Telemetry', type: 'kind', info: 'Telemetry config' },
  { label: 'WorkloadEntry', type: 'kind', info: 'Workload entry' },
  { label: 'WorkloadGroup', type: 'kind', info: 'Workload group' },
  // ArgoCD
  { label: 'Application', type: 'kind', info: 'Argo Application' },
  { label: 'ApplicationSet', type: 'kind', info: 'Argo AppSet' },
  { label: 'AppProject', type: 'kind', info: 'Argo project' },
  // Knative / serverless
  { label: 'Service', type: 'kind', info: 'Knative Service' },
  { label: 'Configuration', type: 'kind', info: 'Knative Config' },
  { label: 'Revision', type: 'kind', info: 'Knative Revision' },
  { label: 'Route', type: 'kind', info: 'Knative Route' },
  { label: 'EventType', type: 'kind', info: 'Knative EventType' },
  { label: 'Trigger', type: 'kind', info: 'Knative Trigger' },
  { label: 'Broker', type: 'kind', info: 'Knative Broker' },
  // Cert-manager
  { label: 'Certificate', type: 'kind', info: 'cert-manager cert' },
  { label: 'Issuer', type: 'kind', info: 'cert-manager issuer' },
  { label: 'ClusterIssuer', type: 'kind', info: 'Cluster issuer' },
  { label: 'CertificateRequest', type: 'kind', info: 'Cert request' },
  { label: 'Order', type: 'kind', info: 'ACME order' },
  { label: 'Challenge', type: 'kind', info: 'ACME challenge' },
  // Additional Ansible keys
  { label: 'tags', type: 'ansible', info: 'Play tags' },
  { label: 'vars', type: 'ansible', info: 'Play vars' },
  { label: 'tasks', type: 'ansible', info: 'Play tasks' },
  { label: 'loop', type: 'ansible', info: 'Task loop' },
  { label: 'until', type: 'ansible', info: 'Retry until' },
  { label: 'retries', type: 'ansible', info: 'Retry count' },
  { label: 'delay', type: 'ansible', info: 'Retry delay' },
  { label: 'async', type: 'ansible', info: 'Async timeout' },
  { label: 'poll', type: 'ansible', info: 'Poll async' },
  { label: 'block', type: 'ansible', info: 'Block of tasks' },
  { label: 'rescue', type: 'ansible', info: 'Rescue tasks' },
  { label: 'always', type: 'ansible', info: 'Always tasks' },
  // Additional Compose keys
  { label: 'credential_spec', type: 'compose', info: 'Cred spec' },
  { label: 'env', type: 'compose', info: 'Env map' },
  { label: 'links', type: 'compose', info: 'Service links' },
  { label: 'external_links', type: 'compose', info: 'External links' },
  { label: 'scale', type: 'compose', info: 'Service scale' },
  { label: 'blkio_config', type: 'compose', info: 'Block IO config' },
  { label: 'cpu_count', type: 'compose', info: 'CPU count' },
  { label: 'cpu_percent', type: 'compose', info: 'CPU percent' },
  { label: 'cpus', type: 'compose', info: 'Number of CPUs' },
  { label: 'cpu_shares', type: 'compose', info: 'CPU shares' },
  { label: 'cpu_quota', type: 'compose', info: 'CPU quota' },
  { label: 'cpu_period', type: 'compose', info: 'CPU period' },
  { label: 'cpu_rt_period', type: 'compose', info: 'CPU RT period' },
  { label: 'cpu_rt_runtime', type: 'compose', info: 'CPU RT runtime' },
  { label: 'cpuset', type: 'compose', info: 'CPU set' },
  { label: 'mem_limit', type: 'compose', info: 'Memory limit' },
  { label: 'mem_reservation', type: 'compose', info: 'Mem reservation' },
  { label: 'memswap_limit', type: 'compose', info: 'Memswap limit' },
  { label: 'mem_swappiness', type: 'compose', info: 'Mem swappiness' },
  { label: 'oom_kill_disable', type: 'compose', info: 'OOM kill disable' },
  { label: 'oom_score_adj', type: 'compose', info: 'OOM score adj' },
  { label: 'pids_limit', type: 'compose', info: 'PIDs limit' },
  { label: 'runtime', type: 'compose', info: 'Container runtime' },
  { label: 'secrets', type: 'compose', info: 'Service secrets' },
];
