// Completion entries for zig.
// Auto-generated from the legacy monolithic completions.js by
// `scripts/split-completions.mjs`. Safe to hand-edit after the split —
// just keep the `export default` array shape.
//
// Entry shape: { label, type, info, apply? }
//   - `type` is one of keyword / function / class / variable / module
//     / constant / method / property / snippet
//   - `info` is a ≤60-char description shown in the autocomplete tooltip
//   - `apply` (optional) overrides what gets inserted when the entry is
//     chosen — used for snippets with placeholders

export default [
  { label: 'const', type: 'keyword', info: 'Constant binding' },
  { label: 'var', type: 'keyword', info: 'Variable binding' },
  { label: 'fn', type: 'keyword', info: 'Function' },
  { label: 'pub', type: 'keyword', info: 'Public visibility' },
  { label: 'extern', type: 'keyword', info: 'Extern C' },
  { label: 'export', type: 'keyword', info: 'Exported symbol' },
  { label: 'inline', type: 'keyword', info: 'Inline function' },
  { label: 'noinline', type: 'keyword', info: 'No inline' },
  { label: 'comptime', type: 'keyword', info: 'Compile-time' },
  { label: 'packed', type: 'keyword', info: 'Packed struct' },
  { label: 'align', type: 'keyword', info: 'Alignment' },
  { label: 'threadlocal', type: 'keyword', info: 'Thread-local' },
  { label: 'struct', type: 'keyword', info: 'Struct type' },
  { label: 'enum', type: 'keyword', info: 'Enum type' },
  { label: 'union', type: 'keyword', info: 'Union type' },
  { label: 'opaque', type: 'keyword', info: 'Opaque type' },
  { label: 'error', type: 'keyword', info: 'Error union' },
  { label: 'try', type: 'keyword', info: 'Try expression' },
  { label: 'catch', type: 'keyword', info: 'Catch error' },
  { label: 'defer', type: 'keyword', info: 'Defer cleanup' },
  { label: 'errdefer', type: 'keyword', info: 'Errdefer cleanup' },
  { label: 'unreachable', type: 'keyword', info: 'Unreachable' },
  { label: 'if', type: 'keyword', info: 'If expression' },
  { label: 'else', type: 'keyword', info: 'Else branch' },
  { label: 'switch', type: 'keyword', info: 'Switch expression' },
  { label: 'for', type: 'keyword', info: 'For loop' },
  { label: 'while', type: 'keyword', info: 'While loop' },
  { label: 'break', type: 'keyword', info: 'Break loop' },
  { label: 'continue', type: 'keyword', info: 'Continue loop' },
  { label: 'return', type: 'keyword', info: 'Return value' },
  { label: 'test', type: 'keyword', info: 'Test block' },
  { label: 'orelse', type: 'keyword', info: 'Unwrap optional' },
  { label: 'and', type: 'keyword', info: 'Logical AND' },
  { label: 'or', type: 'keyword', info: 'Logical OR' },
  { label: 'null', type: 'keyword', info: 'Null optional' },
  { label: 'true', type: 'keyword', info: 'True' },
  { label: 'false', type: 'keyword', info: 'False' },
  { label: 'undefined', type: 'keyword', info: 'Undefined value' },
  { label: 'anytype', type: 'keyword', info: 'Generic type' },
  { label: 'anyerror', type: 'keyword', info: 'Any error set' },
  { label: 'void', type: 'keyword', info: 'Void type' },
  { label: 'noreturn', type: 'keyword', info: 'Never returns' },
  { label: 'usingnamespace', type: 'keyword', info: 'Use namespace' },
  { label: 'async', type: 'keyword', info: 'Async call' },
  { label: 'await', type: 'keyword', info: 'Await frame' },
  { label: 'suspend', type: 'keyword', info: 'Suspend coroutine' },
  { label: 'resume', type: 'keyword', info: 'Resume coroutine' },
  { label: 'nosuspend', type: 'keyword', info: 'No suspend' },
  { label: 'linksection', type: 'keyword', info: 'Link section' },
  // Types
  { label: 'i8', type: 'type', info: '8-bit signed' },
  { label: 'i16', type: 'type', info: '16-bit signed' },
  { label: 'i32', type: 'type', info: '32-bit signed' },
  { label: 'i64', type: 'type', info: '64-bit signed' },
  { label: 'i128', type: 'type', info: '128-bit signed' },
  { label: 'u8', type: 'type', info: '8-bit unsigned' },
  { label: 'u16', type: 'type', info: '16-bit unsigned' },
  { label: 'u32', type: 'type', info: '32-bit unsigned' },
  { label: 'u64', type: 'type', info: '64-bit unsigned' },
  { label: 'u128', type: 'type', info: '128-bit unsigned' },
  { label: 'usize', type: 'type', info: 'Pointer-size uint' },
  { label: 'isize', type: 'type', info: 'Pointer-size int' },
  { label: 'f16', type: 'type', info: '16-bit float' },
  { label: 'f32', type: 'type', info: '32-bit float' },
  { label: 'f64', type: 'type', info: '64-bit float' },
  { label: 'f128', type: 'type', info: '128-bit float' },
  { label: 'bool', type: 'type', info: 'Boolean' },
  { label: 'c_int', type: 'type', info: 'C int' },
  { label: 'c_uint', type: 'type', info: 'C unsigned' },
  { label: 'c_long', type: 'type', info: 'C long' },
  { label: 'c_ulong', type: 'type', info: 'C unsigned long' },
  { label: 'type', type: 'type', info: 'Type type' },
  // Std
  { label: 'std', type: 'module', info: 'Standard library' },
  { label: 'std.debug.print', type: 'function', info: 'Debug print' },
  { label: 'std.debug.assert', type: 'function', info: 'Assert' },
  { label: 'std.log', type: 'module', info: 'Log module' },
  { label: 'std.mem', type: 'module', info: 'Memory utils' },
  { label: 'std.mem.eql', type: 'function', info: 'Slice equality' },
  { label: 'std.mem.copy', type: 'function', info: 'Copy bytes' },
  { label: 'std.mem.Allocator', type: 'type', info: 'Allocator interface' },
  { label: 'std.fmt', type: 'module', info: 'Format utils' },
  { label: 'std.fmt.format', type: 'function', info: 'Format string' },
  { label: 'std.fmt.allocPrint', type: 'function', info: 'Alloc printf' },
  { label: 'std.fmt.bufPrint', type: 'function', info: 'Buffer printf' },
  { label: 'std.os', type: 'module', info: 'OS utils' },
  { label: 'std.fs', type: 'module', info: 'Filesystem' },
  { label: 'std.fs.cwd', type: 'function', info: 'Current working dir' },
  { label: 'std.heap', type: 'module', info: 'Heap allocators' },
  { label: 'std.heap.GeneralPurposeAllocator', type: 'class', info: 'GPA' },
  { label: 'std.heap.page_allocator', type: 'variable', info: 'Page allocator' },
  { label: 'std.heap.ArenaAllocator', type: 'class', info: 'Arena allocator' },
  { label: 'std.ArrayList', type: 'class', info: 'Dynamic array' },
  { label: 'std.StringHashMap', type: 'class', info: 'String hash map' },
  { label: 'std.AutoHashMap', type: 'class', info: 'Auto hash map' },
  { label: 'std.Thread', type: 'class', info: 'Thread' },
  { label: 'std.io', type: 'module', info: 'I/O module' },
  { label: 'std.io.getStdOut', type: 'function', info: 'Get stdout' },
  { label: 'std.io.getStdIn', type: 'function', info: 'Get stdin' },
  { label: 'std.io.getStdErr', type: 'function', info: 'Get stderr' },
  { label: 'std.time', type: 'module', info: 'Time module' },
  { label: 'std.testing', type: 'module', info: 'Testing utils' },
  { label: 'std.testing.expect', type: 'function', info: 'Expect true' },
  { label: 'std.testing.expectEqual', type: 'function', info: 'Expect equal' },
  { label: 'std.testing.expectError', type: 'function', info: 'Expect error' },
  { label: 'std.ChildProcess', type: 'class', info: 'Child process' },
  { label: 'std.json', type: 'module', info: 'JSON module' },
  // Builtins
  { label: '@import', type: 'function', info: 'Import module' },
  { label: '@cImport', type: 'function', info: 'Import C header' },
  { label: '@cInclude', type: 'function', info: 'Include C header' },
  { label: '@sizeOf', type: 'function', info: 'Size of type' },
  { label: '@alignOf', type: 'function', info: 'Alignment of type' },
  { label: '@typeOf', type: 'function', info: 'Type of expr' },
  { label: '@TypeOf', type: 'function', info: 'Type of expr (new)' },
  { label: '@as', type: 'function', info: 'Cast to type' },
  { label: '@intCast', type: 'function', info: 'Integer cast' },
  { label: '@floatCast', type: 'function', info: 'Float cast' },
  { label: '@bitCast', type: 'function', info: 'Bit cast' },
  { label: '@ptrCast', type: 'function', info: 'Pointer cast' },
  { label: '@enumFromInt', type: 'function', info: 'Enum from int' },
  { label: '@intFromEnum', type: 'function', info: 'Int from enum' },
  { label: '@floatFromInt', type: 'function', info: 'Float from int' },
  { label: '@intFromFloat', type: 'function', info: 'Int from float' },
  { label: '@ptrFromInt', type: 'function', info: 'Ptr from int' },
  { label: '@intFromPtr', type: 'function', info: 'Int from ptr' },
  { label: '@compileError', type: 'function', info: 'Compile error' },
  { label: '@compileLog', type: 'function', info: 'Compile log' },
  { label: '@panic', type: 'function', info: 'Panic' },
  { label: '@embedFile', type: 'function', info: 'Embed file' },
  { label: '@min', type: 'function', info: 'Minimum' },
  { label: '@max', type: 'function', info: 'Maximum' },
  { label: '@mod', type: 'function', info: 'Modulo' },
  { label: '@rem', type: 'function', info: 'Remainder' },
  { label: '@abs', type: 'function', info: 'Absolute value' },
  { label: '@sqrt', type: 'function', info: 'Square root' },
  { label: '@memcpy', type: 'function', info: 'Memcpy' },
  { label: '@memset', type: 'function', info: 'Memset' },
  { label: '@fence', type: 'function', info: 'Memory fence' },
  { label: '@atomicLoad', type: 'function', info: 'Atomic load' },
  { label: '@atomicStore', type: 'function', info: 'Atomic store' },
  { label: '@atomicRmw', type: 'function', info: 'Atomic RMW' },
];
