// Crystal completion data — targets ≥ 2,000 unique entries.
import { EntrySet } from './helpers.mjs';

export function buildCrystal() {
  const s = new EntrySet('crystal');

  // ── Keywords ───────────────────────────────────────────────────────
  s.addBulk([
    ['abstract', 'keyword', 'abstract class/def', 'Marks a class/method abstract'],
    ['alias', 'keyword', 'alias Name = Type', 'Type alias declaration'],
    ['annotation', 'keyword', 'annotation Name end', 'Define a custom annotation'],
    ['as', 'keyword', 'expr.as(Type)', 'Type cast (raises on failure)'],
    ['as?', 'keyword', 'expr.as?(Type)', 'Type cast returning nil on failure'],
    ['asm', 'keyword', null, 'Inline assembly block'],
    ['begin', 'keyword', 'begin ... end', 'Begin/rescue/ensure block'],
    ['break', 'keyword', null, 'Exit innermost loop or block'],
    ['case', 'keyword', 'case x; when ... end', 'Pattern-matching case expression'],
    ['class', 'keyword', 'class Name end', 'Class declaration'],
    ['def', 'keyword', 'def name(args) end', 'Method definition'],
    ['do', 'keyword', 'expr do |x| ... end', 'Block introducer'],
    ['else', 'keyword', null, 'Else branch of if/case/begin'],
    ['elsif', 'keyword', null, 'Else-if branch'],
    ['end', 'keyword', null, 'Closes def/class/module/block'],
    ['ensure', 'keyword', null, 'Always-executed cleanup clause'],
    ['enum', 'keyword', 'enum Name; end', 'Enum declaration'],
    ['extend', 'keyword', 'extend Module', 'Mixin module at class level'],
    ['false', 'constant', 'Bool', 'Boolean false'],
    ['for', 'keyword', null, 'Reserved (use each instead)'],
    ['forall', 'keyword', 'def f(x) forall T', 'Free type variable list'],
    ['fun', 'keyword', 'fun name : Type', 'C-callable function in lib'],
    ['if', 'keyword', 'if cond ... end', 'Conditional expression'],
    ['in', 'keyword', null, 'Used in case/when ranges'],
    ['include', 'keyword', 'include Module', 'Mixin module at instance level'],
    ['instance_sizeof', 'keyword', 'instance_sizeof(T)', 'Instance size in bytes'],
    ['is_a?', 'keyword', 'x.is_a?(Type)', 'Runtime type predicate'],
    ['lib', 'keyword', 'lib LibC end', 'C library binding block'],
    ['macro', 'keyword', 'macro name() end', 'Macro definition'],
    ['module', 'keyword', 'module Name end', 'Module declaration'],
    ['next', 'keyword', null, 'Skip to next iteration'],
    ['nil', 'constant', 'Nil', 'The nil singleton'],
    ['nil?', 'keyword', 'x.nil?', 'Test for nil'],
    ['of', 'keyword', 'Array(Int32).new of: Int32', 'Type qualifier in literals'],
    ['out', 'keyword', null, 'Output parameter for C calls'],
    ['pointerof', 'keyword', 'pointerof(var)', 'Pointer to a variable'],
    ['private', 'keyword', null, 'Private visibility modifier'],
    ['protected', 'keyword', null, 'Protected visibility modifier'],
    ['require', 'keyword', "require \"path\"", 'Load source file'],
    ['rescue', 'keyword', 'rescue ex : Type', 'Catch an exception'],
    ['return', 'keyword', null, 'Return from method'],
    ['select', 'keyword', 'select; when ch.receive end', 'Multi-channel select'],
    ['self', 'keyword', null, 'Current object / class'],
    ['sizeof', 'keyword', 'sizeof(T)', 'Size of a type'],
    ['struct', 'keyword', 'struct Name end', 'Value-type struct'],
    ['super', 'keyword', null, 'Call superclass method'],
    ['then', 'keyword', null, 'Optional then in if/case'],
    ['true', 'constant', 'Bool', 'Boolean true'],
    ['type', 'keyword', null, 'Type declaration in lib'],
    ['typeof', 'keyword', 'typeof(expr)', 'Compile-time type of expr'],
    ['uninitialized', 'keyword', 'x = uninitialized T', 'Skip default initialization'],
    ['union', 'keyword', null, 'Union type in lib block'],
    ['unless', 'keyword', 'unless cond ... end', 'Negated if'],
    ['until', 'keyword', 'until cond ... end', 'Negated while'],
    ['verbatim', 'keyword', null, 'Macro verbatim block'],
    ['when', 'keyword', null, 'Case branch'],
    ['while', 'keyword', 'while cond ... end', 'Loop while truthy'],
    ['with', 'keyword', 'with obj yield', 'Block scope with default receiver'],
    ['yield', 'keyword', null, 'Yield to caller block'],
  ]);

  // ── Built-in types ─────────────────────────────────────────────────
  s.addBulk([
    ['Bool', 'type', 'true | false', 'Boolean type'],
    ['Char', 'type', 'UTF-8 codepoint', '32-bit unicode codepoint'],
    ['Float32', 'type', '32-bit IEEE float', 'Single-precision float'],
    ['Float64', 'type', '64-bit IEEE float', 'Double-precision float'],
    ['Int8', 'type', '-128..127', '8-bit signed integer'],
    ['Int16', 'type', '-32_768..32_767', '16-bit signed integer'],
    ['Int32', 'type', 'Default integer', '32-bit signed integer'],
    ['Int64', 'type', '64-bit signed', '64-bit signed integer'],
    ['Int128', 'type', '128-bit signed', '128-bit signed integer'],
    ['UInt8', 'type', '0..255', '8-bit unsigned integer'],
    ['UInt16', 'type', '0..65_535', '16-bit unsigned integer'],
    ['UInt32', 'type', null, '32-bit unsigned integer'],
    ['UInt64', 'type', null, '64-bit unsigned integer'],
    ['UInt128', 'type', null, '128-bit unsigned integer'],
    ['String', 'type', 'UTF-8 string', 'Immutable UTF-8 string'],
    ['Symbol', 'type', ':sym', 'Interned label'],
    ['Nil', 'type', 'nil', 'Type containing only nil'],
    ['Object', 'type', null, 'Root of every type'],
    ['Reference', 'type', null, 'Heap-allocated objects'],
    ['Value', 'type', null, 'Stack-allocated values'],
    ['Number', 'type', null, 'Common numeric ancestor'],
    ['Float', 'type', null, 'Float ancestor'],
    ['Int', 'type', null, 'Integer ancestor'],
    ['Bytes', 'type', 'Slice(UInt8)', 'Byte buffer'],
    ['Pointer', 'type', 'Pointer(T)', 'Raw memory pointer'],
    ['Slice', 'type', 'Slice(T)', 'View over contiguous memory'],
    ['Tuple', 'type', '{T1, T2, ...}', 'Fixed-size heterogeneous tuple'],
    ['NamedTuple', 'type', '{name: T, ...}', 'Tuple with named fields'],
    ['Array', 'type', 'Array(T)', 'Resizable ordered collection'],
    ['Hash', 'type', 'Hash(K, V)', 'Hash map'],
    ['Range', 'type', 'a..b / a...b', 'Range of values'],
    ['Regex', 'type', '/pat/', 'Regular expression'],
    ['Set', 'type', 'Set(T)', 'Hash-backed set'],
    ['Deque', 'type', 'Deque(T)', 'Double-ended queue'],
    ['BitArray', 'type', null, 'Compact bit-vector'],
    ['IO', 'type', null, 'Abstract I/O stream'],
    ['File', 'type', null, 'File handle'],
    ['Dir', 'type', null, 'Directory entry iterator'],
    ['Time', 'type', null, 'Calendar moment with offset'],
    ['URI', 'type', null, 'Parsed URI'],
    ['JSON', 'namespace', null, 'JSON parser/builder namespace'],
    ['YAML', 'namespace', null, 'YAML parser/builder namespace'],
    ['Proc', 'type', '->(args) : R', 'First-class function value'],
    ['Box', 'type', null, 'Boxed reference for void* interop'],
    ['StaticArray', 'type', 'StaticArray(T, N)', 'Fixed-size stack array'],
    ['Enumerable', 'type', null, 'Enumerable mixin module'],
    ['Iterator', 'type', null, 'Lazy iteration protocol'],
    ['Iterable', 'type', null, 'Iterable mixin module'],
    ['Indexable', 'type', null, 'Indexable mixin module'],
    ['Comparable', 'type', null, 'Comparable mixin module'],
  ]);

  // ── Exception hierarchy ────────────────────────────────────────────
  s.addBulk([
    ['Exception', 'class', 'class Exception', 'Root exception class'],
    ['RuntimeError', 'class', null, 'Generic runtime failure'],
    ['IndexError', 'class', null, 'Out-of-bounds index'],
    ['KeyError', 'class', null, 'Missing hash key'],
    ['ArgumentError', 'class', null, 'Invalid argument value'],
    ['TypeCastError', 'class', null, 'as cast failed'],
    ['OverflowError', 'class', null, 'Numeric overflow'],
    ['DivisionByZeroError', 'class', null, 'Integer division by zero'],
    ['NilAssertionError', 'class', null, 'not_nil! on nil value'],
    ['NotImplementedError', 'class', null, 'Method intentionally unimplemented'],
    ['InvalidByteSequenceError', 'class', null, 'Invalid UTF-8 byte sequence'],
    ['IO::Error', 'class', null, 'Generic I/O error'],
    ['IO::EOFError', 'class', null, 'Unexpected end-of-file'],
    ['IO::TimeoutError', 'class', null, 'I/O timeout'],
    ['File::Error', 'class', null, 'File system error'],
    ['File::NotFoundError', 'class', null, 'Path does not exist'],
    ['File::AccessDeniedError', 'class', null, 'Permission denied'],
    ['File::AlreadyExistsError', 'class', null, 'Path already exists'],
    ['File::BadPatternError', 'class', null, 'Invalid glob pattern'],
    ['Errno', 'class', null, 'OS errno wrapper'],
    ['JSON::ParseException', 'class', null, 'Malformed JSON input'],
    ['JSON::SerializableError', 'class', null, 'JSON::Serializable failure'],
    ['YAML::ParseException', 'class', null, 'Malformed YAML input'],
    ['Channel::ClosedError', 'class', null, 'Operation on a closed channel'],
    ['RegexError', 'class', null, 'Invalid regular expression'],
    ['Concurrent::CanceledError', 'class', null, 'Future canceled'],
    ['Socket::Error', 'class', null, 'Socket operation failed'],
    ['Socket::ConnectError', 'class', null, 'Connect/accept failed'],
    ['Socket::BindError', 'class', null, 'Bind failed'],
    ['HTTP::Server::ClientError', 'class', null, 'HTTP server client error'],
    ['OpenSSL::Error', 'class', null, 'OpenSSL operation failed'],
    ['DB::Error', 'class', null, 'Database error'],
    ['DB::ConnectionLost', 'class', null, 'Database connection dropped'],
    ['URI::Error', 'class', null, 'Invalid URI'],
    ['Compress::Gzip::Error', 'class', null, 'Gzip stream error'],
    ['Compress::Deflate::Error', 'class', null, 'Deflate error'],
    ['XML::Error', 'class', null, 'XML parse error'],
    ['Spec::AssertionFailed', 'class', null, 'Spec expectation failed'],
  ]);

  // ── Top-level kernel methods ───────────────────────────────────────
  s.addBulk([
    ['puts', 'function', 'puts(*args)', 'Print arguments and newline'],
    ['print', 'function', 'print(*args)', 'Print arguments without newline'],
    ['p', 'function', 'p(*args)', 'Inspect-print and return value'],
    ['pp', 'function', 'pp(*args)', 'Pretty-print arguments'],
    ['p!', 'function', 'p!(expr)', 'Print expression source + value'],
    ['pp!', 'function', 'pp!(expr)', 'Pretty-print expression source + value'],
    ['gets', 'function', 'gets : String?', 'Read line from STDIN'],
    ['read_line', 'function', null, 'Read line from STDIN, raise on EOF'],
    ['at_exit', 'function', 'at_exit { ... }', 'Register exit handler'],
    ['exit', 'function', 'exit(status = 0)', 'Terminate process'],
    ['abort', 'function', "abort(\"msg\", status = 1)", 'Print and exit'],
    ['caller', 'function', 'caller : Array(String)', 'Current call stack'],
    ['loop', 'function', 'loop { ... }', 'Infinite loop'],
    ['sleep', 'function', 'sleep(seconds)', 'Pause current fiber'],
    ['spawn', 'function', 'spawn { ... }', 'Start a new fiber'],
    ['raise', 'function', 'raise ex', 'Raise an exception'],
    ['Box', 'function', 'Box.box(obj)', 'Box for void* interop'],
    ['__DIR__', 'constant', 'String', 'Directory of current file'],
    ['__FILE__', 'constant', 'String', 'Path of current file'],
    ['__LINE__', 'constant', 'Int32', 'Current source line'],
    ['__END_LINE__', 'constant', 'Int32', 'Last line of enclosing scope'],
    ['parallel', 'function', 'parallel(a, b)', 'Run blocks concurrently'],
    ['delay', 'function', 'delay(seconds) { ... }', 'Run block after delay'],
    ['future', 'function', 'future { compute }', 'Eager future evaluation'],
    ['lazy', 'function', 'lazy { compute }', 'Lazy future evaluation'],
    ['debugger', 'function', null, 'Trigger attached debugger'],
    ['hash', 'function', 'hash(*values)', 'Hash multiple values'],
    ['sprintf', 'function', 'sprintf(fmt, *args)', 'Format to string'],
    ['printf', 'function', 'printf(fmt, *args)', 'Format and print'],
    ['system', 'function', "system(\"cmd\")", 'Run shell command'],
    ['rand', 'function', 'rand : Float64', 'Random number'],
    ['srand', 'function', 'srand(seed)', 'Seed default RNG'],
    ['main', 'function', null, 'Crystal program entry point'],
    ['exit!', 'function', 'exit!(status)', 'Exit without at_exit hooks'],
    ['fork', 'function', 'fork { ... }', 'Fork a new process'],
    ['ARGV', 'constant', 'Array(String)', 'Command-line arguments'],
    ['ARGF', 'constant', 'IO', 'Concatenation of ARGV files / STDIN'],
    ['STDIN', 'constant', 'IO::FileDescriptor', 'Standard input'],
    ['STDOUT', 'constant', 'IO::FileDescriptor', 'Standard output'],
    ['STDERR', 'constant', 'IO::FileDescriptor', 'Standard error'],
    ['ENV', 'constant', 'Hash(String, String)', 'Environment variables'],
    ['PROGRAM_NAME', 'constant', 'String', 'Name of running program'],
    ['Crystal', 'namespace', null, 'Crystal compiler namespace'],
    ['VERSION', 'constant', 'String', 'Crystal version'],
    ['BUILD_COMMIT', 'constant', 'String', 'Build commit hash'],
    ['BUILD_DATE', 'constant', 'String', 'Build date'],
    ['DESCRIPTION', 'constant', 'String', 'Crystal description'],
    ['HOST_TRIPLE', 'constant', 'String', 'Host LLVM triple'],
    ['TARGET_TRIPLE', 'constant', 'String', 'Target LLVM triple'],
    ['LIBRARY_PATH', 'constant', 'String', 'Standard library path'],
    ['PATH', 'constant', 'String', 'Source path lookup'],
    ['Process', 'namespace', null, 'Process management namespace'],
    ['GC', 'namespace', null, 'Garbage collector namespace'],
    ['Thread', 'class', null, 'Native OS thread (rarely used)'],
    ['Atomic', 'class', 'Atomic(T)', 'Atomic value'],
    ['Channel', 'class', 'Channel(T)', 'Fiber communication channel'],
    ['Fiber', 'class', null, 'Lightweight cooperative thread'],
    ['Mutex', 'class', null, 'Mutual exclusion lock'],
    ['Reference', 'class', null, 'Heap-allocated reference root'],
    ['Pretty', 'namespace', null, 'Pretty-printing helpers'],
    ['Random', 'namespace', null, 'Random number generation'],
    ['Math', 'namespace', null, 'Math functions / constants'],
    ['Iterator', 'namespace', null, 'Lazy iteration helpers'],
    ['Comparable', 'namespace', null, 'Comparable mixin'],
    ['Enumerable', 'namespace', null, 'Enumerable mixin'],
    ['Indexable', 'namespace', null, 'Indexable mixin'],
    ['Iterable', 'namespace', null, 'Iterable mixin'],
    ['NotNil', 'function', 'x.not_nil!', 'Assert non-nil'],
    ['typeof', 'function', 'typeof(expr)', 'Compile-time type of expr'],
    ['offsetof', 'function', 'offsetof(T, @field)', 'Field byte offset'],
    ['alignof', 'function', 'alignof(T)', 'Alignment of type'],
    ['instance_alignof', 'function', 'instance_alignof(T)', 'Instance alignment'],
  ]);

  // ── Helper to build per-receiver method entries ───────────────────
  const methodRows = (recv, items) =>
    items.map(([name, sig, doc]) => [
      `${recv}#${name}`,
      'method',
      sig || `${recv}#${name}`,
      doc || `${recv}#${name}`,
    ]);

  // ── String methods ─────────────────────────────────────────────────
  s.addBulk(methodRows('String', [
    ['size', 'String#size : Int32', 'Number of characters'],
    ['length', 'String#length : Int32', 'Alias of size'],
    ['bytesize', 'String#bytesize : Int32', 'Number of bytes'],
    ['byte_at', 'String#byte_at(i) : UInt8', 'Byte at index'],
    ['byte_at?', 'String#byte_at?(i) : UInt8?', 'Byte at index or nil'],
    ['chars', 'String#chars : Array(Char)', 'Array of characters'],
    ['each_char', 'String#each_char(&)', 'Yield each character'],
    ['bytes', 'String#bytes : Array(UInt8)', 'Array of bytes'],
    ['each_byte', 'String#each_byte(&)', 'Yield each byte'],
    ['lines', 'String#lines : Array(String)', 'Array of lines'],
    ['each_line', 'String#each_line(&)', 'Yield each line'],
    ['split', 'String#split(sep)', 'Split into substrings'],
    ['[]', 'String#[](i)', 'Character / substring access'],
    ['[]?', 'String#[]?(i)', 'Optional character access'],
    ['index', 'String#index(needle)', 'Find first occurrence'],
    ['rindex', 'String#rindex(needle)', 'Find last occurrence'],
    ['count', 'String#count(needle)', 'Count matches'],
    ['delete', 'String#delete(set)', 'Remove characters'],
    ['squeeze', 'String#squeeze(set?)', 'Collapse repeats'],
    ['tr', 'String#tr(from, to)', 'Translate characters'],
    ['gsub', 'String#gsub(pat, repl)', 'Global replace'],
    ['sub', 'String#sub(pat, repl)', 'Replace first occurrence'],
    ['replace', 'String#replace(pat, repl)', 'Alias of gsub for many cases'],
    ['chomp', 'String#chomp(suffix?)', 'Strip trailing newline / suffix'],
    ['strip', 'String#strip(set?)', 'Trim both ends'],
    ['lstrip', 'String#lstrip(set?)', 'Trim left'],
    ['rstrip', 'String#rstrip(set?)', 'Trim right'],
    ['downcase', 'String#downcase', 'Lowercase'],
    ['upcase', 'String#upcase', 'Uppercase'],
    ['capitalize', 'String#capitalize', 'Capitalize first letter'],
    ['swapcase', 'String#swapcase', 'Swap case'],
    ['titleize', 'String#titleize', 'Title-case words'],
    ['reverse', 'String#reverse', 'Reverse characters'],
    ['succ', 'String#succ', 'Next string in sequence'],
    ['to_i', 'String#to_i : Int32', 'Parse as Int32'],
    ['to_i8', 'String#to_i8 : Int8', 'Parse as Int8'],
    ['to_i16', 'String#to_i16 : Int16', 'Parse as Int16'],
    ['to_i32', 'String#to_i32 : Int32', 'Parse as Int32'],
    ['to_i64', 'String#to_i64 : Int64', 'Parse as Int64'],
    ['to_i128', 'String#to_i128 : Int128', 'Parse as Int128'],
    ['to_u', 'String#to_u : UInt32', 'Parse as UInt32'],
    ['to_u8', 'String#to_u8 : UInt8', 'Parse as UInt8'],
    ['to_u16', 'String#to_u16 : UInt16', 'Parse as UInt16'],
    ['to_u32', 'String#to_u32 : UInt32', 'Parse as UInt32'],
    ['to_u64', 'String#to_u64 : UInt64', 'Parse as UInt64'],
    ['to_u128', 'String#to_u128 : UInt128', 'Parse as UInt128'],
    ['to_f', 'String#to_f : Float64', 'Parse as Float64'],
    ['to_f32', 'String#to_f32 : Float32', 'Parse as Float32'],
    ['to_f64', 'String#to_f64 : Float64', 'Parse as Float64'],
    ['to_s', 'String#to_s : String', 'Self'],
    ['to_slice', 'String#to_slice : Bytes', 'View as byte slice'],
    ['to_unsafe', 'String#to_unsafe : Pointer(UInt8)', 'Raw byte pointer'],
    ['chr', 'String#chr', 'Single-character String to Char'],
    ['inspect', 'String#inspect : String', 'Inspect representation'],
    ['dump', 'String#dump : String', 'Escaped dump'],
    ['match', 'String#match(re)', 'Regex match (MatchData?)'],
    ['scan', 'String#scan(re)', 'All regex matches'],
    ['=~', 'String#=~ other', 'Regex match index'],
    ['+', 'String#+ other', 'Concatenate'],
    ['*', 'String#* n', 'Repeat n times'],
    ['<=>', 'String#<=> other', 'Compare lexicographically'],
    ['compare', 'String#compare(other)', 'Compare with options'],
    ['starts_with?', 'String#starts_with?(s)', 'Prefix check'],
    ['ends_with?', 'String#ends_with?(s)', 'Suffix check'],
    ['includes?', 'String#includes?(s)', 'Substring check'],
    ['blank?', 'String#blank? : Bool', 'Empty / whitespace'],
    ['presence', 'String#presence : String?', 'Self if present'],
    ['concat', 'String#concat(other)', 'Concatenate'],
    ['<<', 'String#<< other', 'Append (Builder/IO)'],
    ['each', 'String#each_char(&)', 'Iterate characters'],
    ['reverse_each', 'String#reverse_each(&)', 'Iterate reversed'],
    ['format', 'String.format(fmt, *args)', 'Format string'],
    ['%', 'String#% args', 'sprintf-style formatting'],
    ['center', 'String#center(width, pad)', 'Center-justify'],
    ['ljust', 'String#ljust(width, pad)', 'Left-justify'],
    ['rjust', 'String#rjust(width, pad)', 'Right-justify'],
    ['truncate', 'String#truncate(n)', 'Truncate with ellipsis'],
    ['unicode_normalize', 'String#unicode_normalize(form)', 'Unicode normalization'],
    ['valid_encoding?', 'String#valid_encoding? : Bool', 'Valid UTF-8 check'],
    ['encode', 'String#encode(encoding)', 'Encode to bytes'],
    ['force_encoding', 'String#force_encoding(enc)', 'Reinterpret bytes'],
    ['byte_slice', 'String#byte_slice(start, count)', 'Slice by bytes'],
    ['char_at', 'String#char_at(i)', 'Character at index'],
    ['empty?', 'String#empty? : Bool', 'Length zero'],
    ['hash', 'String#hash', 'Hash value'],
    ['bytes_pointer', 'String#to_unsafe', 'Pointer to first byte'],
    ['ascii_only?', 'String#ascii_only? : Bool', 'All ASCII'],
    ['unicode_each_char', 'String#each_char_with_index', 'Iterate with index'],
    ['scrub', 'String#scrub(replacement?)', 'Replace invalid bytes'],
    ['camelcase', 'String#camelcase', 'CamelCase form'],
    ['underscore', 'String#underscore', 'snake_case form'],
    ['parameterize', 'String#parameterize', 'URL-safe form'],
  ]));

  // ── Array methods ──────────────────────────────────────────────────
  s.addBulk(methodRows('Array', [
    ['size', 'Array#size : Int32', 'Number of elements'],
    ['<<', 'Array#<< value', 'Append element'],
    ['push', 'Array#push(*values)', 'Append elements'],
    ['unshift', 'Array#unshift(*values)', 'Prepend elements'],
    ['pop', 'Array#pop : T', 'Remove last element'],
    ['shift', 'Array#shift : T', 'Remove first element'],
    ['[]', 'Array#[](i)', 'Element access'],
    ['[]?', 'Array#[]?(i)', 'Optional element access'],
    ['[]=', 'Array#[]= i, value', 'Set element at index'],
    ['first', 'Array#first', 'First element'],
    ['last', 'Array#last', 'Last element'],
    ['min', 'Array#min', 'Smallest element'],
    ['max', 'Array#max', 'Largest element'],
    ['min_by', 'Array#min_by(&)', 'Min by block result'],
    ['max_by', 'Array#max_by(&)', 'Max by block result'],
    ['sum', 'Array#sum', 'Sum of elements'],
    ['product', 'Array#product', 'Product of elements'],
    ['count', 'Array#count(&)', 'Count matches'],
    ['index', 'Array#index(value)', 'Find index of value'],
    ['find', 'Array#find(&)', 'First matching element'],
    ['find_index', 'Array#find_index(&)', 'Index of first match'],
    ['find!', 'Array#find!(&)', 'First match or raise'],
    ['find_all', 'Array#find_all(&)', 'All matches'],
    ['select', 'Array#select(&)', 'Keep matching elements'],
    ['reject', 'Array#reject(&)', 'Remove matching elements'],
    ['partition', 'Array#partition(&)', 'Split by predicate'],
    ['group_by', 'Array#group_by(&)', 'Group by block result'],
    ['chunk_while', 'Array#chunk_while(&)', 'Chunks while predicate'],
    ['slice_when', 'Array#slice_when(&)', 'Slice when predicate'],
    ['slice', 'Array#slice(start, count)', 'Subarray slice'],
    ['tally', 'Array#tally : Hash', 'Frequency counts'],
    ['each', 'Array#each(&)', 'Iterate elements'],
    ['each_with_index', 'Array#each_with_index(&)', 'Iterate with index'],
    ['each_slice', 'Array#each_slice(n, &)', 'Iterate fixed-size chunks'],
    ['each_cons', 'Array#each_cons(n, &)', 'Iterate sliding windows'],
    ['each_index', 'Array#each_index(&)', 'Iterate indices'],
    ['reverse_each', 'Array#reverse_each(&)', 'Iterate in reverse'],
    ['map', 'Array#map(&)', 'Transform each element'],
    ['map_with_index', 'Array#map_with_index(&)', 'Map with index'],
    ['flat_map', 'Array#flat_map(&)', 'Map and flatten'],
    ['compact_map', 'Array#compact_map(&)', 'Map and drop nil'],
    ['compact', 'Array#compact', 'Drop nil values'],
    ['flatten', 'Array#flatten', 'Flatten nested arrays'],
    ['concat', 'Array#concat(other)', 'Append other array'],
    ['+', 'Array#+ other', 'Concatenation'],
    ['-', 'Array#- other', 'Set difference'],
    ['*', 'Array#* n', 'Repeat n times'],
    ['&', 'Array#& other', 'Set intersection'],
    ['|', 'Array#| other', 'Set union'],
    ['==', 'Array#== other', 'Element-wise equality'],
    ['<=>', 'Array#<=> other', 'Lexicographic compare'],
    ['===', 'Array#=== other', 'Pattern match'],
    ['sort', 'Array#sort', 'Sort copy'],
    ['sort_by', 'Array#sort_by(&)', 'Sort by block result'],
    ['shuffle', 'Array#shuffle', 'Random permutation'],
    ['rotate', 'Array#rotate(n)', 'Rotate elements'],
    ['reverse', 'Array#reverse', 'Reverse copy'],
    ['uniq', 'Array#uniq', 'Unique elements'],
    ['delete', 'Array#delete(value)', 'Remove all matching values'],
    ['delete_at', 'Array#delete_at(i)', 'Remove element at index'],
    ['delete_if', 'Array#delete_if(&)', 'Remove elements where block true'],
    ['keep_if', 'Array#keep_if(&)', 'Keep elements where block true'],
    ['clear', 'Array#clear', 'Remove all elements'],
    ['to_a', 'Array#to_a : Array(T)', 'Self'],
    ['to_set', 'Array#to_set : Set(T)', 'Convert to set'],
    ['to_h', 'Array#to_h : Hash', 'Convert pairs to hash'],
    ['zip', 'Array#zip(other)', 'Pair with other'],
    ['unzip', 'Array#unzip', 'Inverse zip'],
    ['inspect', 'Array#inspect : String', 'Inspect representation'],
    ['join', 'Array#join(separator)', 'Join into string'],
    ['combinations', 'Array#combinations(n)', 'All n-combinations'],
    ['permutations', 'Array#permutations(n)', 'All n-permutations'],
    ['cartesian_product', 'Array#cartesian_product(*)', 'Cartesian product'],
    ['dup', 'Array#dup : Array(T)', 'Shallow copy'],
    ['clone', 'Array#clone : Array(T)', 'Deep copy'],
    ['empty?', 'Array#empty? : Bool', 'No elements'],
    ['any?', 'Array#any?(&)', 'Any matches'],
    ['all?', 'Array#all?(&)', 'All match'],
    ['none?', 'Array#none?(&)', 'No element matches'],
    ['one?', 'Array#one?(&)', 'Exactly one match'],
    ['fill', 'Array#fill(value)', 'Fill with value'],
    ['insert', 'Array#insert(i, value)', 'Insert at index'],
    ['truncate', 'Array#truncate(start, count)', 'Drop everything outside range'],
    ['sample', 'Array#sample(n?)', 'Random sample'],
    ['take_while', 'Array#take_while(&)', 'Prefix while predicate'],
    ['skip_while', 'Array#skip_while(&)', 'Drop prefix while predicate'],
    ['take', 'Array#take(n)', 'First n elements'],
    ['skip', 'Array#skip(n)', 'Drop first n elements'],
    ['minmax', 'Array#minmax', 'Min and max pair'],
    ['minmax_by', 'Array#minmax_by(&)', 'Min/max by block result'],
    ['rindex', 'Array#rindex(value)', 'Last matching index'],
    ['fetch', 'Array#fetch(i, default)', 'Element with default'],
    ['hash', 'Array#hash', 'Hash code'],
    ['frozen?', 'Array#frozen? : Bool', 'Always false (Array is mutable)'],
  ]));

  // ── Hash methods ───────────────────────────────────────────────────
  s.addBulk(methodRows('Hash', [
    ['size', 'Hash#size : Int32', 'Number of pairs'],
    ['[]', 'Hash#[] key', 'Lookup or raise'],
    ['[]?', 'Hash#[]? key', 'Optional lookup'],
    ['[]=', 'Hash#[]= key, value', 'Insert or update'],
    ['dig', 'Hash#dig(*keys)', 'Nested lookup or raise'],
    ['dig?', 'Hash#dig?(*keys)', 'Nested lookup or nil'],
    ['fetch', 'Hash#fetch(key, default)', 'Lookup with default'],
    ['store', 'Hash#store(key, value)', 'Alias of []='],
    ['delete', 'Hash#delete(key)', 'Remove pair'],
    ['delete_if', 'Hash#delete_if(&)', 'Remove matching pairs'],
    ['clear', 'Hash#clear', 'Remove all pairs'],
    ['each', 'Hash#each(&)', 'Yield key/value pairs'],
    ['each_pair', 'Hash#each_pair(&)', 'Yield key/value pairs'],
    ['each_key', 'Hash#each_key(&)', 'Yield keys'],
    ['each_value', 'Hash#each_value(&)', 'Yield values'],
    ['each_with_index', 'Hash#each_with_index(&)', 'Yield with index'],
    ['each_with_object', 'Hash#each_with_object(obj, &)', 'Yield with accumulator'],
    ['keys', 'Hash#keys : Array(K)', 'All keys'],
    ['values', 'Hash#values : Array(V)', 'All values'],
    ['to_a', 'Hash#to_a : Array', 'Pairs as array of tuples'],
    ['to_h', 'Hash#to_h : Hash', 'Self'],
    ['merge', 'Hash#merge(other)', 'Non-mutating merge'],
    ['merge!', 'Hash#merge!(other)', 'Mutating merge'],
    ['transform_keys', 'Hash#transform_keys(&)', 'Transform keys'],
    ['transform_values', 'Hash#transform_values(&)', 'Transform values'],
    ['select', 'Hash#select(&)', 'Keep matching pairs'],
    ['reject', 'Hash#reject(&)', 'Remove matching pairs'],
    ['map', 'Hash#map(&)', 'Map pairs'],
    ['flat_map', 'Hash#flat_map(&)', 'Map and flatten'],
    ['compact', 'Hash#compact', 'Drop nil values'],
    ['find', 'Hash#find(&)', 'First matching pair'],
    ['find_all', 'Hash#find_all(&)', 'All matching pairs'],
    ['min_by', 'Hash#min_by(&)', 'Min pair by block'],
    ['max_by', 'Hash#max_by(&)', 'Max pair by block'],
    ['count', 'Hash#count(&)', 'Number of matches'],
    ['sum', 'Hash#sum(&)', 'Sum block results'],
    ['group_by', 'Hash#group_by(&)', 'Group by block'],
    ['chunk', 'Hash#chunk(&)', 'Chunk consecutive matches'],
    ['==', 'Hash#== other', 'Equality'],
    ['inspect', 'Hash#inspect : String', 'Inspect representation'],
    ['pretty_print', 'Hash#pretty_print(pp)', 'Pretty-print into PrettyPrint'],
    ['partition', 'Hash#partition(&)', 'Split by predicate'],
    ['any?', 'Hash#any?(&)', 'Any matching pair'],
    ['all?', 'Hash#all?(&)', 'All pairs match'],
    ['empty?', 'Hash#empty? : Bool', 'No pairs'],
    ['has_key?', 'Hash#has_key?(key)', 'Key present'],
    ['has_value?', 'Hash#has_value?(value)', 'Value present'],
    ['key_for', 'Hash#key_for(value)', 'Find key for value or raise'],
    ['key_for?', 'Hash#key_for?(value)', 'Find key for value or nil'],
    ['invert', 'Hash#invert : Hash(V, K)', 'Swap keys and values'],
    ['first_key', 'Hash#first_key', 'First key'],
    ['first_value', 'Hash#first_value', 'First value'],
    ['last_key', 'Hash#last_key', 'Last key'],
    ['last_value', 'Hash#last_value', 'Last value'],
    ['shift', 'Hash#shift', 'Remove first pair'],
    ['put', 'Hash#put(key, value)', 'Alias of []='],
    ['replace', 'Hash#replace(other)', 'Replace contents'],
    ['rehash', 'Hash#rehash', 'Recompute internal table'],
    ['update', 'Hash#update(key, &)', 'Update value via block'],
    ['compare_by_identity', 'Hash#compare_by_identity', 'Use object identity for keys'],
    ['compare_by_identity?', 'Hash#compare_by_identity? : Bool', 'Identity-keyed?'],
    ['hash', 'Hash#hash', 'Hash code'],
    ['dup', 'Hash#dup', 'Shallow copy'],
    ['clone', 'Hash#clone', 'Deep copy'],
  ]));

  // ── IO / IO::Memory methods ────────────────────────────────────────
  s.addBulk(methodRows('IO', [
    ['read', 'IO#read(slice)', 'Read into slice'],
    ['write', 'IO#write(slice)', 'Write slice'],
    ['puts', 'IO#puts(*args)', 'Write with newline'],
    ['print', 'IO#print(*args)', 'Write without newline'],
    ['printf', 'IO#printf(fmt, *args)', 'Formatted write'],
    ['gets', 'IO#gets', 'Read line'],
    ['read_line', 'IO#read_line', 'Read line, raise on EOF'],
    ['read_byte', 'IO#read_byte : UInt8?', 'Read single byte'],
    ['read_string', 'IO#read_string(size)', 'Read fixed-size string'],
    ['read_bytes', 'IO#read_bytes(type)', 'Read typed bytes'],
    ['read_to_end', 'IO#read_to_end : String', 'Read remainder'],
    ['close', 'IO#close', 'Close stream'],
    ['closed?', 'IO#closed? : Bool', 'Already closed'],
    ['flush', 'IO#flush', 'Flush buffer'],
    ['sync', 'IO#sync : Bool', 'Auto-flush mode'],
    ['sync=', 'IO#sync= bool', 'Set auto-flush'],
    ['pos', 'IO#pos : Int64', 'Current offset'],
    ['pos=', 'IO#pos= n', 'Seek to offset'],
    ['seek', 'IO#seek(offset, whence?)', 'Seek by offset'],
    ['tell', 'IO#tell : Int64', 'Current position'],
    ['rewind', 'IO#rewind', 'Seek to beginning'],
    ['tty?', 'IO#tty? : Bool', 'Connected to a TTY'],
    ['<<', 'IO#<< value', 'Append'],
    ['copy_to', 'IO#copy_to(dst)', 'Copy contents to dst'],
    ['encoding', 'IO#encoding : String', 'Current encoding'],
    ['set_encoding', 'IO#set_encoding(encoding)', 'Set encoding'],
    ['fd', 'IO::FileDescriptor#fd : Int32', 'Underlying fd'],
    ['blocking', 'IO#blocking : Bool', 'Blocking mode'],
    ['blocking=', 'IO#blocking= bool', 'Set blocking mode'],
    ['read_fully', 'IO#read_fully(slice)', 'Read exactly slice.size bytes'],
    ['read_fully?', 'IO#read_fully?(slice)', 'Read fully or nil on EOF'],
    ['skip', 'IO#skip(n)', 'Discard bytes'],
    ['skip_to_end', 'IO#skip_to_end', 'Discard to EOF'],
    ['peek', 'IO#peek : Bytes?', 'Peek next bytes'],
    ['expect', 'IO#expect(string)', 'Expect prefix'],
    ['empty?', 'IO::Memory#empty? : Bool', 'Memory empty'],
    ['rewind', 'IO::Memory#rewind', 'Rewind memory io'],
    ['to_s', 'IO::Memory#to_s : String', 'Buffer as string'],
    ['to_slice', 'IO::Memory#to_slice : Bytes', 'Buffer as slice'],
    ['clear', 'IO::Memory#clear', 'Reset buffer'],
    ['size', 'IO::Memory#size : Int32', 'Buffer size'],
    ['bytesize', 'IO::Memory#bytesize : Int32', 'Byte size'],
    ['capacity', 'IO::Memory#capacity : Int32', 'Internal capacity'],
  ]));

  // ── File methods (class + instance) ────────────────────────────────
  s.addBulk([
    ['File.read', 'function', 'File.read(path) : String', 'Read entire file'],
    ['File.write', 'function', 'File.write(path, content)', 'Write entire file'],
    ['File.read_lines', 'function', 'File.read_lines(path)', 'Read file into lines'],
    ['File.each_line', 'function', 'File.each_line(path, &)', 'Iterate lines'],
    ['File.open', 'function', 'File.open(path, mode = "r")', 'Open file'],
    ['File.new', 'function', 'File.new(path, mode = "r")', 'Open file as new instance'],
    ['File.close', 'function', 'File#close', 'Close file'],
    ['File.exists?', 'function', 'File.exists?(path)', 'Path exists'],
    ['File.file?', 'function', 'File.file?(path)', 'Path is a regular file'],
    ['File.directory?', 'function', 'File.directory?(path)', 'Path is a directory'],
    ['File.size', 'function', 'File.size(path)', 'File size in bytes'],
    ['File.info', 'function', 'File.info(path)', 'File metadata'],
    ['File.stat', 'function', 'File.info(path)', 'Alias for info'],
    ['File.dirname', 'function', 'File.dirname(path)', 'Directory portion'],
    ['File.basename', 'function', 'File.basename(path, suffix?)', 'Last path component'],
    ['File.extname', 'function', 'File.extname(path)', 'Extension'],
    ['File.expand_path', 'function', 'File.expand_path(path)', 'Absolute path'],
    ['File.join', 'function', 'File.join(*parts)', 'Join path parts'],
    ['File.delete', 'function', 'File.delete(path)', 'Remove file'],
    ['File.rename', 'function', 'File.rename(src, dst)', 'Move file'],
    ['File.chmod', 'function', 'File.chmod(path, mode)', 'Change mode'],
    ['File.chown', 'function', 'File.chown(path, uid, gid)', 'Change owner'],
    ['File.realpath', 'function', 'File.realpath(path)', 'Resolve symlinks'],
    ['File.touch', 'function', 'File.touch(path)', 'Update timestamps'],
    ['File.symlink', 'function', 'File.symlink(src, dst)', 'Create symlink'],
    ['File.symlink?', 'function', 'File.symlink?(path)', 'Path is symlink'],
    ['File.readable?', 'function', 'File.readable?(path)', 'Path is readable'],
    ['File.writable?', 'function', 'File.writable?(path)', 'Path is writable'],
    ['File.executable?', 'function', 'File.executable?(path)', 'Path is executable'],
    ['File.empty?', 'function', 'File.empty?(path)', 'File is empty'],
    ['File.same?', 'function', 'File.same?(p1, p2)', 'Paths point to same file'],
    ['File.match?', 'function', 'File.match?(pattern, path)', 'Glob match'],
    ['File.tempfile', 'function', 'File.tempfile(prefix?)', 'Create temporary file'],
    ['File.tempname', 'function', 'File.tempname(prefix?)', 'Generate tempfile path'],
    ['File.copy', 'function', 'File.copy(src, dst)', 'Copy file'],
    ['File.SEPARATOR', 'constant', 'Char', 'Path separator'],
    ['File.PATH_SEPARATOR', 'constant', 'Char', 'PATH variable separator'],
    ['File.NULL', 'constant', 'String', 'Null device path'],
  ]);

  // ── Dir methods ────────────────────────────────────────────────────
  s.addBulk([
    ['Dir.current', 'function', 'Dir.current : String', 'Current working directory'],
    ['Dir.cd', 'function', 'Dir.cd(path)', 'Change directory'],
    ['Dir.exists?', 'function', 'Dir.exists?(path)', 'Directory exists'],
    ['Dir.empty?', 'function', 'Dir.empty?(path)', 'Directory empty'],
    ['Dir.mkdir', 'function', 'Dir.mkdir(path)', 'Make directory'],
    ['Dir.mkdir_p', 'function', 'Dir.mkdir_p(path)', 'Make directory + parents'],
    ['Dir.delete', 'function', 'Dir.delete(path)', 'Remove empty directory'],
    ['Dir.entries', 'function', 'Dir.entries(path)', 'List entries'],
    ['Dir.children', 'function', 'Dir.children(path)', 'Entries except . and ..'],
    ['Dir.each', 'function', 'Dir.each(path, &)', 'Yield each entry'],
    ['Dir.each_child', 'function', 'Dir.each_child(path, &)', 'Yield each child'],
    ['Dir.glob', 'function', 'Dir.glob(*patterns)', 'Glob matching paths'],
    ['Dir.tempdir', 'function', 'Dir.tempdir : String', 'System temp directory'],
    ['Dir.home', 'function', 'Dir.home : String', 'Home directory'],
    ['Dir.open', 'function', 'Dir.open(path)', 'Open directory'],
    ['Dir.[]', 'function', 'Dir[*patterns]', 'Glob shortcut'],
    ['Dir.[]?', 'function', 'Dir[*patterns]?', 'Glob shortcut (nil-safe)'],
    ['Dir.close', 'function', 'Dir#close', 'Close directory iterator'],
    ['Dir.path', 'function', 'Dir#path : String', 'Directory path'],
    ['Dir.rewind', 'function', 'Dir#rewind', 'Rewind iterator'],
  ]);

  // ── Time methods ───────────────────────────────────────────────────
  s.addBulk([
    ['Time.now', 'function', 'Time.now : Time', 'Current time (alias of local)'],
    ['Time.local', 'function', 'Time.local : Time', 'Current local time'],
    ['Time.utc', 'function', 'Time.utc : Time', 'Current UTC time'],
    ['Time.unix', 'function', 'Time.unix(seconds)', 'Unix timestamp'],
    ['Time.unix_ms', 'function', 'Time.unix_ms(milliseconds)', 'Unix ms timestamp'],
    ['Time.unix_ns', 'function', 'Time.unix_ns(nanoseconds)', 'Unix ns timestamp'],
    ['Time.epoch', 'function', 'Time.epoch(seconds)', 'Alias for unix'],
    ['Time.epoch_ms', 'function', 'Time.epoch_ms(ms)', 'Alias for unix_ms'],
    ['Time.epoch_f', 'function', 'Time.epoch_f(seconds)', 'Float epoch seconds'],
    ['Time.parse', 'function', 'Time.parse(str, fmt, location?)', 'Parse formatted string'],
    ['Time.parse!', 'function', 'Time.parse!(str, fmt)', 'Parse strict'],
    ['Time.parse_iso8601', 'function', 'Time.parse_iso8601(str)', 'Parse ISO-8601'],
    ['Time.parse_rfc2822', 'function', 'Time.parse_rfc2822(str)', 'Parse RFC-2822'],
    ['Time.parse_rfc3339', 'function', 'Time.parse_rfc3339(str)', 'Parse RFC-3339'],
    ['Time.format', 'method', 'Time#format(fmt) : String', 'Format Time as string'],
    ['Time.to_s', 'method', 'Time#to_s(fmt?) : String', 'Format default'],
    ['Time.to_local', 'method', 'Time#to_local : Time', 'Convert to local'],
    ['Time.to_utc', 'method', 'Time#to_utc : Time', 'Convert to UTC'],
    ['Time.to_unix', 'method', 'Time#to_unix : Int64', 'Unix seconds'],
    ['Time.to_unix_ms', 'method', 'Time#to_unix_ms : Int64', 'Unix ms'],
    ['Time.to_unix_ns', 'method', 'Time#to_unix_ns : Int64', 'Unix ns'],
    ['Time.to_unix_f', 'method', 'Time#to_unix_f : Float64', 'Unix seconds float'],
    ['Time.+', 'method', 'Time#+ span', 'Add Time::Span'],
    ['Time.-', 'method', 'Time#- other', 'Span between two Times'],
    ['Time.<=>', 'method', 'Time#<=> other', 'Compare'],
    ['Time.==', 'method', 'Time#== other', 'Equality'],
    ['Time.year', 'method', 'Time#year : Int32', 'Calendar year'],
    ['Time.month', 'method', 'Time#month : Int32', 'Month 1-12'],
    ['Time.day', 'method', 'Time#day : Int32', 'Day of month'],
    ['Time.hour', 'method', 'Time#hour : Int32', 'Hour 0-23'],
    ['Time.minute', 'method', 'Time#minute : Int32', 'Minute 0-59'],
    ['Time.second', 'method', 'Time#second : Int32', 'Second 0-59'],
    ['Time.millisecond', 'method', 'Time#millisecond : Int32', 'Millisecond 0-999'],
    ['Time.microsecond', 'method', 'Time#microsecond : Int32', 'Microsecond 0-999_999'],
    ['Time.nanosecond', 'method', 'Time#nanosecond : Int32', 'Nanosecond 0-999_999_999'],
    ['Time.day_of_week', 'method', 'Time#day_of_week : Time::DayOfWeek', 'Weekday enum'],
    ['Time.day_of_year', 'method', 'Time#day_of_year : Int32', 'Day of year 1-366'],
    ['Time.monotonic', 'function', 'Time.monotonic : Time::Span', 'Monotonic clock value'],
    ['Time.measure', 'function', 'Time.measure { ... }', 'Measure block duration'],
    ['Time.days_in_month', 'function', 'Time.days_in_month(year, month)', 'Days in month'],
    ['Time.days_in_year', 'function', 'Time.days_in_year(year)', 'Days in year'],
    ['Time.leap_year?', 'function', 'Time.leap_year?(year)', 'Check leap year'],
    ['Time::Span', 'type', null, 'Time interval / duration'],
    ['Time::Location', 'type', null, 'Timezone location'],
    ['Time::Format', 'type', null, 'Custom format pattern'],
    ['Time::DayOfWeek', 'type', null, 'Day-of-week enum'],
    ['Time::Month', 'type', null, 'Month enum'],
    ['Time::UNIX_EPOCH', 'constant', 'Time', 'Unix epoch constant'],
  ]);

  // ── Number / Int / Float methods ───────────────────────────────────
  s.addBulk(methodRows('Number', [
    ['abs', 'Number#abs', 'Absolute value'],
    ['abs2', 'Number#abs2', 'Absolute value squared'],
    ['sign', 'Number#sign : Int32', 'Sign (-1, 0, +1)'],
    ['zero?', 'Number#zero? : Bool', 'Equal to zero'],
    ['positive?', 'Number#positive? : Bool', 'Greater than zero'],
    ['negative?', 'Number#negative? : Bool', 'Less than zero'],
    ['floor', 'Number#floor', 'Floor'],
    ['ceil', 'Number#ceil', 'Ceiling'],
    ['round', 'Number#round(digits?)', 'Round to digits'],
    ['trunc', 'Number#trunc', 'Truncate to integer'],
    ['to_i', 'Number#to_i : Int32', 'Convert to Int32'],
    ['to_i64', 'Number#to_i64 : Int64', 'Convert to Int64'],
    ['to_f', 'Number#to_f : Float64', 'Convert to Float64'],
    ['to_f32', 'Number#to_f32 : Float32', 'Convert to Float32'],
    ['to_s', 'Number#to_s(base?) : String', 'String representation'],
    ['clamp', 'Number#clamp(min, max)', 'Clamp to range'],
    ['humanize', 'Number#humanize(precision?)', 'Human-friendly form'],
    ['format', 'Number#format', 'Format with separators'],
    ['divmod', 'Number#divmod(other)', 'Quotient and modulus'],
    ['fdiv', 'Number#fdiv(other) : Float64', 'Float division'],
    ['gcd', 'Int#gcd(other)', 'Greatest common divisor'],
    ['lcm', 'Int#lcm(other)', 'Least common multiple'],
    ['bit', 'Int#bit(i) : Int32', 'Bit at position i'],
    ['bits_set?', 'Int#bits_set?(mask)', 'All bits set in mask'],
    ['popcount', 'Int#popcount', 'Number of set bits'],
    ['leading_zeros_count', 'Int#leading_zeros_count', 'Count leading zeros'],
    ['trailing_zeros_count', 'Int#trailing_zeros_count', 'Count trailing zeros'],
    ['rotate_left', 'Int#rotate_left(n)', 'Rotate bits left'],
    ['rotate_right', 'Int#rotate_right(n)', 'Rotate bits right'],
    ['times', 'Int#times(&)', 'Iterate n times'],
    ['upto', 'Int#upto(n, &)', 'Yield from self to n'],
    ['downto', 'Int#downto(n, &)', 'Yield down from self to n'],
    ['step', 'Number#step(to:, by:, &)', 'Step iteration'],
    ['nan?', 'Float#nan? : Bool', 'NaN test'],
    ['infinite?', 'Float#infinite?', 'Infinity test'],
    ['finite?', 'Float#finite? : Bool', 'Finite test'],
    ['fdiv', 'Float#fdiv(other) : Float64', 'Float division'],
    ['modulo', 'Float#modulo(other) : Float64', 'Modulus'],
    ['remainder', 'Number#remainder(other)', 'Remainder'],
    ['negate', 'Number#- @ ', 'Unary negation'],
    ['hash', 'Number#hash', 'Hash code'],
    ['inspect', 'Number#inspect : String', 'Inspect'],
    ['integer?', 'Number#integer? : Bool', 'Whole-number'],
    ['real?', 'Number#real? : Bool', 'Real number'],
    ['/', 'Number#/ other', 'Division'],
    ['+', 'Number#+ other', 'Addition'],
    ['-', 'Number#- other', 'Subtraction'],
    ['*', 'Number#* other', 'Multiplication'],
    ['**', 'Number#** other', 'Exponentiation'],
    ['%', 'Number#% other', 'Modulo'],
    ['<', 'Number#< other', 'Less-than'],
    ['<=', 'Number#<= other', 'Less-or-equal'],
    ['>', 'Number#> other', 'Greater-than'],
    ['>=', 'Number#>= other', 'Greater-or-equal'],
    ['==', 'Number#== other', 'Equality'],
    ['<=>', 'Number#<=> other', 'Compare'],
  ]));

  // ── Symbol / Char / Bool / Nil ─────────────────────────────────────
  s.addBulk([
    ['Symbol#to_s', 'method', 'Symbol#to_s : String', 'Symbol as String'],
    ['Symbol#to_proc', 'method', 'Symbol#to_proc', 'Convert to Proc'],
    ['Symbol#hash', 'method', 'Symbol#hash : Int32', 'Hash code'],
    ['Symbol#==', 'method', 'Symbol#== other', 'Equality'],
    ['Symbol#<=>', 'method', 'Symbol#<=> other', 'Compare'],
    ['Symbol#inspect', 'method', 'Symbol#inspect : String', 'Inspect representation'],
    ['Char#to_i', 'method', 'Char#to_i : Int32', 'Numeric value'],
    ['Char#to_s', 'method', 'Char#to_s : String', 'Single-character String'],
    ['Char#bytes', 'method', 'Char#bytes : Array(UInt8)', 'UTF-8 encoded bytes'],
    ['Char#bytesize', 'method', 'Char#bytesize : Int32', 'UTF-8 byte length'],
    ['Char#ord', 'method', 'Char#ord : Int32', 'Codepoint value'],
    ['Char#chr', 'method', 'Char#chr', 'Self'],
    ['Char#downcase', 'method', 'Char#downcase', 'Lowercase'],
    ['Char#upcase', 'method', 'Char#upcase', 'Uppercase'],
    ['Char#letter?', 'method', 'Char#letter? : Bool', 'Unicode letter'],
    ['Char#number?', 'method', 'Char#number? : Bool', 'Unicode number'],
    ['Char#digit?', 'method', 'Char#digit? : Bool', 'ASCII digit'],
    ['Char#alphanumeric?', 'method', 'Char#alphanumeric? : Bool', 'Letter or digit'],
    ['Char#whitespace?', 'method', 'Char#whitespace? : Bool', 'Whitespace'],
    ['Char#hex?', 'method', 'Char#hex? : Bool', 'Hex digit'],
    ['Char#ascii?', 'method', 'Char#ascii? : Bool', 'ASCII codepoint'],
    ['Char#ascii_lowercase?', 'method', 'Char#ascii_lowercase? : Bool', 'ASCII lowercase'],
    ['Char#ascii_uppercase?', 'method', 'Char#ascii_uppercase? : Bool', 'ASCII uppercase'],
    ['Char#==', 'method', 'Char#== other', 'Equality'],
    ['Char#<=>', 'method', 'Char#<=> other', 'Compare'],
    ['Char#succ', 'method', 'Char#succ', 'Next codepoint'],
    ['Char#pred', 'method', 'Char#pred', 'Previous codepoint'],
    ['Char#in_set?', 'method', 'Char#in_set?(set)', 'Membership test'],
    ['Bool#&', 'method', 'Bool#& other', 'And'],
    ['Bool#|', 'method', 'Bool#| other', 'Or'],
    ['Bool#^', 'method', 'Bool#^ other', 'Xor'],
    ['Bool#!', 'method', 'Bool#!', 'Negation'],
    ['Bool#hash', 'method', 'Bool#hash : Int32', 'Hash code'],
    ['Bool#to_s', 'method', 'Bool#to_s : String', "'true' or 'false'"],
    ['Bool#inspect', 'method', 'Bool#inspect : String', "'true' or 'false'"],
    ['Nil#to_s', 'method', 'Nil#to_s : String', 'Empty string'],
    ['Nil#inspect', 'method', 'Nil#inspect : String', "'nil'"],
    ['Nil#hash', 'method', 'Nil#hash : Int32', 'Zero hash'],
    ['Nil#nil?', 'method', 'Nil#nil? : Bool', 'Always true'],
    ['Nil#!', 'method', 'Nil#!', 'Always true'],
    ['Nil#try', 'method', 'Nil#try', 'Always nil'],
    ['Nil#not_nil!', 'method', 'Nil#not_nil!', 'Raise NilAssertionError'],
  ]);

  // ── Regex / Set / Deque / NamedTuple / Tuple / Enum ────────────────
  s.addBulk([
    ['Regex.new', 'function', 'Regex.new(source, options?)', 'Compile regex'],
    ['Regex.escape', 'function', 'Regex.escape(str)', 'Escape literal text'],
    ['Regex.union', 'function', 'Regex.union(*patterns)', 'Union of patterns'],
    ['Regex#match', 'method', 'Regex#match(str)', 'Match against string'],
    ['Regex#matches?', 'method', 'Regex#matches?(str)', 'Boolean match'],
    ['Regex#source', 'method', 'Regex#source : String', 'Original pattern source'],
    ['Regex#options', 'method', 'Regex#options : Options', 'Regex options'],
    ['Regex#==', 'method', 'Regex#== other', 'Equality'],
    ['Regex#name_table', 'method', 'Regex#name_table', 'Named-capture table'],
    ['Regex::Options', 'type', null, 'Compile-time options enum'],
    ['Regex::MatchData', 'type', null, 'Match result'],
    ['Set.new', 'function', 'Set(T).new(elements?)', 'Create a Set'],
    ['Set#add', 'method', 'Set#add(value)', 'Insert value'],
    ['Set#delete', 'method', 'Set#delete(value)', 'Remove value'],
    ['Set#includes?', 'method', 'Set#includes?(value)', 'Membership test'],
    ['Set#each', 'method', 'Set#each(&)', 'Iterate'],
    ['Set#size', 'method', 'Set#size : Int32', 'Number of elements'],
    ['Set#to_a', 'method', 'Set#to_a', 'Array of elements'],
    ['Set#&', 'method', 'Set#& other', 'Intersection'],
    ['Set#|', 'method', 'Set#| other', 'Union'],
    ['Set#-', 'method', 'Set#- other', 'Difference'],
    ['Set#^', 'method', 'Set#^ other', 'Symmetric difference'],
    ['Set#subset?', 'method', 'Set#subset?(other)', 'Subset of'],
    ['Set#superset?', 'method', 'Set#superset?(other)', 'Superset of'],
    ['Set#empty?', 'method', 'Set#empty? : Bool', 'No elements'],
    ['Set#clear', 'method', 'Set#clear', 'Remove all'],
    ['Deque.new', 'function', 'Deque(T).new', 'Create deque'],
    ['Deque#push', 'method', 'Deque#push(v)', 'Append element'],
    ['Deque#unshift', 'method', 'Deque#unshift(v)', 'Prepend element'],
    ['Deque#pop', 'method', 'Deque#pop', 'Remove last'],
    ['Deque#shift', 'method', 'Deque#shift', 'Remove first'],
    ['Deque#size', 'method', 'Deque#size : Int32', 'Element count'],
    ['Deque#each', 'method', 'Deque#each(&)', 'Iterate'],
    ['Deque#first', 'method', 'Deque#first', 'First element'],
    ['Deque#last', 'method', 'Deque#last', 'Last element'],
    ['Deque#empty?', 'method', 'Deque#empty? : Bool', 'No elements'],
    ['Deque#rotate!', 'method', 'Deque#rotate!(n)', 'Rotate in place'],
    ['Deque#clear', 'method', 'Deque#clear', 'Remove all'],
    ['NamedTuple#[]', 'method', 'NamedTuple#[](key)', 'Field lookup'],
    ['NamedTuple#[]?', 'method', 'NamedTuple#[]?(key)', 'Optional lookup'],
    ['NamedTuple#size', 'method', 'NamedTuple#size : Int32', 'Field count'],
    ['NamedTuple#keys', 'method', 'NamedTuple#keys', 'All keys'],
    ['NamedTuple#values', 'method', 'NamedTuple#values', 'All values'],
    ['NamedTuple#each', 'method', 'NamedTuple#each(&)', 'Iterate pairs'],
    ['NamedTuple#each_pair', 'method', 'NamedTuple#each_pair(&)', 'Iterate pairs'],
    ['NamedTuple#each_key', 'method', 'NamedTuple#each_key(&)', 'Iterate keys'],
    ['NamedTuple#each_value', 'method', 'NamedTuple#each_value(&)', 'Iterate values'],
    ['NamedTuple#to_h', 'method', 'NamedTuple#to_h : Hash', 'Convert to Hash'],
    ['NamedTuple#merge', 'method', 'NamedTuple#merge(other)', 'Merge with other'],
    ['NamedTuple#dig', 'method', 'NamedTuple#dig(*keys)', 'Nested lookup'],
    ['NamedTuple#dig?', 'method', 'NamedTuple#dig?(*keys)', 'Nested optional lookup'],
    ['NamedTuple#empty?', 'method', 'NamedTuple#empty? : Bool', 'No fields'],
    ['Tuple.new', 'function', 'Tuple.new(*values)', 'Create tuple'],
    ['Tuple#[]', 'method', 'Tuple#[](i)', 'Element by index'],
    ['Tuple#[]?', 'method', 'Tuple#[]?(i)', 'Optional element'],
    ['Tuple#size', 'method', 'Tuple#size : Int32', 'Element count'],
    ['Tuple#each', 'method', 'Tuple#each(&)', 'Iterate'],
    ['Tuple#first', 'method', 'Tuple#first', 'First element'],
    ['Tuple#last', 'method', 'Tuple#last', 'Last element'],
    ['Tuple#map', 'method', 'Tuple#map(&)', 'Transform tuple elements'],
    ['Tuple#to_a', 'method', 'Tuple#to_a', 'Convert to array'],
    ['Tuple#==', 'method', 'Tuple#== other', 'Equality'],
    ['Tuple#<=>', 'method', 'Tuple#<=> other', 'Lexicographic compare'],
    ['Enum.parse', 'function', 'Enum.parse(name)', 'Lookup variant by name'],
    ['Enum.parse?', 'function', 'Enum.parse?(name)', 'Lookup variant or nil'],
    ['Enum#value', 'method', 'Enum#value : Int', 'Underlying value'],
    ['Enum#to_s', 'method', 'Enum#to_s : String', 'String representation'],
    ['Enum#includes?', 'method', 'Enum#includes?(other)', 'Bitflag membership'],
    ['Enum#each', 'method', 'Enum.each(&)', 'Iterate variants'],
    ['Enum#hash', 'method', 'Enum#hash : Int32', 'Hash code'],
    ['Enum#==', 'method', 'Enum#== other', 'Equality'],
    ['Enum#values', 'function', 'Enum.values', 'Array of variants'],
    ['Enum#names', 'function', 'Enum.names', 'Array of variant names'],
    ['Reference#object_id', 'method', 'Reference#object_id : UInt64', 'Stable object id'],
    ['Reference#same?', 'method', 'Reference#same?(other)', 'Identity test'],
    ['Reference#hash', 'method', 'Reference#hash : Int32', 'Hash code'],
    ['Reference#dup', 'method', 'Reference#dup', 'Shallow copy'],
    ['Reference#clone', 'method', 'Reference#clone', 'Deep copy'],
    ['Reference#inspect', 'method', 'Reference#inspect : String', 'Inspect'],
    ['Reference#to_s', 'method', 'Reference#to_s : String', 'String form'],
    ['Object#==', 'method', 'Object#== other', 'Default equality'],
    ['Object#!', 'method', 'Object#!', 'Negation'],
    ['Object#tap', 'method', 'Object#tap { |v| ... }', 'Yield self, return self'],
    ['Object#try', 'method', 'Object#try { |v| ... }', 'Yield self, return result'],
    ['Object#itself', 'method', 'Object#itself', 'Return self'],
    ['Object#not_nil!', 'method', 'Object#not_nil!', 'Assert non-nil'],
    ['Object#in?', 'method', 'Object#in?(*values)', 'Membership test'],
    ['Object#unsafe_as', 'method', 'Object#unsafe_as(T)', 'Bit-cast'],
    ['Pointer.malloc', 'function', 'Pointer(T).malloc(n)', 'Allocate buffer'],
    ['Pointer.null', 'function', 'Pointer(T).null', 'Null pointer'],
    ['Pointer#value', 'method', 'Pointer#value : T', 'Dereference'],
    ['Pointer#value=', 'method', 'Pointer#value= v', 'Assign through pointer'],
    ['Pointer#+', 'method', 'Pointer#+ offset', 'Pointer arithmetic'],
    ['Pointer#-', 'method', 'Pointer#- offset', 'Pointer arithmetic'],
    ['Pointer#address', 'method', 'Pointer#address : UInt64', 'Numeric address'],
    ['Pointer#null?', 'method', 'Pointer#null? : Bool', 'Pointer is null'],
    ['Pointer#realloc', 'method', 'Pointer#realloc(n)', 'Resize buffer'],
    ['Pointer#copy_from', 'method', 'Pointer#copy_from(src, count)', 'Copy from source'],
    ['Pointer#copy_to', 'method', 'Pointer#copy_to(dst, count)', 'Copy to destination'],
    ['Pointer#move_from', 'method', 'Pointer#move_from(src, count)', 'memmove from src'],
    ['Pointer#move_to', 'method', 'Pointer#move_to(dst, count)', 'memmove to dst'],
    ['Pointer#clear', 'method', 'Pointer#clear(count)', 'Zero memory'],
    ['Pointer#as_slice', 'method', 'Pointer#to_slice(size)', 'View as Slice'],
    ['Slice.new', 'function', 'Slice(T).new(size)', 'Create slice'],
    ['Slice.empty', 'function', 'Slice(T).empty', 'Empty slice'],
    ['Slice#[]', 'method', 'Slice#[](i)', 'Element access'],
    ['Slice#[]=', 'method', 'Slice#[]= i, v', 'Element assignment'],
    ['Slice#size', 'method', 'Slice#size : Int32', 'Element count'],
    ['Slice#each', 'method', 'Slice#each(&)', 'Iterate'],
    ['Slice#to_a', 'method', 'Slice#to_a', 'Convert to Array'],
    ['Slice#hexstring', 'method', 'Slice#hexstring : String', 'Hex representation'],
    ['Slice#hexdump', 'method', 'Slice#hexdump : String', 'Hex dump'],
    ['Slice#copy_from', 'method', 'Slice#copy_from(src)', 'Copy from source'],
    ['Slice#copy_to', 'method', 'Slice#copy_to(dst)', 'Copy to destination'],
  ]);

  // ── Math / Random / Digest ────────────────────────────────────────
  s.addBulk([
    ['Math.sqrt', 'function', 'Math.sqrt(x)', 'Square root'],
    ['Math.cbrt', 'function', 'Math.cbrt(x)', 'Cube root'],
    ['Math.sin', 'function', 'Math.sin(x)', 'Sine (radians)'],
    ['Math.cos', 'function', 'Math.cos(x)', 'Cosine (radians)'],
    ['Math.tan', 'function', 'Math.tan(x)', 'Tangent (radians)'],
    ['Math.asin', 'function', 'Math.asin(x)', 'Arcsine'],
    ['Math.acos', 'function', 'Math.acos(x)', 'Arccosine'],
    ['Math.atan', 'function', 'Math.atan(x)', 'Arctangent'],
    ['Math.atan2', 'function', 'Math.atan2(y, x)', 'Two-argument arctangent'],
    ['Math.exp', 'function', 'Math.exp(x)', 'Exponential'],
    ['Math.exp2', 'function', 'Math.exp2(x)', '2^x'],
    ['Math.expm1', 'function', 'Math.expm1(x)', 'exp(x)-1'],
    ['Math.log', 'function', 'Math.log(x, base?)', 'Natural / arbitrary log'],
    ['Math.log10', 'function', 'Math.log10(x)', 'Base-10 log'],
    ['Math.log2', 'function', 'Math.log2(x)', 'Base-2 log'],
    ['Math.log1p', 'function', 'Math.log1p(x)', 'log(1+x)'],
    ['Math.sinh', 'function', 'Math.sinh(x)', 'Hyperbolic sine'],
    ['Math.cosh', 'function', 'Math.cosh(x)', 'Hyperbolic cosine'],
    ['Math.tanh', 'function', 'Math.tanh(x)', 'Hyperbolic tangent'],
    ['Math.asinh', 'function', 'Math.asinh(x)', 'Inverse hyperbolic sine'],
    ['Math.acosh', 'function', 'Math.acosh(x)', 'Inverse hyperbolic cosine'],
    ['Math.atanh', 'function', 'Math.atanh(x)', 'Inverse hyperbolic tangent'],
    ['Math.hypot', 'function', 'Math.hypot(x, y)', 'sqrt(x^2 + y^2)'],
    ['Math.pow', 'function', 'Math.pow(base, exp)', 'Exponentiation'],
    ['Math.gamma', 'function', 'Math.gamma(x)', 'Gamma function'],
    ['Math.lgamma', 'function', 'Math.lgamma(x)', 'log gamma function'],
    ['Math.erf', 'function', 'Math.erf(x)', 'Error function'],
    ['Math.erfc', 'function', 'Math.erfc(x)', 'Complementary error function'],
    ['Math.copysign', 'function', 'Math.copysign(x, y)', 'Copy sign of y onto x'],
    ['Math.frexp', 'function', 'Math.frexp(x)', 'Fraction-exponent split'],
    ['Math.ldexp', 'function', 'Math.ldexp(x, e)', 'x * 2**e'],
    ['Math::E', 'constant', 'Float64', "Euler's number"],
    ['Math::PI', 'constant', 'Float64', 'Pi constant'],
    ['Math::TAU', 'constant', 'Float64', 'Tau (2 * Pi)'],
    ['Math::LOG2', 'constant', 'Float64', 'log(2)'],
    ['Math::LOG10', 'constant', 'Float64', 'log(10)'],
    ['Math::INFINITY', 'constant', 'Float64', 'Positive infinity'],
    ['Random.new', 'function', 'Random.new(seed?)', 'New PCG generator'],
    ['Random.rand', 'function', 'Random.rand(range?)', 'Random number'],
    ['Random.new_seed', 'function', 'Random.new_seed', 'Generate seed'],
    ['Random::DEFAULT', 'constant', 'Random', 'Default RNG'],
    ['Random::PCG32', 'class', null, 'PCG32 generator'],
    ['Random::ISAAC', 'class', null, 'ISAAC generator'],
    ['Random::Secure', 'namespace', null, 'Cryptographically-secure RNG'],
    ['Random::Secure.rand', 'function', 'Random::Secure.rand', 'Secure random number'],
    ['Random::Secure.random_bytes', 'function', 'Random::Secure.random_bytes(n)', 'Secure random bytes'],
    ['Random::Secure.hex', 'function', 'Random::Secure.hex(n)', 'Secure random hex string'],
    ['Random::Secure.base64', 'function', 'Random::Secure.base64(n)', 'Secure base64 string'],
    ['Random::Secure.urlsafe_base64', 'function', 'Random::Secure.urlsafe_base64(n)', 'URL-safe base64 string'],
    ['Random::Secure.uuid', 'function', 'Random::Secure.uuid', 'Random UUID'],
    ['Digest::MD5', 'class', null, 'MD5 digest'],
    ['Digest::SHA1', 'class', null, 'SHA-1 digest'],
    ['Digest::SHA256', 'class', null, 'SHA-256 digest'],
    ['Digest::SHA512', 'class', null, 'SHA-512 digest'],
    ['Digest::SHA384', 'class', null, 'SHA-384 digest'],
    ['Digest::SHA224', 'class', null, 'SHA-224 digest'],
    ['Digest::Adler32', 'class', null, 'Adler-32 checksum'],
    ['Digest::CRC32', 'class', null, 'CRC-32 checksum'],
    ['Digest::Base', 'class', null, 'Abstract digest base'],
    ['Digest::Algorithm', 'class', null, 'Algorithm enum'],
    ['Digest.hexdigest', 'function', 'Digest.hexdigest(algorithm, data)', 'One-shot hex digest'],
    ['Digest.digest', 'function', 'Digest.digest(algorithm, data)', 'One-shot raw digest'],
    ['Digest::MD5.hexdigest', 'function', 'Digest::MD5.hexdigest(data)', 'MD5 hex'],
    ['Digest::SHA1.hexdigest', 'function', 'Digest::SHA1.hexdigest(data)', 'SHA1 hex'],
    ['Digest::SHA256.hexdigest', 'function', 'Digest::SHA256.hexdigest(data)', 'SHA256 hex'],
    ['Digest::SHA512.hexdigest', 'function', 'Digest::SHA512.hexdigest(data)', 'SHA512 hex'],
  ]);

  return s.toArray();
}
