// Shared helpers for the niche-language completion generators.
// Each generator builds a Map<label, entry> to enforce uniqueness, then
// emits a sorted `export default [...]` JS file matching the schema:
//   { label, type, detail?, info?, boost? }

import fs from 'node:fs';
import path from 'node:path';

export class EntrySet {
  constructor(language) {
    this.language = language;
    this.map = new Map();
  }
  add(entry) {
    if (!entry || !entry.label) return;
    if (this.map.has(entry.label)) return; // first writer wins
    this.map.set(entry.label, entry);
  }
  addMany(entries) {
    for (const e of entries) this.add(e);
  }
  // Convenience: bulk add identifiers from an array of [label, type, detail?, info?]
  addBulk(rows, defaults = {}) {
    for (const r of rows) {
      if (!r) continue;
      const [label, type, detail, info] = Array.isArray(r) ? r : [r.label, r.type, r.detail, r.info];
      const entry = { label, type: type || defaults.type || 'variable' };
      if (detail) entry.detail = detail;
      if (info) entry.info = info;
      if (defaults.boost != null) entry.boost = defaults.boost;
      this.add(entry);
    }
  }
  size() { return this.map.size; }
  // Backfill detail field for any entries that lack one, using a
  // language-supplied synthesizer. Ensures the schema requirement of
  // ≥ 70% entries having `detail`.
  backfillDetails(synth) {
    for (const e of this.map.values()) {
      if (e.detail) continue;
      const d = synth(e);
      if (d) e.detail = d;
    }
  }
  toArray() {
    return [...this.map.values()].sort((a, b) =>
      a.label.localeCompare(b.label, 'en', { sensitivity: 'variant' })
    );
  }
}

export function emit(filePath, language, entries) {
  const lines = [];
  lines.push(`// Completion entries for ${language}.`);
  lines.push(`// Generated by scripts/completions-gen — DO NOT hand-edit.`);
  lines.push(`// Re-run \`node scripts/completions-gen/build.mjs\` after changes.`);
  lines.push(`//`);
  lines.push(`// Entry shape: { label, type, detail?, info?, boost? }`);
  lines.push(`//   - type: keyword | function | class | variable | constant | type`);
  lines.push(`//          | method | property | namespace | interface | enum | snippet`);
  lines.push(`//   - detail: short signature string (autocomplete sidebar)`);
  lines.push(`//   - info: longer docstring (autocomplete tooltip)`);
  lines.push(``);
  lines.push(`export default [`);
  for (const e of entries) {
    lines.push('  ' + serialise(e) + ',');
  }
  lines.push(`];`);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, lines.join('\n') + '\n', 'utf8');
}

function serialise(e) {
  const parts = [`label: ${quote(e.label)}`, `type: ${quote(e.type)}`];
  if (e.detail != null) parts.push(`detail: ${quote(e.detail)}`);
  if (e.info != null) parts.push(`info: ${quote(e.info)}`);
  if (e.boost != null) parts.push(`boost: ${e.boost}`);
  return `{ ${parts.join(', ')} }`;
}

function quote(s) {
  if (typeof s !== 'string') return JSON.stringify(s);
  // Use single-quoted JS string literal; escape backslash + quote.
  return "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n') + "'";
}

// Small helper: turn a list of bare names into entries with a uniform type.
// Optional detail/info functions apply per name.
export function bulk(names, type, detailFn, infoFn) {
  return names.map((n) => {
    const e = { label: n, type };
    if (detailFn) {
      const d = detailFn(n);
      if (d) e.detail = d;
    }
    if (infoFn) {
      const i = infoFn(n);
      if (i) e.info = i;
    }
    return e;
  });
}

// Cartesian helper: combine namespace prefixes with member lists.
export function members(prefix, items, type, detailFn, infoFn) {
  return items.map(([name, sig, doc]) => {
    const label = prefix ? `${prefix}.${name}` : name;
    const e = { label, type };
    if (sig) e.detail = sig;
    else if (detailFn) {
      const d = detailFn(name);
      if (d) e.detail = d;
    }
    if (doc) e.info = doc;
    else if (infoFn) {
      const i = infoFn(name);
      if (i) e.info = i;
    }
    return e;
  });
}
