// Nim completion data — targets >= 2,000 unique entries.
import { EntrySet, bulk, members } from './helpers.mjs';

export function buildNim() {
  const s = new EntrySet('nim');

  // ── Keywords ────────────────────────────────────────────────────────
  s.addBulk([
    ['addr', 'keyword', 'addr x', 'Take the address of an lvalue'],
    ['and', 'keyword', 'a and b', 'Logical/bitwise AND operator'],
    ['as', 'keyword', 'expr as Type', 'Type ascription / import alias'],
    ['asm', 'keyword', 'asm "..."', 'Inline assembly block'],
    ['bind', 'keyword', 'bind ident', 'Bind identifier in template/macro scope'],
    ['block', 'keyword', 'block name: stmts', 'Named block expression'],
    ['break', 'keyword', 'break [name]', 'Exit the innermost loop or named block'],
    ['case', 'keyword', 'case x of: of A: ... else: ...', 'Pattern-matching case statement'],
    ['cast', 'keyword', 'cast[T](x)', 'Unsafe type conversion'],
    ['concept', 'keyword', 'type C = concept x', 'Define a generic concept (type class)'],
    ['const', 'keyword', 'const x = 1', 'Compile-time constant declaration'],
    ['continue', 'keyword', null, 'Skip to next loop iteration'],
    ['converter', 'keyword', 'converter toX(a: A): B', 'Implicit type converter declaration'],
    ['defer', 'keyword', 'defer: cleanup()', 'Defer code until current scope exits'],
    ['discard', 'keyword', 'discard expr', 'Discard a non-void expression'],
    ['distinct', 'keyword', 'type Id = distinct int', 'Strongly-typed wrapper around base type'],
    ['div', 'keyword', 'a div b', 'Integer division operator'],
    ['do', 'keyword', 'proc(x) = ...; do: stmts', 'Anonymous proc / block argument'],
    ['elif', 'keyword', 'elif cond:', 'Else-if branch'],
    ['else', 'keyword', 'else:', 'Else branch'],
    ['end', 'keyword', null, 'Reserved end-of-block keyword'],
    ['enum', 'keyword', 'type C = enum a, b, c', 'Enumeration type declaration'],
    ['except', 'keyword', 'except ValueError as e:', 'Exception-handling branch'],
    ['export', 'keyword', 'export module', 'Re-export a symbol from a module'],
    ['finally', 'keyword', 'finally:', 'Always-run cleanup branch'],
    ['for', 'keyword', 'for x in items:', 'For-in loop over an iterator'],
    ['from', 'keyword', 'from m import x', 'Restricted module import'],
    ['func', 'keyword', 'func name(): T', 'Side-effect-free proc'],
    ['if', 'keyword', 'if cond:', 'Conditional statement / expression'],
    ['import', 'keyword', 'import module', 'Import another module'],
    ['in', 'keyword', 'x in s', 'Set/sequence membership / for-loop binding'],
    ['include', 'keyword', 'include file', 'Textually include another file'],
    ['interface', 'keyword', null, 'Reserved keyword (rarely used)'],
    ['is', 'keyword', 'x is T', 'Type check / generic constraint'],
    ['isnot', 'keyword', 'x isnot T', 'Negated type check'],
    ['iterator', 'keyword', 'iterator name(): T', 'Iterator declaration'],
    ['let', 'keyword', 'let x = 1', 'Single-assignment binding'],
    ['macro', 'keyword', 'macro name(): untyped', 'Compile-time AST macro'],
    ['method', 'keyword', 'method name(o: Obj)', 'Multi-method (dynamic dispatch)'],
    ['mixin', 'keyword', 'mixin ident', 'Late-binding identifier in template/generic'],
    ['mod', 'keyword', 'a mod b', 'Modulo operator'],
    ['nil', 'keyword', null, 'Null pointer / reference value'],
    ['not', 'keyword', 'not x', 'Logical/bitwise NOT'],
    ['notin', 'keyword', 'x notin s', 'Negated membership test'],
    ['object', 'keyword', 'type T = object', 'Record/object type declaration'],
    ['of', 'keyword', 'x of T', 'Inheritance check / case branch'],
    ['or', 'keyword', 'a or b', 'Logical/bitwise OR'],
    ['out', 'keyword', 'proc f(out x: T)', 'Out parameter modifier'],
    ['proc', 'keyword', 'proc name()', 'Procedure declaration'],
    ['ptr', 'keyword', 'ptr T', 'Untraced pointer type'],
    ['raise', 'keyword', 'raise newException(E, msg)', 'Raise an exception'],
    ['ref', 'keyword', 'ref T', 'Traced reference type'],
    ['return', 'keyword', 'return x', 'Return from current proc'],
    ['shl', 'keyword', 'a shl n', 'Shift left'],
    ['shr', 'keyword', 'a shr n', 'Shift right'],
    ['static', 'keyword', 'static[T]', 'Compile-time evaluated parameter/block'],
    ['template', 'keyword', 'template name() = body', 'Hygienic substitution template'],
    ['try', 'keyword', 'try: ... except: ...', 'Try / except block'],
    ['tuple', 'keyword', 'tuple[a: int, b: string]', 'Anonymous-record tuple type'],
    ['type', 'keyword', 'type T = ...', 'Type declaration section'],
    ['using', 'keyword', 'using x: int', 'Default parameter type binding'],
    ['var', 'keyword', 'var x: int', 'Mutable variable declaration / by-ref param'],
    ['when', 'keyword', 'when defined(x):', 'Compile-time conditional'],
    ['while', 'keyword', 'while cond:', 'While loop'],
    ['xor', 'keyword', 'a xor b', 'Exclusive-or operator'],
    ['yield', 'keyword', 'yield expr', 'Yield from an iterator'],
    ['true', 'constant', 'bool', 'Boolean true'],
    ['false', 'constant', 'bool', 'Boolean false'],
    ['result', 'variable', null, 'Implicit return variable inside a proc'],
  ]);

  // ── Primitive / built-in types ──────────────────────────────────────
  s.addBulk([
    ['int', 'type', 'int', 'Platform-width signed integer'],
    ['int8', 'type', 'int8', '8-bit signed integer'],
    ['int16', 'type', 'int16', '16-bit signed integer'],
    ['int32', 'type', 'int32', '32-bit signed integer'],
    ['int64', 'type', 'int64', '64-bit signed integer'],
    ['uint', 'type', 'uint', 'Platform-width unsigned integer'],
    ['uint8', 'type', 'uint8', '8-bit unsigned integer'],
    ['uint16', 'type', 'uint16', '16-bit unsigned integer'],
    ['uint32', 'type', 'uint32', '32-bit unsigned integer'],
    ['uint64', 'type', 'uint64', '64-bit unsigned integer'],
    ['byte', 'type', 'uint8', 'Alias for uint8'],
    ['float', 'type', 'float', 'Platform-width IEEE float (usually float64)'],
    ['float32', 'type', 'float32', '32-bit IEEE float'],
    ['float64', 'type', 'float64', '64-bit IEEE float'],
    ['bool', 'type', 'bool', 'Boolean type (true / false)'],
    ['char', 'type', 'char', '8-bit ASCII character'],
    ['string', 'type', 'string', 'Built-in mutable UTF-8 string'],
    ['cstring', 'type', 'cstring', 'Null-terminated C string (foreign code)'],
    ['pointer', 'type', 'pointer', 'Untyped raw pointer'],
    ['void', 'type', 'void', 'No-value return type'],
    ['auto', 'type', 'auto', 'Inferred type placeholder'],
    ['any', 'type', 'any', 'Top type (any)'],
    ['typed', 'type', null, 'Macro/template parameter that is typed'],
    ['untyped', 'type', null, 'Macro/template parameter that is untyped'],
    ['typedesc', 'type', null, 'Compile-time type descriptor'],
    ['seq', 'type', 'seq[T]', 'Dynamic-length sequence container'],
    ['array', 'type', 'array[I, T]', 'Fixed-length array container'],
    ['set', 'type', 'set[T]', 'Bit-set of an ordinal type'],
    ['range', 'type', 'range[lo..hi]', 'Subrange of an ordinal type'],
    ['openArray', 'type', 'openArray[T]', 'Fat-pointer view over array/seq'],
    ['varargs', 'type', 'varargs[T]', 'Variable-length argument list'],
    ['Slice', 'type', 'Slice[T]', 'a..b range slice'],
    ['HSlice', 'type', 'HSlice[A, B]', 'Heterogeneous slice'],
    ['SomeInteger', 'type', null, 'Type class of all integer types'],
    ['SomeSignedInt', 'type', null, 'Type class of signed integers'],
    ['SomeUnsignedInt', 'type', null, 'Type class of unsigned integers'],
    ['SomeFloat', 'type', null, 'Type class of float types'],
    ['SomeNumber', 'type', null, 'Type class of all numeric types'],
    ['SomeOrdinal', 'type', null, 'Type class of all ordinal types'],
    ['Ordinal', 'type', null, 'Generic ordinal type class'],
    ['Natural', 'type', 'range[0..high(int)]', 'Non-negative integer'],
    ['Positive', 'type', 'range[1..high(int)]', 'Positive integer'],
    ['BiggestInt', 'type', null, 'Widest available signed integer'],
    ['BiggestUInt', 'type', null, 'Widest available unsigned integer'],
    ['BiggestFloat', 'type', null, 'Widest available float'],
    ['cint', 'type', 'cint', 'C int (foreign FFI)'],
    ['clong', 'type', 'clong', 'C long (foreign FFI)'],
    ['clonglong', 'type', 'clonglong', 'C long long (foreign FFI)'],
    ['cshort', 'type', 'cshort', 'C short (foreign FFI)'],
    ['cschar', 'type', 'cschar', 'C signed char'],
    ['cuchar', 'type', 'cuchar', 'C unsigned char'],
    ['cuint', 'type', 'cuint', 'C unsigned int'],
    ['culong', 'type', 'culong', 'C unsigned long'],
    ['culonglong', 'type', 'culonglong', 'C unsigned long long'],
    ['cushort', 'type', 'cushort', 'C unsigned short'],
    ['cfloat', 'type', 'cfloat', 'C float'],
    ['cdouble', 'type', 'cdouble', 'C double'],
    ['clongdouble', 'type', 'clongdouble', 'C long double'],
    ['csize_t', 'type', 'csize_t', 'C size_t'],
    ['cssize_t', 'type', 'cssize_t', 'C ssize_t'],
    ['cstringArray', 'type', 'cstringArray', 'NULL-terminated array of cstrings'],
    ['Exception', 'type', null, 'Root of the exception hierarchy'],
    ['Defect', 'type', null, 'Defect parent type (programming errors)'],
    ['CatchableError', 'type', null, 'Errors that may be caught'],
    ['IOError', 'type', null, 'I/O failure exception'],
    ['EOFError', 'type', null, 'End-of-file exception'],
    ['OSError', 'type', null, 'Operating-system failure'],
    ['ValueError', 'type', null, 'Invalid value exception'],
    ['KeyError', 'type', null, 'Missing key exception'],
    ['IndexDefect', 'type', null, 'Index out of bounds defect'],
    ['IndexError', 'type', 'IndexDefect', 'Legacy alias for IndexDefect'],
    ['RangeDefect', 'type', null, 'Value out of range defect'],
    ['RangeError', 'type', 'RangeDefect', 'Legacy alias for RangeDefect'],
    ['OverflowDefect', 'type', null, 'Arithmetic overflow defect'],
    ['DivByZeroDefect', 'type', null, 'Division-by-zero defect'],
    ['NilAccessDefect', 'type', null, 'Nil dereference defect'],
    ['ArithmeticError', 'type', null, 'Arithmetic exception parent'],
    ['AssertionDefect', 'type', null, 'Failed assert defect'],
    ['AssertionError', 'type', 'AssertionDefect', 'Legacy alias'],
    ['FieldDefect', 'type', null, 'Invalid object-variant field access'],
    ['ResourceExhaustedError', 'type', null, 'Out-of-resource error'],
    ['OutOfMemDefect', 'type', null, 'Allocation failure defect'],
    ['DeadThreadDefect', 'type', null, 'Operation on dead thread'],
    ['ReraiseDefect', 'type', null, 'Re-raise without active exception'],
    ['ObjectAssignmentDefect', 'type', null, 'Bad object assignment defect'],
    ['ObjectConversionDefect', 'type', null, 'Bad object cast defect'],
    ['FloatingPointDefect', 'type', null, 'Float arithmetic defect'],
    ['FloatInvalidOpDefect', 'type', null, 'Invalid float op defect'],
    ['FloatDivByZeroDefect', 'type', null, 'Float division-by-zero defect'],
    ['FloatOverflowDefect', 'type', null, 'Float overflow defect'],
    ['FloatUnderflowDefect', 'type', null, 'Float underflow defect'],
    ['FloatInexactDefect', 'type', null, 'Inexact float result defect'],
    ['LibraryError', 'type', null, 'Dynamic library load error'],
  ]);

  // ── System module builtins ──────────────────────────────────────────
  s.addBulk([
    ['echo', 'function', 'proc echo(args: varargs[typed, $])', 'Write arguments to stdout with newline'],
    ['assert', 'function', 'template assert(cond: bool; msg = "")', 'Runtime assertion (off in release)'],
    ['doAssert', 'function', 'template doAssert(cond: bool; msg = "")', 'Always-on assertion'],
    ['raiseAssert', 'function', 'proc raiseAssert(msg: string)', 'Raise AssertionDefect with message'],
    ['add', 'function', 'proc add[T](x: var seq[T]; y: T)', 'Append element/sequence/string'],
    ['len', 'function', 'proc len(x: untyped): int', 'Length of seq, array, string, set, etc.'],
    ['setLen', 'function', 'proc setLen[T](s: var seq[T]; n: Natural)', 'Resize sequence/string'],
    ['pop', 'function', 'proc pop[T](s: var seq[T]): T', 'Remove and return last element'],
    ['delete', 'function', 'proc delete[T](s: var seq[T]; i: Natural)', 'Delete item at index, shifting'],
    ['insert', 'function', 'proc insert[T](s: var seq[T]; item: T; i = 0)', 'Insert element at index'],
    ['del', 'function', 'proc del[T](s: var seq[T]; i: Natural)', 'O(1) delete by swap with last'],
    ['high', 'function', 'proc high[T](x: T): T', 'Highest valid index/value'],
    ['low', 'function', 'proc low[T](x: T): T', 'Lowest valid index/value'],
    ['inc', 'function', 'proc inc[T: Ordinal](x: var T; n = 1)', 'Increment ordinal in place'],
    ['dec', 'function', 'proc dec[T: Ordinal](x: var T; n = 1)', 'Decrement ordinal in place'],
    ['succ', 'function', 'proc succ[T: Ordinal](x: T; n = 1): T', 'Successor of an ordinal'],
    ['pred', 'function', 'proc pred[T: Ordinal](x: T; n = 1): T', 'Predecessor of an ordinal'],
    ['min', 'function', 'proc min[T](a, b: T): T', 'Smaller of two values'],
    ['max', 'function', 'proc max[T](a, b: T): T', 'Larger of two values'],
    ['abs', 'function', 'proc abs[T: SomeNumber](x: T): T', 'Absolute value'],
    ['divmod', 'function', 'proc divmod[T: SomeInteger](a, b: T): (T, T)', 'Quotient and remainder'],
    ['chr', 'function', 'proc chr(i: range[0..255]): char', 'Convert integer to char'],
    ['ord', 'function', 'proc ord[T: Ordinal](x: T): int', 'Convert ordinal to integer'],
    ['repr', 'function', 'proc repr[T](x: T): string', 'Debug textual representation'],
    ['unsafeAddr', 'function', 'proc unsafeAddr[T](x: T): ptr T', 'Take pointer regardless of mutability'],
    ['swap', 'function', 'proc swap[T](a, b: var T)', 'Swap two values in place'],
    ['move', 'function', 'proc move[T](x: var T): T', 'Move-out, leaving default'],
    ['clamp', 'function', 'proc clamp[T](x, a, b: T): T', 'Clamp value to [a, b]'],
    ['slurp', 'function', 'proc slurp(filename: string): string', 'Read file at compile time (alias)'],
    ['gorge', 'function', 'proc gorge(cmd: string; input = ""; cache = ""): string', 'Run command at compile time'],
    ['staticExec', 'function', 'proc staticExec(cmd: string): string', 'Execute shell command at compile time'],
    ['staticRead', 'function', 'proc staticRead(filename: string): string', 'Read file contents at compile time'],
    ['quit', 'function', 'proc quit(errorcode: int = QuitSuccess)', 'Terminate the program'],
    ['defined', 'function', 'proc defined(x: untyped): bool', 'Check if symbol/define is defined'],
    ['declared', 'function', 'proc declared(x: untyped): bool', 'Check if identifier is declared in scope'],
    ['compiles', 'function', 'proc compiles(x: untyped): bool', 'Check if expression compiles'],
    ['getCurrentException', 'function', 'proc getCurrentException(): ref Exception', 'Get current exception object'],
    ['getCurrentExceptionMsg', 'function', 'proc getCurrentExceptionMsg(): string', 'Get message of current exception'],
    ['new', 'function', 'proc new[T](a: var ref T)', 'Allocate and zero-init a ref'],
    ['dispose', 'function', 'proc dispose(p: pointer)', 'Free pointer (manual memory)'],
    ['alloc', 'function', 'proc alloc(size: Natural): pointer', 'Untraced raw allocation'],
    ['dealloc', 'function', 'proc dealloc(p: pointer)', 'Free memory allocated with alloc'],
    ['realloc', 'function', 'proc realloc(p: pointer; size: Natural): pointer', 'Resize allocation'],
    ['alloc0', 'function', 'proc alloc0(size: Natural): pointer', 'Allocate zeroed memory'],
    ['createU', 'function', 'proc createU[T](size: Natural = 1): ptr T', 'Allocate uninitialised memory'],
    ['create', 'function', 'proc create[T](size: Natural = 1): ptr T', 'Allocate zeroed typed memory'],
    ['createShared', 'function', 'proc createShared[T](size: Natural = 1): ptr T', 'Allocate shared memory'],
    ['createSharedU', 'function', 'proc createSharedU[T](size: Natural = 1): ptr T', 'Allocate uninitialised shared memory'],
    ['freeShared', 'function', 'proc freeShared[T](p: ptr T)', 'Free shared memory'],
    ['cmp', 'function', 'proc cmp[T](a, b: T): int', 'Three-way comparison'],
    ['copy', 'function', 'proc copy(s: string; first, last: int): string', 'Substring copy'],
    ['newSeq', 'function', 'proc newSeq[T](len: Natural = 0): seq[T]', 'Create new sequence of length'],
    ['newSeqOfCap', 'function', 'proc newSeqOfCap[T](cap: Natural): seq[T]', 'New empty seq with capacity'],
    ['newSeqUninitialized', 'function', 'proc newSeqUninitialized[T](len: Natural): seq[T]', 'Uninitialised sequence (POD only)'],
    ['newString', 'function', 'proc newString(len: Natural): string', 'Create new string of length'],
    ['newStringOfCap', 'function', 'proc newStringOfCap(cap: Natural): string', 'New empty string with capacity'],
    ['toSeq', 'function', 'proc toSeq[T](iter: iterable[T]): seq[T]', 'Materialise iterator into seq'],
    ['toOpenArray', 'function', 'proc toOpenArray[T](x: seq[T]; first, last: int): openArray[T]', 'View into a slice'],
    ['contains', 'function', 'proc contains[T](s: set[T]; x: T): bool', 'Membership test (in)'],
    ['find', 'function', 'proc find[T](s: openArray[T]; x: T): int', 'Find item index, -1 if absent'],
    ['shallowCopy', 'function', 'proc shallowCopy[T](dest: var T; src: T)', 'Shallow assignment of seqs/strings'],
    ['deepCopy', 'function', 'proc deepCopy[T](dest: var T; src: T)', 'Deep recursive copy'],
    ['hash', 'function', 'proc hash[T](x: T): Hash', 'Default hash via hashes module'],
    ['toLowerAscii', 'function', 'proc toLowerAscii(c: char): char', 'ASCII-only lowercase'],
    ['toUpperAscii', 'function', 'proc toUpperAscii(c: char): char', 'ASCII-only uppercase'],
    ['cstring', 'function', 'proc cstring(s: string): cstring', 'Convert Nim string to cstring'],
    ['readFile', 'function', 'proc readFile(filename: string): string', 'Read entire file into string'],
    ['writeFile', 'function', 'proc writeFile(filename, content: string)', 'Write string to file'],
    ['readLine', 'function', 'proc readLine(f: File): string', 'Read line from file'],
    ['readLines', 'function', 'proc readLines(filename: string; n: Natural): seq[string]', 'Read first n lines'],
    ['writeLine', 'function', 'proc writeLine[T](f: File; x: varargs[T, $])', 'Write line to file'],
    ['open', 'function', 'proc open(f: var File; filename: string; mode = fmRead): bool', 'Open file handle'],
    ['close', 'function', 'proc close(f: File)', 'Close file handle'],
    ['flushFile', 'function', 'proc flushFile(f: File)', 'Flush file buffer'],
    ['endOfFile', 'function', 'proc endOfFile(f: File): bool', 'True at EOF'],
    ['getFileSize', 'function', 'proc getFileSize(f: File): int64', 'Size of open file in bytes'],
    ['getPosition', 'function', 'proc getPosition(f: File): int64', 'Current file position'],
    ['setFilePos', 'function', 'proc setFilePos(f: File; pos: int64)', 'Seek to file position'],
    ['stdout', 'variable', 'File', 'Standard output File'],
    ['stderr', 'variable', 'File', 'Standard error File'],
    ['stdin', 'variable', 'File', 'Standard input File'],
    ['File', 'type', 'File', 'Buffered I/O file handle'],
    ['FileMode', 'enum', null, 'fmRead, fmWrite, fmReadWrite, fmAppend'],
    ['fmRead', 'constant', 'FileMode', 'Open existing file for reading'],
    ['fmWrite', 'constant', 'FileMode', 'Open and truncate for writing'],
    ['fmReadWrite', 'constant', 'FileMode', 'Open existing for read/write'],
    ['fmReadWriteExisting', 'constant', 'FileMode', 'Open existing for read/write (no truncate)'],
    ['fmAppend', 'constant', 'FileMode', 'Open for append'],
    ['QuitSuccess', 'constant', 'int', 'Process exit code 0'],
    ['QuitFailure', 'constant', 'int', 'Process exit code 1'],
    ['NimMajor', 'constant', 'int', 'Compiler major version'],
    ['NimMinor', 'constant', 'int', 'Compiler minor version'],
    ['NimPatch', 'constant', 'int', 'Compiler patch version'],
    ['NimVersion', 'constant', 'string', 'Compiler version string'],
    ['hostOS', 'constant', 'string', 'Target OS name'],
    ['hostCPU', 'constant', 'string', 'Target CPU architecture'],
    ['cpuEndian', 'constant', 'Endianness', 'CPU byte order'],
    ['paramCount', 'function', 'proc paramCount(): int', 'Number of command-line arguments'],
    ['paramStr', 'function', 'proc paramStr(i: int): string', 'Get command-line argument'],
    ['commandLineParams', 'function', 'proc commandLineParams(): seq[string]', 'All command-line arguments'],
    ['typeof', 'function', 'macro typeof(x: untyped): typedesc', 'Type of an expression'],
    ['sizeof', 'function', 'proc sizeof[T](x: T): int', 'Byte size of value/type'],
    ['alignof', 'function', 'proc alignof[T](x: T): int', 'Required alignment of type'],
    ['offsetOf', 'function', 'macro offsetOf(t: typedesc; member: untyped): int', 'Byte offset of object field'],
    ['toFloat', 'function', 'proc toFloat(i: int): float', 'Convert int to float'],
    ['toBiggestFloat', 'function', 'proc toBiggestFloat(i: BiggestInt): BiggestFloat', 'Convert to widest float'],
    ['toInt', 'function', 'proc toInt(f: float): int', 'Round float to int'],
    ['toBiggestInt', 'function', 'proc toBiggestInt(f: BiggestFloat): BiggestInt', 'Round to widest int'],
    ['system', 'namespace', 'module system', 'Implicitly imported core module'],
    ['globalRaiseHook', 'variable', null, 'Hook called on uncaught exception'],
    ['localRaiseHook', 'variable', null, 'Per-thread raise hook'],
    ['onUnhandledException', 'variable', null, 'Final handler for uncaught exceptions'],
    ['gc_ref', 'function', null, 'Increment GC ref count (low-level)'],
    ['gc_unref', 'function', null, 'Decrement GC ref count (low-level)'],
    ['GC_disable', 'function', 'proc GC_disable()', 'Pause garbage collector'],
    ['GC_enable', 'function', 'proc GC_enable()', 'Resume garbage collector'],
    ['GC_fullCollect', 'function', 'proc GC_fullCollect()', 'Force full GC cycle'],
    ['GC_ref', 'function', 'proc GC_ref[T](x: ref T)', 'Pin reference from GC'],
    ['GC_unref', 'function', 'proc GC_unref[T](x: ref T)', 'Unpin reference'],
    ['getOccupiedMem', 'function', 'proc getOccupiedMem(): int', 'Bytes currently in use by GC'],
    ['getFreeMem', 'function', 'proc getFreeMem(): int', 'Free bytes in GC heap'],
    ['getTotalMem', 'function', 'proc getTotalMem(): int', 'Total GC heap bytes'],
    ['rawProc', 'function', null, 'Raw procedure pointer of a closure'],
    ['rawEnv', 'function', null, 'Closure environment pointer'],
    ['finished', 'function', 'proc finished(x: iterator): bool', 'True if iterator exhausted'],
    ['countdown', 'function', 'iterator countdown[T](a, b: T; step = 1): T', 'Count down iterator'],
    ['countup', 'function', 'iterator countup[T](a, b: T; step = 1): T', 'Count up iterator'],
    ['items', 'function', 'iterator items[T](s: openArray[T]): T', 'Standard items iterator'],
    ['pairs', 'function', 'iterator pairs[T](s: openArray[T]): (int, T)', 'Index/value iterator'],
    ['mitems', 'function', 'iterator mitems[T](s: var openArray[T]): var T', 'Mutable items iterator'],
    ['mpairs', 'function', 'iterator mpairs[T](s: var openArray[T]): (int, var T)', 'Mutable index/value iterator'],
    ['fields', 'function', 'iterator fields(x: tuple|object): untyped', 'Iterate fields of tuple/object'],
    ['fieldPairs', 'function', 'iterator fieldPairs(x: tuple|object): (string, untyped)', 'Iterate (name, value) of fields'],
    ['runnableExamples', 'function', 'template runnableExamples(body: untyped)', 'Embed runnable doc examples'],
    ['toString', 'function', 'proc `$`[T](x: T): string', 'Default string conversion'],
    ['$', 'function', 'proc `$`[T](x: T): string', 'String conversion operator'],
    ['&', 'function', 'proc `&`(a, b: string): string', 'String concatenation'],
    ['..', 'function', 'proc `..`[A, B](a: A; b: B): HSlice[A, B]', 'Inclusive range'],
    ['..<', 'function', 'proc `..<`[A, B](a: A; b: B): HSlice[A, B]', 'Half-open range'],
  ]);

  // ── strutils module ────────────────────────────────────────────────
  s.addBulk([
    ['strutils', 'namespace', 'import strutils', 'String manipulation utilities'],
    ['split', 'function', 'proc split(s: string; sep: char): seq[string]', 'Split string by separator'],
    ['splitLines', 'function', 'proc splitLines(s: string): seq[string]', 'Split on \\n / \\r\\n line breaks'],
    ['splitWhitespace', 'function', 'proc splitWhitespace(s: string): seq[string]', 'Split on whitespace runs'],
    ['rsplit', 'function', 'proc rsplit(s: string; sep: char; maxsplit = -1): seq[string]', 'Split from the right'],
    ['parseInt', 'function', 'proc parseInt(s: string): int', 'Parse decimal integer'],
    ['parseUInt', 'function', 'proc parseUInt(s: string): uint', 'Parse decimal unsigned integer'],
    ['parseBiggestInt', 'function', 'proc parseBiggestInt(s: string): BiggestInt', 'Parse widest integer'],
    ['parseBiggestUInt', 'function', 'proc parseBiggestUInt(s: string): BiggestUInt', 'Parse widest unsigned'],
    ['parseFloat', 'function', 'proc parseFloat(s: string): float', 'Parse floating-point number'],
    ['parseBiggestFloat', 'function', 'proc parseBiggestFloat(s: string): BiggestFloat', 'Parse widest float'],
    ['parseBool', 'function', 'proc parseBool(s: string): bool', 'Parse boolean string'],
    ['parseEnum', 'function', 'proc parseEnum[T: enum](s: string): T', 'Parse enum from string'],
    ['parseHexInt', 'function', 'proc parseHexInt(s: string): int', 'Parse hexadecimal integer'],
    ['parseOctInt', 'function', 'proc parseOctInt(s: string): int', 'Parse octal integer'],
    ['parseBinInt', 'function', 'proc parseBinInt(s: string): int', 'Parse binary integer'],
    ['intToStr', 'function', 'proc intToStr(x: int; minChars = 0): string', 'Format integer with min width'],
    ['toBin', 'function', 'proc toBin(x: BiggestInt; len: Natural): string', 'Format as binary string'],
    ['toHex', 'function', 'proc toHex[T](x: T; len: Positive): string', 'Format as hexadecimal'],
    ['toOctal', 'function', 'proc toOctal(c: char): string', 'Format byte as octal'],
    ['replace', 'function', 'proc replace(s, sub, by: string): string', 'Replace all occurrences'],
    ['replaceWord', 'function', 'proc replaceWord(s, sub, by: string): string', 'Replace whole-word occurrences'],
    ['multiReplace', 'function', 'proc multiReplace(s: string; replacements: varargs[(string, string)]): string', 'Multi-pair replace'],
    ['repeat', 'function', 'proc repeat(s: string; n: Natural): string', 'Repeat string n times'],
    ['align', 'function', 'proc align(s: string; count: Natural; fill = \' \'): string', 'Right-align with fill'],
    ['alignLeft', 'function', 'proc alignLeft(s: string; count: Natural; fill = \' \'): string', 'Left-align with fill'],
    ['center', 'function', 'proc center(s: string; width: int; fillChar = \' \'): string', 'Center within width'],
    ['indent', 'function', 'proc indent(s: string; count: Natural; padding = " "): string', 'Indent each line'],
    ['unindent', 'function', 'proc unindent(s: string; count = 1; padding = " "): string', 'Remove leading indentation'],
    ['removeSuffix', 'function', 'proc removeSuffix(s: var string; suffix: string)', 'Strip trailing suffix'],
    ['removePrefix', 'function', 'proc removePrefix(s: var string; prefix: string)', 'Strip leading prefix'],
    ['removeNewlines', 'function', 'proc removeNewlines(s: string): string', 'Strip all line endings'],
    ['rfind', 'function', 'proc rfind(s, sub: string): int', 'Find last occurrence index'],
    ['count', 'function', 'proc count(s: string; sub: string): int', 'Count occurrences of substring'],
    ['startsWith', 'function', 'proc startsWith(s, prefix: string): bool', 'Test string prefix'],
    ['endsWith', 'function', 'proc endsWith(s, suffix: string): bool', 'Test string suffix'],
    ['strip', 'function', 'proc strip(s: string; leading = true; trailing = true): string', 'Trim whitespace'],
    ['stripLineEnd', 'function', 'proc stripLineEnd(s: var string)', 'Remove trailing line end'],
    ['capitalizeAscii', 'function', 'proc capitalizeAscii(s: string): string', 'Uppercase first ASCII char'],
    ['normalize', 'function', 'proc normalize(s: string): string', 'Lowercase + remove underscores'],
    ['editDistance', 'function', 'proc editDistance(a, b: string): int', 'Levenshtein edit distance'],
    ['editDistanceAscii', 'function', 'proc editDistanceAscii(a, b: string): int', 'ASCII-only edit distance'],
    ['format', 'function', 'proc format(s: string; args: varargs[string, $]): string', 'Format with $1, $2 placeholders'],
    ['formatBiggestFloat', 'function', 'proc formatBiggestFloat(f: BiggestFloat; format = ffDefault; precision = -1): string', 'Format widest float'],
    ['formatFloat', 'function', 'proc formatFloat(f: float; format = ffDefault; precision = -1): string', 'Format float to string'],
    ['formatSize', 'function', 'proc formatSize(bytes: int64; prefix = bpIEC; includeSpace = false): string', 'Format byte size human-readable'],
    ['escape', 'function', 'proc escape(s: string; prefix = "\\""; suffix = "\\""): string', 'Escape into Nim literal'],
    ['unescape', 'function', 'proc unescape(s: string; prefix = "\\""; suffix = "\\""): string', 'Reverse of escape'],
    ['cmpIgnoreCase', 'function', 'proc cmpIgnoreCase(a, b: string): int', 'Case-insensitive compare'],
    ['cmpIgnoreStyle', 'function', 'proc cmpIgnoreStyle(a, b: string): int', 'Style-insensitive compare'],
    ['addQuoted', 'function', 'proc addQuoted[T](s: var string; x: T)', 'Append quoted form of value'],
    ['addSep', 'function', 'proc addSep(dest: var string; sep = ", "; startLen: Natural = 0)', 'Add separator if needed'],
    ['wordWrap', 'function', 'proc wordWrap(s: string; maxLineWidth = 80): string', 'Wrap words to width'],
    ['validIdentifier', 'function', 'proc validIdentifier(s: string): bool', 'Is valid Nim identifier'],
    ['isAlphaNumeric', 'function', 'proc isAlphaNumeric(c: char): bool', 'ASCII letter or digit'],
    ['isAlphaAscii', 'function', 'proc isAlphaAscii(c: char): bool', 'ASCII letter'],
    ['isDigit', 'function', 'proc isDigit(c: char): bool', 'ASCII digit'],
    ['isLowerAscii', 'function', 'proc isLowerAscii(c: char): bool', 'ASCII lowercase letter'],
    ['isUpperAscii', 'function', 'proc isUpperAscii(c: char): bool', 'ASCII uppercase letter'],
    ['isSpaceAscii', 'function', 'proc isSpaceAscii(c: char): bool', 'ASCII whitespace'],
    ['isEmptyOrWhitespace', 'function', 'proc isEmptyOrWhitespace(s: string): bool', 'Empty or whitespace-only'],
    ['allCharsInSet', 'function', 'proc allCharsInSet(s: string; theSet: set[char]): bool', 'All chars in set'],
    ['containsAny', 'function', 'proc containsAny(s: string; chars: set[char]): bool', 'Has any of given chars'],
    ['toBinary', 'function', null, 'Internal binary formatting helper'],
    ['Whitespace', 'constant', 'set[char]', 'ASCII whitespace character set'],
    ['Letters', 'constant', 'set[char]', 'ASCII letters set'],
    ['Digits', 'constant', 'set[char]', 'ASCII digits set'],
    ['HexDigits', 'constant', 'set[char]', 'ASCII hex digits set'],
    ['IdentChars', 'constant', 'set[char]', 'Identifier characters set'],
    ['IdentStartChars', 'constant', 'set[char]', 'Identifier start characters set'],
    ['Newlines', 'constant', 'set[char]', 'CR/LF newline character set'],
    ['NewLines', 'constant', 'set[char]', 'Alias for Newlines'],
    ['PrintableChars', 'constant', 'set[char]', 'Printable ASCII characters'],
    ['AllChars', 'constant', 'set[char]', 'All 256 byte values'],
    ['ffDefault', 'constant', 'FloatFormatMode', 'Default float format'],
    ['ffDecimal', 'constant', 'FloatFormatMode', 'Decimal float format'],
    ['ffScientific', 'constant', 'FloatFormatMode', 'Scientific float format'],
  ]);

  // ── sequtils module ────────────────────────────────────────────────
  s.addBulk([
    ['sequtils', 'namespace', 'import sequtils', 'Higher-order seq utilities'],
    ['concat', 'function', 'proc concat[T](seqs: varargs[seq[T]]): seq[T]', 'Concatenate sequences'],
    ['cycle', 'function', 'proc cycle[T](s: openArray[T]; n: Natural): seq[T]', 'Repeat sequence n times'],
    ['deduplicate', 'function', 'proc deduplicate[T](s: openArray[T]; isSorted = false): seq[T]', 'Remove duplicates'],
    ['minIndex', 'function', 'proc minIndex[T](s: openArray[T]): int', 'Index of minimum element'],
    ['maxIndex', 'function', 'proc maxIndex[T](s: openArray[T]): int', 'Index of maximum element'],
    ['flatten', 'function', 'proc flatten[T](s: openArray[seq[T]]): seq[T]', 'Concatenate nested sequences'],
    ['mapIt', 'function', 'template mapIt(s: openArray; op: untyped): untyped', 'Map with `it` placeholder'],
    ['applyIt', 'function', 'template applyIt(s: var openArray; op: untyped)', 'In-place map with `it`'],
    ['keepItIf', 'function', 'template keepItIf(s: var openArray; cond: untyped)', 'Filter in place by predicate'],
    ['filterIt', 'function', 'template filterIt(s: openArray; cond: untyped): seq', 'Filter with `it` placeholder'],
    ['allIt', 'function', 'template allIt(s: openArray; cond: untyped): bool', 'All elements satisfy predicate'],
    ['anyIt', 'function', 'template anyIt(s: openArray; cond: untyped): bool', 'Any element satisfies predicate'],
    ['findIt', 'function', 'template findIt(s: openArray; cond: untyped): int', 'Index of first match'],
    ['mapLiterals', 'function', 'macro mapLiterals(constructor; op: untyped): untyped', 'Apply op to all literals'],
    ['zip', 'function', 'proc zip[S, T](a: openArray[S]; b: openArray[T]): seq[(S, T)]', 'Pair up two sequences'],
    ['unzip', 'function', 'proc unzip[S, T](s: openArray[(S, T)]): (seq[S], seq[T])', 'Split tuples into pair of seqs'],
    ['mergeSorted', 'function', 'proc merge[T](a, b: openArray[T]): seq[T]', 'Merge two sorted sequences'],
    ['mapAndFilter', 'function', null, 'Map then filter (legacy)'],
    ['foldl', 'function', 'template foldl(s; op): untyped', 'Left fold over a sequence'],
    ['foldr', 'function', 'template foldr(s; op): untyped', 'Right fold over a sequence'],
    ['apply', 'function', 'proc apply[T](s: var openArray[T]; op: proc(x: var T))', 'In-place map'],
    ['filter', 'function', 'proc filter[T](s: openArray[T]; pred: proc(x: T): bool): seq[T]', 'Filter by predicate'],
    ['keepIf', 'function', 'proc keepIf[T](s: var seq[T]; pred: proc(x: T): bool)', 'In-place filter'],
    ['chunks', 'function', 'iterator chunks[T](s: openArray[T]; n: int): seq[T]', 'Yield fixed-size chunks'],
    ['windowed', 'function', 'iterator windowed[T](s: openArray[T]; n: int): seq[T]', 'Sliding windows of size n'],
    ['delete', 'function', 'proc delete[T](s: var seq[T]; first, last: Natural)', 'Delete a subrange'],
    ['insert', 'function', 'proc insert[T](dest: var seq[T]; src: openArray[T]; pos = 0)', 'Insert sequence at index'],
    ['count', 'function', 'proc count[T](s: openArray[T]; x: T): int', 'Count occurrences'],
    ['allCombinations', 'function', null, 'Cartesian-style combinations'],
    ['toCountTable', 'function', null, 'Build CountTable from seq'],
    ['toHashSet', 'function', null, 'Build HashSet from seq'],
    ['mapPairs', 'function', null, 'Map over (index, value) pairs'],
    ['range', 'function', 'iterator range[T](a, b: T; step = 1): T', 'Range iterator (sequtils helper)'],
    ['flatMap', 'function', 'proc flatMap[T, U](s: openArray[T]; f: proc(x: T): seq[U]): seq[U]', 'Map and concat'],
    ['enumerate', 'function', 'iterator enumerate[T](s: openArray[T]): (int, T)', 'Index/value pairs'],
    ['groupBy', 'function', null, 'Group elements by key proc'],
    ['partition', 'function', null, 'Split into (matching, non-matching)'],
    ['take', 'function', null, 'Take first n elements'],
    ['drop', 'function', null, 'Drop first n elements'],
    ['takeWhile', 'function', null, 'Take while predicate holds'],
    ['dropWhile', 'function', null, 'Drop while predicate holds'],
  ]);

  // ── tables module ──────────────────────────────────────────────────
  s.addBulk([
    ['tables', 'namespace', 'import tables', 'Hash tables: Table, OrderedTable, CountTable'],
    ['Table', 'type', 'Table[K, V]', 'Generic hash table'],
    ['OrderedTable', 'type', 'OrderedTable[K, V]', 'Insertion-ordered hash table'],
    ['CountTable', 'type', 'CountTable[K]', 'Counter / multiset'],
    ['TableRef', 'type', 'TableRef[K, V]', 'Heap-allocated reference Table'],
    ['OrderedTableRef', 'type', 'OrderedTableRef[K, V]', 'Heap-allocated OrderedTable'],
    ['CountTableRef', 'type', 'CountTableRef[K]', 'Heap-allocated CountTable'],
    ['initTable', 'function', 'proc initTable[K, V](initialSize = 64): Table[K, V]', 'Create empty Table'],
    ['initOrderedTable', 'function', 'proc initOrderedTable[K, V](initialSize = 64): OrderedTable[K, V]', 'Create empty OrderedTable'],
    ['initCountTable', 'function', 'proc initCountTable[K](initialSize = 64): CountTable[K]', 'Create empty CountTable'],
    ['newTable', 'function', 'proc newTable[K, V](initialSize = 64): TableRef[K, V]', 'Create heap Table'],
    ['newOrderedTable', 'function', 'proc newOrderedTable[K, V](initialSize = 64): OrderedTableRef[K, V]', 'Create heap OrderedTable'],
    ['newCountTable', 'function', 'proc newCountTable[K](initialSize = 64): CountTableRef[K]', 'Create heap CountTable'],
    ['toTable', 'function', 'proc toTable[K, V](pairs: openArray[(K, V)]): Table[K, V]', 'Build from key/value pairs'],
    ['toOrderedTable', 'function', 'proc toOrderedTable[K, V](pairs: openArray[(K, V)]): OrderedTable[K, V]', 'Build OrderedTable from pairs'],
    ['toCountTable', 'function', 'proc toCountTable[K](keys: openArray[K]): CountTable[K]', 'Build CountTable from items'],
    ['hasKey', 'function', 'proc hasKey[K, V](t: Table[K, V]; k: K): bool', 'Does table contain key'],
    ['getOrDefault', 'function', 'proc getOrDefault[K, V](t: Table[K, V]; k: K; default: V = default(V)): V', 'Lookup with default'],
    ['mgetOrPut', 'function', 'proc mgetOrPut[K, V](t: var Table[K, V]; k: K; v: V): var V', 'Mutable get-or-insert'],
    ['take', 'function', 'proc take[K, V](t: var Table[K, V]; k: K; v: var V): bool', 'Pop key into out var'],
    ['merge', 'function', 'proc merge[K](a: var CountTable[K]; b: CountTable[K])', 'Add counts from another CountTable'],
    ['keys', 'function', 'iterator keys[K, V](t: Table[K, V]): K', 'Iterate keys'],
    ['values', 'function', 'iterator values[K, V](t: Table[K, V]): V', 'Iterate values'],
    ['mvalues', 'function', 'iterator mvalues[K, V](t: var Table[K, V]): var V', 'Mutable values iterator'],
    ['sort', 'function', 'proc sort[K](t: var CountTable[K]; order = Descending)', 'Sort CountTable by count'],
    ['clear', 'function', 'proc clear[K, V](t: var Table[K, V])', 'Remove all entries'],
    ['hasKeyOrPut', 'function', 'proc hasKeyOrPut[K, V](t: var Table[K, V]; k: K; v: V): bool', 'Insert if missing'],
    ['indexBy', 'function', 'proc indexBy[A, B](xs: openArray[A]; f: proc(x: A): B): Table[B, A]', 'Build Table by key proc'],
    ['smallest', 'function', 'proc smallest[K](t: CountTable[K]): (K, int)', 'Lowest-count key'],
    ['largest', 'function', 'proc largest[K](t: CountTable[K]): (K, int)', 'Highest-count key'],
    ['sortByKey', 'function', null, 'Sort OrderedTable by key'],
    ['sortByValue', 'function', null, 'Sort OrderedTable by value'],
    ['enlarge', 'function', null, 'Internal capacity grow'],
    ['rightSize', 'function', 'proc rightSize(count: Natural): int', 'Recommended initial capacity'],
    ['CountTablePair', 'type', null, 'Internal CountTable pair'],
  ]);

  // ── sets module ────────────────────────────────────────────────────
  s.addBulk([
    ['sets', 'namespace', 'import sets', 'Generic hash sets'],
    ['HashSet', 'type', 'HashSet[A]', 'Generic hash set'],
    ['OrderedSet', 'type', 'OrderedSet[A]', 'Insertion-ordered hash set'],
    ['initHashSet', 'function', 'proc initHashSet[A](initialSize = 64): HashSet[A]', 'Create empty HashSet'],
    ['initOrderedSet', 'function', 'proc initOrderedSet[A](initialSize = 64): OrderedSet[A]', 'Create empty OrderedSet'],
    ['toHashSet', 'function', 'proc toHashSet[A](xs: openArray[A]): HashSet[A]', 'Build set from items'],
    ['toOrderedSet', 'function', 'proc toOrderedSet[A](xs: openArray[A]): OrderedSet[A]', 'Build OrderedSet from items'],
    ['incl', 'function', 'proc incl[A](s: var HashSet[A]; key: A)', 'Insert into set'],
    ['excl', 'function', 'proc excl[A](s: var HashSet[A]; key: A)', 'Remove from set'],
    ['union', 'function', 'proc union[A](a, b: HashSet[A]): HashSet[A]', 'Set union'],
    ['intersection', 'function', 'proc intersection[A](a, b: HashSet[A]): HashSet[A]', 'Set intersection'],
    ['difference', 'function', 'proc difference[A](a, b: HashSet[A]): HashSet[A]', 'Set difference'],
    ['symmetricDifference', 'function', 'proc symmetricDifference[A](a, b: HashSet[A]): HashSet[A]', 'XOR-like difference'],
    ['disjoint', 'function', 'proc disjoint[A](a, b: HashSet[A]): bool', 'No shared elements'],
    ['card', 'function', 'proc card[A](s: HashSet[A]): int', 'Cardinality (size)'],
    ['containsOrIncl', 'function', 'proc containsOrIncl[A](s: var HashSet[A]; key: A): bool', 'Insert; return whether already present'],
    ['missingOrExcl', 'function', 'proc missingOrExcl[A](s: var HashSet[A]; key: A): bool', 'Remove; return whether missing'],
    ['toSet', 'function', 'proc toSet[A](xs: openArray[A]): HashSet[A]', 'Legacy alias for toHashSet'],
    ['init', 'function', null, 'Initialize a generic set'],
    ['isValid', 'function', 'proc isValid[A](s: HashSet[A]): bool', 'Set has been initialised'],
    ['map', 'function', 'proc map[A, B](s: HashSet[A]; f: proc(x: A): B): HashSet[B]', 'Map set through function'],
    ['SetCommon', 'class', null, 'Common set interface'],
  ]);

  // ── options module ─────────────────────────────────────────────────
  s.addBulk([
    ['options', 'namespace', 'import options', 'Optional values: some/none'],
    ['Option', 'type', 'Option[T]', 'Maybe-a-value wrapper'],
    ['some', 'function', 'proc some[T](val: T): Option[T]', 'Wrap a value'],
    ['none', 'function', 'proc none(T: typedesc): Option[T]', 'Empty Option of type T'],
    ['isSome', 'function', 'proc isSome[T](o: Option[T]): bool', 'Has a value?'],
    ['isNone', 'function', 'proc isNone[T](o: Option[T]): bool', 'Is empty?'],
    ['get', 'function', 'proc get[T](o: Option[T]): T', 'Unwrap, raise if none'],
    ['unsafeGet', 'function', 'proc unsafeGet[T](o: Option[T]): T', 'Unwrap without check'],
    ['flatten', 'function', 'proc flatten[A](o: Option[Option[A]]): Option[A]', 'Flatten nested Option'],
    ['UnpackDefect', 'type', null, 'Defect raised by get on none'],
  ]);

  // ── strformat module ────────────────────────────────────────────────
  s.addBulk([
    ['strformat', 'namespace', 'import strformat', 'Python-style string interpolation'],
    ['fmt', 'function', 'macro fmt(pattern: static string): string', 'String interpolation macro'],
    ['&', 'function', 'macro `&`(pattern: static string): string', 'Operator form of fmt'],
  ]);

  // ── math module ────────────────────────────────────────────────────
  s.addBulk([
    ['math', 'namespace', 'import math', 'Mathematical functions and constants'],
    ['PI', 'constant', 'float = 3.14159265...', 'Ratio of circumference to diameter'],
    ['TAU', 'constant', 'float = 2*PI', 'Full circle constant'],
    ['E', 'constant', 'float = 2.71828...', 'Eulers number'],
    ['sqrt', 'function', 'proc sqrt(x: float): float', 'Square root'],
    ['cbrt', 'function', 'proc cbrt(x: float): float', 'Cube root'],
    ['exp', 'function', 'proc exp(x: float): float', 'e raised to x'],
    ['log', 'function', 'proc log(x, base: float): float', 'Logarithm in given base'],
    ['log2', 'function', 'proc log2(x: float): float', 'Base-2 logarithm'],
    ['log10', 'function', 'proc log10(x: float): float', 'Base-10 logarithm'],
    ['ln', 'function', 'proc ln(x: float): float', 'Natural logarithm'],
    ['sin', 'function', 'proc sin(x: float): float', 'Sine'],
    ['cos', 'function', 'proc cos(x: float): float', 'Cosine'],
    ['tan', 'function', 'proc tan(x: float): float', 'Tangent'],
    ['asin', 'function', 'proc asin(x: float): float', 'Inverse sine'],
    ['acos', 'function', 'proc acos(x: float): float', 'Inverse cosine'],
    ['atan', 'function', 'proc atan(x: float): float', 'Inverse tangent'],
    ['atan2', 'function', 'proc atan2(y, x: float): float', 'Two-argument arctangent'],
    ['sinh', 'function', 'proc sinh(x: float): float', 'Hyperbolic sine'],
    ['cosh', 'function', 'proc cosh(x: float): float', 'Hyperbolic cosine'],
    ['tanh', 'function', 'proc tanh(x: float): float', 'Hyperbolic tangent'],
    ['arcsinh', 'function', 'proc arcsinh(x: float): float', 'Inverse hyperbolic sine'],
    ['arccosh', 'function', 'proc arccosh(x: float): float', 'Inverse hyperbolic cosine'],
    ['arctanh', 'function', 'proc arctanh(x: float): float', 'Inverse hyperbolic tangent'],
    ['floor', 'function', 'proc floor(x: float): float', 'Round down to integer'],
    ['ceil', 'function', 'proc ceil(x: float): float', 'Round up to integer'],
    ['round', 'function', 'proc round(x: float; places = 0): float', 'Round to nearest'],
    ['trunc', 'function', 'proc trunc(x: float): float', 'Truncate toward zero'],
    ['pow', 'function', 'proc pow(base, exp: float): float', 'Power function'],
    ['hypot', 'function', 'proc hypot(x, y: float): float', 'sqrt(x*x + y*y)'],
    ['degToRad', 'function', 'proc degToRad(d: float): float', 'Degrees to radians'],
    ['radToDeg', 'function', 'proc radToDeg(r: float): float', 'Radians to degrees'],
    ['gcd', 'function', 'proc gcd[T](a, b: T): T', 'Greatest common divisor'],
    ['lcm', 'function', 'proc lcm[T](a, b: T): T', 'Least common multiple'],
    ['binom', 'function', 'proc binom(n, k: int): int', 'Binomial coefficient'],
    ['factorial', 'function', 'proc factorial(n: int): int', 'n!'],
    ['fac', 'function', 'proc fac(n: int): int', 'Alias for factorial'],
    ['nextPowerOfTwo', 'function', 'proc nextPowerOfTwo(x: int): int', 'Round up to power of two'],
    ['isPowerOfTwo', 'function', 'proc isPowerOfTwo(x: int): bool', 'Is x a power of two'],
    ['classify', 'function', 'proc classify(x: float): FloatClass', 'Classify float (NaN, Inf, etc.)'],
    ['isNaN', 'function', 'proc isNaN(x: float): bool', 'Is value NaN'],
    ['fmod', 'function', 'proc fmod(x, y: float): float', 'Floating-point modulo'],
    ['frexp', 'function', 'proc frexp(x: float): (float, int)', 'Split into mantissa/exponent'],
    ['ldexp', 'function', 'proc ldexp(x: float; e: int): float', 'x * 2^e'],
    ['copySign', 'function', 'proc copySign(x, y: float): float', 'Magnitude of x with sign of y'],
    ['splitDecimal', 'function', 'proc splitDecimal(x: float): (float, float)', 'Integer/fractional parts'],
    ['euclDiv', 'function', 'proc euclDiv[T](a, b: T): T', 'Euclidean division'],
    ['euclMod', 'function', 'proc euclMod[T](a, b: T): T', 'Euclidean modulo'],
    ['floorDiv', 'function', 'proc floorDiv[T](a, b: T): T', 'Floor division'],
    ['floorMod', 'function', 'proc floorMod[T](a, b: T): T', 'Floored modulo'],
    ['ceilDiv', 'function', 'proc ceilDiv[T](a, b: T): T', 'Ceiling division'],
    ['sgn', 'function', 'proc sgn[T](x: T): int', 'Sign: -1, 0, or +1'],
    ['sum', 'function', 'proc sum[T](x: openArray[T]): T', 'Sum of elements'],
    ['prod', 'function', 'proc prod[T](x: openArray[T]): T', 'Product of elements'],
    ['cumsum', 'function', 'proc cumsum[T](s: var openArray[T])', 'In-place cumulative sum'],
    ['cumsummed', 'function', 'proc cumsummed[T](s: openArray[T]): seq[T]', 'Cumulative-sum copy'],
    ['mean', 'function', 'proc mean[T](x: openArray[T]): float', 'Arithmetic mean'],
    ['variance', 'function', 'proc variance[T](x: openArray[T]): float', 'Sample variance'],
    ['standardDeviation', 'function', 'proc standardDeviation[T](x: openArray[T]): float', 'Sample standard deviation'],
    ['Inf', 'constant', 'float', 'Positive infinity'],
    ['NegInf', 'constant', 'float', 'Negative infinity'],
    ['NaN', 'constant', 'float', 'Not-a-number'],
    ['MaxFloat64Precision', 'constant', 'int', 'Float64 decimal precision'],
    ['MaxFloat32Precision', 'constant', 'int', 'Float32 decimal precision'],
    ['fcNan', 'constant', 'FloatClass', 'NaN classification'],
    ['fcInf', 'constant', 'FloatClass', 'Positive infinity classification'],
    ['fcNegInf', 'constant', 'FloatClass', 'Negative infinity classification'],
    ['fcNormal', 'constant', 'FloatClass', 'Normal float classification'],
    ['fcSubnormal', 'constant', 'FloatClass', 'Subnormal float classification'],
    ['fcZero', 'constant', 'FloatClass', 'Positive zero classification'],
    ['fcNegZero', 'constant', 'FloatClass', 'Negative zero classification'],
  ]);

  // ── os module ───────────────────────────────────────────────────────
  s.addBulk([
    ['os', 'namespace', 'import os', 'Operating-system facilities'],
    ['getEnv', 'function', 'proc getEnv(key: string; default = ""): string', 'Read environment variable'],
    ['putEnv', 'function', 'proc putEnv(key, val: string)', 'Set environment variable'],
    ['existsEnv', 'function', 'proc existsEnv(key: string): bool', 'Is env var defined'],
    ['delEnv', 'function', 'proc delEnv(key: string)', 'Unset environment variable'],
    ['envPairs', 'function', 'iterator envPairs(): (string, string)', 'Iterate environment pairs'],
    ['getCurrentDir', 'function', 'proc getCurrentDir(): string', 'Process current directory'],
    ['setCurrentDir', 'function', 'proc setCurrentDir(newDir: string)', 'Change current directory'],
    ['getHomeDir', 'function', 'proc getHomeDir(): string', 'User home directory'],
    ['getConfigDir', 'function', 'proc getConfigDir(): string', 'Per-user config directory'],
    ['getTempDir', 'function', 'proc getTempDir(): string', 'OS temp directory'],
    ['getAppDir', 'function', 'proc getAppDir(): string', 'Directory of running executable'],
    ['getAppFilename', 'function', 'proc getAppFilename(): string', 'Path of running executable'],
    ['getCurrentProcessId', 'function', 'proc getCurrentProcessId(): int', 'Process ID (PID)'],
    ['splitPath', 'function', 'proc splitPath(p: string): (string, string)', 'Split into (head, tail)'],
    ['splitFile', 'function', 'proc splitFile(p: string): (string, string, string)', 'Split into dir/name/ext'],
    ['extractFilename', 'function', 'proc extractFilename(p: string): string', 'Tail component'],
    ['parentDir', 'function', 'proc parentDir(p: string): string', 'Drop tail, return parent'],
    ['joinPath', 'function', 'proc joinPath(parts: varargs[string]): string', 'Join path components'],
    ['relativePath', 'function', 'proc relativePath(p, base: string): string', 'Path relative to base'],
    ['absolutePath', 'function', 'proc absolutePath(p: string; root = ""): string', 'Make path absolute'],
    ['normalizedPath', 'function', 'proc normalizedPath(p: string): string', 'Collapse .. and . segments'],
    ['expandFilename', 'function', 'proc expandFilename(p: string): string', 'Real, absolute, canonical path'],
    ['expandTilde', 'function', 'proc expandTilde(p: string): string', 'Expand leading ~'],
    ['existsFile', 'function', 'proc existsFile(p: string): bool', 'File exists (deprecated alias)'],
    ['existsDir', 'function', 'proc existsDir(p: string): bool', 'Directory exists (deprecated alias)'],
    ['fileExists', 'function', 'proc fileExists(p: string): bool', 'File exists at path'],
    ['dirExists', 'function', 'proc dirExists(p: string): bool', 'Directory exists at path'],
    ['symlinkExists', 'function', 'proc symlinkExists(p: string): bool', 'Symlink exists at path'],
    ['removeFile', 'function', 'proc removeFile(p: string)', 'Delete a file'],
    ['removeDir', 'function', 'proc removeDir(p: string; checkDir = false)', 'Delete a directory tree'],
    ['createDir', 'function', 'proc createDir(p: string)', 'Create directory + parents'],
    ['existsOrCreateDir', 'function', 'proc existsOrCreateDir(p: string): bool', 'Ensure directory exists'],
    ['copyFile', 'function', 'proc copyFile(src, dst: string)', 'Copy a single file'],
    ['copyFileWithPermissions', 'function', 'proc copyFileWithPermissions(src, dst: string)', 'Copy preserving permissions'],
    ['copyDir', 'function', 'proc copyDir(src, dst: string)', 'Copy directory recursively'],
    ['copyDirWithPermissions', 'function', 'proc copyDirWithPermissions(src, dst: string)', 'Copy dir preserving perms'],
    ['moveFile', 'function', 'proc moveFile(src, dst: string)', 'Rename / move file'],
    ['moveDir', 'function', 'proc moveDir(src, dst: string)', 'Rename / move directory'],
    ['walkDir', 'function', 'iterator walkDir(dir: string): tuple[kind: PathComponent, path: string]', 'Iterate directory entries'],
    ['walkDirRec', 'function', 'iterator walkDirRec(dir: string): string', 'Recursive directory walk'],
    ['walkFiles', 'function', 'iterator walkFiles(pattern: string): string', 'Glob-match files'],
    ['walkPattern', 'function', 'iterator walkPattern(pattern: string): string', 'Glob-match files and dirs'],
    ['getFileInfo', 'function', 'proc getFileInfo(p: string; followSymlink = true): FileInfo', 'Stat a file'],
    ['getFileSize', 'function', 'proc getFileSize(p: string): BiggestInt', 'File size in bytes'],
    ['getLastModificationTime', 'function', 'proc getLastModificationTime(p: string): Time', 'Mtime of file'],
    ['getCreationTime', 'function', 'proc getCreationTime(p: string): Time', 'Creation time of file'],
    ['getLastAccessTime', 'function', 'proc getLastAccessTime(p: string): Time', 'Atime of file'],
    ['setFilePermissions', 'function', 'proc setFilePermissions(p: string; permissions: set[FilePermission])', 'Set file permissions'],
    ['getFilePermissions', 'function', 'proc getFilePermissions(p: string): set[FilePermission]', 'Get file permissions'],
    ['execShellCmd', 'function', 'proc execShellCmd(cmd: string): int', 'Run a shell command'],
    ['DirSep', 'constant', 'char', 'OS path separator (\\\\ or /)'],
    ['AltSep', 'constant', 'char', 'Alternative path separator'],
    ['PathSep', 'constant', 'char', 'Char between PATH entries'],
    ['ExtSep', 'constant', 'char', 'Extension separator (.)'],
    ['CurDir', 'constant', 'char', 'Current dir token (.)'],
    ['ParDir', 'constant', 'string', 'Parent dir token (..)'],
    ['FileSystemCaseSensitive', 'constant', 'bool', 'Is FS case-sensitive'],
    ['ExeExt', 'constant', 'string', 'Executable extension'],
    ['ScriptExt', 'constant', 'string', 'Script extension'],
    ['DynlibFormat', 'constant', 'string', 'Dynamic library file format'],
    ['PathComponent', 'enum', null, 'pcFile, pcLinkToFile, pcDir, pcLinkToDir'],
    ['FileInfo', 'type', null, 'File metadata struct'],
    ['FilePermission', 'enum', null, 'fpUserRead, fpGroupExec, fpOthersWrite, etc.'],
  ]);

  // ── times module ────────────────────────────────────────────────────
  s.addBulk([
    ['times', 'namespace', 'import times', 'Date and time handling'],
    ['Time', 'type', 'Time', 'Point-in-time (UNIX nanoseconds)'],
    ['DateTime', 'type', 'DateTime', 'Calendar date/time with timezone'],
    ['Duration', 'type', 'Duration', 'Time span (signed)'],
    ['Month', 'enum', null, 'mJan..mDec'],
    ['WeekDay', 'enum', null, 'dMon..dSun'],
    ['Timezone', 'type', null, 'Timezone information record'],
    ['TimeUnit', 'enum', null, 'Nanoseconds, Microseconds, Days, Years, etc.'],
    ['TimeFormat', 'type', null, 'Compiled time format string'],
    ['TimeInterval', 'type', null, 'Calendar interval (months, years)'],
    ['now', 'function', 'proc now(): DateTime', 'Current local DateTime'],
    ['getTime', 'function', 'proc getTime(): Time', 'Current UNIX time'],
    ['epochTime', 'function', 'proc epochTime(): float', 'Seconds since epoch (float)'],
    ['cpuTime', 'function', 'proc cpuTime(): float', 'CPU time used by process'],
    ['format', 'function', 'proc format(dt: DateTime; f: string): string', 'Format DateTime to string'],
    ['parse', 'function', 'proc parse(input, fmt: string; zone = local()): DateTime', 'Parse DateTime from string'],
    ['parseTime', 'function', 'proc parseTime(input, fmt: string; zone: Timezone): Time', 'Parse Time from string'],
    ['inHours', 'function', 'proc inHours(d: Duration): int64', 'Duration in whole hours'],
    ['inMinutes', 'function', 'proc inMinutes(d: Duration): int64', 'Duration in whole minutes'],
    ['inSeconds', 'function', 'proc inSeconds(d: Duration): int64', 'Duration in whole seconds'],
    ['inMilliseconds', 'function', 'proc inMilliseconds(d: Duration): int64', 'Duration in whole ms'],
    ['inMicroseconds', 'function', 'proc inMicroseconds(d: Duration): int64', 'Duration in whole us'],
    ['inNanoseconds', 'function', 'proc inNanoseconds(d: Duration): int64', 'Duration in whole ns'],
    ['inDays', 'function', 'proc inDays(d: Duration): int64', 'Duration in whole days'],
    ['inWeeks', 'function', 'proc inWeeks(d: Duration): int64', 'Duration in whole weeks'],
    ['initDuration', 'function', 'proc initDuration(...): Duration', 'Construct Duration from parts'],
    ['initTime', 'function', 'proc initTime(unix: int64; nanosecond: NanosecondRange): Time', 'Construct Time'],
    ['initDateTime', 'function', 'proc initDateTime(monthday, month, year, hour, minute, second: int; zone = local()): DateTime', 'Construct DateTime'],
    ['initTimeInterval', 'function', 'proc initTimeInterval(...): TimeInterval', 'Construct TimeInterval'],
    ['toTime', 'function', 'proc toTime(dt: DateTime): Time', 'Convert DateTime to Time'],
    ['local', 'function', 'proc local(): Timezone', 'Local timezone'],
    ['utc', 'function', 'proc utc(): Timezone', 'UTC timezone'],
    ['convert', 'function', 'proc convert(src, dst: TimeUnit; quantity: int64): int64', 'Convert between time units'],
    ['toUnix', 'function', 'proc toUnix(t: Time): int64', 'Time as UNIX seconds'],
    ['fromUnix', 'function', 'proc fromUnix(unix: int64): Time', 'Time from UNIX seconds'],
    ['toUnixFloat', 'function', 'proc toUnixFloat(t: Time): float', 'Time as float UNIX seconds'],
    ['fromUnixFloat', 'function', 'proc fromUnixFloat(seconds: float): Time', 'Time from float UNIX seconds'],
    ['getDayOfWeek', 'function', 'proc getDayOfWeek(monthday, month, year: int): WeekDay', 'Weekday for a date'],
    ['getDayOfYear', 'function', 'proc getDayOfYear(monthday, month, year: int): YearDay', 'Day-of-year for a date'],
    ['getDaysInMonth', 'function', 'proc getDaysInMonth(month: Month; year: int): int', 'Days in given month'],
    ['getDaysInYear', 'function', 'proc getDaysInYear(year: int): int', 'Days in given year'],
    ['isLeapYear', 'function', 'proc isLeapYear(year: int): bool', 'Is year a leap year'],
    ['between', 'function', 'proc between(a, b: DateTime): TimeInterval', 'Calendar interval between dates'],
    ['dateTime', 'function', 'proc dateTime(year, month, day: int): DateTime', 'Convenient DateTime constructor'],
    ['hour', 'property', 'proc hour(dt: DateTime): HourRange', 'Hour-of-day component'],
    ['minute', 'property', 'proc minute(dt: DateTime): MinuteRange', 'Minute component'],
    ['second', 'property', 'proc second(dt: DateTime): SecondRange', 'Second component'],
    ['nanosecond', 'property', 'proc nanosecond(dt: DateTime): NanosecondRange', 'Nanosecond component'],
    ['monthday', 'property', 'proc monthday(dt: DateTime): MonthdayRange', 'Day of month'],
    ['month', 'property', 'proc month(dt: DateTime): Month', 'Month component'],
    ['year', 'property', 'proc year(dt: DateTime): int', 'Year component'],
    ['weekday', 'property', 'proc weekday(dt: DateTime): WeekDay', 'Day-of-week component'],
    ['yearday', 'property', 'proc yearday(dt: DateTime): YearDay', 'Day-of-year component'],
    ['monthdayZero', 'function', null, 'Zero-based day of month'],
    ['nanoseconds', 'function', 'proc nanoseconds(n: int64): Duration', 'Duration of n nanoseconds'],
    ['microseconds', 'function', 'proc microseconds(n: int64): Duration', 'Duration of n microseconds'],
    ['milliseconds', 'function', 'proc milliseconds(n: int64): Duration', 'Duration of n milliseconds'],
    ['seconds', 'function', 'proc seconds(n: int64): Duration', 'Duration of n seconds'],
    ['minutes', 'function', 'proc minutes(n: int64): Duration', 'Duration of n minutes'],
    ['hours', 'function', 'proc hours(n: int64): Duration', 'Duration of n hours'],
    ['days', 'function', 'proc days(n: int64): Duration', 'Duration of n days'],
    ['weeks', 'function', 'proc weeks(n: int64): Duration', 'Duration of n weeks'],
    ['years', 'function', 'proc years(n: int): TimeInterval', 'Calendar interval of n years'],
    ['months', 'function', 'proc months(n: int): TimeInterval', 'Calendar interval of n months'],
  ]);

  // ── macros module ───────────────────────────────────────────────────
  s.addBulk([
    ['macros', 'namespace', 'import macros', 'Compile-time AST manipulation'],
    ['NimNode', 'type', 'NimNode', 'Reference to a Nim AST node'],
    ['NimNodeKind', 'enum', null, 'Discriminant for NimNode kind'],
    ['NimSymKind', 'enum', null, 'Discriminant for symbol kind'],
    ['NimTypeKind', 'enum', null, 'Discriminant for type kind'],
    ['NimSym', 'type', null, 'Symbol AST node'],
    ['NimIdent', 'type', null, 'Identifier AST node'],
    ['getAst', 'function', 'macro getAst(call: untyped): NimNode', 'Materialise template as AST'],
    ['quote', 'function', 'macro quote(body: untyped): NimNode', 'Quasi-quote AST literal'],
    ['bindSym', 'function', 'proc bindSym(ident: string; rule = brClosed): NimNode', 'Resolve identifier to symbol'],
    ['genSym', 'function', 'proc genSym(kind: NimSymKind = nskLet; ident = ""): NimNode', 'Generate hygienic symbol'],
    ['newCall', 'function', 'proc newCall(theProc: NimNode; args: varargs[NimNode]): NimNode', 'Build call expression'],
    ['newLit', 'function', 'proc newLit[T](x: T): NimNode', 'Wrap a value as literal node'],
    ['newTree', 'function', 'proc newTree(kind: NimNodeKind; children: varargs[NimNode]): NimNode', 'Build node with children'],
    ['newStmtList', 'function', 'proc newStmtList(stmts: varargs[NimNode]): NimNode', 'Build a statement list'],
    ['newProc', 'function', 'proc newProc(name: NimNode; params: openArray[NimNode]; body: NimNode): NimNode', 'Build a proc def'],
    ['newIdentNode', 'function', 'proc newIdentNode(i: string): NimNode', 'Create identifier node'],
    ['newEmptyNode', 'function', 'proc newEmptyNode(): NimNode', 'Empty AST node'],
    ['newNimNode', 'function', 'proc newNimNode(kind: NimNodeKind): NimNode', 'Create blank node of kind'],
    ['newPar', 'function', 'proc newPar(): NimNode', 'Create parenthesised tuple'],
    ['newDotExpr', 'function', 'proc newDotExpr(a, b: NimNode): NimNode', 'Create a.b expression'],
    ['newColonExpr', 'function', 'proc newColonExpr(a, b: NimNode): NimNode', 'Create a:b expression'],
    ['newAssignment', 'function', 'proc newAssignment(lhs, rhs: NimNode): NimNode', 'Create lhs = rhs'],
    ['newIfStmt', 'function', 'proc newIfStmt(branches: varargs[(NimNode, NimNode)]): NimNode', 'Build if statement'],
    ['newBlockStmt', 'function', 'proc newBlockStmt(label: NimNode; body: NimNode): NimNode', 'Build labelled block'],
    ['newCommentStmtNode', 'function', 'proc newCommentStmtNode(comment: string): NimNode', 'Build comment statement'],
    ['newConstStmt', 'function', 'proc newConstStmt(name, value: NimNode): NimNode', 'Build const = value'],
    ['newLetStmt', 'function', 'proc newLetStmt(name, value: NimNode): NimNode', 'Build let = value'],
    ['newVarStmt', 'function', 'proc newVarStmt(name, value: NimNode): NimNode', 'Build var = value'],
    ['newNilLit', 'function', 'proc newNilLit(): NimNode', 'nil literal node'],
    ['newIntLitNode', 'function', 'proc newIntLitNode(i: BiggestInt): NimNode', 'Integer literal node'],
    ['newFloatLitNode', 'function', 'proc newFloatLitNode(f: BiggestFloat): NimNode', 'Float literal node'],
    ['newStrLitNode', 'function', 'proc newStrLitNode(s: string): NimNode', 'String literal node'],
    ['parseExpr', 'function', 'proc parseExpr(s: string): NimNode', 'Parse code as expression'],
    ['parseStmt', 'function', 'proc parseStmt(s: string): NimNode', 'Parse code as statement'],
    ['dumpTree', 'function', 'macro dumpTree(s: untyped)', 'Print AST at compile time'],
    ['dumpAstGen', 'function', 'macro dumpAstGen(s: untyped)', 'Print AST builder code'],
    ['treeRepr', 'function', 'proc treeRepr(n: NimNode): string', 'Tree-style AST repr'],
    ['lispRepr', 'function', 'proc lispRepr(n: NimNode): string', 'Lisp-style AST repr'],
    ['astGenRepr', 'function', 'proc astGenRepr(n: NimNode): string', 'AST-generator repr'],
    ['expectKind', 'function', 'proc expectKind(n: NimNode; kind: NimNodeKind)', 'Assert node kind, else error'],
    ['expectLen', 'function', 'proc expectLen(n: NimNode; len: int)', 'Assert child count'],
    ['expectMinLen', 'function', 'proc expectMinLen(n: NimNode; min: int)', 'Assert min child count'],
    ['expectIdent', 'function', 'proc expectIdent(n: NimNode; name: string)', 'Assert identifier name'],
    ['params', 'function', 'proc params(someProc: NimNode): NimNode', 'FormalParams of proc node'],
    ['body', 'function', 'proc body(someProc: NimNode): NimNode', 'Body subtree of proc'],
    ['name', 'function', 'proc name(someProc: NimNode): NimNode', 'Name of proc/iterator/etc.'],
    ['kind', 'function', 'proc kind(n: NimNode): NimNodeKind', 'Kind of an AST node'],
    ['signatureHash', 'function', 'proc signatureHash(n: NimNode): string', 'Stable signature hash'],
    ['sameType', 'function', 'proc sameType(a, b: NimNode): bool', 'Type equivalence test'],
    ['getType', 'function', 'proc getType(n: NimNode): NimNode', 'Compile-time type AST'],
    ['getTypeImpl', 'function', 'proc getTypeImpl(n: NimNode): NimNode', 'Type implementation AST'],
    ['getTypeInst', 'function', 'proc getTypeInst(n: NimNode): NimNode', 'Instantiated type AST'],
    ['getImpl', 'function', 'proc getImpl(s: NimNode): NimNode', 'Implementation AST of symbol'],
    ['strVal', 'function', 'proc strVal(n: NimNode): string', 'String value of literal/ident'],
    ['intVal', 'function', 'proc intVal(n: NimNode): BiggestInt', 'Int value of literal'],
    ['floatVal', 'function', 'proc floatVal(n: NimNode): BiggestFloat', 'Float value of literal'],
    ['symKind', 'function', 'proc symKind(s: NimNode): NimSymKind', 'Symbol kind of node'],
    ['error', 'function', 'proc error(msg: string; n: NimNode = nil)', 'Compile-time error'],
    ['warning', 'function', 'proc warning(msg: string; n: NimNode = nil)', 'Compile-time warning'],
    ['hint', 'function', 'proc hint(msg: string; n: NimNode = nil)', 'Compile-time hint'],
    ['copyNimNode', 'function', 'proc copyNimNode(n: NimNode): NimNode', 'Shallow copy of node'],
    ['copyNimTree', 'function', 'proc copyNimTree(n: NimNode): NimNode', 'Deep copy of subtree'],
    ['lineInfoObj', 'function', 'proc lineInfoObj(n: NimNode): LineInfo', 'Line info object for node'],
    ['lineInfo', 'function', 'proc lineInfo(n: NimNode): string', 'Source location string'],
    ['nnkProcDef', 'constant', 'NimNodeKind', 'Proc definition node kind'],
    ['nnkFuncDef', 'constant', 'NimNodeKind', 'Func definition node kind'],
    ['nnkMethodDef', 'constant', 'NimNodeKind', 'Method definition node kind'],
    ['nnkIteratorDef', 'constant', 'NimNodeKind', 'Iterator definition node kind'],
    ['nnkConverterDef', 'constant', 'NimNodeKind', 'Converter definition kind'],
    ['nnkTemplateDef', 'constant', 'NimNodeKind', 'Template definition kind'],
    ['nnkMacroDef', 'constant', 'NimNodeKind', 'Macro definition kind'],
    ['nnkVarSection', 'constant', 'NimNodeKind', 'var section kind'],
    ['nnkLetSection', 'constant', 'NimNodeKind', 'let section kind'],
    ['nnkConstSection', 'constant', 'NimNodeKind', 'const section kind'],
    ['nnkTypeSection', 'constant', 'NimNodeKind', 'type section kind'],
    ['nnkStmtList', 'constant', 'NimNodeKind', 'Statement list kind'],
    ['nnkInfix', 'constant', 'NimNodeKind', 'Infix expression kind'],
    ['nnkPrefix', 'constant', 'NimNodeKind', 'Prefix expression kind'],
    ['nnkPostfix', 'constant', 'NimNodeKind', 'Postfix expression kind (export marker)'],
    ['nnkCall', 'constant', 'NimNodeKind', 'Call expression kind'],
    ['nnkCommand', 'constant', 'NimNodeKind', 'Command-form call kind'],
    ['nnkBracketExpr', 'constant', 'NimNodeKind', 'a[b] expression kind'],
    ['nnkDotExpr', 'constant', 'NimNodeKind', 'a.b expression kind'],
    ['nnkPragmaExpr', 'constant', 'NimNodeKind', 'Pragma expression kind'],
    ['nnkPragma', 'constant', 'NimNodeKind', 'Pragma list kind'],
    ['nnkIdent', 'constant', 'NimNodeKind', 'Identifier kind'],
    ['nnkSym', 'constant', 'NimNodeKind', 'Symbol kind'],
    ['nnkAccQuoted', 'constant', 'NimNodeKind', 'Accent-quoted name kind'],
    ['nnkRecCase', 'constant', 'NimNodeKind', 'Object variant case kind'],
    ['nnkOfBranch', 'constant', 'NimNodeKind', 'case/of branch kind'],
    ['nnkElseBranch', 'constant', 'NimNodeKind', 'else branch kind'],
    ['nnkElifBranch', 'constant', 'NimNodeKind', 'elif branch kind'],
    ['nnkExceptBranch', 'constant', 'NimNodeKind', 'except branch kind'],
    ['nnkFinally', 'constant', 'NimNodeKind', 'finally clause kind'],
    ['nnkIfStmt', 'constant', 'NimNodeKind', 'if statement kind'],
    ['nnkCaseStmt', 'constant', 'NimNodeKind', 'case statement kind'],
    ['nnkWhenStmt', 'constant', 'NimNodeKind', 'when statement kind'],
    ['nnkWhileStmt', 'constant', 'NimNodeKind', 'while loop kind'],
    ['nnkForStmt', 'constant', 'NimNodeKind', 'for loop kind'],
    ['nnkBlockStmt', 'constant', 'NimNodeKind', 'block statement kind'],
    ['nnkAsgn', 'constant', 'NimNodeKind', 'Assignment kind'],
    ['nnkObjectTy', 'constant', 'NimNodeKind', 'object type kind'],
    ['nnkRefTy', 'constant', 'NimNodeKind', 'ref type kind'],
    ['nnkPtrTy', 'constant', 'NimNodeKind', 'ptr type kind'],
    ['nnkVarTy', 'constant', 'NimNodeKind', 'var T type kind'],
    ['nnkTupleTy', 'constant', 'NimNodeKind', 'tuple type kind'],
    ['nnkProcTy', 'constant', 'NimNodeKind', 'proc type kind'],
    ['nnkEnumTy', 'constant', 'NimNodeKind', 'enum type kind'],
    ['nnkDistinctTy', 'constant', 'NimNodeKind', 'distinct type kind'],
    ['nnkRecList', 'constant', 'NimNodeKind', 'Object record list kind'],
    ['nnkIdentDefs', 'constant', 'NimNodeKind', 'Identifier definitions kind'],
    ['nnkFormalParams', 'constant', 'NimNodeKind', 'Formal parameters kind'],
    ['nnkReturnStmt', 'constant', 'NimNodeKind', 'return statement kind'],
    ['nnkRaiseStmt', 'constant', 'NimNodeKind', 'raise statement kind'],
    ['nnkYieldStmt', 'constant', 'NimNodeKind', 'yield statement kind'],
    ['nnkDiscardStmt', 'constant', 'NimNodeKind', 'discard statement kind'],
    ['nnkContinueStmt', 'constant', 'NimNodeKind', 'continue statement kind'],
    ['nnkBreakStmt', 'constant', 'NimNodeKind', 'break statement kind'],
    ['nnkTryStmt', 'constant', 'NimNodeKind', 'try statement kind'],
    ['nnkImportStmt', 'constant', 'NimNodeKind', 'import statement kind'],
    ['nnkExportStmt', 'constant', 'NimNodeKind', 'export statement kind'],
    ['nnkIncludeStmt', 'constant', 'NimNodeKind', 'include statement kind'],
    ['nnkFromStmt', 'constant', 'NimNodeKind', 'from-import statement kind'],
    ['nnkLambda', 'constant', 'NimNodeKind', 'Anonymous proc lambda kind'],
    ['nnkDo', 'constant', 'NimNodeKind', 'do block kind'],
    ['nnkBracket', 'constant', 'NimNodeKind', 'Array/seq literal kind'],
    ['nnkCurly', 'constant', 'NimNodeKind', 'Set/curly literal kind'],
    ['nnkTupleConstr', 'constant', 'NimNodeKind', 'Tuple constructor kind'],
    ['nnkObjConstr', 'constant', 'NimNodeKind', 'Object constructor kind'],
    ['nnkRange', 'constant', 'NimNodeKind', 'a..b range kind'],
    ['nnkAddr', 'constant', 'NimNodeKind', 'addr expression kind'],
    ['nnkCast', 'constant', 'NimNodeKind', 'cast expression kind'],
    ['nnkNilLit', 'constant', 'NimNodeKind', 'nil literal kind'],
    ['nnkCharLit', 'constant', 'NimNodeKind', 'Char literal kind'],
    ['nnkIntLit', 'constant', 'NimNodeKind', 'Int literal kind'],
    ['nnkFloatLit', 'constant', 'NimNodeKind', 'Float literal kind'],
    ['nnkStrLit', 'constant', 'NimNodeKind', 'String literal kind'],
    ['nnkRStrLit', 'constant', 'NimNodeKind', 'Raw string literal kind'],
    ['nnkTripleStrLit', 'constant', 'NimNodeKind', 'Triple-quoted string kind'],
    ['nnkCommentStmt', 'constant', 'NimNodeKind', 'Doc-comment statement kind'],
    ['nnkEmpty', 'constant', 'NimNodeKind', 'Empty / placeholder kind'],
  ]);

  // ── pragmas (as keyword type) ──────────────────────────────────────
  s.addBulk([
    ['{.compileTime.}', 'keyword', 'pragma', 'Mark proc/var as compile-time-only'],
    ['{.cdecl.}', 'keyword', 'pragma', 'C calling convention'],
    ['{.stdcall.}', 'keyword', 'pragma', 'stdcall calling convention'],
    ['{.fastcall.}', 'keyword', 'pragma', 'fastcall calling convention'],
    ['{.thiscall.}', 'keyword', 'pragma', 'thiscall (C++) calling convention'],
    ['{.syscall.}', 'keyword', 'pragma', 'OS syscall calling convention'],
    ['{.noconv.}', 'keyword', 'pragma', 'No specific calling convention'],
    ['{.closure.}', 'keyword', 'pragma', 'Closure calling convention'],
    ['{.nimcall.}', 'keyword', 'pragma', 'Nim default calling convention'],
    ['{.noSideEffect.}', 'keyword', 'pragma', 'Mark proc as side-effect free'],
    ['{.exportc.}', 'keyword', 'pragma', 'Export symbol with C name'],
    ['{.importc.}', 'keyword', 'pragma', 'Import symbol from C'],
    ['{.importcpp.}', 'keyword', 'pragma', 'Import symbol from C++'],
    ['{.importjs.}', 'keyword', 'pragma', 'Import symbol from JS'],
    ['{.exportcpp.}', 'keyword', 'pragma', 'Export symbol with C++ name'],
    ['{.exportjs.}', 'keyword', 'pragma', 'Export symbol to JS'],
    ['{.pure.}', 'keyword', 'pragma', 'Pure object/enum (no inheritance)'],
    ['{.borrow.}', 'keyword', 'pragma', 'Borrow proc from underlying type'],
    ['{.async.}', 'keyword', 'pragma', 'Mark proc as asynchronous'],
    ['{.gcsafe.}', 'keyword', 'pragma', 'Asserts GC safety'],
    ['{.inline.}', 'keyword', 'pragma', 'Inline this proc'],
    ['{.noinline.}', 'keyword', 'pragma', 'Never inline this proc'],
    ['{.deprecated.}', 'keyword', 'pragma', 'Emit deprecation warning'],
    ['{.experimental.}', 'keyword', 'pragma', 'Enable experimental feature'],
    ['{.error.}', 'keyword', 'pragma', 'Compile-time error if reached'],
    ['{.warning.}', 'keyword', 'pragma', 'Emit a compile-time warning'],
    ['{.hint.}', 'keyword', 'pragma', 'Emit a compile-time hint'],
    ['{.discardable.}', 'keyword', 'pragma', 'Result may be silently discarded'],
    ['{.raises: [].}', 'keyword', 'pragma', 'Declare exception specification'],
    ['{.tags: [].}', 'keyword', 'pragma', 'Declare effect tags'],
    ['{.locks: 0.}', 'keyword', 'pragma', 'Declare lock level'],
    ['{.bycopy.}', 'keyword', 'pragma', 'Pass by copy on FFI boundary'],
    ['{.byref.}', 'keyword', 'pragma', 'Pass by reference on FFI boundary'],
    ['{.acyclic.}', 'keyword', 'pragma', 'Type is acyclic for cycle collector'],
    ['{.shallow.}', 'keyword', 'pragma', 'Use shallow assignment for type'],
    ['{.noinit.}', 'keyword', 'pragma', 'Skip default initialisation'],
    ['{.requiresInit.}', 'keyword', 'pragma', 'All fields must be initialised'],
    ['{.dynlib.}', 'keyword', 'pragma', 'Load symbol from dynamic library'],
    ['{.header.}', 'keyword', 'pragma', 'Include C/C++ header'],
    ['{.emit.}', 'keyword', 'pragma', 'Inline emit C/C++ code'],
    ['{.link.}', 'keyword', 'pragma', 'Link against object/library file'],
    ['{.passC.}', 'keyword', 'pragma', 'Pass flag to C compiler'],
    ['{.passL.}', 'keyword', 'pragma', 'Pass flag to linker'],
    ['{.checks: off.}', 'keyword', 'pragma', 'Disable all runtime checks'],
    ['{.boundChecks: off.}', 'keyword', 'pragma', 'Disable bound checks'],
    ['{.overflowChecks: off.}', 'keyword', 'pragma', 'Disable overflow checks'],
    ['{.assertions: off.}', 'keyword', 'pragma', 'Disable assertions'],
    ['{.linearScanEnd.}', 'keyword', 'pragma', 'Hint for case linear-scan jump table'],
    ['{.computedGoto.}', 'keyword', 'pragma', 'Hint for computed-goto codegen'],
    ['{.threadvar.}', 'keyword', 'pragma', 'Thread-local variable'],
    ['{.global.}', 'keyword', 'pragma', 'Treat var inside template as global'],
    ['{.locks.}', 'keyword', 'pragma', 'Lock-level annotation'],
    ['{.guard.}', 'keyword', 'pragma', 'Guard a field with a lock'],
    ['{.volatile.}', 'keyword', 'pragma', 'Mark variable as volatile'],
    ['{.register.}', 'keyword', 'pragma', 'Hint to keep variable in register'],
    ['{.codegenDecl.}', 'keyword', 'pragma', 'Custom codegen declaration template'],
    ['{.size: 4.}', 'keyword', 'pragma', 'Set object/enum byte size'],
    ['{.packed.}', 'keyword', 'pragma', 'Pack object fields without padding'],
    ['{.union.}', 'keyword', 'pragma', 'C union representation'],
    ['{.final.}', 'keyword', 'pragma', 'Final type (no inheritance)'],
    ['{.injectStmt.}', 'keyword', 'pragma', 'Inject statement at module top'],
    ['{.used.}', 'keyword', 'pragma', 'Suppress "unused" warning'],
    ['{.unused.}', 'keyword', 'pragma', 'Mark symbol as unused'],
    ['{.hint[XDeclaredButNotUsed]: off.}', 'keyword', 'pragma', 'Disable specific hint'],
  ]);

  return s.toArray();
}
