// OCaml completion data — targets >= 2,000 unique entries.
import { EntrySet, members } from './helpers.mjs';

export function buildOCaml() {
  const s = new EntrySet('ocaml');

  // Keywords
  s.addBulk([
    ['let', 'keyword', null, 'Let binding'],
    ['rec', 'keyword', null, 'Recursive binding modifier'],
    ['and', 'keyword', null, 'Mutually recursive binding / type'],
    ['in', 'keyword', null, 'Body of a let binding'],
    ['fun', 'keyword', null, 'Anonymous function (lambda)'],
    ['function', 'keyword', null, 'Pattern-matching anonymous function'],
    ['match', 'keyword', null, 'Pattern match expression'],
    ['with', 'keyword', null, 'Match alternatives / try handler'],
    ['when', 'keyword', null, 'Pattern guard clause'],
    ['if', 'keyword', null, 'Conditional expression'],
    ['then', 'keyword', null, 'Then branch of conditional'],
    ['else', 'keyword', null, 'Else branch of conditional'],
    ['begin', 'keyword', null, 'Begin block (synonym for parens)'],
    ['end', 'keyword', null, 'End of block / module / object'],
    ['module', 'keyword', null, 'Module declaration'],
    ['module type', 'keyword', null, 'Module-type declaration'],
    ['struct', 'keyword', null, 'Module structure body'],
    ['sig', 'keyword', null, 'Module signature body'],
    ['functor', 'keyword', null, 'Parameterised module'],
    ['include', 'keyword', null, 'Include another module'],
    ['open', 'keyword', null, 'Open a module into scope'],
    ['type', 'keyword', null, 'Type definition'],
    ['of', 'keyword', null, 'Constructor argument introducer'],
    ['as', 'keyword', null, 'Pattern alias / module ascription'],
    ['constraint', 'keyword', null, 'Type-equality constraint'],
    ['mutable', 'keyword', null, 'Mutable record field'],
    ['exception', 'keyword', null, 'Exception declaration'],
    ['raise', 'keyword', null, 'Raise an exception'],
    ['raise_notrace', 'keyword', null, 'Raise without backtrace'],
    ['try', 'keyword', null, 'Try expression'],
    ['assert', 'keyword', null, 'Runtime assertion'],
    ['lazy', 'keyword', null, 'Lazy thunk introducer'],
    ['class', 'keyword', null, 'OO class declaration'],
    ['object', 'keyword', null, 'Immediate object expression'],
    ['method', 'keyword', null, 'Object method declaration'],
    ['inherit', 'keyword', null, 'Class inheritance'],
    ['initializer', 'keyword', null, 'Class initialiser'],
    ['virtual', 'keyword', null, 'Virtual method/class member'],
    ['private', 'keyword', null, 'Private method visibility'],
    ['val', 'keyword', null, 'Value/instance variable'],
    ['new', 'keyword', null, 'Instantiate an object'],
    ['do', 'keyword', null, 'Body of a for/while loop'],
    ['done', 'keyword', null, 'End of for/while loop'],
    ['for', 'keyword', null, 'For loop'],
    ['to', 'keyword', null, 'Ascending for-loop bound'],
    ['downto', 'keyword', null, 'Descending for-loop bound'],
    ['while', 'keyword', null, 'While loop'],
    ['external', 'keyword', null, 'External (FFI) value declaration'],
    ['nonrec', 'keyword', null, 'Non-recursive type/let'],
    ['true', 'keyword', null, 'Boolean true'],
    ['false', 'keyword', null, 'Boolean false'],
    ['or', 'keyword', null, 'Logical or (deprecated, use ||)'],
    ['not', 'keyword', null, 'Boolean negation'],
    ['land', 'keyword', null, 'Bitwise and'],
    ['lor', 'keyword', null, 'Bitwise or'],
    ['lxor', 'keyword', null, 'Bitwise xor'],
    ['lnot', 'keyword', null, 'Bitwise not'],
    ['lsl', 'keyword', null, 'Logical shift left'],
    ['lsr', 'keyword', null, 'Logical shift right'],
    ['asr', 'keyword', null, 'Arithmetic shift right'],
    ['mod', 'keyword', null, 'Integer modulo'],
    ['effect', 'keyword', null, 'Effect declaration (OCaml 5)'],
    ['method!', 'keyword', null, 'Method override marker'],
    ['inherit!', 'keyword', null, 'Inheritance override marker'],
    ['val!', 'keyword', null, 'Instance variable override marker'],
    ['module rec', 'keyword', null, 'Recursive module group'],
    ['let%lwt', 'keyword', null, 'Lwt monadic bind sugar'],
    ['let%map', 'keyword', null, 'ppx_let map sugar'],
    ['let%bind', 'keyword', null, 'ppx_let bind sugar'],
    ['let*', 'keyword', null, 'Binding operator (monadic bind)'],
    ['let+', 'keyword', null, 'Binding operator (functor map)'],
    ['and*', 'keyword', null, 'Parallel binding operator'],
    ['and+', 'keyword', null, 'Parallel functor binding'],
    ['_', 'keyword', null, 'Wildcard pattern'],
    ['__LOC__', 'keyword', 'string', 'Caller source location'],
    ['__FILE__', 'keyword', 'string', 'Source file name'],
    ['__LINE__', 'keyword', 'int', 'Source line number'],
    ['__MODULE__', 'keyword', 'string', 'Module name'],
    ['__POS__', 'keyword', '(string * int * int * int)', 'File / line / cnum / enum'],
    ['__FUNCTION__', 'keyword', 'string', 'Enclosing function name'],
    ['__LOC_OF__', 'keyword', null, 'Location of an expression'],
    ['__LINE_OF__', 'keyword', null, 'Line number of an expression'],
    ['__POS_OF__', 'keyword', null, 'Position of an expression'],
  ]);

  // Operators
  s.addBulk([
    ['|>', 'keyword', "'a -> ('a -> 'b) -> 'b", 'Forward pipe operator'],
    ['@@', 'keyword', "('a -> 'b) -> 'a -> 'b", 'Application operator (low prec)'],
    ['::', 'keyword', "'a -> 'a list -> 'a list", 'List cons constructor'],
    ['@', 'keyword', "'a list -> 'a list -> 'a list", 'List concatenation'],
    ['^', 'keyword', 'string -> string -> string', 'String concatenation'],
    ['^^', 'keyword', null, 'Format-string concatenation'],
    ['=', 'keyword', "'a -> 'a -> bool", 'Structural equality'],
    ['==', 'keyword', "'a -> 'a -> bool", 'Physical equality'],
    ['!=', 'keyword', "'a -> 'a -> bool", 'Physical inequality'],
    ['<>', 'keyword', "'a -> 'a -> bool", 'Structural inequality'],
    ['&&', 'keyword', 'bool -> bool -> bool', 'Short-circuit and'],
    ['||', 'keyword', 'bool -> bool -> bool', 'Short-circuit or'],
    ['<-', 'keyword', null, 'Mutation / record-field assignment'],
    [':=', 'keyword', "'a ref -> 'a -> unit", 'Reference assignment'],
    ['!', 'keyword', "'a ref -> 'a", 'Dereference operator'],
    ['?', 'keyword', null, 'Optional argument introducer'],
    ['~', 'keyword', null, 'Labelled argument introducer'],
    ['*', 'keyword', 'int -> int -> int', 'Integer multiplication'],
    ['**', 'keyword', 'float -> float -> float', 'Float power'],
    ['*.', 'keyword', 'float -> float -> float', 'Float multiplication'],
    ['+.', 'keyword', 'float -> float -> float', 'Float addition'],
    ['-.', 'keyword', 'float -> float -> float', 'Float subtraction'],
    ['/.', 'keyword', 'float -> float -> float', 'Float division'],
    ['+', 'keyword', 'int -> int -> int', 'Integer addition'],
    ['-', 'keyword', 'int -> int -> int', 'Integer subtraction'],
    ['/', 'keyword', 'int -> int -> int', 'Integer division'],
    ['<', 'keyword', null, 'Less than'],
    ['>', 'keyword', null, 'Greater than'],
    ['<=', 'keyword', null, 'Less than or equal'],
    ['>=', 'keyword', null, 'Greater than or equal'],
    ['->', 'keyword', null, 'Function arrow'],
    ['|', 'keyword', null, 'Pattern alternative / variant separator'],
    ['#', 'keyword', null, 'Method/object call'],
    ['..', 'keyword', null, 'Open polymorphic variant marker'],
    [';;', 'keyword', null, 'Toplevel phrase terminator'],
    [';', 'keyword', null, 'Sequence operator'],
    [':', 'keyword', null, 'Type annotation'],
    [':>', 'keyword', null, 'Subtype coercion'],
    ['>>=', 'keyword', null, 'Lwt/Result monadic bind'],
    ['>|=', 'keyword', null, 'Lwt functor map'],
    ['>>|', 'keyword', null, 'Async map'],
    ['>>>', 'keyword', null, 'Async sequencing'],
    ['<*>', 'keyword', null, 'Applicative apply'],
    ['<$>', 'keyword', null, 'Functor map (custom)'],
    ['+!', 'keyword', null, 'Custom user operator slot'],
    ['-!', 'keyword', null, 'Custom user operator slot'],
    ['*!', 'keyword', null, 'Custom user operator slot'],
    ['/!', 'keyword', null, 'Custom user operator slot'],
    ['||.', 'keyword', null, 'User-defined chained or'],
    ['&&.', 'keyword', null, 'User-defined chained and'],
    ['?+', 'keyword', null, 'Custom optional operator slot'],
  ]);

  // Prelude types
  s.addBulk([
    ['int', 'type', null, '63/31-bit native integer'],
    ['float', 'type', null, '64-bit IEEE float'],
    ['bool', 'type', null, 'true | false'],
    ['string', 'type', null, 'Immutable byte sequence'],
    ['bytes', 'type', null, 'Mutable byte sequence'],
    ['char', 'type', null, '8-bit character'],
    ['unit', 'type', null, '() singleton type'],
    ['list', 'type', "'a list", 'Immutable singly-linked list'],
    ['array', 'type', "'a array", 'Mutable contiguous array'],
    ['option', 'type', "'a option", 'None | Some of x'],
    ['result', 'type', "('a, 'b) result", 'Ok or Error'],
    ['ref', 'type', "'a ref", 'Single-cell mutable reference'],
    ['lazy_t', 'type', "'a lazy_t", 'Lazy thunk'],
    ['Seq.t', 'type', "'a Seq.t", 'Standard library lazy sequence'],
    ['int32', 'type', null, '32-bit signed integer'],
    ['int64', 'type', null, '64-bit signed integer'],
    ['nativeint', 'type', null, 'Word-sized signed integer'],
    ['exn', 'type', null, 'Exception type'],
    ['format', 'type', null, 'Format string for Printf'],
    ['format4', 'type', null, '4-parameter format'],
    ['format6', 'type', null, '6-parameter format (most common)'],
    ['in_channel', 'type', null, 'Input channel handle'],
    ['out_channel', 'type', null, 'Output channel handle'],
    ['Buffer.t', 'type', null, 'Resizable byte buffer'],
    ['Hashtbl.t', 'type', "('a, 'b) Hashtbl.t", 'Mutable hash table'],
    ['Queue.t', 'type', "'a Queue.t", 'FIFO queue'],
    ['Stack.t', 'type', "'a Stack.t", 'LIFO stack'],
    ['Set.t', 'type', null, 'Functorised immutable set'],
    ['Map.t', 'type', null, 'Functorised immutable map'],
    ['Bigarray.Array1.t', 'type', null, '1-D bigarray'],
    ['Bigarray.Array2.t', 'type', null, '2-D bigarray'],
    ['Bigarray.Array3.t', 'type', null, '3-D bigarray'],
    ['Atomic.t', 'type', "'a Atomic.t", 'Atomic reference (5.0+)'],
    ['Effect.t', 'type', "('a, 'b) Effect.t", 'Effect handler type (5.0+)'],
    ['Domain.t', 'type', "'a Domain.t", 'OS-level parallel domain'],
    ['Mutex.t', 'type', null, 'Threading mutex'],
    ['Condition.t', 'type', null, 'Threading condition variable'],
    ['Semaphore.Counting.t', 'type', null, 'Counting semaphore'],
    ['Semaphore.Binary.t', 'type', null, 'Binary semaphore'],
    ['Lazy.t', 'type', "'a Lazy.t", 'Equivalent of lazy_t'],
    ['Unix.file_descr', 'type', null, 'Unix file descriptor'],
    ['Unix.sockaddr', 'type', null, 'Socket address'],
    ['Unix.error', 'type', null, 'Unix error code'],
    ['Unix.tm', 'type', null, 'Decoded calendar time'],
    ['Format.formatter', 'type', null, 'Pretty-print formatter'],
    ['Scanf.Scanning.in_channel', 'type', null, 'Scanf input channel'],
    ['Scanf.scanbuf', 'type', null, 'Scanf scanning buffer'],
    ['Random.State.t', 'type', null, 'Independent PRNG state'],
    ['Digest.t', 'type', null, 'MD5 digest'],
    ['Marshal.extern_flags', 'type', null, 'Marshal output flag'],
    ['Sys.signal_behavior', 'type', null, 'Signal disposition'],
    ['Sys.backend_type', 'type', null, 'Native | Bytecode | Other'],
    ['Bytes.t', 'type', null, 'Alias of bytes'],
    ['String.t', 'type', null, 'Alias of string'],
    ['Int.t', 'type', null, 'Alias of int (Int module)'],
    ['Float.t', 'type', null, 'Alias of float (Float module)'],
    ['Bool.t', 'type', null, 'Alias of bool (Bool module)'],
    ['Char.t', 'type', null, 'Alias of char (Char module)'],
    ['Either.t', 'type', "('a, 'b) Either.t", 'Left | Right tagged union'],
    ['Fun.t', 'type', null, 'Function combinators'],
    ['Uchar.t', 'type', null, 'Unicode scalar value'],
    ['Int32.t', 'type', null, '32-bit signed integer'],
    ['Int64.t', 'type', null, '64-bit signed integer'],
    ['Nativeint.t', 'type', null, 'Word-sized signed integer'],
    ['Complex.t', 'type', null, 'Record with re and im fields'],
    ['Continuation.t', 'type', null, 'Effect continuation'],
    ['Domain.id', 'type', null, 'Unique domain identifier'],
    ['Printexc.raw_backtrace', 'type', null, 'Raw exception backtrace'],
    ['Printexc.location', 'type', null, 'Backtrace slot location'],
    ['Weak.t', 'type', "'a Weak.t", 'Weak pointer array'],
    ['Ephemeron.K1.t', 'type', null, '1-key ephemeron'],
    ['Ephemeron.K2.t', 'type', null, '2-key ephemeron'],
    ['CamlinternalLazy.t', 'type', null, 'Internal lazy representation'],
    ['Lwt.t', 'type', "'a Lwt.t", 'Lwt promise'],
    ['Yojson.Safe.t', 'type', null, 'Yojson safe JSON value'],
    ['Yojson.Basic.t', 'type', null, 'Yojson basic JSON value'],
    ['Z.t', 'type', null, 'Zarith arbitrary-precision int'],
    ['Q.t', 'type', null, 'Zarith arbitrary-precision rational'],
    ['Re.t', 'type', null, 'Compiled regex (Re library)'],
    ['Re.re', 'type', null, 'Re compiled pattern'],
    ['Mtime.t', 'type', null, 'Monotonic clock timestamp'],
    ['Mtime.span', 'type', null, 'Monotonic clock duration'],
    ['Cohttp.Request.t', 'type', null, 'HTTP request value'],
    ['Cohttp.Response.t', 'type', null, 'HTTP response value'],
  ]);

  // Built-in constructors
  s.addBulk([
    ['None', 'constant', "'a option", 'Empty option'],
    ['Some', 'class', "'a -> 'a option", 'Wrap value in option'],
    ['Ok', 'class', "'a -> ('a, _) result", 'Successful result'],
    ['Error', 'class', "'b -> (_, 'b) result", 'Failed result'],
    ['Left', 'class', "'a -> ('a, _) Either.t", 'Either left'],
    ['Right', 'class', "'b -> (_, 'b) Either.t", 'Either right'],
    ['Nil', 'constant', null, 'Common variant constructor name'],
    ['Cons', 'class', null, 'Common variant constructor name'],
    ['()', 'constant', 'unit', 'Unit value'],
    ['[]', 'constant', "'a list", 'Empty list'],
    ['[||]', 'constant', "'a array", 'Empty array'],
    ['Match_failure', 'class', null, 'Built-in: pattern match failed'],
    ['Assert_failure', 'class', null, 'Built-in: assertion failed'],
    ['Invalid_argument', 'class', null, 'Built-in: bad argument'],
    ['Failure', 'class', null, 'Built-in: failure with message'],
    ['Not_found', 'constant', null, 'Built-in: lookup failed'],
    ['Out_of_memory', 'constant', null, 'Built-in: heap exhausted'],
    ['Stack_overflow', 'constant', null, 'Built-in: native stack overflow'],
    ['Sys_error', 'class', null, 'Built-in: system / I/O error'],
    ['End_of_file', 'constant', null, 'Built-in: EOF reached'],
    ['Division_by_zero', 'constant', null, 'Built-in: divide by zero'],
    ['Sys_blocked_io', 'constant', null, 'Built-in: would block'],
    ['Undefined_recursive_module', 'class', null, 'Built-in: forward ref'],
    ['Continue_with', 'class', null, 'Effect continuation tag'],
    ['Discontinue_with', 'class', null, 'Effect discontinue tag'],
    ['Exit', 'constant', null, 'Stdlib generic exit exception'],
    ['Empty', 'constant', null, 'Common empty constructor (Queue/Stack)'],
    ['Seq.Nil', 'constant', "'a Seq.node", 'Empty sequence node'],
    ['Seq.Cons', 'class', null, 'Sequence cons node'],
  ]);

  // Pervasives / Stdlib top-level functions
  const pervasiveFns = [
    ['print_string', 'string -> unit', 'Print a string to stdout'],
    ['print_endline', 'string -> unit', 'Print a string + newline'],
    ['print_int', 'int -> unit', 'Print an integer'],
    ['print_float', 'float -> unit', 'Print a float'],
    ['print_char', 'char -> unit', 'Print a single character'],
    ['print_bytes', 'bytes -> unit', 'Print mutable bytes'],
    ['print_newline', 'unit -> unit', 'Print a newline + flush'],
    ['prerr_string', 'string -> unit', 'Print to stderr'],
    ['prerr_endline', 'string -> unit', 'Print to stderr + newline'],
    ['prerr_int', 'int -> unit', 'Print integer to stderr'],
    ['prerr_float', 'float -> unit', 'Print float to stderr'],
    ['prerr_char', 'char -> unit', 'Print char to stderr'],
    ['prerr_bytes', 'bytes -> unit', 'Print bytes to stderr'],
    ['prerr_newline', 'unit -> unit', 'Newline + flush stderr'],
    ['read_line', 'unit -> string', 'Read a line from stdin'],
    ['read_int', 'unit -> int', 'Read int from stdin'],
    ['read_int_opt', 'unit -> int option', 'Read int (optional)'],
    ['read_float', 'unit -> float', 'Read float from stdin'],
    ['read_float_opt', 'unit -> float option', 'Read float (optional)'],
    ['min', "'a -> 'a -> 'a", 'Lesser of two'],
    ['max', "'a -> 'a -> 'a", 'Greater of two'],
    ['abs', 'int -> int', 'Absolute value (int)'],
    ['abs_float', 'float -> float', 'Absolute value (float)'],
    ['succ', 'int -> int', 'Successor of an int'],
    ['pred', 'int -> int', 'Predecessor of an int'],
    ['compare', "'a -> 'a -> int", 'Polymorphic compare'],
    ['ignore', "'a -> unit", 'Discard value, unit return'],
    ['failwith', "string -> 'a", 'Raise Failure with message'],
    ['invalid_arg', "string -> 'a", 'Raise Invalid_argument'],
    ['string_of_int', 'int -> string', 'Convert int to string'],
    ['int_of_string', 'string -> int', 'Parse int (raises)'],
    ['int_of_string_opt', 'string -> int option', 'Parse int (option)'],
    ['float_of_int', 'int -> float', 'Widen int to float'],
    ['int_of_float', 'float -> int', 'Truncate float to int'],
    ['string_of_float', 'float -> string', 'Convert float to string'],
    ['float_of_string', 'string -> float', 'Parse float (raises)'],
    ['float_of_string_opt', 'string -> float option', 'Parse float (option)'],
    ['string_of_bool', 'bool -> string', 'Convert bool to string'],
    ['bool_of_string', 'string -> bool', 'Parse bool (raises)'],
    ['bool_of_string_opt', 'string -> bool option', 'Parse bool (option)'],
    ['char_of_int', 'int -> char', 'Code-point to char (raises)'],
    ['int_of_char', 'char -> int', 'Char code-point'],
    ['truncate', 'float -> int', 'Truncate float toward zero'],
    ['mod_float', 'float -> float -> float', 'Float modulo'],
    ['ceil', 'float -> float', 'Ceiling'],
    ['floor', 'float -> float', 'Floor'],
    ['sqrt', 'float -> float', 'Square root'],
    ['exp', 'float -> float', 'Exponential'],
    ['log', 'float -> float', 'Natural logarithm'],
    ['log10', 'float -> float', 'Base-10 logarithm'],
    ['log2', 'float -> float', 'Base-2 logarithm'],
    ['expm1', 'float -> float', 'exp x - 1'],
    ['log1p', 'float -> float', 'log (1+x)'],
    ['sin', 'float -> float', 'Sine'],
    ['cos', 'float -> float', 'Cosine'],
    ['tan', 'float -> float', 'Tangent'],
    ['asin', 'float -> float', 'Arcsine'],
    ['acos', 'float -> float', 'Arccosine'],
    ['atan', 'float -> float', 'Arctangent'],
    ['atan2', 'float -> float -> float', 'Two-argument arctangent'],
    ['hypot', 'float -> float -> float', 'Pythagorean magnitude'],
    ['cosh', 'float -> float', 'Hyperbolic cosine'],
    ['sinh', 'float -> float', 'Hyperbolic sine'],
    ['tanh', 'float -> float', 'Hyperbolic tangent'],
    ['acosh', 'float -> float', 'Inverse hyperbolic cosine'],
    ['asinh', 'float -> float', 'Inverse hyperbolic sine'],
    ['atanh', 'float -> float', 'Inverse hyperbolic tangent'],
    ['ldexp', 'float -> int -> float', 'x * 2^n'],
    ['frexp', 'float -> float * int', 'Split mantissa / exponent'],
    ['modf', 'float -> float * float', 'Split frac and integer parts'],
    ['classify_float', 'float -> fpclass', 'Classify a float value'],
    ['copysign', 'float -> float -> float', 'Copy sign of second to first'],
    ['nan', 'float', 'NaN constant'],
    ['infinity', 'float', '+infinity constant'],
    ['neg_infinity', 'float', '-infinity constant'],
    ['max_float', 'float', 'Largest finite float'],
    ['min_float', 'float', 'Smallest positive float'],
    ['epsilon_float', 'float', '1 ulp around 1.0'],
    ['max_int', 'int', 'Largest int'],
    ['min_int', 'int', 'Smallest int'],
    ['stdin', 'in_channel', 'Standard input channel'],
    ['stdout', 'out_channel', 'Standard output channel'],
    ['stderr', 'out_channel', 'Standard error channel'],
    ['flush', 'out_channel -> unit', 'Flush an output channel'],
    ['flush_all', 'unit -> unit', 'Flush every output channel'],
    ['output_string', 'out_channel -> string -> unit', 'Write string to channel'],
    ['output_char', 'out_channel -> char -> unit', 'Write char to channel'],
    ['output_bytes', 'out_channel -> bytes -> unit', 'Write bytes to channel'],
    ['output_substring', 'out_channel -> string -> int -> int -> unit', 'Write substring'],
    ['output_value', "out_channel -> 'a -> unit", 'Marshal value to channel'],
    ['output_binary_int', 'out_channel -> int -> unit', 'Write 32-bit big-endian int'],
    ['output', null, 'Generic output for bytes/string'],
    ['input_line', 'in_channel -> string', 'Read a line (raises EOF)'],
    ['input_char', 'in_channel -> char', 'Read one character'],
    ['input_byte', 'in_channel -> int', 'Read one byte'],
    ['input_value', "in_channel -> 'a", 'Unmarshal value (unsafe)'],
    ['input_binary_int', 'in_channel -> int', 'Read 32-bit big-endian int'],
    ['really_input', 'in_channel -> bytes -> int -> int -> unit', 'Read exactly n bytes'],
    ['really_input_string', 'in_channel -> int -> string', 'Read exactly n bytes (string)'],
    ['close_in', 'in_channel -> unit', 'Close an in_channel'],
    ['close_in_noerr', 'in_channel -> unit', 'Close ignoring errors'],
    ['close_out', 'out_channel -> unit', 'Close an out_channel'],
    ['close_out_noerr', 'out_channel -> unit', 'Close ignoring errors'],
    ['open_in', 'string -> in_channel', 'Open file for reading'],
    ['open_in_bin', 'string -> in_channel', 'Open binary file for reading'],
    ['open_in_gen', 'open_flag list -> int -> string -> in_channel', 'Open with flags'],
    ['open_out', 'string -> out_channel', 'Open file for writing'],
    ['open_out_bin', 'string -> out_channel', 'Open binary file for writing'],
    ['open_out_gen', 'open_flag list -> int -> string -> out_channel', 'Open with flags'],
    ['seek_in', 'in_channel -> int -> unit', 'Seek in input channel'],
    ['seek_out', 'out_channel -> int -> unit', 'Seek in output channel'],
    ['pos_in', 'in_channel -> int', 'Current position in input'],
    ['pos_out', 'out_channel -> int', 'Current position in output'],
    ['in_channel_length', 'in_channel -> int', 'Length of input channel'],
    ['out_channel_length', 'out_channel -> int', 'Length of output channel'],
    ['set_binary_mode_in', 'in_channel -> bool -> unit', 'Toggle binary mode'],
    ['set_binary_mode_out', 'out_channel -> bool -> unit', 'Toggle binary mode'],
    ['decr', 'int ref -> unit', 'Decrement an int ref'],
    ['incr', 'int ref -> unit', 'Increment an int ref'],
    ['fst', "'a * 'b -> 'a", 'First of a pair'],
    ['snd', "'a * 'b -> 'b", 'Second of a pair'],
    ['at_exit', '(unit -> unit) -> unit', 'Register exit hook'],
    ['exit', "int -> 'a", 'Terminate process'],
    ['do_at_exit', 'unit -> unit', 'Run registered exit hooks'],
    ['format_of_string', null, 'Convert string to format'],
    ['string_of_format', null, 'Convert format to string'],
    ['Lazy.force', "'a Lazy.t -> 'a", 'Force a lazy value'],
    ['Lazy.is_val', "'a Lazy.t -> bool", 'Has lazy been forced?'],
    ['Lazy.from_val', "'a -> 'a Lazy.t", 'Already-forced lazy'],
    ['Lazy.from_fun', "(unit -> 'a) -> 'a Lazy.t", 'Wrap thunk as lazy'],
    ['Lazy.map', "('a -> 'b) -> 'a Lazy.t -> 'b Lazy.t", 'Map a lazy value'],
    ['Lazy.map_val', null, 'Map already forced lazy'],
  ];
  s.addBulk(pervasiveFns.map(([l, d, i]) => [l, 'function', d, i]));

  // List module
  const listFns = [
    ['length', "'a list -> int", 'Length of list'],
    ['compare_lengths', "'a list -> 'b list -> int", 'Compare list lengths'],
    ['compare_length_with', "'a list -> int -> int", 'Compare length to int'],
    ['cons', "'a -> 'a list -> 'a list", 'Cons element to head'],
    ['hd', "'a list -> 'a", 'Head (raises if empty)'],
    ['tl', "'a list -> 'a list", 'Tail (raises if empty)'],
    ['nth', "'a list -> int -> 'a", 'nth element (raises)'],
    ['nth_opt', "'a list -> int -> 'a option", 'nth element (option)'],
    ['rev', "'a list -> 'a list", 'Reverse a list'],
    ['init', "int -> (int -> 'a) -> 'a list", 'Build list from index fn'],
    ['append', "'a list -> 'a list -> 'a list", 'Concatenate two lists'],
    ['rev_append', "'a list -> 'a list -> 'a list", 'rev xs concat ys'],
    ['concat', "'a list list -> 'a list", 'Flatten one level'],
    ['flatten', "'a list list -> 'a list", 'Synonym for concat'],
    ['equal', "('a -> 'a -> bool) -> 'a list -> 'a list -> bool", 'Equality of lists'],
    ['compare', "('a -> 'a -> int) -> 'a list -> 'a list -> int", 'Compare lists'],
    ['iter', "('a -> unit) -> 'a list -> unit", 'Iterate effects'],
    ['iteri', "(int -> 'a -> unit) -> 'a list -> unit", 'Iterate with index'],
    ['map', "('a -> 'b) -> 'a list -> 'b list", 'Map function over list'],
    ['mapi', "(int -> 'a -> 'b) -> 'a list -> 'b list", 'Map with index'],
    ['rev_map', "('a -> 'b) -> 'a list -> 'b list", 'rev (map ...)'],
    ['filter_map', "('a -> 'b option) -> 'a list -> 'b list", 'Map + filter Nones'],
    ['concat_map', "('a -> 'b list) -> 'a list -> 'b list", 'flatten . map'],
    ['fold_left_map', null, 'fold + map combined'],
    ['fold_left', "('acc -> 'a -> 'acc) -> 'acc -> 'a list -> 'acc", 'Strict left fold'],
    ['fold_right', "('a -> 'acc -> 'acc) -> 'a list -> 'acc -> 'acc", 'Right fold'],
    ['iter2', "('a -> 'b -> unit) -> 'a list -> 'b list -> unit", 'Iterate two lists'],
    ['map2', "('a -> 'b -> 'c) -> 'a list -> 'b list -> 'c list", 'Map two lists'],
    ['rev_map2', null, 'rev (map2 ...)'],
    ['fold_left2', null, 'fold_left over two lists'],
    ['fold_right2', null, 'fold_right over two lists'],
    ['for_all', "('a -> bool) -> 'a list -> bool", 'All match predicate?'],
    ['exists', "('a -> bool) -> 'a list -> bool", 'Any match predicate?'],
    ['for_all2', null, 'for_all over two lists'],
    ['exists2', null, 'exists over two lists'],
    ['mem', "'a -> 'a list -> bool", 'Membership (=)'],
    ['memq', "'a -> 'a list -> bool", 'Membership (==)'],
    ['find', "('a -> bool) -> 'a list -> 'a", 'First match (raises)'],
    ['find_opt', "('a -> bool) -> 'a list -> 'a option", 'First match (option)'],
    ['find_index', null, 'Index of first match'],
    ['find_map', "('a -> 'b option) -> 'a list -> 'b option", 'First Some'],
    ['find_mapi', null, 'First Some with index'],
    ['filter', "('a -> bool) -> 'a list -> 'a list", 'Keep matching items'],
    ['find_all', "('a -> bool) -> 'a list -> 'a list", 'Synonym for filter'],
    ['filteri', "(int -> 'a -> bool) -> 'a list -> 'a list", 'filter with index'],
    ['partition', "('a -> bool) -> 'a list -> 'a list * 'a list", 'Split by predicate'],
    ['partition_map', null, 'Split via Either'],
    ['assoc', "'a -> ('a * 'b) list -> 'b", 'Association lookup (raises)'],
    ['assoc_opt', "'a -> ('a * 'b) list -> 'b option", 'Association lookup'],
    ['assq', null, 'Like assoc but uses physical equality'],
    ['assq_opt', null, 'Like assoc_opt but physical'],
    ['mem_assoc', "'a -> ('a * 'b) list -> bool", 'Membership in assoc'],
    ['mem_assq', null, 'Physical mem_assoc'],
    ['remove_assoc', null, 'Drop first assoc match'],
    ['remove_assq', null, 'Physical remove_assoc'],
    ['split', "('a * 'b) list -> 'a list * 'b list", 'Unzip pairs'],
    ['combine', "'a list -> 'b list -> ('a * 'b) list", 'Zip into pairs'],
    ['sort', "('a -> 'a -> int) -> 'a list -> 'a list", 'Stable sort'],
    ['stable_sort', null, 'Stable merge sort'],
    ['fast_sort', null, 'Faster sort (unspecified stability)'],
    ['sort_uniq', null, 'Sort and dedupe'],
    ['merge', null, 'Merge two sorted lists'],
    ['to_seq', "'a list -> 'a Seq.t", 'Convert to sequence'],
    ['of_seq', "'a Seq.t -> 'a list", 'Build from sequence'],
    ['is_empty', "'a list -> bool", 'Is list empty?'],
  ];
  s.addMany(members('List', listFns, 'function'));

  // Array module
  const arrayFns = [
    ['length', "'a array -> int", 'Length of array'],
    ['get', "'a array -> int -> 'a", 'Indexed read (bounds checked)'],
    ['set', "'a array -> int -> 'a -> unit", 'Indexed write'],
    ['unsafe_get', null, 'Indexed read (no bounds check)'],
    ['unsafe_set', null, 'Indexed write (no bounds check)'],
    ['make', "int -> 'a -> 'a array", 'Allocate filled array'],
    ['create_float', 'int -> float array', 'Allocate float array'],
    ['init', "int -> (int -> 'a) -> 'a array", 'Build array from index'],
    ['make_matrix', null, '2-D array of constants'],
    ['append', "'a array -> 'a array -> 'a array", 'Concatenate two arrays'],
    ['concat', "'a array list -> 'a array", 'Flatten arrays'],
    ['sub', "'a array -> int -> int -> 'a array", 'Sub-array copy'],
    ['copy', "'a array -> 'a array", 'Shallow copy'],
    ['fill', null, 'Fill range with value'],
    ['blit', null, 'Copy range to another array'],
    ['to_list', "'a array -> 'a list", 'Convert to list'],
    ['of_list', "'a list -> 'a array", 'Build from list'],
    ['iter', "('a -> unit) -> 'a array -> unit", 'Iterate effects'],
    ['iteri', null, 'Iterate with index'],
    ['map', "('a -> 'b) -> 'a array -> 'b array", 'Map function'],
    ['mapi', null, 'Map with index'],
    ['fold_left', null, 'Strict left fold'],
    ['fold_left_map', null, 'fold + map combined'],
    ['fold_right', null, 'Right fold'],
    ['iter2', null, 'Iterate two arrays'],
    ['map2', null, 'Map two arrays'],
    ['for_all', null, 'Universal predicate'],
    ['exists', null, 'Existential predicate'],
    ['for_all2', null, 'Universal predicate (pair)'],
    ['exists2', null, 'Existential predicate (pair)'],
    ['mem', null, 'Structural membership'],
    ['memq', null, 'Physical membership'],
    ['find_opt', null, 'First match (option)'],
    ['find_index', null, 'Index of first match'],
    ['find_map', null, 'First Some after mapping'],
    ['find_mapi', null, 'First Some after mapping with index'],
    ['split', null, 'Unzip array of pairs'],
    ['combine', null, 'Zip into array of pairs'],
    ['sort', "('a -> 'a -> int) -> 'a array -> unit", 'In-place stable sort'],
    ['stable_sort', null, 'In-place stable sort'],
    ['fast_sort', null, 'In-place faster sort'],
    ['shuffle', null, 'Random permutation in place'],
    ['to_seq', "'a array -> 'a Seq.t", 'Convert to sequence'],
    ['to_seqi', null, 'Sequence of (i, x)'],
    ['of_seq', null, 'Build from sequence'],
    ['is_empty', null, 'Is array empty?'],
    ['filter', null, 'Keep matching items'],
    ['filter_map', null, 'Map + filter Nones'],
    ['concat_map', null, 'Flatten via mapping'],
    ['exists_with_index', null, 'Exists with index'],
  ];
  s.addMany(members('Array', arrayFns, 'function'));

  // String module
  const stringFns = [
    ['length', 'string -> int', 'String length in bytes'],
    ['get', 'string -> int -> char', 'Indexed read'],
    ['make', 'int -> char -> string', 'Repeated character'],
    ['init', 'int -> (int -> char) -> string', 'Build from index fn'],
    ['empty', 'string', 'Empty string'],
    ['of_bytes', 'bytes -> string', 'Convert from bytes'],
    ['to_bytes', 'string -> bytes', 'Convert to bytes'],
    ['blit', null, 'Copy range to bytes'],
    ['concat', 'string -> string list -> string', 'Join with separator'],
    ['cat', 'string -> string -> string', 'Concatenate two strings'],
    ['equal', 'string -> string -> bool', 'String equality'],
    ['compare', 'string -> string -> int', 'Lexicographic compare'],
    ['starts_with', null, 'Prefix predicate (~prefix)'],
    ['ends_with', null, 'Suffix predicate (~suffix)'],
    ['contains', 'string -> char -> bool', 'Contains a character?'],
    ['contains_from', null, 'Contains char from index'],
    ['rcontains_from', null, 'Reverse contains_from'],
    ['index', 'string -> char -> int', 'Index of first occurrence'],
    ['index_opt', null, 'Index of first occurrence (option)'],
    ['rindex', null, 'Last index of char'],
    ['rindex_opt', null, 'Last index (option)'],
    ['index_from', null, 'Index of char from start'],
    ['index_from_opt', null, 'Index from start (option)'],
    ['rindex_from', null, 'Reverse index from start'],
    ['rindex_from_opt', null, 'Reverse index from start (option)'],
    ['sub', 'string -> int -> int -> string', 'Sub-string copy'],
    ['fill', null, 'Mutate range (deprecated)'],
    ['copy', null, 'Identity copy (deprecated)'],
    ['iter', '(char -> unit) -> string -> unit', 'Iterate characters'],
    ['iteri', null, 'Iterate with index'],
    ['map', '(char -> char) -> string -> string', 'Map characters'],
    ['mapi', null, 'Map with index'],
    ['fold_left', null, 'Strict left fold'],
    ['fold_right', null, 'Right fold'],
    ['for_all', null, 'Predicate over all chars'],
    ['exists', null, 'Predicate over any char'],
    ['trim', 'string -> string', 'Trim ASCII whitespace'],
    ['escaped', 'string -> string', 'Escape OCaml-string-style'],
    ['unsafe_get', null, 'Indexed read (no bounds check)'],
    ['unsafe_set', null, 'Indexed write (no bounds check)'],
    ['split_on_char', 'char -> string -> string list', 'Split on a character'],
    ['lowercase_ascii', 'string -> string', 'ASCII lowercase'],
    ['uppercase_ascii', 'string -> string', 'ASCII uppercase'],
    ['capitalize_ascii', 'string -> string', 'Capitalize first ASCII char'],
    ['uncapitalize_ascii', 'string -> string', 'Uncapitalize first ASCII char'],
    ['to_seq', 'string -> char Seq.t', 'Convert to sequence'],
    ['to_seqi', null, '(i, c) sequence'],
    ['of_seq', null, 'Build from sequence'],
    ['get_uint8', null, 'Read unsigned byte'],
    ['get_int8', null, 'Read signed byte'],
    ['get_uint16_be', null, 'Read big-endian uint16'],
    ['get_uint16_le', null, 'Read little-endian uint16'],
    ['get_uint16_ne', null, 'Read native-endian uint16'],
    ['get_int16_be', null, 'Read big-endian int16'],
    ['get_int16_le', null, 'Read little-endian int16'],
    ['get_int16_ne', null, 'Read native-endian int16'],
    ['get_int32_be', null, 'Read big-endian int32'],
    ['get_int32_le', null, 'Read little-endian int32'],
    ['get_int32_ne', null, 'Read native-endian int32'],
    ['get_int64_be', null, 'Read big-endian int64'],
    ['get_int64_le', null, 'Read little-endian int64'],
    ['get_int64_ne', null, 'Read native-endian int64'],
    ['hash', 'string -> int', 'Hash a string'],
    ['seeded_hash', null, 'Seeded hash'],
    ['is_empty', null, 'Empty string predicate'],
    ['is_valid_utf_8', null, 'UTF-8 validity'],
    ['is_valid_utf_16be', null, 'UTF-16BE validity'],
    ['is_valid_utf_16le', null, 'UTF-16LE validity'],
    ['get_utf_8_uchar', null, 'Decode one UTF-8 Uchar'],
  ];
  s.addMany(members('String', stringFns, 'function'));

  // Bytes module
  const bytesFns = [
    ['length', 'bytes -> int', 'Length in bytes'],
    ['get', null, 'Indexed read'],
    ['set', null, 'Indexed write'],
    ['create', 'int -> bytes', 'Uninitialised buffer'],
    ['make', 'int -> char -> bytes', 'Filled buffer'],
    ['init', null, 'Build from index fn'],
    ['empty', null, 'Empty bytes'],
    ['copy', 'bytes -> bytes', 'Shallow copy'],
    ['of_string', 'string -> bytes', 'Convert from string'],
    ['to_string', 'bytes -> string', 'Convert to string'],
    ['sub', null, 'Sub-buffer copy'],
    ['sub_string', null, 'Sub-buffer as string'],
    ['extend', null, 'Resize, padding with NUL'],
    ['fill', null, 'Mutate range to char'],
    ['blit', null, 'Copy range from bytes'],
    ['blit_string', null, 'Copy range from string'],
    ['concat', null, 'Join bytes list'],
    ['cat', null, 'Concatenate two bytes'],
    ['iter', null, 'Iterate characters'],
    ['iteri', null, 'Iterate with index'],
    ['map', null, 'Map characters'],
    ['mapi', null, 'Map with index'],
    ['fold_left', null, 'Strict left fold'],
    ['fold_right', null, 'Right fold'],
    ['for_all', null, 'Predicate over all chars'],
    ['exists', null, 'Predicate over any char'],
    ['trim', null, 'Trim ASCII whitespace'],
    ['escaped', null, 'OCaml-style escape'],
    ['index', null, 'Index of char'],
    ['index_opt', null, 'Index of char (option)'],
    ['rindex', null, 'Reverse index'],
    ['rindex_opt', null, 'Reverse index (option)'],
    ['contains', null, 'Contains char?'],
    ['unsafe_get', null, 'Read without bounds check'],
    ['unsafe_set', null, 'Write without bounds check'],
    ['unsafe_blit', null, 'Blit without bounds check'],
    ['unsafe_fill', null, 'Fill without bounds check'],
    ['lowercase_ascii', null, 'ASCII lowercase'],
    ['uppercase_ascii', null, 'ASCII uppercase'],
    ['capitalize_ascii', null, 'Capitalize first ASCII'],
    ['uncapitalize_ascii', null, 'Uncapitalize first ASCII'],
    ['equal', null, 'Bytes equality'],
    ['compare', null, 'Bytes compare'],
    ['split_on_char', null, 'Split on char'],
    ['to_seq', null, 'Convert to sequence'],
    ['of_seq', null, 'Build from sequence'],
    ['get_uint8', null, 'Read unsigned byte'],
    ['set_uint8', null, 'Write unsigned byte'],
    ['get_int16_be', null, 'Read big-endian int16'],
    ['set_int16_be', null, 'Write big-endian int16'],
    ['get_int32_be', null, 'Read big-endian int32'],
    ['set_int32_be', null, 'Write big-endian int32'],
    ['get_int64_be', null, 'Read big-endian int64'],
    ['set_int64_be', null, 'Write big-endian int64'],
    ['get_utf_8_uchar', null, 'Decode UTF-8 scalar'],
    ['set_utf_8_uchar', null, 'Encode UTF-8 scalar'],
  ];
  s.addMany(members('Bytes', bytesFns, 'function'));

  // Buffer module
  const bufferFns = [
    ['create', 'int -> Buffer.t', 'Allocate with initial capacity'],
    ['contents', 'Buffer.t -> string', 'Snapshot current contents'],
    ['to_bytes', 'Buffer.t -> bytes', 'Snapshot as bytes'],
    ['sub', null, 'Sub-content as string'],
    ['blit', null, 'Copy range to bytes'],
    ['nth', 'Buffer.t -> int -> char', 'Indexed read'],
    ['length', 'Buffer.t -> int', 'Current length in bytes'],
    ['clear', 'Buffer.t -> unit', 'Clear contents (keep buffer)'],
    ['reset', 'Buffer.t -> unit', 'Free internal storage'],
    ['add_char', 'Buffer.t -> char -> unit', 'Append a single char'],
    ['add_utf_8_uchar', null, 'Append UTF-8 scalar'],
    ['add_utf_16le_uchar', null, 'Append UTF-16LE scalar'],
    ['add_utf_16be_uchar', null, 'Append UTF-16BE scalar'],
    ['add_string', 'Buffer.t -> string -> unit', 'Append a string'],
    ['add_substring', null, 'Append a sub-string'],
    ['add_subbytes', null, 'Append a sub-bytes'],
    ['add_bytes', null, 'Append bytes'],
    ['add_substitute', null, 'Append with substitution function'],
    ['add_buffer', null, 'Append another buffer'],
    ['add_channel', null, 'Append data from channel'],
    ['add_int8', null, 'Append signed byte'],
    ['add_uint8', null, 'Append unsigned byte'],
    ['add_int16_be', null, 'Append big-endian int16'],
    ['add_int16_le', null, 'Append little-endian int16'],
    ['add_int32_be', null, 'Append big-endian int32'],
    ['add_int32_le', null, 'Append little-endian int32'],
    ['add_int64_be', null, 'Append big-endian int64'],
    ['add_int64_le', null, 'Append little-endian int64'],
    ['output_buffer', 'out_channel -> Buffer.t -> unit', 'Write to channel'],
    ['truncate', 'Buffer.t -> int -> unit', 'Drop end down to length'],
    ['to_seq', null, 'Convert to char sequence'],
    ['to_seqi', null, '(i, c) sequence'],
    ['of_seq', null, 'Build from sequence'],
  ];
  s.addMany(members('Buffer', bufferFns, 'function'));

  // Hashtbl module
  const hashtblFns = [
    ['create', null, 'Create a fresh hash table'],
    ['clear', null, 'Empty all bindings'],
    ['reset', null, 'Empty + free internal storage'],
    ['copy', null, 'Shallow copy of table'],
    ['add', null, 'Add a binding (does not replace)'],
    ['find', null, 'Find binding (raises)'],
    ['find_opt', null, 'Find binding (option)'],
    ['find_all', null, 'All values bound to a key'],
    ['mem', null, 'Membership predicate'],
    ['remove', null, 'Remove first binding for key'],
    ['replace', null, 'Replace or add binding'],
    ['iter', null, 'Iterate over bindings'],
    ['filter_map_inplace', null, 'In-place filter / map'],
    ['fold', null, 'Fold over bindings'],
    ['length', null, 'Number of bindings'],
    ['randomize', null, 'Re-seed hash randomisation'],
    ['is_randomized', null, 'Is randomisation active?'],
    ['rebuild', null, 'Rebuild internal table'],
    ['stats', null, 'Bucket statistics'],
    ['to_seq', null, 'Sequence of (k, v)'],
    ['to_seq_keys', null, 'Sequence of keys'],
    ['to_seq_values', null, 'Sequence of values'],
    ['add_seq', null, 'Bulk add from sequence'],
    ['replace_seq', null, 'Bulk replace from sequence'],
    ['of_seq', null, 'Build table from sequence'],
    ['hash', null, 'Generic hash function'],
    ['seeded_hash', null, 'Generic hash with seed'],
    ['hash_param', null, 'Bounded generic hash'],
    ['seeded_hash_param', null, 'Bounded seeded hash'],
    ['Make', null, 'Functor for typed hashtables'],
    ['MakeSeeded', null, 'Functor for seeded typed hashtables'],
  ];
  s.addMany(members('Hashtbl', hashtblFns, 'function'));

  // Map module (Map.Make functor surface)
  const mapFns = [
    ['empty', null, 'Empty map'],
    ['is_empty', null, 'Empty predicate'],
    ['mem', null, 'Membership predicate'],
    ['add', null, 'Insert binding'],
    ['add_to_list', null, 'Append to list value'],
    ['update', null, 'Update binding via function'],
    ['singleton', null, 'Singleton map'],
    ['remove', null, 'Remove a key'],
    ['merge', null, 'Generic merge'],
    ['union', null, 'Union with combiner'],
    ['compare', null, 'Compare maps'],
    ['equal', null, 'Map equality'],
    ['iter', null, 'Iterate bindings'],
    ['fold', null, 'Fold bindings'],
    ['for_all', null, 'Universal predicate'],
    ['exists', null, 'Existential predicate'],
    ['filter', null, 'Keep matching bindings'],
    ['filter_map', null, 'Map + filter Nones'],
    ['partition', null, 'Split by predicate'],
    ['cardinal', null, 'Number of bindings'],
    ['bindings', null, 'List of (k, v)'],
    ['min_binding', null, 'Minimum key binding'],
    ['min_binding_opt', null, 'Minimum binding (option)'],
    ['max_binding', null, 'Maximum binding'],
    ['max_binding_opt', null, 'Maximum binding (option)'],
    ['choose', null, 'Pick any binding'],
    ['choose_opt', null, 'Pick any binding (option)'],
    ['split', null, 'Split around a key'],
    ['find', null, 'Lookup (raises)'],
    ['find_opt', null, 'Lookup (option)'],
    ['find_first', null, 'First key satisfying predicate'],
    ['find_first_opt', null, 'First key (option)'],
    ['find_last', null, 'Last key satisfying predicate'],
    ['find_last_opt', null, 'Last key (option)'],
    ['map', null, 'Map values'],
    ['mapi', null, 'Map values with key'],
    ['to_seq', null, 'Sequence of bindings'],
    ['to_rev_seq', null, 'Reverse sequence of bindings'],
    ['to_seq_from', null, 'Sequence from key onward'],
    ['add_seq', null, 'Bulk add from sequence'],
    ['of_seq', null, 'Build from sequence'],
    ['Make', null, 'Map functor on ordered keys'],
  ];
  s.addMany(members('Map', mapFns, 'function'));

  // Set module
  const setFns = [
    ['empty', null, 'Empty set'],
    ['is_empty', null, 'Empty predicate'],
    ['mem', null, 'Membership predicate'],
    ['add', null, 'Add an element'],
    ['singleton', null, 'Singleton set'],
    ['remove', null, 'Remove an element'],
    ['union', null, 'Set union'],
    ['inter', null, 'Set intersection'],
    ['disjoint', null, 'Disjoint predicate'],
    ['diff', null, 'Set difference'],
    ['compare', null, 'Compare sets'],
    ['equal', null, 'Set equality'],
    ['subset', null, 'Subset predicate'],
    ['iter', null, 'Iterate elements'],
    ['map', null, 'Map elements'],
    ['fold', null, 'Fold elements'],
    ['for_all', null, 'Universal predicate'],
    ['exists', null, 'Existential predicate'],
    ['filter', null, 'Keep matching elements'],
    ['filter_map', null, 'Map + filter Nones'],
    ['partition', null, 'Split by predicate'],
    ['cardinal', null, 'Number of elements'],
    ['elements', null, 'Sorted list of elements'],
    ['min_elt', null, 'Minimum element'],
    ['min_elt_opt', null, 'Minimum (option)'],
    ['max_elt', null, 'Maximum element'],
    ['max_elt_opt', null, 'Maximum (option)'],
    ['choose', null, 'Pick any element'],
    ['choose_opt', null, 'Pick any (option)'],
    ['split', null, 'Split around an element'],
    ['find', null, 'Find equal element'],
    ['find_opt', null, 'Find equal element (option)'],
    ['find_first', null, 'First element satisfying predicate'],
    ['find_first_opt', null, 'First element (option)'],
    ['find_last', null, 'Last element satisfying predicate'],
    ['find_last_opt', null, 'Last element (option)'],
    ['of_list', null, 'Build set from list'],
    ['to_seq', null, 'Sequence of elements'],
    ['to_rev_seq', null, 'Reverse sequence'],
    ['to_seq_from', null, 'Sequence from element'],
    ['add_seq', null, 'Bulk add from sequence'],
    ['of_seq', null, 'Build from sequence'],
    ['Make', null, 'Set functor on ordered elements'],
  ];
  s.addMany(members('Set', setFns, 'function'));

  // Seq module
  const seqFns = [
    ['empty', null, 'Empty sequence'],
    ['return', null, 'Singleton sequence'],
    ['cons', null, 'Cons element to sequence'],
    ['append', null, 'Concatenate two sequences'],
    ['init', null, 'Build from index function'],
    ['unfold', null, 'Generate from seed'],
    ['repeat', null, 'Infinite repetition'],
    ['forever', null, 'Infinite repetition of thunk'],
    ['cycle', null, 'Cycle finite sequence'],
    ['iterate', null, 'Successive applications of f'],
    ['iter', null, 'Iterate effects'],
    ['iteri', null, 'Iterate with index'],
    ['fold_left', null, 'Strict left fold'],
    ['fold_lefti', null, 'Strict left fold with index'],
    ['for_all', null, 'Universal predicate'],
    ['exists', null, 'Existential predicate'],
    ['mem', null, 'Membership predicate'],
    ['find', null, 'First match (option)'],
    ['find_index', null, 'Index of first match'],
    ['find_map', null, 'First Some'],
    ['find_mapi', null, 'First Some with index'],
    ['scan', null, 'Cumulative fold'],
    ['take', null, 'First n elements'],
    ['drop', null, 'Skip n elements'],
    ['take_while', null, 'Prefix while predicate'],
    ['drop_while', null, 'Suffix after predicate'],
    ['group', null, 'Group adjacent equal'],
    ['memoize', null, 'Memoise the sequence'],
    ['once', null, 'Allow only one traversal'],
    ['transpose', null, 'Transpose a sequence of seqs'],
    ['zip', null, 'Pair two sequences'],
    ['unzip', null, 'Split sequence of pairs'],
    ['map2', null, 'Map two sequences'],
    ['interleave', null, 'Interleave two sequences'],
    ['sorted_merge', null, 'Merge sorted sequences'],
    ['product', null, 'Cartesian product'],
    ['map_product', null, 'Cartesian product with f'],
    ['filter', null, 'Keep matching items'],
    ['filter_map', null, 'Map + filter Nones'],
    ['concat', null, 'Flatten one level'],
    ['concat_map', null, 'concat (map f)'],
    ['flat_map', null, 'Synonym of concat_map'],
    ['length', null, 'Length (forces sequence)'],
    ['ints', null, 'Sequence of ints from n'],
    ['to_list', null, 'Force to list'],
    ['of_list', null, 'Sequence from list'],
    ['to_array', null, 'Force to array'],
    ['of_array', null, 'Sequence from array'],
    ['split', null, 'Split by predicate'],
    ['equal', null, 'Equality of sequences'],
    ['compare', null, 'Compare sequences'],
    ['is_empty', null, 'Empty predicate'],
    ['uncons', null, 'Pop first element'],
    ['partition', null, 'Split by predicate (eager)'],
    ['partition_map', null, 'Split via Either'],
  ];
  s.addMany(members('Seq', seqFns, 'function'));

  // Option module
  const optionFns = [
    ['none', null, 'None constructor'],
    ['some', null, 'Some constructor'],
    ['value', null, 'Get value or default'],
    ['get', null, 'Get value (raises)'],
    ['bind', null, 'Monadic bind'],
    ['join', null, 'Flatten option of option'],
    ['map', null, 'Map over option'],
    ['fold', null, 'Reduce option to value'],
    ['iter', null, 'Iterate effect'],
    ['is_none', null, 'Is None?'],
    ['is_some', null, 'Is Some?'],
    ['equal', null, 'Equality of options'],
    ['compare', null, 'Compare options'],
    ['to_result', null, 'Convert to result'],
    ['to_list', null, 'Convert to list'],
    ['to_seq', null, 'Convert to sequence'],
  ];
  s.addMany(members('Option', optionFns, 'function'));

  // Result module
  const resultFns = [
    ['ok', null, 'Ok constructor'],
    ['error', null, 'Error constructor'],
    ['value', null, 'Ok or default'],
    ['get_ok', null, 'Get Ok (raises)'],
    ['get_error', null, 'Get Error (raises)'],
    ['bind', null, 'Monadic bind on Ok'],
    ['join', null, 'Flatten result of result'],
    ['map', null, 'Map over Ok'],
    ['map_error', null, 'Map over Error'],
    ['fold', null, 'Reduce result to value'],
    ['iter', null, 'Iterate effect on Ok'],
    ['iter_error', null, 'Iterate effect on Error'],
    ['is_ok', null, 'Is Ok?'],
    ['is_error', null, 'Is Error?'],
    ['equal', null, 'Equality of results'],
    ['compare', null, 'Compare results'],
    ['to_option', null, 'Convert to option'],
    ['to_list', null, 'Convert to list'],
    ['to_seq', null, 'Convert to sequence'],
  ];
  s.addMany(members('Result', resultFns, 'function'));

  // Printf
  const printfFns = [
    ['printf', "('a, out_channel, unit) format -> 'a", 'Formatted print to stdout'],
    ['eprintf', null, 'Formatted print to stderr'],
    ['fprintf', null, 'Formatted print to channel'],
    ['sprintf', "('a, unit, string) format -> 'a", 'Format to string'],
    ['bprintf', null, 'Format into a buffer'],
    ['ifprintf', null, 'Discard formatted output'],
    ['kfprintf', null, 'Continuation form of fprintf'],
    ['ksprintf', null, 'Continuation form of sprintf'],
    ['kbprintf', null, 'Continuation form of bprintf'],
    ['ikfprintf', null, 'Discarding continuation'],
    ['scanf', null, 'Read formatted input from stdin'],
    ['kscanf', null, 'Continuation Scanf'],
    ['CamlinternalPr', null, 'Internal Printf helpers'],
  ];
  s.addMany(members('Printf', printfFns, 'function'));

  // Scanf
  const scanfFns = [
    ['scanf', null, 'Read formatted input from stdin'],
    ['bscanf', null, 'Read from a buffer'],
    ['sscanf', null, 'Read from a string'],
    ['fscanf', null, 'Read from a channel'],
    ['kscanf', null, 'Continuation form of scanf'],
    ['ksscanf', null, 'Continuation form of sscanf'],
    ['kbscanf', null, 'Continuation form of bscanf'],
    ['unescaped', null, 'Inverse of String.escaped'],
    ['format_from_string', null, 'Convert string to format'],
    ['Scanning.from_channel', null, 'Build a scanbuf from channel'],
    ['Scanning.from_string', null, 'Build a scanbuf from string'],
    ['Scanning.from_file', null, 'Build a scanbuf from file'],
    ['Scanning.close_in', null, 'Close the underlying channel'],
    ['Scanning.stdin', null, 'Standard input scanbuf'],
    ['Scanning.end_of_input', null, 'Detect EOF'],
  ];
  s.addMany(members('Scanf', scanfFns, 'function'));

  // Format
  const formatFns = [
    ['fprintf', null, 'Format-print to formatter'],
    ['printf', null, 'Format-print to stdout'],
    ['eprintf', null, 'Format-print to stderr'],
    ['sprintf', null, 'Format-print to string'],
    ['asprintf', null, 'Format with %a/%t'],
    ['kfprintf', null, 'Continuation form of fprintf'],
    ['kasprintf', null, 'Continuation form of asprintf'],
    ['dprintf', null, 'Deferred fprintf'],
    ['ifprintf', null, 'Discard format output'],
    ['std_formatter', null, 'Standard output formatter'],
    ['err_formatter', null, 'Standard error formatter'],
    ['str_formatter', null, 'String formatter'],
    ['flush_str_formatter', null, 'Flush str_formatter to string'],
    ['formatter_of_buffer', null, 'Wrap a Buffer as formatter'],
    ['formatter_of_out_channel', null, 'Wrap a channel as formatter'],
    ['pp_print_string', null, 'Print a string'],
    ['pp_print_int', null, 'Print an integer'],
    ['pp_print_float', null, 'Print a float'],
    ['pp_print_char', null, 'Print a character'],
    ['pp_print_bool', null, 'Print a boolean'],
    ['pp_print_list', null, 'Print a list with separator'],
    ['pp_print_option', null, 'Print an option'],
    ['pp_print_result', null, 'Print a result'],
    ['pp_print_seq', null, 'Print a sequence'],
    ['pp_print_break', null, 'Print a break hint'],
    ['pp_print_cut', null, 'Print a cut hint'],
    ['pp_print_space', null, 'Print a space hint'],
    ['pp_print_newline', null, 'Print a newline'],
    ['pp_open_box', null, 'Open a pretty box'],
    ['pp_close_box', null, 'Close pretty box'],
    ['pp_open_hbox', null, 'Open horizontal box'],
    ['pp_open_vbox', null, 'Open vertical box'],
    ['pp_open_hvbox', null, 'Open hv box'],
    ['pp_open_hovbox', null, 'Open hov box'],
    ['pp_open_tag', null, 'Open semantic tag'],
    ['pp_close_tag', null, 'Close semantic tag'],
    ['pp_set_margin', null, 'Set right margin'],
    ['pp_get_margin', null, 'Get right margin'],
    ['pp_set_max_indent', null, 'Set max indent'],
    ['pp_set_max_boxes', null, 'Set max nested boxes'],
  ];
  s.addMany(members('Format', formatFns, 'function'));

  // Int / Float / Bool / Char modules
  const intFns = [
    ['zero', 'int', 'Constant 0'],
    ['one', 'int', 'Constant 1'],
    ['minus_one', 'int', 'Constant -1'],
    ['neg', 'int -> int', 'Unary negation'],
    ['add', 'int -> int -> int', 'Addition'],
    ['sub', 'int -> int -> int', 'Subtraction'],
    ['mul', 'int -> int -> int', 'Multiplication'],
    ['div', 'int -> int -> int', 'Truncating division'],
    ['rem', 'int -> int -> int', 'Truncating remainder'],
    ['succ', 'int -> int', 'Successor'],
    ['pred', 'int -> int', 'Predecessor'],
    ['abs', 'int -> int', 'Absolute value'],
    ['max_int', 'int', 'Largest int'],
    ['min_int', 'int', 'Smallest int'],
    ['logand', null, 'Bitwise and'],
    ['logor', null, 'Bitwise or'],
    ['logxor', null, 'Bitwise xor'],
    ['lognot', null, 'Bitwise not'],
    ['shift_left', null, 'Logical shift left'],
    ['shift_right', null, 'Arithmetic shift right'],
    ['shift_right_logical', null, 'Logical shift right'],
    ['equal', null, 'Equality predicate'],
    ['compare', null, 'Three-way compare'],
    ['min', null, 'Minimum of two'],
    ['max', null, 'Maximum of two'],
    ['to_float', null, 'Widen to float'],
    ['of_float', null, 'Truncate float to int'],
    ['to_string', null, 'Convert to decimal'],
    ['of_string', null, 'Parse from decimal'],
    ['hash', null, 'Hash an int'],
    ['seeded_hash', null, 'Seeded hash'],
  ];
  s.addMany(members('Int', intFns, 'function'));

  const floatFns = [
    ['zero', null, 'Constant 0.0'],
    ['one', null, 'Constant 1.0'],
    ['minus_one', null, 'Constant -1.0'],
    ['nan', null, 'NaN constant'],
    ['infinity', null, 'Positive infinity'],
    ['neg_infinity', null, 'Negative infinity'],
    ['pi', null, 'Pi constant'],
    ['epsilon', null, 'Float epsilon'],
    ['neg', null, 'Unary negation'],
    ['add', null, 'Addition'],
    ['sub', null, 'Subtraction'],
    ['mul', null, 'Multiplication'],
    ['div', null, 'Division'],
    ['rem', null, 'Remainder'],
    ['fma', null, 'Fused multiply-add'],
    ['abs', null, 'Absolute value'],
    ['is_finite', null, 'Finite predicate'],
    ['is_infinite', null, 'Infinite predicate'],
    ['is_nan', null, 'NaN predicate'],
    ['is_integer', null, 'Integer predicate'],
    ['classify', null, 'Classify float'],
    ['sqrt', null, 'Square root'],
    ['cbrt', null, 'Cube root'],
    ['pow', null, 'Power'],
    ['exp', null, 'Exponential'],
    ['log', null, 'Natural log'],
    ['log2', null, 'Base-2 log'],
    ['log10', null, 'Base-10 log'],
    ['expm1', null, 'exp x - 1'],
    ['log1p', null, 'log (1 + x)'],
    ['cos', null, 'Cosine'],
    ['sin', null, 'Sine'],
    ['tan', null, 'Tangent'],
    ['acos', null, 'Arc cosine'],
    ['asin', null, 'Arc sine'],
    ['atan', null, 'Arc tangent'],
    ['atan2', null, 'Two-argument atan'],
    ['hypot', null, 'Pythagorean magnitude'],
    ['cosh', null, 'Hyperbolic cosine'],
    ['sinh', null, 'Hyperbolic sine'],
    ['tanh', null, 'Hyperbolic tangent'],
    ['acosh', null, 'Inverse hyperbolic cosine'],
    ['asinh', null, 'Inverse hyperbolic sine'],
    ['atanh', null, 'Inverse hyperbolic tangent'],
    ['copysign', null, 'Copy sign of second to first'],
    ['sign_bit', null, 'Sign-bit predicate'],
    ['frexp', null, 'Mantissa / exponent split'],
    ['ldexp', null, 'x * 2^n'],
    ['modf', null, 'Frac / int split'],
    ['compare', null, 'Total order on floats'],
    ['equal', null, 'Equality of floats'],
    ['min', null, 'Minimum of two'],
    ['max', null, 'Maximum of two'],
    ['min_max', null, 'Both min and max'],
    ['to_int', null, 'Truncate to int'],
    ['of_int', null, 'Widen int to float'],
    ['to_string', null, 'Convert to string'],
    ['of_string', null, 'Parse from string'],
    ['hash', null, 'Hash a float'],
  ];
  s.addMany(members('Float', floatFns, 'function'));

  const boolFns = [
    ['not', null, 'Boolean negation'],
    ['compare', null, 'Three-way compare'],
    ['equal', null, 'Equality'],
    ['hash', null, 'Hash a bool'],
    ['seeded_hash', null, 'Seeded hash of bool'],
    ['to_int', null, 'Convert to 0 or 1'],
    ['to_float', null, 'Convert to 0.0 or 1.0'],
    ['to_string', null, 'Convert to "true"/"false"'],
    ['of_string', null, 'Parse from string'],
    ['of_string_opt', null, 'Parse from string (option)'],
  ];
  s.addMany(members('Bool', boolFns, 'function'));

  const charFns = [
    ['code', null, 'Code-point of char'],
    ['chr', null, 'Char of code-point'],
    ['escaped', null, 'OCaml-style escape'],
    ['lowercase_ascii', null, 'ASCII lowercase'],
    ['uppercase_ascii', null, 'ASCII uppercase'],
    ['equal', null, 'Equality'],
    ['compare', null, 'Three-way compare'],
    ['hash', null, 'Hash a char'],
    ['seeded_hash', null, 'Seeded hash'],
    ['unsafe_chr', null, 'Unchecked chr'],
  ];
  s.addMany(members('Char', charFns, 'function'));

  // Filename module
  const filenameFns = [
    ['concat', null, 'Concatenate path segments'],
    ['is_relative', null, 'Is path relative?'],
    ['is_implicit', null, 'Is path implicit?'],
    ['check_suffix', null, 'Has given suffix?'],
    ['chop_suffix', null, 'Drop given suffix'],
    ['chop_suffix_opt', null, 'Drop given suffix (option)'],
    ['extension', null, 'Get extension'],
    ['remove_extension', null, 'Drop extension'],
    ['chop_extension', null, 'Drop extension (raises)'],
    ['basename', null, 'File-name component'],
    ['dirname', null, 'Directory component'],
    ['null', null, '/dev/null on this platform'],
    ['parent_dir_name', null, 'Parent dir literal'],
    ['current_dir_name', null, 'Current dir literal'],
    ['dir_sep', null, 'Platform path separator'],
    ['quote', null, 'Shell-quote a filename'],
    ['quote_command', null, 'Shell-quote a command line'],
    ['temp_file', null, 'Create a fresh temp file'],
    ['temp_dir', null, 'Default temp directory'],
    ['get_temp_dir_name', null, 'Get temp directory'],
    ['set_temp_dir_name', null, 'Set temp directory'],
    ['open_temp_file', null, 'Open fresh temp file'],
  ];
  s.addMany(members('Filename', filenameFns, 'function'));

  // Sys module
  const sysFns = [
    ['argv', 'string array', 'Command line argument vector'],
    ['executable_name', null, 'Path of running executable'],
    ['os_type', null, 'Operating system family'],
    ['unix', null, 'Is OS unix-like?'],
    ['win32', null, 'Is OS Win32?'],
    ['cygwin', null, 'Is OS Cygwin?'],
    ['word_size', null, 'Native word size in bits'],
    ['int_size', null, 'OCaml int size in bits'],
    ['max_array_length', null, 'Max array length'],
    ['max_string_length', null, 'Max string length'],
    ['big_endian', null, 'Native byte order'],
    ['file_exists', null, 'Test for existence'],
    ['is_directory', null, 'Is a directory?'],
    ['is_regular_file', null, 'Is a regular file?'],
    ['remove', null, 'Delete a file'],
    ['rename', null, 'Rename a file'],
    ['getenv', null, 'Read env variable (raises)'],
    ['getenv_opt', null, 'Read env variable (option)'],
    ['putenv', null, 'Set env variable'],
    ['command', null, 'Run shell command'],
    ['time', null, 'Process CPU time'],
    ['chdir', null, 'Change directory'],
    ['mkdir', null, 'Make directory'],
    ['rmdir', null, 'Remove empty directory'],
    ['getcwd', null, 'Current working directory'],
    ['readdir', null, 'List directory entries'],
    ['interactive', null, 'Toplevel-interactive flag'],
    ['signal', null, 'Install a signal handler'],
    ['catch_break', null, 'Toggle break-on-Ctrl-C'],
    ['enable_runtime_warnings', null, 'Toggle runtime warnings'],
    ['runtime_warnings_enabled', null, 'Are runtime warnings on?'],
    ['ocaml_version', null, 'OCaml compiler version'],
    ['ocaml_release', null, 'Detailed release record'],
    ['development_version', null, 'Is dev compiler?'],
    ['backend_type', null, 'Native | Bytecode | Other'],
    ['set_signal', null, 'Configure signal handling'],
    ['sigabrt', null, 'SIGABRT signal'],
    ['sigalrm', null, 'SIGALRM signal'],
    ['sigfpe', null, 'SIGFPE signal'],
    ['sighup', null, 'SIGHUP signal'],
    ['sigill', null, 'SIGILL signal'],
    ['sigint', null, 'SIGINT signal'],
    ['sigkill', null, 'SIGKILL signal'],
    ['sigpipe', null, 'SIGPIPE signal'],
    ['sigquit', null, 'SIGQUIT signal'],
    ['sigsegv', null, 'SIGSEGV signal'],
    ['sigterm', null, 'SIGTERM signal'],
    ['sigusr1', null, 'SIGUSR1 signal'],
    ['sigusr2', null, 'SIGUSR2 signal'],
    ['Break', null, 'Sys.Break exception'],
  ];
  s.addMany(members('Sys', sysFns, 'function'));

  // Arg module
  const argFns = [
    ['parse', null, 'Parse argv against spec'],
    ['parse_dynamic', null, 'Parse with mutable spec'],
    ['parse_argv', null, 'Parse a custom argv'],
    ['parse_argv_dynamic', null, 'Parse custom argv (mutable)'],
    ['parse_and_expand_argv_dynamic', null, 'Parse + expand response files'],
    ['parse_expand', null, 'Parse with response-file expansion'],
    ['Help', null, 'Help-requested exception'],
    ['Bad', null, 'Bad-arg exception'],
    ['usage', null, 'Print usage'],
    ['usage_string', null, 'Build usage string'],
    ['align', null, 'Align spec descriptions'],
    ['current', null, 'Current arg index'],
    ['read_arg', null, 'Read response file (one per line)'],
    ['read_arg0', null, 'Read NUL-separated response file'],
    ['write_arg', null, 'Write response file'],
    ['write_arg0', null, 'Write NUL-separated response file'],
    ['Set', null, 'Spec: set bool ref'],
    ['Clear', null, 'Spec: clear bool ref'],
    ['Unit', null, 'Spec: unit thunk'],
    ['String', null, 'Spec: take a string'],
    ['Set_string', null, 'Spec: store string in ref'],
    ['Int', null, 'Spec: take an int'],
    ['Set_int', null, 'Spec: store int in ref'],
    ['Float', null, 'Spec: take a float'],
    ['Set_float', null, 'Spec: store float in ref'],
    ['Tuple', null, 'Spec: take multiple args'],
    ['Symbol', null, 'Spec: from a symbol set'],
    ['Rest', null, 'Spec: collect remaining args'],
    ['Rest_all', null, 'Spec: collect remaining (5+)'],
    ['Expand', null, 'Spec: expand response files'],
  ];
  s.addMany(members('Arg', argFns, 'function'));

  // Random module
  const randomFns = [
    ['init', null, 'Seed PRNG with int'],
    ['full_init', null, 'Seed with int array'],
    ['self_init', null, 'Seed from system entropy'],
    ['bits', null, 'Random 30-bit int'],
    ['bits32', null, 'Random int32'],
    ['bits64', null, 'Random int64'],
    ['nativebits', null, 'Random nativeint'],
    ['int', null, 'Random int < bound'],
    ['int_in_range', null, 'Random int in inclusive range'],
    ['full_int', null, 'Random non-negative int'],
    ['int32', null, 'Random int32 < bound'],
    ['int32_in_range', null, 'Random int32 in range'],
    ['int64', null, 'Random int64 < bound'],
    ['int64_in_range', null, 'Random int64 in range'],
    ['nativeint', null, 'Random nativeint < bound'],
    ['nativeint_in_range', null, 'Random nativeint in range'],
    ['float', null, 'Random float < bound'],
    ['bool', null, 'Random bool'],
    ['char', null, 'Random char'],
    ['get_state', null, 'Snapshot current state'],
    ['set_state', null, 'Restore previous state'],
    ['split', null, 'Split into independent stream'],
    ['State.make', null, 'Make new state from seed'],
    ['State.make_self_init', null, 'Make state from entropy'],
    ['State.copy', null, 'Copy a state'],
    ['State.bits', null, 'State 30-bit int'],
    ['State.int', null, 'State random int'],
    ['State.float', null, 'State random float'],
    ['State.bool', null, 'State random bool'],
  ];
  s.addMany(members('Random', randomFns, 'function'));

  // Digest module
  const digestFns = [
    ['compare', null, 'Compare digests'],
    ['equal', null, 'Equality of digests'],
    ['string', null, 'Digest of a string'],
    ['bytes', null, 'Digest of bytes'],
    ['substring', null, 'Digest of substring'],
    ['subbytes', null, 'Digest of subbytes'],
    ['channel', null, 'Digest of channel data'],
    ['file', null, 'Digest of a file'],
    ['output', null, 'Write digest to channel'],
    ['input', null, 'Read digest from channel'],
    ['to_hex', null, 'Hex string of digest'],
    ['from_hex', null, 'Parse digest from hex'],
    ['of_hex', null, 'Synonym of from_hex'],
    ['BLAKE128', null, 'BLAKE2 128-bit submodule'],
    ['BLAKE256', null, 'BLAKE2 256-bit submodule'],
    ['BLAKE512', null, 'BLAKE2 512-bit submodule'],
    ['MD5', null, 'MD5 submodule'],
  ];
  s.addMany(members('Digest', digestFns, 'function'));

  // Marshal module
  const marshalFns = [
    ['to_channel', null, 'Marshal value to channel'],
    ['to_string', null, 'Marshal value to string'],
    ['to_bytes', null, 'Marshal value to bytes'],
    ['to_buffer', null, 'Marshal value into buffer'],
    ['from_channel', null, 'Unmarshal value from channel'],
    ['from_string', null, 'Unmarshal value from string'],
    ['from_bytes', null, 'Unmarshal value from bytes'],
    ['header_size', null, 'Marshal header size'],
    ['data_size', null, 'Size of marshalled body'],
    ['total_size', null, 'Total marshal size'],
    ['No_sharing', null, 'Flag: do not share values'],
    ['Closures', null, 'Flag: include closures'],
    ['Compat_32', null, 'Flag: 32-bit compatibility'],
  ];
  s.addMany(members('Marshal', marshalFns, 'function'));

  // Queue / Stack
  const queueFns = [
    ['create', null, 'Allocate empty queue'],
    ['add', null, 'Push at the back'],
    ['push', null, 'Synonym of add'],
    ['pop', null, 'Pop from the front'],
    ['pop_opt', null, 'Pop (option)'],
    ['take', null, 'Synonym of pop'],
    ['take_opt', null, 'Synonym of pop_opt'],
    ['peek', null, 'Front element (raises)'],
    ['peek_opt', null, 'Front element (option)'],
    ['top', null, 'Synonym of peek'],
    ['clear', null, 'Empty the queue'],
    ['copy', null, 'Shallow copy'],
    ['is_empty', null, 'Empty predicate'],
    ['length', null, 'Number of elements'],
    ['iter', null, 'Iterate front-to-back'],
    ['fold', null, 'Fold front-to-back'],
    ['transfer', null, 'Move elements between queues'],
    ['to_seq', null, 'Sequence of elements'],
    ['add_seq', null, 'Bulk add from sequence'],
    ['of_seq', null, 'Build from sequence'],
    ['Empty', null, 'Empty-queue exception'],
  ];
  s.addMany(members('Queue', queueFns, 'function'));

  const stackFns = [
    ['create', null, 'Allocate empty stack'],
    ['push', null, 'Push onto top'],
    ['pop', null, 'Pop top (raises)'],
    ['pop_opt', null, 'Pop top (option)'],
    ['drop', null, 'Discard top (raises)'],
    ['top', null, 'Peek top (raises)'],
    ['top_opt', null, 'Peek top (option)'],
    ['clear', null, 'Empty the stack'],
    ['copy', null, 'Shallow copy'],
    ['is_empty', null, 'Empty predicate'],
    ['length', null, 'Number of elements'],
    ['iter', null, 'Iterate top-to-bottom'],
    ['fold', null, 'Fold top-to-bottom'],
    ['to_seq', null, 'Sequence of elements'],
    ['add_seq', null, 'Bulk push from sequence'],
    ['of_seq', null, 'Build from sequence'],
    ['Empty', null, 'Empty-stack exception'],
  ];
  s.addMany(members('Stack', stackFns, 'function'));

  // Lazy / Fun / Atomic / Domain / Mutex / Condition / Effect
  const lazyFns = [
    ['force', null, 'Force a lazy value'],
    ['force_val', null, 'Force without using exceptions'],
    ['from_fun', null, 'Wrap a thunk as lazy'],
    ['from_val', null, 'Already-forced lazy'],
    ['is_val', null, 'Has been forced?'],
    ['map', null, 'Map over a lazy value'],
    ['map_val', null, 'Map already-forced lazy'],
    ['Undefined', null, 'Internal cycle exception'],
  ];
  s.addMany(members('Lazy', lazyFns, 'function'));

  const funFns = [
    ['id', null, 'Identity function'],
    ['const', null, 'First-arg projection'],
    ['flip', null, 'Swap arguments'],
    ['negate', null, 'Negate a predicate'],
    ['protect', null, 'Run finally cleanup'],
    ['compose', null, 'Function composition'],
    ['Finally_raised', null, 'Failure in finally'],
  ];
  s.addMany(members('Fun', funFns, 'function'));

  const atomicFns = [
    ['make', null, 'Allocate atomic ref'],
    ['make_contended', null, 'Allocate, padded to a cache line'],
    ['get', null, 'Atomic load'],
    ['set', null, 'Atomic store'],
    ['exchange', null, 'Atomic exchange'],
    ['compare_and_set', null, 'Atomic compare-and-set'],
    ['fetch_and_add', null, 'Atomic fetch-and-add'],
    ['add', null, 'Atomic add (5+)'],
    ['sub', null, 'Atomic sub (5+)'],
    ['logand', null, 'Atomic and'],
    ['logor', null, 'Atomic or'],
    ['logxor', null, 'Atomic xor'],
    ['incr', null, 'Atomic increment'],
    ['decr', null, 'Atomic decrement'],
  ];
  s.addMany(members('Atomic', atomicFns, 'function'));

  const domainFns = [
    ['spawn', null, 'Spawn a new domain'],
    ['join', null, 'Wait for a domain to finish'],
    ['self', null, 'Identifier of current domain'],
    ['cpu_relax', null, 'Yield CPU briefly'],
    ['recommended_domain_count', null, 'Suggested concurrency level'],
    ['DLS.new_key', null, 'Allocate domain-local key'],
    ['DLS.set', null, 'Set domain-local value'],
    ['DLS.get', null, 'Read domain-local value'],
    ['at_first_spawn', null, 'Run before first spawn'],
    ['at_each_spawn', null, 'Run on each spawn'],
    ['at_exit', null, 'Run when domain exits'],
    ['before_first_spawn', null, 'Synonym for at_first_spawn'],
  ];
  s.addMany(members('Domain', domainFns, 'function'));

  const mutexFns = [
    ['create', null, 'Allocate a mutex'],
    ['lock', null, 'Acquire a mutex'],
    ['try_lock', null, 'Try to acquire'],
    ['unlock', null, 'Release a mutex'],
    ['protect', null, 'Run with mutex held'],
  ];
  s.addMany(members('Mutex', mutexFns, 'function'));

  const conditionFns = [
    ['create', null, 'Allocate a condition variable'],
    ['wait', null, 'Wait on a condition'],
    ['signal', null, 'Wake one waiter'],
    ['broadcast', null, 'Wake all waiters'],
  ];
  s.addMany(members('Condition', conditionFns, 'function'));

  const semaphoreFns = [
    ['Counting.make', null, 'Allocate counting semaphore'],
    ['Counting.acquire', null, 'Decrement (block if zero)'],
    ['Counting.release', null, 'Increment'],
    ['Counting.try_acquire', null, 'Non-blocking acquire'],
    ['Counting.get_value', null, 'Read counter'],
    ['Binary.make', null, 'Allocate binary semaphore'],
    ['Binary.acquire', null, 'Acquire binary semaphore'],
    ['Binary.release', null, 'Release binary semaphore'],
    ['Binary.try_acquire', null, 'Non-blocking acquire'],
  ];
  s.addMany(members('Semaphore', semaphoreFns, 'function'));

  // Effect (OCaml 5+)
  const effectFns = [
    ['perform', null, 'Perform an effect'],
    ['Deep.try_with', null, 'Run with deep handler'],
    ['Deep.match_with', null, 'Match a deep effect'],
    ['Deep.continue', null, 'Resume continuation with value'],
    ['Deep.discontinue', null, 'Resume with raised exception'],
    ['Deep.discontinue_with_backtrace', null, 'Discontinue with backtrace'],
    ['Deep.continue_with', null, 'Resume with backtrace'],
    ['Deep.handler', null, 'Build a deep handler record'],
    ['Deep.fiber', null, 'Allocate a fresh fiber'],
    ['Shallow.fiber', null, 'Allocate shallow fiber'],
    ['Shallow.continue_with', null, 'Resume shallow continuation'],
    ['Shallow.discontinue_with', null, 'Discontinue shallow continuation'],
    ['Shallow.handler', null, 'Build a shallow handler'],
    ['Shallow.continue', null, 'Resume shallow with value'],
    ['Shallow.discontinue', null, 'Resume shallow with exn'],
    ['Unhandled', null, 'Effect not handled exception'],
    ['Continuation_already_resumed', null, 'Already-resumed exception'],
  ];
  s.addMany(members('Effect', effectFns, 'function'));

  // Mtime
  const mtimeFns = [
    ['now', null, 'Current monotonic timestamp'],
    ['elapsed', null, 'Elapsed since program start'],
    ['span', null, 'Construct a span'],
    ['Span.zero', null, 'Zero span'],
    ['Span.one_nanosecond', null, 'One nanosecond'],
    ['Span.one_microsecond', null, 'One microsecond'],
    ['Span.one_millisecond', null, 'One millisecond'],
    ['Span.one_second', null, 'One second'],
    ['Span.one_minute', null, 'One minute'],
    ['Span.one_hour', null, 'One hour'],
    ['Span.one_day', null, 'One day'],
    ['Span.add', null, 'Add two spans'],
    ['Span.abs_diff', null, 'Absolute difference'],
    ['Span.compare', null, 'Compare spans'],
    ['Span.equal', null, 'Span equality'],
    ['Span.to_uint64_ns', null, 'Span as ns count'],
    ['Span.of_uint64_ns', null, 'Span from ns count'],
    ['Span.pp', null, 'Pretty-print a span'],
    ['Clock.now', null, 'Wall-clock now'],
    ['Clock.elapsed', null, 'Wall-clock elapsed'],
    ['Clock.count', null, 'Counter ticks'],
  ];
  s.addMany(members('Mtime', mtimeFns, 'function'));

  // Unix module
  const unixFns = [
    ['error_message', null, 'String for an Unix.error'],
    ['handle_unix_error', null, 'Run, printing Unix.error'],
    ['environment', null, 'Environment as array'],
    ['unsafe_environment', null, 'Raw environment access'],
    ['getenv', null, 'Read env variable'],
    ['putenv', null, 'Set env variable'],
    ['execv', null, 'execv (no PATH search)'],
    ['execve', null, 'execv with environment'],
    ['execvp', null, 'execvp (PATH search)'],
    ['execvpe', null, 'execvpe (PATH + env)'],
    ['fork', null, 'Fork the current process'],
    ['wait', null, 'Wait for any child'],
    ['waitpid', null, 'Wait for specific child'],
    ['system', null, 'Run a shell command'],
    ['getpid', null, 'Current process ID'],
    ['getppid', null, 'Parent process ID'],
    ['nice', null, 'Adjust scheduling priority'],
    ['stdin', null, 'Standard input file_descr'],
    ['stdout', null, 'Standard output file_descr'],
    ['stderr', null, 'Standard error file_descr'],
    ['openfile', null, 'Open a file'],
    ['close', null, 'Close a file_descr'],
    ['read', null, 'Read into bytes'],
    ['write', null, 'Write from bytes'],
    ['write_substring', null, 'Write substring of string'],
    ['single_write', null, 'Write up to count bytes'],
    ['lseek', null, 'Seek in a file_descr'],
    ['truncate', null, 'Truncate a file by name'],
    ['ftruncate', null, 'Truncate a file_descr'],
    ['stat', null, 'Stat a file by name'],
    ['lstat', null, 'lstat a file by name'],
    ['fstat', null, 'fstat a file_descr'],
    ['isatty', null, 'Is descriptor a TTY?'],
    ['unlink', null, 'Delete a file'],
    ['rename', null, 'Rename a file'],
    ['link', null, 'Create a hard link'],
    ['symlink', null, 'Create a symbolic link'],
    ['readlink', null, 'Read a symlink target'],
    ['mkdir', null, 'Create a directory'],
    ['rmdir', null, 'Remove an empty directory'],
    ['chdir', null, 'Change working directory'],
    ['getcwd', null, 'Current working directory'],
    ['chroot', null, 'Change root directory'],
    ['opendir', null, 'Open a directory stream'],
    ['readdir', null, 'Read directory entry'],
    ['rewinddir', null, 'Reset directory cursor'],
    ['closedir', null, 'Close directory stream'],
    ['pipe', null, 'Create a pipe pair'],
    ['mkfifo', null, 'Create a named pipe'],
    ['create_process', null, 'Spawn child process'],
    ['kill', null, 'Send signal to process'],
    ['sigprocmask', null, 'Manipulate signal mask'],
    ['sigsuspend', null, 'Atomically wait for signal'],
    ['sigpending', null, 'Pending signals'],
    ['pause', null, 'Wait for any signal'],
    ['sleep', null, 'Sleep seconds (block)'],
    ['sleepf', null, 'Sleep float seconds'],
    ['gettimeofday', null, 'Wall clock now'],
    ['time', null, 'Wall clock now (s)'],
    ['gmtime', null, 'Decoded UTC time'],
    ['localtime', null, 'Decoded local time'],
    ['mktime', null, 'Encode tm to seconds'],
    ['alarm', null, 'Schedule a SIGALRM'],
    ['select', null, 'Multiplex on FDs'],
    ['poll', null, 'POSIX poll on FDs'],
    ['lockf', null, 'Apply advisory lock'],
    ['set_close_on_exec', null, 'Set FD_CLOEXEC'],
    ['clear_close_on_exec', null, 'Clear FD_CLOEXEC'],
    ['set_nonblock', null, 'Set O_NONBLOCK'],
    ['clear_nonblock', null, 'Clear O_NONBLOCK'],
    ['umask', null, 'Set process umask'],
    ['chmod', null, 'Change file mode'],
    ['fchmod', null, 'Change mode by descriptor'],
    ['chown', null, 'Change ownership'],
    ['fchown', null, 'Change ownership by descriptor'],
    ['utimes', null, 'Set access/modify times'],
    ['access', null, 'Test file access bits'],
    ['dup', null, 'Duplicate a descriptor'],
    ['dup2', null, 'Duplicate to specific descriptor'],
    ['socket', null, 'Allocate a socket'],
    ['socketpair', null, 'Allocate connected socket pair'],
    ['bind', null, 'Bind socket to address'],
    ['listen', null, 'Listen on bound socket'],
    ['accept', null, 'Accept incoming connection'],
    ['connect', null, 'Connect to peer'],
    ['shutdown', null, 'Close one direction'],
    ['getsockname', null, 'Local socket address'],
    ['getpeername', null, 'Peer socket address'],
    ['recv', null, 'Receive bytes'],
    ['recvfrom', null, 'Receive bytes + sender'],
    ['send', null, 'Send bytes'],
    ['send_substring', null, 'Send substring'],
    ['sendto', null, 'Send bytes to address'],
    ['getsockopt', null, 'Get socket option'],
    ['setsockopt', null, 'Set socket option'],
    ['gethostbyname', null, 'Resolve a host name'],
    ['gethostbyaddr', null, 'Reverse-resolve address'],
    ['getaddrinfo', null, 'Resolve service + host'],
    ['getnameinfo', null, 'Resolve sockaddr to host/port'],
    ['inet_addr_of_string', null, 'Parse IPv4/IPv6 literal'],
    ['string_of_inet_addr', null, 'Format IP address'],
    ['Unix_error', null, 'Standard Unix error exception'],
    ['ADDR_INET', null, 'IPv4/IPv6 socket address'],
    ['ADDR_UNIX', null, 'Unix-domain socket address'],
    ['SOCK_STREAM', null, 'Stream socket type'],
    ['SOCK_DGRAM', null, 'Datagram socket type'],
    ['PF_INET', null, 'IPv4 protocol family'],
    ['PF_INET6', null, 'IPv6 protocol family'],
    ['PF_UNIX', null, 'Unix-domain protocol family'],
    ['O_RDONLY', null, 'Read-only open flag'],
    ['O_WRONLY', null, 'Write-only open flag'],
    ['O_RDWR', null, 'Read-write open flag'],
    ['O_NONBLOCK', null, 'Non-blocking open flag'],
    ['O_APPEND', null, 'Append open flag'],
    ['O_CREAT', null, 'Create open flag'],
    ['O_TRUNC', null, 'Truncate open flag'],
    ['O_EXCL', null, 'Exclusive open flag'],
    ['O_NOCTTY', null, 'No controlling tty flag'],
    ['O_DSYNC', null, 'Data sync flag'],
    ['O_SYNC', null, 'Sync flag'],
    ['O_RSYNC', null, 'Read sync flag'],
    ['O_CLOEXEC', null, 'Close-on-exec flag'],
  ];
  s.addMany(members('Unix', unixFns, 'function'));

  // Jane Street Core / Base
  const coreListFns = [
    'is_empty', 'length', 'hd', 'tl', 'hd_exn', 'tl_exn', 'last', 'last_exn',
    'nth', 'nth_exn', 'rev', 'rev_append', 'rev_map', 'rev_filter',
    'unordered_append', 'fold', 'foldi', 'fold_left', 'fold_right',
    'fold_until', 'fold_result', 'iter', 'iteri', 'map', 'mapi', 'concat_map',
    'filter_map', 'filter_mapi', 'filter', 'filteri', 'partition_tf',
    'partition_map', 'partition3_map', 'partition_result', 'init', 'find',
    'find_exn', 'find_map', 'find_map_exn', 'findi', 'find_mapi',
    'for_all', 'for_alli', 'exists', 'existsi', 'mem', 'count', 'counti',
    'min_elt', 'max_elt', 'sum', 'sort', 'stable_sort', 'sort_and_group',
    'group', 'all_equal', 'concat', 'append', 'unzip', 'unzip3', 'zip',
    'zip_exn', 'merge', 'dedup_and_sort', 'remove_consecutive_duplicates',
    'chunks_of', 'split_n', 'split_while', 'take', 'take_while', 'drop',
    'drop_while', 'cartesian_product', 'transpose', 'transpose_exn',
    'reduce', 'reduce_exn', 'reduce_balanced', 'random_element',
    'random_element_exn', 'permute', 'is_sorted', 'is_sorted_strictly',
    'cons', 'compare', 'equal', 'rev_filter_map', 'concat_no_order',
    'intersperse', 'rev_filteri', 'unfold', 'sub', 'fold_map',
  ];
  s.addBulk(coreListFns.map((n) => [`Core.List.${n}`, 'function', null, `Core.List.${n}`]));

  const coreMapFns = [
    'empty', 'singleton', 'of_alist', 'of_alist_exn', 'of_alist_or_error',
    'of_alist_multi', 'of_alist_reduce', 'of_iteri', 'of_increasing_iterator_unchecked',
    'of_sorted_array', 'of_sorted_array_unchecked', 'is_empty', 'length',
    'add', 'add_exn', 'set', 'add_multi', 'remove_multi', 'find_multi',
    'change', 'update', 'find', 'find_exn', 'remove', 'mem', 'iter',
    'iteri', 'iter_keys', 'fold', 'fold_right', 'fold2', 'filter',
    'filter_keys', 'filter_mapi', 'filter_map', 'partition_mapi',
    'partition_map', 'partition_tf', 'compare_direct', 'equal',
    'keys', 'data', 'to_alist', 'to_sequence', 'merge', 'merge_skewed',
    'symmetric_diff', 'fold_symmetric_diff', 'min_elt', 'min_elt_exn',
    'max_elt', 'max_elt_exn', 'fold_range_inclusive', 'range_to_alist',
    'closest_key', 'nth', 'rank', 'split', 'append', 'subrange',
    'count', 'counti', 'sum', 'find_mapi', 'for_all', 'for_alli',
    'exists', 'existsi', 'map', 'mapi', 'binary_search',
    'binary_search_segmented', 'comparator_s', 'comparator',
  ];
  s.addBulk(coreMapFns.map((n) => [`Core.Map.${n}`, 'function', null, `Core.Map.${n}`]));

  const coreSetFns = [
    'empty', 'singleton', 'union', 'union_list', 'inter', 'diff',
    'symmetric_diff', 'compare_direct', 'equal', 'is_subset', 'are_disjoint',
    'add', 'remove', 'mem', 'fold', 'fold_until', 'fold_right', 'iter',
    'iter2', 'filter', 'filter_map', 'partition_tf', 'min_elt', 'min_elt_exn',
    'max_elt', 'max_elt_exn', 'choose', 'choose_exn', 'split', 'group_by',
    'find', 'find_exn', 'find_map', 'find_map_exn', 'count', 'sum',
    'for_all', 'exists', 'to_list', 'to_array', 'to_sequence', 'of_list',
    'of_array', 'of_sequence', 'of_sorted_array', 'length', 'is_empty',
    'nth', 'rank', 'binary_search',
  ];
  s.addBulk(coreSetFns.map((n) => [`Core.Set.${n}`, 'function', null, `Core.Set.${n}`]));

  const coreHashtblFns = [
    'create', 'of_alist', 'of_alist_exn', 'of_alist_or_error',
    'of_alist_report_all_dups', 'add', 'add_exn', 'add_or_error',
    'set', 'change', 'update', 'find', 'find_exn', 'find_or_add',
    'find_and_call', 'findi_and_call', 'find_and_remove', 'remove',
    'mem', 'clear', 'copy', 'iter', 'iteri', 'iter_keys', 'iter_vals',
    'fold', 'filter', 'filter_keys', 'filter_inplace', 'map',
    'mapi', 'filter_map', 'filter_mapi', 'partition_tf',
    'partition_mapi', 'count', 'counti', 'length', 'is_empty',
    'keys', 'data', 'to_alist', 'merge', 'merge_into', 'choose',
    'choose_exn', 'choose_randomly', 'invariant', 'incr', 'decr',
    'add_multi', 'remove_multi', 'find_multi', 'sexp_of_t',
  ];
  s.addBulk(coreHashtblFns.map((n) => [`Core.Hashtbl.${n}`, 'function', null, `Core.Hashtbl.${n}`]));

  const coreSequenceFns = [
    'empty', 'singleton', 'of_list', 'to_list', 'of_array', 'to_array',
    'unfold', 'unfold_step', 'unfold_with', 'init', 'iter', 'iteri',
    'fold', 'foldi', 'fold_until', 'fold_result', 'map', 'mapi',
    'filter', 'filter_mapi', 'filter_map', 'concat_map', 'concat',
    'append', 'cons', 'cycle_list_exn', 'repeat', 'forever', 'take',
    'take_while', 'drop', 'drop_while', 'find', 'find_exn', 'find_map',
    'for_all', 'exists', 'count', 'min_elt', 'max_elt', 'is_empty',
    'length', 'mem', 'sub', 'split_n', 'split_while', 'group',
    'chunks_of', 'zip', 'zip_full', 'unzip', 'merge', 'next',
    'fold_m', 'iter_m', 'bind', 'return', 'memoize', 'force_eagerly',
  ];
  s.addBulk(coreSequenceFns.map((n) => [`Core.Sequence.${n}`, 'function', null, `Core.Sequence.${n}`]));

  const coreStringFns = [
    'length', 'is_empty', 'sub', 'subo', 'concat', 'concat_array',
    'concat_map', 'concat_mapi', 'init', 'split', 'split_lines',
    'split_on_chars', 'lsplit2', 'rsplit2', 'lsplit2_exn', 'rsplit2_exn',
    'is_prefix', 'is_suffix', 'chop_prefix', 'chop_suffix',
    'chop_prefix_exn', 'chop_suffix_exn', 'chop_prefix_if_exists',
    'chop_suffix_if_exists', 'lstrip', 'rstrip', 'strip', 'lowercase',
    'uppercase', 'capitalize', 'tr', 'tr_multi', 'filter', 'filteri',
    'iter', 'iteri', 'fold', 'foldi', 'find', 'find_map', 'index',
    'index_exn', 'rindex', 'rindex_exn', 'mem', 'count', 'counti',
    'for_all', 'exists', 'contains', 'common_prefix', 'common_suffix',
    'common_prefix2', 'common_suffix2', 'concat_lines', 'pad_left',
    'pad_right', 'partition', 'rev', 'to_list', 'to_array', 'of_list',
    'of_array', 'of_char_list', 'hash', 'compare', 'equal', 'substr_index',
    'substr_index_exn', 'substr_index_all', 'substr_replace_all',
    'substr_replace_first', 'is_substring', 'word_wrap',
  ];
  s.addBulk(coreStringFns.map((n) => [`Core.String.${n}`, 'function', null, `Core.String.${n}`]));

  const coreFloatFns = [
    'zero', 'one', 'minus_one', 'pi', 'e', 'sqrt_pi', 'sqrt_2pi',
    'sqrt2', 'ln_2', 'ln_10', 'log10_e', 'epsilon_float', 'is_nan',
    'is_inf', 'is_finite', 'is_integer', 'classify', 'sign_or_nan',
    'iround_nearest', 'iround_nearest_exn', 'iround_up', 'iround_up_exn',
    'iround_down', 'iround_down_exn', 'iround_zero', 'iround_zero_exn',
    'round_nearest', 'round_up', 'round_down', 'round_towards_zero',
    'round_decimal', 'round_significant', 'truncate', 'modf', 'frexp',
    'ldexp', 'add', 'sub', 'mul', 'div', 'neg', 'abs', 'min', 'max',
    'min_inan', 'max_inan', 'compare', 'equal', 'square', 'cube',
    'sqrt', 'cbrt', 'exp', 'exp2', 'exp10', 'log', 'log2', 'log10',
    'expm1', 'log1p', 'cos', 'sin', 'tan', 'cosh', 'sinh', 'tanh',
    'acos', 'asin', 'atan', 'atan2', 'acosh', 'asinh', 'atanh',
    'hypot', 'erf', 'erfc', 'lgamma', 'gamma', 'to_int', 'of_int',
    'to_string', 'of_string', 'to_padded_compact_string',
    'to_string_hum', 'sexp_of_t', 't_of_sexp',
  ];
  s.addBulk(coreFloatFns.map((n) => [`Core.Float.${n}`, 'function', null, `Core.Float.${n}`]));

  const coreTimeFns = [
    'now', 'epoch', 'add', 'sub', 'diff', 'abs_diff', 'is_earlier',
    'is_later', 'next_multiple', 'prev_multiple', 'occurrence',
    'to_date', 'of_date_ofday', 'to_string', 'of_string', 'to_string_iso8601',
    'of_string_iso8601', 'to_filename_string', 'of_filename_string',
    'to_string_abs', 'to_sec_string', 'to_string_trimmed',
    'pause_forever', 'pause', 'format', 'parse', 'compare', 'equal',
  ];
  s.addBulk(coreTimeFns.map((n) => [`Core.Time.${n}`, 'function', null, `Core.Time.${n}`]));

  const coreDateFns = [
    'create_exn', 'create_opt', 'today', 'add_days', 'sub_days',
    'add_months', 'add_years', 'add_business_days', 'diff', 'diff_weekdays',
    'diff_weekend_days', 'is_weekday', 'is_weekend', 'day_of_week',
    'day', 'month', 'year', 'first_strictly_after', 'last_strictly_before',
    'between', 'compare', 'equal', 'to_string', 'of_string',
    'to_string_iso8601_basic', 'of_string_iso8601_basic',
    'to_tuple', 'pp', 'sexp_of_t', 't_of_sexp', 'min_value', 'max_value',
    'next_business_day', 'previous_business_day',
  ];
  s.addBulk(coreDateFns.map((n) => [`Core.Date.${n}`, 'function', null, `Core.Date.${n}`]));

  s.addBulk([
    ['Core.Date.Day_of_week.Mon', 'constant', null, 'Monday'],
    ['Core.Date.Day_of_week.Tue', 'constant', null, 'Tuesday'],
    ['Core.Date.Day_of_week.Wed', 'constant', null, 'Wednesday'],
    ['Core.Date.Day_of_week.Thu', 'constant', null, 'Thursday'],
    ['Core.Date.Day_of_week.Fri', 'constant', null, 'Friday'],
    ['Core.Date.Day_of_week.Sat', 'constant', null, 'Saturday'],
    ['Core.Date.Day_of_week.Sun', 'constant', null, 'Sunday'],
    ['Core.Date.Day_of_week.of_string', 'function', null, 'Parse a weekday'],
    ['Core.Date.Day_of_week.to_string', 'function', null, 'Format a weekday'],
    ['Core.Date.Day_of_week.is_sun_or_sat', 'function', null, 'Weekend predicate'],
  ]);

  // Async.Deferred / Pipe / Reader / Writer
  const asyncDeferredFns = [
    'return', 'bind', 'map', 'all', 'all_unit', 'both', 'any',
    'any_unit', 'choose', 'never', 'unit', 'don_t_wait_for',
    'create', 'value_exn', 'peek', 'is_determined', 'upon',
    'ok', 'or_error', 'try_with', 'tavu', 'wait', 'forever',
    'with_timeout', 'List.iter', 'List.map', 'List.fold',
    'List.filter', 'List.filter_map', 'List.iteri', 'List.init',
    'Result.bind', 'Result.map', 'Or_error.bind', 'Or_error.map',
    'Or_error.try_with', 'Or_error.error', 'Or_error.return',
    'Or_error.ok', 'Sequence.iter', 'Array.iter', 'Map.iter',
  ];
  s.addBulk(asyncDeferredFns.map((n) => [`Async.Deferred.${n}`, 'function', null, `Async.Deferred.${n}`]));

  const asyncPipeFns = [
    'create', 'create_reader', 'create_writer', 'transfer',
    'transfer_id', 'iter', 'iter_without_pushback', 'fold',
    'map', 'filter', 'filter_map', 'concat_map', 'read', 'read_now',
    'read_choice', 'read_all', 'read_at_most', 'write', 'write_if_open',
    'write_without_pushback', 'pushback', 'closed', 'close', 'close_read',
    'is_closed', 'length', 'peek', 'to_list', 'of_list', 'singleton',
    'empty', 'fork', 'unfold', 'init', 'merge', 'interleave',
  ];
  s.addBulk(asyncPipeFns.map((n) => [`Async.Pipe.${n}`, 'function', null, `Async.Pipe.${n}`]));

  const asyncReaderFns = [
    'create', 'open_file', 'with_file', 'stdin', 'read_line', 'read_lines',
    'read_until', 'read_one_chunk_at_a_time', 'lseek', 'close', 'is_closed',
    'fd', 'pipe', 'transfer', 'contents', 'file_contents', 'file_lines',
    'load_sexp', 'load_sexps', 'load_bin_prot',
  ];
  s.addBulk(asyncReaderFns.map((n) => [`Async.Reader.${n}`, 'function', null, `Async.Reader.${n}`]));

  const asyncWriterFns = [
    'create', 'open_file', 'with_file', 'stdout', 'stderr', 'write',
    'write_line', 'writef', 'write_char', 'write_substring', 'write_bytes',
    'flushed', 'flushed_or_failed_unit', 'close', 'fdatasync', 'fsync',
    'pipe', 'fd', 'is_closed', 'newline', 'write_sexp', 'save_sexp',
    'save', 'save_lines', 'save_bin_prot',
  ];
  s.addBulk(asyncWriterFns.map((n) => [`Async.Writer.${n}`, 'function', null, `Async.Writer.${n}`]));

  return s.toArray();
}
